### ISSUE TITLE
sp_AllNightLog doesn't retry the first full restore if it fails

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1000]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
If sp_AllNightLog @Restore = 1 finds a new database, and tries to restore it from backup, and that restore fails because no file was found (like if there's a /databasename/full folder, but the backup file isn't there):

- No errors are thrown
- The magic time values in msdb.dbo.restore_worker are changed away from their 1900-01-01 00:00:00.000 and 9999-12-31 00:00:00.000 values, reflecting the time of the attempted restore
- That means the full restore is never tried again

**What is the expected behavior?**
It should retry the full restore on the next pass. (Not sure on implementation details yet regarding the error number column or start/finish time hacks.)

**Comment by BrentOzar** [comment]
Thinking through usage scenarios:

- First full restore fails
- Human beings decide we need to re-restore the full or diff for some reason (like log backups were taken out of band, and we need to leapfrog past them)
- Unknown (look, I started a bulleted list, and that looks stupid with only two scenarios)

So maybe add two columns to restore_worker:

- full_restore_required bit, default 0
- diff_restore_required bit, default 0

Code changes required:

- In sp_AllNightLog @PollDiskForNewDatabases = 1, when adding new databases, start with full_restore_required = 1
- In sp_AllNightLog @Restore = 1, in the restore loop, if a database's full_restore_required = 1, use the same logic we're currently using for the hard-coded magic numbers in the date/time fields.

**Comment by BlitzErik** [comment]
This is a case of the error handling in sp_DatabaseRestore being too good. 

Without altering code too much, we could have it return a status code to indicate restore success or failure, and have the retry logic based on that instead of catching errors?

**Comment by BrentOzar** [comment]
We're no longer actively using this ourselves in production, so closing the issue. If the folks using it in production wanna pursue it, they can check in their changes & move forward. I wouldn't wanna make further changes on this branch knowing that there are other active versions of the code out there.
