### ISSUE TITLE
autodisable the restoring job, source of truth

### ISSUE THREAD

**Issue by scorellis** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1004]
Please feel free to correct me if I am not understanding this correctly - 

It appears that it might be possible for the restoring job to run on the secondary, and that its source of truth is "if the backup job is running".  

I would prefer there to be a more centrally (and stable) source of truth, such as a flag in a table somewhere.  It is very conceivable that a dba will hut off a backup job for any number of maintenance reasons, and he may accidentally not realize which server he is on (when he comes back to turn it back on) and accidentally start the restoring job.  If anything, the jobs should be smart enough to disable itself it tries to run  on the wrong role.

**Comment by BrentOzar** [comment]
To summarize, you're worried about a scenario where:

* The server is a primary, with real end user data going in there
* The DBA chooses to shut off the backup jobs (which immediately violates our RPO/RTO anyway - elaborate with specific reasons about why this would need to happen)
* The DBA accidentally starts the restore jobs (which shouldn't be on a primary once we've done #988)

If the restore jobs aren't on the primary, is this still an issue?

**Comment by scorellis** [comment]
I may have to shut off the backup jobs if I have to perform some maintenance on the file servers. This would most likely be occurring during either a planned or an unplanned maintenance window, so RTO and RPO  would not enter into play here.  

If the restore jobs are not on the primary, there is no issue.

**Comment by BrentOzar** [comment]
Ooo, that's an interesting idea - do we want to add a secondary backup location and try that as a fallback? (It's totally a v2 thing but it's pretty compelling.)

**Comment by BrentOzar** [comment]
We discussed this one in person - the point of this project is to avoid having a single point of failure (which would be the source of truth). We'll stick with the job enable/disable setup for now.
