### ISSUE TITLE
sp_Blitz: Arithmetic overflow error for data type smallint

### ISSUE THREAD

**Issue by aharpervc** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1007]
**Do you want to request a *feature* or report a *bug*?**

This is a bug (probably)

**What is the current behavior?**

1) Compile sp_Blitz
2) Run `exec sp_Blitz`
3) Get normal result records, but also the error:
```
Msg 220, Level 16, State 1, Line 12
Arithmetic overflow error for data type smallint, value = 34473.
```

**What is the expected behavior?**

I expected it to execute without any errors.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

sp_Blitz: 5.5 20170701

SQL Server: Microsoft SQL Server 2016 (SP1-CU3) (KB4019916) - 13.0.4435.0 (X64)   Apr 27 2017 17:36:12   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) 

This is a new server & not sure about previous versions.

I asked about this in #firstresponderkit on slack, and additional things that have been tried include `exec sp_blitz @IgnorePrioritiesBelow=255` (3 informational records, but still that same error) and replacing the two instances of `smallint` with `int` in the body of the procedure (no change). I also ran the sp contents manually as a script to see if I could get a better line number, but SSMS just reports the first line of the script.

**Comment by BrentOzar** [comment]
Just to track what's happening - we'll do #1008 first to add a @Debug = 1 mode, and that'll help with this one.

**Comment by BlitzErik** [comment]
@aharpervc -- can you try the version of sp_Blitz in this [pull request](https://raw.githubusercontent.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/2d7e7b903cd8222b2d4855e2929628177fde0489/sp_Blitz.sql)? 

If you install that version and run this code, it should help us isolate which CheckId you're having a problem with:

`EXEC dbo.sp_Blitz @CheckUserDatabaseObjects = 1, @CheckServerInfo = 1, @Debug = 1`

**Comment by aharpervc** [comment]
It is functional, and produces diagnostic logging. However- bad news. The server that gave the error has now been moved into production and no longer exhibits the error, even with the version of sp_Blitz described in the OP. So unfortunately this is not replicating any more.

**Comment by BlitzErik** [comment]
@aharpervc Hahaha, well, doesn't that just figure. If it pops up again, give us a holler here or on Slack. Gonna close this out for now, since we don't really stand a chance of tracking it down.

Thanks!
