### ISSUE TITLE
sp_AllNightLog_setup - Check to ensure jobs are stopping

### ISSUE THREAD

**Issue by jstanford-kcura** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1010]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Calling `sp_AllNightLog_setup @EnableRestoreJobs = 0` will disable the jobs, and immediately return.

Any instance of the job which was in the process of running will continue, so the caller is required to poll for the status of the job before doing any further operations which may interact with it, such as attempting to restore databases WITH RECOVERY.

**What is the expected behavior?**
Ideally, the procedure should poll to ensure the jobs have actually been disabled.  If after some period of time the jobs are still running, an error should be returned to the caller.

**Comment by BrentOzar** [comment]
Coded, in dev branch now.

If you look at the changes via code diff, it doesn't quite tell the full story - I flipped the status changes on the restore jobs so that they go first. I wanted to make sure the disabled restore jobs finished before the backup jobs were enabled.
