### ISSUE TITLE
sp_AllNightLog_Setup - "'@jobs' has already been declared."

### ISSUE THREAD

**Issue by jstanford-kcura** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1014]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When running the setup script for sp_AllNightLog_Setup, the following error is generated:
`The variable name '@jobs' has already been declared. Variable names must be unique within a query batch or stored procedure.`

Root cause appears to be the new table variable named @jobs and the parameter named @jobs

**What is the expected behavior?**
The ALTER PROCEDURE command should complete successfully.

**Comment by BrentOzar** [comment]
Hahaha, sorry about that, fixed.
