### ISSUE TITLE
sp_BlitzWho - Feature request

### ISSUE THREAD

**Issue by CharlieMouse** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1021]
I'm not sure if sp_BlitzWho is looking to replace/replicate features from sp_whoisactive, but there is one addition that i think would be really good.

Percent_complete column : This one is super simple just to include an extra column in the select, the source table is already used in the joins. It is really useful to check the progress of backup, restores and index rebuilds. I'm aware that this might be a breaking change for anyone who capturing the returned dataset into a temporaty table like i am.  `INSERT INTO #Blitz EXEC master.dbo.sp_BlitzWho` into a temporary table, like i am

heres the simple addition

`CASE 
		WHEN r.percent_complete <> 0
			THEN r.percent_complete
		ELSE NULL
		END AS percent_complete`

Thank you for taking the time to read this. I hope its not a duplicate

**Comment by BrentOzar** [comment]
Hi, Brent here. Thanks for the idea! First, when you're suggesting stuff, try to separate each idea into its own Github issue. They may progress at different speeds, or different people may contribute code to different ideas.

I'm going to edit your request and just have this one focus on percent_complete. For the deltas, go ahead and create a separate issue, and can you explain more about what you're looking for there? Thanks!

**Comment by CharlieMouse** [comment]
"long time listener first time caller"

Thanks for being gentle. I will spend more time exploring the capabilities of BlitzFirst to see if our use case for using `sp_whoisactive @delta_interval = 10` is already covered by BlitzFirst

**Comment by CharlieMouse** [comment]
By the way, im happy to complete the work and submit the pull request if needed. Would just need guidance on whether you'd like it as a optional parameter. Thanks
