### ISSUE TITLE
BlitzWho SQLAgentJob <-> Program Name - Enhancement

### ISSUE THREAD

**Issue by CharlieMouse** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1024]
Hello 

We have around 100 SQL agent jobs running on some servers and these jobs can often have many steps.

These batch type processes often get highlighted as requiring further attention. The only way i know i have discovered to trace a process back to the underlying SQL Agent Step is to use the program_name column. Normally this returns something like

`SQLAgent - TSQL JobStep (Job 0xDF2333534C88EF4CAC8B31B02ACE19FF : Step 1)`

Many years ago i found a code snippet that joins the hex string back to the MSDN job table so i can see the jobName and JobStepName , which is much more useful

Here is the hack

`LEFT JOIN msdb..sysjobs J ON S.program_name LIKE 'SQLAgent - TSQL JobStep (Job ' + master.dbo.fn_varbintohexstr(convert(BINARY (16), J.job_id)) + '%'
LEFT JOIN msdb..sysjobsteps JS ON js.job_id = j.job_id`

**Comment by BlitzErik** [comment]
Oh dear, joining on a like with a function. That's interesting.

If you're planning on coding this, that's fine. But I'd only accept the code with a `@CheckAgentJobName` flag that only does this join if it's set to 1. This is a no-go for me in a rather large query that can get dragged down.

Let me know if you plan on coding this. If not, I'll leave it open with a `help wanted` flag for 30 days.

Thanks!

**Comment by CharlieMouse** [comment]
I have completed the enhancement, including factoring out the like join with function and included the parameter, however following the [GitHub contributing Steps](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md) I get the following error when executing `git push origin Blitz_1024`

`remote: Permission to BrentOzarULTD/SQL-Server-First-Responder-Kit.git denied to CharlieMouse.
fatal: unable to access 'https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit.git/': The requested URL returned error: 403`

Sorry new to open source, new to Git , but enjoying the pleasure from contributing

**Comment by BlitzErik** [comment]
Hey there,

If you haven't made any progress with the Pull Request, check our Brent's post for more help.

https://www.brentozar.com/archive/2017/06/ola-hallengrens-maintenance-scripts-now-github/

Thanks!

**Comment by BrentOzar** [comment]
Closing this, but if you do want to contribute it, feel free to reopen once you've got the pull request thing down. Thanks!
