### ISSUE TITLE
sp_BlitzCache and sp_BlitzQueryStore -- Do we want more support for cursor plans?

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1027]
We offer limited support for parsing cursor plans to look for optimistic, and non-forward only cursors.

[Dynamic and Fast Forward](https://blogs.msdn.microsoft.com/psssql/2013/08/28/sql-2012-query-plan-enhancement-i-want-to-know-why-my-query-is-not-parallelized/) cursors inhibit parallelism. 

We can get the cursor reason here:

![image](https://user-images.githubusercontent.com/11590415/28213399-ec2149f2-6873-11e7-900b-6395155bcc3f.png)

Or do the standard check, just under the `StmtCursor` 

![image](https://user-images.githubusercontent.com/11590415/28213438-0afd8a3e-6874-11e7-8362-914c4f146d7b.png)

Assuming we even want this at all.

**Comment by BlitzErik** [comment]
Thinking this through a little bit, what if we just replace StmtCusor with StmtSimple in the plan xml? We'd only do this in the temp table for parsing, so the stuff we display from the global temp table wouldn't be altered. It would seem that all the checks we do on regular plan xml would then run on cursor plans too, without having to run a whole second set of checks or anything. Might have to look at if sql handle or whatever still works to link things together.

**Comment by BrentOzar** [comment]
That's genius!

**Comment by BlitzErik** [comment]
Well, maybe. It could also be very slow. I don't think [replace value of](https://docs.microsoft.com/en-us/sql/t-sql/xml/replace-value-of-xml-dml) works on `/nodes/`, only `@values`. So it'd be running `REPLACE(xmlcol, 'StmtCursor', 'StmtSimple') on XML :'(

**Comment by BlitzErik** [comment]
Ugh, yeah `Msg 2356, Level 16, State 1, Line 36
XQuery [T.x.modify()]: The target of 'replace value of' must be a non-metadata attribute or an element with simple typed content, found 'element(Features,xdt:untyped) ?'`
