### ISSUE TITLE
sp_Blitz File '' either does not exist or is not a recognizable trace file

### ISSUE THREAD

**Issue by watheypr** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1036]
**Do you want to request a *feature* or report a *bug*?**
If you're reporting a bug, include the version number of the script you're using. If it's not the current version, upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build.
Bug current version

**What is the current behavior?**
EXEC [dbo].[sp_Blitz]
    @CheckUserDatabaseObjects = 1 ,
    @CheckProcedureCache = 0 ,
    @OutputType = 'TABLE' ,
    @OutputProcedureCache = 0 ,
    @CheckProcedureCacheFilter = NULL,
    @CheckServerInfo = 1,
	@IgnorePrioritiesAbove = 50
Msg 567, Level 16, State 5, Procedure sp_Blitz, Line 10758
File '' either does not exist or is not a recognizable trace file. Or there was an error opening the file.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

**What is the expected behavior?**

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Microsoft Windows NT 6.0 (6002)
Microsoft SQL Server Standard Edition (64-bit)
10.0.2789.0

**Comment by watheypr** [comment]
Is there a switch to exclude the trace file checking completely for now - so at least I get the other warnings/errors?

**Comment by BlitzErik** [comment]
This is [fixed](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/962) in the dev branch. 

As a side note, it's time to [patch your SQL Server](https://sqlserverupdates.com/). 2789 was released in July, 2010, and has been completely out of Microsoft support for quite some time.
