### ISSUE TITLE
sp_Blitz: DBCC command check should skip monitoring tools

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1041]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
If you use Idera SQL DM, the check for DBCC commands run by users alerts that thousands of commands have been run.

**What is the expected behavior?**
Let's skip where application_name like any of these:

- Critical Care(R) Collector
- Red Gate Software Ltd SQL Prompt
- Spotlight Diagnostic Server
- SQL Diagnostic Manager

**Comment by BrentOzar** [comment]
[dbcc_stuff.xlsx](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/1162106/dbcc_stuff.xlsx)

Attached - example from client with logins & servers stripped out.

**Comment by dbaWJW** [comment]
Please consider excluding application name "SQL Monitor - Monitoring", which is RedGate SQL Monitor, in the sp_Blitz section pertaining to Overall count of DBCC events.   Would need this added criteria added as I see it for my install:

   AND  d.application_name NOT LIKE '%SQL Monitor - Monitoring%'

**Comment by BlitzErik** [comment]
@dbaWJW can you open a new issue for this?
