### ISSUE TITLE
sp_BlitzIndex false duplicate keys alert

### ISSUE THREAD

**Issue by VasylPavuk** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1048]
**Bug**
Version: 5.5 VersionDate:  '20170701'

Finding produced "Multiple Index Personalities: Duplicate keys" (@Mode = 4) for indexes that have same index keys but different index filters.

![image](https://user-images.githubusercontent.com/30172092/28570230-fd228ca4-7145-11e7-85f3-f622aa6238ec.png)

**Comment by BrentOzar** [comment]
Oh wow, never seen someone do that before. Is there a reason you don't do a single filtered index with both 1 & 2?

**Comment by BlitzErik** [comment]
This (to me) falls into the same category as duplicate key indexes that have different included columns. It's

**Comment by VasylPavuk** [comment]
There is no sense to use both because there are just 2 available values for column SavedFilterAlertFrequencyId (1,2)

My recomendation (as DBA) is to split the table to 2 tables (SavedFilterAlert_Scheduled,
SavedFilterAlert_Immediate) refused from developers because this table helds one entity :).

But these indexes used for many seeks & scans, and there are 2 procedures works very often
(1-st procedure uses predicate "SavedFilterAlertFrequencyId=1", and 2-nd uses "SavedFilterAlertFrequencyId = 2").
There are no much data for now, but I want to be ready to perform fast in case there will much more data.
![image](https://user-images.githubusercontent.com/30172092/28572657-9b22da3a-7150-11e7-827f-53c8cf76e864.png)

**Comment by BrentOzar** [comment]
OK, if there's only 2 possible values, then we'd probably suggest doing one index on the table. You can put multiple fields on an index - like indexing on Id and SavedFilterAlertFrequencyId. Closing.
