### ISSUE TITLE
A version for Azure SQL Database would be very welcome

### ISSUE THREAD

**Issue by m60freeman** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1052]
Sadly, Azure SQL Database is missing some of the DMVs that the procedures in the First Responder Kit rely upon. However, most of the code is still usable and useful.

**Comment by BrentOzar** [comment]
Yeah, that isn't something we're pursuing at this time. You're welcome to work on it if you want - you would want to do dynamic version detection at the top of the proc, and then enable/disable checks as you went. It's not a small amount of work. If you want to pursue it, I'd focus on the one stored proc you want the most, and work from there.

I'm going to close this issue for now, but if you do want to pursue it, continue the conversation here with the script you'd be most interested in working on.
