### ISSUE TITLE
sp_Blitz Backup Findings Group Backup

### ISSUE THREAD

**Issue by decompiled** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1053]
sp_Blitz Aug  1 2017 12:00AM

The Findings Group for Backup reports both 'MSDB Backup History not Purged' and 'MSDB Backup History Purged Too Frequently'.

SQL 2008R2 SP3 on 2008R2 Server.

The cleanup job for this particular server is weekly.

**Comment by BlitzErik** [comment]
Can you paste the results from Blitz for these two lines, as well? Trying to get an idea of the dates that are being grabbed.

**Comment by decompiled** [comment]
200	Backup	MSDB Backup History Not Purged	msdb	https://BrentOzar.com/go/history	Database backup history retained back to Jul  1 2017  1:45AM	NULL	NULL	3

200	Backup	MSDB Backup History Purged Too Frequently	msdb	https://BrentOzar.com/go/history	Database backup history only retained back to Jul  1 2017  1:45AM	NULL	NULL	186

**Comment by decompiled** [comment]
Just wanted to clarify that rolling back the sp_Blitz to the previous version sp_Blitz Jun  3 2017 resolves the issue for me.

**Comment by BrentOzar** [comment]
I know this is going to sound crazy, but can you try this:

```
SELECT TOP 1 backup_start_date,
DATEADD(dd, -60, GETDATE()) sixty_days_ago,
GETDATE() AS rightnow
FROM msdb.dbo.backupset ORDER BY 1
```

**Comment by decompiled** [comment]
![image](https://user-images.githubusercontent.com/177521/28877683-1462d38a-776b-11e7-9154-26b7e6ca6abc.png)

**Comment by BlitzErik** [comment]
Out of curiousity, if you diff the previous and current versions (I'm asking you to do this locally, because it may be different than what I have), can you spot any code differences  in the areas you've opened up issues for? If you don't have a tool that can diff files, I'd recommend [kdiff3](http://kdiff3.sourceforge.net/).

**Comment by BrentOzar** [comment]
Okay, now I'm really stumped - try running this query:

```
IF DATEADD(dd, -60, GETDATE()) > (SELECT TOP 1 backup_start_date FROM msdb.dbo.backupset ORDER BY 1)
SELECT 'Not purging'
ELSE
SELECT 'Everything is OK'
```

If you get "Everything is OK", then somehow you've got a bogus version of sp_Blitz. Can you re-download it from Github here or from our site, and try again?

**Comment by BrentOzar** [comment]
OOO! Erik narrowed down the bug. Nice find! If you can email me at help@brentozar.com with your email address, I'd love to give you a free Everything Bundle to say thanks for being so patient in reporting this. Great catch.

**Comment by decompiled** [comment]
@BlitzErik @BrentOzar Glad you found it!  I'll send in an email (thank you).  You guys are awesome and thank you for all the hard work and great training materials.  Hope to meet you some day at an event.  You are a great asset to the SQL community.

**Comment by decompiled** [comment]
@BlitzErik the updated script resolves this issue.
