### ISSUE TITLE
sp_Blitz FindingsGroup Monitoring

### ISSUE THREAD

**Issue by decompiled** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1054]
sp_Blitz Aug  1 2017 12:00AM

The FindingsGroup Monitoring reports that no monitoring is occurring.  Previous versions of script did not report this error on a server where monitors are setup and configured to alert.
Monitoring	Alerts Configured without Follow Up
Monitoring	No Alerts for Corruption
Monitoring	No Alerts for Sev 19-25
Monitoring	No Operators Configured/Enabled
Monitoring	Not All Alerts Configured

2008R2 SP3 on 2008R2 Server

**Comment by BlitzErik** [comment]
Can you post a screen cap of the expanded Alerts node under Agent?

![image](https://user-images.githubusercontent.com/11590415/28876786-588cf20a-7768-11e7-920c-93497f81066d.png)

**Comment by decompiled** [comment]
![image](https://user-images.githubusercontent.com/177521/28876936-d7a31eb6-7768-11e7-89b4-07b55f1e7315.png)

**Comment by BlitzErik** [comment]
These are both great catches. We're missing some `BEGIN`s and `END`s in the proc where the first thing to fire after some `IF`s is the new Debug info. We'll be working on a release to fix things.

**Comment by decompiled** [comment]
@BlitzErik Glad you found it!  You are a great asset to the SQL community.  Thanks for the work!

**Comment by BlitzErik** [comment]
Howdy sir!

Would you mind testing the version of Blitz here: https://raw.githubusercontent.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/c34428174e2509a8156cc1e5427a19681ae44231/sp_Blitz.sql

**Comment by decompiled** [comment]
No issues to report with the version you linked.  It picked up the existence of all the monitoring jobs as expected!  Thank you Sir!

**Comment by BlitzErik** [comment]
Woohoo! Thanks!
