### ISSUE TITLE
sp_Blitz v5.6 incorrectly shows missing Agent alerts 16-25 and 823-825

### ISSUE THREAD

**Issue by tpetersmcit** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1057]
**Do you want to request a *feature* or report a *bug*?**
Bug: Version 5.6, 20170801

**What is the current behavior?**
The following Findings|Check ID shows up in v5.6.

Alerts Configured   without Follow Up | 59
No Alerts for Corruption | 96
No Operators Configured/Enabled | 31
Not All Alerts Configured | 30

They did not show up in v5.5 and the correct records shows up when manually running

SELECT  *
FROM    msdb.dbo.sysalerts
WHERE   severity BETWEEN 19 AND 25 

SELECT  *
FROM    msdb.dbo.sysalerts
WHERE   message_id IN ( 823, 824, 825 ) 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

![blitz results](https://user-images.githubusercontent.com/5817634/28899390-931b78f6-779f-11e7-8b02-add6b17b4702.GIF)
![alerts 19-25](https://user-images.githubusercontent.com/5817634/28899389-931980dc-779f-11e7-8e9a-c4415b91a6fb.GIF)
![alerts 823-825](https://user-images.githubusercontent.com/5817634/28899391-931d633c-779f-11e7-9f00-83df5ccf3321.GIF)

**What is the expected behavior?**
No results in sp_Blitz for missing alerts

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
10.50.6000.34, Server 2008 R2
13.0.4422.0, Server 2012
Worked in sp_Blitz v5.5

**Comment by BlitzErik** [comment]
Thanks Tim, but please search for issues before opening them.

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/1054

There's already a fix for this one in the dev branch.

Thanks!

**Comment by tpetersmcit** [comment]
Sorry, missed that when I searched on open issues.
Thanks!
