### ISSUE TITLE
sp_Blitz.sql RAISERROR('Running CheckId [%d].') logging implemented inconsistently.

### ISSUE THREAD

**Issue by philipthatcher** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1061]
The sp_Blitz.sql source has been instrumented with RAISERROR('Running CheckId [%d].') lines such as 
`IF @Debug IN (1, 2) RAISERROR('Running CheckId [%d].', 0, 1, nnn) WITH NOWAIT;`

I suspect this is to log coverage for regression testing.  However, at present this is implemented inconsistently.  Some instances accurately record that the check has been performed, while other instances record that the check was performed _only_ if the check produces any output.  This looks to be inconsistent and incorrect.

**Comment by BlitzErik** [comment]
It's intended to show people which check is currently running. If the check isn't going to run, why would we want output? Don't mean to argue, just curious what your reasoning is here. 

Maybe it would help if you provided a couple examples of places where you feel it's inconsistent.

Thanks!

**Comment by philipthatcher** [comment]
> If the check isn't going to run, why would we want output? Don't mean to argue, just curious what your reasoning is here.


You've misunderstood me here.  There are cases where a check **is** being run, but as it's a 'pass' and no warning is output, the fact the check has been performed at all is not logged by the RAISERROR line.

Knowing definitely that a check has been run is reassuring, regardless of whether any warning was warranted.  This allows you to verify that the checks you're expecting are actually being run..

e.g.  from the sp_Blitz.sql source:
```
				IF NOT EXISTS ( SELECT  1
								FROM    #SkipChecks
								WHERE   DatabaseName IS NULL AND CheckID = 3 )
					BEGIN
						IF DATEADD(dd, -60, GETDATE()) > (SELECT TOP 1 backup_start_date FROM msdb.dbo.backupset ORDER BY 1)

						BEGIN

						IF @Debug IN (1, 2) RAISERROR('Running CheckId [%d].', 0, 1, 3) WITH NOWAIT;

						INSERT  INTO #BlitzResults
								( CheckID ,
								  DatabaseName ,
								  Priority ,
								  FindingsGroup ,
								  Finding ,
								  URL ,
								  Details
								)
								SELECT TOP 1
										3 AS CheckID ,
										'msdb' ,
										200 AS Priority ,
										'Backup' AS FindingsGroup ,
										'MSDB Backup History Not Purged' AS Finding ,
										'https://BrentOzar.com/go/history' AS URL ,
										( 'Database backup history retained back to '
										  + CAST(bs.backup_start_date AS VARCHAR(20)) ) AS Details
								FROM    msdb.dbo.backupset bs
								ORDER BY backup_set_id ASC;
						END;
					END;

```
should read
```
				IF NOT EXISTS ( SELECT  1
								FROM    #SkipChecks
								WHERE   DatabaseName IS NULL AND CheckID = 3 )
					BEGIN
						IF @Debug IN (1, 2) RAISERROR('Running CheckId [%d].', 0, 1, 3) WITH NOWAIT;

						IF DATEADD(dd, -60, GETDATE()) > (SELECT TOP 1 backup_start_date FROM msdb.dbo.backupset ORDER BY 1)

						BEGIN

						INSERT  INTO #BlitzResults
								( CheckID ,
								  DatabaseName ,
								  Priority ,
								  FindingsGroup ,
								  Finding ,
								  URL ,
								  Details
								)
								SELECT TOP 1
										3 AS CheckID ,
										'msdb' ,
										200 AS Priority ,
										'Backup' AS FindingsGroup ,
										'MSDB Backup History Not Purged' AS Finding ,
										'https://BrentOzar.com/go/history' AS URL ,
										( 'Database backup history retained back to '
										  + CAST(bs.backup_start_date AS VARCHAR(20)) ) AS Details
								FROM    msdb.dbo.backupset bs
								ORDER BY backup_set_id ASC;
						END;
					END;

```

**Comment by BlitzErik** [comment]
I see, but the way it's written is as-intended. 

Sorry about the confusion, and thanks again for the input.
