### ISSUE TITLE
sp_Blitz - undocumented DBCC events related to the replication marked as a finding

### ISSUE THREAD

**Issue by GrzegorzOpara** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1062]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Recently I found in the sp_Blitz output a new finding 'Overall Events' in 'DBCC Events' findings group:
`15278 DBCC events have taken place between Aug  8 2017 12:15AM and Aug  8 2017  8:17AM. This does not include CHECKDB and other usually benign DBCC events.
`
When I digged into this and checked the default trace, I found that every minute it records entries like this:
`
dbcc incrementinstance ("SQL Replication Distribution", "Dist:Delivered Cmds/sec", @agent_name, @new_delivered_commands)
`
`
dbcc setinstance ("SQL Replication Distribution", "Dist:Delivery Latency", @agent_name, @delivery_latency)
`
`
dbcc addinstance ("SQL Replication Logreader", @agent_name)
`
It's plainly visible this is replication related, but since these commands are undocumented I am not sure whether they should come up in the trace. However, basing purely on the output it just measures the amount of commands per seconds plus the latency. I think this is nothing harmful and this is a false-positive.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

**What is the expected behavior?**
If it's normal to see such commands (and I believe it is, but perhaps I would be good to cross check it on other server where the replication runs) in the default trace, perhaps it shouldn't be considered as a finding by sp_Blitz and it should be grouped with other harmless DBCC commands already excluded in sp_Blitz.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
- SQL Server 2016 SP1 CU3 (Microsoft SQL Server 2016 (SP1-CU3) (KB4019916) - 13.0.4435.0 (X64))
- Windows Server 2012 R2 (Microsoft Windows [Version 6.3.9600])

**Comment by BrentOzar** [comment]
Ooo, wow, yeah, great find. We'll exclude that from the alerts.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws
