### ISSUE TITLE
monitoring findings even if alerts are working

### ISSUE THREAD

**Issue by adalfa** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1063]
Hello to all
with latest version (sp_Blitz Aug  1 2017 12:00AM)
i get findings in monitoring (checkid 59,96,61,31,30) even if the alerts are configured and the notification are working properly

![sevalerts](https://user-images.githubusercontent.com/20990623/29215059-d46879c4-7ea9-11e7-878f-fc7fe1d5b537.jpeg)

a test with raiserror works fine

```
RaisError (N'An error occurred Severity 17: insufficient resources ! ', 17, 1)
 
With Log
 
Go
```

tried on  sql2016 (13.0.4446.0),sql 2012 (11.0.6607.3) and sql 2008 (10.0.6000.29) on window 2012 R2
with previous versions the issue is not occuring.

thanks.

andrea

**Comment by BrentOzar** [comment]
Thanks, but whenever you submit an issue, make sure to search the other issues first. This one was already reported and fixed. #1054
