### ISSUE TITLE
sp_AllNightLog: Use xp_dirtree instead of xp_cmdshell

### ISSUE THREAD

**Issue by briangithex** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1067]
Feature Request: If `xp_cmdshell `is disabled, give a warning during setup and use `xp_dirtree `instead.

E.g., `Insert into @table_variable exec xp_dirtree @restore_path_base,0,1`

Motivation: Some security auditors forbid the use of `xp_cmdshell`.

Note that, unlike `xp_cmdshell`, `xp_dirtree` is undocumented (hence why I suggest it as a failover, rather than a default).

SQL Versions: I believe `xp_dirtree` works even as far back as SQL 2000.

**Comment by BrentOzar** [comment]
Yeah, we're definitely not going to use something undocumented in here, sorry. If a security team isn't okay with cmdshell, then they really wouldn't be okay with undocumented features. Interesting idea, but no.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by briangithex** [comment]
The difference is that `xp_cmdshell` requires a configuration change, whereas `xp_dirtree` doesn't.

Though to be fair, anyone who can run `xp_cmdshell` could make that configuration change, so it's not an especially risky change...despite Microsoft explicitly calling dangerous.
