### ISSUE TITLE
sp_AllNightLog - UTC Or Similar TimeZone Awareness

### ISSUE THREAD

**Issue by DSQLJazzman** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1070]
**Do you want to request a *feature* or report a *bug*?**
This is a feature for now, but in a few months could be a Bug

**What is the current behavior?**
Think ahead, but could the tracking, auditing & calculations whether to do anything be based upon UTC rather than local or instance time? I am thinking ahead towards the Bi-Yearly Summer Time changes & what they will do. The configuration I am currently setting up has a Primary in PST & Secondary in EST, so October & April could see a few moments of fun as I understand the logic

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

**What is the expected behavior?**
Changing to UTC would avoid the Summer Time change fun points, as well as reflecting how the old fashion Vanilla Log Ship used to work, which I am guess was partly for this reason

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
This logic would impact all versions of SQL Server

**Comment by BrentOzar** [comment]
Sure, I agree, if you want to code this, thumbs up. Just refer to contributing.md to get started, and if you have questions, you can ask them here or in the Slack channel.

**Comment by BrentOzar** [comment]
@DSQLJazzman did you want to code this? If not, I'm going to close it.

**Comment by DSQLJazzman** [comment]
Hi Brent,

It something I would like to work on, at present it is juggling this with actually getting all the kinks in our Enterprise DR worked out. So not sure when I will be able to achieve the coding. 


Richard

**Comment by BlitzErik** [comment]
Howdy,

We haven't heard back from you on this in a while, so I'm going to close it out for now. If you decide to start working on it again, feel free to re-open the issue.

Thanks!
