### ISSUE TITLE
sp_AllNightLog - Diff Restore Logic Not Yet Live?

### ISSUE THREAD

**Issue by DSQLJazzman** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1071]
**Do you want to request a *feature* or report a *bug*?**
I would suggest this is either a Bug or a feature not yet implemented.

**What is the current behavior?**
Within the table restore_worker, there is a column diff_restore_required. I think this column was added following a separate request. But when I set this column to 1 & tried this logic, then checked the restorehistory nothing. I then re-read the sp_AllNightLog which does not appear to current have the Diff logic written.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

**What is the expected behavior?**
Ideally when then the column diff_restore_required has been used, the next run of the sp_AllNightLog will perform the diff restore.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
With the logic missing, I would suggest that this impacts all versions so far

**Comment by BrentOzar** [comment]
It’s a feature not yet implemented. You can close this issue. Thanks! For questions, you can also try the Slack channel in the documentation.


---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws
