### ISSUE TITLE
continuelogs parameter doesnt work correctly

### ISSUE THREAD

**Issue by cankaya07** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1072]
SqlCompare.sql i set @continuelogs to 0 but still apply logs file
SQL SERVER 2016 sp1

here is my parameter
exec [dbo].[sp_DatabaseRestore]
	  @Database  = 'ServiceDesk', 
	  @RestoreDatabaseName  = NULL, 
	  @BackupPathFull  = 'E:\ServiceDesk\FULL\', 
	  @BackupPathDiff  = 'E:\ServiceDesk\DIFF\', 
	  @BackupPathLog  = 'E:\ServiceDesk\LOG\',
	  @MoveFiles  = 1, 
	  @MoveDataDrive  = 'E:\DATA\', 
	  @MoveLogDrive  = 'E:\LOG\', 
	  @TestRestore  = 0, 
	  @RunCheckDB  = 0, 
	  @RestoreDiff  = 0,
	  @ContinueLogs  = 0, 
	  @RunRecovery  = 0, 
	  @StopAt  = NULL,
	  @OnlyLogsAfter  = NULL,
	  @Debug  = 0, 
	  @Help  = 0,
	  @VersionDate  = NULL  

**Do you want to request a *feature* or report a *bug*?**
If you're reporting a bug, include the version number of the script you're using. If it's not the current version, upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build.

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

**What is the expected behavior?**

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

**Comment by BrentOzar** [comment]
Brent here. Sorry, dumb question, but what are you trying to do? The combination of parameters you're using don't appear to be valid.

**Comment by cankaya07** [comment]
The combination of parameters you're using don't appear to be valid. why ? i just want to full restore thats it. should i set NULL value for diff and log variable ? i am using that stored procedure in the middle of some scripts

**Comment by BrentOzar** [comment]
If you only want to do full restores, check out sp_DatabaseRestore. This stored procedure is for log shipping. Closing.
