### ISSUE TITLE
Overall Events: DBCC Events - Exclude for DBCC SQLPERF (LOGSPACE) not working

### ISSUE THREAD

**Issue by martin-guth** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1074]
**Do you want to request a *feature* or report a *bug*?**

Bug for current dev-Version 5.6 (20170801)

**What is the current behavior?**

The check for "DBCC Events" (Check ID 199) returns results on two of my systems giving me the warning in sp_blitz output.

I checked the events found (SELECT DISTINCT dbcc_event_full_upper FROM #dbcc_events_from_traces With the WHERE-Condition from the current dev Version) and it appears that they are harmless:
"DBCC SQLPERF ( LOGSPACE )" issued by "Microsoft SQL Server Management Studio" presumably from the disk space report
"DBCC SQLPERF (LOGSPACE)" issued by "SQL Server Data Collector - Controller" (Management Data Warehouse)

It appears that the command is saved just the way it was typed in. 

**What is the expected behavior?**
The alert is not activated by SQLPERF LOGSPACE regardless how many spaces are within the command.
Possibly this could be solved by using "NOT LIKE"...here a quick test example:
`
WITH cteTest AS
	(
		SELECT *
		FROM ( VALUES 
			('DBCC SQLPERF ( LOGSPACE )'), 
			('DBCC SQLPERF (LOGSPACE)'), 
			('something else'), 
			('DBCC SQLPERF ( LOGSPACE  )')
			) AS a(dbcc_event_full_upper)
	)
SELECT
	dbcc_event_full_upper
FROM 
	cteTest
WHERE
	dbcc_event_full_upper NOT LIKE 'DBCC SQLPERF%LOGSPACE%)'
;`

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
 SQL 2008 SP4 and SQL 2014 SP2 CU 5
Previous versions had the same issues

**Comment by BrentOzar** [comment]
Makes sense!
