### ISSUE TITLE
Overall Events DBCC Events: Exclude DBCC ERRORLOG

### ISSUE THREAD

**Issue by martin-guth** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1075]
**Do you want to request a *feature* or report a *bug*?**

Feature for current dev-Version 5.6 (20170801)

**What is the current behavior?**

The check for "DBCC Events" (Check ID 199) returns results on two of my systems giving me the warning in sp_blitz output.

I checked the events found (SELECT DISTINCT dbcc_event_full_upper FROM #dbcc_events_from_traces With the WHERE-Condition from the current dev Version) and found "DBCC ERRORLOG"

This is the result of a daily agent job running on my systems which calls "sp_cycle_errorlog" in msdb to give me a fresh log every day. In my view this is quite harmless. Therefore it would be cool if "DBCC ERRORLOG" could be added to the ignore list.

**What is the expected behavior?**
Usage of DBCC ERRORLOG is ignored by sp_blitz

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
 SQL 2008 SP4 and SQL 2014 SP2 CU 5
Previous versions had the same issues

**Comment by BrentOzar** [comment]
Makes sense!
