### ISSUE TITLE
Sort #plans

### ISSUE THREAD

**Issue by ChrisWoods1977** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1083]
In sp_Blitz I get an alert for a large number of plans. The recommended fix is to run sp_blitzcache and look at the # of plans. It would be great to just have it automatically sort by that field rather than pull them all back and then sort.

**Comment by BrentOzar** [comment]
sp_BlitzCache doesn't have a way of aggregating by number of plans - it would require a pretty heavy series of changes. Instead, use the query from sp_BlitzCache's warning page about multiple plans: https://www.brentozar.com/blitzcache/multiple-plans/
