### ISSUE TITLE
sp_BlitzIndex throws error with ASCII control character in column name

### ISSUE THREAD

**Issue by tloehlein** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1086]
**Do you want to request a *feature* or report a *bug*?**
**BUG**
Script: sp_BlitzIndex
Version 5.6 - August 01, 2017

**What is the current behavior?**
sp_BlitzIndex throws following error, when there are 'invalid' XML characters in column names in the database:

Msg 6841, Level 16, State 1, Procedure sp_BlitzIndex, Line 1452 [Batch Start Line 0]
FOR XML could not serialize the data for node 'col_definition' because it contains a character (0x001F) which is not allowed in XML. To retrieve this data using FOR XML, convert it to binary, varbinary or image data type and use the BINARY BASE64 directive.

**What is the expected behavior?**
Either remove all ASCII control characters from the column_name of #IndexColumns. (Which I honestly failed, without using a list of all 32 possibilities)
Or maybe a warning about having this kind of probably not wanted characters in a column name, would be nice.

I just cleaned up the column name in my database. Thank you for finding this beauty ;)

Have a nice day!
Tom

**Comment by BrentOzar** [comment]
HAHAHA, wow, that's awesome (and I would kinda expect the same issue to pop up with database, table, and schema names.) I'd be okay with the full list of 'em embedded in the code if that's what it takes to get the job done.

Here's how I'd code it, although you're welcome to use another design if you can think of something better: during the insert from system tables into sp_BlitzIndex's temp tables, use a WHERE clause to exclude any objects with those control characters in it. Just flat out skip the analysis on them.

Then you could start a separate Github issue to add a warning for objects with those characters in the name. You don't have to code that part now if you don't want to - we could hold that til later for a separate issue.

If you don't want to code it, that's fine, just leave a note here and we'll close the issue. (It's so rare that we wouldn't code it - we'd just add it to the list of known issues.)

Thanks!

**Comment by tloehlein** [comment]
Hi Brent,

I have no clue how this got into the column in first place. 
I've tested a little bit and I actually failed to reproduce assigning a name with low ASCII codes to a column. But I've only tested it with SSMS and it has probably something to do with collation.
But I will test furthermore and try to make a bugfix for sp_BlitzIndex.

I would like to propose this to be a warning in sp_Blitz. 
I mean this issue could be in any kind of script you provide in your package.
And for sure, this is something a DBA should take a look for.

What do you think? I can open another issue for this.

Tom

**Comment by BrentOzar** [comment]
Well, lemme answer that with a question: if you have an index like that, does it hurt anything? Do you have to take any kind of action?

I try to focus sp_Blitz only on things that require attention, so I don't think it's really a good fit there unless I'm missing some kind of danger with the index. We'll steer clear of warning about naming conventions for now. ;-)

**Comment by tloehlein** [comment]
I don't think it has any kind of direct negative effect.

The only issue I see is, that these kind of 'illegal' characters can clearly generate some issues. 
And for me, this is not only about index. I mean things like messed up column names could possibly create a lot of issues.

I agree with the naming conventions, but I think this is not only a naming convention thing.

It will probably take a few days, till I will find some time to do further testing with a fix.
I guess I will be back working on this on Wednesday.

**Comment by BlitzErik** [comment]
Howdy,

Haven't heard back from you in a while on this, so I'm going to close the issue out. If you decide to work on it again in the future, feel free to reopen it.

Thanks!
