### ISSUE TITLE
sp_BlitzIndex not working with SQL Server 2005

### ISSUE THREAD

**Issue by tloehlein** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1088]
**Do you want to request a *feature* or report a *bug*?**
**BUG**

**What is the current behavior?**
Executing the sp_BlitzIndex.sql script fails on SQL Server 2005 with following error messages:
Msg 195, Level 15, State 10, Procedure sp_BlitzIndex, Line 1887 [Batch Start Line 13]
'SYSDATETIME' is not a recognized built-in function name.
Msg 195, Level 15, State 10, Procedure sp_BlitzIndex, Line 2905 [Batch Start Line 13]
'SYSDATETIME' is not a recognized built-in function name.
Msg 195, Level 15, State 10, Procedure sp_BlitzIndex, Line 4220 [Batch Start Line 13]
'SYSDATETIME' is not a recognized built-in function name.

**What is the expected behavior?**
That it works with SQL Server 2005 as mentioned at https://www.brentozar.com/blitzindex/sp_blitzindex-faq/
Regarding https://docs.microsoft.com/en-us/sql/t-sql/functions/sysdatetime-transact-sql , SYSDATETIME was introduced with SQL Server 2008.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Microsoft SQL Server 2005 - 9.00.5057.00 (X64)   Mar 25 2011 13:33:31
Compatibility Level: 90

**Possible fix**
Replace SYSDATETIME with GETDATE. 
I actually saw the usage of SYSDATETIME at the first time. 
After a bit researching, I don't think the lower precision is a deal breaker.

Have a nice day!
Tom

**Comment by BrentOzar** [comment]
None of our tools are supported on SQL Server 2005. Make sure to read the readme on the home page:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit

Closing.

**Comment by tloehlein** [comment]
Ok, I get it. 
Maybe just update the sp_BlitzIndex FAQ https://www.brentozar.com/blitzindex/sp_blitzindex-faq/
I was just looking there and it says: 
It is diagnose issues with indexes in databases running on SQL Server 2005 and higher.

Tom

**Comment by BrentOzar** [comment]
Ah, that page shouldn't even exist anymore, sorry about that. Deleted, closing.
