### ISSUE TITLE
sp_BlitzWho returns multiple records for some session IDs

### ISSUE THREAD

**Issue by nirst** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1089]
**Do you want to request a feature or report a bug?**
Bug
Script: sp_BlitzWho
Version 5.4 - June 05, 2017 onwards

**What is the current behavior?**
Since this version, sp_BlitzWho returns multiple records for some session IDs due to the cross apply to tempdb allocations. This returns multiple rows when sessions have multiple exec_context_ids in sys.dm_db_task_space_usage.

**What is the expected behavior?**
A single row per session - I don't think the cross apply is working as expected.

**SQL Version**
I've seen this issue on Microsoft SQL Server 2008 R2 (SP3) - 10.50.6220.0 (X64)

**Comment by BlitzErik** [comment]
Hello!

I haven't come across this. Can you add some more details to this the next time it happens? We don't join to exec context id, and we're already summing these values 

![image](https://user-images.githubusercontent.com/11590415/29923805-c4b9e52e-8e28-11e7-87bd-7bb232b58c2c.png)

I'm not calling you crazy, because we've run into multiple rows returned bugs in the past, just want to make sure i'm focusing on the right part of the code. 

If it's as simple as adding a `TOP 1` to the `CROSS APPLY` and you want to code and test it, feel free.

Thanks!

**Comment by nirst** [comment]
Nope - you're absolutely right. I'm definitely seeing multiple rows though and its only for sessions where there are multiple exec_context_ids but perhaps that was a red herring - I put 2 and 2 together based on the 5th June version being the first instance where this cropped up. I'll see if I can narrow it down further.

**Comment by nirst** [comment]
OK the issue seems to be on line 261:

![image](https://user-images.githubusercontent.com/7494942/29933986-6f82fee4-8e71-11e7-8bcd-fa1abba4b8fb.png)

The join creates multiple lines when a session has multiple records in task_space_usage (e.g. multiple exec_content_ids). Having found the issue I have no idea how to fix it...

**Comment by BlitzErik** [comment]
Hahaha, well the first thing is that left join shouldn't be there. 

All the information for that part for the query comes from here:

![image](https://user-images.githubusercontent.com/11590415/29934356-d06f3d0e-8e48-11e7-83a7-6735161f827f.png)


Up in the select list, we use the bits from the outer apply.

![image](https://user-images.githubusercontent.com/11590415/29934348-c3f81136-8e48-11e7-9e30-9158abdea708.png)

Lemme crank out a quick version for you to test.

**Comment by BlitzErik** [comment]
Alright, this is probably going to need a TOP 1 in it, but incremental changes are probably smart.

Can you test out the version here and let me know if anything is wonky?

https://raw.githubusercontent.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/933fa6a7343dd6cdc04ac5db5f97631d67e8ed1e/sp_BlitzWho.sql

**Comment by nirst** [comment]
Yep that worked a treat!

**Comment by BlitzErik** [comment]
Awesome! I'm going to leave this open in case you spot anything else, or in case anyone else comes along with the same issue. It will likely go into the next FRK release.

Thanks!
