### ISSUE TITLE
sp_BlitzFirst : Plan cache cleared recently timing issue

### ISSUE THREAD

**Issue by mikejwhitty** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1106]
In `sp_BlitzFirst`,  on the line (835 in master):

    IF DATEADD(mi, -15, SYSDATETIMEOFFSET()) < (SELECT TOP 1 creation_time FROM sys.dm_exec_query_stats ORDER BY creation_time)

Using SYSDATETIMEOFFSET() and comparing to the value in the DMV (which seems is stored just with the sysdatetime), will cause unintended results where the server isn't set to UTC (who does that, right?) of either never being true (if the offset is behind utc) or being true for longer than intended.

Tested in 2016, 2014 and 2012.

**Comment by mikejwhitty** [comment]
Master @RichBenner has identified many other places where the offset time is used and may not be giving intended results.

**Comment by BrentOzar** [comment]
Ooo, neato! @RichBenner - do you want to chime in?

**Comment by BrentOzar** [comment]
More details about the bug:

![1](https://user-images.githubusercontent.com/245462/30161688-3e1e08c8-9397-11e7-89ee-cd3ff649bf4a.png)

Repro script from the screenshot:

```
/* Get the most recent plan to see how creation_time is stored */
SELECT TOP 1 creation_time FROM sys.dm_exec_query_stats ORDER BY creation_time DESC;

/* Show a few different sources to choose from */
SELECT SYSDATETIME() AS sysdatetime, SYSDATETIMEOFFSET() AS sysdatetimeoffset, GETDATE() as getdate;
```

Based on that, it looks like this line:

```
    /* Query Problems - Plan Cache Erased Recently */
    IF DATEADD(mi, -15, SYSDATETIMEOFFSET()) < (SELECT TOP 1 creation_time FROM sys.dm_exec_query_stats ORDER BY creation_time)

```

Needs to be changed to:

```
    /* Query Problems - Plan Cache Erased Recently */
    IF DATEADD(mi, -15, SYSDATETIME()) < (SELECT TOP 1 creation_time FROM sys.dm_exec_query_stats ORDER BY creation_time)
```

Did I capture that right?

**Comment by RichBenner** [comment]
Yeah, i think that's the conclusion we came to in slack. I did notice 138 uses of the SYSDATETIMEOFFSET() command in BlitzFirst, Would it be best practice to deal with any of those that might need fixing at the same time as this one, or treat them as different issues?

**Comment by BrentOzar** [comment]
It'd make sense to tackle them in a single issue and pull request. I love you guys, but I can't deal with 138 one-line pull requests. :-D

If anyone wants to tackle this, leave a note to volunteer and I'll assign the issue to you - otherwise I'll leave it unassigned for now and we can tackle it later. Great catch!

**Comment by mikejwhitty** [comment]
I'll work through and change these and submit a pull request.

**Comment by BrentOzar** [comment]
Thanks sir!

**Comment by BrentOzar** [comment]
Hi guys! In preparation for doing our Summit pre-con, I wanted to get this knocked out. I only did the few checks that jumped out at me, but if anybody finds additional checks or stuff to change, probably best to start a new Github issue for those. Thanks though!
