### ISSUE TITLE
sp_BlitzFirst or sp_Blitz: add memory analysis

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1108]
(Low priority - just making an issue for myself to code this. Comments are totally welcome though.)

**Do you want to request a *feature* or report a *bug*?**
Feature (but not sure which script it makes more sense in just yet, and probably only with expert mode turned on)

**What is the expected behavior?**
I want the user to be able to answer questions like:

 - How much of max server memory am I using?
 - Out of that used memory, what's taking up space? (data pages, execution plans, query workspace, free, or something unusual)

In the initial release, I don't expect to have any guidance in here ("hey this looks odd") - just give us the ability to start collecting data and seeing trends with clients. So for now, just list the top 5-10 major memory consumers, and what percent & size of memory they've got right now.  Fastest way to get this is probably sys.dm_os_memory_clerks - I don't want to hit sys.dm_os_buffer_descriptors because it'd take forever.

**Comment by 619619** [comment]
I think it makes more sense in BlitzFirst, it would be interesting to track the memory usage of the server overtime with the dump to table feature and the PowerBI report, like a makeshift monitoring software

**Comment by BrentOzar** [comment]
@619619 well, you already get the usage over time with the Perfmon counters that are logged with the OutputTableNamePerfmonStats parameter.

**Comment by BrentOzar** [comment]
Did a quick design sketch-out, and realistically, I'm not going to do this anytime soon. I gotta stop adding tickets for myself to do more work, hahaha. Closing.
