### ISSUE TITLE
DBCC event counter does not ignore CHECKDB events

### ISSUE THREAD

**Issue by MarkHions** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1110]
**Do you want to request a *feature* or report a *bug*?**
This is a bug in Version = '5.7'; VersionDate = '20170901';

**What is the current behavior?**
Check 199, which looks for abnormal usage of DBCC, has traditionally ignored CHECKDB - and is documented as such in the output.  However, the WHERE clause that tosses out normal usage of DBCC is now missing the **d.dbcc_event_full_upper NOT LIKE '%DBCC%CHECKDB%'** code, and sp_blitz reports far more occurrences than normal.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
Just run sp_blitz and look for "--LargeNumber-- DBCC events have taken place between --x-- and --y--. This does not include CHECKDB and other usually benign DBCC events." in the first few rows of output.

**What is the expected behavior?**
The check should ignore DBCC CHECKDB events, as it used to.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All versions and OSs.  This used to work correctly.

**Comment by BrentOzar** [comment]
OK, cool! Do you want to contribute the code? (Just checking - some folks like to do that kind of thing.) If not, no worries.

**Comment by MarkHions** [comment]
Since reporting the bug is already stressing my githubian skills, no thank you.  Please make the change yourself.  Most of it is already in the "What is the current behavior?" section above.

**Comment by BrentOzar** [comment]
OK, great! Fixed.

(Mentioning this just in case you see that and you want to play with the new code - it's not been accepted by Erik into the main branch yet, so to see it, you'd need to go here:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/7e6f88ca9c0580fc87b0b079dd9c26f74e825382/sp_Blitz.sql
