### ISSUE TITLE
sp_DatabaseRestore

### ISSUE THREAD

**Issue by dtodd2016** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1114]
Not sure of the version of build number as sp_DatabaseRestore doesn't have those details in it.

There appears to be a bug in that 
execute dbo.sp_DatabaseRestore 
	@Database = 'somedatabase'
	, @RestoreDatabaseName = 'anotherdatabase'
	, @BackupPathFull = 'E:\SQLBackup\etc'
	, @BackupPathLog = 'E:\SQLBackup\etc'
	, @MoveFiles = 1 
	, @MoveDataDrive = 'D:\MSSQL2012\etc'
	, @MoveLogDrive  = 'D:\MSSQL2012\etc'
	, @ContinueLogs = 0
	, @RunRecovery = 1
;

appears to INCLUDE the transaction log backups in the restore, which is NOT what is expected or wanted.

Small feature request:
need to be able to rename the datafiles when restoring on the same server as the source database

**Comment by BrentOzar** [comment]
Howdy, and welcome to our Github repo!

First, if you pass in paths for the log backups, they'll be restored. I'm guessing you think @ContinueLogs = 0 means don't restore the logs, but that's not what it means. Scroll down the main page in this repo to read the documentation:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/

Second, whenever you have multiple things to discuss (like adding another feature request), that needs to be in its own issue. This is also covered in the documentation - and here's more details:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

The short answer on feature requests is that if you're going to code it, then you're absolutely welcome to make that issue request. Read that documentation on how that works. However, if you're thinking that someone else is going to code it for you, that's not the case. (Open source isn't free development work by others.) You're 100% welcome to code it, though! You can read that contributing.md to learn more about how that process works.

Thanks, and welcome to the community! Brent

**Comment by BlitzErik** [comment]
Not to pile on here, but that proc has had a version number and date since May. If you're using a version without that information, you should update. It's likely quite old. 

The ability to rename databases and file names on restore was added a while back, as well. 

Thanks!

**Comment by dtodd2016** [comment]
Hi,

 

I get the First Responders kit and haven’t seen an email to say that it's been updated for some time.

 

I rolled back to April since there was a small bug in the subsequent release. Given that I haven’t seen any notifications since I haven’t investigated for the last couple of months. Now my email provider has had quite a bit of spam for the last several months, so the notification emails may have been filtered on my end …

 

And being a production dba and not a developer, I’m treating the kit like a set, and not having different versions on the same machine. That could make life difficult for others who follow …

 

Regards

  David

**Comment by BrentOzar** [comment]
Ok, gotcha. You’ll want to check your spam or junk mail folders. If you have specific questions or actions you need us to take, let us know. Enjoy the free tools, and hope they help you do your job better.

**Comment by dtodd2016** [comment]
Hi Folks,

 

I downloaded Septembers release of the first responder kit – I appear to have only missed one version. The version info for sp_DatabaseRestore is in a different place in the code to other procedures.

And the fact that the logbackuppath is optional isn’t clear from the documentation.

Is it worthwhile adding the ability to specify the new filenames? Given that I’m restoring (and renaming) another database on this server, having the external filenames reflect the internal filenames means I have to restore to a subdirectory to avoid a filename clash.

 

Just some thoughts.

 

Regards

  David

**Comment by BrentOzar** [comment]
Thanks for the note, but this isn't how the support works for this project. For information about how to have discussions, head on over to the readme:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/tree/master

Thanks!

**Comment by BlitzErik** [comment]
David -- gonna say it again: you have the ability to rename files.

Search the code for `@RestoreDatabaseName`

**Comment by dtodd2016** [comment]
Hey man, you can say that all you want but it didn’t work!

 

I’m taking the backup of PWIN171 and restoring it as PWIN17V.

 

Here is my script.

execute dbo.sp_DatabaseRestore 

                @Database = 'PWIN171'

                , @RestoreDatabaseName = 'PWIN17V'

                , @BackupPathFull = 'E:\SQLBackup\ODC1DB0018\PWIN171\FULL\'

                --, @BackupPathLog = 'E:\SQLBackup\ODC1DB0018\PWIN171\LOG\'

                , @MoveFiles = 1 

                , @MoveDataDrive = 'D:\MSSQL2012\MSSQL11.MSSQLSERVER\MSSQL\DATA\PWIN17V\'

                , @MoveLogDrive  = 'D:\MSSQL2012\MSSQL11.MSSQLSERVER\MSSQL\DATA\PWIN17V\'

                , @ContinueLogs = 0

                , @RunRecovery = 1

;

 

This is the subfolder I felt I had to create and note the files are named exactly the same as the source database files.



 

Regards

  David

**Comment by dtodd2016** [comment]
Hey, 

 

Each time I try to raise an issue in GitHub I get shut down and shouted out.

 

The quality of the interactions since the first responders kit went to open-source have deteriorated markedly. It is like Brent Ozar doesn’t care about it anymore, even if his name is on it.

 

Regards

  David

**Comment by BrentOzar** [comment]
@dtodd2016 howdy sir. You're right: my responses here are getting pretty rough because you're not doing what I've repeatedly asked you to do. Go here and read the readme:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit

Scroll down, and read carefully the section on "How to Get Support."

Github issues are for code contributions. I know the name is a little confusing - "issue" makes it sound like it's for personalized support - but not all open source projects use it that way. We work really hard to be explicitly clear about how we handle support. If you'd like free help from the community, folks like me and Erik are waiting to help - but you need to read the guidelines on how to get support.

The reason you're getting shouted out is that you're not reading those instructions. Read those, and you'll be surprised at how much better your experience is.

**Comment by dtodd2016** [comment]
Dear Brent,

 

How about you ring me to clear the air – there appears to have been some miscommunications on both sides. 

 

Regards

  David

 

 

---------------------------------

David Todd

e-mail:          <mailto:d.todd@clear.net.nz> d.todd@clear.net.nz

mobile:         +64-21-623 377

home:           +64-9-297 7401

---------------------------------

**Comment by BrentOzar** [comment]
David - sorry, I'm working with a client, but seriously, this is the last time I'm going to respond on this issue: the readme.md has clear instructions on how to chat with us. I'd really appreciate you reading it.

Again, here's a direct link, just scroll down and follow the instructions on how to get support:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit
