### ISSUE TITLE
sp_BlitzQueryStore/sp_BlitzCache: pull out compile time values 

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1129]
Reasons.

**Comment by BlitzErik** [comment]
Initial thoughts on this: maybe only pull this info out if we look for a specific stored procedure using `@StoredProcName`? 

Would like to give the entire exec command for the proc with the variables as assigned. How much is it going to suck doing this if someone passes in a NULL value?

**Comment by BrentOzar** [comment]
Ooo, what's the problem you're trying to solve? I adore this for answering the question of, "How much CPU time has SQL Server spent compiling recently?" but I dunno that it fits in sp_BQS/sp_BC. It'd be just a sum of compile time across the plans, grouped by day/hour, maybe? Great DMV query and blog post, but it'd be tough to shoehorn into the procs' existing result sets.

**Comment by BlitzErik** [comment]
When we tune queries for clients, or even during a CC when investigating parameter sniffing, it'd be nice to have the values that the stored procedure was executed with without scrolling through the xml, copy pasting etc. Nothing to do with compile time?

**Comment by BlitzErik** [comment]
May also help track down implicit conversion easier.

**Comment by BrentOzar** [comment]
OH, I misunderstood it as the values FOR compilation time, not the parameter values AT compilation time. Carry on. Love that too.

**Comment by BlitzErik** [comment]
Hahaha. That stuff is in Query Store. We do some analysis on it, but not much.
