### ISSUE TITLE
sp_BlitzIndex - turn off @SkipPartitions unless @BringThePain = 1

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1132]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
@SkipPartitions defaults to 0. If there are more than, say, 100 partitions in the database, set @SkipPartitions = 1 unless @BringThePain is set to 1.

This will make our data collection run way faster by default (and we don't care about partition-level details initially.)

**Comment by BlitzErik** [comment]
Totally on board with this, but please add a line to the final results saying it was skipped. It's a good thing to be prepared for after data collection.

**Comment by BrentOzar** [comment]
Absolutely, I'm glad you said that - good point.
