### ISSUE TITLE
sp_AllNightLog Exclude System Databases

### ISSUE THREAD

**Issue by dalehhirt** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1133]
**Do you want to request a *feature* or report a *bug*?** Bug
If you're reporting a bug, include the version number of the script you're using. If it's not the current version, upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build.

Version is the Aug. 31st 2017 release.

**What is the current behavior?**
If there are system backups in the restore path folder, sp_AllNightLog will attempt to restore them as well.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
Point at a restore folder with master/model/msdb backups as well.

**What is the expected behavior?**
It should ignore system databases.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Affects all versions.

**Comment by dalehhirt** [comment]
Sample fix:
![image](https://user-images.githubusercontent.com/2246127/31040391-d18afb1a-a53b-11e7-8466-52cbbf0e43cd.png)

**Comment by BlitzErik** [comment]
This was fixed! #1162
