### ISSUE TITLE
Add access denied to check to s-_DatabaseRestore.sql

### ISSUE THREAD

**Issue by James-DBA-Anderson** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1135]
Bug
Currently if the script fails to find the backups files because the instance does not have access it silently fails. It would be nice if this error was raised to the user.

Running with @Debug = 1 shows the error in the @FileList table.

Suggested fix is to add the following code after the insert into @FaileList:

	IF (
		SELECT COUNT(*) 
		FROM @FileList AS fl 
		WHERE fl.BackupFile = 'Access is denied.'
		) = 1

		BEGIN
	
			RAISERROR('Access is denied to that database\path', 0, 1) WITH NOWAIT;

		END;

Severity 16 may be more appropriate for this error.

**Comment by BrentOzar** [comment]
Ooo, yeah, that makes sense. We should also include the path where we got denied just to make it easier to troubleshoot later.

Do you want to do a pull request for that change? (If not I totally understand, Github can be a little bit of a PITA, just wanted to give you the chance to do it if you wanted the Internet Points.)

**Comment by James-DBA-Anderson** [comment]
Ha thanks, I do love those internet points. 

Yeah I'd like to, do you need to give me access first or should I be able to just do it?

**Comment by BrentOzar** [comment]
I need to write up a full blown blog post on this, but the short answer is that you fork the project into your own Github account, make your changes, and then do a pull request from your personal project to our dev branch.

(If you Google about how to do this kind of thing, sometimes you'll read a whole bunch of rules about being a good contributor like collapsing your changes into a single commit, but we're totally not that anal. We just look at the line diffs between the original script and your change, and pull the trigger based on that.)

Thanks sir!

**Comment by James-DBA-Anderson** [comment]
Ah OK, that makes sense.
