### ISSUE TITLE
sp_Blitz -- Add posibility to check the backups only on the primary server  in AG

### ISSUE THREAD

**Issue by StanDaMan0505** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1137]
We only back up the databases on the primary server (as the secondary is not readable). Therefore  sp_Blitz always reports missing full- and transaction-log-backups. I wrote a solution that works for us, by adding a parameter @CheckBackupOnlyOnPrimary. Maybe you can check it and implement it in a future version.

File should be attached below.

[sp_Blitz_with_PrimaryCheck.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/1352120/sp_Blitz_with_PrimaryCheck.txt)

It's not the same issue as 399, or is it?
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/399

I just noticed that the function sys.fn_hadr_is_primary_replica is only available since SQL 2014, so my workaround only works on our servers.. There would need to be some more checks about the version with maybe some dynamic SQL..

Thanks for checking

**Comment by StanDaMan0505** [comment]
I should have read all the comments first on the #399 issue.. I guess it is the same at the end...

**Comment by BrentOzar** [comment]
Yeah, same issue as #399 - we can't rely on things like linked servers to be present. Thanks, but closing.
