### ISSUE TITLE
sp_BlitzCache - table analysis mode

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1143]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
I eat eggs

**What is the expected behavior?**
Call sp_BlitzCache with parameters like:

- PlanCacheDatabaseName, PlanCacheSchemaName, PlanCacheTableName
- PlanCacheUniqueColumn - could be ID or GUID, I'm guessing, but needs to be a single column (not doing a combo)
- PlanCacheXMLColumn - where the plans are stored
- PlanCacheWarningsColumn - where we'll write the advice back in

When you run it with those params, it:

- Does a SELECT from that table WHERE PlanCacheWarningsColumn IS NULL
- Gets the rows, analyzes the query plans
- Writes the advice back into PlanCacheWarningsColumn

**Comment by BlitzErik** [comment]
Notes:

You're still going to need the `##bou_BlitzCacheProcs` table
The logging table will need SQL Handle, Query Hash, and Plan Handle.
The main branching point will be to select data from the logging table into `##bou_BlitzCacheProcs`
It would require a tremendous amount of new dynamic sql to do it any other way
We may have to skip some checks that are dependent on analyzing things outside the plan XML

**Comment by BrentOzar** [comment]
Notes from the Slack chat about the problems with sorting (no matter where we do the logic of persisting this to table):

```
SELECT TOP 10 * 
INTO #LastAnalysis
FROM sys.dm_exec_query_stats
ORDER BY total_worker_time DESC;

/* Some time goes by */
SELECT TOP 10 sNow.* 
FROM sys.dm_exec_query_stats sNow
LEFT OUTER JOIN #LastAnalysis sLast ON sNow.query_hash = sLast.query_hash AND sNow.plan_handle = sLast.plan_handle
WHERE (sNow.execution_count <> sLast.execution_count OR sLast.execution_count IS NULL)
ORDER BY ...
```

The ORDER BY becomes a nightmarish hellscape.

Scenario 1: sNow is an entirely new query, new plan: use total_worker_time

Scenario 2: sNow has been in the plan cache for a long time, but it wasn’t in the top 10 last time. We can’t use total_worker_time because that’s not all the new stuff. We have to take the average worker time, times the guessed number of executions in this time span, based on a rolling average of executions since creation_time? That sucks so bad.

**Comment by BrentOzar** [comment]
Closing this. It makes so much more sense to do it in sp_BlitzCache. I just need to do a small tweak for sp_BlitzCache, logging a separate issue for that.
