### ISSUE TITLE
sp_blitzindex - no index on #IndexColumns means performance very slow

### ISSUE THREAD

**Issue by SAinCA** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1149]
Version is 2017-10-01, 5.8

Current behavior: Database has 241,000+ columns.  To run @mode=3 takes over 40 minutes on the build of the compression table, which is irrelevant to a Missing Index.

Steps to Reproduce: Just run sp_blitzindex @mode=3 on a DB with 200K+ columns.

Expected behavior: It should return in a few minutes at most, especially as the focus is just "Missing Indexes"

Run on both SQL 2014 Enterprise and SQL 2016 Developer (SP1 CU2) - Windows Server 2008R2 and Windows Server 2016 respectively.

**Suggestions**

1. Around line 1453, 

`IF NOT EXISTS ( SELECT 1
                  FROM tempdb.sys.indexes
                 WHERE name = 'CLIX_#IndexColumns'
              ) 
    CREATE CLUSTERED INDEX CLIX_#IndexColumns ON #IndexColumns ( database_id, object_id, index_id );`

2. At around 1750: `RAISERROR(N'Populate #PartitionCompressionInfo.', 0, 1) WITH NOWAIT;`
Make the Compression information optional:
`IF @Mode <> 3
    BEGIN
...
    END`

3. There may be many opportunities to skip a number of information retrieval/UPDATEs when @Mode = 3, just to make the proc faster.

**Comment by BrentOzar** [comment]
Oh, goodness. Alright, well, that's definitely an interesting challenge. This wouldn't be something we'd code, but it sounds like you've got a good test case there, and a good idea of what you'd want to change. Do you want to go ahead and start tackling the code? If so, check out the Contributing.md in the root folder.

**Comment by SAinCA** [comment]
Well, that'll be a first!  Never done a thing on GitHub...  Guess I should read a User Guide.

I can say that the added index and branch renders a result in 38 seconds on that DB, in 2 environments on separate SQL instances and versions...

**Comment by BlitzErik** [comment]
Howdy,

Are you still working on this? Are you stuck with something? Just checking in on older issues that we can possibly close out.

Thanks!

**Comment by SAinCA** [comment]
It's still very clearly an issue.  I'm a bit surprised nobody else has run into the problem - 240,000 columns isn't that rare, I'd venture.


I've absolutely ZERO idea how to do anything at all on github even after grubbing around for something that may give some instruction...   For someone who's being developing SQL for over 30 years, it hasn't proven to be a very intuitive process, but then I could simply have not been looking in the right places!


Neither, realistically, do I have the confidence to muck with a very public tool.  All the changes I suggested are in the version I've modified for internal use, and they don't appear to fail, but that may not mean a lot as I rarely use the non-customer-deployed version - far more likely to use a version on one of the score and more customer servers in my charge, and they have older (March 2017) versions.


So, "STUCK" would be a very apt description...  Stuck clueless, would be appropriate, too, in regards to github.


Sorry to disappoint.  I've attached the version I changed, if that may help with a code merge...  I added a little to the version identification to distinguish it from the community version, in case it blew up in my face...


Best regards,


Stephen

________________________________

**Comment by BlitzErik** [comment]
Hi there,

I don't think an attachment came through. 

I'll close this out for now.

Thanks!

**Comment by SAinCA** [comment]
In case it proves to be of any use, and zip files are accepted on your end........  Attached as a zip this time

________________________________

**Comment by nschonni** [comment]
@SAinCA you can only attach files through the web interface. Attachments through email isn't supported by GitHub

**Comment by SAinCA** [comment]
[sp_BlitzIndex.zip](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/1508247/sp_BlitzIndex.zip)

**Comment by SAinCA** [comment]
GitHub know-nowt has added the file the right way - thanks @nschonni

**Comment by BlitzErik** [comment]
Thanks! So the only difference is the index create on `#IndexColumns`? Nothing else? If so, this should be easy to work in.

**Comment by SAinCA** [comment]
That’s all I did for our version, yes.

________________________________
