### ISSUE TITLE
sp_blitzindex - Change @Mode=3 "is_low" to "Impact" and invert the CASE setting of the bit

### ISSUE THREAD

**Issue by SAinCA** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1150]
"Feature Modification" - Version = '5.8'; VersionDate = '20171001';

For @Mode=3 , the "is_low" column is helpful to indicate potential usefulness of the index suggestion in the @Mode=3 resultset.

When you export to Excel, it is counter-intuitive to see "is_low" and its bit values when the zeros are typically at the top of the list.  When using a Custom format to see True/False, or conditional formatting to show a nice green tick or red cross, the current code shows counter-intuitive wording/icons.

Would you consider renaming the output column to "Impact" and inverting the CASE from: `UPDATE #MissingIndexes 
SET is_low = CASE WHEN (user_seeks + user_scans) < 10000 
					OR avg_user_impact < 70. THEN 1
					ELSE 0 
				END;`

to: `UPDATE #MissingIndexes 
SET is_low = CASE WHEN (user_seeks + user_scans) < 10000 
					OR avg_user_impact < 70. THEN 0
					ELSE 1 
				END;`

With a corresponding change to the INSERT #BlitzIndexFindings: `                                N'Indexaphobia' AS findings_group,
                                N'High value missing index' + CASE mi.is_low 
															  WHEN 1 THEN N' with High Impact' 
															  WHEN 0 THEN N' with Low Impact'
															  END
															  AS finding, `

**Comment by BrentOzar** [comment]
I hear where you're coming from, but we won't be renaming columns at this point for convenience sake - it'd take a lot to rename a column or change output logic. Keep in mind that folks have built tools on top of these scripts.

If there's a documentation change that would make these concepts easier to get, though, we're totally open for that.

**Comment by SAinCA** [comment]
Sadness, but understood.  Guess I missed the addition of the is_low to the @Mode=3 column list or I'd have spoken up earlier.  Apologies.
