### ISSUE TITLE
sp_foreachdb: Additional Functionality to Database_list and Exclude_List

### ISSUE THREAD

**Issue by pjjaad** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1151]
**Do you want to request a *feature* or report a *bug*?**
 

**What is the current behavior?**
Hand Cranked List of database names as the list for either database_list or excluded_list
 
**What is the expected behavior?**
Use wild card for generating a comma separated list of database names for both database_list and excluded_list

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

I don't think your previous versions used wild card lists
example exec master.dbo.sp_foreachdb 
@command = 'use ? select ''?'' as Databasename ',@DATABASE_LIST='%V3'
@command = 'use ? select ''?'' as Databasename ',@@exclude_list='%V3'
This allows you to filter databases either way.
I wrote this change because I have multiple versions of databases on the server so this is a quick way to produce a filter using wild cards.
I just did not like hand cranking the lists.

[sp_foreachdb.zip](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/1372103/sp_foreachdb.zip)

**Comment by BlitzErik** [comment]
When I try to run this, I get an error:

```
Msg 137, Level 15, State 2, Procedure sp_foreachdb, Line 37 [Batch Start Line 7]
Must declare the scalar variable "@DATABASE_LIST".
```

Make sure to read the [contributing guidelines](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md).

If you want to work on this more, feel free to reopen the issue. Closing for now.

Thanks!
