### ISSUE TITLE
sp_DatabaseRestore - Add support for multiple full backup files

### ISSUE THREAD

**Issue by petesql** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1153]
**Do you want to request a feature or report a bug?**
Feature

**What is the current behavior?**
Unable to restore 'split' full backups (@NumberOfFiles parameter in Ola's backup script)

**What is the expected behavior?**
Restore full backups no matter how many files the backup media is split into. 

.

With my novice coding skills I have been able to identify the correct files & restore - finding near impossible to implement this into SP_DatabaseRestore. 

This is how I'm identifying files:
```
--Enumerate target path & isolate most recent SQL backup media set.
DECLARE @exec_cmd VARCHAR(550) = 'NET USE R: ' + @backup_root
SET @exec_cmd = 'dir /b /s /a R:\*'
INSERT #backups
EXEC MASTER..xp_cmdshell @exec_cmd

DELETE #backups
	WHERE filepath not like 
	'%'+(SELECT top 1 substring(filepath, PATINDEX ('%[_]FULL[_]%',filepath)+6, 14) from #backups order by filepath desc)+'%'
	or filepath is null
```

Restores are looking like:
```
SET @exec_cmd = 'RESTORE DATABASE [' + @databasename + '] FROM '
SELECT @exec_cmd = COALESCE(@exec_cmd, '') + 'DISK = N'''+filepath+''',' from #backups
-- remove trailing , from the coalesce
SELECT @exec_cmd = left(@exec_cmd, len(@exec_cmd)-1)
SELECT @exec_cmd = COALESCE(@exec_cmd, '') + ' WITH FILE = 1, MOVE ''' + @LogicalDataName + '''' +  ' TO ''' + @Restoring_Path + '\' + @LogicalDataName + '.mdf''' + ','
SELECT @exec_cmd = COALESCE(@exec_cmd, '') + ' MOVE ''' + @LogicalLogName + '''' + ' TO ''' + @Restoring_Path + '\' + @LogicalLogName + '.ldf''' + ','
SELECT @exec_cmd = COALESCE(@exec_cmd, '') + ' REPLACE, STATS =5'
```

**Comment by BrentOzar** [comment]
Yeah, I couldn't figure out how to implement that either - especially since the files can have different names. If you're asking us to code it for you, this isn't something that we have on the horizon, so if you can't code it, I'm going to go ahead and close it for now. Thanks though!
