### ISSUE TITLE
sp_BlitzQueryStore -- results sort order

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1178]
Since we don't actually prefer any single metric for plan cache sorting, I need to come up with a smart way to sort results. Right now I'm using query cost. No real reason. 

I'm thinking plan_id and query_id might be a better idea. 

If not that, then maybe last execution time. ascending? descending?

**Comment by janwillemaikens** [comment]
Hi, 
Thanks for sp_blitzquerystore.
I'm not sure if you've already decided on this.
Could you create a couple of parameters @SortBy (Colnumber) SortOrder (A[scending]/D[escending])
So, ordering by last_executiondate desc would be @SortBy=38, @SortOrder='D'
