### ISSUE TITLE
sp_DatabaseRestore: add options to kill user connections first and/or drop database

### ISSUE THREAD

**Issue by ShawnCrocker** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1181]
Developers won't close SSMS so we need to force majeure this.
To stop reconnection, DROP may be needed

```
    SET @DynamicCommand = '/* Kill connections */';
    SELECT 
        @DynamicCommand = CONCAT(@DynamicCommand, '
    KILL ', spid, ';')
    FROM
        master.sys.sysprocesses  
    WHERE
        dbid = DB_ID(@DBName)
    EXEC (@DynamicCommand);
```

**Comment by BlitzErik** [comment]
Careful with this one. Our scripts have to support 2008+, and `CONCAT` is 2012+.

**Comment by ShawnCrocker** [comment]
Acknowledged, That code is copy+paste from my own code

**Comment by SQLGumbo** [comment]
Just some quick random thoughts.  I'd be concerned about dropping the database depending on the environment needs...what if the restore fails or it is in an Always on config.  Would running an ALTER DATABASE...SET..WITH ROLLBACK IMMEDIATE be an acceptable alternative to killing the spid?  What if there is a process in the database that needs to be running too?  Maybe check if the spid is from SSMS before killing it.

**Comment by ShawnCrocker** [comment]
My plan was to have a "kill or drop" flag
- 0 try and restore
- 1 kill all
- 2 kill and drop

However, my personal use case is to drop to stop reconnections from spammy apps that require db_owner (3rd party apps). In this case, single user is pointless

I'm sure other people are in the same position.

We can add options as needed. 

- 0 try and restore normally
- 1 single user mode
- 2 kill all
- 3 kill and drop

I propose this counting flag approach to avoid conflicting flags if we try to do it in multiple flags

**Comment by BrentOzar** [comment]
I like it! I like the flag with 0/1/2/3, makes sense.

**Comment by ShawnCrocker** [comment]
Haven't forgotten about this. Well, I nearly did...
