### ISSUE TITLE
sp_DatabaseRestore: add option to drop/add/replace a database principal

### ISSUE THREAD

**Issue by ShawnCrocker** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1183]
My use case:

I have different Managed Service Accounts per environment,
When I restore from Live to UAT, it would be good to replace this MSA in the restored database.

**Comment by BrentOzar** [comment]
Interesting! I don't think we've got anything to add in terms of design guidelines or testing notes. Go for it!

**Comment by BlitzErik** [comment]
@ShawnCrocker did you ever do this one? Not sure if you covered it in one of your PRs.

**Comment by BlitzErik** [comment]
Going to close this out for now. When you're ready to work on it, feel free to reopen the issue.
