### ISSUE TITLE
sp_BlitzIndex - if SkipPartitions is set to 1, warn users in table-level views (already done in db-level)

### ISSUE THREAD

**Issue by deweter** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1187]
Latest version (sp_BlitzIndex(TM) v5.8 - October 01, 2017) is not showing CCI size. Blank result is shown instead. 

Tested on Microsoft SQL Server 2016 (SP1-CU3) (KB4019916) - 13.0.4435.0 (X64)   Apr 27 2017 17:36:12   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) 

![cci-blank-size](https://user-images.githubusercontent.com/13314610/31708937-c43c987e-b3f0-11e7-8974-83e9f6079e9e.png)

**Comment by BrentOzar** [comment]
Howdy! A couple clarification questions: can you show the Messages tab, and does this database have over 100 partitions in it?

**Comment by deweter** [comment]
Hi Brent! Here is the output from Messages tab:
```
Starting run. sp_BlitzIndex(TM) v5.8 - October 01, 2017
Create temp tables.
Adding UQ index on #IndexSanity (database_id, object_id, index_id)


LicCS
Inserting data into #IndexColumns for clustered indexes and heaps
Inserting data into #IndexColumns for nonclustered indexes
Inserting data into #IndexSanity
Checking partition count
Setting @SkipPartitions = 1 because > 100 partitions were found. To check them, you must set @BringThePain = 1.
Inserting data into #MissingIndexes
Inserting data into #ForeignKeys
Gathering Computed Column Info.
Gathering Trace Flag Information
Gathering Temporal Table Info
Updating #IndexSanity.key_column_names
Updating #IndexSanity.partition_key_column_name
Updating #IndexSanity.key_column_names_with_sort_order
Updating #IndexSanity.key_column_names_with_sort_order_no_types (for create tsql)
Updating #IndexSanity.include_column_names
Updating #IndexSanity.include_column_names_no_types (for create tsql)
Updating #IndexSanity.count_key_columns and count_include_columns
Updating index_sanity_id on #IndexPartitionSanity
Inserting data into #IndexSanitySize
Determining index usefulness
Updating #IndexSanity.referenced_by_foreign_key
Update index_secret on #IndexSanity for NC indexes.
Update index_secret on #IndexSanity for heaps and non-unique clustered.
Populate #IndexCreateTsql.
Populate #PartitionCompressionInfo.
Update #PartitionCompressionInfo.
@TableName specified, giving detail only on that table.
```
The table has 880 partitions 

...and with 

> @BringThePain = 1

 it is working properly. :open_mouth: 

Originally, I was using sp_BlitzIndex(TM) v5.5 - July 01, 2017 and I got a completely wrong size (many times larger than the actual one). Then I have upgraded the script and got blank results as shown in a previous screenshot. But I didn't have a look on messages to be honest :)

**Comment by BrentOzar** [comment]
OK, perfect. I think it's still a bug - in the normal database-wide view, we throw a warning in the results set to tell you that we had to skip partitions. I need to do the same thing now for table-level view - that hadn't even occurred to me! So thanks for reporting it, and I'll edit the title to make it more clear.

**Comment by BrentOzar** [comment]
Now, when there's >100 partitions but BringThePain wasn't set to 1, we raise an error with severity 16 to make it clear that the data won't be complete.

I was going to add lines to the output tables, but then I realized it was going to be tricky with all the different output modes.
