### ISSUE TITLE
sp_BlitzWho -- pruning default columns

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1188]
We return a lot of information, and not all of it is useful up front. Ideally I'd like to present a shorter set of information, and use `@ExpertMode` = 1 to return extended information.

@BrentOzar will probably have opinions.

**Comment by BrentOzar** [comment]
My thoughts for the core set, rearranged a little:

- run_date
- elapsed_time
- session_id
- database_name
- query_text
- query_plan
- live_query_plan
- query_cost
- status
- wait_info
- top_session_waits
- blocking_session_id
- open_transaction_count
- nt_domain
- host_name
- login_name
- nt_user_name
- program_name

Expert mode, all added to the end after the above:

- client_interface_name
- login_time
- start_time
- request_time
- request_cpu_time, request_logical_reqds, request_writes, request_physical_reads
- session_cpu, session_logical_reads, session_physical_reads, session_writes
- tempdb_allocations_mb
- memory_usage
- estimated_completion_time, percent_complete
- deadlock_priority, transaction_isolation_level, 
- degree_of_parallelism
- memory grant stuff, parallelism stuff, etc
- workload_group_name, resource_pool_name

Totally open to ideas though.

**Comment by SQLGumbo** [comment]
#1255 will be adding context_info.   Thinking it should be one of the expert mode fields.  Want to keep it on the radar.

**Comment by BlitzErik** [comment]
I'm going to merge in your change, and then add it to the list of expert mode columns. That sounds less painful than making you make another pull request after we make this larger change.

**Comment by SQLGumbo** [comment]
Uggh...there goes the practice.   Thx sir.

**Comment by SQLGumbo** [comment]
Pardon my green complexion...I didn't update the version in the code I submitted.   Thinking I don't need to worry about that now these will be consilidates.   Thanks Eric!

**Comment by BlitzErik** [comment]
If you want, just close your pull request, and then work on the new base after the columns are pruned. I'm fine either way, and you'd get credit in either case. Let me know what makes more sense to you.

**Comment by SQLGumbo** [comment]
I hate coming back with this.   Sorry.  Not worried about 'credit' and think whatever is best for getting the changes in is the way to go.   

Personally, I think 1255 should be closed.  Reason being that the requestor is most likely off and running with the first code example presented.  I really like the use of CONTEXT_INFO and respect that they are taking advantage if it.   I'll kick back and do a wait and see.  

I do appreciate the opportunity to go theough the process of making a change.   Have enjoyed it.

**Comment by BlitzErik** [comment]
Alright, cool. Thanks for doing the work and being part of the process.

**Comment by eaglejohn81** [comment]
Thanks both for the work! Much appreciated!
