### ISSUE TITLE
Instead of @debug = 1 upchucking messages, log to table

### ISSUE THREAD

**Issue by scorellis** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1191]
During a two day long troubleshooting jam of sp_allnightlog, I found myself jostling the jobs so that I could call sp_allnightlog from the ssms window in debug mode.  It was extremely awkward.  This is a feature request to improve and increase logging capabilities so that I can run jobs in logging-to-table mode, and then I can simply watch a table to view messages.  Additionally, if I am running more than one backup or restore job, I need the job name to be recorded along with the logging entry.

**Comment by BrentOzar** [comment]
Howdy sir! Neat idea, I like it.

I updated the Contributing.md this morning to make it a little more clear about how contributions to the First Responder Kit work:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md

If you want to code this yourself in the next ~30 days, thumbs up - you can go for it. Just make sure to follow the guidelines in Contributing.md around testing on case sensitive instances & SQL 2008 through 2017. (If you can't do that testing, you'll need to find a volunteer tester in the community.)

If you want to outsource the work, you can talk to the other developers in the Slack channel to see if they want to pick it up:  https://sqlcommunity.slack.com/messages/FirstResponderKit Or of course holler at us, and we can write you up a quote and a Statement of Work, either way.

**Comment by scorellis** [comment]
Hey Brent, 

We are undertaking this work, I started on it yesterday afternoon and am about half way through sp_allNightLog now.  I thought I would present a review of how it works here, for community acceptance and feedback. Let me know if I should post this somewhere else? 

Here is a rough outline of how the logging  it works:

a stored procedure for logging is called from strategic locations throughout the entire sp_AllNightLog procedure, which will log the following:

1. What just happened
2. How long it took, (duration since the last logged event in this session)
3. Any relevant @sql (sometimes I have to make it myself as there is not a ton of dynamic calls), messages, or errors
5. What module/sp created the log entry
6. Duration since the module (sp_allnightLog) started this session
8. SessionID (runID)
9. AgentID - who initiated the session (don't know how to get this yet)
10. Various relevant UTC time stamps
11. What is supposed to happen next

 I'd like to add two rows to the configuration table: 
 1. One row will turn slogging on and off, something along the lines of configuration_setting = 'Slogging_Level',  configuration_value = (0,1)  with a logging_description = 'Sp_AllNightLog can be configured to send system messages to a central table.  0 = logging off, 1 = logging turned on'
This way, I can turn logging on or off from one central location.  

2. The other row will be for SlogRetention, and will be described as "Count of days to retain sp_allnightlog run log entries"

**Functional Description:**
The logging is performed by a stored procedure called "Slogger"; it writes to a table called "SloggerLog" that has the following columns:
	[SLogID] [int] IDENTITY(1,1) NOT NULL,
	[Servername] [sysname] NOT NULL,
	[RunID] [int] NULL,
	[AgentID] [int] NULL,
	[RunStartUTC] [datetime] NULL,
	[LogTimestampUTC] [datetime] NULL,
	[LogIntervalDurationMS] [bigint] NULL,
	[RunDurationMS] [bigint] NULL,
	[Module] [nvarchar](100) NULL,
	[TaskCompleted] [nvarchar](max) NULL,
	[Message] [nvarchar](max) NULL,
	[NextTask] [nvarchar](max) NULL

The stored procedure performs the various calculations needed to flesh out the time and duration columns.  I will add indexes to this as needed; at the moment it only has a clustered index and an auto-seed key.

Logging cleanup -  The stored procedure will semi-randomly decide it needs to perform cleanup and delete any rows in the SlogLog table that are older than the configured value, which is captured by AllNightLog when it is first started. 

If someone doesn't want logging on all agents running, then they need only set the logging value, stop and restart the agent that interests them, and then reset the value back to '0'.

Let me know what you think.  I am reusing a stored procedure that I wrote for a different project.  it only needed some minor changes to make it more generic.  

**A few questions for the community :**  

1. Do you want this feature, if so I can fork and include it
2. are there any objections to how I'm doing it
3. does anyone know how to pull back the name of the agent that calls a script, from the script itself?   I'd like to report in the log the name of the agent that is creating the log entry, as opposed to just throwing in a random spid.

**Comment by BrentOzar** [comment]
Interesting! One big danger: if the code is from anywhere else, we need written permission from the code owner, and the license that they're publishing it under. 

For example, just, uh, theoretically, if you're an employee at a company where the company has had all employees sign an IP agreement specifying that the company owns source code you produce while you work there, and if there are legal agreements prohibiting the usage of open source code without express written approval from the legal team, then, uh, well, you see where I'm going with this. (Insert poker face joke here.)

Section 8 of "The Legal Side of Open Source" is a really good starting point:
https://opensource.guide/legal/

Once we've cleared that, this sounds fine. Normal contribution caveats apply - needs to work on SQL 2008 & newer, including case-sensitive instances. Otherwise sounds good.

**Comment by BlitzErik** [comment]
I'm going to close this for now. If you want to move forward with it in the future, feel free to reopen or start a new issue.

Thanks!
