### ISSUE TITLE
sp_DatabaseRestore: parameter improvement for sources

### ISSUE THREAD

**Issue by ShawnCrocker** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1193]
These parameters are a bit tautological
```
         @Database NVARCHAR(128) = NULL, 
	  @RestoreDatabaseName NVARCHAR(128) = NULL, 
	  @BackupPathFull NVARCHAR(MAX) = NULL, 
	  @BackupPathDiff NVARCHAR(MAX) = NULL, 
	  @BackupPathLog NVARCHAR(MAX) = NULL,
```
It offends me to copy+paste the parameters.

My auto restore code uses something like the following, which is based on Ola's code using very predictable paths:
```
          @Database NVARCHAR(128) = NULL, 
	  @SourceServerInstance NVARCHAR(128) = NULL,  -- if null use @@SERVERNAME
          @BackupPathStub NVARCHAR(MAX)  = NULL,      -- if null, read from registry          
          @RestoreDatabaseName NVARCHAR(128) = NULL,
```

This may not work for all shops and would break existing code.
So it could be done as a wrapper around the current code

There may be more parametere observations over time a I work with this more

**Comment by BrentOzar** [comment]
Ooo, yeah, I'd rather not change the names on these now that it's shipped - unless there's a really, really compelling case to break peoples' existing deployments. Going to close this one.
