### ISSUE TITLE
sp_DatabaseRestore @StopAt ignored for FULL backups, probably DIFFs too

### ISSUE THREAD

**Issue by ShawnCrocker** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1198]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
3 FULL backups, say 
- MyDB_FULL_20171009_175822.bak
- MyDB_FULL_20171014_081632.bak
- MyDB_FULL_20171021_081013.bak

and then @StopAt = N'20171019160000'

The internal @LastFullBackup does not consider @StopAt so will use MyDB_FULL_20171021_081013.bak
Also probably @LastDiffBackup but not tested

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
nah

**What is the expected behavior?**
@StopAt is applied to Full and DiIff backups

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Reproduced on SQL Server 2012 and SQL Server 2016

**Comment by ShawnCrocker** [comment]
In the SELECTs for
@LastDiffBackup = MAX(BackupFile)
and 
@LastFullBackup = MAX(BackupFile)

Add this

```
	AND
	(@StopAt IS NULL OR REPLACE(LEFT(RIGHT(BackupFile, 19), 15),'_','') <= @StopAt);
```

Tested but I'm limited with github usage here

**Comment by BrentOzar** [comment]
This issue is closed. If you have a support question, create a new issue or ask in Slack. Thanks!
