### ISSUE TITLE
SP_BLITZ check 128 still finds SP1-Build 11.0.3000 to be okay, when Support for SP2 (11.0.5058.0) has ended this january. 

### ISSUE THREAD

**Issue by Totty1973** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1199]
**Do you want to request a *feature* or report a *bug*?**
possible enhancement for Version 20171001: encourage SP3 ( 11.0.6020.0 ) or newer. We plan to deploy a 2012 cluster in december, thats no joke.

**What is the current behavior?**
SP_BLITZ check 128 still finds SP1-Build (11.0.3000) to be okay when Support for SP2 (11.0.5058.0) has ended this january according to https://support.microsoft.com/en-us/lifecycle/search?alpha=Microsoft%20SQL%20Server%202012

**What is the expected behavior?**
encourage SP3 or newer. 

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2012

**Comment by BrentOzar** [comment]
YOU READ MY MIND. I was just thinking about that this morning. Great idea, and I'll get that fixed up. Thanks for filing this issue!
