### ISSUE TITLE
sp_BlitzFirst @AsOf feature not working

### ISSUE THREAD

**Issue by TPok177** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1200]
**Do you want to request a *feature* or report a *bug*?**
bug - sp_BlitzFirst version 5.8

**What is the current behavior?**
I'm trying to run sp_BlitzFirst with the @AsOf parameter the following way:
EXEC sp_BlitzFirst @AsOf = '2017-01-01 11:00:00', @OutputDatabaseName = 'Admin', @OutputSchemaName = 'dbo', @OutputTableName = 'BlitzFirst'

I'm getting the following error:
Msg 241, Level 16, State 1, Line 1
Conversion failed when converting date and/or time from character string.

I found this is related to code lines 208-209 where the conversion fails:
            + ' WHERE CheckDate >= DATEADD(mi, -15, ''' + CAST(@AsOf AS NVARCHAR(100)) + ''')'
            + ' AND CheckDate <= DATEADD(mi, 15, ''' + CAST(@AsOf AS NVARCHAR(100)) + ''')'

This issue seems to be existing before as [bug #499 ](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/499) and should haven been fixed.

**What is the expected behavior?**
Returning a result without an error

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Tested on SQL Server 2014 (12.0.5253.0) on Windows Server 2012 R2.

**Comment by BlitzErik** [comment]
Ooh, that's a fun catch. I think I have it worked out. Can you try the version of BF [here](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/1201) and let me know if that works for you as well?
