### ISSUE TITLE
sp_BlitzWho column 'used_memory_kb' outputs twice with same name.

### ISSUE THREAD

**Issue by hfleitas** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1203]
**Do you want to request a *feature* or report a *bug*?**
5.8. 20171001

**What is the current behavior?**
sp_BlitzWho, column used_memory_kb outputs twice with same name

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
run sp_blitzwho, select all output from results pane. Shift+Ctrl+C, Paste contents to a blank window. Search for used_memory_kb, you will see the column header twice.

**What is the expected behavior?**
Column names should be unique so an alias can be used to differentiate. 

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
n/a

**Comment by hfleitas** [comment]
I altered the proc to resolve the issue. See attached.
[sp_BlitzWho.sql.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/1412380/sp_BlitzWho.sql.txt)

**Comment by BlitzErik** [comment]
Thanks. We'll likely tie this fix in to #1188.

**Comment by hfleitas** [comment]
Sounds good, thx Erik!

**Comment by BlitzErik** [comment]
Closing this to focus on the other issue.

Thanks!
