### ISSUE TITLE
sp_Blitz - unrelated checks using the same CheckID

### ISSUE THREAD

**Issue by david-potts** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1205]
Hi Brent,
Not sure if this is a bug or a conscious decision but I have noticed that there are some seemingly unrelated checks which use the same CheckID values.

* CheckID 199 is used for  'Overall Events' in the 'DBCC Events' Findings Group but also for 'There Is An Error With The Default Trace' in the 'Reliability' Findings Group.   
* CheckID 201 is used for  'DBCC FREEPROCCACHE' in the 'DBCC Events' Findings Group but also for  '@CheckUserDatabaseObjects Disabled' in the 'Informational' Findings Group.   
* CheckID 202 is used for  'DBCC SQLPERF(''SYS.DM_OS_WAIT_STATS'',CLEAR)' in the 'DBCC Events' Findings Group but also for 'Encryption Certificate Not Backed Up Recently' in the 'Backup' Findings Group.

The checks in the 'DBCC Events' Findings Group are not listed in the documentation (https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/Documentation/sp_Blitz%20Checks%20by%20Priority.md). 

I am using version = '5.8' of the script (version date = '20171001').

BTW, Thanks for providing this excellent resource.

**Comment by BrentOzar** [comment]
WOOHOO! Great find, man! We'll get those fixed.

Now, I'm curious: what are you doing with the CheckIDs? (Always wondering what folks are doing with those. I first put 'em in hoping that people would build something on top of sp_Blitz.)

**Comment by david-potts** [comment]
I use sp_blitz as a regular health check on all of our systems and then use a spreadsheet to aggregate the results. I use the CheckId to uniquely identify the findings and count/list the systems which need action. 
I could have used the finding text but CheckID was easier ... until there were duplicates.
