### ISSUE TITLE
sp_blitz: Handle AlwaysOn Availability Group backups

### ISSUE THREAD

**Issue by david-potts** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1206]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
sp_blitz reports 'Backups Not Performed Recently' (Checkid 1) and 'Full Recovery Mode w/o Log Backups' (CheckID 2) for databases in an Always On Availability Group. 
We have Automated Backup Preference being set to 'Prefer Secondary' and so sp_blitz reports no backup on the Primary replica and no log backup on the secondary but I assume issues would be reported on one (or more) of the replicas with any setting for this parameter. 

**What is the expected behavior?**
If database is in an Availability Group (in 'sys.availability_databases_cluster'), determine if server is primary replica (sys.fn_hadr_is_primary_replica(dbname)). 
For primary replica with backup preference set to anything other than 'Primary', if no backups then report 'No backups - check other replicas' at low priority.  
For secondary replica with backup preference set to anything other than 'Primary', if no backups then report 'No backups - check other replicas' at high priority.  
For secondary replica if no log backups then report 'No log backups - check primary replica' at low priority.  

I've tried to code this but I'm not easily able to test it and I'm a Git novice.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Verified on SQL Server 2016. Not certain which version Backup Preference was introduced in.

**Comment by BrentOzar** [comment]
The problem is that we don't know failover history for this AG. It could be that backups were supposed to run on this server over the last day, but none did.

We're going to steer clear of this for now - I just haven't seen a good way to code it while knowing about backup history over time, without being able to query the secondaries.

**Comment by david-potts** [comment]
Yep. I understand the difficulty.
We have a daily health check which is 'cluster aware' to an extent but gives 'false positives' in the time between a failover and the next round of backups.
I have to admit that I was kind of hoping you might have a clever way to deal with this but it's kind of comforting to know that you think it is as difficult as I do.

**Comment by BrentOzar** [comment]
Hahaha, it's true! My only thought so far has been to check to see if linked servers exist for the other replicas, and if so, check over there. The error handling and timeouts would suck though.
