### ISSUE TITLE
Read only databases listed as having had no DBCC CHECKDB

### ISSUE THREAD

**Issue by Gavin83** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1207]
It appears that sp_Blitz records read only databases as having not run a DBCC CHECKDB within 14 days even if it has. sp_Blitz checks for the last successful run by using DBCC DBInfo() but the database being in read only mode causes this to not get updated. As this check will never be accurate for read only databases it's probably worth removing them from the 'last known DBCC CHECKDB' by default.

**Comment by BrentOzar** [comment]
Looks good! Nice work sir. We'll get this added to the next release. Thanks!
