### ISSUE TITLE
sp_BlitzQueryStore could use the Schema name

### ISSUE THREAD

**Issue by SQLMonger** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1210]
The result column proc_or_function_name could stand to include the schema name of an object.
Adding the following in at line 1569 will achieve the desired result:

       object_schema_name(qsq.object_id, DB_ID(' + QUOTENAME(@DatabaseName, '''') + N')) +''.'' +

**Comment by BlitzErik** [comment]
Question: would you find this useful in the stored proc name search as well, or just in the printed proc info? Only asking because if you want it for the search as well, I need to add a parameter for the schema name. Makes things a tad more complicated on my end.

Thanks!

**Comment by SQLMonger** [comment]
I think just in the results would suffice.  If I search by a proc name of [Submit] the results will be for any items with that name in any schema, and as long as the name is in the result, I can differentiate between multiple procs.

**Comment by BlitzErik** [comment]
Word up. I'll have this out in the next release. Thanks again!
