### ISSUE TITLE
sp_BlitzFirst wait stat delta views bug with divide by zero error

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1213]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If sp_BlitzFirst is run twice within one second (like from two different sessions, both logging to the same table), the delta view for wait stats will hit a divide-by-zero error on this line:

`, (w.wait_time_ms - wPrior.wait_time_ms) / 1000.0 / DATEDIFF(ss, wPrior.CheckDate, w.CheckDate) AS wait_time_minutes_per_minute`

**What is the expected behavior?**
Either figure out how to divide by zero, or put in an exclusion in the where clause to skip rows where datediff(ss, wPrior.CheckDate, w.CheckDate) > 0.

**Comment by BlitzErik** [comment]
Any reason not to stick a `NULLIF`on it?

**Comment by BrentOzar** [comment]
As I'm looking at it, I'm trying to figure out if I want to rip out near-identical passes out of the table, and how. Basically if 2 of us dump data in at the same time, I'm showing twice as much stuff in all of the dashboard views, rendering it much less useful.

I think I basically want ALL the delta views to have where datediff of this check and the last one is at least, say, 30 seconds.

**Comment by BrentOzar** [comment]
While I'm in here, need to add a per-second output field to the Perfmon deltas view. (Trying to avoid doing any data manipulation in PowerBI to make it easier for people to change data sources.)
