### ISSUE TITLE
sp_DatabaseRestore - Alternative to xp_cmdshell

### ISSUE THREAD

**Issue by samssb82** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1214]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The script currently uses xp_cmdshell.

**What is the expected behavior?**
If possible, I would like to see a version that doesn't use xp_cmdshell.  Audits have led us to disable this on all of our instances.

**Comment by BlitzErik** [comment]
Ooh! I'd like a date with Josie and the Pussycats!

Please read the Contributing guidelines, especially for [feature requests](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md#how-to-request-features) before creating issues.

Thanks!
