### ISSUE TITLE
sp_databaseRestore throws an ERROR Number is NULL for valid backups

### ISSUE THREAD

**Issue by scorellis** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1225]
The below is from the messages when run in Debug mode.  Both of the below commands run and result in a database, restored, in the restoring state.   When these commands are run as a job, with the same credentials as all the other jobs, no error is thrown and the result is a database, restoring.  

Checking restore path
Beginning Restores
Checking variables
Begin tran to grab a database to restore
Updating restore_worker for database ARrce
Restoring full backup for ARrce
Path for FULL backups for ARMRurce is \\VMFIL0om\T7\Backups\\CTU01\ARce\FULL\
Path for LOG backups for ARMRrce is \\VMHa.com\T27\Backups\\CW01\ARrce\LOG\
Starting first Full restore from: 
\\VMura.com\T27\Backups\\CTU01\ARrce\FULL\
DIR /b "\\VM0om\T27\Backups\\CTUSW01\ARrce\FULL\"
INSERT INTO #FileListParameters WITH (TABLOCK)
   (LogicalName, PhysicalName, Type, FileGroupName, Size, MaxSize, FileID, CreateLSN, DropLSN
   ,UniqueID, ReadOnlyLSN, ReadWriteLSN, BackupSizeInBytes, SourceBlockSize, FileGroupID, LogGroupGUID
   ,DifferentialBaseLSN, DifferentialBaseGUID, IsReadOnly, IsPresent, TDEThumbprint, SnapshotUrl)
EXEC ('RESTORE FILELISTONLY FROM DISK=''\\VMHura.com\T27\Backups\\CTU7W01\ARMrce\FULL\VMH827W01_ARMrce_FULL_20171017_155205.bak''')
--@ContinueLogs set to 0
RESTORE DATABASE ARMrce FROM DISK = '\\VMa.com\T27\Backups\\CTUS0W01\ARce\FULL\VMH0W01_ARrce_FULL_20171017_155205.bak' WITH NORECOVERY, REPLACE

Error number IS NULL
Updating backup_worker for database ARce for UNsuccessful backup

**Comment by scorellis** [comment]
I was able to figure this out.  It can be closed.

**Comment by BrentOzar** [comment]
Great, thanks!
