### ISSUE TITLE
Error running sp_BlitzCache

### ISSUE THREAD

**Issue by goldendba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1226]
**Do you want to request a *feature* or report a *bug*?**
Bug - I'm using the DEV version from the PASS Summit session

**What is the current behavior?**
If I run the sp_BlitzCache, even with no options, it gives the following error:
_Getting information about implicit conversions and stored proc parameters
Msg 537, Level 16, State 3, Procedure sp_BlitzCache, Line 2719 [Batch Start Line 0]
Invalid length parameter passed to the LEFT or SUBSTRING function.
The statement has been terminated._

It does return data to the grid, but I'm not sure if it is missing data because of this.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
This is on a SQL 2016 Enterprise SP1 w/ CU5 on Windows 2016 Datacenter

**Comment by BlitzErik** [comment]
Is this error still occurring? This'll be tough to track down without the query xml that's causing it.

**Comment by BrentOzar** [comment]
If it's in the implicit conversion query, I bet it's in the substrings we're doing in the new section that starts with this line:

`CASE WHEN CHARINDEX('@', qq.c.value('@Expression', 'NVARCHAR(128)')) > 0 `

Because we use a couple other charindex stuff in the substrings, we could check to make sure all these are > 0:

CHARINDEX(',', qq.c.value('@Expression', 'NVARCHAR(128)'))
CHARINDEX('=', qq.c.value('@Expression', 'NVARCHAR(128)'))

**Comment by BlitzErik** [comment]
Yeah, this section needs some reworking. I had notes to myself to grab the raw data first and stick it in a temp table with computed columns for the charindex stuff to make the parsing easier to read and debug.

**Comment by BlitzErik** [comment]
This should be taken care of in #1241

**Comment by mflanker** [comment]
Just downloaded the most recently release and I am getting the same error as goldendba above.
Latin1_General_BIN collation
13.0.4435.0  version

**Comment by BrentOzar** [comment]
@mflanker can you include the exact version of sp_BlitzFirst, and the exact error that you're getting?

**Comment by mflanker** [comment]
Error:
...
Checking for row level security in 2016 only
Performing query level checks
Gathering additional plan level information
Warning: Null value is eliminated by an aggregate or other SET operation.
Attempting to get stored procedure name for individual statements
Trace flag checks
Is Paul White Electric?
Getting information about implicit conversions and stored proc parameters
**Msg 537, Level 16, State 3, Procedure sp_BlitzCache, Line 2719 [Batch Start Line 0]
Invalid length parameter passed to the LEFT or SUBSTRING function.
The statement has been terminated.**
Setting configuration values
Checking for query level SQL Server issues.
Checking for forced parameterization and cursors.
Populating Warnings column
Populating Warnings column for stored procedures
Checking for plans with >128 levels of nesting
Checking for plans with no warnings
Writing results to table.
sp_BlitzCache Finished

sp_blitzfirst version:
DECLARE @Version VARCHAR(30);
SET @Version = '5.9';
SET @VersionDate = '20171101';

**Comment by BrentOzar** [comment]
OK, great. That's not the most recent version. Go ahead and grab the current version and then see what happens. (There's a December release out.) Thanks!

**Comment by BrentOzar** [comment]
Totally welcome!
