### ISSUE TITLE
@@SERVERNAME in CSV

### ISSUE THREAD

**Issue by watheypr** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1227]
feature

It's just a minor change, but would greatly help me

I'm running this on all my prod servers weekly, outputting to a CSV to get emailed to me.
Problem is when I open the CSV I forget which server it's from

Something as easy as... would help tremendously
(DatabaseName 7 @@servername below...

INSERT  INTO #BlitzResults
						( CheckID ,
						  Priority ,
						  FindingsGroup ,
						  Finding ,
						  DatabaseName,
						  URL ,
						  Details

						)
				VALUES  ( -1 ,
						  0 ,
						  'sp_Blitz ' + CAST(CONVERT(DATETIME, @VersionDate, 102) AS VARCHAR(100)),
						  'SQL Server First Responder Kit' ,
						  @@SERVERNAME,
						  'http://FirstResponderKit.org/' ,
						  'To get help or add your own contributions, join us at http://FirstResponderKit.org.'

						);

**Comment by BrentOzar** [comment]
@watheypr well, instead of doing that, I'd suggest outputting to table. When you do that, it includes the server name. (This way we won't break existing functionality for other users.) Can that work instead?

**Comment by watheypr** [comment]
Alas it's all about firewalls and different environments, so can't use a common table :-(

I can change my copy for sure (that's pretty easy for me), but I thought it was an easy good tweak rather than a "break" for other users too - as long as the @@servername is less than 128 chars it shouldn't break
