### ISSUE TITLE
sp_BlitzCache - Must declare the scalar variable "@minimumExecutionCount" warning when @exporttoexcel = 1 parameter specified

### ISSUE THREAD

**Issue by GrzegorzOpara** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1230]
**Do you want to request a *feature* or report a *bug*?**
If you're reporting a bug, include the version number of the script you're using. If it's not the current version, upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build.

I would like to report a **bug** (I am using version: 5.9 released on Nov  1 2017 12:00AM)

**What is the current behavior?**

If I specify @exporttoexcel = 1 parameter, for example: 
`sp_blitzcache @expertmode = 1, @databasename = 'XYZ', @top = 20, @exporttoexcel = 1`

I am getting following warning in the output:
```
Msg 137, Level 15, State 2, Line 54
Must declare the scalar variable "@minimumExecutionCount".
```

I also tried to explicitly set **@minimumExecutionCount** to any value and pass it as an execution parameter, but no luck, the warning is still there. Tried on multiple servers with the same result.

If no @exporttoexcel = 1 parameter specified everything works like a charm.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

I provided an example in previous point.

**What is the expected behavior?**

I would expect no such warning in the output.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Microsoft Windows [Version 6.3.9600]
Microsoft SQL Server 2016 (SP1-CU5) (KB4040714) - 13.0.4451.0 (X64)

I think it was working fine in previous versions of the procedure.

**Comment by BrentOzar** [comment]
Doh! Great catch and great bug report. I found it & fixed it in the above pull request - it'll be in the next release of sp_BlitzCache. Sorry about that!
