### ISSUE TITLE
Power BI Dashboard - Include a template

### ISSUE THREAD

**Issue by CraneAlex** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1236]
The current process for changing the data source within the Power BI file is as follows.
 
> In the toolbar, click the down arrow under Edit Queries, then Data Source Settings, then Change Source. Point it at your own SQL Server – in this case, SQL2017A:
> 
> Click OK, Close, and then the Refresh button in your toolbar.

This can be simplified and made a bit slicker by utilizing parameters and a template (attached), so as to prompt the user for these details when opening the file.

We can specify two parameters: one for the name of the instance, another for the database. Both relating to the instance and database in which the scripts were installed, obviously.

Steps to create the template are as follows. **Note: you need to have already installed the scripts before this will work as the parameters need a valid instance/database to be verified.**

1. Open the FirstResponderKit.pbix from the Power BI folder
2. Click File > Options and Settings > Options > click Query Editor under the 'Global' heading > ensure 'Always allow parameterization in data source and transformation dialogs' is ticked in the Parameters section. Click OK.
3. Click Home on the ribbon. Click the down arrow next to 'Edit Queries' and select Data Source Settings
4. Ensure sql2017b;DBAtools is highlighted, then click Chance Source... in the bottom-left.
5. Under the word Server, click the 'ABC' icon and select New Parameter. Change the name to Instance and description to 'Your SQL Server instance.' (this serves as a tool tip when opening the template later on). Ensure 'Required' is ticked, Type is 'Any', Suggested Values is 'Any value' and Current Value is the name of your own instance which is currently working. Click OK.
6. Under the word Database, click the 'ABC' icon and select New Parameter. Change the name to Database and description to 'This is the database where you installed the scripts from the First Responder Kit.'. Ensure the same options are selected as described in step 5, but make sure Current Value is set to the relevant database name. Click OK, OK, then Close.
7. A yellow bar will appear at the top of the report asking you to apply the changes. Click Apply changes. You may be asked to approve running a 'Native Database Query'. If so, click Run for each prompt. Power BI will go and fetch your data.
8. Once the data has refreshed, click File > Export > Power BI template. Enter a description of 'First Responder Kit'. Click OK. Save it to your desired location.
9. Close Power BI. It will prompt you to save changes, but this relates to the original .pbix file, not the template. Click Don't save.

Open the .pbit file you just saved and you should be prompted for the Instance and Database parameters. Enter them and click Load. Voila. 

[FirstResponderKit.zip](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/1480289/FirstResponderKit.zip)

**Comment by BrentOzar** [comment]
Yay, done! Thanks for the crystal-clear walkthrough, @CraneAlex, I really appreciate it.

**Comment by BrentOzar** [comment]
@BlitzErik - when we package the FirstResponderKit.zip, only include the FirstResponderKit.pbit, not the pbix file. For the release notes - say now the Power BI Dashboard for DBAs prompts you for the server name & database when you open it.
