### ISSUE TITLE
Add @OutputType values "Version","VersionCheck"

### ISSUE THREAD

**Issue by jeffchulg** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1237]
**Do you want to request a *feature* or report a *bug*?**
If you're reporting a bug, include the version number of the script you're using. If it's not the current version, upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build.

FEATURE

For each procedure which have an defined @OutputType parameter, add:

- Version: returns version number
- VersionCheck returns true or false whether the current version is outdated or not
- eventually VersionWithCheckResults

This feature would be helpful for management: running a PoSH script that inventories installed versions of the stored procedures across multiple servers and also check for outdated ones versions would be easy and without the need to load servers more than necessary.

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

- version value ==> only visible when executing the procedures (first row of returned data set)
- version_check value ==> not tested for all but can be part of the results set

**What is the expected behavior?**
returns the value as defined above

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
N/A

**Comment by BrentOzar** [comment]
The procs already have a @VersionDate output parameter you can use for checking versions. Have you tried using that, and why doesn't that get what you need? (I'm definitely open to building something else, but just want to see the specific problems with that first.)

**Comment by jeffchulg** [comment]
Well, with the @versiondate output parameter, you will get the version date, which answers to part of the proposal (the VERSION output) but your need the script to run entirely before getting back the value of @versiondate and it's not necessarily what you want if you just want to check for version.

The second proposal is to run the limited check with id 155 and return its outcome (true or false) as dataset.

The vision is to be able to get 2 things using a simple powershell script:
- a report with the version of each SP across all SQL Server of the corporate (this report could be either per server or per SP version)
- report with all servers with outdated version, which we should "patch"

Don't hesitate to comment back for further details if I didn't clearly express my point

**Comment by BrentOzar** [comment]
Ah, gotcha. Check ID 155 isn't in all scripts, and I'd assume you want to check the versions of everything (sp_AllNightLog, sp_DatabaseRestore, sp_BlitzWho, etc).

So lemme rephrase to make sure I capture the goals right:

* You want to be able to take a version inventory for every stored proc
* You don't want the proc to actually run any code other than the version check (important in the case of stuff like sp_AllNightLog which might fire off restores by default)
* You want the output to consist of the version number, and whether it's outdated or not
* All of the stored procs should function identically

If I got any of that wrong, let me know. Now, further questions:

* How are you going to identify what stored procs you need to check? (We can add stored procs at any time, and I'm wondering if we need to somehow identify the FRK stored procs through extended properties or something)
* How will you know where they live? (These can be in any database)
* If you're checking other stored procs, is there an example of how they behave so we can mimic it? (For example, how are you doing it with sp_WhoIsActive or DBAtools scripts?) Or are we setting the first example? (Figuring out how our stuff needs to mimic others.)

**Comment by jeffchulg** [comment]
I think you got it right :) ! 

- there are two solutions for that: 
1. If you add a new stored procedure, I would have to react and define a test for that procedure
2. If you create a table with the list of applications (that you could eventually use as repository for parameters), the check would be generic.

- My idea would work perfectly for standardized installations (or at least using a standardized login which would be mapped to the appropriate db with the appropriate schema)

- At the moment, I use a table called "Common.ApplicationParams" on each server in which I store the version for all SP I have, but it's not perfect... 

>CREATE TABLE [Common].[ApplicationParams](
>        [ApplicationName]   [varchar](128)  NOT NULL,
>        [ParamName]         [varchar](64)   NOT NULL,
>        [ParamValue]        [varchar](max)  ,
>        [DefaultValue]      [varchar](max) ,
>        [ValueCanBeNULL]    [bit]           DEFAULT 0 NOT NULL,
>        [isDepreciated]     [bit]           NOT NULL,
>        [ParamDescription]  [varchar](max)  NULL,
>        [creationdate]      [datetime]      NOT NULL,
>        [lastmodified]      [datetime]      NOT NULL,
>        CONSTRAINT [PK_ApplicationParams] PRIMARY KEY CLUSTERED (
>           [ApplicationName] ASC,
>           [ParamName] ASC
>       )
>    )ON [PRIMARY]

**Comment by jeffchulg** [comment]
Hi there,

here is an idea that could be added to this ticket: there could be a SP called for instance sp_BlitzLifeCycle or sp_FirstResponderVersionCheck that checks the versions for all stored procedures and returns either a report with all components (sp_Blitz, sp_BlitzFirst,...), their actual version and the expected version and a check status ("OK", "Outdated", "Missing")

This could be better than storing versions in a table...

**Comment by BrentOzar** [comment]
Yeah, I'm not wild about any of these. I definitely don't wanna code another stored proc that has to examine multiple databases looking for the scripts. (sigh) Kinda leaving this here to think through it.

**Comment by BrentOzar** [comment]
Just to document what I'm currently thinking - touching each proc to change its output is a little too painful & risky. It'll be easier to just use extended properties for each proc and set the value as part of the deployment script, and let people check that.

**Comment by MisterZeus** [comment]
Here is a horrible thought:

SELECT
	 SUBSTRING([text],CHARINDEX('sp_Blitz',[text],1), 19) AS SProcName
	,SUBSTRING([text],CHARINDEX('SET @Version',[text],1) + 5, 15) AS VersionString
FROM [master].sys.syscomments sc
WHERE sc.[text] LIKE '%sp_Blitz%'
  AND sc.[text] LIKE '%SET @Version%'

**Comment by michalporeba** [comment]
The FirstResponderKit is great at being a first responder kit. An estate management tools are already out there and perhaps could be leveraged to solve the problem. Installing / updating the sp_Blitz* stored procedures across multiple instances could be easily done using the dbatools (https://dbatools.io/functions/install-dbafirstresponderkit/) and it would be very easy to add another powershell command that will collect all the versioning information from across multiple instances.

With powershell two things would be possible: to check for the @versiondate by analysing the sql module definition so without execution, and in case of running it from a workstation with internet connection to compare that with the latest github version to be able to answer the question whether it is outdated or not.

**Comment by BlitzErik** [comment]
This has been open for a long time. Are we still pursuing it?

**Comment by BrentOzar** [comment]
No, I'm not. If someone wants to code it, they can. Closing.

**Comment by MisterZeus** [comment]
FYI for people needing to audit their sp_Blitz versions, there is a workaround here: https://dba.stackexchange.com/a/197790/143235
