### ISSUE TITLE
sp_Blitz - Advise of recent errors where the backup default location is not accessible

### ISSUE THREAD

**Issue by Adedba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1240]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
No check is conducted for the backup default location:
Right click instance > Properties > Database Settings > Backup field

**What is the expected behavior?**
If the backup default location is not set to a valid path SQL will log an entry in the error log to advise that there was an issue creating and deleting the checkpoint file, this does not show any errors for the user doing the restore so can therefore go undetected. 
I think it would be good to see a check conducted in sp_blitz that will check that there have been no recent checkpoint file errors for the backup default path , if so then flag an informational message, and if its blank then also show a message.

It could resemble code like the following:

```
DECLARE @BackupPath NVARCHAR(255)

IF OBJECT_ID('Tempdb..#BackupPathErrors') IS NOT NULL
DROP TABLE #BackupPathErrors;

CREATE TABLE #BackupPathErrors
(
[LogDate] DATETIME,
[ProcessInfo] NVARCHAR(128),
[Text] NVARCHAR(255)
);

--Get the Backup Directory stored in the Registry for this instance.
EXEC xp_instance_regread N'HKEY_LOCAL_MACHINE', N'Software\Microsoft\MSSQLServer\MSSQLServer', N'BackupDirectory', @BackupPath OUTPUT

IF @BackupPath IS NOT NULL   
    BEGIN 
    --Insert any access errors for the path in the current SQL error log file to the Table #BackupPathErrors
    INSERT INTO #BackupPathErrors ([LogDate],[ProcessInfo],[Text])
    EXEC xp_readerrorlog 0,1,N'The operating system returned the error ''3(The system cannot find the path specified.)'' while attempting ''DeleteFile'' on', @BackupPath

	   --IF any errors are present INSERT a message into #BlitzResults
	   IF EXISTS (SELECT 1 FROM #BackupPathErrors)
	   BEGIN
		  --this part would insert into #BlitzResults advising of recent Checkpoint file creation errors due to invalid backup default location set.
	       SELECT 'Recent errors are present and the default backup location should be checked - currently set to: '+@BackupPath
	   END
    END   

IF @BackupPath IS NULL 
	   BEGIN
		  --this part would insert into #BlitzResults advising that the backup default location has not been set.
	       SELECT 'No value specified for Backup Default path'
	   END
```

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Not aware of any versions that had this check

**Comment by BlitzErik** [comment]
There are a couple issues here:

1. Reading through large error logs is dog slow. Not every shop has a hip and with it DBA to cycle error logs. Does this show up in the default trace?

2. To avoid having to use xp_instance_regread, do you get different results from `SELECT SERVERPROPERTY('InstanceDefaultDataPath')`? 

Thanks!

**Comment by Adedba** [comment]
Would adding some search dates aid the performance of the read log i wonder...

Unfortunately it does not show in the default trace, just tested it :( Also tested SERVERPROPERTY('InstanceDefaultDataPath') but this provides the DATA path rather than the backup path, unfortunately there is no option for retrieving the backup path via the function, that was a cracking idea though shame that didn't work!

Thanks

**Comment by BlitzErik** [comment]
Ah. my bad, mixed up the property you were after there. 

If you come up with another way to grab that info, feel free to open a new issue.

Thanks!
