### ISSUE TITLE
Create Procedure to Examine Columnstore Indexes

### ISSUE THREAD

**Issue by jobbish-sql** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1254]
I am requesting development of a new procedure to check for areas of improvement for columnstore indexes. It can be called something like sp_BlitzColumnStore. I will develop the initial version. It will be targeted for SQL Server 2016+ and will ignore in-memory tables.

sp_BlitzIndex detects columnstore indexes currently but doesn't really give any guidance. I think that there should be a new procedure for columnstore indexes for the following reason: Output result sets and parameters are totally different, code is totally different, no need for 2008 support, and fundamentally we're looking for different things.

I've already talked to Erik about this and he seemed to think that it was a reasonable idea. Below is a design for the stored procedure. Looking for feedback. Thanks!

**Use Cases:**
The person running the script could be a DBA or a consultant whose columnstore knowledge ranges from nothing to expert level. The server may or may not be on fire. Specific use cases:
- A DBA may have inherited a database and wants to check for basic columnstore related errors.
- A DBA may want to double check that their maintenance solution is doing the right things.
- A DBA may want to see if the developers have done any bad things lately.
- A consultant may want to get an idea if poor columnstore maintenance is contributing to performance issues.
- A consultant may want to generate a list of the tables which would benefit the most from an immediate reorg or rebuild.
- A consultant may want to get an idea if columnstore maintenance is being done at all.

**Parameters:**

```
@DatabaseName NVARCHAR(128) = NULL, /*Defaults to current DB always, not yet supported*/
@SchemaName NVARCHAR(128) = NULL, /*Requires table_name as well.*/
@TableName NVARCHAR(128) = NULL,  /*Requires schema_name as well.*/
@SkipAllCCI TINYINT = 0,
@SkipAllNCCI TINYINT = 0,
@TableNamesToSkip NVARCHAR(MAX) = NULL,
@ExpertMode TINYINT = 0,
@BringThePain BIT = 0,
@ReorgSortColumn NVARCHAR(128) = N'[Reorg Calculated Score]',
@ReorgSortColumn NVARCHAR(128) = N'[Rebuild Calculated Score]',
@OutputServerName NVARCHAR(256) = NULL ,
@OutputDatabaseName NVARCHAR(256) = NULL ,
@OutputSchemaName NVARCHAR(256) = NULL ,
@OutputTableName NVARCHAR(256) = NULL ,
@Debug BIT = 0,
@Help TINYINT = 0,
@VersionDate DATETIME = NULL OUTPUT
```

**Result Sets**
There will be up to four result sets displayed depending on what we find. For example, the fourth result set won't show up if there aren't any partitioned CCIs in the database.

```
-- standard result set always returned, can be logged to table:
[Priority]
[Finding]
[Database Name]
[Schema name.Table name]
[More Info]
[TSQL to Fix]


-- second result set for reorg:
[Finding]
[Database Name]
[Schema name.Table name]
[Reorg Calculated Score]
[Table rowcount]
[Deleted Compressed Rowcount]
[Deleted Compressed Rowcount %]
[Delta Store Rowcount]
[Delta Store Rowcount %]
[Small Rowgroup Rowcount]
[Deleted Compressed Rowcount %]
[TSQL to Fix]


-- third result set for rebuild at table level:
[Finding]
[Database Name]
[Schema name.Table name]
[Rebuild Calculated Score]
[Table rowcount]
[Number of Extra Rowgroups]
[Number of Extra Rowgroups %]
[Missing Rows due to Memory Pressure]
[Missing Rows due to Memory Pressure %]
[Standard TSQL to Fix]
[Memory Pressure TSQL to Fix]

-- fourth result set for rebuild at partition level:
[Finding]
[Database Name]
[Schema name.Table name]
[Partition Id]
[Rebuild Calculated Score]
[Partition rowcount]
[Number of Extra Rowgroups]
[Number of Extra Rowgroups %]
[Missing Rows due to Memory Pressure]
[Missing Rows due to Memory Pressure %]
[Standard TSQL to Fix]
[Memory Pressure TSQL to Fix]
```

**Checks**
Below are notes for checks to be included as part of the initial release

Checks that always run:

 - Is the CCI too small? < 102400 rows?

 - Is the table unpartitioned but it has more than 100 M (?) rows?

 - Does a table have too many partitions? >= 1000 ?

 - Are there 3 or more partitions with fewer than 1048576 rows?

 - Is there only a single partition with data?

 - Is there at least one empty partition on the left and right?

 - Is there lots of delta store write activity? Percentage of bulk load versus delta store? Need to filter out NCCI and pure tickle load into CCIs

 - Are there delta stores in read only filegroups?

 - Are there delta stores that have been around for a while? Maybe 15 days?

 - Are there entire partitions or tables with all rows in the delta store?

 - Are there more than 1048576 rows in the delta store for a single table or partition?

 - Are there deleted rows in read only filegroups?

 - Are there fully deleted (total_rows = deleted_rows) rowgroups not marked TOMBSTONE? 

 - Are there more than 1048576 deleted rows for a single table or partition?

Calculate a configurable reorg score to tell people when we need to do something. Factors:	
	 - deleted rows
	 - number of compressed rowgroups < 500k ?
	 - number of rows in delta stores

Calculate a configurable rebuild score (at partition level?). Factors:
	 - total rowgroups compared to min theoretical (ignore dictionary pressure ones)
	 - total mem_pressure
	 - tell people to try a reorg first. also need to warn about memory issue. not sure what other factors are missing for REBUILD...

 - Are there a lot of rowgroups limited by memory pressure? Could consider resolving with a tricky REBUILD.	

 - Are we ineligible for parallel insert due to how the table was defined (IDENTITY column, etc)? Only care if we're doing bulk loads and server MAXDOP <> 1, table card > 100 M

Expert mode (requires Bring The pain):

 - Does the table have BIT columns? Point out these don't work with aggregate pushdown.
	
 - Are there columns hitting dictionary pressure which could be reduced with LOB data types in 2017?

 - Is there a single column in an NCCI that's limiting the size of compressed rowgroups? Maybe it could be dropped from the NCCI?
	
 - Is there BIGINT data hiding in string columns? Sometimes folks define keys as VARCHAR columns. Check stats then check column data if necessary

 - Are there NUMERIC columns which could be defined in such a way to be eligible for aggregate pushdown? Check stats then check column data if necessary, just assume NUMERIC(19, (scale from column)) for now...
	
 - Are there unnecessary floats based on the data stored in them? Check stats then check column data if necessary

**Comment by BrentOzar** [comment]
Wow, this is comprehensive! I love it.

**Comment by ktaranov** [comment]
Hi, @jobbish-sql , @BrentOzar .
I think https://github.com/NikoNeugebauer/CISL Niko Neugebauer can help to create this procedure. Also I can start to create first dirty version (If it is still interesting for community).

**Comment by BrentOzar** [comment]
Joe - did you want to move forward building this? If not, no worries - I'll close the issue. (Just didn't want to leave it lying around - it sounds pretty ambitious.)

**Comment by jobbish-sql** [comment]
Hi Brent,

Okay to close. 2018 didn't go as planned and I ended up not making a lot of
progress on this.

**Comment by BrentOzar** [comment]
No worries at all! Just reading the issue made me tired, heh. It was ambitious. Thanks sir.
