### ISSUE TITLE
sp_BlitzWho  - show context info

### ISSUE THREAD

**Issue by eaglejohn81** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1255]
**Do you want to request a feature or report a bug?**
Feature (probably only with expert mode turned on)

**What is the expected behavior?**
Our application uses context_info() to save application specific details (pid,application user, application session) to have kind of an idea in SQL Server from what application session the query is executed. This is shown in sys.dm_exec_requests,  sys.dm_exec_sessions and sys.sysprocesses.

It would be very helpful when sp_BlitzWho can cast this to varchar and show it...

Thanks!

**Comment by BlitzErik** [comment]
sp_BlitzCache doesn't touch any of those DMVs, and it wouldn't make sense to, since plans in the cache can frequently be different from what's currently executing. 

Perhaps this would make more sense in a different procedure, like sp_BlitzWho, which already touches those?

Just FYI, I don't have any app that uses context_info, so when you say information is in DMVs, you'll have to show us where it is, and what you'd expect to be done with it.

If you want to change this issue to modify sp_BlitzWho, go ahead and update it with the relevant information. If not, you can close it. 

Thanks!

**Comment by eaglejohn81** [comment]
Hi Erik,

Thanks for quick follow up.
Looking for a way to find the application source of the executing/executed queries. It would be helpful to find that from the plan cache, but that is not trivial.

sp_BlitzWho can be of help for long running queries here. We use context_info like this:
select cast(context_info as varchar) as "info" from sys.dm_exec_requests where session_id > 50

info                           
02888:usr00002:rttaad423201000 

(Which in our case means: application pid, application user, application session)
The pid is shown in hostprocess column as well, but the app username is not necessarily the SQL Server user name.  The app session id obviously unknown by SQL Server. That is the main reason we use context_info. 

Let me know if more clarification is required.

Thanks,
Adrian

**Comment by BlitzErik** [comment]
Cool. Did you want to code this in, or did you want us to do it?

Make sure to read the [Contributing guidelines](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md#how-to-request-features).

**Comment by eaglejohn81** [comment]
I'm not a developer, so would vote for you doing it... ~Thanks!

**Comment by BlitzErik** [comment]
Sheesh. I'm only a consultant. Maybe a developer will come along someday ;)

**Comment by SQLGumbo** [comment]
MIT license? ;-)   Sounds simple enough..famous last words.  I may circle back around and give this a whirl if it is approved.

**Comment by BlitzErik** [comment]
I'm fine with adding it, just be aware of #1188 -- there are going to be some changes coming up to sp_BlitzWho, at least for 2012+ result sets.

**Comment by SQLGumbo** [comment]
Adrian,   Just to be clear here.  Are requesting to have the context_info value returned in the sp_BlitzWho result set?   Or are you looking to have the application  (program) name returned?

Eric , in regards to [#1188](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/1188) -- good call.  If this request is for the context_info then a column needs to be added to the SELECT clause of the final result set.  No biggy.  But would it be a column returned when @ExpertMode = 1 ...or how to handle.

Another thought...How often are applications taking advantage of setting CONTEXT_INFO out in the database world?    Maybe I am missing something. [Using Session Context](https://technet.microsoft.com/en-us/library/ms189252(v=sql.105).aspx)

**Comment by eaglejohn81** [comment]
Yes, this is about sp_BlitzWho showing context_info result. We use this in our ERP application to relate database queries back to its originating application session name.
The "program name" shown in the DMVs is not sufficient. It just shows the name of our SQL Server driver. We can start multiple sessions/programs on top of this.

**Comment by SQLGumbo** [comment]
Adding 'unit test' for reference.  

BEGIN
   DECLARE @Context VARBINARY(128);
   SET @Context = CONVERT(VARBINARY(128), 'Test setting in SQL 2014/2016');
   SET CONTEXT_INFO @Context;
   --
   SELECT CONVERT(VARCHAR(128), context_info)  AS [ContextInfo],
          context_info 
   FROM sys.dm_exec_requests
   WHERE session_id = @@spid;
   SELECT * INTO #TEMP FROM sysobjects
END

**Comment by SQLGumbo** [comment]
Adding testing module for reference
BEGIN
   DECLARE @Context VARBINARY(128);
   SET @Context = CONVERT(VARBINARY(128), 'Test setting in SQL 2014/2016');
   SET CONTEXT_INFO @Context;
   --
   SELECT CONVERT(VARCHAR(128), context_info)  AS [ContextInfo],
          context_info 
   FROM sys.dm_exec_requests
   WHERE session_id = @@spid;
   SELECT * INTO #TEMP FROM sysobjects
END

**Comment by SQLGumbo** [comment]
Adding for reference..
BEGIN
   DECLARE @Context VARBINARY(128);
   SET @Context = CONVERT(VARBINARY(128), 'Test setting in SQL 2014/2016');
   SET CONTEXT_INFO @Context;

   SELECT CONVERT(VARCHAR(128), context_info)  AS [ContextInfo],
          context_info 
   FROM sys.dm_exec_requests
   WHERE session_id = @@spid;
   SELECT * INTO #TEMP FROM sysobjects
END

**Comment by BlitzErik** [comment]
Oh lord, yeah, always use the Dev branch.

**Comment by SQLGumbo** [comment]
Thanks!  Looking forward to the review of the pull request.  Will keep an eye out..no hurry.

Jeff (Library volunteer..non-consultant and non-developer :-)

**Comment by BlitzErik** [comment]
Closing this out to address via #1188
