### ISSUE TITLE
FRK Power BI Desktop: Missing Time Slices 

### ISSUE THREAD

**Issue by tcartwright** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1257]
I would like to report a possible bug with the FRK Power BI report. It appears that certain time slices are being excluded by the Blitzfirst query source:

SELECT * FROM dbo.BlitzFirst WHERE Priority BETWEEN 1 AND 199

Currently right now only some time slices show in the graph that have the matching priority.

I would like to see all time slices for every time the job is run. I was able to fix my report by changing the query source for CheckDates to using:

SELECT bf.CheckDate FROM dbo.BlitzFirst bf WHERE bf.priority = 0

Now the graph shows all the time slices, and the quick diagnosis grid still has the correct data.

**Comment by BrentOzar** [comment]
OK, great! Thanks for that, will get that added to the next version.

**Comment by tcartwright** [comment]
For those who wish to make this change before the next release you can edit the CheckDates datasource in the query editor. Then click Advanced Editor. Replace the entire text inside the editor with the below text. Make sure to change the datasource and database.

let
    Source = Sql.Database("DATASOURCE(SERVER)", "DATABASE", [Query="SELECT bf.CheckDate, CheckDateHour = DATEPART(hour, bf.CheckDate) FROM dbo.BlitzFirst bf WHERE bf.priority = 0"]),
    #"Removed Duplicates" = Table.Distinct(Source, {"CheckDate"})
in
    #"Removed Duplicates"

**Comment by BrentOzar** [comment]
Achievement Unlocked: I have manually edited a Power BI data source. Thanks, @tcartwright, closing.
