### ISSUE TITLE
FRK Power BI Desktop: Copy text

### ISSUE THREAD

**Issue by tcartwright** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1259]
This is a feature request for the Power BI Desktop report. I would like a way to copy out text from the report. Especially the query hash more info exec statements. I found this method for getting the data out, but it is quite cumbersome to do this for each query detail.

http://community.powerbi.com/t5/Desktop/How-can-copy-data-in-table/td-p/190302

**Comment by tcartwright** [comment]
Not a dumb question, I am digging into it, but it does not appear to be possible. Lame on their part. Sorry I can delete the request if you want. I already found a request for it in the powerbi site: https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/13341723-right-click-context-menu

**Comment by tcartwright** [comment]
Closed this as it is out of their control. The change has to originate from MSFT Power BI.

**Comment by BrentOzar** [comment]
Thanks. Yeah, totally agreed about it being lame - I was blown away that there wasn't a way to copy/paste stuff out!
