### ISSUE TITLE
FRK Power BI Desktop: Enhancement to Check Hours

### ISSUE THREAD

**Issue by tcartwright** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1269]
I would like a way to check time slices that occur over night. However with the way the sliders work I cannot seem to get that data cleanly.

**Comment by BrentOzar** [comment]
Yeah, unfortunately, this is how time sliders work in Power BI - it sucks pretty bad. Rather than using the time slicer, you'll need to just use the date slicer:

https://powerbi.tips/2016/11/grouping-and-improved-date-slicer/

Note that it filters time as well.

**Comment by tcartwright** [comment]
Brent, sorry I know you closed it, but what about this time slicer? http://blog.pragmaticworks.com/power-bi-custom-visuals-advanced-time-slicer It looks perfect.

**Comment by BrentOzar** [comment]
Yeah, I tried that and couldn’t get it to properly filter all the datasets on the page. You’re welcome to take a shot at it though.
