### ISSUE TITLE
sp_BlitzLock - Fix some duplication issues

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1285]
This is likely just because I keep creating the same couple deadlocks over and over again, so I end up with the same process IDs over and over, but I'd rather be safe here.

**Comment by BlitzErik** [comment]
I had this way over-engineered. I'm just remaking XML that already exists, and getting weird results. 

While the parsing is helpful to get details and aggregate stuff, it's not helpful for reconstructing deadlock conditions. I'm just going to return the deadlock XML as-is, because the results are right.

My hat will taste delicious this evening.

**Comment by BrentOzar** [comment]
HAHAHA
