### ISSUE TITLE
sp_BlitzLock bugs

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1291]
Putting these in a single issue just since it's an early build, didn't wanna bombard you with issues. If you want to go live with any of these still existing, feel free to split 'em out into separate issues to leave as known issues or whatever.

**Checks 1 & 5 (database & login/app totals) not accurate** - it's summing up the total from #deadlock_owner_waiter, but if a deadlock spanned multiple objects, it's counting multiple times. For example, I have 4 deadlocks, each of which involve both the Comments & Votes tables, but it's showing 8 total deadlocks.

**Consistent caps & quoting** - I know, this sounds pedantic, but object_name is sometimes quoted and sometimes not, and finding_group is sometimes quoted and sometimes not. I would just pick one style and roll with it:

![1](https://user-images.githubusercontent.com/245462/33526572-3b00d394-d809-11e7-9414-4f8dc1a9ddac.png)

**Include the sp_BlitzLock version in output** - you can rip off the code from sp_Blitz priority 0 check -1:

```
INSERT  INTO #BlitzResults
						( CheckID ,
						  Priority ,
						  FindingsGroup ,
						  Finding ,
						  URL ,
						  Details

						)
				VALUES  ( -1 ,
						  0 ,
						  'sp_Blitz ' + CAST(CONVERT(DATETIME, @VersionDate, 102) AS VARCHAR(100)),
						  'SQL Server First Responder Kit' ,
						  'http://FirstResponderKit.org/' ,
						  'To get help or add your own contributions, join us at http://FirstResponderKit.org.'

						);
```

**The object_names column XML-style formatting seems odd.** Not sure you wanted to output multi-object deadlocks this way:

```
<objects>StackOverflow.dbo.Comments</objects>
<objects>StackOverflow.dbo.Votes</objects>
```

**Checks 5, 9 showing nulls.** Kicked off 10 folks in SQLQueryStress running in the same deadlock, and checkid 9 is showing null object_names.

![2](https://user-images.githubusercontent.com/245462/33526804-eb734f7a-d80b-11e7-9d68-5a31d9d77db4.png)

Check 5 is showing null finding:

![5](https://user-images.githubusercontent.com/245462/33526831-3bb260ca-d80c-11e7-8e52-1a3659289dce.png)

**CheckId 7 sp_BlitzCache typo** - in the More Info Query, change OnlySqlhandles to OnlySqlHandles. (Stupid case-sensitive servers.)

Looking good, though.

**Comment by BlitzErik** [comment]
- Checks 1 & 5 (database & login/app totals) not accurate: Done
- Consistent caps & quoting: Done, mostly, but it's not me being inconsistent. Some of the output is raw data from the XML, and I don't control it. I'll keep an eye out for anything I might have missed after the first pass.
- Include the sp_BlitzLock version in output: Done
- The object_names column XML-style formatting seems odd: Not sure what you mean. How would you change it?
- Checks 5, 9 showing nulls: Haven't been able to repro
- Check 5 is showing null finding: Haven't been able to repro
- CheckId 7 sp_BlitzCache typo: Done
