### ISSUE TITLE
Add sp_Blitz to verify server Power Plan == Maximum Performance

### ISSUE THREAD

**Issue by korggy** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1309]
I was recently troubleshooting an issue where I moved SQL Server from an old, busted server to a shiny new one but the CPU utilization on the new server appeared much higher than it was before. After much troubleshooting it turned out I'd forgotten to change the new server's Power Profile from Balanced to High Performance. For other people who make this same mistake, it would be great if sp_Blitz could verify that the server's Power Plan was set to Maximum Performance.

**Comment by BlitzErik** [comment]
Howdy! Thanks for the idea. 

Make sure to read the [Contributing guidelines](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md).

Quick question: Do you have a way to do this without using `xp_regread`? Some folks might balk at using a script that calls it.

**Comment by korggy** [comment]
No, unfortunately this is just a drive-by feature request. I'm not a SQL wizard like you guys...

**Comment by BlitzErik** [comment]
Okay, cool. I'm gonna close this one out, because I don't think we wanna get into a debate about using undocumented extended stored procs.

Thanks!
