### ISSUE TITLE
sp_Blitz: Arithmetic overflow error converting expression to data type int.

### ISSUE THREAD

**Issue by CferMN** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1313]
I know there are similar issues to this, but the other posted solutions have not worked for me. I get an "Arithmetic overflow error converting expression to data type int" when running sp_Blitz, version 5.9.5 with version date 20171115 on SQL Server 2008 R2 SP2, 10.50.4000.0 (Build 9200). 

I ran it with @Debug = 1 and the results are in the included file.

[sp_Blitz_Messages.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/1528632/sp_Blitz_Messages.txt)

The instance has a database mirror on it as well as hourly snapshots of that mirror between the hours of 0600 and 1800.

I have two other instances on 2008 R2 that are SP3 where this problem doesn't happen. The instance that is being mirrored is an identical set up of the one where Blitz is breaking and that also can run Blitz without any problems.

**Comment by BlitzErik** [comment]
Howdy -- I wasn't sure how long it would take you to log an issue, so I created one and fixed it here #1310 

If you wanna try the version of sp_Blitz in the [dev branch](https://raw.githubusercontent.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/dev/sp_Blitz.sql) to make sure it works for you, that'd be awesome!

Thanks!
