### ISSUE TITLE
sp_foreachdb Breaks when an instance has AG non-readable secondaries

### ISSUE THREAD

**Issue by amtwo** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1318]
**Do you want to request a *feature* or report a *bug*?**
*Bug*
Version 1.9.5 - 20171115

**What is the current behavior?**
If you run sp_foreachdb on an instance with AG secondary replicas that are *not* readable, it fails with 
Msg 976, Level 14, State 1, Line 35
The target database, 'IAmInAnAvailabilityGroup', is participating in an availability group and is currently not accessible for queries. Either data movement is suspended or the availability replica is not enabled for read access. To allow read-only access to this and other databases in the availability group, enable read access to one or more secondary availability replicas in the group.  For more information, see the ALTER AVAILABILITY GROUP statement in SQL Server Books Online.

The database state is "ONLINE" so you cannot use the existing filter to ignore non-readable secondary replicas. The pertinent information is not contained in 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

Configure an AG where the secondary replicas do not accept connections, then run this query on a server with secondary replicas:
EXEC sp_foreachdb @suppress_quotename = 1, @state_desc = 'ONLINE', @command = 'USE [?]'

**What is the expected behavior?**

Using either existing or new parameters, I should be able to run sp_foreachdb on an instance with non-readable secondary replicas. I would be inclined to use the existing @state_desc = 'ONLINE' filter. Technically the DB's state is ONLINE, but it is effectively offline, since it is unavailable for querying. 

This fix would need to include version-aware logic, since the necessary AG DMOs are not present in all supported versions.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

sp_foreachdb has never been AG-aware

**Comment by BlitzErik** [comment]
Doing an FRK release today. Can you test code quickly?

**Comment by BlitzErik** [comment]
Actually, nevermind, I can't get this in today. Too much stuff with version checking to get through.

**Comment by amtwo** [comment]
I'll have a commit for this sometime today, cause I need it today. but if I miss the boat on today's release, everyone else can wait.

**Comment by BlitzErik** [comment]
Ah, cool. If the timing works out, great.
