### ISSUE TITLE
sp_BlitzCache - String or binary data would be truncated

### ISSUE THREAD

**Issue by rossw99** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1322]
Running 6.0 and hit a problem.  Running on SQL Server 13.0.4435.

I receive the error:
Inserting variables
Msg 8152, Level 16, State 13, Procedure sp_BlitzCache, Line 2980 [Batch Start Line 0]
String or binary data would be truncated.
The statement has been terminated.
Updating procs

I tracked it down to this:
INSERT #stored_proc_info ( SPID,    SqlHandle,    QueryHash,    variable_name,    variable_datatype,    compile_time_value,    proc_name )
SELECT                     vi.SPID, vi.SqlHandle, vi.QueryHash, vi.variable_name, vi.variable_datatype, vi.compile_time_value, vi.proc_name
FROM #variable_info AS vi

I believe the problem is related to the mismatched data types in the #stored_proc_info and #variable_info tables for:
compile_time_value NVARCHAR(128),
proc_name NVARCHAR(300),
variable_name NVARCHAR(128),

vs.

compile_time_value NVARCHAR(4000)
proc_name NVARCHAR(128),
variable_name NVARCHAR(200),

**Comment by BlitzErik** [comment]
Great catch! I'll kick out a fix for you in a minute.

**Comment by rossw99** [comment]
FYI, this is what I was running.

exec dba.dbo.sp_BlitzCache @Top = 20, @SortOrder='reads', @OutputDatabaseName  = 'DBA', @OutputSchemaName = 'dbo', @OutputTableName  = 'sp_BlitzCache_ReadsResults'

**Comment by BlitzErik** [comment]
Cool, thanks. Just to make sure, does it only error when you output to a table?

**Comment by rossw99** [comment]
Just tried without output to table and produced same error.

**Comment by BlitzErik** [comment]
Can you grab the version of BlitzCache [here](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/Issue_1322/sp_BlitzCache.sql) and let me know if it produces an error?

**Comment by rossw99** [comment]
Confirmed working with and without output to table option!

Thanks for the super fast response ;-)

**Comment by BlitzErik** [comment]
Great! Thanks for letting me know, and sorry about the troubles.

**Comment by rossw99** [comment]
All good.  Discovered and fixed in under an hour!

**Comment by HenryLee19** [comment]
Running 6.0 on 13.0.4446.0 and getting the same error as above. For me the issue was similar to above, though slightly different. It was the with the table:

CREATE TABLE #stored_proc_info
(
    SPID INT,
	SqlHandle VARBINARY(64),
    QueryHash BINARY(8),
    variable_name NVARCHAR(128),
    variable_datatype NVARCHAR(128),
	converted_column_name NVARCHAR(128),
    compile_time_value NVARCHAR(128),
    proc_name NVARCHAR(300),
    column_name NVARCHAR(128),
    converted_to NVARCHAR(128)
);

I had [compile_time_value] with length > 128. I changed that column to something greater and then it worked fine.
