### ISSUE TITLE
sp_BlitzCache: String or binary data would be truncated - Temp tables do not match

### ISSUE THREAD

**Issue by dklinger** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1324]
**Do you want to request a *feature* or report a *bug*?**
I think I've found a bug in
Version = '6.0';
VersionDate = '20171201';

**What is the current behavior?**
If I run sp_blitzcache I'm sometimes getting the error:
Msg 8152, Level 16, State 13, Procedure sp_BlitzCache, Line 2981
String or binary data would be truncated.

I think the problem is with these temp-tables:
CREATE TABLE #stored_proc_info
(
    SPID INT,
	SqlHandle VARBINARY(64),
    QueryHash BINARY(8),
    variable_name NVARCHAR(128),
    variable_datatype NVARCHAR(128),
	converted_column_name NVARCHAR(128),
    compile_time_value NVARCHAR(128),
    proc_name NVARCHAR(300),
    column_name NVARCHAR(128),
    converted_to NVARCHAR(128)
);

CREATE TABLE #variable_info
(
    SPID INT,
    QueryHash BINARY(8),
    SqlHandle VARBINARY(64),
    proc_name NVARCHAR(128),
    variable_name NVARCHAR(200),
    variable_datatype NVARCHAR(128),
    compile_time_value NVARCHAR(4000)
);

In line 2987 there is data written from #variable_info to #stored_proc_info, but the length of the corresponding fields does not match.
In my case I've increased the length of variable_name in #stored_proc_info from 128 to 200 (as in #variable_info) which solved my problem. But the same problem may possibly occur with compile_time_value as this is 4000 chars long in the source and 128 in the target.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
I don't think it's easily reproducable as it depends on the length and contens of the underlying SQL-statements.

**What is the expected behavior?**
No error is thrown.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
I'm on SQL Server 12.0.5540.0 and Windows Server 2012 R2.

Regards, Daniel

**Comment by BlitzErik** [comment]
Hi,

Thanks -- yeah, we got another report of that this morning. See #1322.

There's a fix in the dev branch.

Pretty please search closed issue before opening new ones.

Thanks!

**Comment by dklinger** [comment]
Yep, I've seen it a few seconds ago in the git-history. Sorry for that one. Thanks.

**Comment by rsotgia** [comment]
WTF.... would be easier to update the version available for download. I'm struggling finding table creation as DKLinger wrote but cannot find it in the code of 3440 lines

**Comment by BlitzErik** [comment]
@rsotgia not sure what you're talking about. It was released and available for download in the zip file about a month ago.

Sorry that ctrl + f doesn't work on your computer. Perhaps that's operator error? 

Best, 
Erik

**Comment by rsotgia** [comment]
got it. After 5 mins of anger I red error in line 2987 was in sp_blitzcache and not in blitzfirst....
