### ISSUE TITLE
sp_blitz:  alerts do not exist for errors 823, 824 and 825

### ISSUE THREAD

**Issue by sherriekubis** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1334]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
When Alerts are set for 823, 824 and 825, they are reported as non-existing. There is a statement: 
        IF @Debug IN ( 1, 2 )
            RAISERROR('Running CheckId [%d].', 0, 1, 96) WITH NOWAIT;
that makes the next statement of the INSERT INTO #BlitzResults execute even though it shouldn't. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

I copied the code that finds the alerts and ran it, making sure that alerts were truly defined first.  When the code runs, it hits the If @Debug statement, and then always executes the next INSERT INTO #BlitzResults.  

**What is the expected behavior?**
Expected behavior is to not fall through and insert 

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Microsoft SQL Server 2016 (SP1-CU5) (KB4040714) - 13.0.4451.0 (X64)   Sep  5 2017 16:12:34   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor) 
Microsoft Windows Server 2012 R2 Standard  
[Execution extracted from code finds no Alerts.docx](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/1540587/Execution.extracted.from.code.finds.no.Alerts.docx)
Version	6.3.9600 Build 9600

[Execution extracted from code finds no Alerts.docx](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/1540592/Execution.extracted.from.code.finds.no.Alerts.docx)

**Comment by BlitzErik** [comment]
Just to be sure, what happens when you run this?
```
SELECT  *
FROM    msdb.dbo.sysalerts
WHERE   message_id IN ( 823, 824, 825 )
```

**Comment by BlitzErik** [comment]
Also, can you let me know which `@Version` and `@VersionDate` of Blitz you're running?

**Comment by sherriekubis** [comment]
SELECT  *

FROM    msdb.dbo.sysalerts

WHERE   message_id IN ( 823, 824, 825 );



Three results returned, stuck them in an excel spreadsheet.




*********************************************************
Sherrie Kubis

**Comment by sherriekubis** [comment]
I’m so sorry about this … but I can’t figure out how to find the version and version date of Blitz.  Can you send me the commands?

*********************************************************
Sherrie Kubis

**Comment by BlitzErik** [comment]
No special command. When you run Blitz it gives you the version date in the first row.

If it's an older version, please update and try running it again.

![image](https://user-images.githubusercontent.com/11590415/33767491-c7cbcccc-dbef-11e7-93a9-2c91fa212ff5.png)

**Comment by sherriekubis** [comment]
FindingsGroup:  sp_Blitz Aug  1 2017 12:00AM

I’m getting the latest and will respond back.  I thought I had the latest, but now I don’t believe so.


*********************************************************
Sherrie Kubis

**Comment by BlitzErik** [comment]
Ooh yeah that's about 5 months old!

**Comment by BlitzErik** [comment]
I'm going to close this out, let us know if you hit the same issue on newer versions.

**Comment by sherriekubis** [comment]
All is fixed now, sorry it took me so long!  You guys are great, I appreciate the help.



*********************************************************
Sherrie Kubis
[lights][lights][lights][lights][lights][lights][lights][lights][lights][lights]

**Comment by BlitzErik** [comment]
Great! Thanks for being vigilant!
