### ISSUE TITLE
README clarification

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1335]
> How to Get Support
> ...
> Got a question? Ask it on DBA.StackExchange.com. Tag your question with the script name, like sp_Blitz, sp_BlitzCache, sp_BlitzIndex, etc, and we’ll be alerted of it right away.

I think we should clarify this a bit, especially since it doesn't seem like we get notifications in Slack for these tags. 

For support with the scripts, people should open GitHub issues (unless for some reason they're steadfastly opposed to using it)

For questions about things they find IN the scipts, they should post them on dba.se (and we should have a link to existing or a new go code about HOW to ask questions on dba.se).

**Comment by BrentOzar** [comment]
Good idea. Done, and also updated the _readme.txt for the next time we package the FRK.
