### ISSUE TITLE
BUG: sp_BlitzCache gives an error on line 2980

### ISSUE THREAD

**Issue by JanOndrik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1340]
It is script from latest version, 6.0. When executing proc with previous version, 5.9.5, it ran without error message.

**What is the current behavior?**
Here is error from execution:
Msg 8152, Level 16, State 13, Procedure sp_BlitzCache, Line 2980 [Batch Start Line 20]
String or binary data would be truncated.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
I'm not able to provide steps to reproduce this. I would only guess, that this has something to do with large plan, more than 127 XML nodes, or some memory limitation.

**What is the expected behavior?**
In previous version this was handled and no error was shown during execution.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
I'm running this against SQL 2016 SP1 Enterprise. As mentioned before, this was working in previous version of script.

THANKS!
Jan

**Comment by BlitzErik** [comment]
Can you tell me if this still happens with the version 8j

**Comment by BlitzErik** [comment]
Can you tell me if this happens with the version in the dev branch? https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzCache.sql

**Comment by JanOndrik** [comment]
Nope, just faced this issue with the version 6.0 and version date 20171201. Your URL points to script with the same information, but it works without error. I would say, that I've downloaded that version from dev branch yesterday and it wasn't working well. However, thanks for pointing me to working version. If you have time, by chance, please let me know if there was something done on that per mail...
I'll close the issue.

Thanks!
