### ISSUE TITLE
sp_Blitz Observation on broken links and Windows 2016 server info

### ISSUE THREAD

**Issue by JaySpatz** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1341]
I am using version 6.0  (first time using any of these scripts) Just noting the link for Virtual Server is broken
https://BrentOzar.com/go/virtual. 
Also Windows Version is not picking up Windows Server 2016 with the details returning
I have no idea which version of Windows you're on. Sorry.
This is running off of vmware.  It does pick up other server versions however!

**Comment by BlitzErik** [comment]
Sure, what do you get from:

```
SELECT *
FROM   sys.dm_os_windows_info AS owi;
```

**Comment by JaySpatz** [comment]
windows_release	windows_service_pack_level	windows_sku	os_language_version
10.0		7	1033

**Comment by BlitzErik** [comment]
Thanks -- do you mind testing the version here?

https://raw.githubusercontent.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/a244ebb50cc55e3fcdf60806bb3b68914ebd4381/sp_Blitz.sql

**Comment by JaySpatz** [comment]
Looks good.. it now knows I am running a pretty modern version of Windows.  The VM link appears to work now as well!  You guys are quick!

**Comment by BlitzErik** [comment]
Cool, thanks! This'll go in the next version of the FRK. For now, you can keep using that version of Blits.
