### ISSUE TITLE
BlitzFirstWaitStats_Deltas performance

### ISSUE THREAD

**Issue by Oleksandr-Kosariev** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1342]
I call sp_BlitzFirst every 30 minutes and have about 50000 records in the blitz.WaitStats table.
Querying from the WaitStats_Deltas view takes too long (about 30 sec on my server). 
Here is the plan
https://www.brentozar.com/pastetheplan/?id=rJjqg60bG

When I add _LOOP JOIN_ hint for the blitz.WaitStats table joins it takes about 3 sec.
The fastest way query which I managed to write included _LAG_ function, but I think SQL2008 does not support it.

**versions of SQL Server**
SQL Server 2012 SP3

**Comment by BrentOzar** [comment]
OK, cool. For performance tuning, you're welcome to work on adding indexes, changing the queries you use (like hinting loop joins), or keeping less history. It's not really designed for long term data retention - we're focusing on using the Power BI Dashboard, which doesn't need to hit the database every time.
