### ISSUE TITLE
Expression.Error: The key didn't match any rows in the table.

### ISSUE THREAD

**Issue by francescovista** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1347]
**Do you want to request a *feature* or report a *bug*?**

A Bug for "FirstResponderKit.pbix" updated to 15/12/2017

**What is the current behavior?**

![capture](https://user-images.githubusercontent.com/30395256/34129679-d856eab4-e4a9-11e7-9c28-b7de2358af40.PNG)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

I followed all the instructions here https://www.brentozar.com/first-aid/first-responder-kit-power-bi-dashboard/.  
I also run all the installation .sql queries both on master and on the specific database but the error persists

**What is the expected behavior?**

Well, "FirstResponderKit.pbix" should work

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

SQL Server: 

```
Microsoft SQL Server Management Studio						13.0.16106.4
Microsoft Analysis Services Client Tools						13.0.1700.441
Microsoft Data Access Components (MDAC)						10.0.15063.0
Microsoft MSXML						3.0 4.0 6.0 
Microsoft Internet Explorer						9.11.15063.0
Microsoft .NET Framework						4.0.30319.42000
Operating System						6.3.15063
```

Power BI version:

 `2.53.4954.481 64-bit (December 2017)`

This is the first time I install "FirstResponderKit.pbix"

**Comment by BrentOzar** [comment]
Hi. Typically that means you don't have a job set up to run sp_BlitzFirst and populate the data into a table. Let's take a quick step back - post the *EXACT* queries you're using to run sp_BlitzFirst, and then look in the tables & views to see if any rows match.

**Comment by francescovista** [comment]
I first run:

- Install-All-Scripts.sql
- Install-Core-Blitz-No-Query-Store.sql
- Install-Core-Blitz-With-Query-Store.sql

and 

```
EXEC sp_BlitzFirst 
  @OutputDatabaseName = 'DBAtools', 
  @OutputSchemaName = 'dbo', 
  @OutputTableName = 'BlitzFirst',
  @OutputTableNameFileStats = 'BlitzFirst_FileStats',
  @OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
  @OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
  @OutputTableNameBlitzCache = 'BlitzCache';
```

on master.

As it didn't work I later did the same against my target database but the error is still there

**Comment by BrentOzar** [comment]
OK, great! You do need to create the DBAtools database if that's the one you want to use - I assume you've already created it. Now, go look in that database - are the tables & views there? Do the views have data in them?

**Comment by francescovista** [comment]
Nope, I don't have a 'DBAtools' database listed on my database list.  
Where can I find the instructions?

**Comment by BrentOzar** [comment]
The instructions are here:
https://www.brentozar.com/first-aid/first-responder-kit-power-bi-dashboard/

Make sure to read carefully - this is the line you missed:
Create a database to hold your First Responder Kit data, like say FirstResponderKit or DBAtools.

Thanks!

**Comment by francescovista** [comment]
yep, you were right, after I created the database DBATools and run `sp_BlitzFirst ` the tables are there and I think everythgin will be alright. 

I just receive this error: 

![capture](https://user-images.githubusercontent.com/30395256/34130454-bf6c6422-e4ac-11e7-80f8-67f5472ef4f8.PNG)

I will let you know if I have more problems

**Comment by BrentOzar** [comment]
OK, great. If you have more problems, just try re-reading the documentation, and also try chatting over in the #FirstResponderKit channel at https://SQLslack.com. Thanks!

**Comment by francescovista** [comment]
It worked, thank you for your awesomeness

**Comment by BrentOzar** [comment]
Hahaha, live to serve.

**Comment by vdaya** [comment]
Hi Brent
I had the same problem and noted a couple of things...  
1. The sp_BlitzFirst does not always create the "BlitzFirst_PerfmonStats_Actuals" view. I followed same setup process on two servers in an AlwaysOn pair. The secondary created has the view but the primary doesn't.  So I created it manually on the primary... however, it runs really slow now when doing a data refresh.
2. Although I run sp_BlitzCache and send the output to the tabel (and I've verified that the data has been put into the table), the Power BI Dashboard does not show any info in the Query Detail tab.

Can you please advise further.

**Comment by BrentOzar** [comment]
@vdaya if you have issues, please create a new issue. Create one separate issue per problem that you're running into. You may also want to chat in the #FirstResponderKit channel at http://sqlslack.com - when you have usability problems, that can be a little quicker to avoid back-and-forth problems.
