### ISSUE TITLE
Query column in sp_Blitzlock

### ISSUE THREAD

**Issue by rminder** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1348]
**Do you want to request a *feature* or report a *bug*?**
Bug, perhaps, with 1.0 of sp_Blitzlock

**What is the current behavior?**

The query output column doesn't contain the actual query. For example, for the row which contains the victim group, I always see this: <inputbuf>
Proc [Database Id = 5 Object Id = 2080778520]   </inputbuf>

And then for the non-victim query, I see a fragment like this: <inputbuf>
(@0 datetime2(7),@1 decimal(7,2),@2 int,@3 bigint,@4 bit,@5 bigint)update [dbo].[Schedule]
set [TimeOUTD] = @0, [Duration] = @1, [Status] = @2, [Flags] = @3, [IsVisit] = @4
where ([ScheduleID] = @5)
</inputbuf>

**What is the expected behavior?**

I would expect to see the entire query?

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

SQL Server 2014 (12.0.4237.0)

**Comment by BrentOzar** [comment]
So if you look in database 5, and query for that object ID, do you see a stored procedure?

**Comment by BlitzErik** [comment]
Can you run with `@Debug = 1` and check the source tables? We don't do modify any of the data from the input buffers in the XML.

**Comment by rminder** [comment]
Yes I can see a stored procedure for that object. But, if the stored proc has multiple queries, there is no way to tell which query caused the deadlock. And, when the victim is not a stored proc, I just see a query fragment. Am I missing something or is this all we can expect to see? Without being able to see the actual queries involved, I'm not sure I see the full value in this. But I could be missing something.

**Comment by BlitzErik** [comment]
Please see my note about running with `@Debug = 1`

If there's an improvement you can make, feel free to contribute to add value. It's open source, after all.

Thanks!

**Comment by rminder** [comment]
Running the script with @Debug = 1 does display the SQL statements, at least part of each statement. There must be a limit to the number of characters of the SQL statement, SQL Server includes in the deadlock XML information. So i guess there isn't much you can do about that. At least with SQL 2016+ and higher, the Query Store can be used to retrieve the full queries since there's enough info the sp_BlitzLock output to find that out.

**Comment by BlitzErik** [comment]
Okay, yeah, nothing I can do about that. Gonna close this out as "Can't Fix", hahaha.
