### ISSUE TITLE
sp_BlitzLock: XML parsing: line 2, character 105, illegal qualified name character

### ISSUE THREAD

**Issue by DaleKBurrell** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1350]
sp_BlitzLock
SET @Version = '1.0';
SET @VersionDate = '20171201';

Gave me the following error on first run.
Msg 9455, Level 16, State 1, Procedure sp_BlitzLock, Line 596 [Batch Start Line 0]
XML parsing: line 2, character 105, illegal qualified name character

A fix is to change
`CONVERT(XML, N'<inputbuf>' + d.inputbuf + N'</inputbuf>') AS query,`
to
'CONVERT(XML, N'<inputbuf><![CDATA[' + d.inputbuf + N']]></inputbuf>') AS query,'

because for me it was the '<' in the query which broke the XML.

(sorry I haven't time to work out how to do pull requests right now).

**Comment by BlitzErik** [comment]
So we're on the same page, your code change stop bringing in all query text, no?

**Comment by DaleKBurrell** [comment]
Sorry - copy & paste fail. Should have been:

`CONVERT(XML, N'<inputbuf><![CDATA[' + d.inputbuf + N']]></inputbuf>') AS query,'

**Comment by BlitzErik** [comment]
Okay, cool. Is this something you want to contribute? I'm fine either way

**Comment by BlitzErik** [comment]
I've copy and pasted this directly into sp_BlitzLock, and I'm getting an error. Was something lost in GitHub translation?

```
Msg 9455, Level 16, State 1, Procedure master.dbo.sp_BlitzLock, Line 613 [Batch Start Line 264]
XML parsing: line 1, character 2, illegal qualified name character
```
