### ISSUE TITLE
sp_DatabaseRestore -- Piecemeal Restore

### ISSUE THREAD

**Issue by reharmsen** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1354]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
There seems to be no option to do a Piecemeal Restore

**What is the expected behavior?**
Be able to do a Piecemeal Restore

Would be nice if sp_DatabaseRestore would be able to support a Piecemeal Restore.
Ola's backup procedure is able to only backup Read/Write filegroups.

This way we would be able to restore our primary filegroups first and get the database online.
After this our read only filegroups can be restored.
Also we would be able to only 'refresh' our primary filegroups while keeping the read-only parts online.
This would save a lot in restore time in our DTA cycles where we often restore production databases (Develop, Test, Accept)

**Comment by BrentOzar** [comment]
@reharmsen - interesting! Welcome to the project. That does indeed sound like it'd be interesting to have.

Here's the contributing guide that explains how to get started building the feature you want:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

For something this complex, you probably want to propose:

- How you want to implement the feature
- What parameters you want to add to support it

You can add those into this issue, or if you want, check out the contributing guide about how to jump into the Slack channel and talk through your ideas with the community in real time to get faster feedback.

If you wanted someone else to code it for you, just let me know and I can close the issue - we don't do free code builds here, unfortunately.

**Comment by reharmsen** [comment]
I expect to get started with this in Januari 2018

**Comment by BrentOzar** [comment]
OK, great! No rush at all. Happy holidays!

**Comment by BlitzErik** [comment]
Hi there! Just wanted to check in on this since we haven't heard from you in a while. 

Are you still interested in contributing this code?

Thanks!

**Comment by reharmsen** [comment]
It's still on my list.
Guess we better close this for now, when I get anything I will open a new issue and a pull request.
