### ISSUE TITLE
sp_blitzLock execution error

### ISSUE THREAD

**Issue by VirudhsRaman** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1355]
**Do you want to request a *feature* or report a *bug*?**
**BUG**
If you're reporting a bug, include the version number of the script you're using. If it's not the current version, upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build.

**What is the current behavior?**
The procedure throws an error when run complaining "illegal qualified name character".

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
Just executing the sp_blitzlock throws the error after running for few seconds.

**What is the expected behavior?**
Results without errors.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2016. I am a first time user of the FirstResponderKit and so I cannot comment on its past version behavior.

![sp_blitzlock error](https://user-images.githubusercontent.com/34776389/34306748-6134ce3e-e70a-11e7-8664-210e68362cc3.jpg)

**Comment by BlitzErik** [comment]
This already has an open issue here #1350
