### ISSUE TITLE
sp_blitzIndex - DEFAULT FillFactor

### ISSUE THREAD

**Issue by VirudhsRaman** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1356]
**Do you want to request a *feature* or report a *bug*?**
**FEATURE**
If you're reporting a bug, include the version number of the script you're using. If it's not the current version, upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build.

**What is the current behavior?**
Missing Index queries supplied by sp_blitzIndex is using a default fill factor of 100. It would be ideal if this configuration is not defaulted like online & sortinTempDB. Considering the fact most of the recommendations are for Non-Clustered Index, a fill factor of 100 is not the ideal choice.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
Not applicable.

**What is the expected behavior?**
Should you need to default a value, then default the value to 90
.
**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Not applicable.

**Comment by BlitzErik** [comment]
We're going to have to agree to disagree on this one. Check out Brent's video here for why we leave it at 100: https://groupby.org/conference-session-abstracts/why-defragmenting-your-indexes-isnt-helping/

**Comment by VirudhsRaman** [comment]
Interesting take on FillFactor. Thanks!

Regards
Virudhachalam Raman
Vice President - Application Development & Support
Healix, Inc.
14140 SW Freeway, Ste 400, Sugar Land, TX 77478
P: (281) 295-4251   C: (281) 450-8599  E: vraman@healix.net<mailto:vraman@healix.net>

 [Description: Description: Description: cid:image001.jpg@01CE2579.753B63A0]

This e-mail and any files transmitted with it are confidential and are intended solely for the use of the individual or entity to whom they are addressed. If you are not the intended recipient or the person responsible for delivering the e-mail to the intended recipient, be advised that you have received this   e-mail in error, and that any use, dissemination, forwarding, printing, or copying of this e-mail is strictly prohibited under 18 U.S.C. § 2511.
