### ISSUE TITLE
sp_BlitzLock - Inaccurate Results

### ISSUE THREAD

**Issue by VirudhsRaman** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1357]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
The Event_Date column is presenting date time inaccurately. It's showing future date and time for a deadlock it is reporting as already occurred. Or may be it has a "MinorityReport" sixth sense and it is predicting a deadlock that is to occur. LOL. Aren't you guys awesome?

**What is the expected behavior?**
Dah! Accurate results. :). Since we were desperate to find how our index tuning had positively impacted the deadlocks, we went fishing for a more accurate and reliable deadlock discovery query and found the following: https://www.sqlshack.com/monitoring-sql-server-deadlocks-easy-way/
I am just sharing it here in hopes you can incorporate some of the techniques presented on this article into sp_BlitzLock.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2016

**Comment by BrentOzar** [comment]
The Event_Date is taken from the deadlock graph. Can you open up the graph and see what the value is in there? I'm guessing it's because the server's in a different time zone than you might expect, or the server's time zone is in UTC.

About taking someone else's query and importing it to sp_BlitzLock - unfortunately, that's not how copyright works, heh.

**Comment by BlitzErik** [comment]
All the date values we get are from the deadlock XML. We don't change anything, just extract.

Best of luck with the other script.

**Comment by VirudhsRaman** [comment]
Thank you gentlemen. Appreciate all the awesome work you do here. Honestly, a big fan of you all's work. 

The sharing of the article was in good will and faith to only make this one blip on the FirstResponderKit be rectified.

**Comment by HolisticDeveloper** [comment]
From what I have seen, extended events like the deadlock event are always captured in UTC regardless of the server's local time zone.
