### ISSUE TITLE
sp_Blitz -- Middle ground for getting the active power plan

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1359]
We've gotten a number of requests for this, and I'd love to have it, but I don't want to use `xp_regread`. Tinkering with PowerShell a little bit, I came up with a possible workaround. If `xp_cmdshell` is already active, we can do this. 

I'll leave this open for comment for a bit. There are probably pitfalls that aren't totally obvious, like I'm sure there are conditions that would cause the powershell call to fail or something. As far as I can tell this is pretty PowerShell version agnostic, though.

```
IF EXISTS (
	SELECT 1
	FROM sys.configurations AS c
	WHERE name = 'xp_cmdshell'
	AND c.value_in_use = 1 )

		BEGIN
		
			CREATE TABLE #output (clob VARCHAR(8000))
			
			DECLARE @cmd varchar(8000) = 'powershell.exe -Command Get-WmiObject -Class win32_powerplan -Namespace root\cimv2\power -Filter "isActive=''true''"'
			INSERT #output (clob)
			EXEC xp_cmdshell @cmd
			
			SELECT *, SUBSTRING(o.clob, CHARINDEX(': ', o.clob) + 2, LEN(o.clob)) AS power_plan
			FROM #output AS o
			WHERE clob LIKE 'ElementName%'
			
			DROP TABLE #output
		
		END

```

**Comment by wqweto** [comment]
Is this like `powercfg /list | findstr /c:") *"` w/o PS?

**Comment by BlitzErik** [comment]
WOOHOO! 

You had me at "without PowerShell"

**Comment by BlitzErik** [comment]
Confirmed that this also works:

```
IF EXISTS (
	SELECT 1
	FROM sys.configurations AS c
	WHERE name = 'xp_cmdshell'
	AND c.value_in_use = 1 )

		BEGIN
		
			CREATE TABLE #output (clob VARCHAR(8000))
			
			DECLARE @cmd varchar(8000) = 'powercfg /list | findstr /c:") *"'
			INSERT #output (clob)
			EXEC xp_cmdshell @cmd
			
			SELECT *, SUBSTRING(o.clob, 
								CHARINDEX('(', o.clob) + 1, 
								CHARINDEX(')', o.clob, CHARINDEX('(', o.clob)) - CHARINDEX('(', o.clob) -1
								) AS power_plan
			FROM #output AS o
			WHERE clob IS NOT NULL
			
			DROP TABLE #output
		
		END

```

**Comment by BlitzErik** [comment]
If we wanted to do this with `xp_regread`, we'd have to:

1. Get the guid of the current active power scheme:
![image](https://user-images.githubusercontent.com/11590415/34573290-bef65e16-f141-11e7-8975-8243d1c9ca2e.png)

2. Get the friendly name from the right key:
![image](https://user-images.githubusercontent.com/11590415/34573330-df2e2df8-f141-11e7-928c-2558efd12837.png)

**Comment by BlitzErik** [comment]
Or I'm an idiot and there are only three possible GUIDs it could be.

**Comment by BlitzErik** [comment]
It looks like this will be a good first stab:

```
DECLARE @outval VARCHAR(36);

EXEC master.sys.xp_regread @rootkey = 'HKEY_LOCAL_MACHINE',
                           @key = 'SYSTEM\CurrentControlSet\Control\Power\User\PowerSchemes',
                           @value_name = 'ActivePowerScheme',
                           @value = @outval OUTPUT;

SELECT  CASE @outval
             WHEN 'a1841308-3541-4fab-bc81-f71556f20b4a'
             THEN 'power saving'
             WHEN '381b4222-f694-41f0-9685-ff5bb260df2e'
             THEN 'balanced'
             WHEN '8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c'
             THEN 'high performance'
        END;
```

**Comment by wqweto** [comment]
There are also custom power schemes that vendors like to setup (or users fiddle with).

Probably will need an additional `xp_regread` to get the `FriendlyName` and then on retval an `ELSE` case -- on custom plans the name seems not to be localized from DLL resources.
