### ISSUE TITLE
Section 2 of contributing documentation

### ISSUE THREAD

**Issue by js0505** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1360]
**Do you want to request a *feature* or report a *bug*?**
Update Documentation on CONTRIBUTING.md

**What is the current behavior?**
git checkout master
git pull upstream master

**What is the expected behavior?**
I have found that when you have your own local repository that git pull upstream master can be flaky.

I recommend using the following process for section 2.
git fetch origin
git checkout master
git merge origin/master

**Comment by BrentOzar** [comment]
@js0505 sure, go ahead and make that change to the documentation. I'll assign you to it. I have to confess that I have no idea what you're talking about, hahaha, so I'll trust you on this. :-D

**Comment by BrentOzar** [comment]
@js0505 I'm going to go ahead and close this since you haven't done it, but if you change your mind and wanna do it, feel free to reopen this and do a pull request. Thanks!
