### ISSUE TITLE
Feature Request - Avoid Early Blitz Warnings when running SQL Server Checklist

### ISSUE THREAD

**Issue by briangithex** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1362]
If running through the current SQL Server Setup Checklist in the First Responder Kit, section 6.11 suggests:

> Usefree scripts from Ola Hallengren to create customized SQL Server Agent Jobs: http://ola.hallengren.com/

Section 9.1 suggests running: `exec sp_Blitz @CheckServerInfo=1` .

Blindly following these suggestions results in a "Tables in the Master Database" warning ( https://www.brentozar.com/blitz/tables-master-database/ ).

Being capable of passing sp_Blitz when working with a clean SQL install seems ideal.  Possibly 6.11's suggestion to use Ola's scripts should say something like "(Avoid polluting the master database by creating a DBATools database and running the scripts there)".  Or, if you feel that polluting the master database with Ola's logging table is fine, maybe add a special rule which drops the priority in the specific case of that table (though that approach is rather dirty).

**Comment by BrentOzar** [comment]
@briangithex - there's no such thing as "passing" sp_Blitz. sp_Blitz is just a list of things to be aware of on your server. I do admire your goal to get a perfect score though! This won't be something we'll be doing, though - if you want to code it yourself, you can - here's the contributing guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

**Comment by briangithex** [comment]
@BrentOzar : I'm happy to do so.  Please post the source to the SQL Server Setup Checklist PDF on Github, as well as instructions on how to generate the PDF.

**Comment by BrentOzar** [comment]
Oh, no, it wouldn't be the setup guide changing - that's not open source. I'm just saying you could change sp_Blitz if you want. Go ahead and read through that setup guide.

**Comment by briangithex** [comment]
@BrentOzar I'm using this location to point out what I consider an omission/inconsistency in your setup guide because the _readme.txt included in the kit suggested posting any suggestions to firstresponderkit.org (i.e., here).

Personally, I agree with your suggestion on https://www.brentozar.com/blitz/tables-master-database/ that it might be preferable to put such utilities tables in a separate database, but it was not something I considered until sp_blitz pointed it out...at which point I was mildly annoyed at your setup guide.

That said, I'll defer to your expertise.  If you're OK with merging in a change to sp_blitz which hard-codes a special case for `CommandLog`, I'll push it.

**Comment by BrentOzar** [comment]
OK, great! You're clear to start contributing that change to sp_Blitz. Thanks! Brent

**Comment by briangithex** [comment]
Well, I went through the steps to contribute it, but in the process hit https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/Documentation/sp_Blitz%20Checks%20by%20Priority.md , which didn't really offer any better priorities to use than 200.  Since I personally don't like the idea of using "doesn't report the issue at all" as a special case, there isn't really a better alternative.

I still think this constitutes a flaw in the setup docs, but that's out of scope for the repository.

**Comment by BrentOzar** [comment]
Ok, no problem. Thanks anyway, and hope you enjoy the free scripts and resources.
