### ISSUE TITLE
Documentation fix - sp_Blitz Checks by Priority is missing "Thanks!" check

### ISSUE THREAD

**Issue by briangithex** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1363]
**Bug**
Version number: Experienced on "sp_Blitz Dec  1 2017 12:00AM".  Also verified in the latest commit of the source code.

**What is the current behavior?**
"Thanks!" is not documented on https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/Documentation/sp_Blitz%20Checks%20by%20Priority.md

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
Visit https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/Documentation/sp_Blitz%20Checks%20by%20Priority.md

**What is the expected behavior?**
Expected "Thanks!" to be documented

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All versions of SQL Server / OS (this is a documentation bug)

**Comment by BrentOzar** [comment]
Great catch! Sure, you're clear to go ahead and make that change. (Based on our other interactions, I'm guessing you've already found the readme and the contribution guide.)

**Comment by BrentOzar** [comment]
Cool, will get this into the January milestone. Thanks!
