### ISSUE TITLE
Truncate on exact VARCHAR length after XML values extraction

### ISSUE THREAD

**Issue by wqweto** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1365]
. . . before inserting into temp tables, instead of terminating w/ error when length is exceeded.

For instance this

            q.n.value('@Column', 'NVARCHAR(256)') AS variable_name,
            q.n.value('@ParameterDataType', 'NVARCHAR(256)') AS variable_datatype,
            q.n.value('@ParameterCompiledValue', 'NVARCHAR(4000)') AS compile_time_value

. . . can be refactored to something like this

            LEFT(q.n.value('@Column', 'NVARCHAR(MAX)'), 256) AS variable_name,
            LEFT(q.n.value('@ParameterDataType', 'NVARCHAR(MAX)'), 256) AS variable_datatype,
            LEFT(q.n.value('@ParameterCompiledValue', 'NVARCHAR(MAX)'), 4000) AS compile_time_value

. . . so that `value` on source XML never bombs out and its result gets manually truncated before going into the temp table.

I can prepare a PR if this seems like a reasonable idea.

**Comment by BlitzErik** [comment]
No, I'd much rather size the columns appropriately. Can you find the plan that caused the issue?

**Comment by wqweto** [comment]
I had troubles with `sp_BlitzCache` from current `Dec 5, 2017` zip release where `#variable_info.compile_time_value` is `NVARCHAR(4000)` but `#stored_proc_info.compile_time_value` is `NVARCHAR(128)` and got `string or binary data would be truncated` error at some point (not the same problem as described in the issue altogether).

Then I noticed that this column is populated from XML with `q.n.value('@ParameterCompiledValue', 'NVARCHAR(1000)') AS compile_time_value` and considered what can be done for worst case scenario in general -- when `ParameterCompiledValue` attrib is more than 1000 characters long.

In latest commits these particular size mismatches seem to be fixed but unbound string sizes in XML would be a constant source of pain when populating temp tables with pretty much "random" sizes on VARCHARs. If XML elements/attributes data has documented upper bound on size then using precise data-type on `value` in preferred of course.

**Comment by BlitzErik** [comment]
If they did, I'd be using them :)

**Comment by wqweto** [comment]
What is the max size of `ParameterCompiledValue` then? Current 4000 seems big but still pretty random and certainly not big enough for some corner cases.

I'm not proposing changing `compile_time_value` column size -- it can safely remain VARCHAR(4000). Just consider populating it in a manner that would truncate the string from XML, not bomb out when a large binary data is encountered in the wild.

**Comment by BlitzErik** [comment]
If you can find the plan that it threw an error on, I can make an adjustment. Right now, I don't even know if that's the value that caused an error. If you figure it out, let me know. 

Thanks!

**Comment by wqweto** [comment]
Challenge accepted!

[ShowPlanXML schema](http://schemas.microsoft.com/sqlserver/2004/07/showplan/sql2017/showplanxml.xsd) does not set upper bound on the attrib

    <xsd:attribute name="ParameterCompiledValue" type="xsd:string" use="optional"/>

. . . only asserts `string` type which looks promising.

Unfortunately further tests on sql2016/2008 show the actually value is trimmed to 256 chars (258 incl. the quotes) so yes, this particular attrib has an undocumented upper bound of 258.

Fortunately unshielded XML parsing is so abundant throughout FRK there's bound to be some low hanging fruits there :-))

**Comment by BlitzErik** [comment]
Took a look at this. Not sure what to do, so leaving it as-is. I see what you mean about the compile time value thing being trimmed, but that's not causing any problems right now.
