### ISSUE TITLE
sp_BlitzCache Error: Line 3317 XML parsing: line 208, character 1, incorrect processing instruction syntax

### ISSUE THREAD

**Issue by jasonseiler** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1376]
using the dev version:
https://raw.githubusercontent.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/dev/sp_BlitzCache.sql

****
Msg 9451, Level 16, State 1, Procedure sp_BlitzCache, Line 3317
XML parsing: line 208, character 1, incorrect processing instruction syntax
--

Think its likely due to a very large missing index xml string >4000 chars

**Comment by BrentOzar** [comment]
Was there anything you were supposed to include in this Github issue, by chance, Jason?

**Comment by BlitzErik** [comment]
Jason, can you try the version of blitzcache here?

https://raw.githubusercontent.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/b9a929655b3963d1a229c928c67c2f880d5f4f9f/sp_BlitzCache.sql

I took a couple stabs at correcting possible issues.

**Comment by jasonseiler** [comment]
I'm also finding that the xml parsing error is intermittent, I've been able to run it several times without error so still trying to find the exact code being called

**Comment by jasonseiler** [comment]
Erik, when running your new version you posted, I'm running into these errors:

Checking for plans with no warnings
Writing results to table.
Msg 207, Level 16, State 1, Line 1
Invalid column name 'MinSpills'.
Msg 207, Level 16, State 1, Line 1
Invalid column name 'MaxSpills'.
Msg 207, Level 16, State 1, Line 1
Invalid column name 'TotalSpills'.
Msg 207, Level 16, State 1, Line 1
Invalid column name 'AvgSpills'.
sp_BlitzCache Finished

**Comment by BlitzErik** [comment]
Yep, that's a breaking change in this release.

Microsoft added [more information](https://support.microsoft.com/en-us/help/4041814) to some DMVs, and the BlitzCache output table changed. There are no release notes, because this hasn't been released yet.

How Agile is that??

Anyway, if you want to add them, you can just run this.

```
ALTER TABLE dbo.YourTable ADD 		
		MinSpills BIGINT,
		MaxSpills BIGINT,
		TotalSpills BIGINT,
		AvgSpills MONEY
```

**Comment by jasonseiler** [comment]
Adding those columns to the table worked, and it ran without error... although now i'm not sure if its solved because the prior code only intermittently errored out. Will continue testing and let you know.

**Comment by BlitzErik** [comment]
Okay, cool, thanks. If you don't run into it again, feel free to close this out. I'm gonna push the code from this branch. If you do run into it again, you have a couple options

1. Run BlitzCache alone and use `@Debug = 1`. This'll do a select out of all the temp tables that it populates, and you can potentially track down large/rogue data from them.

2. Take a look at plans returned by BlitzCache for large/rogue data in the XML

Thanks!
