### ISSUE TITLE
sp_BlitzCache - Add index creation syntax options to missing index requests

### ISSUE THREAD

**Issue by js0505** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1378]
This really is not a bug nor a unique feature, however, when executing sp_BlitzCache and there are missing indexes, the script only outputs the create index portion without any of the additional "WITH" syntax.

Expected behavior would be to have all of the optional syntax items in the output of the xml.

This behavior should be universal across all sql versions and replicate that of sp_BlitzIndex to also include compression option.

**Comment by BlitzErik** [comment]
Do you want to take a stab at adding this to BlitzQueryStore, too? They both have the same column.

**Comment by BlitzErik** [comment]
DItto this one. Doing some cleanup.
