### ISSUE TITLE
sp_BlitzCache Invalid column name min_spills, max_spills, total_spills

### ISSUE THREAD

**Issue by Kilsgaard** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1381]
I have tried to get sp_BlitzFirst running on my MS SQL 2017 14.0.3008.27.
But I get the following errors:

**Comment by BlitzErik** [comment]
Apply CU3 and it will work.

**Comment by Kilsgaard** [comment]
Oh had not seen Cu3 was released :o
But now is it working perfect.

Thanks

**Comment by BlitzErik** [comment]
At the risk of sounding rude, I'd politely ask that you read release notes:

https://www.brentozar.com/archive/2018/01/first-responder-kit-release-cold-not-release/

![image](https://user-images.githubusercontent.com/11590415/34830408-be372c6a-f6b1-11e7-98ca-9c96a4de5652.png)

**Comment by Kilsgaard** [comment]
I am so sorry missed that, think it is time to get my eyes checked :O

**Comment by KaiserSozei87** [comment]
had same problem. But i got my version of BlitzCache from first responder today. Will try and find CU3 update where it may be to fix.

**Comment by BlitzErik** [comment]
@KaiserSozei87 -- it's [pretty easy](https://support.microsoft.com/en-us/help/4052987/cumulative-update-3-for-sql-server-2017) to find ;)

**Comment by KaiserSozei87** [comment]
crikey fast response!! Yeah i was having a dull moment. I only just twigged after posting that you meant CU3 of SQL :smiley: ...........downloading as we speak. Brand new env so just trying to get DEV and PROD aligned. Used kit for the first time today. Very impressive. Thanks for the hard work.

**Comment by BlitzErik** [comment]
Glad you're enjoying it! Let us know if there's anything we can do!

**Comment by mschelstrate** [comment]
Actually, there are probably many users of sp_BlitzFrist who can't  update all of their SQL Server to CU3 easily, including me.
Can I revert back to an older version to eliminate this error?

**Comment by BlitzErik** [comment]
@mschelstrate Actually, you should try updating your FRK. A fix was made to avoid this error back in April, in #1529
