### ISSUE TITLE
sp_BlitzFirst: Invalid column names MinSpills, MaxSpills, TotalSpills, AvgSpills

### ISSUE THREAD

**Issue by clabough** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1384]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
error when running sp_BlitzFirst

>Writing results to table.
Msg 207, Level 16, State 1, Line 1
Invalid column name 'MinSpills'.
Msg 207, Level 16, State 1, Line 1
Invalid column name 'MaxSpills'.
Msg 207, Level 16, State 1, Line 1
Invalid column name 'TotalSpills'.
Msg 207, Level 16, State 1, Line 1
Invalid column name 'AvgSpills'.
sp_BlitzCache Finished 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

EXEC sp_BlitzFirst 
  @OutputDatabaseName = 'DBAtools', 
  @OutputSchemaName = 'dbo', 
  @OutputTableName = 'BlitzFirst',
  @OutputTableNameFileStats = 'BlitzFirst_FileStats',
  @OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
  @OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
  @OutputTableNameBlitzCache = 'BlitzCache';

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Currently running 2012 SP4 and this script was working on the previous version of sp_BlitzFirst, but broke with the latest version.

**Comment by BlitzErik** [comment]
Pretty please, with every kind of cheese on top, READ THE RELEASE NOTES:

https://www.brentozar.com/archive/2018/01/first-responder-kit-release-cold-not-release/

![image](https://user-images.githubusercontent.com/11590415/34835431-c8ae5fb8-f6c2-11e7-9cf8-3f97f74d95b2.png)

**Comment by clabough** [comment]
Hit self with hammer. Sorry, I'm usually pretty good at catching those things.

**Comment by msurasky** [comment]
I guess I add my name on the "sorry" list... I also totally missed that Special Note on the Release Notes

Thanks for pointing that out Erik
