### ISSUE TITLE
sp_Blitz incorrectly reporting the default XE diagnostics session as an extra one

### ISSUE THREAD

**Issue by elsimer** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1393]
**Do you want to request a *feature* or report a *bug*?**
sp_Blitz Version 6.1 (20180101 Date) lines 4239-4260 check for extended event sessions that are not standard and are running.

**What is the current behavior?**
`SELECT name
FROM sys.dm_xe_sessions;`
returns several rows that include

- system_health
- AlwaysOn_health
- sp_server_diagnostics session
- hkenginexesession
- telemetry_xevents

Line 4258 excludes names that are not in ( 'AlwaysOn_health', 'system_health', 'telemetry_xevents', '**sp_server_diagnostics**', 'hkenginexesession' )

If I have 1 additional extended event session then I will trip CheckId 176.

**What is the expected behavior?**
I would expect that **sp_server_diagnostics session** would be excluded from the check as well.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
I've tested this on SQL Server 2016 SP1 CU2 and CU7 as well as SQL Server 2008R2 SP3. It looks like this was broken by @BlitzErik commit 1c7c8ee4443dfdaac5bf4ca8cb6a3d52c38cd324 (which was supposed to fix issue #1116 

In the process of adding the exclusion for AlwaysOn_health session, the name of the sp_server_diagnostics session event was altered (because it's also the only extended event session that has a space followed by the word session).

**Comment by BlitzErik** [comment]
Ah, good catch. For some reason I thought the space I had in there was erroneous. 

![image](https://user-images.githubusercontent.com/11590415/35118984-99bb3920-fc61-11e7-804f-06ce726298e8.png)

Did you want to fix this?

Thanks!

**Comment by elsimer** [comment]
I haven't set myself up to contribute fixes yet but I'm going to try to get set up today.
