### ISSUE TITLE
sp_blitzLock 2 query result sets - second set not filtered by specific DB

### ISSUE THREAD

**Issue by jnickle** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1395]
**Do you want to request a *feature* or report a *bug*?**
Bug - Version 1.1 (current)

**What is the current behavior?**
Execute:
  EXEC dbo.sp_BlitzLock @DatabaseName = N'dbName'
Results:
  The 2nd result set is not filtered on the database specified

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**  (see above)

**What is the expected behavior?**
filter the results on the DBName provided

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
2014, not tested in any other versions

**Comment by BlitzErik** [comment]
Sweet, thanks!
