### ISSUE TITLE
Is sp_BlitzCache fix w/o CU3 possible?

### ISSUE THREAD

**Issue by mikethedba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1399]
Erik, et al,

I read the resolution in thread https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/1381, where your recommendation was to apply SQL 2017 CU3.  I also read the thread https://www.brentozar.com/archive/2018/01/first-responder-kit-release-cold-not-release/ to add the four columns to "dbo.YourTable" - I'm guessing that is the table that @OutputTableNameBlitzCache is writing to.

My question is: what if I can't apply CU3?  Am I SOL?

Current environment:
-- I already have those four columns in my BlitzCache table
-- Script @VersionDate = '20180101'
-- SELECT @@VERSION = 
"Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64) 
	Aug 22 2017 17:04:49 
	Copyright (C) 2017 Microsoft Corporation
	Standard Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)
"

This is my first installation and execution of the script sp_BlitzFirst and friends, so I don't have any prior behavior to compare to.

Thanks in advance, and my apologies in advance if I'm overlooking something you've already answered.

Mike

**Comment by BlitzErik** [comment]
Just out of curiosity -- why can't you patch SQL?

**Comment by mikethedba** [comment]
I'm at a client site... honestly I haven't asked them yet.  I'll bring it up later this afternoon when I meet with them.  I anticipate that they'll ask about patching and I want to have an answer ready.

**Comment by BlitzErik** [comment]
Right - since this is a pretty critical patch for Spectre/Meltdown I'd probably advise them to apply it. That's what the conversation was about in Slack. I won't have time to add any logic to check for minor version number in the logic this week. You're welcome to make it locally if it's urgent.

**Comment by mikethedba** [comment]
Dig it.  Thanks!
