### ISSUE TITLE
Problem refreshing data in Power BI Desktop - duplicate values in BlitzCache

### ISSUE THREAD

**Issue by mikethedba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1406]
When I open First Responder Kit and refresh the data, if there are rows with duplicate values in "PercentCPUByType", I get at least two different error messages in the "Refresh" window, "OLE DB or ODBC error: Exception from HRESULT: 0x80040E43", and "Load was cancelled by an error in loading a previous table."  I've attached screen shots of all the error messages I'm seeing.

[sp_Blitz refresh error messages.pdf](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/1690059/sp_Blitz.refresh.error.messages.pdf)

The one error message that I understand is "Column 'PercentCPUByType' in Table 'BlitzCache (2)' contains a duplicate value '<value>' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table"

I run the query:

select * -- id, CheckDate, PercentCPUByType 
from BlitzCache
where PercentCPUByType in (
	select PercentCPUByType 
	from BlitzCache
	group by PercentCPUByType having count(*) > 1
)
order by PercentCPUByType, CheckDate, ID

and it returns a list of the rows in the table with duplicate "PercentCPUByType" values.

If I manually change the values so there aren't duplicate values then the refresh proceeds just fine.

* Why do I have a "BlitzCache (2)" table showing up in the error message; I don't have one in the database
* I'm sure this is something that would have come up sooner - why am I seeing it?

Environment configuration:

select @@VERSION = 
Microsoft SQL Server 2016 (SP1) (KB3182545) - 13.0.4001.0 (X64)   Oct 28 2016 18:17:30   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 6.3 <X64> (Build 16299: ) 

From sp_BlitzFirst:
SET @Version = '6.2';
SET @VersionDate = '20180201'

The Blitz* objects are in the 'master' database, and I've created another database to store the results from BlitzFirst running.

**Comment by 619619** [comment]
Have you modified the relationships in the model or maybe clicked around to "Autodetect..." ?
There is no default relationship that includes "PercentCPUByType", so the error message makes no sense in the current committed version

![image](https://user-images.githubusercontent.com/1709105/36058039-2336993e-0e18-11e8-8641-e617f67c03c7.png)

Can you show me this same screen in your model?

**Comment by BrentOzar** [comment]
@EmanueleMeazzo thanks for chiming in.

@mikethedba - Emanuele is right, this isn't a relationship we built in the distributed Power BI, so I'm guessing you made a change in your Power BI file. I'm going to close the issue, but if you do want to follow Emanuele's instructions on adding this screenshot, go ahead. Thanks!
