### ISSUE TITLE
Sp_blitz New feature request to check if the owner of a database is an existing user

### ISSUE THREAD

**Issue by parlevjo2** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1407]
If I execute sp_helpdb i see many times databases which have no current database owner.
Mostly because the owner of the database was an administrator which has left the company, eg:

name | db_size | owner
--------- | --------- | ---------
dbname | 2284.13 MB | \~~ UNKNOWN ~~

Those can easily be identified:
`SELECT * FROM sys.databases WHERE SUSER_SNAME(owner_sid) IS NULL`

It would be nice if sp_blitz could report these databases.
Note: They are not reported by CheckID 55 'Database Owner <> SA'

I already have written the code. It is almost the same as CheckID 55.
Part of the code which can also be easily executed on its own:
```sql
SELECT  NN AS CheckID ,
        [name] AS DatabaseName ,
        230 AS Priority ,
        'Security' AS FindingsGroup ,
        'Database Owner Unknown' AS Finding ,
        'https://BrentOzar.com/go/owndbunknown' AS URL ,
        ( 'Database name: ' + [name] + '   '
        + 'Owner name: ' + ISNULL(SUSER_SNAME(owner_sid),'') ) AS Details
FROM    sys.databases
WHERE   SUSER_SNAME(owner_sid) is NULL
```

[Link to SUSER_SNAME()](https://docs.microsoft.com/en-us/sql/t-sql/functions/suser-sname-transact-sql)
This is my first time on Github. I already have forked and cloned the project.

**Comment by parlevjo2** [comment]
Hi @BlitzErik ,

How does it works with new CheckID's.
Can I use CheckID 58 for my code ?

**Comment by BlitzErik** [comment]
@parlevjo2 - Please [look here](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/Documentation/sp_Blitz%20Checks%20by%20Priority.md)

**Comment by parlevjo2** [comment]
I would like to make a new CheckID with these characteristics. Open for a debate:

Priority | FindingsGroup | Finding | URL | CheckID
-------- | ------------- | ------- | --------------------------------------- | ----------------
230 | Security | Database Owner is Unknown | https://BrentOzar.com/go/owndbunknown | Current High CheckID + 1

It is based on CheckID 55 which is in the same category.

Priority | FindingsGroup | Finding | URL | CheckID
-------- | ------------- | ------- | --------------------------------------- | ----------------
230 | Security | Database Owner <> SA | https://www.BrentOzar.com/go/owndb | 55

**Comment by BrentOzar** [comment]
Cool, go for it! Sounds good to me.

**Comment by parlevjo2** [comment]
I have published the changes ("sp_Blitz Checks by Priority.md" and "sp_Blitz.sql") to branch 'issue_1407/parlevjo2'.
I have tested the new sp_blitz.sql on SQL Server 2008 R2 and SQL Server 2012

Example output:

FindingsGroup | Finding | DatabaseName | URL | Details | QueryPlan | QueryPlanFiltered | CheckID
-------- | ------------------------- | -------- | ------------------------------------- | ------------------------------------- | ---- | ---- | ---
Security | Database Owner is Unknown | Testdbname | https://BrentOzar.com/go/owndbunknown | Database name: Testdbname   Owner name:  | NULL | NULL | 213

Am I still on the right track (It's the first time I use github) ?

**Comment by BlitzErik** [comment]
You're on the right track. When you're ready for us to see the code, create a pull request.

One other note: you're linking to a URL on our site that doesn't exist. You'll probably wanna use a link that exists instead, that way it's easier for us to drop the wording for the warning on that page (if you don't mind writing it -- I don't know what you'd tell people here that's actionable).

**Comment by parlevjo2** [comment]
Hi Erik,

We have 3 options in my opinion.

1.

**Comment by parlevjo2** [comment]
Hi Erik,

We have 4 options in my opinion:

1. Yan can copy the page https://www.BrentOzar.com/go/owndb to https://BrentOzar.com/go/owndbunknown. Replace "Database Owners <> SA" with "Database Owner is Unknown". Remove the section: "To Fix the Problem Long Term". New Text:
# sp_Blitz® Result: Database Owner is Unknown
When databases are created, the owner defaults to whoever created it. When the owner of a database directs to a Windows Account and the Windows Account has been deleted you end up with a database with an “Unknown” owner.
This part of our SQL Server sp_Blitz script checks sys.databases looking at the SUSER_SNAME(owner_sid) of the owners.  It was contributed by Johan Parlevliet.
## To Fix the Problem
Make SA the new owner because it’s the easiest way to avoid ownership problems when the owner name no longer exists. To make SA the owner on a database, run this T-SQL command:
```sql
ALTER AUTHORIZATION ON DATABASE::ReplaceThisWithYourDatabaseName to sa;
```

2. I could use in my SQL code the url "http://blogs.lessthandot.com/index.php/datamgmt/dbadmin/sql-server-database-owner-unknown/".

3. You make the page https://BrentOzar.com/go/owndbunknown redirect to the url "http://blogs.lessthandot.com/index.php/datamgmt/dbadmin/sql-server-database-owner-unknown/".

4. A combination of 1. and url "http://blogs.lessthandot.com/index.php/datamgmt/dbadmin/sql-server-database-owner-unknown/" on the page.

My choose would be 1., 3. or 4. but you may choose whatever suits you the best.

**Comment by BlitzErik** [comment]
Is the less than dot page yours, or someone elses?

**Comment by parlevjo2** [comment]
Somebodies else page. I do not have a website.

**Comment by BlitzErik** [comment]
Okay, go ahead and leave the URL blank for now. I'll create a page with a script from scratch to use.

Thanks!

**Comment by parlevjo2** [comment]
Hi @BlitzErik ,

I did probably something wrong.
As in the documentation was written I had made a fork from master.
I Created a Pull Request in Github desktop and ended up with these pull request: "parlevjo2  wants to merge 15 commits into BrentOzarULTD:dev from parlevjo2:issue_1407/parlevjo2"
