### ISSUE TITLE
sp_Database_Restore

### ISSUE THREAD

**Issue by BilliousBT** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1409]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
I have three databases named ODS, ODS_Easy and ODS_Hard.   The backups are all stored in the same directory.

This command:
EXEC dbo.sp_DatabaseRestore @Database = 'ODS',@BackupPathFull = 'H:\Backups\',@MoveFiles = 1,@MoveDataDrive = 'G:\SQL\DATA\',@MoveLogDrive = 'L:\SQL\LOGS',@RunRecovery = 1;

Results in the ODS_Easy database being restored and renamed to ODS.

If executed with ODS_Easy and ODS_Hard as the @database parameters the correct databases are restored.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

**What is the expected behavior?**
ODS database is restored.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2016 (13.0.4466.4) and Windows 2012 R2 (RTM).

**Comment by BrentOzar** [comment]
Hmmm, we don't recommend putting multiple database backups in the same folder. If you want to do this, you'll need to write the code to support that - this wouldn't be something we'd tackle. Do you want to write that code? If so, go ahead and check the contribution guide - otherwise just let us know and we can close the issue for you. Thanks!

**Comment by BlitzErik** [comment]
No word back, closing.

**Comment by BilliousBT** [comment]
Sorry got distracted by an outage.   I normally use Ola's solution, so this isn't normally an issue for me.   Current client, however, was all over the place.

**Comment by markstewart-simplifi** [comment]
Hello Brent... I had the same issue and I tracked down the issue and modified one line of code to fix this issue. I hardly feel like a contributor for adding an underscore to one line of code. But muchos gracias for sp_DatabaseRestore. Saved me hours from writing my own solution. 

 ```
-- Find latest full backup
 -- Get the TOP record to use in "Restore HeaderOnly/FileListOnly" statement as well as Non-Split Backups Restore Command
 SELECT TOP 1 @LastFullBackup = BackupFile, @CurrentBackupPathFull = BackupPath
 FROM @FileList
 WHERE BackupFile LIKE N'%.bak'
     AND
     -- The line below modified by MStewart 2Jan2026:  Added +'[_]'+ between the @Database and the N'%'  --
  BackupFile LIKE N'%' + @Database + '[_]' + N'%'
		AND
  (@StopAt IS NULL OR REPLACE( RIGHT( REPLACE( BackupFile, RIGHT( BackupFile, PATINDEX( '%_[0-9][0-9]%', REVERSE( BackupFile ) ) ), '' ), 16 ), '_', '' ) <= @StopAt)
 ORDER BY BackupFile DESC;
```
