### ISSUE TITLE
sp_BlitzFirst - BlitzCache Output Table Error

### ISSUE THREAD

**Issue by mcsaunders** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1412]
**Do you want to request a *feature* or report a *bug*?**
Bug - sp_BlitzFirst version 6.2 / 20180201

**What is the current behavior?**
In a clean database (i.e. First Responder Kit objects do not already exist), the first time sp_BlitzFirst is run with output table parameters an invalid object error is generated for the BlitzCache output table.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
To reproduce, in a clean database run one of the "Install-" scripts to create the stored procs, then run sp_BlitzFirst with output table parameters.

`
EXEC [dbo].[sp_BlitzFirst] 
	@OutputDatabaseName = 'FRK_20180201', 
	@OutputSchemaName = 'dbo', 
	@OutputTableName = 'BlitzFirst',
	@OutputTableNameFileStats = 'BlitzFirst_FileStats',
	@OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
	@OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
	@OutputTableNameBlitzCache = 'BlitzCache';`

> Warning: Null value is eliminated by an aggregate or other SET operation.
Setting up configuration variables
Now starting diagnostic analysis
Capturing first pass of wait stats, perfmon counters, file stats
Beginning investigatory queries
Finished running investigatory queries
Waiting to match @Seconds parameter
Capturing second pass of wait stats, perfmon counters, file stats
Analyzing changes between first and second passes of DMVs
Analysis finished, outputting results
Calling sp_BlitzCache
_Msg 208, Level 16, State 1, Line 39
Invalid object name 'FRK_20180201.dbo.BlitzCache'._
Checking @MinutesBack validity.
Setting @MinutesBack to a negative number
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking plan cache age
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring system databases by default
Setting minutes back filter
Applying chosen sort order
Substituting NULLs for spill columns in older versions of SQL
Adding additional info columns for newer versions of SQL
Getting memory grant information for newer versions of SQL
Substituting NULLs for spill columns in older versions of SQL
Adding SQL to collect trigger stats.
Collecting execution plan information.
Attempting to aggregate stored proc info from separate statements
Computing CPU, duration, read, and write metrics
Update CPU percentage for stored procedures
Gather percentage information from grouped results
Begin XML nodes processing
Gathering high level plan information
Performing compile timeout checks
Performing compile memory limit exceeded checks
Performing unparameterized query checks
Performing index DML checks
Performing table DML checks
Gathering row estimates
Gathering trivial plans
Gathering statement costs
Updating statement costs
Checking for plan warnings
Checking for implicit conversion
Performing busy loops checks
Performing TVF join check
Checking for operator warnings
Checking for table variables
Checking for functions
Checking for expensive key lookups
Checking for expensive remote queries
Checking for expensive sorts
Checking for Optimistic cursors
Checking if cursor is Forward Only
Checking for Dynamic cursors
Checking for bad scans and plan forcing
Checking for computed columns that reference scalar UDFs
Checking for filters that reference scalar UDFs
Checking modification queries that hit lots of indexes
Checking for Spatial index use
Checking for wonky Index Spools
Checking for forced serialization
Checking for ColumnStore queries operating in Row Mode instead of Batch Mode
Performing query level checks
Gathering additional plan level information
Attempting to get stored procedure name for individual statements
Trace flag checks
Is Paul White Electric?
Setting configuration values
Checking for query level SQL Server issues.
Checking for forced parameterization and cursors.
Populating Warnings column
Populating Warnings column for stored procedures
Checking for plans with >128 levels of nesting
Checking for plans with no warnings
Writing results to table.
sp_BlitzCache Finished

This only happens the first time sp_BlitzFirst is run - it looks like the BlitzCache output table is queried before sp_BlitzCache is called, so once the table exists everything is ok.

**Comment by BlitzErik** [comment]
You could even do this in one pass with the regular system views:

```
IF EXISTS (
SELECT  'your mom'
FROM    StackOverflow.sys.schemas AS s
JOIN    StackOverflow.sys.tables AS t
    ON t.schema_id = s.schema_id
WHERE   QUOTENAME(s.name) = '[dbo]'
        AND QUOTENAME(t.name) = '[Votes]'
)
```

**Comment by mcsaunders** [comment]
Thanks Erik. I'm a bit of a newbie when it comes to Git/GitHub but I'd be more than happy to take a look at this.

**Comment by BlitzErik** [comment]
Sure! If you decide to take a pass on it, lemme know and I'll pick it up.

**Comment by MTDatat** [comment]
I am brand new to GitHub.  I downloaded the FirstResponder Kit this week.  When I run sp_BlitzFirst with the parameter @OutputTableNameBlitzCache = 'BlitzCache' I get the following response in SSMS:
Setting up configuration variables
Now starting diagnostic analysis
Capturing first pass of wait stats, perfmon counters, file stats
Beginning investigatory queries
Finished running investigatory queries
Waiting to match @Seconds parameter
Capturing second pass of wait stats, perfmon counters, file stats
Analyzing changes between first and second passes of DMVs
Analysis finished, outputting results
Calling sp_BlitzCache
Msg 208, Level 16, State 1, Line 1
Invalid object name 'DBATools.dbo.BlitzCache'.
I do not have a Table in my DBATools DB named BlitzCache.  Do you have a script I can run that will create this table?
I apologize if I am using this forum wrong

**Comment by mcsaunders** [comment]
@MTDatat The BlitzCache table is created by sp_BlitzCache, there is no need to run a separate script to create it.  This particular issue relates to sp_BlitzFirst trying to query the table before sp_BlitzCache has been called, so the first time it runs the table does not exist.  Now that you've run sp_BlitzFirst once, the table should exist in your DBATools database, and everything should be fine.
