### ISSUE TITLE
Could not load file or assembly System.EnterpiseServices or one of its dependencies.

### ISSUE THREAD

**Issue by iwebsguy** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1413]
Followed the instructions on the first responder page. Ran the query to install, created the database, installed PowerBI, when I go to connect to the server I get the following error

![2018-02-07 09_38_21-](https://user-images.githubusercontent.com/34586483/35931802-aacb582e-0bea-11e8-9705-0e0fdb9cc07f.png)

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Microsoft SQL Server 2017 (RTM-CU3-GDR) (KB4052987) - 14.0.3015.40 (X64)   Dec 22 2017 16:13:22   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 

Desktop is Windows 10 Professional build 1709. Have not tried in other environments yet

**Comment by BrentOzar** [comment]
If you Google for that error message, it looks like a fairly common issue with Power BI. You can follow the steps from there to troubleshoot. (It's not an issue with the First Responder Kit, so closing.)

**Comment by iwebsguy** [comment]
You are correct, I was not running as local admin. Running it as admin resolved the issue. Thanks.

https://community.powerbi.com/t5/Desktop/Unable-to-Connect-to-SQL-Server/td-p/202262
