### ISSUE TITLE
sp_Blitz Collation problem for CheckId 163 (Query Store Disabled) database name

### ISSUE THREAD

**Issue by ktaranov** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1416]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Run: `EXEC sp_blitz` and get for **CheckId 163** result - `? ? 17 Test` (Database name is `ಠ ಠ 17 Test`)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
You can create demo database from this script: https://github.com/ktaranov/sqlserver-kit/blob/master/Scripts/IN_Memory_Example_2017.sql

**What is the expected behavior?**
Return database name `ಠ ಠ 17 Test`

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
```Microsoft SQL Server 2017 (RTM-CU1) (KB4038634) - 14.0.3006.16 (X64)   Oct 19 2017 02:42:29   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 16299: ) (Hypervisor) ```
sp_Blitz version is `6.2`

Simple fix worked for me: Line **4911** change `''?'',` to `N''?'',`.

I can create pull request but I want test on another SQL Server Versions. Also could you confirm this issue?

**Comment by BlitzErik** [comment]
I do not have that issue here! Do you have a ~weird~ collation?

![image](https://user-images.githubusercontent.com/11590415/36052396-869b0062-0dbb-11e8-9e29-40673d57b532.png)

**Comment by BlitzErik** [comment]
OOH YOU'RE RIGHT! Nevermind.

**Comment by BlitzErik** [comment]
Alright, just doing a ctrl+f through the code for `''?''`, I found a bunch of places where Unicode characters would get lost. Gonna expand the issue to tackle those, too.
