### ISSUE TITLE
sp_Blitz - dangerous modules check misses DOS 8.3 filenames

### ISSUE THREAD

**Issue by rainyclouds** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1424]
I'm using version 6.2 of the sp_Blitz script. The dangerous modules check picked up the `C:\ProgramData\Sophos\Web Intelligence\swi_ifslsp_64.dll` module but missed `C:\PROGRA~2\Sophos\SOPHOS~1\SOPHOS~2.DLL`, which happens to be `C:\Program Files (x86)\Sophos\Sophos Anti-Virus\sophos_detoured_x64.dll`.

The output of:
```sql
SELECT company,
	description,
	name
FROM sys.dm_os_loaded_modules 
WHERE company != 'Microsoft Corporation';
```
is:

company | description | name
------------ | ------------ | ------------
Sophos Limited|Sophos Buffer Overrun Protection|C:\PROGRA\~2\Sophos\SOPHOS\~1\SOPHOS\~2.DLL
Sophos Limited|Sophos Web Intelligence|C:\ProgramData\Sophos\Web Intelligence\swi_ifslsp_64.dll

**Comment by BrentOzar** [comment]
Great, thanks for the heads up. Here's the contributing guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md

Did you want to make the code change yourself? Just checking, wasn't quite clear from the issue. (I'm fine either way.)

**Comment by rainyclouds** [comment]
Thanks @BrentOzar 

I'm happy for you to make the change as you see fit.
