### ISSUE TITLE
sp_BlitzBackup Bug - Doesn't push time_zone to listener

### ISSUE THREAD

**Issue by jfoudy** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1425]
**Do you want to request a *feature* or report a *bug*?**
Bug - sp_BlitzBackup v2.2

**What is the current behavior?**
When using the functionality to push backup history to the listener, it creates a table called backupset.  This includes a column called time_zone, but when the data is pushed to the table the time_zone column is not included.  

This is required if you want to create a centralized report and convert the backup times from servers with different timezones.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

Install sp_BlitzBackups on multiple servers with different times zones

Use example in sp_BlitzBackup post to push backup information to a linked server/AG 

Example:
 EXEC sp_BlitzBackups 
@PushBackupHistoryToListener = 1, 
@WriteBackupsToListenerName = 'SQLAGLISTEN', 
@WriteBackupsToDatabaseName = 'msdb_fake', 
@WriteBackupsLastHours = 168

 Now run this query to show you the backup times for each of the servers.  

Select
 time_zone,
 backup_start_date
 ,ISNULL(CAST(DATEADD(HOUR,DATEDIFF(hh, getutcdate(), getdate()) +1,dateadd(MINUTE,(cast(b.time_zone as float) / cast(4 as float) * 60 * -1), b.backup_start_date)) as varchar(19)), ‘~NEVER~’) as ‘Last Backup Date (EST)’
,ISNULL(CAST(DATEADD(HOUR,DATEDIFF(hh, getutcdate(), getdate()) +0,dateadd(MINUTE,(cast(b.time_zone as float) / cast(4 as float) * 60 * -1), b.backup_start_date)) as varchar(19)), ‘~NEVER~’) as ‘Last Backup Date (CST)’
,ISNULL(CAST(DATEADD(hour,DATEDIFF(hh, getutcdate(), getdate()) -1,dateadd(MINUTE,(cast(b.time_zone as float) / cast(4 as float) * 60 * -1), b.backup_start_date)) as varchar(19)), ‘~NEVER~’) as ‘Last Backup Date (MST)’
,ISNULL(CAST(dateadd(MINUTE,(cast(b.time_zone as float) / cast(4 as float) * 60 * -1), b.backup_start_date) as varchar(19)), ‘~NEVER~’) as ‘Last Backup Date (UTC)’
,*
FROM [msdb_fake].[dbo].[backupset] b

You will notice that it can't translate the time of the backups.

Simplified Example: 
Server A (Mountain Time) has backup at 1PM
Server B (Central Time) has a backup at 1PM

When query is ran is should display:
                                            Last Backup Date (EST)  Last Backup Date (CST)  Last Backup Date (MST)
Server A (Mountain Time)   3PM                               2PM                                1PM
Server B (Central Time)        2PM                              1PM                                 12PM

**What is the expected behavior?**
The query should be able to show you the backup time translated into a specific time zone.  This is required so you can have accurate centralized reporting when you have servers on multiple time zones.  
In order for your centralized database/reporting to know if you have a good full backup in the past day and transaction log backup in the past 15 minutes, you must be able to translate the time of the backup on different servers so you can compare with the current date/time of time zone of the centralized server.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2008+ and this has never worked since this stored procedure was created.

In the latest version of this procedure simply change the following lines from:

		SET @StringToExecute += N'INSERT ' + QUOTENAME(@WriteBackupsToListenerName) + N'.' + QUOTENAME(@WriteBackupsToDatabaseName) + N'.dbo.backupset
									' 
		SET @StringToExecute += N' (database_name, database_guid, backup_set_uuid, type, backup_size, backup_start_date, backup_finish_date, media_set_id,
									compressed_backup_size, recovery_model, server_name, machine_name, first_lsn, last_lsn, user_name, compatibility_level, 
									is_password_protected, is_snapshot, is_readonly, is_single_user, has_backup_checksums, is_damaged, ' + CASE WHEN @ProductVersionMajor >= 12 
																																				THEN + N'encryptor_type, has_bulk_logged_data)' + @crlf
																																				ELSE + N'has_bulk_logged_data)' + @crlf
																																				END
		
		SET @StringToExecute +=N'
									SELECT database_name, database_guid, backup_set_uuid, type, backup_size, backup_start_date, backup_finish_date, media_set_id,
									compressed_backup_size, recovery_model, server_name, machine_name, first_lsn, last_lsn, user_name, compatibility_level, 
									is_password_protected, is_snapshot, is_readonly, is_single_user, has_backup_checksums, is_damaged, ' + CASE WHEN @ProductVersionMajor >= 12 
																																				THEN + N'encryptor_type, has_bulk_logged_data' + @crlf
																																				ELSE + N'has_bulk_logged_data' + @crlf
																																				END

**To this, will fix the issue**
```
		SET @StringToExecute += N'INSERT ' + QUOTENAME(@WriteBackupsToListenerName) + N'.' + QUOTENAME(@WriteBackupsToDatabaseName) + N'.dbo.backupset
									' 
		SET @StringToExecute += N' (database_name, database_guid, backup_set_uuid, type, backup_size, backup_start_date, backup_finish_date, media_set_id, time_zone,
									compressed_backup_size, recovery_model, server_name, machine_name, first_lsn, last_lsn, user_name, compatibility_level, 
									is_password_protected, is_snapshot, is_readonly, is_single_user, has_backup_checksums, is_damaged, ' + CASE WHEN @ProductVersionMajor >= 12 
																																				THEN + N'encryptor_type, has_bulk_logged_data)' + @crlf
																																				ELSE + N'has_bulk_logged_data)' + @crlf
																																				END
```
		
		SET @StringToExecute +=N'
									SELECT database_name, database_guid, backup_set_uuid, type, backup_size, backup_start_date, backup_finish_date, media_set_id, time_zone,
									compressed_backup_size, recovery_model, server_name, machine_name, first_lsn, last_lsn, user_name, compatibility_level, 
									is_password_protected, is_snapshot, is_readonly, is_single_user, has_backup_checksums, is_damaged, ' + CASE WHEN @ProductVersionMajor >= 12 
																																				THEN + N'encryptor_type, has_bulk_logged_data' + @crlf
																																				ELSE + N'has_bulk_logged_data' + @crlf
																																				END

**Note: I'm also attaching an older version 1.7.1 of the stored procedure that has the fix in place and has been running in our Production environment for some time now (see lines 1463-1478)**
![sp_blitzbackups_fix](https://user-images.githubusercontent.com/29755239/36214547-a34855e0-11a1-11e8-986e-6ec66b7ef65a.png)

**Comment by BlitzErik** [comment]
Thanks for letting us know!
