### ISSUE TITLE
sp_BlitzFirst - Can get stuck on WAITFOR TIME with certain edge cases.

### ISSUE THREAD

**Issue by Adedba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1429]
**Do you want to request a *feature* or report a *bug*?**
Not really a bug as such, more of an improvement

**What is the current behavior?**
If SQL gets to the IF block containing the WAITFOR TIME with just a few milleseconds and the WAITFOR TIME has a short delay spinning up a thread to start the internal counter this can cause the Procedure to hang with a wait type of WAITFOR as a result of @FinishSampleTimeWaitFor being less than the current time.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
Unable to replicate without fiddling with the code.

**What is the expected behavior?**
To skip the IF block if there is just a few milliseconds to spare

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Only found the issue recently since we started using sp_BlitzFirst to log to a table since the BI release.

Potential fix: 
To add a second to the IF evaluation so that there is ample time to action the WAITFOR TIME

For example: 
    --Current code
    IF SYSDATETIMEOFFSET() < @FinishSampleTime
		BEGIN
		RAISERROR('Waiting to match @Seconds parameter',10,1) WITH NOWAIT;
        WAITFOR TIME @FinishSampleTimeWaitFor;
		END

    --Jump into the IF block if there is at least a second to make up to @FinishSampleTimeWaitFor
    IF DATEADD(SECOND,1,SYSDATETIMEOFFSET()) < @FinishSampleTime
		BEGIN
		RAISERROR('Waiting to match @Seconds parameter',10,1) WITH NOWAIT;
        WAITFOR TIME @FinishSampleTimeWaitFor;
		END

**Comment by BrentOzar** [comment]
Perfect, thanks for working through this, I really appreciate it. I'll get that code into the next release.

**Comment by Adedba** [comment]
no problem at all, glad it was helpful. 
So it happened again but this time we left it running to test a theory whether it would stop 24 hours later... and it did!!  so it doesn't get stuck as such, just waits for the next occurrence of the time to come around .
