### ISSUE TITLE
sp_BlitzFirst Plan Cache Erased Recently Finding

### ISSUE THREAD

**Issue by harvey635** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1446]
**Do you want to request a *feature* or report a *bug*?**
Requesting an enhancement.

**What is the current behavior?**
The Plan Cache Erased Recently finding details indicates that DBCC FREEPROCCACHE was the cause.

**What is the expected behavior?**
Finding details indicate that execution of DBCC FLUSHPROCINDB(<dbid>) may also be the cause.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Discovered on SQL Server 2016. MSDN indicates DBCC FLUSHPROCINDB has been available at least since SQL Server 2005. This enhancement request is only to text string output and not to the condition evaluation logic.

**Comment by harvey635** [comment]
I'm happy to code it, already been working on it. I have to say I like your style (code style at least, can't speak to your fashion sense ;).
The check for the "Plan Cache Erased Recently" finding uses sys.dm_exec_query_stats, to check the aggregate query plans on the instance. Which makes sense, the whole sp is intented to check the instance, not just the context database. As I mentioned in my case I had no DBCC FREEPROCCACHE executions only DBCC FLUSHPROCINDB, and a lot of them, which suggests they were run against all of the databases. 
So updating the details text is easy (and well, done, in my repo) in order to test this DBCC FLUSHPROCINDB has be run against all databases. Is this an edge case that even makes sense accounting for?

**Comment by BrentOzar** [comment]
I don't think so, but you're the one who asked for it. :-)

**Comment by BrentOzar** [comment]
The other thing you can look at is the check for recent DBCC commands - that might also catch it, and you may be able to reuse that logic.

**Comment by BlitzErik** [comment]
We haven't heard back from you on this in a while. I'm going to close the issue out, but feel free to open a new one (or reopen this one) if you decide to work on it in the future.

Thanks!
