### ISSUE TITLE
sp_Blitz - Add check to determine log backups have the ability to take on a secondary Replica.

### ISSUE THREAD

**Issue by Adedba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1452]
**Do you want to request a *feature* or report a *bug*?**
Feature 

**What is the current behavior?**
A Check is conducted whether log backups have taken for each FULL recovery database within the last 7 days , If any databases are found meeting the above criteria then this will output 'Full Recovery Model w/o Log Backups' in the findings column but no check is conducted to check if any of the Availability groups may be set to take transaction log backups on secondary replicas.

Proposal. 
Add variable @SecondaryBackups BIT

Do a check to see if any availability groups on the instance have their backup preference set to 'Secondary only', 'Prefer secondary' or 'Any Replica' and Set @SecondaryBackups to 1 or 0 accodingly.
e.g 
IF EXISTS(SELECT 1 FROM sys.availability_groups WHERE automated_backup_preference > 0)
BEGIN SET @SecondaryBackups = 1 END ELSE BEGIN SET @SecondaryBackups = 0 END

It could be made more specific but then it would involve more use of the availability group dmv's which can become slow with lots of databases/AG's.

If SecondaryBackups  = 1 then change the output text for findings to the following if any database with issues are found:
 
'Full Recovery Model w/o Log Backups however one or more Availability groups allow backups on the Secondary replica, be sure to check there too!'

Just an extra nudge to run on the secondary too if applicable.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?** do not believe this part of the code has had any changes recently.

**Comment by BrentOzar** [comment]
This has been suggested several times in the past (you can search the closed issues). Here's the big problem: AGs can fail over anywhere, at any time. People may have changed the preferred backup flags. People might just be doing it wrong.

Until we can safely check the backup situation across the replicas, like doing linked server queries across all AG members, we're not going to dig deeper in sp_Blitz. We don't want to give people a false sense of security.

Thanks for the suggestion, though! Brent
