### ISSUE TITLE
Error when running sp_BlitzFirst - Invalid column name 'min_spills' and many more similar errors

### ISSUE THREAD

**Issue by PAPutzback** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1455]
Reporting a BUG
The Version of my First Responder Kit is 2.2

Executed the "Install-All-Scripts.sql in Master
Executed Install-Core-Blitz-No-Query-Store.sql in Master
Created a database named DBATools
Executed the following from the site.

 EXEC sp_BlitzFirst 
  @OutputDatabaseName = 'DBAtools', 
  @OutputSchemaName = 'dbo', 
  @OutputTableName = 'BlitzFirst',
  @OutputTableNameFileStats = 'BlitzFirst_FileStats',
  @OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
  @OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
  @OutputTableNameBlitzCache = 'BlitzCache';

**What is the expected behavior?**
On my SQL 2012 server I get results in the window. On my 2017 box I get the following errors.

Collecting execution plan information.
Msg 207, Level 16, State 1, Line 63
Invalid column name 'min_spills'.
Msg 207, Level 16, State 1, Line 64
Invalid column name 'max_spills'.
Msg 207, Level 16, State 1, Line 65
Invalid column name 'total_spills'.
Msg 207, Level 16, State 1, Line 66
Invalid column name 'total_spills'.
Msg 207, Level 16, State 1, Line 66
Invalid column name 'total_spills'.
Msg 207, Level 16, State 1, Line 184
Invalid column name 'min_spills'.
Msg 207, Level 16, State 1, Line 185
Invalid column name 'max_spills'.
Msg 207, Level 16, State 1, Line 186
Invalid column name 'total_spills'.
Msg 207, Level 16, State 1, Line 187
Invalid column name 'total_spills'.
Msg 207, Level 16, State 1, Line 187
Invalid column name 'total_spills'.
Msg 207, Level 16, State 1, Line 420
Invalid column name 'min_spills'.
Msg 207, Level 16, State 1, Line 421
Invalid column name 'max_spills'.
Msg 207, Level 16, State 1, Line 422
Invalid column name 'total_spills'.
Msg 207, Level 16, State 1, Line 423
Invalid column name 'total_spills'.
Msg 207, Level 16, State 1, Line 423
Invalid column name 'total_spills'.

The 2017 version of SQL server is 13.0.2000.64 and the OS is Windows Server 2016

**Comment by BlitzErik** [comment]
Please search closed issues before filing.

#1381
