### ISSUE TITLE
sp_Blitz should skip check 68 (no CHECKDB) for databases < 2 weeks old

### ISSUE THREAD

**Issue by Totty1973** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1466]
**Do you want to request a *feature* or report a *bug*?**
request a feature. It seems to me that check 68 does not check for newly created databases.

**What is the current behavior?**
says "Last good DBCC CHECKDB over 2 weeks old" when running "sp_Blitz Feb  1 2017 12:00AM"

**What is the expected behavior?**
should skip newly created databases or report is as "less severe".

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 10.50.6220 on Server 2008 R2 Standard.

**Comment by BrentOzar** [comment]
Hmm, I'll try to rephrase the question to make sure I understand.

You're saying that if a database was created 3 weeks ago, and it still hasn't had a CHECKDB, that it isn't a big deal?

**Comment by BrentOzar** [comment]
Ahhh, wait, I think I see what you're saying. You're saying that if I do this:

```
CREATE DATABASE [BrandNewDatabase];
GO
sp_Blitz;
```

Then check 68 reports that BrandNewDatabase has never had a CHECKDB.

OK, sure, that feature makes sense. [Here's the Contributing Guide](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md) that explains how to contribute new features or changes. You did the right thing by reporting an issue first and talking to the community about it. The next step is to get the code and work on the change.

If you've got questions as you work through it, feel free to check into the Slack community, or ask questions here. If you don't check the code in within a week or two, we'll close the issue, but you can always reopen it later if you have more time to work on the code.

Thanks!

**Comment by BrentOzar** [comment]
@Totty1973 I didn't hear back from you, and I was in here this morning, so I coded it. Thanks again for reporting it! Should be in the next release of sp_Blitz.
