### ISSUE TITLE
sp_BlitzFirst - Distinguish "RESTORE" and "RESTORE VERIFYONLY"

### ISSUE THREAD

**Issue by dbadave87** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1467]
This is a change request.

When running Ola's log backups with "@Verify = 'Y' " parameter with scheduled sp_bliztFirst job running in the background, this creates an entry in BlitzFirst table and subsequently raises unnecessary alarms for those monitoring PowerBI dashboard.

I have filtered out for now in PowerBI but this is only possible for QueryPlan XML (ergh!):

![image](https://user-images.githubusercontent.com/37111394/37035503-af16f07c-2144-11e8-9fb2-371321794037.png)

Presume we don't want to exclude these in initial capture in case the VERIFY-ONLY consumes resources (however unlikely). 

Could we somehow distinguish between the two?

**Comment by BrentOzar** [comment]
Hmm, dumb questions here:

 - What result set are you trying to filter? Are you talking about a specific check in sp_BlitzFirst's main result set (the prioritized list of problems, like a backup running right now) or sp_BlitzCache's table?
 - Why are you trying to keep it out? Say it's the most resource-consuming query on the system - wouldn't you want to know that?
 - Are you only trying to filter it out of Power BI, or out of the table itself?
 - Have you thought about just deleting the rows you don't want, like in a scheduled job or script?

**Comment by dbadave87** [comment]
Wow, speedy response.

Data is pulled from sp_BlitzFirst's main result set.  Using your PowerBI
template, the highlighted rows below are from backups with VERIFYONLY flag
turned on:


These don't specify they are merely verifying the backup but instead
suggest a genuine "Restore Running" on production server.

I still want to know if its consuming most resources but would like to
distinguish between verify only and a 'genuine' restore.

If I filter out in PowerBI, it looks OK at first but then on next
collection/refresh, I don't get a "No Problems Found" (findingsgroup)
message because there is a record in that table.

Now, I could delete those rows from the table as part of job but would much
rather handle it.

Perhaps a separate 'Finding' header within "Maintenance Tasks Running"
(FindingsGroup) with a lower priority?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by BrentOzar** [comment]
OK, bad news: verifying a restore is pretty similar to the workload of running the actual restore. SQL Server rips through the entire restore process. It's a maintenance task just like running a backup, restore, or a checkdb.

I understand if it's a lower priority to you personally, but it's not a lower priority to the server itself. You can see by watching the server's utilization while the verify runs. (Turning off verifies is usually one of the first things I do on a production box with Ola's scripts - cuts the maintenance times dramatically, and I offload that work to my disaster recovery box - which should be restoring the dbs anyway.)

If you want to do the coding & check it into Github, I'm totally fine with that, though. Is that something you want to do? If so, [here's the contributing guide](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md). If not, just let me know and I can close the issue.

**Comment by dbadave87** [comment]
Fair point on workload being the same. 

To clarify, with AOAG selecting "prefer secondary" would be a better option to reduce workload on primary node:
![image](https://user-images.githubusercontent.com/37111394/37038286-4d2ce166-214c-11e8-90c5-d58fdb47b5d1.png)

**Comment by BrentOzar** [comment]
OK, so do you want to do the coding & check it into Github, I'm totally fine with that, though. Is that something you want to do? If so, [here's the contributing guide](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md). If not, just let me know and I can close the issue.

**Comment by dbadave87** [comment]
I withdraw my request. You can close :)
