### ISSUE TITLE
Backups on databases on Availability Group servers

### ISSUE THREAD

**Issue by JulieOKC** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1471]
Bug - version sp_Blitz Feb  1 2018 12:00AM

Databases are participating in an Availability Group and backups are preformed on the Primary. Secondary servers show databases as not being backed up. Same with log file backups for databases that are in full recovery mode. 

I have found the following on our servers:
For SQL 2016, secondary servers update full backup date for databases.
For SQL 2014, secondary servers do not update full backup date for databases.
For SQL 2012, don't have cluster to test.
No SQL version updates the log file backup date for databases.

To reproduce, create a SQL Server Availability Group cluster, add databases to the availability group, create jobs to do full and log backups for the databases, observe the backup date for each database.

**What is the expected behavior?** Want sp_Blitz to not warn of no backup on secondaries when backup is done on primary.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?** SQL Server 2016, and 2014. OS version Windows Server 2012 R2. Have not tested previous version but doubt it worked in any version of sp_Blitz.

I don't know if you can get this to work as the procedure would need to connect to a separate server.  Maybe just have the warning state that database is part of an AG and backups occur on the primary node.

**Comment by BlitzErik** [comment]
This has been suggested a few times, most recently here: #1452 

It's just not something we can feasibly do.
