### ISSUE TITLE
BlitzCache - Capitalization in the " CREATE TABLE #missing_index_pretty " section

### ISSUE THREAD

**Issue by isujinx** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1478]
The column name "INCLUDE" is capitalized twice in the "ELSE inequality" section of the CREATE TABLE #missing_index_pretty statement.

This causes installation issues for those of us with case sensitive database collations.  SQL 2014 Std.

**Comment by BlitzErik** [comment]
I am one of the people with a case (and accent!) sensitive instance. Can you describe the problem you're running into, in the form of an error message?

Thanks!

**Comment by isujinx** [comment]
Sure thing!    When attempting to run BlitzCache, I get the following error.

Msg 207, Level 16, State 1, Procedure sp_BlitzCache, Line 1141 [Batch Start Line 2]
Invalid column name 'INCLUDE'.
Msg 207, Level 16, State 1, Procedure sp_BlitzCache, Line 1141 [Batch Start Line 2]
Invalid column name 'INCLUDE'.

Changing those two column names to 'include' rather than 'INCLUDE' allows for proper execution.

**Comment by BlitzErik** [comment]
They're [already lowercase](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzCache.sql#L1368) here, and as far back as I can remember, always have been.

![image](https://user-images.githubusercontent.com/11590415/37464373-8336dcb0-282e-11e8-8b48-f5a8a06c3627.png)

Can you let me know which version of BlitzCache you're running? I have a feeling that either someone (or some SQL formatting tool you have?) may have altered the script.

**Comment by isujinx** [comment]
That must have been it!  ApexSQL Refactor changed it.  I just double checked the one I pulled from (this morning, front page of the github) - and its lowercase.  Sorry to bother.

**Comment by BlitzErik** [comment]
No problem! Happy Blitzing!
