### ISSUE TITLE
sp_BlitzFirst: change wait stats details URL to SQLskills

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1482]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Wait types in sp_BlitzFirst currently point to BrentOzar.com's waits page, but we're not keeping that updated with new waits. Instead, let's point here:

https://www.sqlskills.com/help/waits/WAITSTATNAME/

As in:
https://www.sqlskills.com/help/waits/pageiolatch_sh/

Thankfully, it's not case-sensitive, so we can pass uppercase over there.

**Comment by BlitzErik** [comment]
Never heard of them. Are they trustworthy?

**Comment by BrentOzar** [comment]
One of them worked at Digital Equipment Corporation for a number of years, and that's always a good sign.

**Comment by BlitzErik** [comment]
It's important that equipment be digital so that it can beepboop at you when it's has to go potty.
