### ISSUE TITLE
sp_Blitz -- Do we want CPU speed in the balanced power check?

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1483]
I semi-recently answered [this question](https://dba.stackexchange.com/questions/198045/how-to-get-the-cpu-speed-in-sql-server/198065#198065). So it's easy to get the CPU speed from the registry.

I'm thinking to include it in the power mode check since it also calls `xp_regread` and if someone wanted to skip checks that call it for whatever reason, it would be more simple to do two together. I know there's another check for stacked instances that uses it, so hey!

Anyway, I'm not married to it, but it might be nice to have.

**Comment by BrentOzar** [comment]
That would be amazing!
