### ISSUE TITLE
sp_BlitzCache/BQS: Prioritize checks

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1489]
It has recently come to my attention that we check for a lot of stuff, and that it may be overwhelming to most people.

What I wanna do is take all the immediately and easily actionable checks and have them run no matter what, then take all the most obscure stuff and lump it under the `ExpertMode` parameter. 

You know, that thing no one ever uses.

Heads up for @BrentOzar -- we may want to alter the way BlitzFirst calls BlitzCache in the future if you want full info in logging tables.

**Comment by BrentOzar** [comment]
That makes perfect sense, yeah.

**Comment by BlitzErik** [comment]
Stuff I made Expert Mode:
- Unparameterized Queries
- Index DML
- Table DML
- Row estimate mismatch
- Busy loops
- TVF Join
- UDF computed column
- Index modifications
- Spatial indexes
- Index spools
- ColumnStore row mode
- Row goals
- Many to many merge joins
- Switch operators

I'm also adding a checks file for BLitzCache like Blitz and BlitzFirst have to make this easier to review. I'll probably hold off on one for BQS for now.

Open to suggestions on that list.
