### ISSUE TITLE
sp_Blitz To report on different compatibility level than SQL server instance 

### ISSUE THREAD

**Issue by isp0000** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1490]
**Do you want to request a *feature* or report a *bug*?**
New **feature**

**What is the expected behavior?**

Report on any user database with compatibility level  different from SQL server instance (or master db?).

**Comment by BrentOzar** [comment]
Hmm, what action would you take, though? Changing compat levels comes with a risk (by breaking app T-SQL interpretation, or changing the cardinality estimator.) We're not big fans of adding new alerts on something where the user can't take a safe action.

**Comment by isp0000** [comment]
@BrentOzar, you are correct. In my experience most of the compatibility level downgrades are just lazy migrations where backup from older version of SQL Server was restored in new one without any consideration on what the compatibility level should be.
