### ISSUE TITLE
sp_Blitz Bug

### ISSUE THREAD

**Issue by VasylPavuk** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1491]
**-Bug-**

**What is the current behavior?**
I have message: Transaction Log Larger than Data File

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
Database *tempdb*

**What is the expected behavior?**
Exclude database *tempdb* from this check

**P.S. I have the following message:**
The database [tempdb] has a 3 GB transaction log file, larger than the total data file sizes. This may indicate that transaction log backups are not being performed or not performed often enough.

**Comment by BrentOzar** [comment]
Hi! That's not a bug - that's actually an interesting situation you probably want to dig into. My guess is that someone's been shrinking TempDB. 3GB is a little on the small side for TempDB. If you've been shrinking it, you may want to ease up on that practice.

**Comment by VasylPavuk** [comment]
Dear Brent,
No one shrink tempdb :).
This database intensively used because there are many temporary tables and table variables.
That is why transaction log in tempdb is relatively big.
But I there no ablility to backup log on *tempdb* according to message in the procedure **sp_Blitz**

![image](https://user-images.githubusercontent.com/30172092/37591989-fce115fe-2b75-11e8-8381-2d3da3cb0165.png)

**Comment by BrentOzar** [comment]
Correct, and you may want to use larger TempDB data files. 348MB isn't that big. If the log has grown to 3.5GB, that means you probably need larger data files.

**Comment by VasylPavuk** [comment]
Thank you, Brent.
But message "This may indicate that transaction log backups are not being performed or not performed often enough" is irrelevant to **tempdb** database

**Comment by BrentOzar** [comment]
Vasyl - I understand and hear you completely. This will not be changed. Please fix your TempDB database file sizes. Further discussion will not be productive here. Thank you for reporting the issue, though.
