### ISSUE TITLE
sp_Blitz - filter Litespeed operations from DBCC Events findings group

### ISSUE THREAD

**Issue by TheZenoParadox** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1497]
**Do you want to request a *feature* or report a *bug*?** Feature
If you're reporting a bug, include the version number of the script you're using. If it's not the current version, upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build.

**What is the current behavior?** Quest Litespeed generated DBCC PAGE commands are listed as events of interest. Litespeed is executing these after backup jobs. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com** Issue a Litespeed backup against a database

**What is the expected behavior?** These messages should not be included in the DBCC Events findings group as they are expected as part of Litespeed backup behavior.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

**Comment by BlitzErik** [comment]
Cool, thanks. Right now, we filter on some applications [like this](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/commit/e390993de8f1b2195140bf20fe85a935bdfda13f#diff-45927e55fc4332260bd0ae9708e4ef62)

Can you provide the application name string you'd like filtered out, if you're not planning on coding this yourself?

Thanks!

**Comment by TheZenoParadox** [comment]
@BlitzErik  - the string should be '%LiteSpeed%' - I'd be happy to try doing the update myself but I'm a Git noob! Let me know if you want me to try it or if you want to just add the line.

**Comment by BlitzErik** [comment]
The only way to not be a n00b is to try it out.

If you don't wanna, I don't mind adding it. But I like to give people the opportunity to have their name on the contributing line :)

Lemme know what you wanna do.

**Comment by TheZenoParadox** [comment]
LOL! Right...ok let me give it a try.

**Comment by TheZenoParadox** [comment]
@BlitzErik - ok all set. Be gentle!

**Comment by BlitzErik** [comment]
Looks fine to me! Will get this into the next FRK release.

Thanks!

**Comment by BlitzErik** [comment]
Closed via #1498
