### ISSUE TITLE
sp_Blitz: add check for less than, say, 13 error logs

### ISSUE THREAD

**Issue by Totty1973** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1520]
**Do you want to request a *feature* or report a *bug*?**
request a feature. SP_BLITZ could check for "number of error logs":

**What is the current behavior?**
does not check  "number of error logs"

**What is the expected behavior?**
 i do not have complete control who restarts my server but I'm the one responsible for finding and fixing errors. This can get difficult if I do not have complete information. 6 error logs is too few for that, I think about somethink like 13. SP_BLITZ could just check it and report it as "Non-Default Server Config", a DBA should be able to change the number when installing SP_BLITZ as desired. I work in a drug-related company so finding errors before data integrity suffers is key.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
i think: any

**Comment by BrentOzar** [comment]
Oh, also, one note on the implementation - you would want to make sure it wasn't due to the server just being recently installed from scratch.

You don't have to test it in AWS RDS or Azure Managed Instances if you don't have access to those - as long as it works as designed in an on-premises instance, we can work out the rest.

**Comment by Totty1973** [comment]
I propably do not have time for coding right now,
If anyone else feels inclined, feel free.
Otherwise it can probably be "closed for now".

**Comment by BrentOzar** [comment]
OK, thanks for taking the time to suggest it anyway! Have a good week.

**Comment by Totty1973** [comment]
would calling master.sys.xp_instance_regread be okay?
something along like
DECLARE @NumErrorLogs int;
EXECUTE master.sys.xp_instance_regread
    'HKEY_LOCAL_MACHINE',
    'SOFTWARE\Microsoft\\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQLServer',
    'NumErrorLogs',
    @NumErrorLogs OUTPUT;
SELECT @NumErrorLogs;

**Comment by BrentOzar** [comment]
Yep, if you do a search in the code, I wanna say we're already doing that. The tricky part is figuring out the right registry location, of course.

**Comment by Totty1973** [comment]
the code from https://sqlandme.com/tag/registry-path-sql-server/ seems to work

CREATE TABLE #tempInstanceNames
(
      InstanceName      NVARCHAR(100),
      RegPath           NVARCHAR(100)
      DefaultDataPath   NVARCHAR(MAX)
)
INSERT INTO #tempInstanceNames (InstanceName, RegPath)
EXEC   master..xp_instance_regenumvalues
       @rootkey = N'HKEY_LOCAL_MACHINE',
       @key     = N'SOFTWARE\\Microsoft\\Microsoft SQL Server\\Instance Names\\SQL'
SELECT      InstanceName, RegPath, DefaultDataPath
FROM        #tempInstanceNames

**Comment by BlitzErik** [comment]
Be careful -- code from blog posts (and other people's websites) is sometimes copyrighted, or not licensed for open source distribution. If you're going to write something like that, you'll have to do it from scratch, or get the author's permission.

Thanks!
