### ISSUE TITLE
SP_BLITZ Check 78 reports "[distributionA].[dbo].[sp_MSdelete_dodelete] has WITH RECOMPILE in the stored procedure code, which may cause increased CPU usage due to constant recompiles of the code." when setting up a distribution publisher on SQL 2014 

### ISSUE THREAD

**Issue by Totty1973** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1521]
**Do you want to request a *feature* or report a *bug*?**
maybe its a bug, maybe an improvement. Version "sp_Blitz Apr  1 2018 12:00AM"

**What is the current behavior?**
SP_BLITZ Check 78 reports "[distributionA].[dbo].[sp_MSdelete_dodelete] has WITH RECOMPILE in the stored procedure code, which may cause increased CPU usage due to constant recompiles of the code." when setting up a distribution publisher on SQL 2014 

**What is the expected behavior?**
could skip objects with "is_ms_shipped"

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2014 SP2-CU11 Standard on Server 2012 R2 Standard seems to be affected.

**Comment by BrentOzar** [comment]
Makes sense! You're free to start coding it per the contributing guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md

If you've got any questions, holler. Thanks! If you didn't plan on coding it yourself, just let me know and I can close the issue - we don't really take requests, but you might be able to recruit someone else to code it for you in the #FirstResponderKit channel in SQLslack.com.

**Comment by Totty1973** [comment]
I propably do not have time for coding right now,
If anyone else feels inclined, feel free.
Otherwise it can probably be "closed for now".

**Comment by BrentOzar** [comment]
No problem, understood. I close it for now. Thanks anyway for reporting it!
