### ISSUE TITLE
sp_BlitzCache possible bug

### ISSUE THREAD

**Issue by achepak** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1523]
From time to time we get the following error when running sp_BlitzCache (ver 6.2 and 6.3), see below a copy of the output produced by sp_BlitzCache:

...
Parsing conversion info
Updating variables inserted procs
Inserting variables for other procs
Updating procs

**Msg 537, Level 16, State 3, Procedure sp_BlitzCache, Line 3145
Invalid length parameter passed to the LEFT or SUBSTRING function.
The statement has been terminated.**

Updating conversion XML
Updating cached parameter XML
...

**Comment by BlitzErik** [comment]
Okay, sorry about that! I've made a lot of adjustments around that section of code. 

The thing is, it's really hard to know which changes to make from here. Can you try running it with @Debug = 1 enabled and seeing if you can spot the temp table data that causes this issue?

Thanks!

**Comment by achepak** [comment]
Well, we are still on the same version but the error disappeared at the moment. I will add more information if or when we get it again.

**Comment by BlitzErik** [comment]
Alright, cool. If you run into it again, feel free to reopen this issue or start a new one with more information.

**Comment by BlitzErik** [comment]
We got a user to help us track this down. Turns out if there's a CASE expression as part of implicit conversion, it can be way longer than 258 characters. Increasing the column length here.
