### ISSUE TITLE
sp_BlitzCache throws Table DML warning on Temporary Table usage

### ISSUE THREAD

**Issue by jeffreymergler** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1530]
Originally reported here: https://dba.stackexchange.com/questions/204106/sp-blitzcache-throws-table-dml-warning-on-temp-tables

Recap: I get a warning on a procedure that creates, uses, then drops a Temporary Table.  No other tables are created or dropped.

The is how the warning is described:
FindingsGroup	Finding	URL	Details
Table DML	Tables were created or dropped	https://www.brentozar.com/blitzcache/table-dml/	This can cause recompiles and stuff.

Honestly, I am not sure if this is a bug or not, its really down to whether the creators of sp_BlitzCache feel there's any merit in reporting the warning when Temporary tables are used.  We were previously getting warnings on table variables and after Brent scared us away from that bad practice in a class in Portland we converted away from that to temp tables.

Observed the warnings on client's SQL Server 2012 Web Edition in Windows 2012 server.  

sp_BlitzCache is:
SET @Version = '6.4';
SET @VersionDate = '20180401';

If there is no issue with using Temp Tables, not sure if raising a Table DML false positive is ideal.  Maybe suppress the warning on Temp Tables?  If there is merit, then I am fine and can happily work with the product as is.

**Comment by BlitzErik** [comment]
@jeffreymergler haven't heard back from you in a while on this one. If you decide to pick it up, feel free to reopen the issue. 

Thanks!
