### ISSUE TITLE
sp_BlitzIndex doesn't include "{datatype maxbytes}" for DESC columns

### ISSUE THREAD

**Issue by amtwo** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1532]
**Do you want to request a *feature* or report a *bug*?**
Bug in sp_BlitzIndex 6.4 (20180401)

**What is the current behavior?**
When an index definition includes a column that is specified as DESC, sp_BlitzIndex does not include the "{datatype maxbytes}" designation for that column in the "Definition" column of the resultset

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

```
USE tempdb
GO
CREATE TABLE dbo.AM2 (ID int PRIMARY KEY CLUSTERED, name char(10));
CREATE INDEX IX_WhyDoPeopleCreateDescIndexes ON AM2 (name DESC, ID);
GO
EXEC DBA.dbo.sp_BlitzIndex 'tempdb','dbo','AM2'
GO
DROP TABLE dbo.AM2;
GO
```

**What is the expected behavior?**

The index definition for IX_WhyDoPeopleCreateDescIndexes should list the definition as (bolded the missing part):
[2 KEYS] name DESC **{char 10}**, ID {int 4}

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Noticing this in 2017. Assume it's all versions.

**Comment by amtwo** [comment]
![image](https://user-images.githubusercontent.com/9381581/39057685-daedc2e6-4487-11e8-958d-af14e9cac3c9.png)

**Comment by BlitzErik** [comment]
Oh that's weird.

**Comment by BlitzErik** [comment]
FOUND IT! Case expression end gone rogue. 

![image](https://user-images.githubusercontent.com/11590415/39079526-8569aeee-44ea-11e8-80e8-c621d8ed9571.png)
