### ISSUE TITLE
New script proposal: generate a table with SQL Server versions

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1539]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
We don't currently have a way to check to see if there are updates available for a SQL Server. We do have an "unsupported version" warning in sp_Blitz, but that only checks for truly unsupported - not whether there's an update available.

To build something really reusable, I'm proposing we create a script to build a table with columns for:

- Major version number
- Minor version number
- Branch (RTM, SP1, SP2, SP3)
- URL (for the KB article for this build number)
- ReleaseDate
- MainstreamSupportEndDate
- ExtendedSupportEndDate
- Major version name (SQL Server 2016)
- Minor version name (Service Pack 1 Cumulative Update 3)

The script would create the table if it doesn't already exist, and then add rows if they don't exist. Thoughts about the definition of the table?

**Sample deliverable, pseudocode:**

```
IF EXISTS dbo.SQLServerVersions THEN DROP TABLE dbo.SQLServerVersions;
CREATE TABLE dbo.SQLServerVersions (MajorVersionNumber, MinorVersionNumber, Branch, URL, ReleaseDate, MainstreamSupportEndDate, ExtendedSupportEndDate);
INSERT INTO dbo.SQLServerVersions VALUES (blah blah blah blah);
INSERT INTO dbo.SQLServerVersions VALUES (blah blah blah blah);
INSERT INTO dbo.SQLServerVersions VALUES (blah blah blah blah);
INSERT INTO dbo.SQLServerVersions VALUES (blah blah blah blah);
GO
```

**Comment by EmanueleMeazzo** [comment]
I was thinking, maybe the list of versions can be automatically created by fetching the data from sqlserverupdates.com (or wherever this dataset is) with a powershell script (or whatever) when releasing each version, as opposed to maintaining it manually.

**Comment by jadarnel27** [comment]
What should be in the minor version column?  As an example, the version number for SQL Server 2016 SP1 CU7 is: `13.0.4466.4`

Assuming major version is 13, is minor version everything else (0.4466.4)?  I know in general .NET assembly versioning, those four parts are major, minor (I think only 2008 R2 used this), build (SP / CU), and revision (hotfixes).

Maybe it would make sense to have just one column with the whole four-part version number (major, minor, build, revision)?  That seems like it would make finding the row easier when querying this table to see if a specific server has available updates.

PS: I'm interested in working on this, just want to make sure I understand what should go into the table

**Comment by BlitzErik** [comment]
We usually just grab the four digit number as the minor version -- so 4466.

Thanks and hi!

**Comment by jadarnel27** [comment]
Got it, Erik - thanks (and hi)!

**Comment by jadarnel27** [comment]
I'd be glad to take this issue.

I'm assuming the resulting code should be added to the repo as a newfile.  So let me know if you'd prefer to have it in one of the other scripts / install files!

**Comment by BlitzErik** [comment]
@jadarnel27 awesome, thanks! Let's see what you come up with first.

**Comment by BrentOzar** [comment]
Added fields for Major Version Name, Minor Version Name.

**Comment by jadarnel27** [comment]
Got it!  I should have an initial PR for you all in the next couple days.

**Comment by BlitzErik** [comment]
@jadarnel27 that's awesome! thanks for hopping on this. It would have taken us years.

**Comment by EmanueleMeazzo** [comment]
@jadarnel27 I remember reading that if you call Microsoft support they'll ask you to update to the latest CU before they examine your issue in case it has been already fixed by a CU.
So it's not really "out of support", but neither "fully supported"

**Comment by BlitzErik** [comment]
@BrentOzar can you assign this to @jadarnel27? He doesn't show up when I try to do it, and he has something in the works.

**Comment by BrentOzar** [comment]
Huh - he doesn't show up to me either.

**Comment by BrentOzar** [comment]
@jadarnel27 DAAANG, nice work, sir! That's phenomenal.

**Comment by jadarnel27** [comment]
Thanks, @BrentOzar!

By the way, I'm sourcing my support date information from here:

https://support.microsoft.com/en-us/lifecycle/search?alpha=SQL%20Server

The only thing missing there is SQL 2016 SP2.  I don't know how long it usually take Microsoft to update that page.

**Comment by GrumpyVader** [comment]
I've been working on sprocs to pull system information using SERVERPROPERTY and the like. Would this version table be a manual update for the time being or is anyone working on an automated way to get the latest build info? I know with SQL 2017 there will no longer be SPs and the CUs will be released monthly.

**Comment by jadarnel27** [comment]
@GrumpyVader I wrote a scraper app that generated the script using the information on these two pages:

- [How to determine the version, edition, and update level of SQL Server and its components](https://support.microsoft.com/en-us/help/321185/how-to-determine-the-version-edition-and-update-level-of-sql-server-an)
  - For the build numbers, release dates, and related branch names (CU1, SP3, etc)
- [Microsoft SQL Server support lifecycle page](https://support.microsoft.com/en-us/lifecycle/search?alpha=SQL%20Server)
  - For the mainstream and extended support dates

I'd be happy to open source little app that builds the script if there is interest.

**Comment by GrumpyVader** [comment]
Cool @jadarnel27. I'm interested for sure. It would help for keeping inventory on the servers I support.
