### ISSUE TITLE
[FEATURE] Maximum history for output results table....

### ISSUE THREAD

**Issue by natiki** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1541]
Hi,

To complement the existing @Output* parameters that allow outputs to be written to a table could I suggest that we add an additional option of: @OutputMaxRunCount 

This would automatically remove old records from @OutputTableName when the number of "runs logged" to the table is exceeded? That way table growth can be managed as part of the script execution.

This parameter could default to 0 which would maintain existing behaviour to keep all the history.

**Comment by BrentOzar** [comment]
Which table are you referring to? If it's sp_BlitzFirst, for example, have you looked at the @OutputTableRetentionDays table?

**Comment by BrentOzar** [comment]
Gotcha. No, sp_BlitzFirst has @OutputTableRetentionDays, but sp_Blitz doesn't. If you'd like to copy that logic from sp_BlitzFirst over to sp_Blitz, and use the same parameters & functionality, that makes sense.

Here's the contributing guide to get started:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md

If you didn't want to write the code, no problem, just let me know and I can close the issue. Thanks, and welcome to the club!

**Comment by BlitzErik** [comment]
Just to minimize issue clutter, I'm going to close this out. If you decide you want to code it, feel free to reopen the issue.
