### ISSUE TITLE
[FEATURE] sp_BlitzCache - Suppress explanation table....

### ISSUE THREAD

**Issue by natiki** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1542]
Hi,

Is it possible to suppress the second result set? We have an antiquated tool that does not like multiple result sets coming back. I realise I could go and edit the necessary SQL but....

Perhaps adding a column to the first result set that links back to an explanation somewhere (like the other SP's do).

**Comment by BrentOzar** [comment]
What antiquated tool?

**Comment by natiki** [comment]
It's an inhouse command line tool that we use for automation. So not directly related to SQL Server specifically.

**Comment by BrentOzar** [comment]
Ah, gotcha. Okay, probably start by hitting the documentation and reading the code - check out the @HideSummary parameter. If it doesn't do what you want, here's the contributing guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md

**Comment by BlitzErik** [comment]
Closing this out, since we have a parameter that covers it.
