### ISSUE TITLE
BlitzFirst introduces Single-Use Plans

### ISSUE THREAD

**Issue by goochjj** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1545]
Run sp_BlitzFirst:
EXEC dbo.sp_BlitzFirst  @OutputDatabaseName = 'DBATools',
  @OutputSchemaName = 'dbo',
  @OutputTableName = 'BlitzFirst',
  @OutputTableNameFileStats = 'BlitzFirst_FileStats',
  @OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
  @OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
  @OutputTableNameBlitzCache = 'BlitzCache',
  @OutputTableRetentionDays = 14;

(Adjust database name as necessary)

Run this
SELECT DB_NAME(S.dbid),s.*,p.*
FROM sys.dm_exec_cached_plans P 
	CROSS APPLY sys.dm_exec_sql_text(P.plan_handle) S 
WHERE P.usecounts=1 AND P.objtype IN ('Adhoc','Prepared')
	AND S.text LIKE '%blitzfirst%'
ORDER BY s.dbid

See all the BlitzFirst queries that are inserting data into tables.

Possible reasons - 
1) The conditional that creates the tables generates a new, GUID-based primary key identifier each run.  Personally I'd rather see this as something readable, like PK_BlitzFirst_WaitStats__ID (based on the given name of the table)

CONSTRAINT [PK_1987219D-2991-452D-96B1-BE3C019C0BA9] PRIMARY KEY CLUSTERED (ID)
CONSTRAINT [PK_20CA8BC9-BF80-47FD-9171-3C96DC55AA97] PRIMARY KEY CLUSTERED (ID)

2) The run time and instance information is included in the insert:
 IF EXISTS(SELECT * FROM [DBATools].INFORMATION_SCHEMA.SCHEMATA WHERE QUOTENAME(SCHEMA_NAME) = '[dbo]') INSERT [DBATools].[dbo].[BlitzFirst_WaitStats] (ServerName, CheckDate, wait_type, wait_time_ms, signal_wait_time_ms, waiting_tasks_count) SELECT 'PRODSQL16V01\PRODSQL16V01', '2018-04-26 11:55:01.3116364 -04:00', wait_type, wait_time_ms, signal_wait_time_ms, waiting_tasks_count FROM #WaitStats WHERE Pass = 2 AND wait_time_ms > 0 AND waiting_tasks_count > 0
 IF EXISTS(SELECT * FROM [DBATools].INFORMATION_SCHEMA.SCHEMATA WHERE QUOTENAME(SCHEMA_NAME) = '[dbo]') INSERT [DBATools].[dbo].[BlitzFirst_WaitStats] (ServerName, CheckDate, wait_type, wait_time_ms, signal_wait_time_ms, waiting_tasks_count) SELECT 'PRODSQL16V01\PRODSQL16V01', '2018-04-26 11:40:01.1278699 -04:00', wait_type, wait_time_ms, signal_wait_time_ms, waiting_tasks_count FROM #WaitStats WHERE Pass = 2 AND wait_time_ms > 0 AND waiting_tasks_count > 0

Further analysis will likely reveal other similar problems.

**Comment by BlitzErik** [comment]
How many single use plans does it introduce, exactly?

**Comment by BlitzErik** [comment]
This is going to be a bit awkward to fix. It doesn't look like option recompile will work, here.

```
DBCC FREEPROCCACHE;

IF EXISTS ( SELECT 1 FROM sys.databases )
    SELECT 1
    OPTION ( RECOMPILE );

SELECT      DB_NAME(S.dbid), S.*, P.*
FROM        sys.dm_exec_cached_plans AS P
CROSS APPLY sys.dm_exec_sql_text(P.plan_handle) AS S
WHERE       P.usecounts = 1
AND         P.objtype IN ( 'Adhoc', 'Prepared' )
AND         S.text LIKE '%sys.databases%'
ORDER BY    S.dbid;
```

This might be something we just have to Deal With®

**Comment by goochjj** [comment]
If the PK constraint names were explicit, and consistent, probably half of these would go away.
As for the inserts, can't you use sp_executesql to pass the value as a parameter instead?  Or a variable? i.e.
IF EXISTS(SELECT * FROM [DBATools].INFORMATION_SCHEMA.SCHEMATA WHERE QUOTENAME(SCHEMA_NAME) = '[dbo]') INSERT [DBATools].[dbo].[BlitzFirst] (ServerName, CheckDate, CheckID, Priority, FindingsGroup, Finding, URL, Details, HowToStopIt, QueryPlan, QueryText, StartTime, LoginName, NTUserName, OriginalLoginName, ProgramName, HostName, DatabaseID, DatabaseName, OpenTransactionCount, DetailsInt) SELECT 'STANDBYSQLV01\STANDBYSQLV01', '2018-04-14 17:55:00.3738848 -04:00', CheckID, Priority, FindingsGroup, Finding, URL, Details, HowToStopIt, QueryPlan, QueryText, StartTime, LoginName, NTUserName, OriginalLoginName, ProgramName, HostName, DatabaseID, DatabaseName, OpenTransactionCount, DetailsInt FROM #BlitzFirstResults ORDER BY Priority , FindingsGroup , Finding , Details

**Comment by BlitzErik** [comment]
Okay, can you test out that that's the case? I'd hate to put a bunch of work into coding it to find it doesn't fix anything for you.

Thanks!

**Comment by goochjj** [comment]
I mean, you could also just recommend people locate the function in a database with forced parameterization on - unless you can recommend setting it on master won't cause other problems.

**Comment by BlitzErik** [comment]
That's something else for you to test, yeah, if FP would parameterize contraint names. It may not.

Looking forward to your findings!

**Comment by goochjj** [comment]
FP Fixed nothing.
(@0 int,@1 int,@2 int)insert [DBATools] . [dbo] . [BlitzFirst_WaitStats] ( ServerName , CheckDate , wait_type , wait_time_ms , signal_wait_time_ms , waiting_tasks_count ) select 'PRODSQL16V01\PRODSQL16V01' , '2018-04-26 12:25:00.9412856 -04:00' , wait_type , wait_time_ms , signal_wait_time_ms , waiting_tasks_count from #WaitStats where Pass = @0 and wait_time_ms > @1 and waiting_tasks_count > @2

It only changed the where clause, not the literals in the SELECT statement.

Constraint names can't be parameterized (just like you couldn't parameterize a table name)

So changing the code seems like the only option

**Comment by BlitzErik** [comment]
Great -- when you settle on code that does what you want it to do, let us know. I'll help you either make the contribution yourself, or set up a branch for you to test with.

Thanks!

**Comment by BlitzErik** [comment]
Oops, wrong button.

**Comment by goochjj** [comment]
@BlitzErik  you're up. :)

**Comment by BlitzErik** [comment]
Looks good! Nice job!
