### ISSUE TITLE
sp_BlitzCache doesn't work in Azure SQL Database

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#155]
HOLD ON, before you close this - it's really, really close. Azure SQL Database just doesn't support global temp tables - if you just do a search/replace for ## to #, it works flawlessly. Not saying you need to change this anytime soon, but if we have a separate Azure version where we just find/replace ## to # every time, that's better than screwing around with building one version to work in both places.

Logging this because I'm doing an ASD CC next week, so I'm going through the scripts and figuring out what I need to change. sp_BlitzCache is probably the easiest one I've found so far, hahaha.

**Comment by BlitzErik** [comment]
Closing because: https://www.brentozar.com/archive/2017/07/sp_blitzcache-eventual-compatibility-azure/
