### ISSUE TITLE
SP_Blitz: Check #176 Returns an unwanted row?

### ISSUE THREAD

**Issue by namraja** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1552]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Using SP_Blitz (version 6.4) on SQL Server 2014 SP2 CU11 and SQL Server 2017 CU6, check #176 includes an XE session named 'sp_server _diagnostics session', but the predicate to ignore it is called 'sp_server_diagnotics' (maybe the session name has changed over time?)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
![image](https://user-images.githubusercontent.com/38831905/39407919-ee656316-4bc5-11e8-8eb6-4ed1f54f96e0.png)

**What is the expected behavior?**
Unsure - but I suspect that 'sp_server_diagnotics session' should be excluded from SP_Blitz's resultset

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Reproducible on SQL Server 2014 SP2 CU11 and SQL Server 2017 CU6. Unsure if this worked in a previous version...

**Comment by BlitzErik** [comment]
Ah, this is fun. It looks like it got not-fixed in #1393 when #1116 was trying to get fixed. 

Thanks for letting us know.
