### ISSUE TITLE
Syntax Error in sp_Blitz

### ISSUE THREAD

**Issue by jefowler2** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1554]
**Do you want to request a *feature* or report a *bug*?**
Bug in version 6.5 - syntax error

**What is the current behavior?**
The stored procedure has a syntax error preventing it from getting altered:
Msg 102, Level 15, State 1, Procedure sp_Blitz, Line 4280 [Batch Start Line 3]
Incorrect syntax near 'AlwaysOn_health'.

There is an "extra left and right parentheses in a list of values that should get replaced with a comma.

**What is the expected behavior?**
The stored procedure should get altered and produce this message:
Commands completed successfully.

**Which versions of SQL Server and which OS are affected by this issue? SQL 2012 SP4

 Did this work in previous versions of our procedures?** Yes

**Comment by BlitzErik** [comment]
Howdy! Thanks for opening the issue. We already got a report of it on the blog. There was an issue with the GitHub merge of the fix. If you re-download, it'll be taken care of.

Thanks!
