### ISSUE TITLE
Syntax error in [dbo].[sp_Blitz] of version 6.5 release

### ISSUE THREAD

**Issue by zahidhanif** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1555]
Version 6.5 of the [dbo].[sp_Blitz] stored procedure has a syntax error on line 4282 of the script file. The WHERE [name] NOT IN clause has 2 bracketed sets that are causing a syntax error when compiled in Visual Studio. I am using Visual Studio 2015 and SQL Data Tools 14.0.61712.050.

**Comment by BlitzErik** [comment]
Duplicate #1554
