### ISSUE TITLE
DatabaseRestore does not support URL pathing

### ISSUE THREAD

**Issue by GrumpyVader** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1570]
New Feature? The DatabaseRestore script currently does not support cloud backups using the URL and credential options.

**What is the current behavior?**
Currently the only paths supported are drive letter and UNC path.

**What is the expected behavior?**
The BackupPaths should support URL and a new parameter should be added for the Credential to use.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
This option is available starting with SQL 2014+.

Example:
BACKUP DATABASE [databasename] 
TO  URL = 'https://cloudstorage.blob.core.windows.net/fullbackups/databasename.bak'
WITH  
	CREDENTIAL = N'cred_cloudaccount'
	,FORMAT
	,COMPRESSION
GO

**Comment by BlitzErik** [comment]
Great idea! 

The thing is, none of us are using those, so we wouldn't be able to develop or test the code.

If you want to take franchise of it, that's fine with us. Just let me know here and I'll assign the issue over to you. 

Make sure to read the [contributing guide](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md) first

If not, that's fine too -- it's hard to fine free time to do this stuff -- I'll close the issue out. 

Thanks!

**Comment by GrumpyVader** [comment]
I'm taking a look at what changes would be needed and I will read the guide as well then I will let you know if I can take it on. :)

**Comment by BlitzErik** [comment]
Sounds good. I'll assign it to you without a milestone. No pressure, just whenever you make a decision on it, let me know.

Thanks!

**Comment by BlitzErik** [comment]
@GrumpyVader were you still interested in taking this on? Just checking in on open issues. 

Thanks!

**Comment by BlitzErik** [comment]
@GrumpyVader Haven't heard back from you in a while, so going to close this out. Feel free to reopen if you decide to pursue it in the future.

**Comment by GrumpyVader** [comment]
Sorry about that. I’ve been busy with server migrations. I will work on it when I get some free time.

Thank you,
    Eric Ritzie

Sent from my iPhone

On Jun 1, 2018, at 2:30 PM, BlitzErik <notifications@github.com<mailto:notifications@github.com>> wrote:


@GrumpyVader<https://github.com/GrumpyVader> Haven't heard back from you in a while, so going to close this out. Feel free to reopen if you decide to pursue it in the future.
