### ISSUE TITLE
sp_BlitzCache - The database you specified is not readable, but status is online

### ISSUE THREAD

**Issue by bmistiaen** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1582]
Reporting bug in sp_BlitzCache 
Version = '6.5';
VersionDate = '20180501';

**What is the current behavior?**
1. Executing sp_BlitzCache
Input:
exec sp_blitzcache @DatabaseName='AX2012R3_SAV_PROD'

Output:
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Msg 50000, Level 16, State 1, Procedure sp_BlitzCache, Line 775
The database you specified is not readable. Please check the name and try again. Better yet, check your server.

2. Executing in SSMS Query window:
Input:
DECLARE @DatabaseName nvarchar(500) = 'AX2012R3_SAV_PROD';
DECLARE @mystatus nvarchar(50);

SELECT @mystatus = convert(nvarchar(50), DATABASEPROPERTYEX(@DatabaseName, 'Status'));
IF (@mystatus) <> 'ONLINE'
BEGIN
   RAISERROR('The database you specified is not readable. Please check the name and try again. Better yet, check your server.', 16, 1);
   RETURN;
END;
ELSE
BEGIN
	PRINT(convert(nvarchar(50), DATABASEPROPERTYEX(@DatabaseName, 'Status')));
    PRINT('ok');
END;

Output:
ONLINE
ok

**What is the expected behavior?**
To have sp_BlitzCache recognize that the database has status 'ONLINE'

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
From Glenn Berry's script (Query
Microsoft SQL Server 2014 (SP2) (KB3171021) - 12.0.5000.0 (X64) 
	Jun 17 2016 19:14:09 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)
Windows Server 2012 R2 Standard

**Comment by BrentOzar** [comment]
Working OK here. Make sure you've got the database name configured *exactly* as the real database is - case sensitivity, hidden characters, etc. Sometimes it's easier to do a SELECT * FROM sys.databases, and copy/paste it into the sp_BlitzCache parameter.

If that still doesn't work, include screenshots showing the list of databases, the output of SELECT * FROM sys.databases, and the sp_BlitzCache call & output.

**Comment by bmistiaen** [comment]
Database name is exactly the same. 
Did the copy-paste from sys.databases, still gives same error.
Requested screenshots attached.
![1582_listofdatabases](https://user-images.githubusercontent.com/25608894/40239341-124df712-5ab6-11e8-8a60-c9a50ffca363.png)
![1582_select_from_sysdatabases](https://user-images.githubusercontent.com/25608894/40239343-126b8d04-5ab6-11e8-8fac-a1e05e70e532.png)
![1582_sp_blitzcache_call_and_output](https://user-images.githubusercontent.com/25608894/40239345-1285bfe4-5ab6-11e8-976d-d39080917c23.png)

**Comment by BrentOzar** [comment]
Thanks for that quick turnaround! I know this is going to sound paranoid, so please bear with me. You might be the world's most qualified SQL Server professional, but I just have no idea, so I have to kinda check the basics first.

I really appreciate the screenshot of the excerpt, but it's not quite the whole relevant script. Try this:

```
DECLARE @DatabaseName NVARCHAR(500) = 'AX2012R3_SAV_PROD';
SET @DatabaseName = LTRIM(RTRIM(@DatabaseName)) ;
IF (DB_ID(@DatabaseName)) IS NULL AND @DatabaseName <> N''
BEGIN
   RAISERROR('The database you specified does not exist. Please check the name and try again.', 16, 1);
   RETURN;
END;
IF (SELECT DATABASEPROPERTYEX(@DatabaseName, 'Status')) <> 'ONLINE'
BEGIN
   RAISERROR('The database you specified is not readable. Please check the name and try again. Better yet, check your server.', 16, 1);
   RETURN;
END;
```

I'm particularly interested in the DB_ID() portion, so you might even try that separately:

`SELECT (DB_ID(@DatabaseName)), DATABASEPROPERTYEX(@DatabaseName, 'Status'))`

**Comment by bmistiaen** [comment]
First query:
![1582_trim](https://user-images.githubusercontent.com/25608894/40240309-9444e8dc-5ab8-11e8-8208-9fc9be9668e9.png)

Second query:
![1582_databasepropertyex](https://user-images.githubusercontent.com/25608894/40240315-9adeea62-5ab8-11e8-94e3-c269e7b73e57.png)

**Comment by BrentOzar** [comment]
Thanks for that! The first query's success means that the code inside sp_BlitzCache is running properly. 

I really hate to say this, but that leaves me with only one conclusion: that somehow the installed version of sp_BlitzCache has been modified. Go ahead and drop your existing sp_BlitzCache, and reinstall it from the official version here. Make sure to check the databases & schemas that you're currently in, too - I know sometimes I accidentally create modified versions in user databases and run them by accident.

**Comment by bmistiaen** [comment]
Checked all databases.
sp_BlitzCache only exists in master.
Dropped it.
Re-created it in master, from SQL-Server-First-Responder-Kit-dev.zip
And lo and behold: it works now!
SQL Server sure works in mysterious ways sometimes...
Thank you very much for your swift help and quick responses!

**Comment by BrentOzar** [comment]
No problem, glad we could help!

**Comment by tatormills** [comment]
I also received this error in SQL Server 2016 and sp_blitzcache version is 6.5, Date is 2018-05-01.

I install sp_blitz stuff in the master database.
My current  database is DevDB, i.e. not master.

I tried to use the @DatabaseName filter for sp_blitzcache, like:

exec sp_blitzcache @sortorder='average reads', @DatabaseName=N'DevDB'

but I get the following error:

Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Msg 50000, Level 16, State 1, Procedure sp_BlitzCache, Line 774 [Batch Start Line 9]
The database you specified is not readable. Please check the name and try again. Better yet, check your server.

If my current database is master, i.e. where the sp_blitzcache SP is located, it works and I get what I want.

I found this in the MS documentation:
_For SQL Database, DATABASEPROPERTYEX requires the name of the current database. It returns NULL for all properties if given a different database name._

But if this is true, I do not understand why it works when my current database is master and I set @DatabaseName to ‘DevDB’.

Clearly I can always set my current DB to be master and I am good to go.  But I rarely set master as my current DB.  So I hacked up sp_blitzcache with a cast of the DATABASEPROPERTYEX(@DatabaseName, 'Status') to nvarchar(128).  For example:

  IF (SELECT cast(DATABASEPROPERTYEX(@DatabaseName, 'Status') as nvarchar(128))) <> 'ONLINE'
  BEGIN
     RAISERROR('The database you specified is not readable. Please check the name and try again. Better yet, check your server.', 16, 1);
     RETURN;
  END
