### ISSUE TITLE
Overall Events DBCC Events: Exclude DBCC USEROPTIONS

### ISSUE THREAD

**Issue by rsocol** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1583]
**Do you want to request a *feature* or report a *bug*?**

feature for version 6.4 (20180401)

**What is the current behavior?**

The check for overall DBCC events returns warnings for DBCC USERINFO.

**What is the expected behavior?**

I think DBCC USERINFO is fairly benign, as it only shows the current values of the SET options, without changing them.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

SQL 2008 SP4 (and probably all others)
Previous versions had the same issues

**Comment by BrentOzar** [comment]
Great idea, and makes total sense. If you wanna contribute the code for it and see your name in lights, here's the contributing guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md

If you're not comfortable with Github or you don't have the time, no worries - this change is easy enough that I can tackle it really quickly. Just let me know either way - wanted to give you the chance to do it if you wanted to experiment with Github. Thanks!

**Comment by rsocol** [comment]
Thanks for the very fast response, I didn't expect such a quick reaction!
I'm not familiar with using git, maybe I'll try to install it (and see my name in lights) the next time I have an idea for sp_Blitz (maybe it will be a bit more substantial).
