### ISSUE TITLE
sp_BlitzLock - Add a column for the full graph

### ISSUE THREAD

**Issue by jadarnel27** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1590]
**Do you want to request a *feature* or report a *bug*?**
Request a feature

**What is the current behavior?**
Running `sp_BlitzLock` produces awesomeness.

**What is the expected behavior?**
Running `sp_BlitzLock` produces awesomeness, *and* a column to view the full deadlock graph.

This would make it easier to save the deadlock graph to a folder, or send it to someone else to troubleshoot, look at the weird nitty gritty details, etc.  Right now I have to dig around in the system_health XE to get this.

The column should be clickable ("click to show in XML editor") like "query" and "object_names" are.

If you all are open to the feature, I'd be glad to submit a PR.

**Comment by BlitzErik** [comment]
Totally, go for it!
