### ISSUE TITLE
duplicate rows when checking for recompiled procedures

### ISSUE THREAD

**Issue by Tisit** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1592]
**Do you want to request a *feature* or report a *bug*?**
Bug. Version 6.5

**What is the current behavior?**

When there are 2 or more stored procedures with option recompile and same name but different schemas sp_Blitz returns duplicate warnings.

Simple reproducer:
CREATE SCHEMA S1
GO
CREATE SCHEMA S2
GO

CREATE PROC S1.A WITH RECOMPILE AS 
SELECT 1
GO

CREATE PROC S2.A WITH RECOMPILE AS 
SELECT 1
GO

EXEC sp_Blitz @IgnorePrioritiesBelow =99, @IgnorePrioritiesAbove = 101

**What is the expected behavior?**
The above code should return warnings about 2 procedures, but returns 4

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
At least 2014 and 2016

**Comment by BrentOzar** [comment]
OK, great! I added a quick and dirty fix with a SELECT DISTINCT, but if you wanted to code another fix, you're welcome to check out the contributing guide and make a pull request. Thanks!

**Comment by Tisit** [comment]
Took a look at the code and I think it could be fixed in another way. Give me a day or 2 to figure out the whole github thing.
