### ISSUE TITLE
Hard coded table name: [dbo].[BlitzFirst_WaitStats]

### ISSUE THREAD

**Issue by Alansoft-BR** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1596]
Line ~18945 of Install-Core-Blitz-No-Query-Store.sql has the following:

`                + '        FROM [dbo].[BlitzFirst_WaitStats]' + @LineFeed
`
Which causes the following issue when the parameter has a different table name than the default:
Invalid object name 'dbo.BlitzFirst_WaitStats'.

This line should have the following:
`                + '        FROM ' + @OutputSchemaName + '.' + @OutputTableNameWaitStats + '' + @LineFeed
`

**Comment by BrentOzar** [comment]
Hi, and thanks for reporting it. Whenever you report an issue, just search first to see if the issue already exists - especially if it's closed because it's already been fixed:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/1571

Thanks though!

**Comment by Alansoft-BR** [comment]
Thanks @BrentOzar. But, if it was closed, why doesn't the code reflect that fix?

**Comment by BrentOzar** [comment]
The way open source projects work is that there's often a development branch (where active development is happening, with frequent changes) and then a master/stable branch (which is released on a regular basis, and stays stable for a while.) If you'd like to get the most recent version, check the development branch. Click Code at the top of the screen, look at the "Branch" dropdown to make sure you're in dev, and then click the "clone or download" on the right hand side.

The installation scripts are only updated when the master branch is released, so you'll want to open sp_BlitzFirst.sql directly.

**Comment by Alansoft-BR** [comment]
Of course! My bad since I didn't look around before, came here directly - will take a look.
Thank you for all this amazing code.
Best,
Alan
