### ISSUE TITLE
sp_BlitzWho Doesn't Report Open Transactions Correctly

### ISSUE THREAD

**Issue by MrTCS** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1598]
**Do you want to request a *feature* or report a *bug*?**
Bug.  Version 6.5

**What is the current behavior?**
sp_BlitzWho is not correctly reporting open transactions with sleeping SPIDs.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
BEGIN TRAN
SELECT * FROM Table

OR 
BEGIN TRAN
UPDATE TABLE SET....

--From a seperate Tab
exec sp_BlitzFirst --Will not show any current sessions

**What is the expected behavior?**
Would like for sleeping SPIDs with an open transaction to show up even without having "ShowSleepingSPIDs".  At a minimum it should show an open transaction when using the ShowSleepingSPIDs flag.  

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2012, Windows 10.

**Comment by BlitzErik** [comment]
Thanks for letting us know. Is this something you had planned on coding?

If so, please check out the [contributing ](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md) guide.

**Comment by BlitzErik** [comment]
@MrTCS can you verify which version you're on, etc.? I'm testing a blocking scenario like the one you described and it's showing correctly for me.

![image](https://user-images.githubusercontent.com/11590415/40876793-e2337d84-6647-11e8-85f5-456cf0690315.png)

**Comment by BlitzErik** [comment]
Closing this for now. Feel free to reopen it when you have a working repro script.

Thanks!

**Comment by MrTCS** [comment]
Erik,

I got busy with some stuff and missed the notifications for this.  I'm not specifically talking about blocking here, just SPIDs with an open transaction but are sleeping.  I found a little bit of time to look into it and the problem is with dm_exec_requests only showing active sessions.  I believe a join to dm_tran_session_transactions would solve this issue.  

Haven't worked with GIT but I can try and figure out how to help out here if I can steal some free time in the next week.

**Comment by BlitzErik** [comment]
Cool, I'm open to the change! Just give a holler when you've got something you're ready to show us. 

If you need help, the [#FirstResponderKit Slack channel](https://sqlcommunity.slack.com/messages/firstresponderkit/) is usually faster. 

If you need a free invite, hit [SQLslack.com](http://SQLslack.com/).
