### ISSUE TITLE
SP_Blitz Arithmetic overflow line 595

### ISSUE THREAD

**Issue by CCUMan** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1600]
Have latest downloadable version from FirstAid kit. 

sp_Blitz @IgnorePrioritiesAbove = 50, @CheckUserDatabaseObjects = 0
Msg 8115, Level 16, State 2, Procedure sp_Blitz, Line 595 [Batch Start Line 0]
Arithmetic overflow error converting expression to data type int.
The statement has been terminated.

EXEC dbo.sp_Blitz @CheckUserDatabaseObjects = 1, @CheckServerInfo = 1, @Debug = 1
Setting @MsSinceWaitsCleared
Running CheckId [185].
Msg 8115, Level 16, State 2, Procedure sp_Blitz, Line 595 [Batch Start Line 0]
Arithmetic overflow error converting expression to data type int.
The statement has been terminated.
Setting @CpuMsSinceWaitsCleared
Getting version information.
Running CheckId [1].
Running CheckId [2].
Running CheckId [8].
Running CheckId [93].
Running CheckId [119].
Running CheckId [202].
Running CheckId [4].
Running CheckId [5].
Running CheckId [104].
Running CheckId [6].
Running CheckId [7].
Running CheckId [10].
Running CheckId [11].
Running CheckId [12].
Running CheckId [13].
Running CheckId [14].
Running CheckId [15].
Running CheckId [16].
Running CheckId [17].
Running CheckId [18].
Running CheckId [20].
Running CheckId [21].
Generating default configuration values
Running CheckId [22].
Setting @MinServerMemory and @MaxServerMemory
Setting @Processors.
Setting @NUMANodes
Running CheckId [188].
Running CheckId [24].
Running CheckId [25].
Running CheckId [26].
Running CheckId [27].
Running CheckId [28].
Running CheckId [29].
Running CheckId [34].
Running CheckId [89].
Running CheckId [90].
Running CheckId [36].
Running CheckId [37].
Running CheckId [44].
Running CheckId [45].
Running CheckId [49].
Running CheckId [50].
Running CheckId [51].
Running CheckId [159].
Running CheckId [53].
Running CheckId [55].
Running CheckId [57].
Running CheckId [97].
Running CheckId [154].
Running CheckId [62].
Running CheckId [94].
Running CheckId [100].
Running CheckId [110].
Running CheckId [107].
Running CheckId [121].
Running CheckId [162].
Running CheckId [111].
Running CheckId [112].
Running CheckId [116].
Running CheckId [117].
Running CheckId [124].
Running CheckId [145].
Running CheckId [146].
Running CheckId [147].
Running CheckId [148].
Running CheckId [149].
Running CheckId [150].
Running CheckId [151].
Running CheckId [160].
Running CheckId [161].
Running CheckId [165].
Generating database defaults.
Running CheckId [131].
Running CheckId [132].
Running CheckId [133].
Running CheckId [134].
Running CheckId [135].
Running CheckId [136].
Running CheckId [137].
Running CheckId [138].
Running CheckId [140].
Running CheckId [141].
Running CheckId [142].
Running CheckId [143].
Running CheckId [144].
Running CheckId [167].
Running CheckId [168].
Running CheckId [169].
Running CheckId [170].
Running CheckId [171].
Running CheckId [173].
Running CheckId [174].
Running CheckId [175].
Running CheckId [176].
Running CheckId [177].
Running CheckId [179].
Running CheckId [180].
Running CheckId [181].
Running CheckId [184].
Running CheckId [199].
Running CheckId [200].
Running CheckId [201].
Running CheckId [202].
Running CheckId [203].
Running CheckId [204].
Running CheckId [205].
Starting @CheckUserDatabaseObjects section.
Running CheckId [99].
Running CheckId [163].
Running CheckId [41].
Running CheckId [42].
Running CheckId [82].
Running CheckId [158].
Running CheckId [33].
Running CheckId [19].
Running CheckId [32].
Running CheckId [38].
Running CheckId [164].
Running CheckId [39].
Running CheckId [46].
Running CheckId [47].
Running CheckId [48].
Running CheckId [56].
Running CheckId [95].
Running CheckId [60].
Running CheckId [78].
Running CheckId [86].
Running CheckId [72].
Running CheckId [113].
Running CheckId [115].
Running CheckId [122].
Running CheckId [69] (2012 version of Log Info).
Running CheckId [80].
Running CheckId [74].
Running CheckId [194] through [197].
Running CheckId [68].
Running CheckId [73].
Running CheckId [74].
Running CheckId [75].
Running CheckId [76].
Running CheckId [77].
Running CheckId [79].
Running CheckId [81].
Running CheckId [123].
Running CheckId [172].
Running CheckId [166].
Running CheckId [166].
Running CheckId [184].
Running CheckId [192].
Running CheckId [130].
Running CheckId [83].
Running CheckId [84].
Running CheckId [85].
Running CheckId [88].
Running CheckId [91].
Running CheckId [92].
Running CheckId [103].
Running CheckId [114].
Running CheckId [211].
Running CheckId [212].
Running CheckId [106].
Running CheckId [153].

**Comment by CCUMan** [comment]
[cid:image001.png@01D3F9C5.A0EDD110]

**Comment by BlitzErik** [comment]
Sorry, the image didn't come through via email.

**Comment by CCUMan** [comment]
![image](https://user-images.githubusercontent.com/39840608/40862157-9af1bd52-65b9-11e8-887d-e5ee78ec236f.png)

**Comment by BlitzErik** [comment]
Alright, one more! Can you just paste the number in, though, if it works?

```
        SELECT DATEDIFF(MINUTE, create_date, CURRENT_TIMESTAMP) * 60000.0
            FROM    sys.databases
            WHERE   name = 'tempdb';
```

**Comment by CCUMan** [comment]
![image](https://user-images.githubusercontent.com/39840608/40862777-92981244-65bb-11e8-9475-1995d6ac9f3c.png)

**Comment by BlitzErik** [comment]
Thanks -- can you test the version here?

https://gist.github.com/BlitzErik/df087cc5abf6d54dfb2bb649a20f7f67

**Comment by CCUMan** [comment]
Resolved
