### ISSUE TITLE
sp_BlitzIMOLTP -- gracefully bail on unsupported versions

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1608]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When this proc runs, it doesn't do any version checking to make sure someone is on a version of SQL Server that support IMOLTP, or some of the T-SQL constructs that are used. When someone goes to install our scripts from a bulk create module on a non-supported version, a bunch of errors are thrown.

![image](https://user-images.githubusercontent.com/11590415/40922891-657c7b92-67e1-11e8-97bd-cbe5a659555c.png)

**What is the expected behavior?**
Should check and gracefully bail out on versions where IMOLTP isn't supported

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
< 2014

**Comment by BlitzErik** [comment]
I see up a the top that @nedotter and @ktaranov have added version checking, but it looks like `THROW` wasn't added to T-SQL until 2012.

**Comment by nedotter** [comment]
I will address this tonight, thanks for the catch --

**Comment by BlitzErik** [comment]
Cool, thanks. This is how I do it in `sp_BlitzQueryStore`. I realize you have other exceptions, but it should just be a matter of using `RETURN` instead.

```
DECLARE @msg NVARCHAR(MAX) = N'';

	-- Must be a compatible, on-prem version of SQL (2016+)
IF  (	(SELECT SERVERPROPERTY ('EDITION')) <> 'SQL Azure' 
	AND (SELECT PARSENAME(CONVERT(NVARCHAR(128), SERVERPROPERTY ('PRODUCTVERSION')), 4)) < 13 
	)
	-- or Azure Database (not Azure Data Warehouse), running at database compat level 130+
OR	(	(SELECT SERVERPROPERTY ('EDITION')) = 'SQL Azure'
	AND (SELECT SERVERPROPERTY ('ENGINEEDITION')) <> 5
	AND (SELECT [compatibility_level] FROM sys.databases WHERE [name] = DB_NAME()) < 130
	)
BEGIN
	SELECT @msg = N'Sorry, sp_BlitzQueryStore doesn''t work on versions of SQL prior to 2016, or Azure Database compatibility < 130.' + REPLICATE(CHAR(13), 7933);
	PRINT @msg;
	RETURN;
END;
```

**Comment by nedotter** [comment]
Much appreciated --

**Comment by nedotter** [comment]
Sir Erik,

Just testing on SQL 2012 Enterprise, and the proc can't even be created,
because sys.databases doesn't have the resource_pool_id column.

So I'm wondering if we need to exit gracefully from that which we cannot
invoke....

Thanks,

Ned

**Comment by BlitzErik** [comment]
HI Ned,

You can't run it, but that doesn't mean people won't try to install it. We still get questions about why things won't run/install on 2000/2005. Heh.

I hit that error when I had your script in the bulk install scripts in our repo (we package everything up together a few different ways for folks who only wanna hit F5 once), and started testing against older but still supported versions.

If you'd rather not change code, I can leave it out of those, and keep it as a standalone install. I'm totally fine either way; it's up to you.

Thanks,
Erik

**Comment by nedotter** [comment]
Hi Erik,

So it seems that I can simply place a modified version of your code at the
top of the script, and then the creation of the proc is never attempted.

Think I'll go with that --

Thanks,

Ned

**Comment by BlitzErik** [comment]
Hey Ned,

That code was contributed some time ago by someone working heavily in Azure. I don't do anything with Azure, so if you find the code is incorrect in some way, I'd be happy to update it. I don't have any Azure instance to look at, even.

Thanks,
Erik

**Comment by nedotter** [comment]
Hey Erik,

I've got an Azure db in front if me (not an Azure instance), and SELECT
SERVERPROPERTY ('ENGINEEDITION') returns 5.

So I would think that would confirm that the logic is incorrect....

Best,

Ned
