### ISSUE TITLE
Add sp_rename code for DTA indexes in SpBlitzIndex

### ISSUE THREAD

**Issue by way0utwest** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1610]
One thing that might be nice is if you added the sp_rename code for indexes that might be dups for the _dta_% indexes. These may be good indexes, but they are poorly named. You could start them as IX_col_col_col names, with the user then overriding the name if needed.

Dropping isn't great to provide the code, but the rename (as in lab 1 of the Index Tuning class) is nice.

If you want to, maybe add this for all system generated names, such as poor PKs.

**Comment by BlitzErik** [comment]
I like this idea, but what we run into a lot on consulting gigs is DTA indexes with lots of key columns. It's possible for rename to fail if we don't chop the new name to 128 chars.

- Chopped names leave us with a choice
  - Chopped column names with no _Includes indicator
  - Further chopped column names with _Includes indicator

@way0utwest - Do you have any input on which would be preferable?

**Comment by way0utwest** [comment]
What I might lean towards is chopping the names at (all columns) - tablename - _Includes

**Comment by BlitzErik** [comment]
Maybe a count of columns? `ix_table_name_12_key_columns_and_96_includes`

**Comment by way0utwest** [comment]
Hmmm, Is this in the case where there are many columns? Or in all cases? I'd like to think that we might have the first one or two most SARGable columns listed and then perhaps the others.

`ix_table_name_CustomerKey_CustomerStatus_12_key_columns_and_96_includes`
