### ISSUE TITLE
Bug PowerBi report

### ISSUE THREAD

**Issue by PsPsam** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1619]
**Do you want to request a *feature* or report a *bug*?**
If you're reporting a bug, include the version number of the script you're using. If it's not the current version, upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build.
Using the latest powerbi template from github

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/20344934/41152482-fb078b22-6b13-11e8-9baf-831e81f92720.png)

![image](https://user-images.githubusercontent.com/20344934/41152467-f3ba88b0-6b13-11e8-832a-4ff1f876f842.png)

Let me know if you need more logs and where to get them in that case. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
Trying to use the powerbi to visual the data. I have an old version of the powerbi report that doesnt have the performance counters and that works.

But using the new version that are on the github I get the above error. 

I have collected data running "EXEC sp_BlitzFirst
  @OutputDatabaseName = 'DBAtools',
  @OutputSchemaName = 'dbo',
  @OutputTableName = 'BlitzFirst',
  @OutputTableNameFileStats = 'BlitzFirst_FileStats',
  @OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
  @OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
  @OutputTableNameBlitzCache = 'BlitzCache';"
every 15 min.

The server installed two weeks ago and FirstResponderKit was install by the DBAtools command to install it. 

I have the latest version of PowerBi

**What is the expected behavior?**
The report should load as the example powerbi report does.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Windows server 2016
SQL server 2016 SP 1 Cu 7 Standard

**Comment by BrentOzar** [comment]
Hi! That looks like you haven't upgraded to the latest sp_BlitzFirst and sp_BlitzCache. You might be using the newest Power BI Dashboard, but not those scripts. Update those so they can create the underlying BlitzFirst_PerfmonStats_Actuals.

**Comment by PsPsam** [comment]
Thanks @BrentOzar I made a mistake of updating in the wrong db. Forgot to change from master to DBAtools when I ran the script before trying the new Report :(

It now fetching the data correctly.

Thanks for the help and all the work of this great tool.

And also thanks for the podcast! Its very interesting and fun to listen to.

**Comment by BrentOzar** [comment]
Awesome, great! Glad you enjoy it. Thanks!
