### ISSUE TITLE
sp_Blitz - Power Plan is not retrieved correctly if set by Group Policy in Windows

### ISSUE THREAD

**Issue by AAvella** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1620]
**Do you want to request a *feature* or report a *bug*?**
sp_Blitz 6.5

**What is the current behavior?**
Results incorrectly say that the server is on a power plan that it is not necessarily on.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

**What is the expected behavior?**
Script needs to check a different spot in the registry to get the value set by group policy. If this key does not exist, it should then fall back to the local registry key.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

**Comment by BrentOzar** [comment]
Oh no, sorry to hear that! Can you let us know which spot to check? (Obviously your server has something different than what we've got.)

**Comment by BrentOzar** [comment]
@AAvella congrats on the awesome issue and the pull request! I'd like to give you something to say thanks - can you email us at help@brentozar.com when you have a chance? Thanks!
