### ISSUE TITLE
Maintenance Tasks Running warning for a Log-shipping task

### ISSUE THREAD

**Issue by stgioia** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1623]
@Version = '6.5';
@VersionDate = '20180501'; 

sp_BlitzFirst "Maintenance Tasks Running" finding is listing log-shipping restore commands. I'm using the procedure for a NOC dashboard and every 30 minutes the warning comes up. 

Suggestion: ignore it or split and create a low-priority finding specific for log-shipping (if RESTORE LOG + JOIN msdb..log_shipping_secondary_databases table).

**Comment by BrentOzar** [comment]
Sure, that makes sense! Here's the contributing guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

You've successfully done the first step, filing an issue, and the issue makes sense. I don't think anyone would argue with that request. Next, the contributing guide describes how to get started making the change that you want.

Github can be a kinda intimidating when you first get started, so if you can't make it work, just put the code changes you want here in the issue, and a community volunteer may be able to get that in.

If you didn't want to code this yourself, no problem - you can close it, or I can, either way.

**Comment by BrentOzar** [comment]
I agree, makes sense!
