### ISSUE TITLE
sp_BlitzIndex: add page_io_latch_wait_in_ms to @Mode = 2 output

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1626]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
We're not including the page_io_latch_wait_in_ms field from sys.dm_db_index_operational_stats in @Mode = 2 output. Later, we can think about setting thresholds or giving people advice on it, but for now, let's just start collecting it.

**Comment by BlitzErik** [comment]
I think these would generally be interesting:

- page_latch_wait_count
- page_latch_wait_in_ms
- page_io_latch_wait_count
- page_io_latch_wait_in_ms
