### ISSUE TITLE
sp_BlitzQueryStore Azure SQL Managed Instance version check failure

### ISSUE THREAD

**Issue by OmnipotentOwl** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1627]
**Bug Report**
sp_BlitzQueryStore v2.5 version date: 20180501

**What is the current behavior?**
Currently on an Azure SQL Managed Instance database set at compatibility version 130 when attempting to use sp_BlitzQueryStore the following error message is displayed "Sorry, sp_BlitzQueryStore doesn't work on Azure Data Warehouse, or Azure Databases with DB compatibility < 130." Looking inside the SP at why this might be I can see that the code that determines if the SP is compatible is testing for a specific EngineEdition that MI doesn't use. 
```

IF  ( (SELECT SERVERPROPERTY ('EDITION')) = 'SQL Azure' )
	BEGIN
		SET @is_azure_db = 1;

		IF	(	(SELECT SERVERPROPERTY ('ENGINEEDITION')) <> 5
			OR	(SELECT [compatibility_level] FROM sys.databases WHERE [name] = DB_NAME()) < 130 
			)
		BEGIN
			SELECT @msg = N'Sorry, sp_BlitzQueryStore doesn''t work on Azure Data Warehouse, or Azure Databases with DB compatibility < 130.' + REPLICATE(CHAR(13), 7933);
			PRINT @msg;
			RETURN;
		END;
	END;
```
Running the SELECT SERVERPROPERTY ('ENGINEEDITION') query on MI returns a value of 8 which fails the test at the first inside IF statement.

**What is the expected behavior?**
Running sp_BlitzQueryStore for a database at compatibility version 130 or higher would work. A proposed fix would be to change the `(SELECT SERVERPROPERTY ('ENGINEEDITION')) <> 5` to instead be something like `(SELECT SERVERPROPERTY ('ENGINEEDITION')) NOT IN (5,8)`. I have tested this change and it does resolve the issue and allows the SP to work on MI.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Azure SQL Managed Instance

**Comment by BrentOzar** [comment]
Sure, sounds good - go for it. Here's the contributing guide explaining how to make the change:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

**Comment by OmnipotentOwl** [comment]
Hopefully, I followed the process correctly for updating the TSQL code in GitHub. Please let me know if you need anything else for this.

**Comment by BlitzErik** [comment]
That looks perfect, thanks @OmnipotentOwl
