### ISSUE TITLE
High levels of CPU and reads when executing sp_BlitzFirst

### ISSUE THREAD

**Issue by Jimixter** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1629]
On our production SQL Server 2014 Web Edition instance, sp_WhoIsActive has highlighted that sp_BlitzFirst is resulting in up to 3 million reads and a CPU overhead of up to 62,000 each time it is executed (it takes nearly 30 seconds to complete each time). I wondered if you might please have any thoughts on this?

We have configured a SQL Agent job to run the following every 15 minutes:

EXEC dbo.sp_BlitzFirst 
	@OutputDatabaseName = 'DBAtools', 
	@OutputSchemaName = 'dbo', 
	@OutputTableName = 'BlitzFirst',
	@OutputTableNameFileStats = 'BlitzFirst_FileStats',
	@OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
	@OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
	@OutputTableNameBlitzCache = 'BlitzCache';

The main offending sections of code appear to be as follows:

WITH XMLNAMESPACES('http://schemas.microsoft.com/sqlserver/2004/07/showplan' AS p)
UPDATE b
SET b.is_fast_forward_cursor = 1
FROM ##bou_BlitzCacheProcs b
JOIN #statements AS qs
ON b.SqlHandle = qs.SqlHandle
CROSS APPLY qs.statement.nodes('/p:StmtCursor') AS n1(fn)
WHERE SPID = @@SPID
AND n1.fn.exist('//p:CursorPlan/@CursorActualType[.="FastForward"]') = 1
OPTION (RECOMPILE)

WITH XMLNAMESPACES('http://schemas.microsoft.com/sqlserver/2004/07/showplan' AS p)
UPDATE ##bou_BlitzCacheProcs
SET sort_cost = y.max_sort_cost 
FROM (
	SELECT x.SqlHandle, MAX((x.sort_io + x.sort_cpu)) AS max_sort_cost
	FROM (
		SELECT 
		       qs.SqlHandle,
			   relop.value('sum(/p:RelOp/@EstimateIO)', 'float') AS sort_io,
			   relop.value('sum(/p:RelOp/@EstimateCPU)', 'float') AS sort_cpu
		FROM   #relop qs
		WHERE [relop].exist('/p:RelOp[(@PhysicalOp[.="Sort"])]') = 1
		) AS x
	GROUP BY x.SqlHandle
	) AS y
WHERE ##bou_BlitzCacheProcs.SqlHandle = y.SqlHandle
AND SPID = @@SPID
OPTION (RECOMPILE)

WITH XMLNAMESPACES('http://schemas.microsoft.com/sqlserver/2004/07/showplan' AS p)
UPDATE ##bou_BlitzCacheProcs
SET remote_query_cost = x.remote_query_cost
FROM (
SELECT 
       qs.SqlHandle,
	   MAX(relop.value('sum(/p:RelOp/@EstimatedTotalSubtreeCost)', 'float')) AS remote_query_cost
FROM   #relop qs
WHERE [relop].exist('/p:RelOp[(@PhysicalOp[contains(., "Remote")])]') = 1
GROUP BY qs.SqlHandle
) AS x
WHERE ##bou_BlitzCacheProcs.SqlHandle = x.SqlHandle
AND SPID = @@SPID
OPTION (RECOMPILE)

WITH XMLNAMESPACES('http://schemas.microsoft.com/sqlserver/2004/07/showplan' AS p)
UPDATE ##bou_BlitzCacheProcs
SET is_computed_filter = x.filter_function
FROM (
SELECT 
r.SqlHandle, 
c.n.value('count(distinct-values(//p:UserDefinedFunction[not(@IsClrFunction)]))', 'INT') AS filter_function
FROM #relop AS r
CROSS APPLY r.relop.nodes('/p:RelOp/p:Filter/p:Predicate/p:ScalarOperator/p:Compare/p:ScalarOperator/p:UserDefinedFunction') c(n) 
) x
WHERE ##bou_BlitzCacheProcs.SqlHandle = x.SqlHandle
AND SPID = @@SPID
OPTION (RECOMPILE)

Hope you can help.

James

**Comment by BlitzErik** [comment]
Hi,

Yeah, there's not a lot we can do there. That's sp_BlitzCache processing query plan XML. On some servers it's fast (1-5 seconds), and on other servers it's slower.

The main hurdles are:

1. Plan size: Larger plans take longer to explore the XML in
2. Server size: Smaller servers that are already overloaded take more time to work through XML generally

You didn't include which version of the FRK you're running, but I moved many checks to under the `ExpertMode` flag a few months ago. The logging mechanism should skip most of the ones you mentioned.

I'm also open to suggestions on improving the XQuery used to parse things, if you've got any.

Thanks

**Comment by Jimixter** [comment]
Hi Erik,

Thank you for your prompt reply, apologies I couldn't get back to you
sooner. I'd already left the office for the weekend when you responded, and
was on baby/Father's Day duties all weekend!

We are using version 6.4 of the FRK (i.e. two version behind). Looking at
sp_BlitzCache v6.6, I can see new BEGIN END blocks around some of the
checks, with IF @ExpertMode = 1. So we will look to implement the latest
version as it may well help to reduce these issues, thank you.

We did find some interesting XQuery performance improvements could be made,
by specifying the use of singleton elements (i.e. the first occurrence
denoted by [1], rather than any occurrence). This appeared to have a large
bearing on how the query plan was optimised before execution. Please take a
look at the link below and let me know if you have any thoughts. Perhaps it
might help to reduce the read counts in sp_BlitzCache too?

https://www.sqlservercentral.com/Forums/1951026/Inefficient-TSQL-Query-using-XQuery

We also noticed that using single backslashes rather than double
backslashes in the XQuery (e.g. '/MyXML[1]/Test' instead of  '//MyXML[1]/Test')
also had a small impact on query performance, since the latter will be
searching for any occurrence rather than the direct path.

For example, the following change might improve performance?

BEFORE:
WITH XMLNAMESPACES('http://schemas.microsoft.com/sqlserver/2004/07/showplan'
AS p)
UPDATE b
SET b.is_fast_forward_cursor = 1
FROM ##bou_BlitzCacheProcs b
JOIN #statements AS qs
ON b.SqlHandle = qs.SqlHandle
CROSS APPLY qs.statement.nodes('/p:StmtCursor') AS n1(fn)
WHERE SPID = @@SPID
AND n1.fn.exist('//p:CursorPlan/@CursorActualType[.="FastForward"]') = 1
OPTION (RECOMPILE)

AFTER:
WITH XMLNAMESPACES('http://schemas.microsoft.com/sqlserver/2004/07/showplan'
AS p)
UPDATE b
SET b.is_fast_forward_cursor = 1
FROM ##bou_BlitzCacheProcs b
JOIN #statements AS qs
ON b.SqlHandle = qs.SqlHandle
CROSS APPLY qs.statement.nodes('/p:StmtCursor') AS n1(fn)
WHERE SPID = @@SPID
AND n1.fn.exist('/p:CursorPlan[1]/@CursorActualType[.="FastForward"]') = 1
OPTION (RECOMPILE)

All the best,

James

**Comment by BlitzErik** [comment]
Hi James,

Unfortunately, we can't rely on something we're looking for being in the first occurrence of an xml path or node. There can be many occurrences that we need to check. 

Thanks, 
Erik

**Comment by Jimixter** [comment]
Hi Erik,

Yes I thought that may be the case. We were just surprised how much of a
difference this made to the query plan and performance.

Thanks for your help.

James

**Comment by BlitzErik** [comment]
In a year or so when we no longer have to support 08 and 08R2, I may revisit [selective XML indexes](https://brentozar.com/archive/2016/12/selective-xml-indexes-not-bad/). 

The trouble is that sometimes creating them takes as long as just running the query, and we have many different paths to explore, so choosing the right one(s) would be quite an exercise.
