### ISSUE TITLE
Feature request: Please remove hard dependency to Ola's scripts being installed in Master DB

### ISSUE THREAD

**Issue by ubidev** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1630]
Hi!
Since both of the fantastic tools (Olas maintenance scripts and SSFRK) can be installed to another database than master, it would be great if SSFRK could be configured to point to Olas scripts accordingly.

ubidev :)

**Comment by BrentOzar** [comment]
Sure, that isn't something we need at the company, but it'd be a welcome contribution if you need that functionality. Here's the contributing guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

If that's something you want to tackle, feel free to go for it! Otherwise we'll close this if we don't hear back from you.

**Comment by ubidev** [comment]
I was afraid you'd gently nudge me in that direction lol
Guess I'll finaly start contributing to a project after all :) 
I'll tackle this later this summer on my spare time. 
So please keep this thread open.

**Comment by ShawnCrocker** [comment]
Neither my SSFRK or Ola's scripts are in master  (both are in a "DBA" database) and just work.
None of the SSFRK scripts have a USE except sp_foreachdb.sql

What do you see as the problem exactly?

**Comment by ubidev** [comment]
Sorry for the delay, was in vacation.
If you look at the following installation script https://raw.githubusercontent.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/dev/Install-All-Scripts.sql

then search for "master", you'll come accross the following comment for a starter: 

> Make sure Ola Hallengren's scripts are installed in master

**Comment by BrentOzar** [comment]
Oh sure, so it's just a documentation change? If that's the only thing you need, you can do that pretty easily, right? Is there anything else you need changed?

**Comment by ubidev** [comment]
I was just answering the previous poster, in the hope that I didn't need to quote the full code under the comment...
Now since that attempt obviously failed, here it is...
``

**Comment by BrentOzar** [comment]
OK, no problem - to contribute the change, please follow the contributing guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

If that's something you want to tackle, feel free to go for it! Otherwise we'll close this if we don't hear back from you.

**Comment by ShawnCrocker** [comment]
ah, I don't use Install-All-Scripts.sql so I wouldn't have seen this.
I would suggest that that the checks confirm "in the same database" instead of "in master"

**Comment by BlitzErik** [comment]
@ubidev we haven't heard back from you in a while on this, so I'm going to close it out. Feel free to reopen when you're ready to work on it.

Thanks!
