### ISSUE TITLE
sp_Blitz and sp_BlitzFirst: warn about userstore_tokenperm memory size

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1633]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
We've seen situations where the plan cache is just continuously empty even though there's plenty of memory available. This feedback item suggests that it might be related to userstore_tokenperm size grows to 5GB, but I'm not going to be able to build a repro quickly:

https://feedback.azure.com/forums/908035-sql-server/suggestions/32903272-procedure-cache-empties-spontaneously-even-on-an-i

**What is the expected behavior?**
If we fire the alert for not much plan data in the cache, let's also include a check of the userstore_tokenperm cache size, and suggest clearing that to see if it alleviates the issue.

**Comment by BlitzErik** [comment]
@jadarnel27 found a repro and it turns out we should be using `dm_os_memory_clerks` instead.
