### ISSUE TITLE
@Version and @VersionDate mismatch between bundles and individual scripts

### ISSUE THREAD

**Issue by klitzkrieg** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1635]
For example, the sp_Blitz within the Install-All-Scripts bundle has last months version
```
SET @Version = '6.5';
SET @VersionDate = '20180501';
```
Where the individual script file for sp_Blitz has the current version
`	SET @Version = '6.6';
	SET @VersionDate = '20180601';
`

Otherwise the code matches.

This is consistent across all individual script files and all bundles that I checked.

**Comment by BlitzErik** [comment]
Weird -- try running this PowerShell script: 

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/Documentation/Development/Merge%20Blitz.ps1

See if that resolves it.

**Comment by klitzkrieg** [comment]
Thanks! Recombining the individual scripts with your merge ps1 did the trick.

Looks like all ALTER PROCEDURE statements have the latest version except sp_AllNightLog. But at least the bundle matches the individual script now.

Changes in the merge diff for Install-All-Scripts were 
All but one instance of the SET @version and SET @VersionDate
AND
This line was also different :
Install-All-Scripts Line 556 `AND fl.BackupFile NOT IN (SELECT name from sys.databases where database_id < 5)`

FYI the issue is present in both the GitHub release zip and the zip from https://www.brentozar.com/first-aid/

**Comment by BlitzErik** [comment]
Yeah, ANL hasn't gotten any updates in quite a while. We haven't gotten any issues on it, so we're guessing adoption wasn't very high. 

It looks like I forgot to re-run the merge after bumping the version numbers. The code itself should have been bumped when I did the first round of testing though.

Thanks!
