### ISSUE TITLE
Add @IgnorePrioritiesBelow and @IgnorePrioritiesAbove to sp_blitzFirst

### ISSUE THREAD

**Issue by stgioia** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1638]
Current version: 
SET @Version = '6.5';  
SET @VersionDate = '20180501'; 

Self-explanatory title. Maybe we could @IgnorePrioritiesBelow and @IgnorePrioritiesAbove parameters for sp_blitzFirst (similar to sp_Blitz).

**Comment by BrentOzar** [comment]
Sure, makes sense. You can probably pretty much copy paste the logic out of sp_Blitz if you want. In there, I’m not really skipping the checks - just not showing the output to the end user. I would understand if you want to skip running the checks altogether, but that’d be a lot more work - your call, either way that you want to code it is fine.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by stgioia** [comment]
Well, since there are quite a few heavyweight checks I was thinking about
skipping it, but I'll evaluate how much work needs to be done.

Thanks

**Comment by BlitzErik** [comment]
@stgioia haven't heard back from you in a while on this. I'm going to close it out for now, but feel free to reopen it when you're ready to work on it. Thanks!
