### ISSUE TITLE
sp_BlitzCache: Target string size is too small to represent the XML instance

### ISSUE THREAD

**Issue by william001** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1640]
Applies to: sp_BlitzCache version 6.5 & 6.6

When running exec sp_BlitzCache @SortOrder = 'cpu', on SQL Server 2014 Web edition, I get the following error: 
**Msg 6354, Level 16, State 10, Procedure sp_BlitzCache, Line 3504 [Batch Start Line 0]
Target string size is too small to represent the XML instance**

Here is the full list of messages generated:
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking plan cache age
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring system databases by default
Applying chosen sort order
Substituting NULLs for spill columns in older versions of SQL
Adding additional info columns for newer versions of SQL
Getting memory grant information for newer versions of SQL
Substituting NULLs for spill columns in older versions of SQL
Adding SQL to collect trigger stats.
Collecting execution plan information.
Attempting to aggregate stored proc info from separate statements
Warning: Null value is eliminated by an aggregate or other SET operation.
Computing CPU, duration, read, and write metrics
Update CPU percentage for stored procedures
Gather percentage information from grouped results
Begin XML nodes processing
Gathering high level plan information
Warning: Null value is eliminated by an aggregate or other SET operation.
Performing compile timeout checks
Performing compile memory limit exceeded checks
Gathering trivial plans
Gathering statement costs
Updating statement costs
Gathering stored procedure costs
Checking for plan warnings
Checking for implicit conversion
Performing TVF join check
Checking for table variables
Checking for expensive key lookups
Checking for expensive remote queries
Checking for expensive sorts
Checking for Optimistic cursors
Checking if cursor is Forward Only
Checking if cursor is Fast Forward
Checking for Dynamic cursors
Checking for filters that reference scalar UDFs
Checking for forced serialization
Checking for downlevel cardinality estimators being used on SQL Server 2014.
Performing query level checks
Gathering additional plan level information
Warning: Null value is eliminated by an aggregate or other SET operation.
Attempting to get stored procedure name for individual statements
Trace flag checks
Checking for MSTVFs
Checking for non-sargable predicates
Getting information about implicit conversions and stored proc parameters
Getting variable info
Getting conversion info
Parsing conversion info
Updating variables for inserted procs
Inserting variables for other procs
Updating procs
Updating SET options
Updating conversion XML
Updating cached parameter XML for stored procs
Updating cached parameter XML for statements
Filling in implicit conversion info
Msg 6354, Level 16, State 10, Procedure sp_BlitzCache, Line 3504 [Batch Start Line 0]
Target string size is too small to represent the XML instance

This did appear to work previously so I suspect it's something different in the data its reporting on.

**Comment by BlitzErik** [comment]
This was also reported in #1624 and fixed in dev. It's helpful to search closed issues before filing new ones.

Thanks!
