### ISSUE TITLE
Install-All-Scripts.sql has a May version

### ISSUE THREAD

**Issue by lehase** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1641]
Hi!
I was pulled June Release from github, and try to update all scripts with Install-All-Scripts.sql
But @VersionDate = '20180501'; is from May release. In single files it's OK, But InstallAllScript is very comfortable to upgrade all stuff.

**Comment by BrentOzar** [comment]
Thanks, but before you file an issue, make sure you search past issues. This was already filed and will be fixed in the next release:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/1635
