### ISSUE TITLE
Memory Dumps reported by sp_blitz

### ISSUE THREAD

**Issue by mightymouse84** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1647]
sp_blitz is reporting Memory Dumps that happened 11 months ago.
Could there be a default period for reporting these.
I run regularly so I'm well aware of them1

That ain't good. I've had 5 memory dumps between Jul 24 2017  8:30AM and Jul 24 2017  8:44AM!

Version of blitz is sp_Blitz Jun  1 2018 12:00AM

**Comment by BlitzErik** [comment]
You can [skip checks](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/README.md#skipping-checks-or-databases) if you don't care about them. Hit the link to view the readme.

If you'd like to change how far back we look for dumps, what period of time makes sense to you?

Adding a configurable period of time to look back would be more work than is worth it, given the number of checks that have date dependencies, and wouldn't be worth adding a parameter for just one.

Thanks!

**Comment by mightymouse84** [comment]
I get email alerts of events like that, so anything over 2 weeks (say I was on holiday and wasn't around to check) isn't really of use. A month would be safe, I guess but everyone's different.
I wouldn't want to skip the check to lose old results as not all servers I audit are mine to 'manage' , I often report findings to others.

Thank you

**Comment by BlitzErik** [comment]
Okay, cool. Have a look at the [contributing guide](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md) to get started on how to get your code added to the project.

**Comment by BlitzErik** [comment]
Haven't heard back from you on this, so I'm going to close the issue out for now. If you decide you want to work on it later, feel free to reopen it.

Thanks!
