### ISSUE TITLE
sp_BlitzIndex - spelling mistake in error message

### ISSUE THREAD

**Issue by roy-tate** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1648]
**Do you want to request a *feature* or report a *bug*?**
Minor annoyance bug in version 6.5 of sp_BlitzIndex

**What is the current behavior?**

Msg 50000, Level 16, State 1, Procedure sp_BlitzIndex, Line 1483 [Batch Start Line 0]
FOO database failed to process. @Filter only **appies** when @Mode=0 and @TableName is not specified. Please try again.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
execute dbo.sp_BlitzIndex @DatabaseName = 'FOO', @SchemaName = 'bar', @Mode = 3, @Filter = 1

Line 808 contains ...
SET @msg=N'@Filter only appies when @Mode=0 and @TableName is not specified. Please try again.';

Should contain ...
SET @msg=N'@Filter only applies when @Mode=0 and @TableName is not specified. Please try again.';

**What is the expected behavior?**
The message should say "... only applies ..."

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Affects all SQL versions.

**Comment by BlitzErik** [comment]
Thanks for letting us know. Did you want to code the fix yourself?
