### ISSUE TITLE
sp_BlitzIndex - Collation Conflict in Azure SQL DB

### ISSUE THREAD

**Issue by visionthroughdesign** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1652]
**BUG:** 
Currently running sp_BlitzIndex on
Database Edition: Premium
Azure SQL Version: Microsoft SQL Azure (RTM) - 12.0.2000.8

**What is the current behavior?**
When running sp_BlitzIndex it fails on Check_id 11: Total lock wait time > 5 minutes (row + page) with long average waits. The following error is presented - Msg 451, Level 16, State 1, Procedure sp_BlitzIndex, Line 2177 - Cannot resolve collation conflict between "SQL_Latin1_General_CP1_CI_AS" and "Latin1_General_BIN2" in add operator occurring in ORDER BY statement column 3.

When you remove the section for --Aggressive Indexes: Check_id 10-19 - It runs without any issues. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

Installed Latest version of sp_BlitzIndex on Azure SQL. 
Running against user database and experiencing the error listed above.

**Comment by BrentOzar** [comment]
OK, good news and bad news: the bad news is that Azure SQL DB isn't supported. This may not be the only problem you run into as you try different parameters.

The good news is that you can probably fix this if you want - it involves a collation difference between your user database and TempDB. You can fix it by explicitly naming collations on both sides of that query involved, like using the database default as described here:

https://stackoverflow.com/questions/2290753/doing-a-join-across-two-databases-with-different-collations-on-sql-server-and-ge

If this is something you'd like to do, check out our contributing guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

If you don't want to fix it, totally understood - just let us know and we can close the issue, or another community member may be interested in running with it.

**Comment by visionthroughdesign** [comment]
Thanks for the response Brent,

Will take a look into it in a few days, I've tried across a few different instances of Azure SQL and same issue. Just seems to be the Aggressive Indexes checks that are failing.

**Comment by BrentOzar** [comment]
This morning, I tried repeatedly to reproduce this, and I haven't been able to. If you want to work on it again at some point, feel free to reopen the issue. Thanks anyway!
