### ISSUE TITLE
sp_Blitz - not reporting last backups correctly on SQL 2014/2016 Developer Edition

### ISSUE THREAD

**Issue by mike-halford** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1654]
We are having issues with out two Developer Edition servers. 

sp_blitz is reporting Priority 1 (Finding - Backups Not Performed Recently)(Details - Last backed up never) when we can confirm the databases are backup up. This is happening on both the 2014 and 2016 developer editions of SQL Server and for every database on these servers.

**Comment by BrentOzar** [comment]
Sorry to hear that! Go ahead and look in the code for the query sp_Blitz is using to check for backups, and then run that on your own servers separately to see what's going on. (Every time I've worked with folks on this, they've either been surprised that the backups weren't really happening, or they had a configuration issue like the database names didn't match in MSDB, or the server names didn't match, etc.)

**Comment by mike-halford** [comment]
Can confirm that the following code reports successful backups and backup files are being created.

> SELECT sdb.Name AS DatabaseName,
COALESCE(CONVERT(VARCHAR(12), MAX(bus.backup_finish_date), 101),'-') AS LastBackUpTime
FROM sys.sysdatabases sdb
LEFT OUTER JOIN msdb.dbo.backupset bus ON bus.database_name = sdb.name
GROUP BY sdb.Name

**Comment by BrentOzar** [comment]
Keep digging - without seeing the data, I can’t really take this as a bug report because it’s working great here. If you’re on a case sensitive server, for example, pay particular attention to the cases on both the database names AND the server names.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by mike-halford** [comment]
We have subsequently run the procedures again on the servers and this time they are not reporting missing/failed backups. Not sure why but we will continue to monitor.

Thanks
