### ISSUE TITLE
sp_DatabaseRestore sanity check folders with xp_dirtree

### ISSUE THREAD

**Issue by kimchipantload** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1662]
*BUG*
sp_DatabaseRestore v6.7

It appears as though the switch from xp_cmdshell to xp_dirtree has caused an issue with the empty directory detection.

Currently xp_dirtree will return 0 records when the directory is empty, but the script is assuming at least 1 result of NULL, which is the normal result of an empty directory using xp_cmdshell

IF (
		SELECT COUNT(*) 
		FROM @FileList AS fl 
		) = 1
	AND (
		SELECT COUNT(*) 
		FROM @FileList AS fl 							
		WHERE fl.BackupFile IS NULL
		) = 1

		BEGIN
	
			RAISERROR('That directory appears to be empty', 0, 1) WITH NOWAIT;
	
			RETURN;
	
		END

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?** 
I would imagine any version with xp_dirtree. Yes, this was functional before the xp_cmdshell switch.

First time submitting so I apologize in advance.

Thanks!

**Comment by BlitzErik** [comment]
Hi! Thanks for letting us know! Couple questions:

1. Were you going to submit a fix yourself?
2. If not, can you let us know what would fix it?

**Comment by kimchipantload** [comment]
@ShawnCrocker I like the idea of handling both situations. What if, instead of a parameter, we do a check for xp_cmdshell being enabled? If enabled, use it, else use xp_dirtree. 

over simplified example

`IF (
	SELECT CONVERT(INT, value_in_use)
	FROM sys.configurations 
	WHERE name = 'xp_cmdshell'
) = 1
BEGIN
	PRINT 'use xp_cmdshell'
END
ELSE
	PRINT 'xp_cmdshell not enabled. using xp_dirtree'`

**Comment by ShawnCrocker** [comment]
I'll do it. Summary:
- new parameter @SimpleFolderEnumeration bit default = 0
- if set to 1 or xp_cmdshell disabled, use my new code and skip checks

**Comment by BlitzErik** [comment]
You're the man, man.
