### ISSUE TITLE
Feature Request: sp_RestoreDatabase: Allow restore standby for full and differential database restore

### ISSUE THREAD

**Issue by lionicsql** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1671]
Currently the standby parameters:
@StandbyMode, @StandbyUndoPath are used to affect @LogRecoveryOption and are ignored otherwise.
Adding the standby options to @sql will make the behavior consistent for log, differential and full restores.

**Comment by BlitzErik** [comment]
This is a good idea! Thanks. 

To get the obvious stuff out of the way: were you planning on coding this, or did you want someone else from the community to do it?

**Comment by lionicsql** [comment]
I have a fix working locally. I'd be happy to work on a pull request!


On Tue, Jul 3, 2018, at 6:47 PM, BlitzErik wrote:
> This is a good idea! Thanks.


> To get the obvious stuff out of the way: were you planning on coding
> this, or did you want someone else from the community to do it?> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/1671#issuecomment-402322497

**Comment by lionicsql** [comment]
PR #1675 added.
