### ISSUE TITLE
@StandbyMode = 1 in sp_Databaserestore is broken

### ISSUE THREAD

**Issue by reharmsen** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1673]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.
Version = '6.7';
VersionDate = '20180701';

**What is the current behavior?**
@StandbyMode = 1, does not properly set @LogRecoveryOption, and therefore the restore always uses NORECOVERY

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
EXECUTE [DBADB].[dbo].[sp_DatabaseRestore] 
	@Database = 'SOURCE', 
	@RestoreDatabaseName = 'DEST', 
	@BackupPathFull = '\\BACKUP\\SQL\BLA\FULL\', 
	@BackupPathLog = '\\BACKUP\\SQL\BLA\LOG\', 
	@MoveFiles = 1, 
	@MoveDataDrive = 'F:\SQLData\', 
	@MoveLogDrive = 'G:\SQLLog\', 
	@ContinueLogs = 1, 
	@RunRecovery = 0,
	@StandbyMode = 1,
	@StandbyUndoPath = 'G:\SQLLogship\',
	@ExistingDBAction = 2,
	@Debug = 1;

**What is the expected behavior?**
That @LogRecoveryOption is set with 'STANDBY = ''' + @StandbyUndoPath + @Database + 'Undo.ldf'

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Did work in a previous version... seems related to the changed made with  #1656

Seems to g wrong in this part of code:

IF (@StandbyMode = 1)
	BEGIN
		IF (@StandbyUndoPath IS NULL)
			IF @Execute = 'Y' OR @Debug = 1 RAISERROR('The file path of the undo file for standby mode was not specified. Logs will not be restored in standby mode.', 0, 1) WITH NOWAIT;
		ELSE
			SET @LogRecoveryOption = N'STANDBY = ''' + @StandbyUndoPath + @Database + 'Undo.ldf''';
	END;

The last ELSE, should be an ELSE for IF (@StandbyUndoPath IS NULL), but is an ELSE for IF @Execute = 'Y'...

**Comment by reharmsen** [comment]
Can be fixed by changing 'IF @Execute = 'Y'..... '  into:

			BEGIN
				IF @Execute = 'Y' OR @Debug = 1 RAISERROR('The file path of the undo file for standby mode was not specified. Logs will not be restored in standby mode.', 0, 1) WITH NOWAIT;
			END;



But there might be other stuff broken in the procedure to.

**Comment by BrentOzar** [comment]
Thanks for reporting it! We don't use this stored proc actively as a company - we're just maintaining the open source repo - so you're welcome to submit bug fixes, and talk about them with the community here.

Here's the contributing guide that explains how to get started with contributing your fixes:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md

If you have any questions about the process or need help, feel free to ask them here, or talk in the Slack channel described in the guide. Thanks!

**Comment by reharmsen** [comment]
See PR #1674
