### ISSUE TITLE
sp_BlitzLock fails when a Indexname [<Name of Missing Index, sysname,>] is involved

### ISSUE THREAD

**Issue by btammenga** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1694]
Bug using sp_BlitzLock  v 1.7

Following errormessage is shown:
Msg 9415, Level 16, State 1, Procedure sp_BlitzLock, Line 170 
XML parsing: line 66, character 95, well formed check: no '<' in attribute value

After diving into the code of sp_BlitzLock i found that the error occurs on the following part (Line 174):
SELECT CONVERT(XML, event_data) AS deadlock_xml
             FROM   sys.fn_xe_file_target_read_file(@EventSessionPath, NULL, NULL, NULL)

The bug occurs when, in the rare event, someone names an index [<Name of Missing Index, sysname,>]
This breaks the XML syntax,

It seems to work, when i replace the code with:
 SELECT CONVERT(XML, REPLACE(event_data,'<Name of Missing Index, sysname,>','NameofMissingIndex')) AS deadlock_xml 
             FROM   sys.fn_xe_file_target_read_file(@EventSessionPath, NULL, NULL, NULL)

**Comment by BlitzErik** [comment]
This is a general bug with how Microsoft handles the xml: https://feedback.azure.com/forums/908035-sql-server/suggestions/33731290-correctly-escape-predefined-entities-in-deadlock-x
