### ISSUE TITLE
sp_Blitz - Add information if connected to an Availability Group

### ISSUE THREAD

**Issue by JulieOKC** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1713]
**New Feature**
**What is the current behavior?**
No information is listed about AGs

**Which versions of SQL Server and which OS are affected by this issue?**
I've run the following code against SQL 2005 - 2016, some containing SQL AGs of SQL 2012, 2014 & 2016.

--------------------- Code Below --------------------------
-- Will notify user if the server is an Availability Group server and if they are connect to the server or the listener.
-- Will notify user of cluster name & quorum type
-- List the node names
-- List if the AG is using a file share or disk as a witness
-- Will notify user if one or more of the nodes is down
-- Number of quorum votes and who holds them

DECLARE @strData as nvarchar(125);
DECLARE @NodeListener AS nvarchar;
DECLARE @ListenerConnect as BIT;

SET @strData = '';
SET @NodeListener = '';
SET @ListenerConnect = '';

IF SERVERPROPERTY(N'IsHadrEnabled') = 1
BEGIN -- Server is AG
     SET @ListenerConnect = (SELECT  COUNT(agl.dns_name)
     FROM sys.availability_groups AS ag
     JOIN sys.availability_group_listeners agl ON ag.group_id = agl.group_id
     JOIN sys.availability_group_listener_ip_addresses aglip ON agl.listener_id = aglip.listener_id
     JOIN sys.dm_exec_connections ec ON aglip.ip_address = ec.local_net_address
     WHERE ec.session_id = @@SPID) 
    SET @strData = 
       CASE @ListenerConnect
          WHEN 0 THEN 'This server is part of AG cluster. Current connection is to the server.'
          ELSE        'This server is part of AG cluster. Current connection is to the listener.'
       END -- CASE
    SELECT '200', 'Informational','AG Cluster Info'
        , '', 'https://BrentOzar.com/', @strData, '', '', '9999' --Update CheckID
    UNION
    SELECT '200', 'Informational','AG Cluster Info'
        , '', 'https://BrentOzar.com/'
		, 'Cluster name = ' + cluster_name + '. Cluster quorum type = ' + quorum_type_desc + '. Available types are: Node Majority, Node & Disk Majority, Node & File Share Majority, No Majority'
		, '', '', '9999' --Update CheckID
    FROM sys.dm_hadr_cluster 
    UNION
	SELECT '200', 'Informational','AG Cluster Info'
        , '', 'https://BrentOzar.com/'
		, 'Node names for the cluster: ' + STUFF ((SELECT ', ' + member_name 
                     FROM sys.dm_hadr_cluster_members WHERE member_type = 0
					 FOR XML PATH('')
                     ),1,2,'') 
		, '', '', '9999' --Update CheckID
    UNION
	SELECT '200', 'Informational','AG Cluster Info'
        , '', 'https://BrentOzar.com/'
		, 'This Availability Group is using a ' + member_type_desc + '.'
		, '', '', '9999' --Update CheckID
	FROM sys.dm_hadr_cluster_members WHERE member_type <> 0
UNION
   SELECT '200', 'Warning','AG Cluster Info - warning'
        , '', 'https://BrentOzar.com/'
		, 'Node ' + member_name + ' is offline! This means the server cannot participate in a faileover!' 
		, '', '', '9999' --Update CheckID
   FROM sys.dm_hadr_cluster_members 
   WHERE member_state = 0
UNION
   SELECT DISTINCT '200', 'Informational','AG Cluster Info'
        , '', 'https://BrentOzar.com/'
		, 'Total quorum votes = ' + (CAST((select COUNT(*) FROM sys.dm_hadr_cluster_members
                                     WHERE number_of_quorum_votes = 1) AS nchar(3))) + ' held by : ' +
                                     STUFF ((SELECT ', ' + member_name 
                                             FROM sys.dm_hadr_cluster_members
                                             WHERE number_of_quorum_votes = 1
					                 FOR XML PATH('')
                     ),1,2,'')
		, '', '', '9999' --Update CheckID
FROM sys.dm_hadr_cluster_members
END
ELSE
BEGIN
   SELECT '', '','', '', '', '', '', '', '' WHERE 1<>1
END;

**Comment by BlitzErik** [comment]
You would have to make this dynamic to make sure that those views and columns exist. We still have to support 2008/R2 for another year.

**Comment by JulieOKC** [comment]
Need to remove the @@ServerName, from the first SELECT statement and '', from the second.

**Comment by BlitzErik** [comment]
@JulieOKC I know you worked with Brent a little on this -- gonna close it out until you're ready to pick things back up.

Thanks!

**Comment by JulieOKC** [comment]
Have the script ready. Planned on uploading today.

**Comment by JulieOKC** [comment]
I believe I have uploaded the change, but am not sure how to check. Can you verify?
