### ISSUE TITLE
sp_Blitz - Table in model database reports as msdb database

### ISSUE THREAD

**Issue by TheUsernameSelectionSucks** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1719]
**Do you want to request a *feature* or report a *bug*?**
BUG
Script version sp_Blitz Aug  1 2018 12:00AM

**What is the current behavior?**
I have a table in the "model" database, but the DatabaseName columns says "msdb" database, as the "Finding" column reports.

![image](https://user-images.githubusercontent.com/26902750/44219393-828c9e80-a141-11e8-941a-c03befeff446.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

Create table model.dbo.Test_Table (Column1 INT)
EXEC sp_Blitz

**What is the expected behavior?**
The column should report the correct database

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

SQL Server 2016
Windows Server 2012 R2
Not sure if it worked in previous version

**Comment by RichBenner** [comment]
it's a typo at line 2079

    SELECT  29 AS CheckID ,
    'msdb' AS DatabaseName ,
    200 AS Priority ,
    'Informational' AS FindingsGroup ,
    'Tables in the Model Database' AS Finding ,

**Comment by BrentOzar** [comment]
Thanks, fixed!
