### ISSUE TITLE
sp_BlitzWho -- 2017 Memory grants

### ISSUE THREAD

**Issue by osumatt** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1721]
Version = '6.8'

Current Behavior:  Much like #1402, sp_BlitzWho also needs updated for SQL Server 2017.  Sadly, all the cool memory grant columns are missing :(

Expected Behavior:  All the cool memory grant columns are returned!

I will create a pull request.

**Comment by BlitzErik** [comment]
Did you run it with expertmode = 1?

**Comment by osumatt** [comment]
I did!  I am making the PR in a few.  The change that needs made is:

SELECT @EnhanceFlag = 
	    CASE WHEN @ProductVersionMajor = 11 AND @ProductVersionMinor >= 6020 THEN 1
		     WHEN @ProductVersionMajor = 12 AND @ProductVersionMinor >= 5000 THEN 1
		     WHEN @ProductVersionMajor = 13 AND	@ProductVersionMinor >= 1601 THEN 1
			 **WHEN @ProductVersionMajor > 13 THEN 1**
		     ELSE 0 
	    END
