### ISSUE TITLE
Feature request: Can sp_Blitz include the details of the SQL Server version and edition in it's 'informational' output?

### ISSUE THREAD

**Issue by philipthatcher** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1723]
**Do you want to request a *feature* or report a *bug*?**
Feature request:

Can sp_Blitz include the details of the SQL Server version and edition in it's 'informational' output?
i.e The output of SELECT @@VERSION.

I run sp_Blitz across an estate of SQL servers of different versions and editions, and this addition would be useful in the output.

**Comment by BrentOzar** [comment]
Have you tried @CheckServerInfo = 1? I wanna say it’s in there along with a lot of other informational, non-urgent stuff.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by philipthatcher** [comment]
>Have you tried @CheckServerInfo = 1?
I hadn't, but have now.  This certainly generates more useful output, including the SQL version number - which I can use.  Thx.

I've just run the latest sp_Blitz @CheckServerInfo = 1 against
Microsoft SQL Server 2012 (SP3) (KB3072779) - 11.0.6020.0 (X64) 
	Oct 20 2015 15:36:27 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit)
and the text "2012" is not present in the sp_Blitz output.

**Comment by BlitzErik** [comment]
Haven't heard back from you in a while, so closing this out. If you decide you want to work on it later, feel free to reopen the issue.
