### ISSUE TITLE
*feature request* add @sortorder='QueryPlanCost'

### ISSUE THREAD

**Issue by incantius** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1731]
**Do you want to request a *feature* or report a *bug*?**
If you're reporting a bug, include the version number of the script you're using. If it's not the current version, upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build.

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

**What is the expected behavior?**

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

**Comment by incantius** [comment]
left out that this was on sp_BlitzCache

**Comment by BrentOzar** [comment]
Unfortunately, that's a no-go because it would involve querying the XML for every plan in the cache:

https://www.scarydba.com/2017/02/20/estimated-costs-queries/

**Comment by jadarnel27** [comment]
@BrentOzar Based on the timing of comments here, I'm not sure if you saw the issue author's second comment.  I could be missing something obvious here, but isn't that what BlitzCache does (query the XML for every plan in the cache)?
