### ISSUE TITLE
Missing information when running Mode=4 for all databases - M4 tab in CCC

### ISSUE THREAD

**Issue by TaraKizer** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1739]
**Do you want to request a *feature* or report a *bug*?**
Bug - Missing information, such as borderline duplicate key indexes when looking at the M4 tab in the CCC file. When I run Mode=4 manually in a particular database, they show up. The M4 tab has a much shorter list than when run manually for each database.

Compare the Sheet1 info to the M4 tab in 20180823_125000. M4 contains info for 2 databases. Sheet1 is for Mode=4 for one database, Sheet2 is Mode=4 for the other database. M4 has 39 rows. Just Sheet1 has 124 rows. So BIG different and haven't even added in Sheet2 yet.

**What is the current behavior?**

Missing information such as borderline missing indexes

**What is the expected behavior?**

The Mode=4 output for each database should match the output when running Mode=4 and GetAllDatabases=1

**Comment by BlitzErik** [comment]
I kid, I kid.
