### ISSUE TITLE
sp_AllNightLog/Setup CleanUpTime

### ISSUE THREAD

**Issue by gavdraper** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1741]
Take in CleanUpTime to sp_AllNightLogSetup and pass that down to sp_AllNightLog to then pass that into Ola's DatabaseBackup script for log retention. 

For Example

EXEC sp_AllNightLogSetup @CleanUpTime = 24, @BackupPath......

This will delete log files older than 24 hours assuming a full backup has taken place since then. 

I may be missing something and I've never contributed here before but it seems like a simple change and I'm happy to add it in and create a pull request?

**Comment by BrentOzar** [comment]
Sure, go for it! Here's the contribution guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md
