### ISSUE TITLE
sp_Blitz INCLUDES vs INCLUDE

### ISSUE THREAD

**Issue by RichBenner** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1744]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

This comes out of this week's index tuning class. When running sp_BlitzIndex we see things like this;

INEQUALITY: [Reputation], [UpVotes] INCLUDES: [DownVotes]

Brent mentioned this should be singular and it's a simple typo for the fix. Raised the bug because I'd forget about it if it were me :)

**Comment by BrentOzar** [comment]
WOOHOO! Thanks for doing this, man!
