### ISSUE TITLE
sp_BlitzFirst CPU Utilization and High CPU Utilization Mismatch

### ISSUE THREAD

**Issue by bl4met** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1746]
**Do you want to request a *feature* or report a *bug*?**
Bug 
Version 6.9
Version Date 2018-09-01

**What is the current behavior?**
Details for sp_BlitzFirst High CPU Utilization and General CPU Utilization are showing different values. I dont know if this is due to me running an ancient version of SQL Server but to my knowledge theses values reported the same a couple versions back. I have seen the range between the values vary greatly.

In this example High CPU Utilization shows:
`<?ClickToSeeDetails -- 66%. -- ?>`

CPU Utilization shows:
```
<?ClickToSeeDetails -- 
58%. 
Ring buffer details: 
<Record id="393458" type="RING_BUFFER_SCHEDULER_MONITOR" time="23599551976">
	<SchedulerMonitorEvent>
		<SystemHealth>
			<ProcessUtilization>54</ProcessUtilization>
			<SystemIdle>42</SystemIdle>
			<UserModeTime>1913196264</UserModeTime>
			<KernelModeTime>58188373</KernelModeTime>
			<PageFaults>39412</PageFaults>
			<WorkingSetDelta>-8192</WorkingSetDelta>
			<MemoryUtilization>94</MemoryUtilization>
		</SystemHealth>
	</SchedulerMonitorEvent>
</Record>
 -- ?>
```

**What is the expected behavior?**
Both values should show the same if the High CPU Utilization threshold is reached and that finding is visible.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2008R2 10.50.1600.1
Windows Server 2008 R2, SP1

**Comment by BrentOzar** [comment]
Yep, they're checked at different times. You can learn more about the background on that by reading the code. Thanks!
