### ISSUE TITLE
Get sp_DatabaseRestore working on Linux

### ISSUE THREAD

**Issue by CurryEleison** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1750]
I propose to get sp_DatabaseRestore working on Linux. This would be useful for e.g. running test restores and checks of databases in containers.

Currently, attempts to use sp_DatabaseRestore on Linux result in failure. The problems are due to the difference in directory separators between Linux and Windows, and fix the involves some relatively minor adjustments to filename and path handling. 

Is there any interest this enhancement? The change could potentially worsen the complexity of future testing, since there are tricky corner cases like taking a backup on Windows and restoring it to Linux.

If there is interest in this enhancement I propose to do the following:
- Modify sp_DatabaseRestore so it can handle both Unix and Windows-style pathnames to backups and data files
- Ensure that backups originally taken on Windows can be restored to Linux machines and vice-versa
- I can develop it to use parameters to control path-style or alternatively use automatic detection of platforms. Input on your preference is welcome.

Thanks in advance for your thoughts and feedback on this proposal.

**Comment by BlitzErik** [comment]
@CurryEleison are you still interested in working on this? Doing some issue cleanup.

**Comment by CurryEleison** [comment]
@BlitzErik  Thanks for asking and yes I'm working on this. Code is done and I've tested in some challenging circumstances -- it looks good to me. There are a couple of corner cases I'd like to test before I submit though. 
BTW if you have any advice on edge cases you think I should consider or test for I would be happy to work that in.

**Comment by BlitzErik** [comment]
@CurryEleison I wish that I did, but I don't use this proc all that regularly, and I don't use Linux at all. We're happy to take your contribution with the testing you've done. More documentation is always better, though it's a bit of a chore to write.

**Comment by ShawnCrocker** [comment]
@CurryEleison I can't test this on Linux, but I can retrogressively test it on Windows. I use it a lot (and pushed several changes back)

**Comment by BlitzErik** [comment]
@CurryEleison I'm going to be doing a FRK release in about a week -- do you wanna get this code in for that?

**Comment by BlitzErik** [comment]
@CurryEleison I'm going to close this out for now, since we haven't heard from you since September.

If you wanna get it to us at any point, just open a new issue and reference this one.

Thanks!
