### ISSUE TITLE
sp_Blitz - new check to point out alerts that send NULL error messages via email / pager / net-send?

### ISSUE THREAD

**Issue by MisterZeus** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1753]
**Do you want to request a *feature* or report a *bug*?**
New Feature: Should sp_Blitz check whether people have a bunch of alerts set up to send NULL instead of the actual error message, when they get triggered and send out an email / pager / net-send message?

**What is the current behavior?**
sp_Blitz doesn't check for alerts WHERE include_event_description_in = 0

**What is the expected behavior?**
sp_Blitz could check for alerts WHERE include_event_description_in = 0, and warn peopl that they are missing out on free, time-saving details in their email / pager / net-send messages!

**Comment by BrentOzar** [comment]
Sure, sounds interesting! Check out the contributing guide to get started:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

I don't have any input on gotchas with this one - sounds like you've been burned by it so you'll know how to include testing instructions in the issue. Thanks!

**Comment by MisterZeus** [comment]
Thanks Brent!
Yup, I'll script out a way to test this weird situation, where you get an alert email that basically says "Hey! This thing happened! I won't tell you why (even though I can), cause you didn't tick the right box when you made me! Ha-ha!"
