### ISSUE TITLE
sp_BlitzIndex check 48 NVARCHAR(10) for Read/Write is too short

### ISSUE THREAD

**Issue by jerryhung** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1759]
**Do you want to request a *feature* or report a *bug*?**
BUG
sp_BlitzIndex(TM) v6.9 - September 01, 2018: Database [XXX] as of 2018-09-11 09:40

**What is the current behavior?**
Failed with error "Arithmetic overflow error converting expression to data type nvarchar."
at check_id 48 "Index with High Writes:Reads" as we have index with BIG numbers (see below)
1st one is Length 11 > NVARCHAR(10)

Reads: 3156 Writes: 19292194290 on: 	**11**
Reads: 3154 Writes: 7035822994 on: 	10
Reads: 13028 Writes: 1117698633 on: 	10
Reads: 255 Writes: 1900957720 on: 	10
Reads: 887480 Writes: 1901137758 on: 	10
Reads: 29 Writes: 1902298371 on: 	10
Reads: 13028 Writes: 1901500391 on: 	10
Reads: 81535 Writes: 1902372705 on: 	10
Reads: 4467 Writes: 1914391407 on: 	10
Reads: 42513 Writes: 1898953401 on: 	10
Reads: 240 Writes: 1433555666 on: 	10

**What is the expected behavior?**
I increased the length frmo 10 to 100 and all is good now
								+ CONVERT(NVARCHAR(100), i.total_reads)
								+ N' Writes: ' 
								+ CONVERT(NVARCHAR(100), i.user_updates)

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2014

**Comment by BlitzErik** [comment]
While I'm in here, I also want to format these numbers better. They could probably use some commas if people are hitting 11 digit numbers in writes.

I'd also humbly suggest that if you have 11 digit number writes and four digit number reads, you're well overdue for some index tuning ;)
