### ISSUE TITLE
sp_Blitz - Ignore Change Tracking for Databases in SkipChecks

### ISSUE THREAD

**Issue by dallyhorton** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1760]
Howdy!

I've been playing around with an idea that makes my experiance with sp_Blitz better. I have the MDS database on my instance and I've added this to my BlitzChecksToSkip table. When I run sp_Blitz it warns me that Change Tracking is enabled for MDS. I don't want to ingore this CheckID, but I do want to ingore MDS.

I've tweaked the code for the SkipChecks section to ingore any databases in my BlitzChecksToSkip table:

```SQL
IF NOT EXISTS ( SELECT  1
		FROM    #SkipChecks
		WHERE   DatabaseName IS NULL AND CheckID = 112 )
	AND EXISTS (SELECT 1 FROM master.sys.change_tracking_databases AS ctd
			INNER JOIN sys.databases AS d ON ctd.database_id = d.database_id 
			WHERE d.name NOT IN (SELECT DatabaseName FROM #SkipChecks
					WHERE DatabaseName IS NOT NULL))
```

Then I tweaked the @StringToExecute to exclude databases I've asked to ingore. I'm also returning the database name because we're already getting one output row for each database. We not include the name?

```SQL
SET @StringToExecute = 'INSERT INTO #BlitzResults
	(CheckID,
	Priority,
	FindingsGroup,
	Finding,
	DatabaseName,
	URL,
	Details)
SELECT 112 AS CheckID,
100 AS Priority,
''Performance'' AS FindingsGroup,
''Change Tracking Enabled'' AS Finding,
d.[name],
''https://BrentOzar.com/go/tracking'' AS URL,
( d.[name] + '' has change tracking enabled. This is not a default setting, and it has some performance overhead. It keeps track of changes to rows in tables that have change tracking turned on.'' ) AS Details FROM sys.change_tracking_databases AS ctd INNER JOIN sys.databases AS d ON ctd.database_id = d.database_id WHERE d.name NOT IN (SELECT DatabaseName FROM #SkipChecks WHERE DatabaseName IS NOT NULL) OPTION (RECOMPILE)';
```

I don't have a SQL 2008 instance to test with, but the code looks to me like it should run on older versions.

Does this seem like a good idea?

Cheers,
Troy

**Comment by BrentOzar** [comment]
You're close! The columns in SkipChecks include both CheckId and DatabaseName. You would want to skip checks on a particular database if either:

* CheckID = 112 and DatabaseName is null (meaning, skip check 112 for all databases), or
* CheckID is null and DatabaseName = current database (meaning, skip all checks for this specific database)

**Comment by BlitzErik** [comment]
@dallyhorton haven't heard back from you in a while on this, so closing it out. If you wanna work on it again in the future, feel free to reopen or start a new issue. Thanks!
