### ISSUE TITLE
sp_Blitz - CheckID 55 "Database Owner <> SA" - Add a new parameter for the database owner

### ISSUE THREAD

**Issue by hamidmira** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1762]
Feature request : 
sp_Blitz - Version: 6.9   - Version date  : 20180901

For CheckID 55 "Database Owner <> SA", I suggest to make the database owner configurable.
Indeed, there are many SQL environments where the database owner is not necessarily 'SA', and this is not considered an anomaly.
For example, I suggest adding a new parameter named @UsualDBOwner to the sp_Blitz procedure

`@UsualDBOwner sysname = SUSER_SNAME(0x01);`

and modify CheckID 55 "Database Owner <> SA" as follows:
```
INSERT  INTO #BlitzResults
(....)
SELECT  55 AS CheckID ,
	[name] AS DatabaseName ,
	230 AS Priority ,
	'Security' AS FindingsGroup ,
	'Database Owner <> ' + @UsualDBOwner AS Finding,
	'https://BrentOzar.com/go/owndb' AS URL ,
	( 'Database name: ' + [name] + '   '
	  + 'Owner name: ' + SUSER_SNAME(owner_sid) ) AS Details
FROM    sys.databases
WHERE   SUSER_SNAME(owner_sid) <> @UsualDBOwner 
		AND name NOT IN ( SELECT DISTINCT  DatabaseName
						  FROM    #SkipChecks
						  WHERE CheckID IS NULL OR CheckID = 55);
```
Thank you.

**Comment by BrentOzar** [comment]
Oh interesting! Sure, if that's important to you, that'd be a code contribution that would work out for the community. Here's the contributing guide on how to get started:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

If you change your mind and don't want to code it, no problem - just let us know and we'll close the issue.

**Comment by hamidmira** [comment]
I'm not yet comfortable with GitHub operation! I have to take the step one day. 
For the time being, I would have preferred you to integrate this feature. 
PS : I would look more closely at the link you indicated 
Thank you.

**Comment by BrentOzar** [comment]
OK, cool. I'll go ahead and close it.

I understand that you'd like us to do the work, but open source doesn't mean free consulting. ;-)

**Comment by jadarnel27** [comment]
Hey, I can make this change, if you don't mind re-opening and assigning it to me.

**Comment by BlitzErik** [comment]
@jadarnel27 it's reopened, but I can't assign it to you for some reason (again).

**Comment by jadarnel27** [comment]
@BlitzErik have you tried turning GitHub off and on again?

**Comment by BlitzErik** [comment]
I'm just waiting for the next time a Windows update hits it.

**Comment by hamidmira** [comment]
@jadarnel27
Thank you for proposing to make the changes.
This is what I had planned. But you can arrange it differently.
PS : The controls of the owner of the "system databases" remain unchanged
```
ALTER PROCEDURE [dbo].[sp_Blitz]
...
	@UsualDBOwner sysname = NULL ,
...
AS 
...

...

IF @UsualDBOwner IS NULL
	SET @UsualDBOwner = SUSER_SNAME(0x01);

INSERT  INTO #BlitzResults
		( CheckID ,
		  DatabaseName ,
		  Priority ,
		  FindingsGroup ,
		  Finding ,
		  URL ,
		  Details
		)
SELECT 55 AS CheckID ,
		[name] AS DatabaseName ,
		230 AS Priority ,
		'Security' AS FindingsGroup ,
		'Database Owner <> ' + @UsualDBOwner AS Finding , 
		'https://BrentOzar.com/go/owndb' AS URL ,
		( 'Database name: ' + [name] + '   '
		  + 'Owner name: ' + SUSER_SNAME(owner_sid) ) AS Details
FROM    sys.databases
WHERE (     (  ( SUSER_SNAME(owner_sid) <> SUSER_SNAME(0x01) ) AND ( name IN (N'master', N'model', N'msdb', N'tempdb') ) )                           
		OR  (  ( SUSER_SNAME(owner_sid) <> @UsualDBOwner) AND ( name NOT IN (N'master', N'model', N'msdb', N'tempdb') ) ) 
	  )                                                                                                                                             
AND name NOT IN ( SELECT DISTINCT DatabaseName
				  FROM    #SkipChecks
				  WHERE CheckID IS NULL OR CheckID = 55);

```

A+

**Comment by BlitzErik** [comment]
@jadarnel27 were you still going to work on this one? Doing some issue cleanup.

**Comment by jadarnel27** [comment]
@BlitzErik yep, and thanks for the reminder!  I'll get it in today or tomorrow so it can hopefully make the next release.
