### ISSUE TITLE
BlitzIndex: Select Op Stats columns when Mode=2

### ISSUE THREAD

**Issue by arampendley** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1769]
**Do you want to request a *feature* or report a *bug*?**
Feature. I am saving BlitzIndex to a table, but the table is missing some index usage counters.

**What is the current behavior?**
Op Stats are not selected when Mode=2

**What is the expected behavior?**
Select
total_singleton_lookup_count as [Singleton Lookups],
total_range_scan_count as [Range Scans],
total_leaf_update_count as [Leaf Updates],
total_leaf_delete_count as [Leaf Deletes],
when Mode=2. 
Also persist these columns to @OutputTableName.

**Comment by BlitzErik** [comment]
@arampendley were you going to work on this one?

**Comment by BlitzErik** [comment]
Ah, great! Make sure to read the [contributing](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md) doc. You don't need any special privileges -- you're on the right track. Have a look at [this blog post for some instructions](https://www.brentozar.com/archive/2018/01/peoples-githubs-fork-clone-pull/).
