### ISSUE TITLE
sp_Blitz - check looking for statistics with no histogram contents enhancement: exclude CCI stats and add per partition resample

### ISSUE THREAD

**Issue by baleng** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1770]
**Do you want to request a *feature* or report a *bug*?**
i guess this is a bug

hi master Brent! .i'm so happy to be here! 
as posted in your website (a comment) for https://www.brentozar.com/archive/2018/09/finding-fixing-statistics-without-histograms/ (closed pull request #1757  )

the query should exclude the CCI on a table (i use "where stat_id > 1 " to exclude them ) 
it could be better to have a single statement for each stat with an issue instead of resampling every stats (maybe only a stat has a problem)
(next step it could be nice to check if the stat is partitioned and resampling only the partitions.)

you are my best teacher!i'm proud to be here (sorry if this is not an orthodox pull request)
ciao!
 

**Do you want to request a *feature* or report a *bug*?**
If you're reporting a bug, include the version number of the script you're using. If it's not the current version, upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build.

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

**What is the expected behavior?**

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

**Comment by BlitzErik** [comment]
We're going to yank this check, it's kind of a hot mess. Thanks!
