### ISSUE TITLE
sp_blitz - false positives for statistics without histograms

### ISSUE THREAD

**Issue by kevriley** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1771]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Not sure which check in sp_blitz this is in as I was prompted to post here from the blog: https://www.brentozar.com/archive/2018/09/finding-fixing-statistics-without-histograms

The query is returning some false positives for me – when a column only has NULL values for every row DBCC SHOW_STATISTICS returns a one row histogram, with RANGE_HI_KEY = NULL and EQ_ROWS= total number of rows in the table.
But sys.dm_db_stats_histogram returns nothing.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
create a table with one column having only null values
Add some data and query the table to auto generate statistics

execute DBCC SHOW_STATISTICS and see that there is a one-row histogram output

query sys.dm_db_stats_histogram for the same and get no results

**What is the expected behavior?**
This table\column should not show up in the results

**Comment by BlitzErik** [comment]
We're going to yank this check, it's kind of a hot mess. Thanks!
