### ISSUE TITLE
The [XXX] database file XXX_log has a max file size set to 2048MB. If it runs out of space, the database will stop working even though there may be drive space available.

### ISSUE THREAD

**Issue by sqlenders** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1775]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
The [XXX] database file XXX_log has a max file size set to 2048MB. If it runs out of space, the database will stop working even though there may be drive space available.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
Just set a database log to  fixed size and in read only mode. 

**What is the expected behavior?**
This message should *not* appear for read only databases

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All versions of SQL/OS and the kit.

**Comment by BrentOzar** [comment]
Sure, makes sense! To contribute the fix, you can grab the contributing guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

If you have any questions, holler, or check in with us in Slack. Thanks for reporting it!

**Comment by BrentOzar** [comment]
I went ahead and coded it this morning because I was in sp_Blitz for other stuff. Closing - thanks again for the bug report!
