### ISSUE TITLE
sp_BlitzCashe throw divide by zero error.

### ISSUE THREAD

**Issue by githubsqltoolsse** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1777]
VersionDate = 20180901

When running sp_BlitzCache I got this error messages:
Msg 8134, Level 16, State 1, Procedure sp_BlitzCache, Line 3972 [Batch Start Line 2]
Divide by zero error encountered.

It is thrown three times. I believe it has to do with MaxCompileMemory.

I got this error on some of my servers but not others. I have not enough information but think it might be due to some sql versions. I get the error every time on when of the servers running three instances of 2012. Version from one of them is: 11.0.6020.0

OS: is windows server 2012 Datacenter version. 6.2.9200.0

**Comment by BlitzErik** [comment]
Closing as a duplicate #1747
