### ISSUE TITLE
sp_blitz and Cluster Shared Volumes

### ISSUE THREAD

**Issue by ekholve** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1783]
**Do you want to request a *feature* or report a *bug*?**
If you're reporting a bug, include the version number of the script you're using. If it's not the current version, upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build.
sp_Blitz Sep  1 2018 12:00AM

**What is the current behavior?**
Just run sp_blitz against failover clustered SQL instance running on cluster shared volumes and noticed that sp_blitz complains about running all databases, logs and backups on c:\ drive.
 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

**What is the expected behavior?**
sp_blitz should not report this as an issue as long as cluster shared volumes are used?

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2017 Standard Edition, Windows Server 2016 Standard Edition.

**Comment by BlitzErik** [comment]
Okay, cool! We don't use those, so you'd have to figure out how to detect and ignore this condition. Are you game for doing that?

**Comment by ekholve** [comment]
Thanks for the quick response! I am afraid that I am not able to contribute in any other way but testing the code. :(
Anyway, I just did a bit of a research on this matter and found that at least the existence of CSV clustering can be checked fairly easily like this:
SELECT * FROM sys.dm_io_cluster_valid_path_names; 
https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-io-cluster-valid-path-names-transact-sql?view=sql-server-2017

**Comment by BlitzErik** [comment]
Ah, alright. I'll leave this issue open for a bit to see if anyone else picks it up, but it's likely not something that we'd work on, because none of us are set up to write the code easily. If no one takes it in the next month, I'll close it out.

Thanks!

**Comment by ekholve** [comment]
Sounds like a plan. Thank you!

**Comment by Adedba** [comment]
I have tried to replicate this issue on our SQL 2012 instance but unfortunately I cannot replicate it there, I know the issue mentions SQL 2016 and 2017 but thought it was worth a try. Looking at the code it appears to do a LEFT 1 on physical_name in sys.master_files and when this is equal to 'C' it will see this as the C drive, does the name of your volume/s start with the letter 'C'? A similar check is conducted against
msdb.dbo.backupmediafamily where the leftmost 3 chars in the backup file name = the left 3 chars of the database file name.  It may be worth running this slightly revised snippet of code from sp_Blitz to see for yourself if you get results as this would indicate that sys_master files and backupmediafamily both contain paths that begin with the same first 3 chars. 


```
SELECT CAST(COUNT(1) AS VARCHAR(50)) + ' backups done on drive '+UPPER(LEFT(bmf.physical_device_name, 3))
FROM    msdb.dbo.backupmediafamily AS bmf
INNER JOIN msdb.dbo.backupset AS bs ON bmf.media_set_id = bs.media_set_id
								  AND bs.backup_start_date >= ( DATEADD(dd,
								  -14, GETDATE()) )
		/* Filter out databases that were recently restored: */
		LEFT OUTER JOIN msdb.dbo.restorehistory rh ON bs.database_name = rh.destination_database_name AND rh.restore_date > DATEADD(dd, -14, GETDATE())
WHERE   UPPER(LEFT(bmf.physical_device_name, 3)) <> 'HTT' AND
        UPPER(LEFT(bmf.physical_device_name COLLATE SQL_Latin1_General_CP1_CI_AS, 3)) IN (
		SELECT DISTINCT
				UPPER(LEFT(mf.physical_name COLLATE SQL_Latin1_General_CP1_CI_AS, 3))
		FROM    sys.master_files AS mf )
		AND rh.destination_database_name IS NULL
GROUP BY UPPER(LEFT(bmf.physical_device_name, 3));
```

Its an interesting one, I know its possible to mount a local drive to an NTFS folder on the C:\ drive in which case it would show as C:\'Mounted Folder name' in sys.master_files not sure if the same is possible for a clustered drive though.

**Comment by ekholve** [comment]
Adedba. Thanks for your contribution here. Unfortunately it seems that you are not running your instance on CSVFS (cluster shared volume file system). When you enable that in your Failover Cluster, it creates folder structure C:\ClusterStorage\ where you mount your clustered volumes. Each LUN is then mounted on separate folders such as SQLSYSTEM, SQLDATA, SQLLOG etc. according to your plan/policy.
This is clustering specific issue and has nothing to do with SQL Server version other than that version 2014 was actually the first release to support this kind of storage design.
I believe this could be reproduced using single instance and normal volume mount points mounted under manually created C:\ClusterStorage\ folder structure.
Anyways, thanks again for investigating this matter. :)

**Comment by ekholve** [comment]
Anyways, your finding in the code seems to be correct place to adjust. 
So basically if you could check if the folder under the c:\folder contains mounted volume then the this matter is not reported?

**Comment by BlitzErik** [comment]
I think we've given this a fair shot to get picked up by someone. Gonna close this out for now. If you decide you want to work on it, feel free to open a new issue.
