### ISSUE TITLE
Duplicate checkID sp_Blitz

### ISSUE THREAD

**Issue by tellwade** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1785]
Possible bug - Version 6.9
CheckID 216 is duplicated in sp_Blitz

First check on this ID is for SQL 2017 missing features (if 2017 but not CU3)
Then later on same CheckID (216) is used to check for a recent server restart

**Comment by BrentOzar** [comment]
Great catch! Thanks for the heads up. Changed the recent restart check to be id 221.
