### ISSUE TITLE
sp_blitz new feature for database mail

### ISSUE THREAD

**Issue by athurgar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1787]
I would like to see sp_blitz check to see if database mail is enabled and started. See attached T-SQL as sample code
[Check Database Mail.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/2445507/Check.Database.Mail.txt)

**Comment by BrentOzar** [comment]
Sure, that sounds good. Here's how to get started contributing a new check:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

**Comment by BrentOzar** [comment]
@athurgar did you want to contribute the code? If not, no worries - just let us know and we'll close the issue.

**Comment by athurgar** [comment]
Hi Brent,

I am currently recovering from a bone marrow transplant for a blood cancer.
I will not be able to look at this item until after this time.

Thanks,

Adam

Adam Thurgar
SQL Server Support
Mobile: +61 (0)419 290 524
http://www.sqlserversupport.com
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
This message (including any attachments) is confidential and may be privileged. If you have received it by mistake please notify the sender by return e-mail and delete this message from your system. Any unauthorised use or dissemination of this message in whole or in part is strictly prohibited. Please note that e-mails are susceptible to change.
AiT Consultancy Group Pty Ltd (including its group companies) shall not be liable for the improper or incomplete transmission of the information contained in this communication nor for any delay in its receipt or damage to your system. AiT Consultancy Group Pty Ltd (or its group companies) does not guarantee that the integrity of this communication has been maintained nor that this communication is free of viruses, interceptions or interference.
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by BrentOzar** [comment]
Oh wow! In that case, definitely focus on getting better. Sorry to hear that! I'll close the issue. Best wishes on the recovery!
