### ISSUE TITLE
sp_blitz enhancement for TCP port

### ISSUE THREAD

**Issue by athurgar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1788]
Previously I had raised this and it was closed but would like to gauge if there is any change in interest to this being added.
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/161

See attached for sample t-sql code to get this information.

[SQL TCP Port Reg Key.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/2445525/SQL.TCP.Port.Reg.Key.txt)

**Comment by BrentOzar** [comment]
We're steering clear of security checks for now. Other folks or repos in the community are welcome to get started building a security audit stored procedure, but we're not going to do that here. I think there's a great space in the community for a security auditing tool, but it just isn't what sp_Blitz is. Thanks for understanding.
