### ISSUE TITLE
sp_BlitzCache Invalid length parameter passed to the LEFT or SUBSTRING function

### ISSUE THREAD

**Issue by imyourdba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1800]
BUG
Version 6.10 Date 20181001 (Even deleted SP's and Tables and re-ran setup)

**What is the current behavior?**
When running the following:
EXEC sp_BlitzFirst 
  @OutputDatabaseName = 'SQLAdmin', 
  @OutputSchemaName = 'dbo', 
  @OutputTableName = 'BlitzFirst',
  @OutputTableNameFileStats = 'BlitzFirst_FileStats',
  @OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
  @OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
  @OutputTableNameBlitzCache = 'BlitzCache',
  @OutputTableRetentionDays = 14;

**It gets to here and then provides the following error:**
Getting information about implicit conversions and stored proc parameters
Msg 537, Level 16, State 3, Procedure sp_BlitzCache, Line 2719 [Batch Start Line 0]
Invalid length parameter passed to the LEFT or SUBSTRING function.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2017 CU11 on Windows 2016

**If I just run sp_BlitzCache it works fine.** 
EXEC sp_blitzcache @OutputTableName = 'BlitzCache'

**Comment by BrentOzar** [comment]
Thanks! It's been reported before - check this out:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/1754

The difference between running it via sp_BlitzFirst versus running it with sp_BlitzCache is that sp_BlitzFirst can run sp_BlitzCache with different sort orders depending on what your server's bottleneck is at the moment. Try running sp_BlitzCache @SortOrder = 'all' and see if you can repro the error that way. From there, you can troubleshoot more deeply to see which query is causing the problem on your instance, and that'll help you figure out what we need to tweak.

Thanks for your help!

**Comment by imyourdba** [comment]
Looks like it may have been some encrypted objects in a database, but it's not needed any longer so I detached it and reran this...everything seemed to work fine after that.  Thanks for the response.
