### ISSUE TITLE
Dashboards for Mobile View in Power BI template + training files

### ISSUE THREAD

**Issue by hfleitas** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1809]
**Do you want to request a *feature* or report a *bug*?**
The 💣 feature!

**What is the current behavior?**
The template and training file are missing mobile views to showcase the portability of the FRK visuals on a phone or tablet. 

I can work on this item. Lmk who to send an updated .pbix or .pbt.

**What is the expected behavior?**
See the 💣 screenshots below... 

**1. Overview:**
![img_1348](https://user-images.githubusercontent.com/4984616/47243380-cdd06100-d3bf-11e8-8072-85bd32629bb3.png) ![img_1349](https://user-images.githubusercontent.com/4984616/47243382-cdd06100-d3bf-11e8-83ca-40a92f3a1518.png) ![img_1350](https://user-images.githubusercontent.com/4984616/47243384-cdd06100-d3bf-11e8-8faa-2e40ff7fd748.png) ![img_1351](https://user-images.githubusercontent.com/4984616/47243385-ce68f780-d3bf-11e8-9f46-01a8b369b9e3.png) ![img_1352](https://user-images.githubusercontent.com/4984616/47243386-ce68f780-d3bf-11e8-908c-ec564e73b820.png)

**2. Query Details:**
![img_1354](https://user-images.githubusercontent.com/4984616/47243348-babd9100-d3bf-11e8-9862-d89f77cb2869.png) ![img_1353](https://user-images.githubusercontent.com/4984616/47243349-bb562780-d3bf-11e8-876a-7fc7b5c97cf8.png)

**3. File Speeds:**
![img_1355](https://user-images.githubusercontent.com/4984616/47243333-b002fc00-d3bf-11e8-819c-de4c46620982.png) ![img_1356](https://user-images.githubusercontent.com/4984616/47243334-b002fc00-d3bf-11e8-9cb6-d52e29d866cb.png) ![img_1357](https://user-images.githubusercontent.com/4984616/47243335-b002fc00-d3bf-11e8-97a8-8fe9c367bb97.png)

**5. File Sizes:**
![img_1358](https://user-images.githubusercontent.com/4984616/47243316-a4173a00-d3bf-11e8-8911-d26b1350ed9e.png) ![img_1359](https://user-images.githubusercontent.com/4984616/47243318-a4173a00-d3bf-11e8-89a7-5d892c68c8de.png) ![img_1360](https://user-images.githubusercontent.com/4984616/47243319-a4afd080-d3bf-11e8-9470-632fe82695e6.png)

**6. Perfmon:**
![img_1361](https://user-images.githubusercontent.com/4984616/47243297-9366c400-d3bf-11e8-8550-f82d046ee5b5.png) ![img_1362](https://user-images.githubusercontent.com/4984616/47243298-9366c400-d3bf-11e8-93c7-9929b54c6bd0.png) ![img_1363](https://user-images.githubusercontent.com/4984616/47243299-9366c400-d3bf-11e8-865f-bdac28016bd3.png)

**7. Wait Stats Anomalies:**
![img_1364](https://user-images.githubusercontent.com/4984616/47243281-88139880-d3bf-11e8-9a78-f0fea222457b.png) ![img_1365](https://user-images.githubusercontent.com/4984616/47243282-88139880-d3bf-11e8-9cec-49ed77caca6a.png) ![img_1366](https://user-images.githubusercontent.com/4984616/47243283-88139880-d3bf-11e8-9d0e-13be9529040a.png)

**8. Perfmon Anomalies:**
![img_1367](https://user-images.githubusercontent.com/4984616/47243195-4a167480-d3bf-11e8-8f98-f99dfc92cca2.png) ![img_1368](https://user-images.githubusercontent.com/4984616/47243196-4a167480-d3bf-11e8-92c1-885e00f2e371.png) ![img_1369](https://user-images.githubusercontent.com/4984616/47243197-4a167480-d3bf-11e8-9475-482ae44c72c6.png) ![img_1370](https://user-images.githubusercontent.com/4984616/47243198-4a167480-d3bf-11e8-80c1-2a401e1bb783.png)

**9. Instructions:**
![img_1371](https://user-images.githubusercontent.com/4984616/47243171-3f5bdf80-d3bf-11e8-8759-8346cdb6c23b.png)

Thx,
Hiram

**Comment by BrentOzar** [comment]
Ooo, looks awesome! Sure, do a pull request as described here:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

Or if you don't want to hassle with Github, email it to us at help@brentozar.com. Thanks!
