### ISSUE TITLE
Add sp_ineachdb to the frk

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1822]
WE HAVE LIFTOFF

**Comment by darshanrampatel** [comment]
Not sure if you will get the comment I left on #1821 but there is a typo in the code:

![image](https://user-images.githubusercontent.com/14162899/47297745-eafa6f00-d60d-11e8-83eb-6d29a18ef0b0.png)

**Comment by BlitzErik** [comment]
@darshanrampatel can you open a new issue for that?

Thanks!

**Comment by darshanrampatel** [comment]
@BlitzErik, sure #1824

I will create a PR to fix it.
