### ISSUE TITLE
sp_Blitz: Finding 'TraceFlag On' URL invalid

### ISSUE THREAD

**Issue by Hydrogen76** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1831]
The sp_Blitz output provides an invalid URL for the 'TraceFlag On' finding (CheckID 74).  The URL in the output points to a HTTP 404 (Not Found) returning page.  

https://www.BrentOzar.com/go/traceflags/

sp_Blitz version: 6.10

**Comment by McA-the-dba** [comment]
It appears that the correct URL is https://www.brentozar.com/blitz/trace-flags-enabled-globally/ - you can use that for reference until the sp is updated.

**Comment by BrentOzar** [comment]
Sorry about that! Fixed.
