### ISSUE TITLE
sp_BlitzQueryStore pull back by total and average

### ISSUE THREAD

**Issue by tboggiano** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1832]
**Feature request**
Currently the procedure returns the top x queries by max metrics. It would be useful to have an option to return it by max, total, or average metrics.

**Comment by BlitzErik** [comment]
Right now, we do everything by averages. If you ctrl+f for `Gathering intervals`, you'll hit the section where we figure out which time periods to focus on. 

Ditto a ctrl + f for `Gathering longest duration plans` -- the query there follows the same pattern as all the others to find "worsts" -- we order everything by `avg_metric DESC`.

The way query store data is, doing it by totals would be kind of tough, but I could do MAXes easily.

If you're cool with that, I'll get it into the next release. Lemme know!

**Comment by tboggiano** [comment]
Pulling back MAXes would be cool as well.
