### ISSUE TITLE
Page not found error from links inside sp_BlitzIndex

### ISSUE THREAD

**Issue by TurnerBurn** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1833]
I'm Running the latest version (Downloaded yesterday, 10/29) of sp_BlitzIndex and some of the URLs listed for certain index issues are pulling up a 'Page Not Found' error.

Here are the ones so far : 
https://www.brentozar.com/go/IndexHoarder
https://www.brentozar.com/go/AbnormalPsychology
https://www.brentozar.com/go/Workaholics
https://www.brentozar.com/go/Indexaphobia
https://www.brentozar.com/go/AggressiveIndexes
https://www.brentozar.com/go/IndexFeatures

**Comment by jerryhung** [comment]
I'll just also add here as well
sp_BlitzIndex
http://BrentOzar.com/go/AggressiveIndexes

I found it by Google
https://www.brentozar.com/blitzindex/sp_blitzindex-aggressive-indexes/

**Comment by BrentOzar** [comment]
Thanks for the bug report! Fixed.
