### ISSUE TITLE
URL for finding "Agent Jobs Starting Simultaneously" is page not found

### ISSUE THREAD

**Issue by daviespaul** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1845]
Blitz version: sp_Blitz Oct  1 2018 12:00AM

Finding "Agent Jobs Starting Simultaneously" has help URL of "https://BrentOzar.com/go/busyagent/" which points to a 404 due to the trailing forward-slash - which *should* work anyway, but doesn't

**Comment by BrentOzar** [comment]
Sorry about that, and thanks for the report! Fixed.
