### ISSUE TITLE
sp_BlitzLock - Treating triggers like Stored Procs

### ISSUE THREAD

**Issue by RichBenner** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1851]
**Do you want to request a *feature* or report a *bug*?**
Possibly a bug?

**What is the current behavior?**
I'm running BlitzLock on a client site and it looks like it treats triggers the same way as SP's for check_id 7. 

check_id | database_name | object_name | finding_group | finding
------------ | ------------- | ------------- | ------------- | -------------
7| Database           | Database.dbo.entityTrigger1 | More Info - Query | EXEC sp_BlitzCache @StoredProcName = 'entityTrigger1';

the BlitzCache query returns nothing because this query isn't a SP, it's a trigger.

I've looked through BlitzCache and it doesn't look like it can currently take a trigger as a parameter (e.g. @TriggerName) so modifications might need to be made in there too if this modification was to be made.

This is just a thought exercise at the moment but i'd be happy to look at coding this if the change was something that wants to be done.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
This is on SQL Server 2014 (12.0.5207.00) but it's not going to be confined to a particular version.

**Comment by BrentOzar** [comment]
@avdbosch for support questions, you're best off asking a question in Slack. Here's how to get started: https://www.brentozar.com/support/

The query hash is in the second result set of sp_BlitzLock, down at the bottom half of your screen. Keep reading down.

**Comment by BrentOzar** [comment]
@RichBenner sure, if you want to code that, that sounds interesting - give 'er a shot. Thanks sir!
