### ISSUE TITLE
Move solution to its own schema

### ISSUE THREAD

**Issue by jeffchulg** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1852]
**Do you want to request a *feature* or report a *bug*?**
If you're reporting a bug, include the version number of the script you're using. If it's not the current version, upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build.

Move all objects related to first responder kit to its own schema, so that any resource is isolated from any other tool.

**What is the current behavior?**

Every objects go to [dbo] schema.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

**What is the expected behavior?**
/

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
/

**Comment by BrentOzar** [comment]
What's the problem we're trying to solve?

I want to make sure the problem is severe enough that it warrants breaking a lot of peoples' scripts and blog posts which already call out dbo.

**Comment by jeffchulg** [comment]
There is no actual problem. 

My point is that it could be cool to avoid object name collisions between eventual projects we put inside our "dbatools" database.

The same kind of discussion has been opened by Ola Hallengren (https://github.com/olahallengren/sql-server-maintenance-solution/issues/91)

**Comment by BrentOzar** [comment]
OK, gotcha. If there's not a problem, we're going to avoid changing it. If we changed it, it would *immediately* cause documentation problems for people who've already put a lot of work into this. Thanks though.
