### ISSUE TITLE
sp_Blitz: DBCC command check should skip monitoring tools, additional exclusion

### ISSUE THREAD

**Issue by dbaWJW** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1853]
New item pertaining to #1041 

Please consider an additional exclusion of application name "SQL Monitor - Monitoring", which is RedGate SQL Monitor, in the sp_Blitz section pertaining to Overall count of DBCC events. 

Would need this criteria added, as I see it, based on my install:

AND d.application_name NOT LIKE '%SQL Monitor - Monitoring%'

**Comment by BlitzErik** [comment]
Thanks, will get this in the next release.
