### ISSUE TITLE
sp_databaserestore: Improve @MoveFiles behaviour

### ISSUE THREAD

**Issue by ShawnCrocker** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1854]
**Do you want to request a *feature* or report a *bug*?**
Request

**What is the current behavior?**
Personally, I almost always have to set @MoveFiles = 1

**What is the expected behavior?**

***Option 1***
Change @MoveFiles to default NULL
..
If @MoveFiles IS NOT NULL, just use it as-is
If @RestoreDatabaseName= @DBName and @MoveFiles IS NULL, set @MoveFiles = 0
If @RestoreDatabaseName<> @DBName, and @MoveFiles IS NULL, set @MoveFiles = 1

***Option 2***
Alternatively, it could be safe to default it to 1
- Same database, same server means no effect
- Same database, new server means probably different path
- Different database, same server means probably different file names
- Different database, new server means probably different file names and different path

Thoughts please...

**Comment by BrentOzar** [comment]
Oh, that's interesting - yeah, I agree that option 1 makes sense.

**Comment by ShawnCrocker** [comment]
I prefer option 2 (I made that upü as I wrote the request)

Any tie breaking opinions? Otherwise I'll go with what the boss says

**Comment by BrentOzar** [comment]
Oh sure, I’m okay with #2 too. They’re both good.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws
