### ISSUE TITLE
sp_Blitz: capitalize No failsafe operator warning

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1874]
**Version of the script**
(Current)

**What is the current behavior?**
No failsafe operator warning is lower case. I would type more, but I'm in front of an audience.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

**Comment by BlitzErik** [comment]
Brent will hug the first attendee who fixes the issue before his session is over.

**Comment by BrentOzar** [comment]
HAHAHA

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by jadarnel27** [comment]
*Brent hugs himself*
