### ISSUE TITLE
Collation issue in sp_BlitzLock

### ISSUE THREAD

**Issue by xHedra** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1876]
**Version of the script**
1.12 - 20181201

**What is the current behavior?**
The stp does not complete and returns the following error message

Msg 451, Level 16, State 1, Procedure sp_BlitzLock, Line 798
Cannot resolve collation conflict between "SQL_Latin1_General_CP1_CI_AI" and "SQL_Latin1_General_CP1_CI_AS" in UNION ALL operator occurring in SELECT statement column 8.
Msg 451, Level 16, State 1, Procedure sp_BlitzLock, Line 798
Cannot resolve collation conflict between "SQL_Latin1_General_CP1_CI_AI" and "SQL_Latin1_General_CP1_CI_AS" in UNION ALL operator occurring in SELECT statement column 9.

**If the current behavior is a bug, please provide the steps to reproduce.**

I installed the full responder kit and I have been able to run every one of the stp included EXCEPT for sp_BlitzLock which returns 2 collation errors.

**What is the expected behavior?**

Not to crash.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

We are currently on SQL Server 2012 version 11.0.5678.0 and the server collation is SQL_Latin1_General_CP1_CI_AS 

IMPORTANT*** Our main database, the one that we are experiencing locks on, is in collation SQL_Latin1_General_CP1_CI_AI 

This is because we are in a Canadian French location and need to be able to compare and search ignoring accents...

Montreal needs to be equal to Montréal

**Comment by BlitzErik** [comment]
Thanks for submitting this. Were you planning on working on a fix?
