### ISSUE TITLE
Unable to apply scripts on AzureSQL instance

### ISSUE THREAD

**Issue by davidflett** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1878]
I have been having issues applying the sp_BlitzFirst script (as of the current dev branch I believe) on an Azure SQL database instance.

With a bit of investigation it seems like the blocks of code which check for the azure instance, do not give the expected results, eg:

`SERVERPROPERTY('Edition') = 'SQL Azure'` & `SERVERPROPERTY('Edition') <> 'SQL Azure'`

For example, if I run `SELECT SERVERPROPERTY('Edition')` I get `SQL Azure`.

If I run `select case WHEN SERVERPROPERTY('Edition') = 'SQL Azure' THEN 1 ELSE 0 END` I get `0` whereas I would expect to get `1`.

I have noticed that the return type of SERVERPROPERTY is `sql_variant`, so if I instead try `select case WHEN cast(SERVERPROPERTY('Edition') as nvarchar) = 'SQL Azure' THEN 1 ELSE 0 END` I get `1` as expected.

I have wondered if this could be related to the Azure instance being located in the UK South data centre, do you get the same results elsewhere?

**Comment by davidflett** [comment]
I found I have access to another machine which I believe is hosted in "North Europe".

It gives the same result for both queries.

Just to be complete, these are the queries I am running:

```
SELECT SERVERPROPERTY('Edition')

select case WHEN SERVERPROPERTY('Edition') = 'SQL Azure' THEN 1 ELSE 0 END
select case WHEN SERVERPROPERTY('Edition') <> 'SQL Azure' THEN 1 ELSE 0 END

select case WHEN cast(SERVERPROPERTY('Edition') as nvarchar) = 'SQL Azure' THEN 1 ELSE 0 END
select case WHEN cast(SERVERPROPERTY('Edition') as nvarchar) <> 'SQL Azure' THEN 1 ELSE 0 END 
```

**Comment by BlitzErik** [comment]
@davidflett can you check the collations?

**Comment by davidflett** [comment]
The master database for the UK South one is `SQL_Latin1_General_CP1_CI_AS`.

I'm not quite sure what you mean by user database, do you mean the database I'm trying to get this to run on?

**Comment by BlitzErik** [comment]
Yep, that's the one.

**Comment by davidflett** [comment]
Ah, well that's also `SQL_Latin1_General_CP1_CI_AS` as that's what I was running it on before.

**Comment by BlitzErik** [comment]
This is weird for three reasons:

1. I just did a round of testing installing the scripts in Azure SQLDB, and didn't run into issues
2. When I've run into issues with property functions, it's been because of conflicting database collations
3. I'm on our Azure instance now, and able to install it normally:

![image](https://user-images.githubusercontent.com/11590415/49605868-be04e000-f95f-11e8-9c07-8652ddd173ea.png)

Can you do me a favor and paste the exact error message you get when you try to run the script?

**Comment by davidflett** [comment]
This looks a little specific to my specific instance.

This is the user database:

![image](https://user-images.githubusercontent.com/2144239/49612777-a77d7980-f99d-11e8-8eee-e37e6c5374ad.png)

However I noticed that in the database properties, there is a different collation:

![image](https://user-images.githubusercontent.com/2144239/49612837-c976fc00-f99d-11e8-9073-afe6b8a65321.png)

This particular database was a migration via bacpac from a SQL2012 database, which likely was installed with the UK defaults.

When I run the queries on the master database on this same server, or a fresh test database which has the same collation as master, then it all works as expected.

**Comment by BrentOzar** [comment]
Gotcha. You’re confusing a couple of things here: server collation and database collation. Server collation is the collation for the system databases. When you query for a system property - even in a user database - you’re seeing the system collation.

Generally speaking, when you set up a server, you want to use the same collation in your system databases that you use in your user databases. When they don’t match, you can run into some problems - and this is one of ‘em.

If you want to get this to work with your configuration, you’re welcome to pop open the code and give it a shot, but this wouldn’t be something we’d work on ourselves.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by BlitzErik** [comment]
Gonna close this one out for now since we haven't heard back from you. Feel free to open a new issue and reference this one if you want to work on it.
