### ISSUE TITLE
sp_blitzindex warning about a heap with a nonclustered PK that might not be a heap

### ISSUE THREAD

**Issue by imyourdba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1883]
**Version of the script**
6.12
20181201

**What is the current behavior?**
Priority 100 - Self Loathing Indexes: Heap with a Nonclustered Primary Key
This is showing "Heap with a NC PK", but the table has a clustered index, so it isn't a Heap.  Should the finding say something different or are we just lumping this in?

**If the current behavior is a bug, please provide the steps to reproduce.**
To reproduce, you can create a table like this and then run sp_blitzindex:
CREATE TABLE [dbo].[CustomerChangeLog](
	[CompanyID] [int] NOT NULL,
	[CustomerID] [int] NOT NULL,
	[ModifiedDate] [datetime] NOT NULL,
	[ModifiedBy] [nvarchar](100) NOT NULL,
	[Detail] [nvarchar](4000) NOT NULL,
	[CustomerChangeLogID] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_CustomerChangeLog] PRIMARY KEY NONCLUSTERED 
(
	[CustomerChangeLogID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE CLUSTERED INDEX [IX_CustomerChangeLog] ON [dbo].[CustomerChangeLog]
(
	[CompanyID] ASC,
	[CustomerID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_CompIDModDt] ON [dbo].[CustomerChangeLog]
(
	[CompanyID] ASC,
	[ModifiedDate] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
GO

**What is the expected behavior?**
I would expect the finding to say something different, like "Primary Key Is Not Clustered Index" or something like that.  Just so there is no confusion about the table being a Heap and needing a clustered index added.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
This is on an Azure SQL database.
Microsoft SQL Azure (RTM) - 12.0.2000.8

**Comment by BrentOzar** [comment]
I'm not seeing that. Your script doesn't insert any rows in the table, so it won't show up in sp_BlitzIndex's output. This one does:

```
CREATE TABLE dbo.HeapsOfSadness (Id1 INT IDENTITY(1,1), Id2 INT, Stuffing CHAR(1000),
CONSTRAINT PK_Id1 PRIMARY KEY NONCLUSTERED ([Id1] ASC));
GO
CREATE CLUSTERED INDEX [CLIX_Id2] ON [dbo].HeapsOfSadness (Id2);
GO
INSERT INTO dbo.HeapsOfSadness (Id2, Stuffing)
  SELECT 1, 'Stuff' /* Short */
  FROM sys.messages;
GO

EXEC sp_BlitzIndex @Mode = 4, @ThresholdMB = 1;
```

But the output doesn't show anything about a heap with a nonclustered primary key:

![screen shot 2018-12-10 at 1 01 01 pm](https://user-images.githubusercontent.com/245462/49761338-abe6b280-fc7b-11e8-9df5-be096882e73b.png)

Can you try to produce a working repro? I looked at the code, and it doesn't appear to work the way you're describing. I think you really do have a heap.

**Comment by imyourdba** [comment]
Here is the output for the row.  The code I provided before was the actual create statements generated from SSMS by right clicking and scripting the create statements for the table and indexes.  I'll see if I can create a new table with the same scripting and reproduce the same output. 

**Priority:** 100
**Finding:** Self Loathing Indexes: Heap with a Nonclustered Primary Key
**Database Name:** {Database}	
**Details:** dbo.CustomerChangeLog.PK_CustomerChangeLog (2) is a HEAP with a Nonclustered Primary Key	
**Definition:** [PK] [1 KEY] CustomerChangeLogID {int 4}	
Secret Columns: [2 INCLUDES] CompanyID {int 4}, CustomerID {int 4} [UNIQUIFIER]	
**Usage:** Reads: 5,391 (5,391 seek) Writes:1,408,949	
Size: 647,063 rows; 23.8MB	
**More Info:** EXEC dbo.sp_BlitzIndex @DatabaseName='{Database}', @SchemaName='dbo', @TableName='CustomerChangeLog';	
**URL:** http://BrentOzar.com/go/SelfLoathing	
**Create TSQL:** ALTER TABLE [dbo].[CustomerChangeLog] ADD CONSTRAINT [PK_CustomerChangeLog] PRIMARY KEY ( [CustomerChangeLogID] ) WITH (FILLFACTOR=100, ONLINE=?, SORT_IN_TEMPDB=?, DATA_COMPRESSION=?);

**Comment by imyourdba** [comment]
Here is a generated script of a new database with a new table built just for the purposes of illustrating the issue.

[sp_BlitzIndex Test Database.zip](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/2665213/sp_BlitzIndex.Test.Database.zip)

**Comment by imyourdba** [comment]
![image](https://user-images.githubusercontent.com/32579014/49766073-c6c81f80-fc99-11e8-8d06-7f9bcf02c776.png)

**Comment by BrentOzar** [comment]
Um...this is a ten thousand line file with sp_BlitzCache in it?

**Comment by BlitzErik** [comment]
It's not flagging all of them incorrectly, just yours, because you have a column called "CustomerID" and it's in the "Secret Columns" column of the output, that you didn't include in the screenshot.

When the code looks for `AND i.secret_columns LIKE '%RID%'`, it finds that row.

**Comment by BlitzErik** [comment]
@BrentOzar  you repro script catches it if you change it a little:

```
CREATE TABLE dbo.HeapsOfSadness (Id1 INT IDENTITY(1,1), CustomeRID INT, Stuffing CHAR(1000),
CONSTRAINT PK_Id1 PRIMARY KEY NONCLUSTERED ([Id1] ASC));
GO
CREATE CLUSTERED INDEX [CLIX_CustomeRID] ON [dbo].HeapsOfSadness (CustomeRID);
GO
INSERT INTO dbo.HeapsOfSadness (CustomeRID, Stuffing)
  SELECT 1, 'Stuff' /* Short */
  FROM sys.messages;
GO

EXEC sp_BlitzIndex @Mode = 4, @ThresholdMB = 1;
```

**Comment by BlitzErik** [comment]
@imyourdba can you confirm the version here works for you?

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/1884/files

**Comment by imyourdba** [comment]
Yes sir, that removed it
