### ISSUE TITLE
sp_BlitzLock - NO_PERFORMANCE_SPOOL

### ISSUE THREAD

**Issue by RichBenner** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1887]
**Version of the script**
current dev script (1.12)

**What is the current behavior?**
syntax error when installing, NO_PERFORMANCE_SPOOL isn't available on my 2012 or earlier boxes (i don't have a 2014 box to test it on). Works fine on 2016<

**If the current behavior is a bug, please provide the steps to reproduce.**
Try to install on an older box, you'll get this error;

Msg 102, Level 15, State 1, Procedure sp_BlitzLock, Line 201 [Batch Start Line 3]
Incorrect syntax near 'NO_PERFORMANCE_SPOOL'.

**What is the expected behavior?**

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Fails on 2012 and earlier, haven't tested on 2014 but works on 2016<

**Comment by BlitzErik** [comment]
This is the dev branch, right?

**Comment by RichBenner** [comment]
yeah, should have made that clearer, sorry

**Comment by BlitzErik** [comment]
You can pull it out if you want, I don't think it's doing a whole lot.

**Comment by RichBenner** [comment]
Thanks for doing that Erik, I was away from my desk last night.
