### ISSUE TITLE
Incorrect control-of-flow code block and help text in sp_foreachdb

### ISSUE THREAD

**Issue by pwsqldba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1893]
Version 2.12, dated 20181201.

When executing the script, SQL Server throws an error when attempting to complete the ALTER PROCEDURE:

-----------
Msg 102, Level 15, State 1, Procedure sp_foreachdb, Line 266 [Batch Start Line 6]
Incorrect syntax near 'END'.
-----------

This is caused by a control-of-flow code block opened with BEGIN on line 44, but not closed with an END on line 90.

Additionally, the current help text has been copied from sp_DatabaseRestore, so incorrectly describes the intended functionality.

The expected behaviour of the script is to create a blank copy of the stored procedure sp_foreachdb if it doesn't exist, then alter the object it to contain the new code.

All versions of SQL Server are affected by this issue.

**Comment by BlitzErik** [comment]
Thanks!
