### ISSUE TITLE
sp_DatabaseRestore: validate @Database against FULL backup file

### ISSUE THREAD

**Issue by ShawnCrocker** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1894]
**Version of the script**
Commit from Issue 1185

**What is the current behavior?**
Imagine one of these calls

EXEC _DBA.dbo.sp_DatabaseRestore
    @Database = 'SomeDB',
    @RestoreDatabaseName = 'SomeDB**Test**'
    @BackupPathFull = '\\blah\SomeDB**Copy**',
    @MoveFiles = 1,
   ...
 or

EXEC _DBA.dbo.sp_DatabaseRestore
    @Database = 'SomeDB',
    @BackupPathFull = '\\blah\SomeDB**Copy**',
   ...

SQL Pattern matching means we can restore SomeDBCopy because it matches SomeDB in filters like
     BackupFile LIKE N'%' + @Database + N'%'
And file moves don't work as expected because of the simple REPLACE

Fixing the LIKE/REPLACE code is possible but we can validate that the full backup files does actually match the @Database parameter.

**If the current behavior is a bug, please provide the steps to reproduce.**
Pick any database naming convention as above

**What is the expected behavior?**
We restore exactly 
**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Tested here on SQL 2012+ 2017 so assum all versions have the same issue

**Comment by BrentOzar** [comment]
Nice job. Thanks, sir!
