### ISSUE TITLE
sp_Blitz - missing info page: https://www.brentozar.com/go/reportservertempdb/

### ISSUE THREAD

**Issue by MisterZeus** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1897]
**Version of the script**
sp_Blitz (TM) v41 as of Jun 18 2015 12:00AM

**What is the current behavior?**
URL goes to 404 page. The URL is from Check 127 in sp_Blitz

**If the current behavior is a bug, please provide the steps to reproduce.**
Go to https://www.brentozar.com/go/reportservertempdb/

**What is the expected behavior?**
A page describing the problem and steps to fix it.

**Comment by BrentOzar** [comment]
Great catch! Sorry about that, and fixed. Brent

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws
