### ISSUE TITLE
sp_Blitz not working on Azure PAAS (Azure SQL Databases)

### ISSUE THREAD

**Issue by GustavoFischer** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1898]
**Version of the script**
Version 7.1 (comes from the future as it says 20190101)

**What is the current behavior?**
Msg 40515, Level 15, State 1, Procedure sp_Blitz, Line 16 [Batch Start Line 3]
Reference to database and/or server name in 'master.sys.databases' is not supported in this version of SQL Server.

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a database under SQL databases in Azure, in this case Standard S0:10 DTUs. Try to run the sp_Blitz Alter Procedure script.

**What is the expected behavior?**
Being able to create the sp_Blitz stored procedure.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Sql 12.0.2000.8 (Sql 2014 RTM) managed by Azure. First time testing this in Azure. I believe they worked on our hosted SQL servers and VMs.

Probably a known issue but I didn't see it in the list :) (only the snarky "If we knew them, they would be known. Duh." :) )

**Comment by BrentOzar** [comment]
Correct, check the readme on the home page here - Azure SQL DB isn’t supported. Brent

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by GustavoFischer** [comment]
Thank you and sorry to bother. Could this be added to the readme/known issues in-script?

**Comment by BrentOzar** [comment]
Sure, follow the instructions in the contributing guide and you can actually do that work if it’s important to you. (This is the fun thing about open source - your contributions are totally welcome!)
