### ISSUE TITLE
Tweak Criteria for "Busy Loops" Warnings in BlitzCache

### ISSUE THREAD

**Issue by jadarnel27** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1899]
**Is your feature request related to a problem? Please describe.**
I noticed the BlitzCache ["busy loops" warning](https://www.brentozar.com/blitzcache/busy-loops/) on a stored procedure.  Here's the "Details" from that result for reference:

 >Operations have been found that are executed 100 times more often than the number of rows returned by each iteration. This is an indicator that something is off in query execution.

However, the operators in question had estimated rows of "0" and estimated execution of "1."  Running the query from the linked help page results in:

|node_id|estimated_rows|estimated_executions|
|-|-|-|
|0|0|1|
|1|0|1|

Here's the example plan: https://www.brentozar.com/pastetheplan/?id=Syv90aPW4  
*Note: this is a natively compiled stored procedure, so it's possible this is all just a Hekaton quirk.*

**Describe the solution you'd like**
BlitzCache should filter out "busy loops" warnings where 

 - estimated rows are 0 *and* 
 - estimated executions are less than 100

This feels like it would eliminate the "false positive" scenario above, while still allowing real problem operators (0 estimated rows, 100 or more estimated executions) to bubble up.

**Describe alternatives you've considered**
My original thought was to eliminate all busy loops results where estimated rows is 0.  My concern with that would be that it could hide real problems.  You all have seen this script used in practice a lot more than I have - are there cases where an operator with 0 estimated rows is causing real problems?

**Are you ready to build the code for the feature?**
I'd be glad to make this change.

**Comment by BlitzErik** [comment]
Yep, this should be a pretty easy fix. Go for it!

**Comment by jadarnel27** [comment]
Cool, I'll get it knocked out.

**Comment by BrentOzar** [comment]
@jadarnel27 is this something you still wanna do? If not, no worries, I'll close it.

**Comment by BrentOzar** [comment]
Haven't heard back from Josh, so closing the issue.
