### ISSUE TITLE
sp_BlitzBackups should throw an error when it fails

### ISSUE THREAD

**Issue by M-Ron** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1904]
**Version of the script**
Bug in sp_BlitzBackups - (2.10)

**What is the current behavior?**
When executing sp_BlitzBackups from a SQL Agent job, it does not cause the job to fail if sp_BlitzBackups does not complete successfully.

**If the current behavior is a bug, please provide the steps to reproduce.**
For example if I were to execute this on a newly installed SQL Server without having first created the linked server named 'BIG-AG':
```
	EXEC sp_BlitzBackups 
	@PushBackupHistoryToListener = 1, 
	@WriteBackupsToListenerName = 'BIG-AG', 
	@WriteBackupsToDatabaseName = 'Backups-AG', 
	@WriteBackupsLastHours = 3000
```
We would get this message:
```
	Pushing backup history to listener
	We need a linked server to write data across. Please set one up for BIG-AG.
```

But we see that the "Query executed successfully."

**What is the expected behavior?**
sp_BlitzBackups should throw a SQL error if it cannot execute as required; it should not finish with "Query executed successfully." in these cases.
The fix would be to change the 'severity' value for every call to RAISERROR where it is immediately followed by a RETURN.  The RAISERROR should be called with a 'severity' value of 16 instead of 0 as it is done for example in sp_BlitzCache to cause it to throw a SQL error.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All versions of SQL Server and of the O/S would be affected by this.
As I am not yet a GitHubian I'm reporting this with the hope someone could have a look at making this change.

**Comment by BrentOzar** [comment]
M-Ron - thanks, but this isn't really free consulting here, unfortunately. You're absolutely welcome to point out the specific lines that need to be changed, and how to change them, but if you need a change made, you do need to roll up your sleeves and help. Is this something you want to tackle?

**Comment by M-Ron** [comment]
'free consulting', ha!  I'd never think of it.  The T-SQL change is quite straight forward, I can make the change.   I'd just need to get up the GiHub learning curve...

**Comment by M-Ron** [comment]
I have created my first Pull request for this issue.  Let me know if I missed anything.  Thanks!

**Comment by BrentOzar** [comment]
Great job! Congratulations on getting your first (two!) pull requests accepted. Thumbs up! Now go enjoy the beverage of your choice for the weekend. This will be in the Feb release of the First Responder Kit, and we'll credit you in the announcement.
