### ISSUE TITLE
sp_BlitzFirst throws an error if it calls sp_BlitzCache with @SortOrder = 'memory grant' for SQL Server versions that do not support it

### ISSUE THREAD

**Issue by M-Ron** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1910]
**Version of the script**
Bug in sp_BlitzFirst - (6.10)

**What is the current behavior?**
When triggering sp_BlitzFirst as part of a SQL Agent job, this fails at the same time every day with this error:
	"Your version of SQL does not support sorting by memory grant or average memory grant. Please use another sort order."
While this error is valid based on the triggered query (i.e. sp_BlitzCache @SortOrder = 'memory grant'), as this server is version 10.0.6535.0, it prompted investigations into potential memory grant issues. 

Ideally the triggered sp_BlitzCache would not be called with the @SortOrder = 'memory grant' for SQL Server versions that would cause it to fail.  This would allow sp_BlitzFirst to fully complete its analysis.

To address this we can take the SQL Server version check from sp_BlictCache and implement it in sp_BlitzFirst.

Ahead of the line `RAISERROR('Calling sp_BlitzCache',10,1) WITH NOWAIT;` add this:
```
	DECLARE	@v DECIMAL(6,2),
		@build INT,
		@memGrantSortSupported BIT = 1;

	RAISERROR (N'Determining SQL Server version.',0,1) WITH NOWAIT;

	INSERT INTO #checkversion (version)
	SELECT CAST(SERVERPROPERTY('ProductVersion') AS NVARCHAR(128))
	OPTION (RECOMPILE);


	SELECT @v = common_version ,
		   @build = build
	FROM   #checkversion
	OPTION (RECOMPILE);

	IF (@v < 11)
	OR (@v = 11 AND @build < 6020) 
	OR (@v = 12 AND @build < 5000) 
	OR (@v = 13 AND @build < 1601)
		SET @memGrantSortSupported = 0;
```

Change:
	`WHEN Finding = 'Poison Wait Detected: RESOURCE_SEMAPHORE' THEN 'memory grant'
	WHEN Finding = 'Poison Wait Detected: RESOURCE_SEMAPHORE_QUERY_COMPILE' THEN 'memory grant'`

To this:
	`WHEN Finding = 'Poison Wait Detected: RESOURCE_SEMAPHORE' AND @memGrantSortSupported = 1 THEN 'memory grant'
	WHEN Finding = 'Poison Wait Detected: RESOURCE_SEMAPHORE_QUERY_COMPILE' AND @memGrantSortSupported = 1 THEN 'memory grant'`

Change:
	`IF @BlitzCacheSortOrder IS NULL AND EXISTS (SELECT * FROM #BlitzFirstResults WHERE CheckID = 34)`

To this:
	`IF @BlitzCacheSortOrder IS NULL AND EXISTS (SELECT * FROM #BlitzFirstResults WHERE CheckID = 34) AND @memGrantSortSupported = 1`

**What is the expected behavior?**
sp_BlitzFirst should complete successfully on all supported SQL Server versions (2008 and up) even when CheckID 34 is encountered.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All versions of SQL Server where calling sp_BlitzCache with @SortOrder = 'memory grant' would fail are affected.
As I am not yet a GitHubian I'm reporting this with the hope someone could have a look at making this change.

**Comment by BrentOzar** [comment]
Great job! Congratulations on getting your first (two!) pull requests accepted. Thumbs up! Now go enjoy the beverage of your choice for the weekend. This will be in the Feb release of the First Responder Kit, and we'll credit you in the announcement.
