### ISSUE TITLE
False alarm "x backups done on drive y:\ in the last two weeks, where database files also live. This represents a serious risk if that array fails."

### ISSUE THREAD

**Issue by HenrikStaunPoulsen** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1916]
**Version of the script**
7.1 dated 20190101

**What is the current behavior?**
if reports 
x backups done on drive y:\ in the last two weeks, where database files also live. This represents a serious risk if that array fails."
even if there are no databases on the y: drive _EXCEPT TempDb_

**If the current behavior is a bug, please provide the steps to reproduce.**
put tempdb on its own drive. backup a database to the same drive. run sp_blitz.

**What is the expected behavior?**
tempdb is recreated on start-up, so we're not loosing data if we lose that drive. 

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
all versions, event SQL Server 2008 R2.

**Note:**
I'll try to change line 958 of sp_blitz from
   FROM sys.master_files AS mf )
to
   FROM sys.master_files AS mf WHERE mf.database_id <> 2)

which fixes the problem on my server.
I'm not a GitHub super-user, so it may take a day or two.

**Comment by BrentOzar** [comment]
Great catch, and great bug report! You made the fix really easy, so I went ahead and did it. It's in the dev branch now, and it'll be in the next release. Thanks sir!

**Comment by HenrikStaunPoulsen** [comment]
great, then I did not have to learn to use GitHub, again.
