### ISSUE TITLE
sp_blitz incorrectly excludes checks on EC2 VM with default name

### ISSUE THREAD

**Issue by rknight29** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1925]
**Version of the script**
7.1

**What is the current behavior?**
When running on an EC2 VM (actually an AWS workspace in this case) it will exclude the checks that don't work on RDS.  This is because it is looking at the server name to decide if its RDS or not. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Run on any server with a hostname staring with EC2AMAZ-.  It doesn't even have to be an AWS instance.  

**What is the expected behavior?**
This should only apply to actual RDS databases, not IaaS  VMs

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
I just noticed this so I don't know.  This was on SQL 2017 but it doesn't appear to be in a version specific part of the code. 

![2019-01-17 18_14_11-sqlquery10 sql - local ssg_healthcheck_a09610eb011c4e6eb03896c7da3fd43c corp_](https://user-images.githubusercontent.com/16143654/51361211-cc2c3d00-1a83-11e9-9285-0e848063ad16.png)

**Comment by BrentOzar** [comment]
Awwww, c'mon, man, you're not even bothering to change your server names? ;-)

Yeah, I bet I can reverse engineer it based on some of the system objects they put in. I'll spin one up and check.

**Comment by BrentOzar** [comment]
Fixed. The dev branch now detects RDS by also looking for:

```
		   AND db_id('rdsadmin') IS NOT NULL
		   AND EXISTS(SELECT * FROM master.sys.all_objects WHERE name IN ('rds_startup_tasks', 'rds_help_revlogin', 'rds_hexadecimal', 'rds_failover_tracking', 'rds_database_tracking', 'rds_track_change'))
```

And then also adds a priority 0 (top) result noting that checks were skipped because RDS was detected. Also added that for Express Edition and Azure SQL DB Managed Instances while I was in there.

**Comment by BrentOzar** [comment]
![screen shot 2019-01-18 at 7 56 11 am](https://user-images.githubusercontent.com/245462/51397706-9ecca700-1af6-11e9-982b-01d5b315cfb5.png)

**Comment by rknight29** [comment]
It is admittedly an edge case ha.

**Comment by erikdarlingdata** [comment]
Just FYI, this breaks on RDS now. The stuff you're looking for in sysobjects doesn't show up.

![image](https://user-images.githubusercontent.com/2136037/54566128-633f4380-49a6-11e9-94ab-941e460f0f9d.png)

**Comment by BrentOzar** [comment]
Hmm, you sure? I just created a new RDS instance and they were there:

![Screen Shot 2019-03-20 at 9 23 53 AM](https://user-images.githubusercontent.com/245462/54701292-f2a53d80-4af1-11e9-9229-204f4d6217c6.png)

(I know, I know, Azure Data Studio screenshot, hahaha)

**Comment by erikdarlingdata** [comment]
Yep, though in my case it was a permissions issue I think.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by BrentOzar** [comment]
Ah. In order to run our scripts, you need to have SA-level permissions. If you're a lower-level user, like an outside contractor who's only trusted to run selects in tempdb, you may need to get someone more senior from the client to help.

![wham](https://user-images.githubusercontent.com/245462/54701799-e40b5600-4af2-11e9-94e7-0d20e17243dd.gif)

**Comment by erikdarlingdata** [comment]
I hear the Tiger Toolkit is a nice alternative for the security minded.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
