### ISSUE TITLE
sp_BlitzCache: An INSERT EXEC statement cannot be nested

### ISSUE THREAD

**Issue by DatAssCode** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1929]
I'm running sp_BlitzCache, Version 6.12, in a wrapper procedure to store the query data. I'm getting a nester insert exec error as there is an insert exec, moving the insert into the dynamic SQL fixes the issue.

The insert exec is here:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/89ceb09c62b2074ff82c956a59151a439ec53345/sp_BlitzCache.sql#L1566

**Comment by BrentOzar** [comment]
Oh neat! It's cool that you're using it that way, very interesting. Sure, if you'd like to code that, check out the contributing guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md

And if you have any questions, let me know. If you decide you don't wanna do it, no worries, just let me know and I can close the issue.

**Comment by DatAssCode** [comment]
Thanks for the response, I didn't realize I could make changes. I'll follow the contributing guide :D

**Comment by DatAssCode** [comment]
I've been to told to change our implementation rather than fix this issue by my employee, so I'm closing this issue.

**Comment by BrentOzar** [comment]
OK, no problemo! Thanks for submitting it anyway. Have a good weekend.
