### ISSUE TITLE
sp_BlitzIndex DaysUptimeInsertValue variable NULL against Azure SQL DB

### ISSUE THREAD

**Issue by imyourdba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1933]
**Version of the script**
7.2 (20190128)

**What is the current behavior?**
Throws a NULL value error:

check_id 120: Check Constraints That Reference Functions
Insert a row to help people find help
Failure analyzing temp tables.
Msg 50000, Level 16, State 2, Procedure dbo.sp_BlitzIndex, Line 4892 [Batch Start Line 0]
Cannot insert the value NULL into column 'index_definition', table 'tempdb.dbo.#BlitzIndexResults__________________________________________________________________________________________________000000060D38'; column does not allow nulls. INSERT fails.

**If the current behavior is a bug, please provide the steps to reproduce.**
Run sp_BlitzIndex without parameters specified

EXEC [dbo].[sp_BlitzIndex]

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Azure SQL DB...it was working fine with version 6.12 (20181201)

**Comment by imyourdba** [comment]
Just tested and it also throws the error at the same place in version 7.1 (20190101)

**Comment by BrentOzar** [comment]
Great, thanks for the code! Committed the change, and it's in the dev branch now.
