### ISSUE TITLE
sp_BlitzFirst - Show Batch Requests/sec and Wait time per core per second as decimal values

### ISSUE THREAD

**Issue by RichBenner** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1940]
**Version of the script**
Current (7.2)

**What is the current behavior?**
The counters `batch requests/sec` and `wait time per core per second` are currently rounded to whole numbers. It would be good if these showed decimal values.

**Comment by BrentOzar** [comment]
Great job as always! Thanks sir. This will be in the Feb release with a shout-out. Thanks!
