### ISSUE TITLE
sp_Blitz - Check Running Services for SSIS, SSAS, SSRS

### ISSUE THREAD

**Issue by RichBenner** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1943]
**Is your feature request related to a problem? Please describe.**
Nope, just a feature.

**Describe the solution you'd like**
It would be good to run xp_cmdshell 'net start' to pull in services and flag up if SSRS/SSAS/SSIS and potentially more services are currently running. 

**Describe alternatives you've considered**
Other than this it's a fairly manual process.

**Are you ready to build the code for the feature?**
More than happy to. I'll code for the three SS*S processes to start with. 

I guess this would probably sit around level 110 - Performance?

**Comment by RichBenner** [comment]
I've got the code ready to go for this. I've set it as a 200 - Performance priority level. Do you have a handy url for that column in the output?

**Comment by BrentOzar** [comment]
Perfect, thanks sir! I wrote up a blog post and added a URL. It'll be in the Feb release and I'll credit you in the release notes. Thanks!
