### ISSUE TITLE
sp_BlitzCache - Version Check returning datasets

### ISSUE THREAD

**Issue by jeffchulg** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1948]
**Version of the script**
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.

2019.01.01
**What is the current behavior?**
It's not possible to only get back the VersionDate without running the actual code...

**If the current behavior is a bug, please provide the steps to reproduce.**
DECLARE @BlitzCacheVersionDate  DATETIME2;
EXEC sp_BlitzCache @SkipAnalysis = 1 , @VersionDate = @BlitzCacheVersionDate OUTPUT;

**What is the expected behavior?**
If you do following commands, you can get back the version without actually execute the whole procedure logic:
EXEC sp_Blitz @Help = 1, @VersionDate = @BlitzVersionDate OUTPUT ;
EXEC sp_BlitzFirst @Help = 1, @VersionDate = @BlitzFirstVersionDate OUTPUT;

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
all

**Comment by BrentOzar** [comment]
Sure, if you'd like to code that, we'd welcome that as a contribution. Here's the contributing guide to get started:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md

If you didn't intend to code it, no worries - we'll close this in a few days if you don't respond. Thanks!

**Comment by BrentOzar** [comment]
Great job! Merged into dev, and it'll be in the February release along with your name in the credits. Love the idea and the execution.
