### ISSUE TITLE
BlitzIndex output to table failing

### ISSUE THREAD

**Issue by arampendley** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1952]
**Version of the script**
SET @Version = '7.2';
SET @VersionDate = '20190128';

**What is the current behavior?**
Output to table fails.

Starting run. sp_BlitzIndex(TM) v7.2 - January 28, 2019
Create temp tables.
Adding UQ index on #IndexSanity (database_id, object_id, index_id)
Inserting data into #IndexColumns for clustered indexes and heaps
Inserting data into #IndexColumns for nonclustered indexes
Inserting data into #IndexSanity
Checking partition count
Preferring non-2012 syntax with LEFT JOIN to sys.dm_db_index_operational_stats
Inserting data into #IndexPartitionSanity
Inserting data into #MissingIndexes
Inserting data into #ForeignKeys
Gathering Computed Column Info.
Gathering Trace Flag Information
Gathering Temporal Table Info
Updating #IndexSanity.key_column_names
Updating #IndexSanity.partition_key_column_name
Updating #IndexSanity.key_column_names_with_sort_order
Updating #IndexSanity.key_column_names_with_sort_order_no_types (for create tsql)
Updating #IndexSanity.include_column_names
Updating #IndexSanity.include_column_names_no_types (for create tsql)
Updating #IndexSanity.count_key_columns and count_include_columns
Updating index_sanity_id on #IndexPartitionSanity
Inserting data into #IndexSanitySize
Warning: Null value is eliminated by an aggregate or other SET operation.
Determining index usefulness
Updating #IndexSanity.referenced_by_foreign_key
Update index_secret on #IndexSanity for NC indexes.
Update index_secret on #IndexSanity for heaps and non-unique clustered.
Populate #IndexCreateTsql.
Populate #PartitionCompressionInfo.
Update #PartitionCompressionInfo.
Update #IndexSanity for filtered indexes with columns not in the index definition.
@Mode=2, here's the details on existing indexes.
Failure analyzing temp tables.
Msg 50000, Level 16, State 3, Procedure dbo.sp_BlitzIndex, Line 4892 [Batch Start Line 2]
Implicit conversion from data type datetime to int is not allowed. Use the CONVERT function to run this query.

**If the current behavior is a bug, please provide the steps to reproduce.**
DECLARE @DatabaseName NVARCHAR(128) = N'MYDATABASE'
DECLARE @Mode TINYINT = 2
DECLARE @OutputDatabaseName NVARCHAR(256) = N'master'
DECLARE @OutputSchemaName NVARCHAR(256) = N'dbo'
DECLARE @OutputTableName NVARCHAR(256) = N'BlitzIndex'

EXECUTE [dbo].[sp_BlitzIndex] 
   @DatabaseName = @DatabaseName
  ,@Mode = @Mode
  ,@OutputDatabaseName = @OutputDatabaseName
  ,@OutputSchemaName = @OutputSchemaName
  ,@OutputTableName = @OutputTableName

**What is the expected behavior?**
Output to table with no errors.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2017 CU12. Yes, worked in previous version.

**Comment by alchemistmatt** [comment]
I am also seeing this on Microsoft SQL Server 2014; it was working last month.  Unfortunately, the reported line number (4892) isn't helpful.

**Comment by alchemistmatt** [comment]
Digging into this I found the issue: the `[Drop_Tsql]` and `[Create_Tsql]` columns are not in the correct position for the INSERT query at https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/a4bc3358b918c20de2dda17c7ffcfc9f4bdaaff5/sp_BlitzIndex.sql#L4572
They are currently between `[index_name]` and `[index_id]` but they need to be between `[more_info]` and `[display_order]`.

I'll look into making a Pull Request.
