### ISSUE TITLE
sp_Blitz - limit to specific database

### ISSUE THREAD

**Issue by rasmus** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1959]
**Is your feature request related to a problem? Please describe.**
I'm a developer that has access to a few databases on our production system and would like to be able to use `sp_Blitz` to analyse each database separately.

**Describe the solution you'd like**
While `sp_Blitz` has excellent support for omitting specific databases, servers and checks, it doesn't allow me to limit it to only one database. Maybe add a `@CheckOnlyDatabase` argument that allows me to check a single database.

**Describe alternatives you've considered**
As I don't control the other databases on the server, I can't maintain a list of databases using the skip table.

**Are you ready to build the code for the feature?**
Maybe, will need to get legal approval to contribute to the project and as I'm a pure developer which only seldom dabble with SQL, you might not like my SQL style 😄

**Comment by BrentOzar** [comment]
Gotcha. That's what sp_BlitzIndex and sp_BlitzCache are for - developers that need to analyze queries and indexes. Those two procs have database name parameters. 

sp_Blitz is for database administrators and systems administrators. 

Closing.
