### ISSUE TITLE
sp_Blitz - documentation update?

### ISSUE THREAD

**Issue by RichBenner** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1966]
**Version of the script**
current dev script, but this isn't new.

**What is the current behavior?**
in the documentation for sp_Blitz it shows that check 223 and 204 do the opposite to what they actually appear to do in the script. In sp_Blitz it shows that 223 is the check for @CheckUserDatabaseObjects disabled but the script actually does that in check 204. Does the documentation need to just swap these two around?

**Comment by BrentOzar** [comment]
Great catch! Fixed. Thanks!
