### ISSUE TITLE
sp_Blitz - Supported Version Check

### ISSUE THREAD

**Issue by RichBenner** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1967]
**Version of the script**
current dev script

**What is the current behavior?**
when running check 128 for the supported version of sql server, it's got the following check for SQL 2012.
```
(@ProductVersionMajor = 11 AND @ProductVersionMinor < 6518) OR
```
Checking this on https://sqlserverupdates.com/sql-server-2012-updates/ it appears that SP4 is a necessity so I think it should be this as of October 2018
```
(@ProductVersionMajor = 11 AND @ProductVersionMinor < 7001) OR
```

**Comment by BrentOzar** [comment]
Great catch! Fixed. Thanks sir!
