### ISSUE TITLE
sp_Blitz Find 'Memory Dumps Have Occurred' URL not found

### ISSUE THREAD

**Issue by rogatec** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1968]
**Version of the script**
`Version = 7.2`
`VersionDate = 2019-01-28`

**What is the current behavior?**
Page not found

**If the current behavior is a bug, please provide the steps to reproduce.**
execute _sp_Blitz_ and browse to the URL given by Finding `Memory Dumps Have Occured`
given URL: https://BrentOzar.com/go/dump

**What is the expected behavior?**
Page found ;-)

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
doesn't matter

**Comment by BrentOzar** [comment]
Yep, that's a new blog post going live next week. Stay tuned!
