### ISSUE TITLE
VersionDate variable defined twice in many scripts

### ISSUE THREAD

**Issue by sivey42** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1978]
**Version of the script**
7.3, 20190219

**What is the current behavior?**
parameters...
    @Help BIT = 0,
    @Version     VARCHAR(30) = NULL OUTPUT,
	@VersionDate DATETIME = NULL OUTPUT,
    @VersionCheckMode BIT = 0,
    @VersionDate DATETIME = NULL OUTPUT
…
SET @Version = '7.3';
SET @VersionDate = '20190219';
DECLARE @Version VARCHAR(30);
SET @Version = '7.2';
SET @VersionDate = '20190128';

**If the current behavior is a bug, please provide the steps to reproduce.**
VersionDate is duplicated in parameter lists

**What is the expected behavior?**
Should be there only once

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

**Comment by BrentOzar** [comment]
Hi! You happened to get a mid-deployment version - hang tight. We're not quite done with the release yet. Thanks!
