### ISSUE TITLE
Release 2019-02-19 @VersionCheckMode error (duplicate @Version variable)

### ISSUE THREAD

**Issue by jerryhung** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1981]
**Version of the script**
V7.2/V7.3 sp_Blitz (or any of them really)

**What is the current behavior?**
	SET @Version = '7.3';
	SET @VersionDate = '20190219';
	DECLARE @Version VARCHAR(30);
	SET @Version = '7.2';
	SET @VersionDate = '20190128';
	SET @OutputType = UPPER(@OutputType);
The variable name '@Version' has already been declared. Variable names must be unique within a query batch or stored procedure.

**If the current behavior is a bug, please provide the steps to reproduce.**
just deploy any sp* code or the All code and it'll error

**What is the expected behavior?**
once I commented out
	--DECLARE @Version VARCHAR(30);
	--SET @Version = '7.2';
	--SET @VersionDate = '20190128';
now I can deploy

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2014

**Comment by BrentOzar** [comment]
Sorry about that - you caught us in the middle of a deployment. It's already fixed though - download a new copy. Thanks!
