### ISSUE TITLE
sp_Blitz - EXECUTE vs sp_executesql

### ISSUE THREAD

**Issue by RichBenner** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1982]
**Version of the script**
current dev, not a new thing though

**What is the current behavior?**
I've noticed that sp_Blitz mixes using EXECUTE(@StringToExecute) and elsewhere uses EXEC sp_executesql (). Would there be an advantage at standardising this? With how often sp_Blitz is run (not very) I don't believe it to be a performance issue either way.

It may well be that EXEC is used because of parameter sniffing concerns, if so, that makes total sense. I'd be happy to modify this to standardise one way or the other though if it's not a concern.

**Comment by BrentOzar** [comment]
If you want to work on it, work in the #1970 issue where Henrik's been working a lot on getting it to work in Azure SQL DB and Hyperscale. (There's a ton of work there.)
