### ISSUE TITLE
sp_BlitzFirst passing invalid sort orders to sp_BlitzCache

### ISSUE THREAD

**Issue by bmrazik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1983]
when running this as a part of blitzfirst, it errors out causing the agent job to error:
 Invalid sort order chosen, reverting to cpu [SQLSTATE 42000]

**Comment by BrentOzar** [comment]
Sorry about that! Fixed in the dev branch. You can grab the updated version here:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzFirst.sql

It was calling sp_BlitzCache @SortOrder = 'compilations', which should have been 'recent compilations'. Thanks!
