### ISSUE TITLE
sp_BlitzCache: use the OS's default decimal separators (commas vs periods) in output

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1985]
**Version of the script**
SET @Version = '7.3';
SET @VersionDate = '20190219';

**What is the current behavior?**
When run on a VM with the default decimal separator as comma, and default digit grouping separator as period:

![screen shot 2019-02-23 at 4 21 28 am](https://user-images.githubusercontent.com/245462/53286389-8fa6cd80-3722-11e9-8da4-085a5c231299.png)

sp_BlitzCache isn't honoring that:

![screen shot 2019-02-23 at 4 19 36 am](https://user-images.githubusercontent.com/245462/53286391-9df4e980-3722-11e9-8914-702a3147b595.png)

**What is the expected behavior?**
The output should match the user's regional settings.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Has probably been this way since the dawn of time. (It's present in other scripts too, like sp_BlitzIndex's text column for object size, and sp_BlitzFirst, but let's tackle this one first.)

**Comment by NielsSchNL** [comment]
This is my first-ever reply to a GitHub project. I'm eager to participate but please forgive me if I'm not following the correct code of conduct. 

I'd be happy to take a swing at this if you'd like. However, I'm not clear on which regional settings should be honored. Are we trying to honor the server OS regional settings or the settings the client OS creating the session (for instance SSMS)?

AFAIK (and please correct me if I'm wrong) the client OS regional settings are not visible in a session. Each session simply defaults to the server/database's settings (as shown in @@LANGUAGE). The server OS regional settings may be found in sys.dm_os_windows_info but that won't cover every scenario. The best way to move forward on this may be to introduce a parameter.

Sidenote: if another locale would've been honored then sp_BlitzCache would break anyway as there's some hard-coded REPLACE going on to strip '.00'-decimals in the output.

**Comment by BrentOzar** [comment]
Hi, and welcome to the project! It'd be the server's default settings - the same thing you see when you run this:

`SELECT CAST(1 AS DECIMAL(10,2)) / 10 AS OneTenth`

Depending on your server's defaults, you may see either comma separators or decimal separators there.

**Comment by NielsSchNL** [comment]
I've created a pull request with my changes ( #2012 ). I've tested it as far as I could. Seems to work just as expected now, based on the session's current language setting.

**Comment by BrentOzar** [comment]
@NielsSchNL getting closer - does work on cost, but doesn't quite work as expected on most columns though, like weight and memory grants:

![Screen Shot 2019-04-18 at 8 10 48 AM](https://user-images.githubusercontent.com/245462/56371271-aeb95d00-61b1-11e9-8528-222edc6cab13.png)

![Screen Shot 2019-04-18 at 8 11 06 AM](https://user-images.githubusercontent.com/245462/56371278-b24ce400-61b1-11e9-9f5c-2d3bab85fa04.png)

![Screen Shot 2019-04-18 at 8 11 22 AM](https://user-images.githubusercontent.com/245462/56371282-b4af3e00-61b1-11e9-8fda-a34e69c98478.png)

**Comment by johnvanaltvorst** [comment]
Hey @BrentOzar , would you accept formatting on SQL Server versions 2012+ only?

I'm thinking that we could use the `FORMAT` function utilizing the culture param which would be a param to sp_BlitzCache.

If the user provides this culture param to sp_BlitzCache and is running SQL Server 2008/2008R2, it would give them a message that formatting is not supported and they would get non formatted output (or just not run at all and the user needs to remove the culture param to run exec the sp).

**Comment by BrentOzar** [comment]
@johnvanaltvorst no, I think we need to keep this at SQL Server 2008 compatibility for now. 2008 & 2008R2 adoption is still higher than 2019: https://www.brentozar.com/archive/2020/06/sql-constantcare-population-report-spring-2020/

With that in mind, I think I'm going to close this for now - it'd be nice to have, but there just isn't an easy solution on this, and it's not that high of a priority, more of a nice-to-have. Thanks though!
