### ISSUE TITLE
sp_DatabaseRestore @StopAt ignored when @ContinueLogs = 1

### ISSUE THREAD

**Issue by troyjennings** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1986]
**Version of the script**
SET @Version = '7.3';
SET @VersionDate = '20190219';

**What is the current behavior?**
When @StopAt is not null and @ContinueLogs = 1, the StopAt value was not in the criteria for determining transaction log backups to apply.

**What is the expected behavior?**
When @StopAt is not null and @ContinueLogs = 1 only the transaction log backups up to the StopAt value would be applied.

**Comment by BrentOzar** [comment]
Great catch! Merged it into the dev branch, and I'll credit you for the March release. Thanks, and good work!

**Comment by troyjennings** [comment]
Great, thanks!
