### ISSUE TITLE
sp_BlitzIndex - Duplicate columns in Insert statement when writing to an existing table

### ISSUE THREAD

**Issue by alchemistmatt** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1988]
**Version of the script**
Version 7.3
VersionDate 20190219

**What is the current behavior?**
Running with `@outputToTables=1` leads to error
```
Msg 50000, Level 15, State 1, Procedure sp_BlitzIndex, Line 4901 [Batch Start Line 8]
The select list for the INSERT statement contains fewer items than the insert list. The number of SELECT values must match the number of INSERT columns.
```
I have found the issue: Drop_Tsql and Create_Tsql are included twice in the Insert list.  See:
* https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/8778f770cc04b07c74547847f5ea4da7089cc758/sp_BlitzIndex.sql#L4578
* https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/8778f770cc04b07c74547847f5ea4da7089cc758/sp_BlitzIndex.sql#L4640
I will submit a pull request to fix this.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
EXEC RunBlitzChecks 
    @overview = 0,
    @runBlitz = 1,
    @runBlitzCache = 1,
    @runBlitzIndex = 1,
    @blitzIndexDatabaseList= 'dba',
    @outputToTables=1, 
    @outputDatabaseName='dba'
```

**What is the expected behavior?**
No Error. 

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Tested with Microsoft SQL Server 2014 (SP2); worked 2 months ago.  Tried to fix last month; I suspect a merge mangled things.

**Comment by BrentOzar** [comment]
Makes sense! Not sure what RunBlitzChecks is though. :-D

**Comment by alchemistmatt** [comment]
Oh, right, that's my wrapper procedure that calls several first responder stored procedures.

**Comment by alchemistmatt** [comment]
Corrected **steps to reproduce**
```

EXEC sp_BlitzIndex @GetAllDatabases = 1, @Mode=2,
                    @OutputDatabaseName = 'dba', 
                    @OutputSchemaName = 'dbo',
                    @OutputTableName = 'T_BlitzIndex_Results',
                    @BringThePain = 0
```

**Comment by BrentOzar** [comment]
Good job! Reviewed & tested, and merged in for the March release. I'll credit you in the release notes. Thanks, and have a good week!
