### ISSUE TITLE
sp_Blitz Error related to @SkipChecks and not-null params

### ISSUE THREAD

**Issue by lowellizaguirre** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1990]
**Version of the script**
	SET @Version = '7.1';
	SET @VersionDate = '20190101';

**What is the current behavior?**
Error occurs when running with parameters identified below: specific error,and command that is dynamically created are below: it looks like it is building an invalid FROM statement, might be legacy code?
The code that this occurs on is on line 231:
		IF @SkipChecksTable IS NOT NULL
			AND @SkipChecksSchema IS NOT NULL
			AND @SkipChecksDatabase IS NOT NULL
			BEGIN
				
				IF @Debug IN (1, 2) RAISERROR('Inserting SkipChecks', 0, 1) WITH NOWAIT;
				
				SET @StringToExecute = 'INSERT INTO #SkipChecks(DatabaseName, CheckID, ServerName )
				SELECT DISTINCT DatabaseName, CheckID, ServerName
				FROM ' + QUOTENAME(@SkipChecksDatabase) + '.' + QUOTENAME(@SkipChecksSchema) + '.' + QUOTENAME(@SkipChecksTable)
					+ ' WHERE ServerName IS NULL OR ServerName = SERVERPROPERTY(''ServerName'') OPTION (RECOMPILE);';
				EXEC(@StringToExecute);
			END;
This is some modified results fromthe SSMS text detailing the output and dynamic command that was created:

_Inserting SkipChecks
**INSERT INTO #SkipChecks(DatabaseName, CheckID, ServerName )
				SELECT DISTINCT DatabaseName, CheckID, ServerName
				FROM [0].[0].[0] WHERE ServerName IS NULL OR ServerName = SERVERPROPERTY('ServerName') OPTION (RECOMPILE);**
Msg 208, Level 16, State 1, Line 1
Invalid object name '0.0.0'.
PostSkipChecks_
**If the current behavior is a bug, please provide the steps to reproduce.**
EXEC dbo.sp_Blitz @CheckServerInfo=1,
                  @SkipChecksDatabase = 0,
                  @SkipChecksSchema = 0,
                  @SkipChecksTable = 0,
                  @BringThePain = 1,
                  @Debug=1
![sp_blitz_skip_checks](https://user-images.githubusercontent.com/5039118/53687828-a3949580-3d07-11e9-9cab-ed349af0a728.png)

**What is the expected behavior?**

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Version: [SQL 2016 || 13.0.1742.0] Developer Edition (64-bit), and the command was connected via named pipes,and not TCP

**Comment by BrentOzar** [comment]
Hmm, have you read the documentation about what those parameters do? You don't pass numbers into those - they're for passing in the database, schema, and table name of your SkipChecks table.
