### ISSUE TITLE
sp_BlitzIndex: merge low-impact and high-impact missing indexes

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1991]
We have two findings:

* "Indexaphobia: High value missing index with Low Impact"
* "Indexaphobia: High value missing index with High Impact"

Let's just merge these together into:

* "Indexaphobia: High value missing index"

**Comment by beckmanjm** [comment]
This is an unfortunate change - we preferred the old way of doing things. For the most part, the Low Impact indexes were ones we ignored, but might look at if there were also high impact indexes. We break them out in reports. Any way this could be made optional?

**Comment by BrentOzar** [comment]
The problem is that the impact is SQL Server's guess, and that guess was often wrong. It might estimate that an index have low impact, but then the presence of the index radically changes the plan, and further opportunities arise. I just wouldn't put any credence in that number.
