### ISSUE TITLE
sp_Blitz - Add Check for all FRK SP version date is the same

### ISSUE THREAD

**Issue by jeffchulg** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1994]
**Is your feature request related to a problem? Please describe.**

As I added the capability to run all the SP in VersionCheckMode, the next step could be to run a check for "schema consistency" (and I think sp_Blitzis the right candidate to do it).

**Describe the solution you'd like**

In sp_BlitzFirst, create a temporary table which contains the name of each SP, except sp_Blitz.

Run a loop that will:
0) Create a variable Highest
1) Check the procedure exists
1a=> if not exists ==> continue
1b => if exists:
   run the stored procedure in VersionCheckMode (using dynamic SQL) and maybe between TRY...CATCH.
   if the version for at least one SP is older than the one from sp_Blitz, then there is an inconsistent installation
   If the version for at least one SP is higher than the one from sp_Blitz, then there is an insconsistent installation
   

**Describe alternatives you've considered**

Create a new dedicated stored procedure

**Are you ready to build the code for the feature?**
As much as we'd love to build everything that everyone wants for free, we need your help. Open source is built with your help and code. Are you ready to commit time to this project? Have you got existing code you can help contribute to solve the problem?

Why not... it does not seem to be difficult or time-consuming to implement...

**Comment by BrentOzar** [comment]
I love it! That's a great idea. Things to think about:

* One or more of the scripts may not exist (and that's OK, shouldn't flag a warning that there's an inconsistent installation)
* The scripts may be installed in the master database, but you may be in a different database context
* The scripts may be installed in a user database, and you may be in the same database context (example: users install it in a "DBA" database and run them from that same database, without db/schema prefixes)
* The scripts may be installed in a user database, and you may be in a DIFFERENT database context (example: installed in "DBA", but run from tempdb with fully prefixed names, like "EXEC DBA.dbo.sp_Blitz")

**Comment by jeffchulg** [comment]
HI Brent,

the use of DB_NAME() inside sp_Blitz should solve the "the scripts may be installed" sentences, shouldn't it?

**Comment by BrentOzar** [comment]
Yes, as long as you use that to build fully qualified calls to the procs, that will work, I bet.

**Comment by jeffchulg** [comment]
Hi Brent,

could you please review the code attached... I don't want to insert it directly to sp_Blitz before it's ok for you...
[VersionCheck.sql.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/2936684/VersionCheck.sql.txt)

**Comment by BrentOzar** [comment]
Can you do a regular pull request? I’m on the road, and a pull request will let other folks review the code easier. (Just don’t want it bottlenecked on me.) Thanks!

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by BrentOzar** [comment]
Awesome, thanks sir! I'm going to make a few tweaks, but great job. I've merged it, and it'll be in this month's release, along with credits for you in the blog post. Thanks!
