### ISSUE TITLE
sp_Blitz check ID 93 on Linux thinks backups exist on the same drive

### ISSUE THREAD

**Issue by ucjonathan** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1995]
**Version of the script**
	SET @Version = '7.3';
	SET @VersionDate = '20190219';

**What is the current behavior?**
Check 93 thinks that backups are on the same drive as the database.   The layout is 

/sql/data
/sql/backup

These are separate EBS volumes on the EC2 instance.  I know it's probably just doing string comparison, but I would recommend skipping this check on paths that start with /

**If the current behavior is a bug, please provide the steps to reproduce.**

Run sp_Blitz on a linux installation of SQL server.

**What is the expected behavior?**

Probably to skip the check entirely.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

SQL Server 2017 cu13 on RHEL 7.4

**Comment by BrentOzar** [comment]
Sure, feel free to contribute the change per the contributing guide. (I don’t have SQL Server on Linux, so I can’t test it, but sounds like you can pretty quickly.) Thanks! Brent

**Comment by bsquidwrd** [comment]
I can implement this fix as it _seems_ simple enough to get my hands wet on this project 👍

**Comment by BrentOzar** [comment]
Nice job! Added to the March release, and will credit you in the post. Thanks!
