### ISSUE TITLE
No logs are restored when no diff backup has been taken yet

### ISSUE THREAD

**Issue by fvanderhaegen** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1998]
When using sp_databaserestore to restore full, diff and log backups no logs are restored when no diff backup has been taken yet.

Sample:
```
exec [master].[dbo].[sp_DatabaseRestore] 
	@database='test', 
	@backuppathFull=N'[pathfull]', 
	@backuppathdiff=N'[pathdiff]', 
	@backuppathlog=N'[pathlog]',
	@restorediff=1,
	@continuelogs=0,
	@runrecovery=0,
```

If no DIFF backup has been taken yet and above script is executed, no logs will be applied.
This happens because @DiffLastLSN has not been set.

I solved the issue by adding following code at the of the IF-clause that checks if @BackupPathDiff is not empty:
`if @DiffLastLSN is null	set @DiffLastLsn=@FullLastLSN
`

**Comment by BrentOzar** [comment]
OK, cool, did you want to check in the code for it so you can get credit? (Not sure by this issue if you meant you were going to check in the fix or not.) Thanks!

**Comment by fvanderhaegen** [comment]
I'm rather a newbie in working with github, so I made the changes in my clone of the dev-branch but I'm unable to push my changes to origin.
This is the error message "remote: Permission to BrentOzarULTD/SQL-Server-First-Responder-Kit.git denied to fvanderhaegen."

**Comment by BrentOzar** [comment]
Yeah, you can’t push directly to ours - you have to open a pull request.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by fvanderhaegen** [comment]
The [pull request](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/1999) has been opened

**Comment by BrentOzar** [comment]
Good job! Thanks for that. Merged it in for the March release, and I'll credit you in the release notes. Thanks!
