### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by briangithex** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2013]
**Version of the script**
Latest raw source on Github as of this issue.

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/Documentation/sp_Blitz%20Checks%20by%20Priority.md

AND

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_Blitz.sql

**What is the current behavior?**
https://www.brentozar.com/go/azurefiles returns a page not found.

**If the current behavior is a bug, please provide the steps to reproduce.**
Visit https://www.brentozar.com/go/azurefiles .

**What is the expected behavior?**
Either don't link to https://www.brentozar.com/go/azurefiles or create a page at https://www.brentozar.com/go/azurefiles .

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
N/A

**Comment by BrentOzar** [comment]
Sorry about that! Fixed. Thanks!
