### ISSUE TITLE
sp_blitz report on User created Stored Procedures in the Master database

### ISSUE THREAD

**Issue by EamMur** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2020]
Currently when sp_Blitz executes it reports on User created Tables in the Master database.

It does not report on user created Stored Procedures (SP) in the Master database.

It would be nice to include this.

(I will work on this over the next few days)

**Comment by EamMur** [comment]
I have got the latest code down and I have read the  Code of Conduct and Contributing code. I also read the sp_Blitz check for priority.

My approach would be to 

1. Add new CheckIds (226,227,228) based on the current max value (225) with a description of "Stored Tables in the nn Database" where nn is Master, Model, MSDB for 226 , 227, 229 respectively
2: Add a section to sp_blitz to check the database for sys.procedures where is_ms_shipped = 0 and record as appropriate. Similar to how the check for tables is performed.

Is this approach acceptable ? 

Is this feature something others would find useful ?

**Comment by BrentOzar** [comment]
Sounds good! I would just add one CheckID though, and put the database in the DatabaseName column of the output. (That’s how most of the other checks work.)

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by BrentOzar** [comment]
@EamMur - is this something you still want to tackle, or should I close the issue?

**Comment by EamMur** [comment]
I still want to tackle it but my day job suddenly got very busy!

**Comment by BrentOzar** [comment]
OK, if you decide you want to work on it again sometime, you can reopen the issue. Closing for now. Thanks!
