### ISSUE TITLE
The schedule for sp_AllNightLog_Backup_01 SQL Server Agent Job is not correctly setup.

### ISSUE THREAD

**Issue by modernuniverse** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2021]
**Version of the script**
SELECT @Version = '3.4', @VersionDate = '20190320';

**What is the current behavior?**
No matter what I specify for @RPOSeconds, the sql server agent job is always created with a 10 second schedule.

**If the current behavior is a bug, please provide the steps to reproduce.**
I run this and then check the schedule setup for sp_AllNightLog_Backup_01. 

sp_AllNightLog_Setup
  @RPOSeconds = 6000,
  @RTOSeconds = 6000,
  @BackupPath = 'c:\tmp\'
  @Jobs = 1,
  @UpdateSetup = 1,
  @Debug = 1;

**What is the expected behavior?**

Expected behavior is that the job is scheduled to run every ten minutes. However, it is set up to run every 10 seconds.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Windows 10, 
Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)

**Comment by BrentOzar** [comment]
That’s by design. The job schedule doesn’t need to match your RPO. The job just wakes up and checks to see if any databases need to be backed up or restored.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by modernuniverse** [comment]
I see. That makes sense. Thank you for the quick clarification.
