### ISSUE TITLE
sp_BlitzBackup - Centralize multiple servers, use Azure SQL

### ISSUE THREAD

**Issue by gliljas** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2023]
We have many servers, some set up with HA, some with the older mirroring system. We use Hallengren's script to back them up into Azure.

To provide a full overview of the backups for all servers we would like to centralize backupset data. It would be convenient if the central DB could be an Azure SQL database.

This central data could also be used to create restore scripts and to handle deletion of old backups (since that is not available for standard URL backups). In other words, centralizing the mediaset table would also be necessary.

Current issues.

- Handle a linked server which is an Azure SQL instance (this was easy to fix by removing the "database exists" check)
- backupsetid can't be the primary key if several servers should add data
- ...otherwise, the name of the target table (backupset) should be a parameter
- backupmediaset must also be backed up

I'll gladly put some effort into this, but is it something sp_BlitzBackup should handle?

**Comment by BrentOzar** [comment]
@gliljas sure, you're welcome to work on that if you like! Here's the contributing guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

I'll leave this issue open for ~30 days, and if you change your mind and decide not to work on it, just close the issue, or leave a note for me and I can close it for you. (I wouldn't be able to work on it for free, unfortunately.)

**Comment by gliljas** [comment]
FYI. Working on it.

**Comment by BrentOzar** [comment]
Haven't heard back from you for a while - no problem, just if you decide you want to actively work on it again, you can reopen this issue. Thanks!
