### ISSUE TITLE
sp_DatabaseRestore t-log restores not applied when @BackupPathFull is null 

### ISSUE THREAD

**Issue by troyjennings** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2036]
**Version of the script**
@Version = '7.4', @VersionDate = '20190320'

**What is the current behavior?**

When @BackupPathFull is null, @BackupPathLog is set and @ContinueLogs = 1, no transaction log backups are applied.

**What is the expected behavior?**

Transaction log backups should be applied when the database is already in recovery and only the path to the log backups is provided.

**Comment by BrentOzar** [comment]
OK, cool. Do you want to make the changes? (I don't personally use this script these days, so I don't have a testing environment for it.) You can check out [the contributing guide](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md) for more info on how to do it, or check in with the Slack channel in there to see if someone else may be able to help you do it.

**Comment by reharmsen** [comment]
I did notice this in February or March, hence we reverted to an older version we were running and which functions for us (6.9).  Did not find time yet to dive in to this further.

If @troyjennings is not able to look into this, I might try to find some time in May to look in to this and hopefully fix this, at least for our setup.

**Comment by troyjennings** [comment]
@reharmsen I have a fix for it that I was testing over the weekend. I plan on pushing it today.

**Comment by reharmsen** [comment]
@troyjennings If you need help reviewing or testing I am glad to help

**Comment by troyjennings** [comment]
Thanks @reharmsen   You can get a copy of the procedure change here 
https://github.com/troyjennings/SQL-Server-First-Responder-Kit/blob/Issue_2036_2/sp_DatabaseRestore.sql

**Comment by BrentOzar** [comment]
Merged the fix - thanks @troyjennings! Will be in the May release and credit you.
