### ISSUE TITLE
sp_Blitz - URL for Instance Stacking Dead link

### ISSUE THREAD

**Issue by BilliousBT** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2041]
**Version of the script**
sp_Blitz Mar 20 2019 12:00AM

**What is the current behavior?**
sp_Blitz @CheckServerInfo = 1

**If the current behavior is a bug, please provide the steps to reproduce.**
deadlink: https://www.brentozar.com/go/babygotstacked/

**What is the expected behavior?**
webpage present

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

**Comment by BilliousBT** [comment]
Maybe point at https://www.brentozar.com/archive/2016/12/install-multiple-instances-sql-server/

**Comment by BrentOzar** [comment]
Sorry about that, and thanks for the bug report. Fixed.
