### ISSUE TITLE
sp_Blitz - New Windows 10 Power Setting (CheckID 211)

### ISSUE THREAD

**Issue by IndexSeek** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2044]
**Version of the script**
Version = 7.4
Version Date = 20190320

**What is the current behavior?**
Running EXEC sp_Blitz @CheckServerInfo = 1; returns the Power Plan finding in unknown power mode. Windows 10 Pro for Workstations OS supports a new power setting named "Ultimate Performance." 

**What is the expected behavior?**
Your server has X.XXGHz CPUs, and is in ultimate performance power mode.
This can be fixed by adding the following two lines below line 8275 in the sp_Blitz.sql file:
```
WHEN 'e9a42b02-d5df-448d-aa00-03f14749eb61'
THEN 'ultimate performance power mode'
```

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Not related to SQL Server versioning. To my knowledge, Windows 10 Pro for Workstations is the only OS affected. This may be helpful for developer localhost instances.

**Comment by IndexSeek** [comment]
![UltimatePerformancePowerSetting](https://user-images.githubusercontent.com/50381805/57332103-19422680-70e8-11e9-839f-1770c23dfe89.PNG)

**Comment by BrentOzar** [comment]
Perfect, thanks for the bug report and the code! Sorry this one took so long to get in - especially considering how easy you made it! It's in the dev branch now, and it'll be in the August release, along with a thanks to you in the change log.
