### ISSUE TITLE
Outdated Component message for sp_blitz

### ISSUE THREAD

**Issue by ejustu** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2045]
**Version of the script**
Version 7.5 27/04/2019

**What is the current behavior?**
Run on 8 May 2019 gave message Outdated Component.

**If the current behavior is a bug, please provide the steps to reproduce.**
Could be related to the fact that I am working on an Australian website and the date is not formatted in an expected way?  This gives the same error wherever I run it every time.

**What is the expected behavior?**
Not give this message unless the component is over 6 months old.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Can't tell - it gave the error message when I used the October version in April but it really was out of date at that stage and I don't have any other versions to test.

**Comment by ejustu** [comment]
Hi,

Sigh, it’s face palm time.  The message did not relate to sp_blitz but to sp_blitzcache which I thought that I had updated but appear not to have done in most environments.

I think I must have been looking at my excel spreadsheet and did not expand the column fully to see the full name.  This is an explanation but not really an excuse.

A waste of time on all counts, I am so sorry but thank you for the really quick response.

Elizabeth

[cid:image001.png@01D50665.12797170]
UNIX Database Adminstrator
D: (02) 42 980 255

**Comment by BrentOzar** [comment]
No problem at all! That's good, that means it's working. Have a good one!
