### ISSUE TITLE
sp_DatabaseRestore - Delete backup files after restore

### ISSUE THREAD

**Issue by LowlyDBA** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2050]
**Describe the solution you'd like**
After restoring database file(s), it'd be helpful to have an option to clean up the source backup files from the local directory. For example, if I'm testing a restore on a separate server the backup was taken from, it is difficult to associate the specific backup files with the restored copy outside the context of the stored procedure, and thus difficult to clean those files up automatically. 

**Are you ready to build the code for the feature?**
I am open to doing the dev work for this, but wouldn't stop anyone if they felt compelled to help out either :)

**Comment by BrentOzar** [comment]
Hmm - sp_DatabaseRestore tries to only restore the files that are necessary to get to the latest point in time. So say you have:

* Monday - full backups, differential backups, log backups
* Tuesday - full backups, differential backups, log backups
* Wednesday - differential backups, log backups

sp_DatabaseRestore (should) pick up Tuesday's full, Wednesday's most recent diff, and all the log backups after the diff.

Are you suggesting that it *only* delete the backups that it used for the restore? Or are you suggesting that it delete *all* backups in the relevant folders? If it's all of the backups...you don't need sp_DatabaseRestore to do that, do you? (I'm just not clear on the concept here, but I'm probably missing something.)

**Comment by LowlyDBA** [comment]
Just the ones it used. In your example it might not make sense to use this proposed feature, since you'd then be left with a weird mismatch of files. 

But if you had a folder containing a random ad-hoc backup someone took 6 months ago (that "needs" to be kept), the one you need to restore from Monday, and who knows what else, the idea would be to only delete the file(s) the sproc is ultimately going to be using. Most likely in this scenario you're coping the files directly to a server instead of accessing via a share of some sort, so you aren't destroying any important files by doing this. 

Maybe this is too much of an edge case?

**Comment by BrentOzar** [comment]
Yeah, I'm gonna be honest - this sounds like it's going to cause more problems than it's going to solve. If you don't need leftover files in a directory when sp_DatabaseRestore is done, then...delete those. Probably time to start doing some organization over there. ;-)
