### ISSUE TITLE
sp_BlitzCache: add @SortOrder = 'query hash'

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2051]
**Is your feature request related to a problem? Please describe.**
A lot of folks aren't parameterizing their queries, so the plan cache is full of one-offs. They want to solve performance issues, but they're not sure where to start.

**Describe the solution you'd like**
Either of these would be good:

* @SortOrder = 'query hash' - get the top 10 query hashes grouped from sys.dm_exec_query_stats, sorted by, say, duration, and show those in the grid. This might be easier to run it like we run @SortOrder = 'all' - by getting the list of top 10 query hashes, and then running sp_BlitzCache again with just those query hashes - or...
* @GroupByQueryHash = 1 - add a group by query hash to the dynamic SQL. I think this is going to be spectacularly hard though.

**Comment by BrentOzar** [comment]
@erikdarlingdata I was testing it, and it's reeeeally close, but the qhg variable ends up with a leading single quote, so the first hash doesn't go in. To see what I mean:

```
DropIndexes;
GO
CREATE INDEX IX_DisplayName ON dbo.Users(DisplayName);
GO
DBCC FREEPROCCACHE;
GO
SELECT * FROM dbo.Users WHERE UPPER(DisplayName) = 'Brent Ozar';
GO
SELECT * FROM dbo.Users WHERE UPPER(DisplayName) = 'Erik Darling';
GO
SELECT * FROM dbo.Users WHERE LOWER(DisplayName) = 'Brent Ozar';
GO
SELECT * FROM dbo.Users WHERE LOWER(DisplayName) = 'Erik Darling';
GO
sp_BlitzCache @SortOrder = 'query hash'
GO
```

Only the lowers show up. To diagnose it, in sp_BlitzCache, I went to where you're setting qhg, and added a couple of diagnostic lines at the end of this:

```
    SELECT TOP (1)
	         @qhg = STUFF((SELECT DISTINCT N',' + CONVERT(NVARCHAR(MAX), qhg.query_hash, 1) 
    FROM #query_hash_grouped AS qhg 
    WHERE qhg.query_hash <> 0x00
    FOR XML PATH(N''), TYPE).value(N'.[1]', N'NVARCHAR(MAX)'), 1, 1, N'''')
	OPTION(RECOMPILE);
    
    SELECT * FROM #query_hash_grouped;
    SELECT @qhg AS qhg;
```

And that's how I found the leading single quote:

<img width="578" alt="Screen Shot 2019-09-19 at 10 35 39 AM" src="https://user-images.githubusercontent.com/245462/65267132-3f7dc700-dac9-11e9-84de-e65ef51d5d95.png">

I was thisclose to just taking the left 1 character out of the variable, hahaha, but I figured you would look down on my crappy XML query skills.

**Comment by erikdarlingdata** [comment]
Oh, duh. I'm a dummy. I pulled the code from the dynamic SQL we use for all/all avg and forgot to remove the doubled up quote: `N''''` Just change it to `N''` if you want a quick fix. Lemme know!

**Comment by BrentOzar** [comment]
Woohoo! Perfect, I can do that. Thanks man!
