### ISSUE TITLE
sp_BlitzCache: change priority of "Plan Cache Information" warning when most of the plan cache is new

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2052]
**Is your feature request related to a problem? Please describe.**
Priority 254 "Plan Cache Information" shows what percentage of the plans in the cache were generated recently. If they have a mostly unparameterized plan cache, it'd be cool to bubble that up to priority 1 if, say, 75% of their plan cache was generated in the last day.

**Comment by SakariForsberg** [comment]
Hi! It would be a good idea to make it configurable same way than 'long running query warning (seconds)'. We have dedicated servers (couple of databases) where 25% would be real high value and maybe needed some inspecting meanwhile our shared server (several score databases) would do almost fine if their percentage is 90%. 75% would be a good default value.

Thank you for the nice kit.

**Comment by BrentOzar** [comment]
@SakariForsberg thanks for the input, but I just made it 75% for now. For a configurable high-priority warning, sp_Blitz is probably a better place.
