### ISSUE TITLE
sp_BlitzIndex: @IgnoreDatabases only works if names are on a single line

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2053]
**Version of the script**
7.5

**What is the current behavior?**
If you have a list of database names with carriage returns (say you're pasting from a query or Excel or something), carriage returns and line breaks prevent database names from matching correctly.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
EXEC sp_BlitzIndex @Mode = 4, @GetAllDatabases = 1, 
@IgnoreDatabases = '
StackOverflow,
StackOverflow2013,
StackOverflow2010
'
```

**What is the expected behavior?**
Carriage returns and line breaks should be removed from input, like:
`SET @IgnoreDatabases = REPLACE(REPLACE(@IgnoreDatabases, CHAR(10), ''), CHAR(13), '');`

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All, probably

**Comment by BrentOzar** [comment]
Good catch! I should have fixed this earlier, doh. Merged into dev, will be in the August release.
