### ISSUE TITLE
sp_Blitz typo in hyperlink

### ISSUE THREAD

**Issue by RichBenner** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2055]
**Version of the script**
Current Dev - 20190417

**What is the current behavior?**
at approx line 2355 on 'alerts disabled' there's a hyperlink given as https://www.BrentOzar.com/go/alerts/ which returns 'page not found'.

To match the other links it should be https://BrentOzar.com/go/alert

**Comment by BrentOzar** [comment]
Awesome, thanks sir! Good catch.
