### ISSUE TITLE
sp_BlitzLock: add ability to log sp_BlitzLock to table / excel friendly format

### ISSUE THREAD

**Issue by visionthroughdesign** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2057]
Do you want to request a feature or report a bug?
Features: Add output parameter for sp_blitzlock to excel format or even @outputtotdatabase like sp_blitz / blitzcache

**Comment by BrentOzar** [comment]
Sure, that totally sounds like a contribution we'd be willing to accept.  To code it, check out the contributing guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

If you don't feel like coding it, no problem - let me know and I can close the issue. (As much as we'd love to build everything for free, open source doesn't mean free consulting & development.)

**Comment by BrentOzar** [comment]
Haven't heard back from you for a few months, so closing.
