### ISSUE TITLE
SqlServerVersions.sql  DataPoint Issue

### ISSUE THREAD

**Issue by sm8680** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2059]
(12, 5626, 'SP2 CU17', 'https://support.microsoft.com/en-us/help/4491540', '2019-04-16', '2020-01-14', '2020-01-14', 'SQL Server 2014', 'Service Pack 2 Cumulative Update 17'),
    (12, 5626, 'SP2 CU16', 'https://support.microsoft.com/en-us/help/4482967', '2019-02-19', '2020-01-14', '2020-01-14', 'SQL Server 2014', 'Service Pack 2 Cumulative Update 16'),

Based on the above data in the overall file.  SP2 CU17 should be MinorVersionNumber 5632 and not MinorVersionNumber 5626.  Which is the MinorVersionNumber for CU16

**Comment by BrentOzar** [comment]
Good catch! Fixed. Going forward you can just submit pull requests along with the issue for this kind of thing.
