### ISSUE TITLE
sp_BlitzFirst - CheckID 40 - Arithmetic overflow error converting expression to data type int.

### ISSUE THREAD

**Issue by rentadba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2060]
**Version of the script**
 sp_BlitzFirst: @Version = '7.5', @VersionDate = '20190427'

**What is the current behavior?**
Getting error when running: EXEC dbo.sp_BlitzFirst @ExpertMode = 1;
Msg 8115, Level 16, State 2, Procedure sp_BlitzFirst, Line 1670 [Batch Start Line 3947]
Arithmetic overflow error converting expression to data type int.

**If the current behavior is a bug, please provide the steps to reproduce.**
EXEC dbo.sp_BlitzFirst @ExpertMode = 1;

**What is the expected behavior?**
At line 1673, there is a "CAST(cntr_value AS INT)". On my system, the value for cntr_value is 2308500000.
The conversion should be made to bigint: CAST(cntr_value AS [bigint]).

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Microsoft SQL Server 2016 (SP2-CU5) (KB4475776) - 13.0.5264.1 (X64) 
Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Datacenter 10.0 <X64>

**Comment by BrentOzar** [comment]
Woohoo! Love that 2.3TB RAM, sounds awesome. OK, fixed in the dev branch, and will be in August's release. Thanks!
