### ISSUE TITLE
sp_BlitzCache: Selects that cause writes

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2063]
**Is your feature request related to a problem? Please describe.**
When a query is only doing a select, but writes are registered, it probably did something bad. This is a good way to catch spills (especially pre-DMV data) and spools. 

**Describe the solution you'd like**
Something like [here](https://erikdarlingdata.com/2019/04/selects-that-cause-writes/). 

**Describe alternatives you've considered**
The spills column in newer versions of SQL Server is okay, but doesn't catch all writes.

**Are you ready to build the code for the feature?**
Yes, have some.

**Comment by BrentOzar** [comment]
Makes sense! You wanna go for it? (We'll sponsor the work if you wanna tackle it.)

**Comment by erikdarlingdata** [comment]
Yes, I'll get to this (and all the issues I opened) when I have some downtime. Been bonkers over here lately. I haven't forgotten about them.

**Comment by BrentOzar** [comment]
No worries, just wanted to put it in publicly so people knew where we were at. No rush.

**Comment by BrentOzar** [comment]
Great job! Thanks sir, merging, will be in this month's release, and I'll fix the collector for it too.
