### ISSUE TITLE
Checkdate for spblitzcache out of alignment with everything else (powerbi relationship key)

### ISSUE THREAD

**Issue by ianmanton** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2064]
**Version of the script**
@Version = '7.5', @VersionDate = '20190427';

**What is the current behavior?**
Entries in SPBlitzcache do not record the same checkdate as every other spblitz table - so when the powerbi report is used the relationship finds no match between spblitzcache and the checkdate dimension so shows no results when date filtering is used.

**If the current behavior is a bug, please provide the steps to reproduce.**
Use the power bi report and note absence of entries in intensive query section

**What is the expected behavior?**
Section populated 

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Can't recall - at some point in the past yes

**Comment by BrentOzar** [comment]
OK, cool. Do you want to tackle this? (I don't personally use that feature these days, and I'm booked solid right now, so I can't contribute code on it.) If you don't want to, I totally understand, and we can leave this as a known issue.

**Comment by ianmanton** [comment]
TBH – I did try lol – but I couldn’t work out why it wasn’t working.  I.e. I can only see the checkdate being set at the point of execution so didn’t see why it was changing only for the splblitz execution?

Could just add a new slicer in power bi for the spblitz chkdate version but imagine the drillthrough to querydetails wouldn’t sit very well with that?

**Comment by BrentOzar** [comment]
OK, go ahead and feel free to make whatever changes you want to your Power BI Desktop files and go from there. (We no longer maintain that.)
