### ISSUE TITLE
sp_BlitzIndex - getting partition compression info is very slow on large databases

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2065]
**Is your feature request related to a problem? Please describe.**
The section of code that figures out compression info (that I wrote, ha ha ha perf guy) stalls out pretty hard on large databases. Nothing a couple temp tables can't fix to materialize the interim results.

**Describe the solution you'd like**
IT'S SLOW AND I WANT IT FAST

**Describe alternatives you've considered**
It could be quoted out, or it could only run conditionally based on [some metric]

**Are you ready to build the code for the feature?**
Yes.

**Comment by BrentOzar** [comment]
Makes sense! You wanna go for it? (We'll sponsor the work if you wanna tackle it.)

**Comment by BrentOzar** [comment]
Looks good! Thanks sir!
