### ISSUE TITLE
sp_BlitzWho: Asks for a large memory grant, shows up in BlitzCache for being naughty

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2066]
**Is your feature request related to a problem? Please describe.**
BlitzWho runs a fairly big, complicated select query and returns some big columns (query text, xml), ordered by earliest query start time. As a result, I've seen it ask for 6-7GB memory grants, and then hardly use any.

**Describe the solution you'd like**
Big top, little optimize for trick.

**Describe alternatives you've considered**
Query hints, but the version-branched code doesn't apply to the order by, and it's easier to not have more logic.

**Are you ready to build the code for the feature?**
Y

**Comment by BrentOzar** [comment]
Makes sense! You wanna go for it? (We'll sponsor the work if you wanna tackle it.)

**Comment by erikdarlingdata** [comment]
Can close this if it's being deprecated.
