### ISSUE TITLE
sp_DatabaseRestore - Add compatibility to restore to BLOB URL

### ISSUE THREAD

**Issue by LowlyDBA** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2067]
**Is your feature request related to a problem? Please describe.**
Have sp_DatabaseRestore support [BLOB as a restore destination](https://docs.microsoft.com/en-us/sql/relational-databases/tutorial-use-azure-blob-storage-service-with-sql-server-2016?view=sql-server-2017#4----restore-database-to-virtual-machine-from-url). Currently the only blocker for this is the "fixing" logic that auto-appends `\` to locations which will obviously break the URL location. I.e. if I set the restore destination as a BLOB, the restore command comes out as:

```sql
MOVE 'MyDatabase' TO 'https://MyStorage.blob.core.windows.net/mycontainer\mydb.mdf',
```

**Describe the solution you'd like**
Adding this logic to the path fixing would work:
```sql
IF (SELECT RIGHT(@MoveDataDrive, 1)) <> '/' AND @MoveDataDrive LIKE '%/%' --Has to end in a '/'
BEGIN
	IF @Execute = 'Y' OR @Debug = 1 RAISERROR('Fixing @MoveDataDrive to add a "/"', 0, 1) WITH NOWAIT;
	SET @MoveDataDrive += N'/';
END;
ELSE IF (SELECT RIGHT(@MoveDataDrive, 1)) <> '\'  AND @MoveDataDrive LIKE '%\%'--Has to end in a '\'
BEGIN
	IF @Execute = 'Y' OR @Debug = 1 RAISERROR('Fixing @MoveDataDrive to add a "\"', 0, 1) WITH NOWAIT;
	SET @MoveDataDrive += N'\';
END;
```

**Describe alternatives you've considered**
Could also be done as a dedicated parameter, but that seems unnecessary. Charindex might be a healthier alternative to check for slash style as well. 

**Are you ready to build the code for the feature?**
Happy to make a PR with the change implemented in all necessary locations.

**Comment by BrentOzar** [comment]
Haven't heard any complaints - seems like this would be a good one. Do you still want to code it? If not, let me know and I'll close this, either way. Thanks!

**Comment by BrentOzar** [comment]
Great work! Merged into the dev branch, and this will be in the August release with you in the credits. Thanks!
