### ISSUE TITLE
sp_BlitzQueryStore: performance on large stores is terrible

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2068]
I'm working around the usual format a bit because this is a very specific problem.

When Query Store is large (like around 100MB or so), BQS performance tanks on the initial data grabs. There are two issues with them:

1. Validating that the query plan column is not null takes minutes sometimes
2. A performance spool gets added for ???reasons???

It's easier to deal with the possibility of a NULL plan later (if that's even a thing?). The difference in execution time when those things are accounted for is 12 minutes > 1:30.

**Comment by BrentOzar** [comment]
Makes sense! You wanna go for it? (We'll sponsor the work if you wanna tackle it.)

**Comment by erikdarlingdata** [comment]
This should be closed. The fix I had ended up not working in all cases, and coming up with a fix to work in all cases is impossible because of the way data gets read from the in memory tables when query store is active. Detailed a bit [here](https://erikdarlingdata.com/2019/08/for-better-query-store-adoption-make-querying-it-easier/).
