### ISSUE TITLE
New CheckID 225 "Some Databases has more than one log files."

### ISSUE THREAD

**Issue by ktaranov** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2069]
**Describe the solution you'd like**
Add new CheckID 225 **Some Databases has more than one log files. Database need only ONE transaction log file. See ...**

Detailed explanation from Kimberly Tripp https://www.sqlskills.com/blogs/kimberly/8-steps-to-better-transaction-log-throughput/ :

> Create only ONE transaction log file. Even though you can create multiple transaction log files, you only need one… SQL Server DOES not “stripe” across multiple transaction log files. Instead, SQL Server uses the transaction log files sequentially. While this might sound bad – it’s not. If you want to get better performance out of the transaction log, place it on faster disks and/or a more performant disk (RAID) configuration. You could place the transaction log on a RAID 0 array but you’ll likely want fault tolerance as well as performance. Isolation, as per number 1 is a good start but if you also need increased capacity then using hardware based RAID to combine disks for both better performance and redundancy is your next choice. See 4.

**Are you ready to build the code for the feature?**
I am ready to build this feature.

**Comment by BrentOzar** [comment]
It's already covered by check 170, multiple logs on the same drive letter.

There's a valid use case for multiple logs on different drives - a main log file with a fixed size on a smaller drive, and an "emergency vent valve" log file at 1MB with autogrowth on in the event of an emergency.
