### ISSUE TITLE
sp_BlitzFirst and sp_BlitzCache - Sometimes fail when there are readable secondary databases on the server

### ISSUE THREAD

**Issue by Adedba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2072]
**Version of the script**
sp_BlitzFirst - Version = '7.6', VersionDate = '20190702';
sp_BlitzCache - Version = '7.6', VersionDate = '20190702';

**What is the current behavior?**
When I run the BlitzFirst collection to log output to tables using the following command on a Read intent secondary server it can error.

Command: 

EXEC sp_BlitzFirst 
  @OutputDatabaseName = 'DBA', 
  @OutputSchemaName = 'dbo', 
  @OutputTableName = 'BlitzFirst',
  @OutputTableNameFileStats = 'BlitzFirst_FileStats',
  @OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
  @OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
  @OutputTableNameBlitzCache = 'BlitzCache';

Error:
Msg 978, Level 14, State 1, Line 45
The target database ('ReadableDB') is in an availability group and is currently accessible for connections when the application intent is set to read only. For more information about application intent, see SQL Server Books Online.

**If the current behavior is a bug, please provide the steps to reproduce.**
Whilst a query is running against a read intent secondary database either with a request or waiting task run sp_BlitzFirst or sp_BlitzCache, an easier way to demonstrate manually just using the DMVs is to: 

- Set an AG to have a Read-intent secondary (note that the read only route URLs and required config need to be present) 

- Using SSMS connect to the read intent secondary but in the connection window expand options > Additional Connection Parameters then enter "ApplicationIntent= ReadOnly"

- Open a new query window and use a database of your choice from the AG you set to Read intent in step 1

- Run a query relatively long running query in this window (3-5 seconds) which allows enough time to hop onto another query window and run the following query: 

	
SELECT *
FROM  sys.dm_exec_requests r 
CROSS APPLY sys.dm_exec_query_plan(r.plan_handle) pl
WHERE r.database_id IN (SELECT DB_ID('YourReadableDBname'));

As long as the query is still running in the other window you should see an error similar to this: 
Msg 978, Level 14, State 1, Line 45
The target database ('ReadableDB') is in an availability group and is currently accessible for connections when the application intent is set to read only. For more information about application intent, see SQL Server Books Online.

**What is the expected behavior?**
To skip read intent databases to avoid the error occurring.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2012 , possibly higher versions but do not have any servers with this config in place to test on higher versions.

**Comment by BrentOzar** [comment]
Great bug report! Nice job. (For folks reading here and not Slack, Adrian's working on tweaks to the code.)

**Comment by BrentOzar** [comment]
Looks good! Merged into the dev branch, and it'll be in the August release and I'll credit you in the release notes. Thanks!

**Comment by Reacherous** [comment]
New to the Blitzstash of scripts...  Does this mean when I run sp_blitzcache I can expect it to pick up traffic on the secondary?   We have some reporting and downstreams using readonly intent flag....  I'd like to determine if their traffic is causing issues....  How to run sp_blitzcache on secondary?

**Comment by BrentOzar** [comment]
@Reacherous for support questions, hit the readme on where to ask interactive questions in the community Slack.

For a quick answer, though, if you want data from a server, you'll need to connect to that server. SQL Server doesn't have cross-server DMVs.

**Comment by Reacherous** [comment]
Thank you sir.  Your work is quite amazing.
