### ISSUE TITLE
sp_AllNightLog uses unsupported parameter value for sp DatabaseBackup call

### ISSUE THREAD

**Issue by brokenthorn** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2074]
Olla Hallengren DatabaseBackup Version: 2019-06-14 00:05:34

`EXEC sp_AllNightLog @Backup = 1, @Debug=1`

prints:

```
Msg 50000, Level 16, State 1, Procedure master.dbo.DatabaseBackup, Line 1176 [Batch Start Line 18]
The value for the parameter @ChangeBackupType is not supported.
Value is 'MSDB'.
```

L1183:

```sql
IF @ChangeBackupType NOT IN ('Y','N') OR @ChangeBackupType IS NULL
BEGIN
  SET @ErrorMessage = 'The value for the parameter @ChangeBackupType is not supported.'
  RAISERROR('%s',16,1,@ErrorMessage) WITH NOWAIT
  SET @Error = @@ERROR
  RAISERROR(@EmptyLine,10,1) WITH NOWAIT
END
```

Secondary issue is that the backup jobs don't fail because DatabaseBackup returns null for the error code when it fails above and `sp_AllNightLog @Backup = 1` treats that as success.

**Comment by BrentOzar** [comment]
Yep, that's here: https://github.com/olahallengren/sql-server-maintenance-solution/pull/13

**Comment by brokenthorn** [comment]
My bad. I feel stupid. I should have read the description more carefully.
