### ISSUE TITLE
sp_Blitz causing MSSQLSERVER & SQLSERVERAENT services  to stop

### ISSUE THREAD

**Issue by ssodba2** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2075]
Version 7.6

Run:
EXEC sp_Blitz @CheckUserDatabaseObjects = 1, @CheckServerInfo = 1;

Result:
RegOpenKeyEx() returned error 2, 'The system cannot find the file specified.'
Msg 22001, Level 1, State 1
Warning: Null value is eliminated by an aggregate or other SET operation.
Msg 64, Level 20, State 0, Line 0
A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - The specified network name is no longer available.)

Scenario:
I have 9 instances of SQL Server 2012 each running on the own virtual server. I run your first responder script as above every morning to check the health of my instance & databases. 
This runs fine of 8 of the servers. However, starting on Monday (15-Jul-19) at 9:06 AM, one instance crashes when it is run (That was version 7.5). Restarted the server, reran script and it worked. This issue reoccurred today. Had to restart the server, reran script and it worked. Downloaded version 7.6. Reran script and the instance crashed again. Restarted the server, reran script and it worked. The error message received is shown above.  Any ideas on the root cause? You feedback is appreciated.

Running SQL Server version currently being used is:  11.0.3128.0
Operating System version is:  Microsoft Windows NT 6.2 (9200)

So far there are no issues with my other 8 SQL Server Instances.

**Comment by BrentOzar** [comment]
My guess - and this is just a guess - is that you're hitting corruption issues. I'd check your SQL Server logs.

**Comment by BrentOzar** [comment]
Haven't heard back from you, closing. If you have additional questions just let us know, though.
