### ISSUE TITLE
sp_Databaserestore doesn't restore diffs by default

### ISSUE THREAD

**Issue by gdoddsy** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2077]
If the @BackupPathDiff is specified in sp_DatabaseRestore then it should restore the diff backups unless RestoreDiff is specifically set to 0.

**Comment by BrentOzar** [comment]
Ooo, interesting. So are you saying it doesn’t work when RestoreDiff is set to 1 and the diff path is populated? Can you be more specific about the scenario where it’s not working or giving you an error? Thanks!

**Comment by gdoddsy** [comment]
Nope. It works fine when you do that, everything works as designed.

I'm questioning the design. If I specify the Full and Log paths then it automatically restores the full and log. If I specify the Full and Diff and Log paths then it still only restores the Full and Log, not the Diff.

I've created a pull request (I think correctly) on how I think it should work: If you go to the effort of specifying a differential backup path then it should restore the differential, unless you specifically say @RestoreDiff = 0.

**Comment by BrentOzar** [comment]
Gotcha. If we were designing a new script from scratch, I'd be totally open to this, but once the script is out in the wild, I'm not a big fan of changing its behavior. Thousands of people download these scripts every month, and I don't want to change the way they work by default unless there's a really, really compelling reason - as in, the way they work is broken.

It's nothing against your request - it's a fair idea - but it's not the way the scripts currently work, and changing it runs the risk of breaking someone's existing process. For example, if someone's restoring to fix a corruption issue, then they need to only restore the full and the logs. It would be bad if we restored the diffs (and thereby included the corrupt data pages.)
