### ISSUE TITLE
sp_Blitz - Plan Guides and QUOTED_IDENTIFIER OFF

### ISSUE THREAD

**Issue by howarthcd** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2078]
**Version of the script**
@Version = '7.6', @VersionDate = '20190702'

**What is the current behavior?**
If a plan guide's query text uses quoted identifiers then the 'Plan Guides Failing' is returned by sp_Blitz even if the plan guide's query text is valid with QUOTED_IDENTIFIER set to ON.

It seems that plan guides are being validated as if QUOTED_IDENTIFIER were set to OFF. 

**If the current behavior is a bug, please provide the steps to reproduce.**

CREATE DATABASE TestDB
GO
USE TestDB
GO
IF EXISTS (SELECT 1 FROM sys.plan_guides WHERE name = 'sp_Blitz Test Plan Guide')
    EXEC sp_control_plan_guide N'DROP',  N'sp_Blitz Test Plan Guide';
GO
EXEC sp_create_plan_guide 
        @name = N'sp_Blitz Test Plan Guide',
        @stmt = N'SELECT TOP 1 * FROM "sys"."objects"',
        @type = N'SQL',
        @module_or_batch = NULL,
        @hints = N'OPTION (RECOMPILE)'
GO
-- Validation fails
EXEC sys.sp_MSforeachdb 'USE [?];
			SELECT *
			FROM sys.plan_guides g
				CROSS APPLY fn_validate_plan_guide(g.plan_guide_id)';
GO
-- Validation succeeds
EXEC sys.sp_MSforeachdb 'USE [?];
			SET QUOTED_IDENTIFIER ON;
			SELECT *
			FROM sys.plan_guides g
				CROSS APPLY fn_validate_plan_guide(g.plan_guide_id)';
GO

**What is the expected behavior?**

I would expect the validation to pass when run as part of sp_Blitz.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Able to reproduce the issue on both SQL Server 2008 R2 on Windows 2008 R2 and SQL Server 2017 on Windows Server 2016

**Comment by BrentOzar** [comment]
Yeah, after some investigation, looks like sp_msforeachdb isn't honoring the database's quoted_identifier setting:

/* Check your current session settings: */
if ((256 & @@options) = 256) print 'quoted_identifier is on' else print 'quoted_identifier is off';

/* Check each database's settings: */
SELECT name, is_quoted_identifier_on FROM sys.databases;

/* Check how sp_msforeachdb works: */
sp_msforeachdb 'USE [?]; if ((256 & @@options) = 256) SELECT ''?'' AS db_name, ''on'' AS quoted_identifier else SELECT ''?'' AS db_name, ''off'' AS quoted_identifier;'

Results:

<img width="779" alt="Screen Shot 2019-08-18 at 8 14 36 AM" src="https://user-images.githubusercontent.com/245462/63226590-578fbd00-c190-11e9-8c06-4de6928f0c53.png">

**Comment by BrentOzar** [comment]
The section of the code involved is here:

```
								EXEC dbo.sp_MSforeachdb 'USE [?];
			SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
            INSERT INTO #BlitzResults
			(CheckID,
			DatabaseName,
			Priority,
			FindingsGroup,
			Finding,
			URL,
			Details)
		  SELECT DISTINCT 164,
		  N''?'',
		  20,
		  ''Reliability'',
		  ''Plan Guides Failing'',
		  ''https://BrentOzar.com/go/misguided'',
		  (''The ['' + DB_NAME() + ''] database has plan guides that are no longer valid, so the queries involved may be failing silently.'')
		  FROM [?].sys.plan_guides g CROSS APPLY fn_validate_plan_guide(g.plan_guide_id) OPTION (RECOMPILE)';
							END;
```

If you want to code this fix, doing this right would probably involve looping through the databases, checking their quoted_identifier settings, and then running the right SET QUOTED_IDENTIFIER settings for that particular database. Is that something you want to tackle? (If not, I totally understand - it's beyond something I can do quickly too.)

**Comment by BrentOzar** [comment]
@howarthcd is this something you want to tackle, or should I close it?

**Comment by howarthcd** [comment]
Sorry @BrentOzar , I missed the email notifications in respect of your earlier replies. I'll take a look into it and let you know. Thanks, Chris.

**Comment by BrentOzar** [comment]
@howarthcd it's been a couple of months now, so I'll go ahead and close this. If you want to start working on it actively, you can reopen it and we can go from there. Thanks!
