### ISSUE TITLE
Uninstall (remove) First Responder Kit

### ISSUE THREAD

**Issue by ShawnPOWER** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2080]
It would be awesome to be able to run some SQL in order to remove all items after running Install-All-Scripts. I haven't found this feature in any of the documentation thus far.

**Comment by BrentOzar** [comment]
Sure, that's a neat feature request. If you'd like to code it, go ahead and read the contributing guide in this repo for how to get started. For example, you might call it Uninstall.sql.

**Comment by EmanueleMeazzo** [comment]
I'll code it if @ShawnPOWER doesn't have the time, let me know

**Comment by ShawnPOWER** [comment]
I unfortunately don't have the time at the moment to assist. Thank you @EmanueleMeazzo!

**Comment by BrentOzar** [comment]
Great job, @EmanueleMeazzo! Merged it into the dev branch, and it'll be in the September release with credit to y'all. Thanks!
