### ISSUE TITLE
Set the owner of the database after restore

### ISSUE THREAD

**Issue by gdoddsy** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2081]
**Is your feature request related to a problem? Please describe.**
We always want to set the database owner after a restore, so we'd like to specify the owner as part of the restore script.

**Describe the solution you'd like**
Provide an extra parameter to sp_DatabaseRestore that sends in the desired owner username. After restoring the database, validate that it's actually a user and then set the owner of the restored database to that user.

**Describe alternatives you've considered**
We currently run this as an additional step in the job, but for manual restores it's always forgotten until weeks (months) later.

**Are you ready to build the code for the feature?**
I've pretty much got this going already, just need to add in some checking that the username passed in is an actual user.

**Comment by BrentOzar** [comment]
Makes sense! I like it. Go for it!

**Comment by gdoddsy** [comment]
@BrentOzar - do you have a suggestion for how to validate the user exists and what to do if they don't?

I'm currently thinking something like:
```

IF @DatabaseOwner IS NOT NULL
	BEGIN
		IF EXISTS (SELECT * FROM master.dbo.syslogins WHERE syslogins.loginname = @DatabaseOwner)
		BEGIN
			SET @sql = N'ALTER AUTHORIZATION ON DATABASE::[' + @RestoreDatabaseName + '] TO [' + @databaseowner + ']';

				IF @Debug = 1 OR @Execute = 'N'
				BEGIN
					IF @sql IS NULL PRINT '@sql is NULL for Set Database Owner';
					PRINT @sql;
				END;

			IF @Debug IN (0, 1) AND @Execute = 'Y'
				EXECUTE (@sql);
		END
		ELSE
		BEGIN
			PRINT @DatabaseOwner ' is not a valid Login. Database Owner not set.'
		END
	END;

```

**Comment by BrentOzar** [comment]
No, no opinion here (out on vacation this month) - but other folks might have an opinion, will let them chime in.

**Comment by gdoddsy** [comment]
Pull request sent through.

**Comment by BrentOzar** [comment]
Good job! I've merged it into the dev branch, and it'll be in the August release, with credit to you in the release notes. Thanks!
