### ISSUE TITLE
Drop Support for SQL Server 2008(R2)

### ISSUE THREAD

**Issue by EmanueleMeazzo** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2083]
Since Microsoft has dropped support for SQL Server 2008, should we drop the requirement for the FirstResponderKit to support it too?
In this way TSQL code from SQL Server 2012+ could be used, which would allow to create a more compact and faster code, e.g.:

- TRY_CONVERT
- IIF
- CONCAT
- FORMAT
- Offset Windowing Functions

What do you think?

**Comment by BrentOzar** [comment]
"More compact and faster code" isn't really a benefit here - it would require rewriting the code to use the newer features, which requires volunteer labor. Same thing with testing - code rewrites introduce the possibility of bugs.

So all I'm seeing here is more work and more bugs - not really a benefit there.

If, during the course of developing something new inside the First Responder Kit, that work can only be done with the newer TSQL, then sure, it might make sense. Until then, I don't really see a compelling argument to rewrite it to support LESS servers, take MORE time, and introduce more bugs.

Is there something I'm missing though? I'm open to ideas.

**Comment by EmanueleMeazzo** [comment]
Indeed, a rewrite would be too much of a hassle and absolutely impractical; what I'm proposing is not a refactoring but a formal drop of the _support requirement_ from the project, i.e. : 

- Changing the Readme
- Any issue regarding SQL 2008 specifically will be dismissed as "not suported"
- Any future development will not be bound by the 2008 constraints

That's it, just saying "guys, we won't guarantee support from now on"
Maybe I'm thinking too much as a software vendor that wants to avoid "legacy tickets" and remove curbs for devs(?)

**Comment by BrentOzar** [comment]
Gotcha - no, given the huge, huge adoption rate of SQL Server 2008, I don't think it makes sense. There are more servers on 2008 and 2008R2 than on 2016 and 2017 *combined*: https://app.spotlightcloud.io/public/collectiveiq
