### ISSUE TITLE
sp_Blitz - improve old compat level warnings

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#209]
Check 62 - Old Compat Level - only warn if it's the oldest compat level that will be deprecated.

**Comment by MikePenguin** [comment]
There is some discrepancy here though. 
I found an odd but really bad situation whereby the master database on a number of instances[ not by managed by me btw ;) ] had their compatibility level changed, so was causing issues. 
When you read the description : https://www.brentozar.com/blitz/old-compatibility-level/
it does say : "This part of our SQL Server sp_Blitz script checks the compatibility_level field for each database in sys.databases and compares it to the compatibility_level of the model database."

But the code is hard coded to 90 , as you say, which doesn't match the message or description on the item. 
I have amended my local copy to use the following , and compare to that so it does show all databases that do not match that of the current SQL Server version, and think this should be reflected in the sp_blitz, or maybe split into two separate errors and warn if any system databases have had their compatibility changed.

	declare @compatlevel tinyint = 90; 
	if @@VERSION like 'Microsoft SQL Server 2008%' select @compatlevel = 100;
	if @@VERSION like 'Microsoft SQL Server 2012%' select @compatlevel = 110;
	if @@VERSION like 'Microsoft SQL Server 2014%' select @compatlevel = 120;
	if @@VERSION like 'Microsoft SQL Server 2016%' select @compatlevel = 130;



[sp_Blitz.sql.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/789674/sp_Blitz.sql.txt)
