### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by petervandivier** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2099]
**Version of the script**
As noted in #2013 , #6 , #2041 sometimes links break. So clearly we need a [new internet](https://en.wikipedia.org/wiki/Project_Xanadu). While we wait on that though, we must toil in the DNS mines to harvest the raw URL ore necessary to feed the ever-hungering Beast. This issue is such toil  

**What is the current behavior?**

I've flagged two (2) links that point to dead targets that can be repaired that the Beast might feed. 

* 🥝 http://sqlblog.com/blogs/paul_white/archive/2013/06/11/hello-operator-my-switch-is-bored.aspx
* :octocat: https://github.com/ktaranov/sqlserver-kit/blob/master/Stored_Procedure/sp_BlitzInMemoryOLTP.sql

**What is the expected behavior?**

Links provided for external resources should link to resources that exist externally. 

* https://www.sql.kiwi/2013/06/hello-operator-my-switch-is-bored.html
* https://github.com/ktaranov/sqlserver-kit/blob/master/Stored_Procedure/dbo.sp_BlitzInMemoryOLTP.sql

**Additional Info**

While [poking around for potential dead links](https://gist.github.com/petervandivier/8220fde5dab0c3bad017d5b9dfefad6a), I noticed a number of other candidates. 

* some are bad hits from the regex I used
* some are 301s
* there is precedent for "placeholder" links for "upcoming" resources

Those links that are defunct though should be repaired or removed so that [there is nothing wrong on the internet](https://xkcd.com/386/)

**Comment by BrentOzar** [comment]
Great job, thanks sir!
