### ISSUE TITLE
duplicate version

### ISSUE THREAD

**Issue by aelmi** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2108]
There are 2 values for 
major = 10 and minor = 1600

10.50.1600. = Server 2008 R2 RTM  RTM
please refer to https://sqlserverbuilds.blogspot.com

So you need to remove the the last linebefore go - line 334
(10, 1600, 'RTM ', '', '2008-08-06', '2014-07-08', '2019-07-09', 'SQL Server 2008', 'RTM ')

**Comment by BrentOzar** [comment]
Hmm, I don't see what you see? Here's what's in the file currently:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/SqlServerVersions.sql

```
    (10, 1763, 'RTM CU1', 'https://support.microsoft.com/en-us/help/956717', '2008-09-22', '2014-07-08', '2019-07-09', 'SQL Server 2008', 'RTM Cumulative Update 1'),
    (10, 1600, 'RTM ', '', '2008-08-06', '2014-07-08', '2019-07-09', 'SQL Server 2008', 'RTM ')

```
Can you be more specific, or include a screenshot? Thanks!

**Comment by BrentOzar** [comment]
Closing this - feel free to reopen it if you've got more details. Thanks!
