### ISSUE TITLE
Reports an error ... missing object sp_DatabaseRestore on first install

### ISSUE THREAD

**Issue by roy-tate** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2110]
**Version of the script**
@Version = '3.7', @VersionDate = '20190826';

**What is the current behavior?**
Reports an error for a procedure CONTAINED in the script!

The module 'sp_AllNightLog' depends on the missing object 'DbTools.dbo.sp_DatabaseRestore'. The module will still be created; however, it cannot run successfully until the object exists.

**If the current behavior is a bug, please provide the steps to reproduce.**
Open File "Install-All-Scripts.sql" int a SQL Query window, press execute button on the toolbar.

**What is the expected behavior?**
I did not expect an error regarding sp_DatabaseRestore, which is included in the package.  This is error is presented to first-time users, who are the least familiar with the tool suite.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
This error has been present for at least a year.

**Solution**
Open file "Merge Blitz.ps1".

Add the following sort command (comment is optional) between the Where-Object and ForEach-Object lines in all 3 sections of file concatenation.
```
# use descending sort to place sp_AllNightLog after sp_DatabaseRestore
Sort-Object -Property Name -Descending |
```

I tested the code change locally.  I just don't have time to push a change right now.

**Comment by BrentOzar** [comment]
OK, whenever you've got time to push a change, feel free to reopen the issue. Thanks!
