### ISSUE TITLE
Version Check on sp_BlitzQueryStore Failing.

### ISSUE THREAD

**Issue by paulmchenry** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2124]
**Version of the script**
Version = '3.8',
VersionDate = '20190922';

**What is the current behavior?**
Running against Azure SQL DB compatibility level 140 returns an error saying it isn't supported, which is contrary to what is in the notes.

**If the current behavior is a bug, please provide the steps to reproduce.**
Run the script against Azure SQL DB.

**What is the expected behavior?**
For compatibility level 130 + the script should execute as normal and not return the error.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Azure SQL DB. All versions (or at least anything compatibility level 130 +, as that's where the error appears and where the check comes in)

This bug appears to be due to using the `SELECT SERVERPROPERTY ('EDITION')) <> 'SQL Azure'`  comparison. `SERVERPROPERTY` is returned as a `sql_variant` data type and this causes the comparison to fail. This can be resolved by converting the `SERVERPROPERTY` to its base data type before performing the comparison.

**Comment by BrentOzar** [comment]
Great, thanks Paul! I've merged it into the dev branch, and it'll be in the October release, and I'll credit you in the release notes. Have a good week!

**Comment by paulmchenry** [comment]
Thanks, Brent, you too!
