### ISSUE TITLE
sp_DatabaseRestore - Missing parameter for buffercount, maxtransfersize and blocksize

### ISSUE THREAD

**Issue by fvanderhaegen** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2127]
Version: 7.8
VersionDate: 20190922

There are no parameters in stored procedure to set maxtransfersize, buffercount and blocksize.

**Comment by BrentOzar** [comment]
You don’t set that on restore, do you? Thought those were inherited from the backup.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by BrentOzar** [comment]
OK, great! Here's the difference:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/compare/dev...fvanderhaegen:issue_2127/fvanderhaegen

There appears to be an unrelated change in this line:

`	if @DiffLastLSN is null	set @DiffLastLsn=@FullLastLSN
`
Can you either remove that out, or explain why you want to add that? Thanks!

**Comment by fvanderhaegen** [comment]
I removed the line. Don't know how it came there.

**Comment by BrentOzar** [comment]
Perfect, thanks! I've merged it into the dev branch, and it'll be in the October release, and we'll credit you in the release notes. Have a great week!
