### ISSUE TITLE
sp_blitzindex new parameter , list of columns

### ISSUE THREAD

**Issue by heliolino** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2128]
**Is your feature request related to a problem? Please describe.**

It would be great if the proc sp_blitzindex could filter based on a list of columns  
and generate only the indexes that match the column list 

**Describe the solution you'd like**

instead of generating the entire list of indexes of a certain table , if one new parameter , like 
@columnList , it return only the indexes with the columns mentioned 

**Describe alternatives you've considered**

Unfortunately the sp_blitzindex cannot project to a temporary table because the proc cannot be nested twice 

it´s not possible to execute the following , for example: 

insert into #IndexResults
exec sp_blitzindex @DatabaseName='VATCOPY', @BringThePain = 1 ,@TableName = 'transaction'

**Are you ready to build the code for the feature?**
As much as we'd love to build everything that everyone wants for free, we need your help. Open source is built with your help and code. Are you ready to commit time to this project? Have you got existing code you can help contribute to solve the problem?

here is the script i have adapt from internet , but the script build the index adding all columns as part of composite index and not separating the columns that should be in the include clause

-- Get all existing indexes, but NOT the primary keys
DECLARE cIX CURSOR FOR
    SELECT distinct OBJECT_NAME(SI.Object_ID), SI.Object_ID, SI.Name, SI.Index_ID
        FROM Sys.Indexes SI 
            LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC 
			ON SI.Name = TC.CONSTRAINT_NAME 
			AND OBJECT_NAME(SI.Object_ID) = TC.TABLE_NAME
			Inner join sys.index_columns ic 
			ON  SI.object_id = ic.object_id 
			and SI.index_id = ic.index_id 
			INNER JOIN sys.columns col 
			ON ic.object_id = col.object_id 
			and ic.column_id = col.column_id 
        WHERE TC.CONSTRAINT_NAME IS NULL
            AND OBJECTPROPERTY(SI.Object_ID, 'IsUserTable') = 1
			AND OBJECT_NAME(SI.Object_ID) = '<table_name>'  ------ add table name here 
			AND col.name in ('<column_A>','column_B','column_C') --- add column names here 
        --ORDER BY OBJECT_NAME(SI.Object_ID), SI.Index_ID

DECLARE @IxTable SYSNAME
DECLARE @IxTableID INT
DECLARE @IxName SYSNAME
DECLARE @IxID INT

-- Loop through all indexes
OPEN cIX
FETCH NEXT FROM cIX INTO @IxTable, @IxTableID, @IxName, @IxID
WHILE (@@FETCH_STATUS = 0)
BEGIN
    DECLARE @IXSQL NVARCHAR(4000) SET @IXSQL = ''
    SET @IXSQL = 'CREATE '

    -- Check if the index is unique
    IF (INDEXPROPERTY(@IxTableID, @IxName, 'IsUnique') = 1)
        SET @IXSQL = @IXSQL + 'UNIQUE '
    -- Check if the index is clustered
    IF (INDEXPROPERTY(@IxTableID, @IxName, 'IsClustered') = 1)
        SET @IXSQL = @IXSQL + 'CLUSTERED '

    SET @IXSQL = @IXSQL + 'INDEX ' + @IxName + ' ON ' + @IxTable + '('

    -- Get all columns of the index
    DECLARE cIxColumn CURSOR FOR 
        SELECT SC.Name
        FROM Sys.Index_Columns IC
            JOIN Sys.Columns SC ON IC.Object_ID = SC.Object_ID AND IC.Column_ID = SC.Column_ID
        WHERE IC.Object_ID = @IxTableID AND Index_ID = @IxID
        ORDER BY IC.Index_Column_ID

    DECLARE @IxColumn SYSNAME
    DECLARE @IxFirstColumn BIT SET @IxFirstColumn = 1

    -- Loop throug all columns of the index and append them to the CREATE statement
    OPEN cIxColumn
    FETCH NEXT FROM cIxColumn INTO @IxColumn
    WHILE (@@FETCH_STATUS = 0)
    BEGIN
        IF (@IxFirstColumn = 1)
            SET @IxFirstColumn = 0
        ELSE
            SET @IXSQL = @IXSQL + ', '

        SET @IXSQL = @IXSQL + @IxColumn

        FETCH NEXT FROM cIxColumn INTO @IxColumn
    END
    CLOSE cIxColumn
    DEALLOCATE cIxColumn

    SET @IXSQL = @IXSQL + ')'
    -- Print out the CREATE statement for the index
    IF @IXSQL != '' 
	BEGIN 
	 PRINT @IXSQL 
	END

    FETCH NEXT FROM cIX INTO @IxTable, @IxTableID, @IxName, @IxID
END

CLOSE cIX
DEALLOCATE cIX

**Comment by BrentOzar** [comment]
Interesting. Can you tell me a little more about the use case - a scenario where you only care about a specific column?

**Comment by BrentOzar** [comment]
I didn't hear back from you, so I'll close this - but if you have time, feel free to add more details and I can reopen it.

**Comment by heliolino** [comment]
Sorry @BrentOzar for the late reply,

I can't say how useful sp_blitzIndex is.
Especially when you start taking care of an application already in place.
Then you discover large large tables with all the bizarre data types and index zones.

Not only that, there are materialized views with schema binding and of course indexes over them. 

Now, can you imagine the schema change on this table?

Dropping views, indexes, changing table then create everything back

To be clear, sp_blitzindex is also useful for creating all DDL indexes and it would be very handy if the proc could accept an argument like a list of column names , ex: @columList = 'columnA,columnB'
