### ISSUE TITLE
@StopAt For Full Backup Split Across Multiple Files

### ISSUE THREAD

**Issue by kenjmartinii** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2132]
**Version of the script**
7.8 
20190922

**What is the current behavior?**

Execute sp_DatabaseRestore to restore a date-specific FULL backup split across eight FULL backup files for a single database. Regardless of the @StopAt value passed in the procedure will always restore the latest FULL backup it can find for the database.

**If the current behavior is a bug, please provide the steps to reproduce.**

- Backup a single database using Ola's dbo.DatabaseBackup stored procedure, set @NumberOfFiles = 8
- Assume the backup date reflects 20190924032502
- A few days pass and more FULL backups are automatically generated as previously mentioned spreading a single FULL backup across eight files, the latest one being 20190926032502
- Issue a restore of the database in question via the following code setting @StopAt to 20190924032502 since you don't want the latest backup to be restored:

```sql
EXEC dbo.sp_DatabaseRestore 
@Database = 'someDatabase', 
@BackupPathFull = '\\somePath\someInstance\someDatabase\FULL\',  
@RunRecovery = 1,
@MoveFiles = 1,
@MoveDataDrive = 'T:\',
@MoveLogDrive = 'U:\',
@TestRestore = 0, 
@RunCheckDB = 0,
@ExistingDBAction = 1, 
@Debug = 1,
@Execute = 'Y',
@DatabaseOwner = 'sa',
@StopAt = '20190924032502'
```
- View debug output, it will find all of the backup files but choose to only restore the most recent

**What is the expected behavior?**

The logic should correctly identify the backup to be restored based upon the value for @StopAt even if the FULL backup is split across multiple files. It should also work regardless of backup type, however, my use case is specifically for FULL backups.

Digging into this and I can clearly see what is happening on [line 556](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_DatabaseRestore.sql#L556)

```sql
(@StopAt IS NULL OR REPLACE(LEFT(RIGHT(BackupFile, 19), 15),'_','') <= @StopAt);
```
It assumes that the backup file name starts 19 characters from the right, however, in the case where multiple backup files are created, an underscore and number is appended to the filename before the file extension to indicate the number of the backup in the set based upon how many files you had the backup split across.

For example, here are the FULL backup filenames I am dealing with:

> someInstance_someDatabase_FULL_20190924_032502_1.bak
> someInstance_someDatabase_FULL_20190924_032502_2.bak
> someInstance_someDatabase_FULL_20190924_032502_3.bak
> someInstance_someDatabase_FULL_20190924_032502_4.bak
> someInstance_someDatabase_FULL_20190924_032502_5.bak
> someInstance_someDatabase_FULL_20190924_032502_6.bak
> someInstance_someDatabase_FULL_20190924_032502_7.bak
> someInstance_someDatabase_FULL_20190924_032502_8.bak

Based upon the filtering logic mentioned above, it will take this file name and spit out the following, note it is removing the underscore immediately prior to the backup file number instead of the underscore between YYYYMMDD and hhmmss. This will result in wonky dates compared to what is expected to be passed in for @StopAt:

> 1909240325021
> 1909240325022
> 1909240325023
> 1909240325024
> 1909240325025
> 1909240325026
> 1909240325027
> 1909240325028

To get around this (quick and dirty) I successfully used the following code to cleanup the file names if the FULL backup was split across multiple files. It first finds the occurrence of an underscore and then a numeric value followed by .bak. When that string is found it is replaced with nothing, from there I then take the 19 RIGHT characters of the remaining string and end up with the correct filename which can be correctly filtered upon via @StopAt. 

```sql
REPLACE(LEFT(RIGHT(STUFF(BackupFile, PATINDEX('%_[0-9].bak', BackupFile),2, ''), 19), 15),'_','')
```

Quick and dirty test script based upon the code with sp_DatabaseRestore:

```sql
DECLARE @StopAt nvarchar(14) = '20190924032502'

DECLARE @FileListSimple TABLE (
    BackupFile NVARCHAR(255) NOT NULL, 
    depth int NOT NULL, 
    [file] int NOT NULL
);

DECLARE @FileList TABLE (
    BackupFile NVARCHAR(255) NULL
);

INSERT INTO @FileListSimple
EXEC master.sys.xp_dirtree '\\somePath\someInstance\someDatabase\FULL\', 1, 1

INSERT @FileList (BackupFile) SELECT BackupFile FROM @FileListSimple;
SELECT * FROM @FileListSimple

SELECT REPLACE(LEFT(RIGHT(BackupFile, 19), 15),'_','') AS [bad] --yuckos :(
,STUFF(BackupFile, PATINDEX('%_[0-9].bak', BackupFile),2, '') [almost!] --check to make sure the underscore and file number before .bak is stripped out
,REPLACE(LEFT(RIGHT(STUFF(BackupFile, PATINDEX('%_[0-9].bak', BackupFile),2, ''), 19), 15),'_','') --huzzah! success!
FROM @FileList
WHERE BackupFile LIKE N'%.bak'
        AND
        BackupFile LIKE N'%' + 'someDatabase' + N'%'
	    AND
	    (@StopAt IS NULL OR REPLACE(LEFT(RIGHT(STUFF(BackupFile, PATINDEX('%_[0-9].bak', BackupFile),2, ''), 19), 15),'_','') <= @StopAt);
```

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

No clue if this previously worked on older versions

> Microsoft SQL Server 2017 (RTM-CU16) (KB4508218) - 14.0.3223.3 (X64)   Jul 12 2019 17:43:08   
> Copyright (C) 2017 Microsoft Corporation  
> Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

**Comment by kenjmartinii** [comment]
Realized my proposed fix will break for databases backed-up to a single file.

After some trial and error and black magic, I found this to work. Basically for databases without multiple backup files, use the existing filter. For databases with multiple backups, use my proposed filter.

```sql
(@StopAt IS NULL OR (CASE 
		WHEN PATINDEX('%_[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]_[0-9][0-9][0-9][0-9][0-9][0-9].bak', BackupFile) = 0 THEN REPLACE(LEFT(RIGHT(STUFF(BackupFile, PATINDEX('%_[0-9].bak', BackupFile),2, ''), 19), 15),'_','')
		ELSE REPLACE(LEFT(RIGHT(BackupFile, 19), 15),'_','') 
		END) <= @StopAt)
```

**Comment by BrentOzar** [comment]
OK, cool! Here's the contributing guide for how to create a pull request with your proposed changes:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

Thanks!

**Comment by BrentOzar** [comment]
@kenjmartinii I haven't heard back from you - did you want to move forward with contributing the code? If not I can close this - let me know either way. Thanks!

**Comment by kenjmartinii** [comment]
I could definitely give it a stab, just not right now. Early November would be the earliest. If someone else wants to pick it up that would be cool as well!

**Comment by BrentOzar** [comment]
OK, cool - I'm going to go ahead and close this. Whenever you're ready to give 'er a shot, feel free to reopen it as you work. Read the contributing guide for more info. Thanks!
