### ISSUE TITLE
@LogMessageCheckDate parameter ingnored when logging messages.

### ISSUE THREAD

**Issue by planetmatt** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2135]
**Version of the script**
7.8

**What is the current behavior?**
When logging messages with sp_BlitzFirst, passing in any value to the @LogMessageCheckDate parameter is ignored and the current datetime used instead.

**If the current behavior is a bug, please provide the steps to reproduce.**

EXEC dbo.sp_BlitzFirst 
	@LogMessage = 'this is a test',
	@LogMessageFindingsGroup = 'bug testing',
	@LogMessageFinding = 'Logged by me',
	@LogMessageCheckDate = '2010-01-01 00:00:00'

Should add a message dated Jan 1st 2010.  It does not. It logs a message for the date that the script executes. 

![BlitzFristMessageDateBug](https://user-images.githubusercontent.com/8879443/65949389-0aac3100-e434-11e9-86f0-2bb48d89baa3.png)

**What is the expected behavior?**

The message should log and record the value passed to @LogMessageCheckDate in the CheckDate column in the dbo.BlitzFirst table. 

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Microsoft SQL Server 2016 (SP2-CU3) (KB4458871) - 13.0.5216.0 (X64)   Sep 13 2018 22:16:01   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

Both versions 7.7 and 7.8 display the same behavior.

**Comment by BrentOzar** [comment]
Great catch, and thanks for the detailed bug report! I've fixed it in the dev branch, and it'll be in the October release, and I'll credit you in the release notes. Have a good week!
