### ISSUE TITLE
BlitzQueryStore Azure QS Check Failing due to incorrect result from DB_ID

### ISSUE THREAD

**Issue by paulmchenry** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2136]
**Version of the script**
Version = '3.8', 
VersionDate = '20190922';

**What is the current behavior?**
Here is the relevant piece of code:
```/*Does it have Query Store enabled?*/
RAISERROR('Making sure [%s] has Query Store enabled', 0, 1, @DatabaseName) WITH NOWAIT;
IF 	
	((DB_ID(@DatabaseName)) IS NOT NULL AND @DatabaseName <> '')
AND		
	(   SELECT DB_NAME(d.database_id)
		FROM sys.databases AS d
		WHERE d.is_query_store_on = 1
		AND d.user_access_desc='MULTI_USER'
		AND d.state_desc = 'ONLINE'
		AND DB_NAME(d.database_id) = @DatabaseName ) IS NULL
BEGIN
	RAISERROR('The @DatabaseName you specified ([%s]) does not have the Query Store enabled. Please check the name or settings, and try again.', 0, 1, @DatabaseName) WITH	NOWAIT;
	RETURN;
END;
```

Currently when checking if query store is enabled, `sp_blitzquerystore` compares the `database_id` value from `sys.databases` against the result returned from the `DB_NAME` function. The issue with this is that in Azure SQL DB, the database IDs returned using functions do not always match up with those in `sys.databases`. This is documented [here](https://docs.microsoft.com/en-us/sql/t-sql/functions/db-id-transact-sql?view=sql-server-2017).

I specifically encountered this when using a readable secondary as part of an availability group.

**If the current behavior is a bug, please provide the steps to reproduce.**
Set up a database as part of an Azure Availability group and install `sp_blitzquerystore` then try to run it on the secondary. 

This will likely fail with the error that query store is not enabled. Technically you could argue that this would be accurate, as it's a secondary and QS isn't enabled for the secondary itself, however, if you query sys.databases, as far as it's concerned, QS is enabled, meaning that the error is being returned erroneously. I would also expect that for most people using this it would be more desirable to be able to run the script on the secondary to query the results from the primary, rather than just not be able to run it at all on the secondary.

The reason for the failure can be confirmed by looking at the database IDs returned using `DB_ID` and comparing against those in `sys.databases` - the ID in `sys.databases` won't match, therefore the name being used for the comparison is incorrect.

**What is the expected behavior?**
The database names/IDs being compared should match up. Or in my case, I was hoping to be able to run the script on the secondary server to look at the stats from the primary copy of the database which has query store enabled.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Azure SQL DB.

**Comment by BrentOzar** [comment]
Hi! Thanks for the issue and the code. I left some questions on a code review:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/2137

Thanks!

**Comment by BrentOzar** [comment]
Great job! I really appreciate your work on this. I merged it into the dev branch, it'll be in the Oct release, and I'll credit you in the release notes. I'm making a note of that # issue to get it into the contributing guide. Thanks!
