### ISSUE TITLE
sp_DatabaseRestore does no generate the MOVE clause if physical file names differ from the database name

### ISSUE THREAD

**Issue by jesusnac** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2140]
**Version of the script**

7.8,  (20190922)

**What is the current behavior?**

Does not generate any string for the @MoveOption when restoring a database from a different source database backup and the database backup physical files does not match with the source database name.

**If the current behavior is a bug, please provide the steps to reproduce.**

CREATE DATABASE [MySourceDatabase]
 ON  PRIMARY 
( NAME = N'Visionblue_dat', FILENAME = N'F:\Data\OLDFILEDATA.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 2048KB )
 LOG ON 
( NAME = N'Visionblue_log', FILENAME = N'F:\Log\OTHERDATA_LOG.ldf' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 512KB )
GO

....[BACKUP DATABASE using sp_DatabaseBackup ]....

EXEC dbo.sp_DatabaseRestore 
@Database = N'MySourceDatabase',
@RestoreDatabaseName = N'OtherDatabase',
@BackupPathFull = N'F:\Data\MyInstance\MySourceDatabase\FULL\', 
@ExistingDBAction = 1,
@MoveFiles = 1

**What is the expected behavior?**

Generate a valid physical name for restoring.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

It is version independent

**Comment by BrentOzar** [comment]
OK, cool. Did you want to code the fix? (I don't personally use this proc anymore, so I don't code in it.) If so, here's the contribution guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

**Comment by jesusnac** [comment]
Sure, as soon as I have some time. 

Cheers.

**Comment by BrentOzar** [comment]
It's been a month, so I'm going to go ahead and close this. Nothing personal, just keeping the issues list clean.

If you change your mind and want to work on it, feel free to reopen the issue and leave a note. Thanks.
