### ISSUE TITLE
sp_BlitzBackups - Add check for chain integrity

### ISSUE THREAD

**Issue by digitalohm** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2146]
**Is your feature request related to a problem? Please describe.**
When checking backups, it would be helpful if a check for chain integrity (not sure if that is the term to use here) was intact

**Describe the solution you'd like**
in the secondary output of sp_BlitzBackups we can add a row that flags for possible backup chain issues.  The current query I'm using to check this is below, I'm working on testing what happens when the is_copy_only column is both 1 or 0 (my assumption is that a copy only backup won't matter).  I think that the solution could just check for is_copy_only 0 and the backup paths being different, in the current cases I'm seeing, virtual backups leave a GUID in the physical_device_name column, so perhaps the check will also look for where the physical_device_name paths are different?

SELECT
	bs.database_name AS DatabaseName
	,CASE bs.type
		WHEN 'D' THEN 'Full'
		WHEN 'I' THEN 'Differential'
		WHEN 'L' THEN 'Transaction Log'
	END AS BackupType
	,device_type
	,is_copy_only
	,CAST(DATEDIFF
		(SECOND,bs.backup_start_date,bs.backup_finish_date) 
		AS VARCHAR(4)) + ' ' + 'Seconds' AS TotalTimeTaken
	,bs.backup_start_date AS BackupStartDate
	,CAST(bs.first_lsn AS VARCHAR(50)) AS FirstLSN
	,CAST(bs.last_lsn AS VARCHAR(50)) AS LastLSN
	,bmf.physical_device_name AS PhysicalDeviceName
	,CAST(CAST(bs.backup_size / 1000000 AS INT) AS VARCHAR(14)) 
		+ ' ' + 'MB' AS BackupSize
	,bs.server_name AS ServerName
	,bs.recovery_model AS RecoveryModel
FROM msdb.dbo.backupset AS bs
INNER JOIN msdb.dbo.backupmediafamily AS bmf
	ON bs.media_set_id = bmf.media_set_id
WHERE bs.type IN ('D', 'I') and is_copy_only <> 1
ORDER BY backup_start_date DESC
	,backup_finish_date

**Describe alternatives you've considered**
the only alternative is being sad when sp_DatabaseRestore doesn't work because of missing files or broken chains

**Are you ready to build the code for the feature?**
Yes.  I can start working on this as it's a priority item that we are checking with scripts outside of sp_BlitzBackups since it has recently been a problem in the field.

**Comment by BrentOzar** [comment]
It's been a month, so I'm going to go ahead and close this. Nothing personal, just keeping the issues list clean.

If you change your mind and want to work on it, feel free to reopen the issue and leave a note. Thanks.
