### ISSUE TITLE
sp_BlitzLock StartDate filtering by local time (server time)

### ISSUE THREAD

**Issue by digitalohm** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2147]
**Is your feature request related to a problem? Please describe.**
When filtering sp_BlitzLock by a StartDate with time because for example all of a sudden we get a period during the day where a lot of deadlocks are happening, it would be helpful if the time could be converted to local time rather than UTC

**Describe the solution you'd like**
a new column with local time, or when the StartDate option is used convert it?

**Describe alternatives you've considered**
logging the output to a table and converting in the analysis query

**Are you ready to build the code for the feature?**
Yes.  I dont think this should be too hard

**Comment by BrentOzar** [comment]
I went ahead and coded this one to get it in the October release, closing.
