### ISSUE TITLE
sp_blitz reports unused heaps as used

### ISSUE THREAD

**Issue by rsocol** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2149]
sp_blitz version 7.8 (20190922) reports heaps as being used although they have zero user_seeks, user_scans, user_lookups and user_updates. I would expect such heaps to be reported as not used.

**Comment by BrentOzar** [comment]
Looking at the code you sent in - if you head heaps with 0's for user_seeks, user_scans, user_lookups and user_updates, then your fix wouldn't change anything. The NULLIF wouldn't be triggered if the values were zero. Can you tell me more about the user_seeks, user_scans, user_lookups and user_updates that you're seeing in production that led to the problem? Thanks!

**Comment by rsocol** [comment]
I have some rows that have 0, 0, 0, 0 and some rows that have NULL, NULL, NULL, NULL. 
The current code considers that the table is unused only if all values are NULL.
My code changes the 0-s to NULL-s (because I'm using NULLIF, not ISNULL).

**Comment by BrentOzar** [comment]
Ahhhh, I see what you're doing! Great catch. I've merged it into the dev branch, it'll be in the October release, and I'll credit you in the release notes. Thanks!
