### ISSUE TITLE
sp_DataBaseRestore does not create STOP AT = '' when the @StopAt parameter has a value

### ISSUE THREAD

**Issue by steveearle86** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2152]
**Version of the script**
Version = '7.8', VersionDate = '20190922';

**What is the current behavior?**
Given that my backup regime using Ola's scripts is as follows:

_Full_ - daily (12AM)
_Tran_ - Four hourly from 4AM - 8PM (on the hour)
_Log_ - every 15 mins (starting at 5 past the hour)

EXEC dbo.sp_DatabaseRestore 
  @Database = 'AdventureWorks2014', 
  @BackupPathFull = 'C:\Test\Ola\MYINSTANCE\AdventureWorks2014\FULL\', 
  @BackupPathDiff = 'C:\Test\Ola\MYINSTANCE\AdventureWorks2014\DIFF\',
  @BackupPathLog = 'C:\Test\Ola\MYINSTANCE\AdventureWorks2014\LOG\', 
  @RestoreDiff = 1,
  @ContinueLogs = 0, 
  @RunRecovery = 1,
  @StopAt = '20191017071000',
  @Execute = 'N'

prints all the relevant statements, but is missing the final one (the one which restores from the 0720 backup with the STOPAT command)

**If the current behavior is a bug, please provide the steps to reproduce.**
Backup as follows using Ola's scripts

_Full_ - daily (12AM)
_Tran_ - Four hourly from 4AM - 8PM (on the hour)
_Log_ - every 15 mins (starting at 5 past the hour)

Run following command (ensure stopat value is part way through a transaction log backup)

EXEC dbo.sp_DatabaseRestore 
  @Database = 'AdventureWorks2014', 
  @BackupPathFull = 'C:\Test\Ola\MYINSTANCE\AdventureWorks2014\FULL\', 
  @BackupPathDiff = 'C:\Test\Ola\MYINSTANCE\AdventureWorks2014\DIFF\',
  @BackupPathLog = 'C:\Test\Ola\MYINSTANCE\AdventureWorks2014\LOG\', 
  @RestoreDiff = 1,
  @ContinueLogs = 0, 
  @RunRecovery = 1,
  @StopAt = '20191017071000',
  @Execute = 'N'

**What is the expected behavior?**
RESTORE LOG Statement is generated which includes the "STOPAT =" command included as the final RESTORE statement (or executed if @Execute is set to Y)

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2014. This is the first version of the procedure I have used

**Comment by BrentOzar** [comment]
Hi Steve. sp_DatabaseRestore doesn't currently generate the RESTORE LOG command with STOPAT - it just literally stops at that time, making sure that it doesn't restore any logs that would include that time in it.

The behavior you're describing would be a new feature, and it totally makes sense if you want to code it. Want to give it a shot? The contributing guide is here:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

If you don't want to code it, no worries - just let me know and I'll close it (or you can work to recruit folks to code it for you if you want.) Thanks!

**Comment by BrentOzar** [comment]
OK, cool. I'm going to close this for now then - whenever you're ready to tackle it, leave a comment here and we can reopen it. (We just don't keep future-feature-requests left open because you know how it is - life interferes.) Thanks!
