### ISSUE TITLE
sp_DatabaseRestore broken

### ISSUE THREAD

**Issue by huguesgauthiertransit** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2153]
@Version = '7.8', 
@VersionDate = '20190922'

**What is the current behavior?**
since I updated sp_DatabaseRestore to the new version, this script to work anymore.
```
EXEC [dbo].[sp_DatabaseRestore] 
@Database = 'MyDB',
@RestoreDatabaseName = NULL,
@BackupPathFull = 'c:\MyPath\',
@BackupPathLog = NULL,
@MoveFiles = 1,
@MoveDataDrive = @MoveDataDrive,	
@MoveLogDrive =	@MoveLogDrive,
@RunRecovery = 1	
```
Return error..
Msg 50000, Level 16, State 1, Procedure sp_DatabaseRestore, Line 599 [Batch Start Line 0]
Backupfile "MyDB.bak" does not match @Database parameter "MyDB"

from this line..in sp_DatabaseRestore procedure

```
--Ensure we are looking at the expected backup, but only if we expect to restore a FULL backups
IF NOT EXISTS (SELECT * FROM #Headers h WHERE h.DatabaseName = @Database)
BEGIN
    RAISERROR('Backupfile "%s" does not match @Database parameter "%s"', 16, 1, @LastFullBackup, @Database) WITH NOWAIT;
    RETURN;
END;
```

**What is the expected behavior?**
working lol :P

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Sql 2012 enterprise... yes it works in previous version of procedure.

**Comment by BrentOzar** [comment]
That code hasn't changed in 8 months, so can you dig a little deeper? Try checking to make sure that in c:\MyPath, you actually have backups for MyDB. If you're trying to restore a database to a different name, try using the @RestoreDatabaseName parameter.

Any more info we can get from you around debugging it would be helpful. Thanks!

**Comment by huguesgauthiertransit** [comment]
I was using this version before
SET @Version = '6.2';
SET @VersionDate = '20180201';

And in this version there is no validation like this
```
--Ensure we are looking at the expected backup, but only if we expect to restore a FULL backups
IF NOT EXISTS (SELECT * FROM #Headers h WHERE h.DatabaseName = @Database)
BEGIN
    RAISERROR('Backupfile "%s" does not match @Database parameter "%s"', 16, 1, @LastFullBackup, @Database) WITH NOWAIT;
    RETURN;
END;
```

I commented theses lines in the new version, and the restore is back to life.

**Comment by BrentOzar** [comment]
OK, gotcha - that's over a year and a half old. Back then, we weren't checking for things like whether you were restoring the right database.

Like I wrote earlier, try checking to make sure that in c:\MyPath, you actually have backups for MyDB. If you're trying to restore a database to a different name, try using the @RestoreDatabaseName parameter.

Any more info we can get from you around debugging it would be helpful. Thanks!

**Comment by huguesgauthiertransit** [comment]
Yes in c:\MyPath, i have backup MyDB.bak. And the database name is the same. 

The backup MyDB.bak, is comming from outside of our environment. We received this bak file every month, we pay for these backups.

So I copy this backup files in c:\MyPath and execute the script
```
EXEC [dbo].[sp_DatabaseRestore] 
@Database = 'MyDB',
@RestoreDatabaseName = NULL,
@BackupPathFull = 'c:\MyPath\',
@BackupPathLog = NULL,
@MoveFiles = 1,
@MoveDataDrive = @MoveDataDrive,	
@MoveLogDrive =	@MoveLogDrive,
@RunRecovery = 1	
```

and it works only if I comment theses validation lines.
```
--Ensure we are looking at the expected backup, but only if we expect to restore a FULL backups
IF NOT EXISTS (SELECT * FROM #Headers h WHERE h.DatabaseName = @Database)
BEGIN
    RAISERROR('Backupfile "%s" does not match @Database parameter "%s"', 16, 1, @LastFullBackup, @Database) WITH NOWAIT;
    RETURN;
END;
```

**Comment by reharmsen** [comment]
Could you check the DataBaseName used in the backup?
You should use that name as the @Database (and in the filename)
And then use @RestoreDatabaseName  to restore to the correct database (i guess MyDB)

Use this to get the header from the backup file, and look for the DataBaseName column
```sql
RESTORE HEADERONLY   
FROM DISK = N'C:\MyPath]MyDB.bak'
```

**Comment by BrentOzar** [comment]
@huguesgauthiertransit we haven't heard back from you, so I'm going to close it. If you have more questions though, feel free to stop into the Slack channel and we can help troubleshoot it interactively.

**Comment by huguesgauthiertransit** [comment]
Sorry for the delay, I use the code from @reharmsen https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/2153#issuecomment-543335664, and the result is (EnhancedStandard_PCDB_Exported_PRD)...

So I update the code with

```
EXEC [dbo].[sp_DatabaseRestore] 
@Database = 'EnhancedStandard_PCDB_Exported_PRD',
@RestoreDatabaseName = 'MyDB',
@BackupPathFull = 'c:\MyPath\',
@BackupPathLog = NULL,
@MoveFiles = 1,
@MoveDataDrive = @MoveDataDrive,	
@MoveLogDrive =	@MoveLogDrive,
@RunRecovery = 1	
```

return 

No backups for "EnhancedStandard_PCDB_Exported_PRD" found in "c:\MyPath\"

**Comment by huguesgauthiertransit** [comment]
Ok I rename the backup name as EnhancedStandard_PCDB_Exported_PRD.bak and it works...
thanks for helping me

**Comment by BrentOzar** [comment]
OK, great. So it sounds like you have database backups in c:\MyPath that are not named EnhancedStandard_PCDB_Exported_PRD.

I'm guessing - just guessing - that someone is taking backups of DatabaseA, but naming the files with DatabaseB. I don't think that's going to work.

Can you get the file names to match the databases that they reflect? That's how Ola's scripts work, and that's what sp_DatabaseRestore is designed to work with.

**Comment by BrentOzar** [comment]
Yep, there you go. Thanks!
