### ISSUE TITLE
Logging BlitzFirst to tables excludes BlitzCache Query Warnings

### ISSUE THREAD

**Issue by planetmatt** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2155]
**Version of the script**
7.8

**What is the current behavior?**
Following instructions on this page https://www.brentozar.com/first-aid/first-responder-kit-power-bi-dashboard/ shows that Query Warnings should appear in the PowerBI dashboard on the Query Details tab.

However, query warnings are only exported to a table if calling BlitzCache directly with @SkipAnalysis = 0.

When calling BlitzFirst and specifying Output tables as instructed on the PowerBI page, BlitzFirst calls BlitzCache and hard codes @SkipAnalysis = 1  at line 2801. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Run BlitzFirst with table logging.

EXEC [sp_BlitzFirst] 
@ExpertMode = 1,
@CheckProcedureCache=1,
@OutputDatabaseName = 'DBATools', 
@OutputSchemaName = 'dbo', 
@OutputTableName = 'BlitzFirst',
@OutputTableNameFileStats = 'BlitzFirst_FileStats',
@OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
@OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
@OutputTableNameBlitzCache = 'BlitzCache'

Then query BltzCache table for warnings

SELECT * FROM dbatools.dbo.BlitzCache WHERE Warnings IS NOT NULL.  I have 30 days of stats and no rows with warnings. 

I have Query Plans that show warnings when I run BlitzCache manually but are not logged by Blitzfirst. 

**What is the expected behavior?**
Either that BlitzFirst has a parameter to toggle SkipAnalysis on, or that the instructions for the PowerBI dashboard explicitly state that only plans captured directly with BlitzCache show warnings on the dashboard. 

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Microsoft SQL Server 2016 (SP2-CU3) (KB4458871) - 13.0.5216.0 (X64)   Sep 13 2018 22:16:01   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

**Comment by BrentOzar** [comment]
Great catch - I updated the documentation just now to take out the warnings part. If you want to change sp_BlitzFirst to have a @SkipQueryAnalysis parameter to pass on to sp_BlitzCache, that'd totally be a welcome pull request - just have it default to 1 to match the current behavior. (Running analysis on the top resource-intensive queries every 15 minutes can be really CPU-intensive.)

**Comment by BrentOzar** [comment]
I felt guilty and I was in there fixing other stuff, so I added a new @BlitzCacheSkipAnalysis parameter to sp_BlitzFirst. It defaults to 1, but if you want to do the analysis, you can flip that to 0 in your Agent jobs.

Coincidentally, I found a bug in sp_BlitzCache that was causing the Power BI Dashboard joins not to work between the BlitzFirst tables and BlitzCache tables. That's in #2159, and it'll be in the Oct release. (It's already in the dev branch.)

**Comment by planetmatt** [comment]
I think I might have already hit that issue which as a total n00b to PowerBi wasn't much fun.  It seems the joins work on exact values. The CheckDates table is constructed from unique values in the BlitzFirst table and uses a precision of milliseconds.  These datetime stamps then differ from the datetime stamps in the BlitzCache table. 

I resolved this by adding Computed Columns to all my Blitz tables that converted CheckDate to a SMALLDATETIME, then used this to define the relationships between all the Blitz tables in PowerBi.

Does your fix address this?

**Comment by BrentOzar** [comment]
Yes, that was the exact problem! The dates used to be the same, then a change to sp_BlitzCache broke it (totally my fault) and now it’s fixed in the dev branch.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws
