### ISSUE TITLE
BlitzCache returns an erroneous second resultset when @SortOrder = All

### ISSUE THREAD

**Issue by planetmatt** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2169]
**Version of the script**
7.8

**What is the current behavior?**
When calling BlitzCache with @SortOrder = All, BlitzCache returns the correct recordset, and then a mysterious second 5 row recordset.  

**If the current behavior is a bug, please provide the steps to reproduce.**
EXEC sp_BlitzCache
@ExpertMode = 0, @HideSummary = 1,
@SortOrder = 'all',
@SkipAnalysis = 1,
@MinutesBack = 15

Observe that two recordsets return, the second omits the Pattern column so it's unclear what Sort Order was used for these 5 plans. 

**What is the expected behavior?**

Only one recordset is returned.  

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Microsoft SQL Server 2016 (SP2-CU3) (KB4458871) - 13.0.5216.0 (X64)   Sep 13 2018 22:16:01   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

**Comment by BrentOzar** [comment]
Doh! That's not good. I'm on it. Thanks for the bug report!

**Comment by BrentOzar** [comment]
Ah - fixed this in #2168, closing.
