### ISSUE TITLE
sp_BlitzCache: some sort orders can produce rows they shouldn't

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2174]
**Version of the script**
SELECT @Version = '7.8', @VersionDate = '20190922';

**What is the current behavior?**
If you run @SortOrder = 'spills', but you don't have 10 queries with spills, then queries will show up in here even though they have 0 spills - just because we're sorting the top 10 queries, with no relevant where clause to filter out spills = 0:

![Screen Shot 2019-10-24 at 9 17 34 AM](https://user-images.githubusercontent.com/245462/67504937-2c699400-f63f-11e9-99f6-2782637e78e9.png)

Now that might sound esoteric, but it could show up in workloads where you're using @SortOrder = 'all'. (That's how I found it.) I had a bunch of bad queries, but by the time sp_BlitzCache @SortOrder = 'all' worked its way down to spills, there weren't any queries left that hadn't been covered by other sort orders, so I had queries with Sort Order = 'spills' but didn't have any spills.

**What is the expected behavior?**
This is gonna suck a little, but we need to introduce a dynamic WHERE clause that filters things out if they don't meet the sort order filter.

**Comment by erikdarlingdata** [comment]
Every time I look at this issue, I think that we shouldn't be returning 0 values for any sort order no matter what. If someone is sorting by a metric, we shouldn't give them rows with nothing for that metric. This is probably most common with writes, spills, and memory. I can see it happening with executions/xpm for CPU and reads, but that's unrelated from the sort order.

Side question: Do we want a default insert message if no plans are found? I know we do that in other procs when analysis doesn't turn anything up. 

I'll take this one; assign it to me and I'll work on it this month.

**Comment by BrentOzar** [comment]
Love it. Yeah, wanna copy the good news type message for the second result set, and just leave the first result set empty?

**Comment by erikdarlingdata** [comment]
yeah, makes sense. i think i'd probably keep any plan cache related warnings in the second result set though, just in case they're not seeing anything because of instability or whatever.

**Comment by BrentOzar** [comment]
Nice work! Thanks for the PR, merged into dev, will be in the October release along with a note that you are a god amongst men. Not all men, just New York men, but still, that's a big deal.
