### ISSUE TITLE
Unusual messages in October versions

### ISSUE THREAD

**Issue by thornersetrans** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2179]
I am installing October versions of First Responder.  I am seeing warnings and messages not seen in my August versions.  I also notice that sp_foreachdb is not in the October zip file (probably why that sp_blitz message says sp_foreachdb is outdated).  Anything I should be concerned about?  Whenever I see any anomalies, I hesitate to put on production servers.   FYI: I put these SP's in a database called MaintenanceDB, not master.

October version, sp_blitzfirst:
Setting up configuration variables
Now starting diagnostic analysis
Capturing first pass of wait stats, perfmon counters, file stats
Beginning investigatory queries
**Warning: The join order has been enforced because a local join hint is used.
Warning: The join order has been enforced because a local join hint is used.**
Finished running investigatory queries
Waiting to match @Seconds parameter
Capturing second pass of wait stats, perfmon counters, file stats
Analyzing changes between first and second passes of DMVs
Analysis finished, outputting results

October version, sp_blitz:
**Component [MaintenanceDB].[dbo].[sp_foreachdb] is outdated**

October version, sp_blitzindex (a few of these now appear in messages):
**Warning: Null value is eliminated by an aggregate or other SET operation.**

August version, sp_blitzfirst:
Setting up configuration variables
Now starting diagnostic analysis
Checking for Read intent databases to exclude
Capturing first pass of wait stats, perfmon counters, file stats
Beginning investigatory queries
Finished running investigatory queries
Capturing second pass of wait stats, perfmon counters, file stats
Analyzing changes between first and second passes of DMVs
Analysis finished, outputting results

**Comment by ck75** [comment]
Hi,
I'm seeing the same error as well. Only on 2 servers out of 100 we have the update on and it happens intermittingly.

**Comment by BrentOzar** [comment]
About the join order & null value messages - those are totally normal.

About the outdated component - that means you need to update that component.

**Comment by thornersetrans** [comment]
What I noticed is that the sp_foreachdb script is not included in the October 28, 2019 zip file, which caused the outdated component message.  Usually all the required scripts are in the zip file, even if they did not change.

Thomas Horner
SQL Server DBA
(O) 404-209-3012
