### ISSUE TITLE
SqlServerVersions.sql Data Point issue

### ISSUE THREAD

**Issue by sm8680** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2181]
(13, 5426, 'SP2 CU10', 'https://support.microsoft.com/en-us/help/4505830', '2019-10-08', '2021-07-13', '2026-07-14', 'SQL Server 2016', 'Service Pack 2 Cumulative Update 10'),
    (13, 5426, 'SP2 CU9', 'https://support.microsoft.com/en-us/help/4505830', '2019-09-30', '2021-07-13', '2026-07-14', 'SQL Server 2016', 'Service Pack 2 Cumulative Update 9'),
    (13, 5426, 'SP2 CU8', 'https://support.microsoft.com/en-us/help/4505830', '2019-07-31', '2021-07-13', '2026-07-14', 'SQL Server 2016', 'Service Pack 2 Cumulative Update 8'),

5426 and the url are repeated in the 3 data points above https://support.microsoft.com/en-us/help/4505830

You may want to consider adding a PK on the following fields [MajorVersionName], [MajorVersionNumber], [MinorVersionNumber] in order to catch these type of issues in testing.  Thanks for all the awesome hard work!

**Comment by EmanueleMeazzo** [comment]
I found an issue with other version numbers too; e.g.  SQL Server RTM CU 17 is 14.3238, not 14.3228
I'm updating the file fixing this data points (and adding SQL Server 2019 too since I'm there)

**Comment by BrentOzar** [comment]
Thanks for the bug report! @EmanueleMeazzo fixed in the dev branch, and it'll be in the November release, along with thanks to both of y'all.
