### ISSUE TITLE
Problem of exporting to csv file ! 

### ISSUE THREAD

**Issue by hamidmira** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2182]
**Is your feature request related to a problem? Please describe.**
I have problems exporting the result to a csv file, due to line breaks in some error messages
See  CheckID : 150 "Errors Logged Recently in the Default Trace" 

**Describe the solution you'd like**

**Describe alternatives you've considered**
I suggest the following modification to make it easier to export to a csv file, or copy/paste to an Excel file. 

Replace

```SQL
SELECT DISTINCT 150 AS CheckID ,
        t.DatabaseName,
        50 AS Priority ,
        'Reliability' AS FindingsGroup ,
        'Errors Logged Recently in the Default Trace' AS Finding ,
        'https://BrentOzar.com/go/defaulttrace' AS URL ,
         CAST(t.TextData AS NVARCHAR(4000)) AS Details -- !!! problem of exporting to csv file !!!
FROM    #fnTraceGettable t
WHERE t.EventClass = 22
```
with
```SQL
SELECT DISTINCT 150 AS CheckID ,
        t.DatabaseName,
        50 AS Priority ,
        'Reliability' AS FindingsGroup ,
        'Errors Logged Recently in the Default Trace' AS Finding ,
        'https://BrentOzar.com/go/defaulttrace' AS URL ,
         REPLACE(REPLACE (CAST(t.TextData AS NVARCHAR(4000)), CHAR(13), '|'), CHAR(10), '|') AS Details -- !!! Solves problem of exporting to csv file  !!!
FROM    #fnTraceGettable t
WHERE t.EventClass = 22
```
Note 
This solves the problem of "line breaks" 
But, this will not solve the problem when the error message itself contains semicolons ! 

**Are you ready to build the code for the feature?**
No !

**Comment by EmanueleMeazzo** [comment]
What about using a string qualifier when exporting the data to CSV?
Makes no sense  to modify the base scripts to fix an issue with your own personal way of importing/exporting data, check the settings of your tool of choice

**Comment by hamidmira** [comment]
Hello and thank you for your answer.
I use SSMS (right click save as csv). SSMS does not offer many options for CSV export (?)
The problem with string qualifier is that it can itself be contained in the chain!
Example:
chain qualifier: `"`
Text (column _Details_):
```
... This scenario is not supported.
See "Impersonation Overview" in Books Online...
```
In this scenario the csv export does not work !
Actually, I'm not sure there is a solution to this problem without transforming the text in the _Details_ column  (?)

**Comment by EmanueleMeazzo** [comment]
Yes there is, the issue is with how you export/import data, and not with the procedure itself.

Use Azure Data Studio, for example, to export in csv or directly in Excel if that's your end goal; otherwise, if you're stuck with SSMS , save the results of spBlitz in a table first and then select from it in such a way to modify the "text" column as in your example in OP

**Comment by hamidmira** [comment]
OK, Thank you for these clarifications and tips :) 
So, as indicated, I will use Azure Data Studio or Export from SSMS in a table and then transformation etc. 
This issue can be considered closed :) 
Thank you very much.
