### ISSUE TITLE
sp_BlitzIndex Crashes when output to a new table with long list of columns 

### ISSUE THREAD

**Issue by heliolino** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2183]
**Version of the script**
v7.9 - October 24, 2019

**What is the current behavior?**
sp_blitzIndex exit with following error
Failure analyzing temp tables.
Msg 50000, Level 16, State 10, Procedure sp_blitzindex, Line 4994 [Batch Start Line 10]
String or binary data would be truncated.

**If the current behavior is a bug, please provide the steps to reproduce.**
using a table with lots of columns with large names lead to the error 

**What is the expected behavior?**
The problem only occurs when you run the procedure with the parameter @OutputTableName
on, probably no one have reached this problem before. 
but the issue fix is easy.

in the part of the code where it says "N'CREATE TABLE @@@OutputDatabaseName@@@.@@@OutputSchemaName@@@.@@@OutputTableName@@@ "

changing the below datatypes length 
[Drop_Tsql] NVARCHAR(4000),
[Create_Tsql] NVARCHAR(4000), 
[index_definition] NVARCHAR(4000), 

To NVARVARCHAR(MAX) was enough to solve the problem. 

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
this bug is not related with SQL/OS version neither the version of sp_blitzIndex

**Comment by BrentOzar** [comment]
Thanks for the bug report. Fixed in the dev branch. Will be in the November release, and you'll be credited in the release notes.
