### ISSUE TITLE
sp_BlitzFirst issue - Incorrect syntax near 'r'.

### ISSUE THREAD

**Issue by igal8183** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2184]
**Version of the script**
Version = '7.9', VersionDate = '20191024'

**What is the current behavior?**
When running sp_BlitzFirst  you'll get 2 errors:
**Msg 102, Level 15, State 1, Line 33
Incorrect syntax near 'r'.
Msg 156, Level 15, State 1, Line 41
Incorrect syntax near the keyword 'AND'.**

Solution - 
There's a missing comma on line 1498, in the **Query Problems - Long-Running Query Blocking Others - CheckID 5 block**, after **0 AS OpenTransactionCount**

**Comment by EmanueleMeazzo** [comment]
There is, indeed! Thanks!!

**Comment by BrentOzar** [comment]
Thanks for the bug report! @EmanueleMeazzo fixed in the dev branch, and it'll be in the November release, along with thanks to both of y'all.
