### ISSUE TITLE
 Non-Default Database Config enable_broker and honor_broker_priority just as trustworthy

### ISSUE THREAD

**Issue by parlevjo2** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2187]
Hi Brent

I would like to add some code for detecting for those 2 options on a database.
Recently I had detached an SCCM database for moving the datafile to another disk. I reattached the database and SCCM was not working. I found out that 3 database properties are just not being set when attaching the database.

So just as "Trustworthy Enabled" is already in your script I want to add that for "enable_broker" and 
"honor_broker_priority".

[Details](https://blogs.technet.microsoft.com/configurationmgr/2013/04/02/how-to-move-the-configmgr-2012-site-database-to-a-new-sql-server/)

--- Enable the SQL Broker on the Site database

> USE master;
> GO
> ALTER DATABASE SCCM_DATABASE SET ENABLE_BROKER
> GO

--- SET the Site Database as trustworthy

> ALTER DATABASE SCCM_DATABASE SET TRUSTWORTHY ON
> GO

--- SET the Database to honor the HONOR_BROKER_PRIORITY

> ALTER DATABASE SCCM_DATABASE SET HONOR_BROKER_PRIORITY ON;
> GO

**Comment by BrentOzar** [comment]
Hi, and thanks for the issue. What script are you referring to, and where do you want to add these lines of code?

**Comment by parlevjo2** [comment]
Hi @BrentOzar 

I was referring to
`
						INSERT INTO #DatabaseDefaults
						  SELECT 'is_trustworthy_on', 0, 137, 210, 'Trustworthy Enabled', 'https://BrentOzar.com/go/dbdefaults', NULL
						  FROM sys.all_columns
						  WHERE name = 'is_trustworthy_on' AND object_id = OBJECT_ID('sys.databases');
`

I would like to add those lines to sp_blitz.sql:
`						INSERT INTO #DatabaseDefaults
						  SELECT 'is_broker_enabled', 0, 230, 210, 'Broker Enabled', 'https://BrentOzar.com/go/dbdefaults', NULL
						  FROM sys.all_columns
						  WHERE name = 'is_broker_enabled' AND object_id = OBJECT_ID('sys.databases');`
`
						INSERT INTO #DatabaseDefaults
						  SELECT 'is_honor_broker_priority_on', 0, 231, 210, 'Honor Broker Priority Enabled', 'https://BrentOzar.com/go/dbdefaults', NULL
						  FROM sys.all_columns
						  WHERE name = 'is_honor_broker_priority_on' AND object_id = OBJECT_ID('sys.databases');
`

and add 2 entries to "Documentation\sp_Blitz Checks by Priority.md"
`
| 210 | Non-Default Database Config | Broker Enabled | https://www.BrentOzar.com/go/dbdefaults | 230 |
`
`
| 210 | Non-Default Database Config | Honor Broker Priority Enabled | https://www.BrentOzar.com/go/dbdefaults | 231 |
`

**Comment by BrentOzar** [comment]
OK, did some quick research. It gets a little trickier: is_broker_enabled = 1 is normal for msdb and tempdb. We wouldn't want to give them a false alarm saying that is_broker_enabled has been turned on for msdb and tempdb, so just make sure your solution accounts for that.

Sounds good though. Whenever you're ready, you can do a pull request per the contributing guide. Thanks!

**Comment by parlevjo2** [comment]
Good point. All Reportserver, ReportServerTempDB ,SUSDB and CM_XXX (SCCM) and distribution databases have is_broker_enabled=1.
I see also many other application databases which have is_broker_enabled=1 too.
On [Link](https://davewentzel.com/content/service-broker-demystified-set-enable_broker-vs-new_broker/) I read "The process of restoring the database did NOT change the GUID...but it did disable SSB. So, we'll need to fix it if we want to use our services and queues in that database."
So it is important information to know. But will give probably too many hits.
Strange that in 20 years I now only have once experienced a problem with broker. 

`Select name, is_broker_enabled, service_broker_guid, is_honor_broker_priority_on from sys.databases`

I need to rethink about this or only cover "is_honor_broker_priority_on".

**Comment by RobAshton-IM** [comment]
@parlevjo2 Johan, whilst I can see plenty of merit in excluding msdb and tempdb from the is_broker_enabled check (nobody wants sp_Blitz giving conflicing and mutually exclusive warnings telling them that DatabaseMail isn't enabled or that is_broker_enabled is enabled on msdb), not everyone has applications like System Center to worry about so it seems like a lot of extra work adding those in as specific exclusions in the sp_Blitz check code.

The "SkipChecks" functionality would be the solution here wouldn't it? If you're in the position that you have false positives for this new set of alerts for a particular database, just exclude that check for that database and hey presto, no more false positive.

**Comment by parlevjo2** [comment]
Hi @RobAshton-IM and @BrentOzar 

It turns out that this particular part of sp_blitz does not check the databases with database_id <=4.
So master, tempdb, model, msdb are not checked for the DatabaseDefaults part of sp_blitz.
I have created 2 new CheckIDs in sp_Blitz Checks by Priority.md

| Priority | FindingsGroup | Finding | URL | CheckID |
|----------|-----------------------------|---------------------------------------------------------|------------------------------------------------------------------------|----------|
| 210 | Non-Default Database Config | Broker Enabled | https://www.BrentOzar.com/go/dbdefaults | 230 |
| 210 | Non-Default Database Config | Honor Broker Priority Enabled | https://www.BrentOzar.com/go/dbdefaults | 231 |

Based on CheckID 137 which is in the same category.

| Priority | FindingsGroup | Finding | URL | CheckID |
|----------|-----------------------------|---------------------------------------------------------|------------------------------------------------------------------------|----------|
| 210 | Non-Default Database Config | Trustworthy Enabled | https://www.BrentOzar.com/go/dbdefaults | 137 |

If those numbers ale already taken by another update please let me know which ones I can use.

And I have those extra lines in sp_blitz.sql

`					INSERT INTO #DatabaseDefaults
						  SELECT 'is_broker_enabled', 0, 230, 210, 'Broker Enabled', 'https://BrentOzar.com/go/dbdefaults', NULL
						  FROM sys.all_columns
						  WHERE name = 'is_broker_enabled' AND object_id = OBJECT_ID('sys.databases');`
`						INSERT INTO #DatabaseDefaults
						  SELECT 'is_honor_broker_priority_on', 0, 231, 210, 'Honor Broker Priority Enabled', 'https://BrentOzar.com/go/dbdefaults', NULL
						  FROM sys.all_columns
						  WHERE name = 'is_honor_broker_priority_on' AND object_id = OBJECT_ID('sys.databases');
`

I have created a topic branch "issue_2187_broker_and_honor_broker_priority". 
I will create a Pull Request after your approval

**Comment by BrentOzar** [comment]
Hi! Can you just go ahead and create the pull request so folks can look at it? Thanks!

**Comment by parlevjo2** [comment]
@BrentOzar I just have created a pull request. Sorry for the delay. I could not publish my branch. It took me a while to figure out that I had to work on my forked repository (and first sync it with your dev version).

**Comment by BrentOzar** [comment]
Thanks for the pull request! Merged into the dev branch. It'll be in the January release, and we'll credit you in the release notes.
