### ISSUE TITLE
sp_blitzindex is not creating new table with parameter @mode=4

### ISSUE THREAD

**Issue by heliolino** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2190]
**Version of the script**
sp_BlitzIndex(TM) v7.9 - October 24, 2019: Database [VAT-Resource-Demo] as of 2019-11-14 14:24

**What is the current behavior?**
the output table is not being created 

**If the current behavior is a bug, please provide the steps to reproduce.**

the following set of parameters does not create a new output table 

sp_blitzindex @DatabaseName = 'somedb',@BringThePain = 1, @mode =4,@OutputDatabaseName = 'DBOUT',@OutputSchemaName = 'dbo', @OutputTableName = 'TbIndexReport'

**What is the expected behavior?**
to create a new table and populate data 

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2014 /windows 2012 
not sure if on previous versions had worked

**Comment by BrentOzar** [comment]
Hi. The only @Mode supported for table output is @Mode = 2. If you want data output for @Mode = 4, that would be a new feature, but you'd be on the hook for coding that. ;-) I'll clarify the documentation to make that more obvious.
