### ISSUE TITLE
sp_BlitzIndex creation script returns "Unrecognized SQL escape 'datatype'"

### ISSUE THREAD

**Issue by amoroso** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2191]
**Version of the script**
@Version = '7.9', @VersionDate = '20191024'

**What is the current behavior?**
Running script returns error: 

```
Command was executed successfully
 [Executed: 11/14/2019 12:52:14 PM] [Execution: 2ms] 
 Command was executed successfully
 [Executed: 11/14/2019 12:52:14 PM] [Execution: 4ms] 
>[Error] Script lines: 14-5017 ----------------------
 Unrecognized SQL escape 'datatype' at line position 113218.
 [Executed: 11/14/2019 12:52:14 PM] [Execution: 1ms]
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Load script - I'm using Aqua Data Studio - and run under "master" database

**What is the expected behavior?**
 Command was executed successfully

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
```
Microsoft SQL Server 2017 (RTM-CU17) (KB4515579) - 14.0.3238.1 (X64) 
	Sep 13 2019 15:49:57 
	Copyright (C) 2017 Microsoft Corporation
	Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

```

**Comment by BrentOzar** [comment]
Hi! Do you have the same problem in SQL Server Management Studio?

**Comment by amoroso** [comment]
Nope!  It worked in SSMS.  Sorry about that...I'm usually on a Mac and use
Aqua Data Studio.  If I encounter another issue, I'll make sure to try on
SSMS in my Windows VM.

Thank you!
-Bobby

**Comment by BrentOzar** [comment]
OK, thanks, closing.
