### ISSUE TITLE
sp_Blitz: arithmetic overflow, dukesql troubleshooting to find root cause

### ISSUE THREAD

**Issue by dukesql** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2193]
**Version of the script**
@Version = '7.9', @VersionDate = '20191024';

**What is the current behavior?**
Running CheckId [40].
Msg 220, Level 16, State 2, Procedure sp_Blitz, Line 2622
Arithmetic overflow error for data type tinyint, value = 1100.
**I see this error after CheckID 40, 41 and 80

It also reports  - Version 11.00.7001.00 is no longer supported by Microsoft. You need to apply a service pack.  Not sure why this is, but maybe related to the other failure errors.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Windows 2012 R2 Datacenter
SQL 2012 SP4 11.00.7001

**Comment by BrentOzar** [comment]
Errrr, how many files and filegroups do you have per database?

**Comment by dukesql** [comment]
Server has 7 user databases.  All of them except 1 has 1 data file and 1 log file each.  The one oddball has 14 data files each with it's own filegroup (vendor app/db).

**Comment by BrentOzar** [comment]
OK, something else is going on - you may need to check the scripts for each of those checks individually, running them one at a time, to track down what's happening. It's working OK here, so I'm guessing something else is going on that isn't related to checks 40 or 41.

**Comment by BrentOzar** [comment]
Duke - I haven't heard back from you, so I'm going to close this, but if you get more details, feel free to follow back up with the information. Thanks!
