### ISSUE TITLE
sp_BlitzLock: Make it collector friendly

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2194]
**Is your feature request related to a problem? Please describe.**
I would like the option to format sp_BlitzLock output to make it Excel friendly, in hopes that it can be added to the data collection utility.

**Describe the solution you'd like**
Add an `@ExportToExcel` option that de-XMLs the output.

**Describe alternatives you've considered**
Ritual suicide, Gozer worship, AA, Crossfit.

**Are you ready to build the code for the feature?**
Yes.

**Comment by BrentOzar** [comment]
I've actually been wanting to get Richie to write the deadlock graphs to separate files - the same way we do with execution plans. If we do that, is there anything else we would need to tweak? That might be enough right there.

**Comment by erikdarlingdata** [comment]
I don't think so, no. I'd just skip outputting them as an unformatted field here. If we're getting those it might make sense to skip some other fields that someone could see more easily in Plan Explorer or SSMS.

**Comment by BrentOzar** [comment]
WOOHOO! Turns out the collector already has the ability to write any column to file. No changes were needed on sp_BlitzLock itself. Will be in the December release.
