### ISSUE TITLE
Invalid length parameter passed to the LEFT or SUBSTRING function.

### ISSUE THREAD

**Issue by bike-dude** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2198]
**Version of the script**
Version 5.8
Version Date 20171001

**What is the current behavior?**
It errors out with a not too helpful message: 
Msg 537, Level 16, State 3, Line 2660 Invalid length parameter passed to the LEFT or SUBSTRING function. I get no results.

**If the current behavior is a bug, please provide the steps to reproduce.**
I just ran it on my system.

**What is the expected behavior?**
To produce results on issues with my databases.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Standard 2016.
Win10 OS.

**Comment by BrentOzar** [comment]
OK, go ahead and upgrade to the latest version. Unlike those fine antiques you have in the basement, sp_BlitzCache doesn't get better with age. Then let us know if one built in the last two years has the same issue. ;-)

**Comment by bike-dude** [comment]
Still getting the same issues.
here's another version of the error message:

|  
The job failed. The Job was invoked by User DOF\FIPSLESI. The last step to run was step 1 (Subplan_1).
 Step 1 (Subplan_1): Executed as user: NT Service\SQLSERVERAGENT. ...26.0 for 64-bit Copyright (C) 2016 Microsoft. All rights reserved. Started: 12:21:46 PM Progress: 2019-11-19 12:21:46.80 Source: {E57137AB-CEE0-4607-B27B-76F7F4F01AE0} Executing query "DECLARE @Guid UNIQUEIDENTIFIER EXECUTE msdb..sp...".: 100% complete End Progress Progress: 2019-11-19 12:21:46.88 Source: Execute T-SQL Statement Task Executing query "use DBAResources; ".: 50% complete End Progress Error: 2019-11-19 12:22:04.15 Code: 0xC002F210 Source: Execute T-SQL Statement Task Execute SQL Task Description: Executing the query " EXEC dba.sp_blitzcache @OutputDatabaseName = 'DB..." failed with the following error: "Invalid length parameter passed to the LEFT or SUBSTRING function. Creating temp tables for results and warnings. Checking database validity Checking sort order Cleaning up old warnings for your SPID Cleaning up old plans for your SPID Creating temp tables for internal processing Checking plan cache age Checking plan stub count Warning: Null value is eliminated by an aggregate or other SET operation. Checking single use plan count Warning: Null value is eliminated by an aggregate or other SET operation. Setting up variables Determining SQL Server version. Creating dynamic SQL based on SQL Server version. Ignoring system databases by default Applying chosen sort order Adding additional info columns for newer versions of SQL Getting memory grant information for newer versions of SQL Adding SQL to collect trigger stats. Collecting execution plan information. Attempting to aggregate stored proc info from separate statements Computing CPU, duration, read, and write metrics Update CPU percentage for stored procedures Gather percentage information from grouped results Begin XML nodes processing Gathering high level plan information Warning: Null value is eliminated by an aggregate or other SET operation. Performing compile timeout checks Performing compile memory limit exceeded checks Performing unparameterized query checks Performing index DML checks Performing table DML checks Gathering row estimates Gathering statement costs Updating statement costs Gathering stored procedure costs Checking for plan warnings Checking for implicit conversion Performing busy loops checks Performing TVF join check Checking for operator warnings Checking for table variables Checking for functions Checking for expensive key lookups Checking for expensive remote queries Checking for expensive sorts Checking for icky cursors Checking for bad scans and plan forcing Checking for computed columns that reference scalar UDFs Checking for filters that reference scalar UDFs Checking modification queries that hit lots of indexes Checking for Spatial index use Checking for wonky Index Spools Checking for forced serialization Checking for ColumnStore queries operating in Row Mode instead of Batch Mode Checking for downlevel cardinality estimators being used on SQL Server 2014. Checking for row level security in 2016 only Performing query level checks Gathering additional plan level information Warning: Null value is eliminated by an aggregate or other SET operation. Attempting to get stored procedure name for individual statements Trace flag checks Is Paul White Electric? Getting information about implicit conversions and stored proc parameters The statement has been terminated. Setting configuration values Checking for query level SQL Server issues. Checking for forced parameterization and cursors. Populating Warnings column Populating Warnings column for stored procedures Checking for plans with >128 levels of nesting Checking for plans with no warnings Writing results to table.". Possible failure reasons: Problems with the query, "ResultSet" property not set correctly, parameters not set correctly, or connection not established corre... The package execution fa... The step failed.
  |



    On Tuesday, November 19, 2019, 12:10:51 PM PST, Brent Ozar <notifications@github.com> wrote:  
 
 
OK, go ahead and upgrade to the latest version. Unlike those fine antiques you have in the basement, sp_BlitzCache doesn't get better with age. Then let us know if one built in the last two years has the same issue. ;-)

**Comment by BrentOzar** [comment]
Okay, that's an Agent job, not running sp_BlitzCache.

I'm going to cut right to the chase because I'm sure you're as busy as I am, and I wanna minimize the back-and-forth that we do here. I'm doing troubleshooting as a volunteer, and I need your help to get across the finish line as quickly as possible.

Just run sp_BlitzCache from SSMS, no parameters, just sp_BlitzCache. If that doesn't work, send a screenshot of exactly what you're seeing.

If you're doing something other than sp_BlitzCache in SSMS, then start by:

* Run it just by itself, and see if that errors out
* Run it with the parameters you want to use, and see if that errors out
* If it does, try stripping away parameters one at a time until you find the one that's causing the error
* If it doesn't, then finally try running it in an Agent job

But let's start by keeping it simple. Go for it and let me know what you find. Thanks!

**Comment by bike-dude** [comment]
The new version did it.
Thank you!
    On Tuesday, November 19, 2019, 12:26:25 PM PST, Brent Ozar <notifications@github.com> wrote:  
 
 
Okay, that's an Agent job, not running sp_BlitzCache.

I'm going to cut right to the chase because I'm sure you're as busy as I am, and I wanna minimize the back-and-forth that we do here. I'm doing troubleshooting as a volunteer, and I need your help to get across the finish line as quickly as possible.

Just run sp_BlitzCache from SSMS, no parameters, just sp_BlitzCache. If that doesn't work, send a screenshot of exactly what you're seeing.

If you're doing something other than sp_BlitzCache in SSMS, then start by:
   
   - Run it just by itself, and see if that errors out
   - Run it with the parameters you want to use, and see if that errors out
   - If it does, try stripping away parameters one at a time until you find the one that's causing the error
   - If it doesn't, then finally try running it in an Agent job

But let's start by keeping it simple. Go for it and let me know what you find. Thanks!

**Comment by BrentOzar** [comment]
OK, great, thanks, closing.
