### ISSUE TITLE
sp_ineachdb.sql - [state] & 992  (or Lost In Translation)

### ISSUE THREAD

**Issue by bgehem** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2199]
**Version of the script**
dev

**What is the current behavior?**
In https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/310618afe99baa3e8f04b3d3df75eae6466c202a/sp_ineachdb.sql#L189 the following check is made `[state] & 992 <> 0` I believe this is an error carried over from [Aaron Bertrand's blog post introducing sp_ineachdb](https://www.mssqltips.com/sqlservertip/5686/execute-a-command-in-the-context-of-each-database-in-sql-server-using-spineachdb/). In the comments Robert Steen asks about this masking of the state value and  Aaron's answer is that this came from sp_MSforeachdb. There is however one small difference:

- **sp_MSforeachdb** queries the **status** value from  [master.dbo.**sysdatabases**](https://docs.microsoft.com/en-us/sql/relational-databases/system-compatibility-views/sys-sysdatabases-transact-sql?view=sqlallproducts-allversions) which contains status bits and where masking with decimal value 992 makes sense.

Value | Description
----- | -----------
```0000 0011 1110 0000``` | decimal 992
```0000 0000 0000 0001``` | autoclose 		   
```0000 0000 0000 0100``` | select into/bulkcopy
```0000 0000 0000 1000``` | trunc. log on chkpt
```0000 0000 0001 0000``` | torn page detection
```0000 0000 0010 0000``` | loading
```0000 0000 0100 0000``` | pre recovery
```0000 0000 1000 0000``` | recovering
```0000 0001 0000 0000``` | not recovered
```0000 0010 0000 0000``` | offline 
```0000 0100 0000 0000``` | read only
```0000 1000 0000 0000``` | dbo use only
```0001 0000 0000 0000``` | single user

- **sp_ineachdb** queries the **state** value from  [master.sys.**databases**](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-databases-transact-sql?view=sqlallproducts-allversions) which just contains a numerical value and where masking with decimal value 992 makes absolutely no sense.

Value | Description
----- | -----------
```0000 0011 1110 0000``` | decimal 992
```0000 0000 0000 0000``` | ONLINE
```0000 0000 0000 0001``` | RESTORING
```0000 0000 0000 0010``` | RECOVERING 
```0000 0000 0000 0011``` | RECOVERY_PENDING
```0000 0000 0000 0100``` | SUSPECT
```0000 0000 0000 0101``` | EMERGENCY 
```0000 0000 0000 0110``` | OFFLINE
```0000 0000 0000 0111``` | COPYING (Azure)
```0000 0000 0000 1010``` | OFFLINE_SECONDARY (Azure)

**If the current behavior is a bug, please provide the steps to reproduce.**
```sql
SELECT state, state_desc, [state] & 992 AS "wt?" FROM sys.databases
```
`[state] & 992` will always be zero.

**What is the expected behavior?**
This check should never be performed against sys.databases.state.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All

**Comment by BrentOzar** [comment]
OK, cool. If you want to contribute the change, here's how to do it:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

I don't actually use that proc myself, so you're welcome to take a shot at it. If you don't want to do it, totally understood - we'll leave it open for a while for others to tackle it, and then close it if it hasn't had a patch in 30 days. Thanks!

**Comment by BrentOzar** [comment]
I haven't heard back from you in a month, so I'll go ahead and close this. If you want to move forward with the fix, though, just leave a note here when you're ready to work on it, and we can reopen it. Thanks!
