### ISSUE TITLE
sp_BlitzIndex - use recently-modified check to improve not-in-use recommendations

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#220]
Since index usage stats get cleared on a rebuild with 2012 & newer, we shouldn't show unused-index warnings if the index has been rebuilt/modified in the last week.

**Comment by BlitzErik** [comment]
2012 SP2 + CU12 and SP3 + CU 3 fix this, along with 2014 SP2 and 2016 RTM. Just adding this in in case someone picks this up.

**Comment by BlitzErik** [comment]
Fixed in #373

**Comment by BrentOzar** [comment]
Fixed, closing, good job.
