### ISSUE TITLE
Install-Core-Blitz-No-Query-Store script sp_BlitzFirst and sp_BlitzWho dependencies

### ISSUE THREAD

**Issue by Brianc-DBA** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2200]
**Version of the script**
7.9
**What is the current behavior?**
When executing Install-Core-Blitz-No-Query-Store.sql (and presumably Install-Core-Blitz-With-Query-Store.sql based on a cursory look) into a server that does not have the FRK installed, it displays the following warning:
"The module 'sp_BlitzFirst' depends on the missing object 'sp_BlitzWho'. The module will still be created; however, it cannot run successfully until the object exists. "

This would probably go away if sp_BlitzWho was moved above sp_BlitzFirst in the No-Query-Store / Query-Store scripts.

**If the current behavior is a bug, please provide the steps to reproduce.**
Execute Install-Core-Blitz-No-Query-Store.sql in a server that does not have the FRK already installed.

**What is the expected behavior?**
No warning received upon script execution.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Tested in SQL 2008R2 and SQL 2017, though it likely behaves the same in all versions.

**Comment by BrentOzar** [comment]
Sure, to do that, you can contribute a change to the build script here:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/Documentation/Development/Merge%20Blitz.ps1

Here's the contributing guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md

Is this something you're ready to tackle?

**Comment by Brianc-DBA** [comment]
Sounds good, I should be able to look into this.

Thanks,
Brian

**Comment by Brianc-DBA** [comment]
Oh, the build script is in PowerShell, that's like Sanskrit to me.  :)  I tried and had an idea, but it won't quite work.  May need more PowerShell expertise to weigh in.

Right now the files for #All Core Blitz Without sp_BlitzQueryStore return in this order:
Mode                LastWriteTime         Length Name                                                                                                          
----                -------------         ------ ----                                                                                                          
-a----       11/14/2019   1:23 PM         414100 sp_Blitz.sql                                                                                                  
-a----       11/14/2019   1:23 PM          65722 sp_BlitzBackups.sql                                                                                           
-a----       11/14/2019   1:23 PM         296591 sp_BlitzCache.sql                                                                                             
-a----       11/14/2019   1:23 PM         281614 sp_BlitzFirst.sql                                                                                             
-a----       11/14/2019   1:23 PM         280593 sp_BlitzIndex.sql                                                                                             
-a----       11/14/2019   1:23 PM          52641 sp_BlitzLock.sql                                                                                              
-a----       11/14/2019   1:23 PM          37650 sp_BlitzWho.sql  

I don't believe the PS Get-ChildItem command guarantees an implicit sort order.  But you can create that by adding an explicit sort at the end of the 'Where-Object' line, and making it descending will return files in reverse order (thus sp_BlitzWho will show up first): 
Where-Object { $_.FullName -notlike "*sp_BlitzQueryStore.sql*" -and $_.FullName -notlike "*sp_BlitzInMemoryOLTP*"} |Sort $_.FullName -Descending

Mode                LastWriteTime         Length Name                                                                                                          
----                -------------         ------ ----                                                                                                          
-a----       11/14/2019   1:23 PM          37650 sp_BlitzWho.sql                                                                                               
-a----       11/14/2019   1:23 PM          52641 sp_BlitzLock.sql                                                                                              
-a----       11/14/2019   1:23 PM         280593 sp_BlitzIndex.sql                                                                                             
-a----       11/14/2019   1:23 PM         281614 sp_BlitzFirst.sql                                                                                             
-a----       11/14/2019   1:23 PM         296591 sp_BlitzCache.sql                                                                                             
-a----       11/14/2019   1:23 PM          65722 sp_BlitzBackups.sql                                                                                           
-a----       11/14/2019   1:23 PM         414100 sp_Blitz.sql  

Unfortunately, there are other script dependencies.  sp_BlitxIndex depends on sp_BlitzCache, and so there will just be another warning if the script is changed this way.  What I was really trying to do is to just move sp_BlitzWho to the top and run the rest in ascending order, or find some other automated way to specify the dependency files in order.  But I am not sure how to do that in PowerShell.

**Comment by BrentOzar** [comment]
OK, cool. I'm going to close this for now, but if you decide you want to tackle it, just leave a note and I can reopen it.
