### ISSUE TITLE
sp_BlitzFirst version 7.91  ##WaitCategories

### ISSUE THREAD

**Issue by bgpjr** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2208]
**sp_BlitzFirst version 7.91t**

**What is the current behavior?**
IF 504 <> (SELECT COALESCE(SUM(1),0) FROM ##WaitCategories)
  will always be true as the procedure will insert 527 rows

**If the current behavior is a bug, please provide the steps to reproduce.**
- create the table
- run the inserts
- run the select statement against the table
- observe the result -- 527 

**What is the expected behavior?**
IF 527 <> (SELECT COALESCE(SUM(1),0) FROM ##WaitCategories)
Will not repopulate the table

**Comment by BrentOzar** [comment]
Howdy sir! I wasn't sure if you were going to try to do this or not, but it was pretty easy so I knocked it out. Thanks!
