### ISSUE TITLE
Power BI BlitzFirst - BlitzCache duplicate joinkey

### ISSUE THREAD

**Issue by rabentho** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2209]
@Version = '7.9', @VersionDate = '20191024'

**What is the current behavior?**
Unable to refresh power bi dashboard. Column 'JoinKey' in Table 'BlitzFirst' contains a duplicate value 'CES-INSTANTSSIS2019-11-27 02:00:01.3804179 -05:00' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Have multiple items with the same server, checkdate and a priority between 1 and 199 in the BlitzFirst table

**What is the expected behavior?**
Not to fail refreshing power bi dashboard data.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2016, Windows 10, This is the only version I have used.

**Comment by BrentOzar** [comment]
Hi! Can you run the queries outside of Power BI to find out what rows are triggering the error? This shouldn't be happening with the default setups, so I'm guessing something else might be inserting duplicate rows, like an ETL process.

To get the queries, you can click Edit Queries in the Power BI ribbon.

**Comment by rabentho** [comment]
Issue was corrected in with the December update of the dashboard. I was able to run the query outside of Power BI, the issue was being caused by 2 rows having the exact same joinkey. One was a priority 40 and the other a priority 50 item. Thank you for the response.
