### ISSUE TITLE
sp_BlitzCache: parameters duplicated when query is run with different session options

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2213]
**Version of the script**
SELECT @Version = '7.91', @VersionDate = '20191202';

**What is the current behavior?**
When queries have multiple parameterized plans in the cache (like due to different session options) and the plans have different input parameters, the "Cached Execution Parameters" output shows all of them rather than filtering for the specific plan involved.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
CREATE OR ALTER PROC dbo.usp_SearchUsers @DisplayName NVARCHAR(40) AS
  SELECT * FROM dbo.Users WHERE DisplayName = @DisplayName;
GO
DBCC FREEPROCCACHE
SET ARITHABORT ON;
GO
EXEC usp_SearchUsers @DisplayName = 'Brent Ozar';
GO
SET ARITHABORT OFF;
GO
EXEC usp_SearchUsers @DisplayName = 'James Bond';
GO
sp_BlitzCache
```

You get two plans in the result set, and if you click on Cached Execution Parameters for either of 'em, you get:

`EXEC [dbo].[usp_SearchUsers]  @DisplayName = N'Brent Ozar', @DisplayName = N'James Bond'`

**What is the expected behavior?**
Just show the parameters that were used to build this particular plan.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
I think it's always been this way, just now discovering it.

**Comment by erikdarlingdata** [comment]
It has always been this way. I had it in there so people could see how different parameters potentially built different plans, but I can see how it might be confusing or annoying when there are a lot of parameters.

**Comment by BrentOzar** [comment]
Yeah, screw it, let's leave it in there. Came in handy for me this week. Closing.
