### ISSUE TITLE
sp_BlitzFirst duplicate column and potential error

### ISSUE THREAD

**Issue by sm8680** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2218]
@Version = '7.91'
@VersionDate = '20191202'
Line 1494 and 1495

                0 AS OpenTransactionCount,
                0 AS OpenTransactionCount      -- Duplicate\redundant and if not missing the ,
                r.query_hash

**Comment by BrentOzar** [comment]
Great catch! Fixed in the dev branch and it'll be in the January release. Thanks!
