### ISSUE TITLE
sp_DatabaseRestore: Restore DIFF backups with multiple files not posible

### ISSUE THREAD

**Issue by MichaelKeller1und1** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2220]
Hello

I am currently testing sp_DatabaseRestore and notice that a restore of a DIFF Bakcup with multiple files is not possible. With Fullbackup it works:
I uses the actual version from sp_DatabaseRestore 

Can you fix this?

**Comment by BrentOzar** [comment]
I don’t use that proc myself anymore, so if there’s a feature you’d like to see added (like handling multiple differential files), you would need to code it yourself, or reach out to other folks in the community to see if they’d be willing to code it for you (possibly for hire.) To learn more about that, read the contributing guide for This project, linked to from the home page of the project. Does this sound like something you’d be interested in tackling?

**Comment by BrentOzar** [comment]
I haven't heard back from you for over a month, so I'll go ahead and close this. If you change your mind and you'd like to work on it, check out the contributing guide here: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

Thanks anyway!
