### ISSUE TITLE
Multiple instance check for running services only

### ISSUE THREAD

**Issue by seniuka** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2224]
I have a few servers where our upgrade path has been adding a new instance of SQL with a new SQL version. For example 2008R2 to 2012, we have had to create a new instance but keep the server (since the OS is still 2012) then shut down and disable the old instance. The current blitz check does not validate if the installed instance services are running or not... so I have made a manual change in the code to validate the services are only counting running ones. 

The solution would be to add a loop to execute the xp_servicecontrol to collect the service status then add a where clause on the count to only pull in running instances.

Here is the code I have created to work around this within my environment.

```
IF OBJECT_ID('tempdb..#Instances') IS NOT NULL DROP TABLE #Instances;
		CREATE TABLE #Instances
            (
              Instance_Number NVARCHAR(MAX) ,
              Instance_Name NVARCHAR(MAX) ,
              Data_Field NVARCHAR(MAX),
			  Instance_state NVARCHAR(MAX),
			  InstanceID int identity(1,1)
            );

DECLARE @servicecontrol table (Instance_state NVARCHAR(MAX))
DECLARE @InstanceID int = 0, @InstanceIDCount int = 0, @Instance_Name NVARCHAR(MAX), @Instance_state NVARCHAR(MAX)

INSERT INTO #Instances (Instance_Number, Instance_Name, Data_Field)
EXEC master.sys.xp_regread @rootkey = 'HKEY_LOCAL_MACHINE',
							@key = 'SOFTWARE\Microsoft\Microsoft SQL Server',
							@value_name = 'InstalledInstances'
SELECT @InstanceIDCount = COUNT(*) FROM #Instances								
WHILE @InstanceID < @InstanceIDCount
BEGIN
	SET @InstanceID = @InstanceID + 1
	SELECT @Instance_Name = Instance_Name  FROM #Instances WHERE InstanceID = @InstanceID
	if @Instance_Name != 'MSSQLSERVER' 
	begin
		set @Instance_Name = 'MSSQL$' + @Instance_Name
	end									
	
	insert into @servicecontrol EXEC master.sys.xp_servicecontrol N'querystate',@Instance_Name
	select @Instance_state = Instance_state from @servicecontrol

	update #Instances set Instance_state = @Instance_state WHERE InstanceID = @InstanceID

	-- Clean up variables
	set @Instance_Name = null
	set @Instance_state = null
	delete from @servicecontrol

END								

IF (SELECT count(*) FROM #Instances where Instance_state = 'Running.') > 1
```

Hopefully this is something other people also want.
Thanks

**Comment by BrentOzar** [comment]
I'm a little hesitant to use an undocumented, unsupported stored proc (xp_servicecontrol) in sp_Blitz just because of the amount of support we have to do on it. Thanks, but I'm going to take a pass on this one - thanks for offering though! If you can do it with documented/supported commands, we'd be down with adding it.
