### ISSUE TITLE
sp_BlitzIndex missing index requests: add datatype to column list

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2227]
**Is your feature request related to a problem? Please describe.**
When I'm looking at the Consultant Toolkit output for missing indexes, I want to see the column datatypes before I take Clippy's word on an index.

For example, when I run this:

```
DropIndexes;
GO
SELECT AboutMe FROM dbo.Users WHERE Location = 'Antarctica';
GO 10
sp_BlitzIndex @TableName = 'Users'
GO
```

I get this in the missing index finding: 

EQUALITY: [Location] INCLUDES: [AboutMe] 

And I'd like it to use the same output style that we use in the Definition column of the first result set. If I create that above index, the Definition column looks like this:

[1 KEY] Location {nvarchar 200} [1 INCLUDE]  AboutMe {nvarchar -1}

So we probably want the missing index output to look like this:

EQUALITY: [Location] {nvarchar 200} INCLUDES: [AboutMe] {nvarchar -1}

**Describe alternatives you've considered**
Outputting all of the column definitions for all of the tables to a separate Consultant Toolkit tab, but that would take up a heck of a lot of space and we probably don't need it, and it'd involve back-and-forth lookups between tabs.

**Are you ready to build the code for the feature?**
Yeah, or maybe see if Erik wants to build it?

**Comment by BrentOzar** [comment]
Other things we may wanna test to make sure it'll work okay:

* SQL Server 2016, but the database is in 2008 compat mode
* Missing index requests with each of these in equality, inequality, and includes:
    * NVARCHAR(100), NVARCHAR(MAX)
    * VARCHAR(100), VARCHAR(MAX)
    * XML, JSON
    * TEXT, NTEXT
    * SMALLINT, INT, BIGINT
    * Dates

**Comment by BrentOzar** [comment]
This isn't quite working yet, but it's close enough for government work and horseshoes, so I'm going to accept it and start working on a tweak to it. Thanks for the pull request. It'll be in the August release with credit to you in the release notes.

**Comment by gdoddsy** [comment]
@BrentOzar - I'm planning to add in the missing commas in the next day or 3, did you want a new issue for that, or can I continue this issue? I don't mind either way, whatever makes your life easier.

**Comment by BrentOzar** [comment]
No worries! Yeah, let's do a new issue for that just because I wanna get the August release out this weekend.
