### ISSUE TITLE
sp_BlitzCache: Possible to get both parallel and nearly parallel warnings

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2234]
**Version of the script**
All of them through 7.91

**What is the current behavior?**
The check for nearly parallel only looks at query cost relative to cost threshold for parallelism. It doesn't look at if the plan is already parallel with a cost under CTFP.

For example, with CTFP at 50, this plan gets flagged as parallel and nearly parallel:

![image](https://user-images.githubusercontent.com/2136037/71623172-aae73280-2ba8-11ea-9af3-278facfa772a.png)

![image](https://user-images.githubusercontent.com/2136037/71623185-b8042180-2ba8-11ea-9862-ce818c9f8e93.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
The nearly parallel check should ignore plans that are parallel.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All of them. Will fix.

**Comment by BrentOzar** [comment]
Hahaha, that's awesome. Thumbs up, assigning you if that works.

**Comment by BrentOzar** [comment]
Good work! Merged, closing. Will be in the February release.
