### ISSUE TITLE
Add similar warnings for Table Spools as we have for Index Spools

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2235]
**Is your feature request related to a problem? Please describe.**
These are good things to call out in query plans, because they're often a sign that there's overly complex logic taking place in joins or where clauses. Not always, but enough to take a look.

**Describe the solution you'd like**
Look for expensive table spools, or table spools that dish out a lot of rows. 

**Describe alternatives you've considered**
Globally enabling trace flag 8690.

**Are you ready to build the code for the feature?**
Yes, I have it written locally, and I'm finishing up some testing.

**Comment by BrentOzar** [comment]
Woohoo! Nice work, sir!
