### ISSUE TITLE
sp_BlitzLock / XML parsing / semicolon expected

### ISSUE THREAD

**Issue by johnuhr** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2236]
Script @Version : 2.91 / @VersionDate : 2019-12-02
SQL Server @ProductVersionMajor: 13 / @ProductVersionMinor: 5233
Windows Server @windows_release: 6.3

When I execute the stored procedure I receive this error message:

Grab the initial set of XML to parse at Jan  2 2020 10:57:33:557AM
Msg 9411, Level 16, State 1, Procedure sp_BlitzLock, Line 194 [Batch Start Line 0]
XML parsing: line 24, character 100, semicolon expected

I need some help :)

**Comment by BrentOzar** [comment]
Sorry to hear that. My guess is that you're trying to run it in a database whose compatibility mode dates back to the good ol' days when dinosaurs roamed the earth. Try installing sp_BlitzLock in the master database, which on your server should be in the current compatibility level.

**Comment by johnuhr** [comment]
All my databases are in compatibility mode 130 and I have installed the procedures into the master database and I am running the procedure from the master database.

I have attached the CREATE EVENT SESSION for the XE named [system_health] (which I assume is the one being used by the mentioned procedure).

Any other ideas to what may be the reason?

[EVENT SESSION [system_health].txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/4016208/EVENT.SESSION.system_health.txt)

**Comment by johnuhr** [comment]
The default collation is Danish_Greenlandic_100_CS_AS (maybe the case sensitive setting has something to do with why I am receiving this error).

**Comment by BrentOzar** [comment]
OK, can you try it on another server? I don't have any other suggestions - it's working fine here.

**Comment by johnuhr** [comment]
It does look like is is a specific server issue - I suspect the collation:

USE [master];
DECLARE @Edition nvarchar(128) = (SELECT CAST(SERVERPROPERTY('Edition') AS NVARCHAR(128)) )
RAISERROR('@Edition = %s',0,1,@Edition)
DECLARE @ProductVersion nvarchar(128) = (SELECT CAST(SERVERPROPERTY('ProductVersion') AS NVARCHAR(128)) )
RAISERROR('@ProductVersion = %s',0,1,@ProductVersion)
DECLARE @Collation nvarchar(128) = (SELECT CAST(SERVERPROPERTY('Collation') AS NVARCHAR(128)) )
RAISERROR('@Collation = %s',0,1,@Collation)
DECLARE @path nvarchar(256) = N'system_health_0_132222696500980000.xel';
SELECT CONVERT(xml, event_data) AS deadlock_xml FROM sys.fn_xe_file_target_read_file(@path, null, null, null);
--------
Messages
--------
@Edition = Standard Edition (64-bit)
@ProductVersion = 13.0.5233.0
@Collation = Danish_Greenlandic_100_CS_AS
Msg 9411, Level 16, State 1, Line 13
XML parsing: line 24, character 100, semicolon expected

**Comment by BrentOzar** [comment]
OK, cool. So if you want it to work on your specific server, you're welcome to submit a pull request:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

Would you like to tackle that? If not, you can also read the contributing guide to see how to get other people to help write code for you, like sponsoring them to do it. If not, I'll close the issue if you don't respond within a week or two. (I just can't do free coding for every possible server.)

**Comment by johnuhr** [comment]
Thanks for responding :) It does look like the issue is related to the sql server.
