### ISSUE TITLE
sp_BlitzIndex run over all databases without @bringthepain

### ISSUE THREAD

**Issue by DBAdminDB** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2237]
**Version of the script**
v 7.91

**What is the current behavior?**
When i run "EXEC sp_BlitzIndex @GetAllDatabases =1 , @mode =3" even if there are more then 50 databases it goes over them all, even though i didnt expresed the "bringthepain"  parameter.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Go over all databases only if I use the "bringthepain" parameter

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
On all version this behavior is the same.

**Comment by BrentOzar** [comment]
Hmm, @Mode = 3 is the list of missing indexes. That should be pretty quick regardless of the number of databases. Are you having a problem where it's taking a long time? If so, can you elaborate a little more about the number of databases, length of time, and kind of hardware horsepower (CPU cores, memory, SQL Server version) involved? Thanks!

**Comment by DBAdminDB** [comment]
I cant recall now exactly how much time it took, but it was around 5 minutes. near the end i saw a cmd window running something, it may be connected?
There are 98 databases on this particular instance, but because I am hopping between servers I cant see now how much HP the server has.

maybe it was an extreme case, if it should go over all databases as you said, so its not a bug :)

if I will encounter it again I'll open a report here with all the needed information

**Comment by BrentOzar** [comment]
OK, sp_BlitzIndex doesn't run command windows, so I think we're dealing with something unrelated. If you can get to the point where you can reproduce this, you can reopen it with those details. Thanks!

**Comment by DBAdminDB** [comment]
Hi Brent, 

I've tried it again on *other* server.
server properties:
- 4 cores 
- 12 GB RAM
- 119 databases
- 2008 R2 SP3
- the total size of all databases is around 50 GB

it took 8:40 minutes but I stopped it because the server CPU went up to 100% on the last databases...
I've noticed that it got stuck on this step: "inserting data into #IndexSanity", I don't think that something is special about this step.

do you want me to check something else?

**Comment by BrentOzar** [comment]
Sorry about that! Fixed in the dev branch, and it'll be in the January release.
