### ISSUE TITLE
BlitzFirst when logging BlitzCache to table is causing 'Many Plans for One Query' when executing sp_Blitz

### ISSUE THREAD

**Issue by Adedba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2252]
Using the latest procs from the master branch: @Version = '7.91', @VersionDate = '20191202';

Tested with SQL2016:

Steps to reproduce: 

DBCC FREEPROCCACHE

Run BlitzFirst using example below with output tables 15 times (enough times to generate the plans)
`DECLARE @i INT = 1 

WHILE @i < 15
BEGIN 
	RAISERROR('Execution number %d',0,0,@i) WITH NOWAIT;

	EXEC sp_BlitzFirst 
	  @OutputDatabaseName = 'BlitzTest', 
	  @OutputSchemaName = 'dbo', 
	  @OutputTableName = 'BlitzFirst',
	  @OutputTableNameFileStats = 'BlitzFirst_FileStats',
	  @OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
	  @OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
	  @OutputTableNameBlitzCache = 'BlitzCache',
	  @OutputTableNameBlitzWho = 'BlitzWho';

	  SET @i+=1;
END`

Check the cache using the following query: 
`SELECT st.text,B.*
FROM 
(
	select qs.query_hash, pa.value
	FROM sys.dm_exec_query_stats qs
	CROSS APPLY sys.dm_exec_plan_attributes(qs.plan_handle) pa
	WHERE pa.attribute = 'dbid'
	GROUP BY qs.query_hash, pa.value
	HAVING COUNT(DISTINCT plan_handle) > 50
) as Plans
INNER JOIN (SELECT * from sys.dm_exec_query_stats) AS  B ON  Plans.query_hash = B.query_hash AND Plans.query_hash != 0x0000000000000000
CROSS APPLY sys.dm_exec_sql_text(B.sql_handle) AS st
WHERE st.text LIKE '%Blitz%'
ORDER BY query_hash ASC`

You will notice alot of queries in the results for the BlitzCache table creation and the thing that makes them unique if the PK contraint which has a generated NEWID(), see screenshot below: 
![image](https://user-images.githubusercontent.com/33764798/72188264-c98fc980-33f1-11ea-9122-6d6a586bf432.png)

Run sp_Blitz and you will see the the 'Many Plans for One Query' warning.

Looking at the code for sp_BlitzFirst I can see that the BlitzCache table has the following snippet as part of the table creation:
`CONSTRAINT [PK_' + CAST(NEWID() AS CHAR(36)) + '] PRIMARY KEY CLUSTERED (ID ASC));';`

As a test I replaced this with: 
`CONSTRAINT [PK_' +REPLACE(REPLACE(@OutputTableName,'[',''),']','') + '] PRIMARY KEY CLUSTERED(ID ASC))';`

I then dropped the Blitz tables so that I could confirm that creation would not fail and this completed successfully, ran it through the same 15 execution loop and checked the cache with the query used previously, this time no rows returned.

Ran sp_Blitz to confirm and warning no longer present 

 Checked the BlitzCache table and the PK is created as expected with the table with a naming convention of PK_BlitzCache.

**Comment by BrentOzar** [comment]
Great, thanks for the fix! Added it to the dev build and it'll be in the January release. Thanks!
