### ISSUE TITLE
sp_Blitz : Finding = System Database on C Drive. Quoted URL takes you to the wrong place.

### ISSUE THREAD

**Issue by DanielSalisbury** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2261]
**Version of the script**

7.91 / 2019-12-02 00:00:00.000

**What is the current behavior?**

The results of using sp_Blitz reports that the system databases are on the C Drive.
This is correct, my bad. 
The corresponding URL states to go to https://BrentOzar.com/go/cdrive

**If the current behavior is a bug, please provide the steps to reproduce.**

The corresponding URL states to go to https://BrentOzar.com/go/cdrive
This then re-directs you to https://www.brentozar.com/blitz/user-databases-on-c-drive/

**What is the expected behavior?**

I would assume it is meant to go to https://www.brentozar.com/blitz/system-databases-on-c-drive/

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Microsoft SQL Server 2019 (RTM-CU1) (KB4527376) - 15.0.4003.23 (X64)   Dec  6 2019 14:53:33   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19041: ) (Hypervisor) 

Untested in previous versions, First-time use on this box.

**Comment by BrentOzar** [comment]
Thanks! I edited the https://BrentOzar.com/go/cdrive page to have info on both the user and system databases. (It's probably not the fix you were expecting, but it's the fastest one for me to get done.) Thanks!
