### ISSUE TITLE
sp_BlitzIndex: Include number of writes in Details column for unused indexes

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2266]
**Is your feature request related to a problem? Please describe.**
For indexes with a high read/write ratio, the writes are included in the details column. We should do that for unused indexes, too.

**Describe the solution you'd like**
I'd like... to see... the writes... Brent...

**Describe alternatives you've considered**
Scrolling to the right to look at them. I didn't like it. 

**Are you ready to build the code for the feature?**
Yessireebob. Brent. Sorry.

**Comment by BrentOzar** [comment]
I love it! Two thumbs up. Would up thumbs again.

**Comment by BrentOzar** [comment]
Looks perfect, thanks! Merged, will be in the February release.
