### ISSUE TITLE
Cannot convert BIGINT sp_BlitzIndex @GetAllDatabases = 1

### ISSUE THREAD

**Issue by jbarnard84** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2268]
I get an error in sp_BlitzIndex
Msg 50000, Level 16, State 2, Procedure sp_BlitzIndex, Line 1865 [Batch Start Line 2]
PredictiveModeling database failed to process. Arithmetic overflow error converting expression to data type bigint.

This occurs on the CAST(ic.last_value AS BIGINT)  for the following:

SELECT 5,
					s.name,    
                    si.object_id, 
                    si.index_id, 
                    sc.key_ordinal, 
                    sc.is_included_column, 
                    sc.is_descending_key,
                    sc.partition_ordinal,
                    c.name as column_name, 
                    st.name as system_type_name,
                    c.max_length,
                    c.[precision],
                    c.[scale],
                    c.collation_name,
                    c.is_nullable,
                    c.is_identity,
                    c.is_computed,
                    c.is_replicated,
                    c.is_sparse,
                    c.is_filestream,
                    CAST(ic.seed_value AS BIGINT),
                    CAST(ic.increment_value AS INT),
                    CAST(ic.last_value AS BIGINT),
                    ic.is_not_for_replication
                FROM    [PredictiveModeling].sys.indexes si
                JOIN    [PredictiveModeling].sys.columns c ON
                    si.object_id=c.object_id
                LEFT JOIN [PredictiveModeling].sys.index_columns sc ON 
                    sc.object_id = si.object_id
                    and sc.index_id=si.index_id
                    AND sc.column_id=c.column_id
                LEFT JOIN [PredictiveModeling].sys.identity_columns ic ON
                    c.object_id=ic.object_id and
                    c.column_id=ic.column_id
                JOIN [PredictiveModeling].sys.types st ON 
                    c.system_type_id=st.system_type_id
                    AND c.user_type_id=st.user_type_id
				JOIN [PredictiveModeling].sys.objects AS so  ON si.object_id = so.object_id
																		  AND so.is_ms_shipped = 0
				JOIN [PredictiveModeling].sys.schemas AS s ON s.schema_id = so.schema_id
                WHERE si.index_id in (0,1) OPTION (RECOMPILE);

**Comment by Adedba** [comment]
As a test what happens if you execute the above code replacing CAST(ic.last_value AS BIGINT) with:
CAST(ic.last_value AS sql_variant)  or CAST(ic.last_value AS DECIMAL(38,0)) , I imagine the data type of your identity column causing the problem is a numeric or decimal which exceeds the bigint data type limit.  I imagine the DECIMAL option may be the preferred change but Brent may want to decide on that.

**Comment by BrentOzar** [comment]
@jbarnard84 can you respond to AdeDBA's question? That'll help us build a good fix. Thanks!

**Comment by jbarnard84** [comment]
HI Brent, AdeDBA,

Yes, both of these CAST's work successfully.  I also ran the original code and it still does not work, so I think either of these CAST's will work.


Thanks for replying so quickly.

**Comment by BrentOzar** [comment]
Right, but what's the output of those casts? Just trying to get a handle on what kind of data we're dealing with. Sorry if that wasn't clear. Thanks!

**Comment by jbarnard84** [comment]
Hi,

I am going to attach a small portion of a spreadsheet results and a screen shot where I moved those two CAST to the beginning and Order By DESC.  The first 2 rows have a massive value.  This could just be from poor index development on our side.
[sp_BlitzIndex_2268_CAST.xlsx](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/4117518/sp_BlitzIndex_2268_CAST.xlsx)
![sp_BlitzIndex_CAST_2268](https://user-images.githubusercontent.com/60272898/73182606-95492800-40d6-11ea-9768-5f49c9262407.png)

**Comment by BrentOzar** [comment]
Ouch. Yep, that's a giant number alright. A few ways we could fix this:

* Switch the data type for #IndexColumns.last_value from BIGINT to something else - looks relatively safe, only used in a handful of places to check for abnormal psychology warnings about IDs running out of space
* Use SQL Server 2012's new TRY_CAST functionality. This would break sp_BlitzIndex on SQL Server 2008R2 & prior.
* In the population of #IndexColumns, try to add a filter for these kinds of situations (skip populating just the last_value column when the indexed column is a decimal or float - but we would lose the warnings in this situation, although I'm not sure the warnings are valuable anyway here)

If anybody has passionate opinions on this, holler. Will let it set here for a while before I tackle it.

**Comment by BrentOzar** [comment]
@jbarnard84 can you give this version a shot and see if it errors out: https://raw.githubusercontent.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/dev/sp_BlitzIndex.sql

Thanks!

**Comment by BrentOzar** [comment]
@jbarnard84 I haven't heard back from ya, so I'm closing this. It's in the May release.
