### ISSUE TITLE
Consultant Toolkit only: sp_BlitzCache failing with Arithmetic overflow error converting expression to data type nvarchar

### ISSUE THREAD

**Issue by jbconsult007** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2270]
Following is output from SQL Server Checkup calling sp_BlitzCache on a particularly beefy/busy server.  Some calls succeed but most fail for given error.  If additional info needed to review please let me know:

13:10:37.5456 Info - Calling sqlData.ExecuteQuery to execute query 'sp_BlitzCache by Avg Reads'
13:11:18.6060 Error - Source: .Net SqlClient Data Provider; Message: Arithmetic overflow error converting expression to data type nvarchar.;
13:11:18.6449 Info - Calling sqlData.ExecuteQuery to execute query 'sp_BlitzCache by XPM'
13:11:41.7507 Info - Export Query Data to Excel.
13:11:42.5994 Info - Write result [0] data to worksheet 'Plans Executions'.
13:11:43.3165 Info - Calling sqlData.ExecuteQuery to execute query 'sp_BlitzCache by Executions'
13:11:53.9275 Info - Export Query Data to Excel.
13:11:54.8259 Info - Write result [0] data to worksheet 'Plans Executions'.
13:11:55.6631 Info - Calling sqlData.ExecuteQuery to execute query 'sp_BlitzCache by Writes'
13:12:23.6396 Error - Source: .Net SqlClient Data Provider; Message: Arithmetic overflow error converting expression to data type nvarchar.;
13:12:23.6545 Info - Calling sqlData.ExecuteQuery to execute query 'sp_BlitzCache by Memory'
13:12:39.6464 Error - Source: .Net SqlClient Data Provider; Message: Arithmetic overflow error converting expression to data type nvarchar.;
13:12:39.6613 Info - Calling sqlData.ExecuteQuery to execute query 'sp_BlitzCache by Avg Writes'
13:13:23.1879 Error - Source: .Net SqlClient Data Provider; Message: Arithmetic overflow error converting expression to data type nvarchar.;
13:13:23.2238 Info - Calling sqlData.ExecuteQuery to execute query 'sp_BlitzCache by Spills'
13:13:48.5977 Error - Source: .Net SqlClient Data Provider; Message: Arithmetic overflow error converting expression to data type nvarchar.;
13:13:48.6134 Info - Calling sqlData.ExecuteQuery to execute query 'sp_BlitzCache by Avg Spills'
13:14:24.0149 Error - Source: .Net SqlClient Data Provider; Message: Arithmetic overflow error converting expression to data type nvarchar.;
13:14:24.0540 Info - Calling sqlData.ExecuteQuery to execute query 'sp_BlitzCache by CPU ByHash'
13:15:07.5765 Info - Export Query Data to Excel.
13:15:09.0486 Info - Write result [0] data to worksheet 'Plans CPU ByHash'.
13:15:10.2793 Info - Calling sqlData.ExecuteQuery to execute query 'Memory Perfmon'

**Comment by BrentOzar** [comment]
OK, cool. Sure, try running sp_BlitzCache @SortOrder = 'all', @Debug = 1. That'll give you the queries in the messages tab, and you're looking for the last query that runs before the arithmetic overflow error hits.

**Comment by jbconsult007** [comment]
Hmm... calling "sp_BlitzCache @SortOrder = 'all', @debug = 1" directly works fine.  But reproducible in the utility.

**Comment by BrentOzar** [comment]
Ah! Makes sense, OK, good. I'm going to add a separate issue in the private Github repo that we use for the Consultant Toolkit, and link it here. I'll leave this issue open though so I can update it when we fix it.

**Comment by BrentOzar** [comment]
Good news! This is fixed in the July release. Thanks for your patience!

**Comment by jbconsult007** [comment]
That's great news.  Thanks. 💪
