### ISSUE TITLE
sp_DatabaseRestore: want ability to stay in single_user mode, but add WITH STANDBY

### ISSUE THREAD

**Issue by reutaaa** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2275]
**Is your feature request related to a problem? Please describe.**
we use sp_databaseRestore to create a standby version of our databases used for reports.
we use the @ExistingDBAction and setting the database to single user mode to prevent other sessions taking access on the database and interrupt the restore process.
1. we've noticed that after every RESTORE LOG WITH STANDBY command, the database gets back to MULTI_USER state thus enabling other sessions to interrupt.

2. another thing when setting the restored database to single_user mode is that if there are no logs to restore, the database remains in SINGLE_USER mode.

**Describe the solution you'd like**
1. set the restored DB to SINGLE_USER mode prior to every RESTORE LOG command:
IF @ExistingDBAction = 1 AND @StandbyMode = 1
BEGIN
					RAISERROR('Setting single user', 0, 1) WITH NOWAIT;
					SET @sql = N'ALTER DATABASE ' + @RestoreDatabaseName + ' SET SINGLE_USER WITH ROLLBACK IMMEDIATE; ' + NCHAR(13);
					IF @Debug = 1 OR @Execute = 'N'
					BEGIN
						IF @sql IS NULL PRINT '@sql is NULL for SINGLE_USER';
						PRINT @sql;
					END;
					IF @Debug IN (0, 1) AND @Execute = 'Y'
						EXECUTE @sql = [dbo].[CommandExecute] @Command = @sql, @CommandType = 'ALTER DATABASE SINGLE_USER', @Mode = 1, @DatabaseName = @Database, @LogToTable = 'Y', @Execute = 'Y';
				END

2. at the end of all restoring files - check if the database remains in SINGLE_USER and setting back it to MULTI_USER:
IF (SELECT user_access_desc FROM sys.databases where database_id = @RestoreDatabaseID) = 'SINGLE_USER'
				BEGIN
					RAISERROR('Setting multi user', 0, 1) WITH NOWAIT;
					SET @sql = N'ALTER DATABASE ' + @RestoreDatabaseName + ' SET MULTI_USER WITH ROLLBACK IMMEDIATE; ' + NCHAR(13);
					IF @Debug = 1 OR @Execute = 'N'
					BEGIN
						IF @sql IS NULL PRINT '@sql is NULL for MULTI_USER';
						PRINT @sql;
					END;
					IF @Debug IN (0, 1) AND @Execute = 'Y'
						EXECUTE @sql = [dbo].[CommandExecute] @Command = @sql, @CommandType = 'ALTER DATABASE MULTI_USER', @Mode = 1, @DatabaseName = @Database, @LogToTable = 'Y', @Execute = 'Y';
				END
            END

**Describe alternatives you've considered**

**Are you ready to build the code for the feature?**
script above

**Comment by reutaaa** [comment]
suggested additions added to comment. thanks

**Comment by BrentOzar** [comment]
Dumb question: why are you using the combination of WITH STANDBY and SINGLE_USER mode?

WITH STANDBY is to let people into the database to run report queries. It's the exact opposite of what you want if you're trying to keep people out of the database. If you're using it for a reporting server, you generally want to simply stop doing restores during business hours (like 8AM-5PM, and starting at 5PM, you go back to restoring logs (but not in standby mode).

Can you tell me more about what you're trying to do, and why?

**Comment by reutaaa** [comment]
Hi Brent,

that's exactly my purpose.
this is a copy of our prod databases used for reports in another instance.
the restore process runs daily every night and restores log files of the
last 24H
but sometimes there are some sporadic sessions from applications the
developers can't explain,
a developer that decided to check something at off working hours, etc.,
so we use the SINGLE_USER mode (killing connections was tested and was not
sufficient)

can i restore all log files without setting STANDBY for each log and then
setting STANDBY only at the end of the files list?
i believe that is another alternative but also requires changes in the SP,
right?

thanks,
Reut

**Comment by BrentOzar** [comment]
OK, in that case, if you want to use the proc for that purpose, you would need to contribute the code changes that you want. Here's the contributing guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

**Comment by BrentOzar** [comment]
I haven't heard back from you, so I'm closing this. If you do decide that you want to move forward with it, let me know when you're ready to start working on it. Thanks!
