### ISSUE TITLE
sp_BlitzIndex: 0 read, 0 write indexes

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2280]
**Is your feature request related to a problem? Please describe.**
I'm thinking this is a good fit for mode 0 (but it might also help with the 10k line cutoff in mode 4, too 👀👀👀). Filter out indexes that have no reads or writes. It'll make the output more succinct, and help people focus on things that will have an impact.

**Describe the solution you'd like**
Great taste, less filling

**Describe alternatives you've considered**
Worse taste, more filling

**Are you ready to build the code for the feature?**
Yeah, if the nice people who read these things think it'd be useful.

**Comment by BrentOzar** [comment]
Oh that totally makes sense in both modes.

**Comment by erikdarlingdata** [comment]
We could do the filter [here](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzIndex.sql#L1187), on the insert to `#IndexSanity`. 

That could have downstream effects on what data is populated in other parts of the proc, since that table drives a few other processes. If we truly don't care about 0 read, 0 write indexes, this isn't a problem. I'm just not sure if it would keep them from showing up in Mode 1 or 2 output.

The alternative is to add the filter to each mode 0/4 check where it would make sense. This'd take some more work, but whatever. 

Up to you @BrentOzar!

**Comment by BrentOzar** [comment]
I like that approach - it's fast and easy. 

I can think of two times when this will cause an issue:

* In production servers that were recently restarted - so we could work around that by having a parameter @IncludeIndexesWithoutActivity, default to 0. If the server has been up for < 1 day, then set this to 1.
* In development servers where workloads aren't running - but I wouldn't use @Mode = 0 or 4 in that scenario anyway, just @Mode = 2. I would say if @Mode = 2, then we should set @IncludeIndexesWithoutActivity = 1 anyway?

I was trying to think of ways it could backfire - for example, a table where OTHER indexes are getting reads/writes, and you're trying to dedupe them, but...the only way that would happen is if the table was getting updates, but not inserts/deletes. (Or if the 0-read-0-write index was filtered.) Those scenarios just don't resonate with me though.

**Comment by BrentOzar** [comment]
I should add - when I say I like the approach, I mean skipping them early on into the insert into #IndexSanity. I know it's going to cause slightly invalid results on edge case scenarios, like showing "0 indexes exist" if Clippy's recommending a missing index on that table, but if the index isn't getting any writes, that means there are no inserts or deletes happening, so,...I don't really care.

**Comment by erikdarlingdata** [comment]
Cool, will do!

**Comment by BrentOzar** [comment]
Merged! Thanks sir, will be in the February release.
