### ISSUE TITLE
sp_BlitzLock: Object names not populated correctly

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2282]
**Version of the script**
SELECT @Version = '2.92', @VersionDate = '20200123';

**What is the current behavior?**
Object names don't populate in the final output

**If the current behavior is a bug, please provide the steps to reproduce.**
Just run the script, heh

**What is the expected behavior?**
Object names should populate in the final result set

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All, it used to work. This is a bug introduced in https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/commit/f00cd13cbd245ebf710e820eb5495c947af637f8 where event_date is converted to a datetime.

Which messes up this:

![image](https://user-images.githubusercontent.com/2136037/74234758-8f894000-4c9b-11ea-8210-b463a25eda44.png)

Because these don't match:

![image](https://user-images.githubusercontent.com/2136037/74234779-a0d24c80-4c9b-11ea-944d-c861c6a80826.png)

I'm fixing this in another PR to add Victim Only output.

**Comment by BrentOzar** [comment]
Awesome! Thanks, sir. Merged, will be in the February release.
