### ISSUE TITLE
sp_BlitzIndex: Add Mode = 5 to build cleanup scripts

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2284]
**Is your feature request related to a problem? Please describe.**
I want to add a new mode that will generate sensible cleanup scripts so I don't have to do it in Excel. What I find quite often is that once I list out unused and low utilization indexes, a lot of the overlapping indexes disappear. It's generally a hassle to do this efficiently, especially when there's a lot of indexes to check back on.

**Describe the solution you'd like**
Run in Mode 5, get output to paste into a script.

**Describe alternatives you've considered**
Diazepam, that's valium, Temazepam, Lithium.

**Are you ready to build the code for the feature?**
Yes, but not quickly. I'm open to feedback on any of the details below.

**MORE DETAILS!**
* Server must have 7 days of uptime to run.
* Tables have to be of a decent size, like around 500k rows
* I wanna skip over any 0 read/0 write stuff.

 **IMPORTANT** 
There has to be a section that lists problems where a decision couldn't be made, and maybe why. People should be aware there's more work to do, and some of it needs a human eyeball. Or two. Or a coin toss.
 
**Step 1: Unused indexes**
 * Start with unused indexes: 0 reads and > 100k writes
 * Then low utilization indexes < 1k reads, > 10,000x writes

**Step 2: Overlapping**

Once those are out, do we have any exact key dupes?
  * Screen out PK/CX, Unique, Filtered, etc.
  * Merge include columns
   * Stuff I'd love to be rational about:
    - Long strings
    - More than 10 includes better have _a lot_ of reads, but skipping for v1

Borderline dupes:
 * I think the only ones I'd feel great about would be superset/subset matches with different includes.
 
In other words: 
 * index_1: (a, b, c) include(d, e)
 * index_2: (a, b) include(f)
 
Would result in index_3: (a, b, c) include(d, e, f)
 
I don't wanna go after index_1(a, b, c) vs index_2(a, c, b)
  * My thinking is any un-useful indexes would be caught earlier on in the process, and the remainders would be beneficial. 
 * Same deal here, likely skipping over > 10 includes

**Heaps:**
 * Only with forwarded fetches (the deletes thing is often a bust)
 * Only with > 100k rows

Suggest a clustered index. This is tough with the output now, because we get index definitions, but not full table definitions anywhere. I get why, I'm not asking for that. 

 * First, look for not-nullable integer columns
 * Any with Id or Key in the name?
 * Second, look for not-nullable date/datetime columns
 * These could satisfy most CX reqs
 
Include rebuild commands for people who can't create them. Probably warn about rebuilding Heaps with > 5 nonclustered indexes or something, right?

**Comment by BrentOzar** [comment]
Yeah, basically this is what we're gradually adding in SQL ConstantCare. I thought about doing it in sp_BlitzIndex, but I wanted to see activity over the course of several days, and I wanted it to be unit-testable, so I went with that. But I'm totally okay with you doing it in here if you want!

**Comment by erikdarlingdata** [comment]
Oh cool! Right now I have an Excel file I paste stuff into that does a lot of this, but... I didn't wanna add an Excel file here, or ask people to run a macro, hahaha.

**Comment by BrentOzar** [comment]
I'm going to close this for now - if you want to come back and work on it, holler and I can reopen it.
