### ISSUE TITLE
sp_BlitzIndex: Inflates column sizes for NVARCHAR columns

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2285]
**Version of the script**
`SELECT @Version = '7.92', @VersionDate = '20200123'`

I was looking into #2227 when I noticed...

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/2136037/74244579-a6399200-4caf-11ea-84da-72c5325ce51a.png)

The actual lengths are: `NVARCHAR(40)`, `NVARCHAR(100)`, and `NVARCHAR(250)`. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Create and index on some nvarchar columns and watch the data sizes magickally double.

**What is the expected behavior?**
Accuracy!

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
I don't think this has ever worked, no.

**Comment by BrentOzar** [comment]
Hahaha, that's so awesome - we used to have the opposite problem: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/1068

**Comment by erikdarlingdata** [comment]
I thought that sounded familiar. Crap.
