### ISSUE TITLE
sp_BlitzCache: Selects w/ Writes may fire incorrectly for stored procedures

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2290]
**Version of the script**
All of them since I added this check :(

**What is the current behavior?**
This check matches on the QueryHash, but the way the XML is parsed into temp tables, all plans are associated with all query hashes. So for a proc like this, you'll see that a select did writes even if it didn't:

```
CREATE PROC dbo.Wronged
AS
BEGIN
SET NOCOUNT, XACT_ABORT ON;
    SELECT *
    INTO #Badges
    FROM dbo.Badges AS b
    WHERE b.Name = N'Popular Question'
    
    
    SELECT TOP 1 * 
    FROM dbo.Badges AS b 
    WHERE b.Name = N'Popular Question'
END
GO 

EXEC dbo.Wronged

EXEC sp_BlitzCache @StoredProcName = 'Wronged', @ExpertMode = 1, @Debug = 1;
```

**If the current behavior is a bug, please provide the steps to reproduce.**
See above

**What is the expected behavior?**
Don't be goofy

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All of them

**Comment by BrentOzar** [comment]
Thanks sir! Merged into dev, will be in the February release.
