### ISSUE TITLE
Remove IX_ prefix from the create index statements in BlitzIndex

### ISSUE THREAD

**Issue by gdoddsy** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2292]
**Is your feature request related to a problem? Please describe.**
Based on posts/suggestions/arguments from Brent and Erik that IX_ is pointless in an index name, BlitzIndex should not suggest creating it with IX_

**Describe the solution you'd like**
Remove the IX_ prefix from BlitzIndex missing index request details

**Are you ready to build the code for the feature?**
I'm happy to build it

**Comment by BrentOzar** [comment]
I love it! Great idea. Go for it! Thanks.

**Comment by BrentOzar** [comment]
I know you wanted to do this, hahaha, but I was in the code already and prepping for this month's release, so I went ahead and knocked it out. Thanks though!

**Comment by gdoddsy** [comment]
I'm happy to not do work
