### ISSUE TITLE
"sp_executeSQL" in Uninstall.sql needs to be "sp_executesql" for case-sensitive collations.

### ISSUE THREAD

**Issue by Protiguous** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2307]
First Responder Kit Uninstaller Script "Uninstall.sql" as of 2020-19-02.

The letters SQL are capitalized in the command "EXEC sp_executeSQL @innerSQL, N'@SQL nvarchar(max) OUTPUT', @SQL = @SQL OUTPUT;".

This will fail to execute on case-sensitive collations, "sp_executeSQL" needs to be "sp_executesql".

**Comment by BrentOzar** [comment]
Thanks for the heads up. Fixed in the dev branch, and it'll be in the March release.
