### ISSUE TITLE
Problem with @FilterPlansByDatabse in sp_BlitzFirst

### ISSUE THREAD

**Issue by scareycalabrio** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2311]
```
            ;WITH a AS
                (
                SELECT CAST(1 AS BIGINT) f, CHARINDEX(',', @FilterPlansByDatabase) t, 1 SEQ
                UNION ALL
                SELECT t + 1, CHARINDEX(',', @FilterPlansByDatabase, t + 1), SEQ + 1
                FROM a
                WHERE CHARINDEX(',', @FilterPlansByDatabase, t + 1) > 0
                )
            INSERT #FilterPlansByDatabase (DatabaseID)
                SELECT SUBSTRING(@FilterPlansByDatabase, f, t - f)
                FROM a
                WHERE SUBSTRING(@FilterPlansByDatabase, f, t - f) IS NOT NULL
                OPTION (MAXRECURSION 0);
```
Line 990... The insert into #FilterPlansByDatabse is failing on the insert. DatabaseID INT... SUBSTRING() isn't INT . Missing column? wrong code? Is the intended purpose parsing a list then looking up the db ids?

**Comment by BrentOzar** [comment]
Wow, I didn't even remember that parameter existed! Looks like the code hasn't been changed in over 4 years, so I'm not sure if that feature ever worked. I did a quick fix just now in the dev branch - can you grab that and see if it works to do what you're trying to do? (At least the insert works now.)

**Comment by scareycalabrio** [comment]
`            ;WITH a AS
                (
                SELECT CAST(1 AS BIGINT) f, CHARINDEX(',', @FilterPlansByDatabase) t, 1 SEQ
                UNION ALL
                SELECT t + 1, CHARINDEX(',', @FilterPlansByDatabase, t + 1), SEQ + 1
                FROM a
                WHERE CHARINDEX(',', @FilterPlansByDatabase, t + 1) > 0
                )
			, b AS (
				SELECT database_id dbids
				FROM sys.databases d
				WHERE EXISTS (SELECT 1/0 FROM a where SUBSTRING(@FilterPlansByDatabase, f, t - f) = d.name)
			)
            INSERT #FilterPlansByDatabase (DatabaseID)
                SELECT dbids 
                FROM b
                --WHERE SUBSTRING(@FilterPlansByDatabase, f, t - f) IS NOT NULL
				OPTION (MAXRECURSION 0);`

This would be a worse way to fix the issue? wasn't expecting such a speedy reply.

**Comment by BrentOzar** [comment]
That'd probably be fine too - I don't worry too much about fine grained performance on stuff like this where the query won't run too often, and it's hard to predict the performance of stuff like sys.databases across different versions. Glad it worked!
