### ISSUE TITLE
PowerBI Desktop Overview is empty

### ISSUE THREAD

**Issue by Brianc-DBA** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2316]
**Version of the script**
7.93, 20200217
**What is the current behavior?**
The First Responder Kit.pbix overview screen is empty

**If the current behavior is a bug, please provide the steps to reproduce.**
0. Updated PowerBI Desktop to the December 2019 version (tried all steps without, thought this might make a difference but didn't).
1. Updated the SQL Job which runs every 15 minutes to include the additional line as per the instructions (@OutputTableNameBlitzWho = 'BlitzWho';)
2. Change data source to an appropriate server / database
3. Refresh data

**What is the expected behavior?**
Overview will refresh with all data

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
 SQL 2008 R2, Windows 10 (Desktop), Windows 2012 R2 (database server) .  It worked the last time I updated it - The January version of the file has data.  I will try to attach both versions; they use the same data source.

**Comment by Brianc-DBA** [comment]
It doesn't seem to want me to attach .jpg files here... but the February one is blank and the January one has data for the same data source.

**Comment by BrentOzar** [comment]
Hi. I just verified that it works fine on currently supported versions of Power BI Desktop (2020 Feb) and SQL Server (2012-2019.) I bet it isn't a version thing though - I bet you just didn't notice the filter pane on the right side of Power BI:

<img width="270" alt="Screen Shot 2020-02-29 at 2 26 52 PM" src="https://user-images.githubusercontent.com/245462/75615991-c8c90900-5aff-11ea-91d4-c25a898e357d.png">

You can pick servers, date ranges, etc. there.
