### ISSUE TITLE
Raise Error when running sp_BlitzLock

### ISSUE THREAD

**Issue by Ernesto-Ibanez** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2317]
**Version of the script**
/****** Object:  StoredProcedure [dbo].[sp_BlitzLock]    Script Date: 28/02/2020 02:37:49 p. m. ******/

**What is the current behavior?**
Grab the initial set of XML to parse at Feb 28 2020  8:04:19:573PM
Parse process and input buffer XML Feb 28 2020  8:04:35:877PM
Parse execution stack XML Feb 28 2020  8:04:35:937PM
Grab the full resource list Feb 28 2020  8:04:35:937PM
Parse object locks Feb 28 2020  8:04:35:953PM
Parse page locks Feb 28 2020  8:04:35:967PM
Parse key locks Feb 28 2020  8:04:35:983PM
Parse RID locks Feb 28 2020  8:04:36:013PM
Parse row group locks Feb 28 2020  8:04:36:027PM
Parse parallel deadlocks Feb 28 2020  8:04:36:057PM
Get rid of parallel noise Feb 28 2020  8:04:36:073PM
Get rid of nonsense Feb 28 2020  8:04:36:087PM
Update some nonsense part 1 Feb 28 2020  8:04:36:087PM
Update some nonsense part 2 Feb 28 2020  8:04:36:103PM
Get Agent Job and Step names Feb 28 2020  8:04:36:103PM
Msg 229, Level 14, State 5, Line 19
The SELECT permission was denied on the object 'sysjobsteps', database 'msdb', schema 'dbo'.
Check 1 Feb 28 2020  8:04:36:117PM
Check 2 objects Feb 28 2020  8:04:36:117PM
Check 2 indexes Feb 28 2020  8:04:36:133PM
Check 3 Feb 28 2020  8:04:36:133PM
Check 4 Feb 28 2020  8:04:36:133PM
Check 5 Feb 28 2020  8:04:36:133PM
Check 6 Feb 28 2020  8:04:36:147PM
Check 7 part 1 Feb 28 2020  8:04:36:163PM
Check 7 part 2 Feb 28 2020  8:04:36:177PM
Check 8 Feb 28 2020  8:04:36:177PM
Check 9 Feb 28 2020  8:04:36:193PM
Check 10 Feb 28 2020  8:04:36:193PM
Check 11 Feb 28 2020  8:04:36:193PM
Check 12 Feb 28 2020  8:04:36:207PM
Results 1 Feb 28 2020  8:04:36:207PM
Findings Feb 28 2020  8:04:36:223PM
Done Feb 28 2020  8:04:36:223PM

Completion time: 2020-02-28T14:04:37.2069754-06:00

**If the current behavior is a bug, please provide the steps to reproduce.**
Just EXEC sp_BlitzLock

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Engine
SQL Server Express Edition

Class
db.t2.small
AWS Under RDS

Version: Microsoft SQL Server 2017 (RTM-CU16) (KB4508218) - 14.0.3223.3 (X64)   Jul 12 2019 17:43:08   Copyright (C) 2017 Microsoft Corporation  Express Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)

**Comment by BrentOzar** [comment]
Fixed in the dev branch, and it'll be in the March release. Thanks!
