### ISSUE TITLE
BlitzCache data table not being cleaned up

### ISSUE THREAD

**Issue by sixten** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2320]
**Version of the script**
`SELECT @Version = '7.93', @VersionDate = '20200217';`

**What is the current behavior?**
We've had sp_BlitzFirst running on a scheduled basis, and configured to save data to tables, for a couple of years. Recently, one of our DBAs pointed out that the BlitzCache table had grown quite large. Upon inspection, it turned out that we had data in there from back to the beginning of our usage.

In order to confirm that this wasn't a bug you'd fixed (and because of your bug reporting policy for older versions), we truncated the table, updated the sprocs, and waited. As of this morning (9 March), there's data back to 25 February in the table.

It appears to me that [there's code in sp_BlitzFirst](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/sp_BlitzFirst.sql#L2880) that's intended to clean up that table. I'm not sure why it's not doing so. The other tables _do_ appear to get cleaned up as expected.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Install sp_BlitzFirst and sp_BlitzCache.
2. Schedule execution of sp_BlitzFirst, with default parameters.
3. Wait.

Here's how we're invoking the sproc:

```
EXEC sp_BlitzFirst
  @OutputDatabaseName = 'DBAtools',
  @OutputSchemaName = 'dbo',
  @OutputTableName = 'BlitzFirst',
  @OutputTableNameFileStats = 'BlitzFirst_FileStats',
  @OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
  @OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
  @OutputTableNameBlitzCache = 'BlitzCache'
```

**What is the expected behavior?**
Older data is removed from the BlitzCache table, keeping it at a finite size.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2016 on Windows 2016.
It doesn't appear that it's ever worked _for us_, but I can't say with any certainty whether it works in general.

**Comment by BrentOzar** [comment]
OK, I'm out on vacation for several weeks, so you may need to troubleshoot it yourself by going through the code if you need a quick resolution. Otherwise, I'll take a look when I get back in April.

**Comment by Adedba** [comment]
Unfortunately @Debug = 1 does not show the cleanup statements however the cleanup code for BlitzCache is wrapped in an IF EXISTS clause: 

`SELECT * FROM sys.objects o 
                        INNER JOIN sys.parameters pMB ON o.object_id = pMB.object_id AND pMB.name = '@MinutesBack'
                        INNER JOIN sys.parameters pCDO ON o.object_id = pCDO.object_id AND pCDO.name = '@CheckDateOverride'
                        WHERE o.name = 'sp_BlitzCache'`

Is your agent job running within the master database? I did a quick test with the above code using master and a user DB , the master DB returns a row but the user database does not.. just a thery - let us know.

**Comment by sixten** [comment]
Yes, the job is running in master. And that existence test must be passing, because there's data flowing into the BlitzCache table.

**Comment by Adedba** [comment]
What happens if you run the same command in SSMS? any errors?

might be worth popping in a `RAISERROR('%s',0,0,@StringToExecute) WITH NOWAIT;` just so you can see the command that gets created:

![image](https://user-images.githubusercontent.com/33764798/76340801-13166b00-62f4-11ea-8450-b925db3671f6.png)

**Comment by sixten** [comment]
I'm not sure which "same command" you mean, but…

The existence check in your previous message definitely runs without error, and finds our installation of `sp_BlitzCache`.

If I pull the code for the delete, shown in your screenshot, out, it generates this string (line breaks added):

```
IF EXISTS(SELECT * FROM DBAtools.INFORMATION_SCHEMA.SCHEMATA WHERE QUOTENAME(SCHEMA_NAME) = 'dbo')
DELETE DBAtools.dbo.[BlitzCache]
WHERE ServerName = @SrvName AND CheckDate < @CheckDate;
```

That seems like a weird test, since it's checking for the existence of the schema and not the table, and it doesn't pass, either:

```
IF EXISTS(SELECT * FROM DBAtools.INFORMATION_SCHEMA.SCHEMATA WHERE QUOTENAME(SCHEMA_NAME) = 'dbo')
	print 'Schema exists'
else
	print 'Schema not found'
```

The issue appears to be that `INFORMATION_SCHEMA.SCHEMATA` has a row for `dbo`, but after passing through `QUOTENAME()`, it no longer matches. If I either remove that function call, or compare it to `'[dbo]'`, the test passes.

(It appears that [the code that's trying to generate a value for `@BlitzCacheMinutesBack`](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/sp_BlitzFirst.sql#L2857) a little earlier has the exact same problem, too.)

**Comment by Adedba** [comment]
Did you get the Delete statement from the output in the messages tab after adding the Raiserror i mentioned? 

I just tested using that method to output the actual string that is going to be executed and found that the dbo is actually evaluated as [dbo] , for example when I added the Raiserror as pictured above I got this statement: 

`IF EXISTS(SELECT * FROM [DBAtools].INFORMATION_SCHEMA.SCHEMATA WHERE QUOTENAME(SCHEMA_NAME) = '[dbo]') DELETE [DBAtools].[dbo].[BlitzCache] WHERE ServerName = @SrvName AND CheckDate < @CheckDate;`

This makes the quotename(schema_name) a valid clause because its checking for '[dbo]' I do get what you mean about checking for the schema and not the table - looks like you may have discovered an issue there but I am not sure that is where the problem lies for your issue. 

The only other factors I can see are  @@SERVERNAME and @CheckDate,

The delete statement is the equivalent of the following select (assuming you are retaining 7 days) do you get results in SSMS if you run the below query?

`SELECT * 
FROM [DBAtools].[dbo].[BlitzCache] 
WHERE ServerName = @@SERVERNAME AND CheckDate < CAST( (DATEADD(DAY, -1 * 7, GETDATE() ) ) AS DATE)`

**Comment by sixten** [comment]
No, I'm not modifying the actual sproc on production, I'm working with extracts of the code. And it appears that there's code that I missed that's setting the value of `@OutputSchemaName` [to the quoted version of itself](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/bb9de6c4766dc55508afc146770393ee47eb8f8c/sp_BlitzFirst.sql#L147). I apologize for the red herring! 😣

Your inlined query returns zero results when I run it.

We're not passing in a value for the `@OutputTableRetentionDays` param, so I believe that the date checking in your query matches production behavior.

But regarding `@@SERVERNAME`… I think you might be on to something. If I remove that clause, the query matches 18k of 45k records in the table.

The values in the BlitzCache table match what I expect to see as the name of the server. But the result of `@@SERVERNAME` _does not_.

[Looking at the code for `sp_BlitzCache`](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/bb9de6c4766dc55508afc146770393ee47eb8f8c/sp_BlitzCache.sql#L6755), it appears that it's using a different method for determining the name of the server: `QUOTENAME(CAST(SERVERPROPERTY('ServerName') AS NVARCHAR(128)), N'''')` Running this in SSMS, I see the name that I expect.

Both of these methods seem to be used throughout `sp_BlitzFirst`.

**Comment by Adedba** [comment]
Great so looks like that may be the answer then, so when you run the following I assume you are getting different results?

`SELECT @@SERVERNAME,SERVERPROPERTY('ServerName')` 

You mentioned @@servername returning a unexpected server name, Out of interest has the server had a name change at some stage?

**Comment by sixten** [comment]
Almost certainly: it's running in an EC2 instance, which apparently gets a randomized name on launch. And judging by what Google's showing me, those two values being out of sync is a pretty common problem? (Which would seem to make mixing the two methods in the same piece of code kind of problematic.)

**Comment by Adedba** [comment]
Ahh I see ,  that makes sense because @@servername looks at sys.servers not entirely sure how SERVERPROPERTY('Servername') works under the covers but looks like it is not reliant on sys.servers.

Probably best to wait for @BrentOzar to return from his vacation to decide how he wants to proceed as this is quite a big change! 

Changes would be required in: 
sp_Blitz
sp_BlitzCache
sp-BlitzFirst
sp_BlitzLock
sp_BlitzWho

**Comment by sixten** [comment]
In the mean time, we've updated `sys.servers` (but now need to find a time to reboot the server).

**Comment by BrentOzar** [comment]
@sixten @Adedba OK, I'm back from vacation - can you give me the quick rundown of what you found and what needs to be changed? Scanned through this and I'm not entirely clear on which method was accurate on @sixten's server, and which one was not.

**Comment by sixten** [comment]
Short version:

* Our BlitzCache data doesn't get cleaned out because inserts and deletes are using different names.
  * `SERVERPROPERTY('Servername')` matched the name I expected
  * `@@ServerName` _did not_ match what I expected, but appears to be the original name generated for the EC2 instance
* We did find a procedure to update `sys.servers` to bring the answers into alignment.
* But it would be good to either make the code more consistent, or at least raise an error if they're not.
  * (Might also be a good test for Constant Care?)

**Comment by BrentOzar** [comment]
OK, gotcha. Sounds like you're renaming servers after they're built, and not following the documented steps: https://docs.microsoft.com/en-us/sql/database-engine/install-windows/rename-a-computer-that-hosts-a-stand-alone-instance-of-sql-server?view=sql-server-ver15

I went ahead and changed sp_BlitzFirst's code to handle the sp_BlitzCache deletes in that situation, but I would make sure you're renaming servers the right way - this has a cascading effect in a bunch of places. Thanks!
