### ISSUE TITLE
sp_BlitzWho - replace SQLAgent jobid with job name

### ISSUE THREAD

**Issue by jerryhung** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2328]
**Is your feature request related to a problem? Please describe.**
Currently sp_BlitzWho shows sys.dm_exec_sessions program_name as
SQLAgent - TSQL JobStep (Job 0x661AAAA77D36F84FBF435986093A0880 : Step 2)

**Describe the solution you'd like**
Instead of going to msdb and find out what the job is, let's replace it in the view?
I know sp_whoIsActive also doesn't do it either, not sure why

SQLAgent - TSQL JobStep (Job "Hiding the name" : Step 2)

**Are you ready to build the code for the feature?**

Please see below code, I didn't want to submit a new branch/code if people didn't want it, or maybe add it as DEBUG or expert mode feature?

Here is the code - 1 line change really. I avoided using the undocumented master.dbo.fn_varbintohexstr function too

The snippet from @StringToExecute (sp_BlitzWho line 348 and line 547)

--before
s.program_name,	--original

--after
--new code, grabbing from msdb and replace job_id with job_name
new_program_name = COALESCE((
SELECT REPLACE(PROGRAM_NAME,Substring(program_name,30,34),'"'+j.name+'"') 
FROM msdb.dbo.sysjobs j WHERE Substring(program_name,32,32) = CONVERT(char(32),CAST(j.job_id AS binary(16)),2)
),s.program_name)

**Output**
--before
SQLAgent - TSQL JobStep (Job 0x661AAAA77D36F84FBF435986093A0880 : Step 2)	
--after
SQLAgent - TSQL JobStep (Job "Hiding the name" : Step 2)

**Comment by BrentOzar** [comment]
Hi, and thanks for the issue. Sure, by all means, you can contribute code by following the contribution guide here:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

And it's totally welcome!

**Comment by jerryhung** [comment]
Sorry for newbie GitHub question
I have the code, the branch ready to commit, Publish - error

I followed the video too
https://www.brentozar.com/archive/2019/02/video-an-introduction-to-github-for-dbas/

On the bottom-left window it'd say I don't have Write access to this repository and asks if I want to folk instead. Same when I publish it (no write access)

Is there any special permission I need? Thanks

**Comment by BrentOzar** [comment]
Gotcha - that sounds like you've tried to edit directly in my repository. Try reading this and following along: https://sqldbawithabeard.com/2019/11/29/how-to-fork-a-github-repository-and-contribute-to-an-open-source-project/

**Comment by BrentOzar** [comment]
Great job! Works, merged into the dev branch, will be in the May release with credit to you in the release notes.
