### ISSUE TITLE
SP_BlitzIndex: add foreign key table schema

### ISSUE THREAD

**Issue by furt1v3ly** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2334]
In the table specific reporting, the foreign key listing shows the tables and columns referenced but doesn't show the schema of the table. We occasionally have matching table names in different schema and have to hunt down which is which.

If possible, could the report have a column for schema added named "Referenced Schema"

Sadly I can't offer to help edit without clearing it with my office since I discovered the issue at work.  I'll ask and see if they have issues with lightweight changes like this to free tools we use. If so I'll pick this up. It really looks to be an easy change.

**Comment by BrentOzar** [comment]
Gotcha. Open source isn't really free development: if there's a feature you need, as the feature request showed, you need to consider rolling up your sleeves and building it.

I'm going to go ahead and close this for now, but if you decide you want to contribute the code, read the Contributing Guide here:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

And then reopen another issue. Thanks!
