### ISSUE TITLE
sp_BlitzIndex - missing Warning URL on Obsessive Constraintive: Serial Forcer

### ISSUE THREAD

**Issue by chambrick** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2340]
**Version of the script**
Script being used is sp_BlitzIndex(TM) v7.94 - March 24, 2020: 

**What is the current behavior?**
When the finding comes back with Obsessive Constraintive: Serial Forcer, there is no warning URL given

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Warning URL needs to be added into procedure

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
This is running on SQL 2017 CU 16

**Comment by chambrick** [comment]
Brent I am HamboneDBA

**Comment by BrentOzar** [comment]
Good catch, Hambone! Added a link to point here: https://www.brentozar.com/archive/2016/01/another-reason-why-scalar-functions-in-computed-columns-is-a-bad-idea/ And will credit you in the May release notes. Thanks!
