### ISSUE TITLE
Add parameter to sp_BlitzFirst to return required rows for Analyze Your Wait Stats

### ISSUE THREAD

**Issue by NRKirby** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2342]
**Is your feature request related to a problem? Please describe.**

I've been watching your some of your Twitch "Watch Brent Analyze Your Wait Stats" videos this week and notice you ask people to send you the first 10 rows and specific 9 columns from the result of calling `sp_BlitzFirst @SinceStartup = 1`. I wonder if we could create a parameter to pass BlitzFirst so that only the rows/cols you need get returned.

**Describe the solution you'd like**
Create a parameter to pass BlitzFirst so that only the rows/cols you need get returned.

**Are you ready to build the code for the feature?**
I would love to look into writing the code to enable this feature, if you think this is worth doing!

**Comment by BrentOzar** [comment]
I am so glad you said that! Every time I do that kind of live stream, I say to myself, "Self, you've gotta build a parameter for sp_BlitzFirst to make that easier," and then I forget to log an issue for it every time.

You can go for it! I'd love to have it. The way I'd code it is to add an option for @OutputType = 'Top10', and only output the top 10 rows, with these columns: 

* Hours Sample
* wait_type
* wait_category
* Wait Time (Hours)
* Per Core Per Hour
* Number of Waits
* Avg ms Per Wait

You can probably add it around line 3821-3822. In there, I'm going through the different OutputType options, and dumping out the right results. I'd put it between these two lines:

```
        END;
        ELSE IF @ExpertMode = 0 AND @OutputType <> 'NONE' AND @OutputXMLasNVARCHAR = 0 AND @SinceStartup = 0
```

And you can just do it as:

`        ELSE IF @OutputType = 'Top10'`

And put the select in there. You can copy the select from around line 3923 which starts with:

`--What happened: #WaitStats`

If you run into problems or run out of time, holler, and I can do it. Thanks!

**Comment by NRKirby** [comment]
Great! I'm doing it right now...

**Comment by BrentOzar** [comment]
Great, thanks! Merged into the dev branch and will be in the May release, and will credit you in the release notes.
