### ISSUE TITLE
Parameter Names

### ISSUE THREAD

**Issue by patrickjolliffe** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2344]
sp_blitzindex @schemaname='xxx', @tablename='yyy'

Just a personal bugbear, but the "name" is kind of redundant right? isn't everything a name?
Save me some typing so I can use:
 sp_blitzindex @schema='xxx', @table='yyy'

No biggie, maybe you want to keep as currently is for backwards compatability, or disagree with me on this :)

**Comment by BrentOzar** [comment]
Given that it's almost a decade old and there is a ton of written documentation and videos out about it, we'll need to stick with the existing parameters. Sorry about the extra typing - hope your fingers can learn to deal with the incredible burden. ;-)

**Comment by patrickjolliffe** [comment]
Haha, yes I think I'll survive somehow, yes there are really more pressing issues elsewhere in the world #peace
