### ISSUE TITLE
sp_BlitzCache: sys.dm_os_buffer_descriptors is slow, use clerks instead

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2345]
**Version of the script**
SELECT @Version = '7.94', @VersionDate = '20200324';

**What is the current behavior?**
In the blog comments, Daniel reported that this query ran slow, taking 10 minutes on a box with 800GB RAM:

```
SELECT @buffer_pool_memory_gb = ( COUNT_BIG(*) * 8.0 ) / 1024. / 1024.
                                  FROM sys.dm_os_buffer_descriptors;
```

Let's use sys.dm_os_memory_clerks instead.

**Comment by daniel-mrowiec** [comment]
If you need more info related to this issue, please let me know

**Comment by BrentOzar** [comment]
Thanks! It's fine though - I just wrote it out so that I could track it for when I have more time. I'm tied up teaching classes this week & next, but I'll work on it next month (May). Or if you want to jump in, you can too, either way.

Brent

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by BrentOzar** [comment]
Now uses this instead, which will be crazy fast in comparison:

```
SELECT @buffer_pool_memory_gb = SUM(pages_kb)/ 1024. / 1024.  
    FROM sys.dm_os_memory_clerks 
    WHERE type = 'MEMORYCLERK_SQLBUFFERPOOL';
```

Thanks for the heads up - will be in the May release.
