### ISSUE TITLE
sp_DatabaseRestore errors out when @StopAt and @OnlyLogsAfter are both specified

### ISSUE THREAD

**Issue by gdoddsy** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2348]
**Version of the script**
7.94, (Date: 20200324)

**What is the current behavior?**
When restoring, the script crashes with the error: "A cursor with the name 'BackupFiles' does not exist."

**If the current behavior is a bug, please provide the steps to reproduce.**
If you specify @StopAt and @OnlyLogsAfter parameters, then you get the error 

**What is the expected behavior?**
Restores the log files up to the specified time.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2019, Windows 2019. I suspect it's always been broken.

**Comment by gdoddsy** [comment]
I realized after reading the code that you can specify just @StopAt and don't need to include @OnlyLogsFrom to get the experience I desired, but I think you should be able to specify both and not have it crash.

Another suggested fix for this would be to have an error raised that says you can't specify both parameters. The current Cursor doesn't exist is not intuitive as to what went wrong.

**Comment by BrentOzar** [comment]
Haven't heard back from folks, so I'm going to go ahead and merge these. They'll be in the July release along with credit to you in the release notes. Thanks sir!
