### ISSUE TITLE
Add check for logical file name "master" in user databases

### ISSUE THREAD

**Issue by Hermholtz** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2352]
**Is your feature request related to a problem? Please describe.**
A problem occurs when failing over an FCI node when user database has a file with logical name "master."

https://desertdba.com/failovers-cant-serve-two-masters/

**Describe the solution you'd like**
A red flag in one of the sp_Blitz% scripts when it sees that.

**Describe alternatives you've considered**
People can live without it, but it would catch an extremely time-consuming issue before it happens in a very stressful moment.

**Are you ready to build the code for the feature?**
Not sure if got enough skills for that.

**Comment by BrentOzar** [comment]
Thanks for the inspiration, and the link to Jeff's blog post. I added a check in sp_Blitz for it. It's in the dev branch now, and will be included in the May release along with a credit in the release notes. Thanks!
