### ISSUE TITLE
sp_BlitzLock error when XML parsing, possibly due to strange object names

### ISSUE THREAD

**Issue by johnuhr** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2358]
**Version of the script**
SELECT @Version = '2.94', @VersionDate = '20200324';

**What is the current behavior?**
Grab the initial set of XML to parse at May  1 2020  7:56:26:000AM
Msg 9411, Level 16, State 1, Procedure sp_BlitzLock, Line 305 [Batch Start Line 0]
XML parsing: line 24, character 79, semicolon expected

Completion time: 2020-05-01T07:56:28.8072801+02:00

**If the current behavior is a bug, please provide the steps to reproduce.**
don't know 

**What is the expected behavior?**
no, this is an error 

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Microsoft SQL Server 2016 (SP2-CU4) (KB4464106) - 13.0.5233.0 (X64)   Nov  3 2018 00:01:54   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor) 

=====> SOLUTION <=====
https: // richardbriansmith.com/2018/12/13/fix-sp_blitzlock/

**Comment by erikdarlingdata** [comment]
Is this happening because you have odd characters somewhere in an object name? Or something else?

I took a look at the fix, and running replace on a whole bunch of XML could be pretty painful for what might be a very localized issue (or a [Microsoft bug](https://feedback.azure.com/forums/908035-sql-server/suggestions/33731290-correctly-escape-predefined-entities-in-deadlock-x) in handling deadlock XML). I'd love to use `TRY_CONVERT` here instead, but it seems to break in certain compat levels. Have gotten a few bug reports about it in BlitzQueryStore.

**Comment by BrentOzar** [comment]
@johnuhr can you speak to Erik's questions? Thanks!

**Comment by johnuhr** [comment]
sorry about the late reply. the system and the database is an out of the box Microsoft Dynamics NAV with multiple financial companies. The standard syntax for objects in the database is [<company>$<table name>]. I assume it is the "$" that is causing the issue. 
Is there an easy way for me to identify which odd characters that are causing this error?

**Comment by johnuhr** [comment]
...The standard syntax for objects in the database is [(company name)$(table name)]

**Comment by johnuhr** [comment]
...collation is "Danish_Greenlandic_100_CS_AS"

**Comment by BrentOzar** [comment]
I did a quick check, and the $ isn't causing the issue:

<img width="1090" alt="Screen Shot 2020-05-07 at 3 58 55 AM" src="https://user-images.githubusercontent.com/245462/81287135-1c336800-9017-11ea-8945-3d9c3e52642a.png">

I don't know a quick way offhand to see what characters are causing the issue, but I'm with Erik on this one: doing converts on XML would make this thing pretty doggone slow. I'm glad to hear you found a workaround that works for you, but given that we haven't heard this from anyone else, I'm going to close this one for now. If you end up identifying which character is breaking it, then we might be able to find a performant solution. Thanks though!

**Comment by johnuhr** [comment]
I'm using this script to identify characters being used by all objects:

SET NOCOUNT ON
IF OBJECT_ID('tempdb..#tmp') IS NOT NULL DROP TABLE #tmp
SELECT TOP (100) PERCENT CAST([name] AS nvarchar(128)) AS [name] INTO #tmp FROM sys.objects

IF OBJECT_ID('tempdb..#charsFound') IS NOT NULL DROP TABLE #charsFound
CREATE TABLE #charsFound ([char] nchar(1), [unicode] int, [count] int)

DECLARE @nchar nchar(1), @cnt int = 0, @cnt_chars int = 0

WHILE (SELECT TOP (1) left([name],1) FROM #tmp WHERE left([name],1) <> SPACE(1)) IS NOT NULL
BEGIN
	SELECT TOP (1) @nchar = left([name],1) FROM #tmp WHERE left([name],1) <> SPACE(1)
	SET @cnt += 1
	RAISERROR('%i',0,1,@cnt) WITH NOWAIT
	IF @cnt = 50000 RETURN
	SELECT @cnt_chars = SUM(DATALENGTH([name]) - DATALENGTH(REPLACE([name], @nchar, SPACE(0)))) /2 FROM #tmp 
	UPDATE #tmp SET [name] = REPLACE([name], @nchar, space(0))
	DELETE #tmp WHERE [name] = SPACE(0)
	INSERT INTO #charsFound SELECT @nchar, UNICODE(@nchar), @cnt_chars
END

SELECT * FROM #charsFound

**Comment by johnuhr** [comment]
I use this code to identify all characters used in all objects in database:

SET NOCOUNT ON
IF OBJECT_ID('tempdb..#tmp') IS NOT NULL DROP TABLE #tmp
SELECT TOP (100) PERCENT CAST([name] AS nvarchar(128)) AS [name] INTO #tmp FROM sys.objects
UPDATE #tmp SET [name] = REPLACE([name], SPACE(1), SPACE(0))

IF OBJECT_ID('tempdb..#charsFound') IS NOT NULL DROP TABLE #charsFound
CREATE TABLE #charsFound ([char] nchar(1), [unicode] int, [count] int)

DECLARE @nchar nchar(1), @cnt int = 0, @cnt_chars int = 0, @unicode int, @name nvarchar(128)

WHILE EXISTS (SELECT 1 FROM #tmp) 
BEGIN
	SELECT TOP (1) @name = [name] FROM #tmp 
	SET @nchar = left(@name,1) 
	SELECT @unicode = UNICODE(@nchar)
	SET @cnt += 1
	RAISERROR('%i ---> [%s] ---> %i ---> [%s]', 0, 1, @cnt, @nchar, @unicode, @name) WITH NOWAIT
	IF @cnt = 5000 RETURN
	SELECT @cnt_chars = SUM(DATALENGTH([name]) - DATALENGTH(REPLACE([name], @nchar, SPACE(0)))) /2 FROM #tmp 
	UPDATE #tmp SET [name] = REPLACE([name] COLLATE Latin1_General_BIN, @nchar, SPACE(0)) 
	DELETE #tmp WHERE [name] = SPACE(0)
	INSERT INTO #charsFound SELECT @nchar, @unicode, @cnt_chars
END

SELECT * FROM #charsFound ORDER BY [unicode]

--------------------------------------------------------------------------------
$	36	171579
&	38	14905
(	40	706
)	41	706
*	42	29370
-	45	3432
0	48	54475
1	49	3025
2	50	1836
3	51	1268
4	52	930
5	53	829
6	54	1874
7	55	374
8	56	645
9	57	390
<	60	132
>	62	132
A	65	97799
B	66	46986
C	67	49558
D	68	35738
E	69	37111
F	70	18798
G	71	25849
H	72	34029
I	73	58758
J	74	6361
K	75	11879
L	76	43066
M	77	38910
N	78	13673
O	79	11816
P	80	47872
Q	81	1769
R	82	48194
S	83	106761
T	84	81384
U	85	8796
V	86	11951
W	87	7053
X	88	891
Y	89	132
Z	90	123393
_	95	50016
a	97	276061
b	98	39501
c	99	282861
d	100	85126
e	101	333108
f	102	22108
g	103	35987
h	104	53245
i	105	129213
j	106	2478
k	107	36096
l	108	76995
m	109	68491
n	110	242951
o	111	273213
p	112	48801
q	113	1097
r	114	194149
s	115	128089
t	116	213209
u	117	82718
v	118	26393
w	119	22704
x	120	7008
y	121	54564
z	122	1206
Ö	214	4895
ö	246	4895

**Comment by BrentOzar** [comment]
OK, if you want to go through and run tests on those, you're welcome to, but this is a little beyond what I can do quickly in my spare time. Is that fair?

**Comment by johnuhr** [comment]
yes - absolutely fair :) I did not intent for anyone else but myself to find the answer :)

**Comment by johnuhr** [comment]
We do have tables and views that contain the asterisk character unicode(42)

**Comment by BrentOzar** [comment]
OK - you don't have to give us a play by play here. (I get email notifications with each comment.) Go ahead and do the research necessary to find the answer, and then get back to us if you need help with something specific. Thanks!
