### ISSUE TITLE
sp_BlitzCache: Should we warn about lots of single use plans?

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2359]
**Is your feature request related to a problem? Please describe.**
We warn about percentages of plans created in the past X hours, is this also a valuable metric to also warn about? Perhaps for something additional to look at alongside the token perm warning?

**Describe the solution you'd like**
I think there's already some logic in Blitz to warn about single use plans. It might be good to surface that here.

**Describe alternatives you've considered**
Running sp_Blitz every 10 minutes.

**Are you ready to build the code for the feature?**
Yeah, it should be easy to drop in.

**Comment by erikdarlingdata** [comment]
I started looking at how I'd wanna do this today. Sticking this query here so I don't lose it, and in case there's any feedback to incorporate. I haven't figured out thresholds to warn at yet, so if you have OPINIONS, feel free to prolapse them here.

```
WITH many_plans AS 
(
    SELECT SUM(x.duplicate_plan_handles) AS duplicate_plan_handles
    FROM (
        SELECT COUNT_BIG(DISTINCT plan_handle) AS duplicate_plan_handles
        FROM sys.dm_exec_query_stats qs
            CROSS APPLY sys.dm_exec_plan_attributes(qs.plan_handle) pa
        WHERE pa.attribute = N'dbid'
        GROUP BY qs.query_hash, pa.value
        HAVING COUNT_BIG(DISTINCT plan_handle) > 5
    ) AS x
),
     single_use_plans AS 
(
    SELECT COUNT_BIG(*) AS single_use_plan_count
    FROM sys.dm_exec_cached_plans AS cp
    WHERE cp.usecounts = 1
    AND   cp.objtype = N'Adhoc'
    AND   EXISTS ( SELECT 1/0
                   FROM sys.configurations AS c
                   WHERE c.name = N'optimize for ad hoc workloads'
                   AND   c.value_in_use = 0 )
    HAVING COUNT_BIG(*) > 1
),
     total_plans AS 
(
    SELECT COUNT_BIG(*) AS total_plans
    FROM sys.dm_exec_cached_plans AS decp
)
SELECT m.duplicate_plan_handles, 
       CONVERT(DECIMAL(3,2), m.duplicate_plan_handles / (1. * NULLIF(t.total_plans, 0))) * 100. AS percent_duplicate,
       s.single_use_plan_count, 
       CONVERT(DECIMAL(3,2), s.single_use_plan_count / (1. * NULLIF(t.total_plans, 0))) * 100. AS percent_single,
       t.total_plans
FROM   many_plans AS m, 
       single_use_plans AS s, 
       total_plans AS t;
```

**Comment by BrentOzar** [comment]
Looks great! Thanks sir. Merged in, and will be in the June release. Getting one out early for June, will be dropping it June 1.
