### ISSUE TITLE
BlitzLock shows heap in a table with clustered index

### ISSUE THREAD

**Issue by diegombt** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2360]
**Version of the script**
Version = '2.94', @VersionDate = '20200324'

**What is the current behavior?**
I'm watching a lock alert for a heap when table has a clustered index

**If the current behavior is a bug, please provide the steps to reproduce.**
I've created a clustered index with allow pages / rows off, what generated a lock escalation at index level. However, the SP showed that there is a lock at the table's heap!

**What is the expected behavior?**
Lock escalation happening at table's clustered index

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Microsoft SQL Server 2016 (SP2-CU10) (KB4524334) - 13.0.5492.2 (X64)   Oct  4 2019 19:14:08   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
![lock](https://user-images.githubusercontent.com/4006383/81130009-d5a51700-8f0b-11ea-8be2-8ce3a3b39f80.png)
Tested only in this server with this script version

**Comment by erikdarlingdata** [comment]
Can you script out the table definition and update the issue with it?

**Comment by BrentOzar** [comment]
I can confirm that I've seen the same thing during the Mastering classes, but I couldn't script it out at the time. I just tried doing some quick repros and didn't see it, so I can't get it in for this month's release, but will try during the next round of Mastering classes.

**Comment by diegombt** [comment]
Hi, there is the script for related table.

[table.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/4594943/table.txt)

**Comment by erikdarlingdata** [comment]
Thanks for the quick response! Might need more info to reproduce though. 

When I create the table with the script you use, along with another table called `other` so that I can get a deadlock and not just blocking, the `HEAP` appears in the right spot.

![image](https://user-images.githubusercontent.com/2136037/81331379-7d872580-906f-11ea-977c-4ddd0f3d7cc5.png)

If it's not a confidentiality issue, could you upload the deadlock XML?

**Comment by diegombt** [comment]
Thanks to you, this is part of the messages for deadlocking

[deadlock.xlsx](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/4595052/deadlock.xlsx)

**Comment by erikdarlingdata** [comment]
I see the problem. I can fix it. Thanks for sending that.

**Comment by BrentOzar** [comment]
Looks great! Thanks sir. Merged in, and will be in the June release. Getting one out early for June, will be dropping it June 1.
