### ISSUE TITLE
sp_Blitz check two masters (SQL 2008 R2)

### ISSUE THREAD

**Issue by Brianc-DBA** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2371]
**Version of the script**
@Version = '7.95', @VersionDate = '20200506'

**What is the current behavior?**
When running Execute Install-Core-Blitz-No-Query-Store.sql on SQL 2008 R2 the following error occurs.  (Yes, I know, but we still have several important databases on that and pay for third party mega expensive support for these servers).   It works on any SQL version higher than that (2012 - 2019).

Msg 102, Level 15, State 1, Procedure sp_Blitz, Line 5863 [Batch Start Line 3]
Incorrect syntax near ' '.

-- this can be traced to this block of code:
							SELECT 234 AS CheckID,
							       100 AS Priority,
								   db_name(f.database_id) AS DatabaseName,
							       'Reliability' AS FindingsGroup,
							       'SQL Server Update May Fail' AS Finding,
							       'https://desertdba.com/failovers-cant-serve-two-masters/' AS URL,
							       'This database has a file with a logical name of ''master'', which can break SQL Server updates. Rename it in SSMS by right-clicking on the database, go into Properties, and rename the file. Takes effect instantly.' AS details
							FROM master.sys.master_files f
							WHERE (f.name = N'master')
							  AND f.database_id > 4
							  AND db_name(f.database_id) <> 'master'; /* Thanks Michaels3 for catching this */

-- Since I am running Execute Install-Core-Blitz-No-Query-Store.sql instead of just the sp_Blitz script, it also catches a bug in sp_BlitzCache:
Msg 207, Level 16, State 1, Procedure sp_BlitzCache, Line 4814 [Batch Start Line 10926]
Invalid column name 'pages_kb'.

**If the current behavior is a bug, please provide the steps to reproduce.**
Execute Install-Core-Blitz-No-Query-Store.sql
-- this bug in sp_Blitz
Msg 102, Level 15, State 1, Procedure sp_Blitz, Line 5863 [Batch Start Line 3]
Incorrect syntax near ' '.
-- separate bug in sp_BlitzCache, also for 2008 R2 only.  I can open a separate bug for that item if you accept this bug report for this old-timey version of SQL .  If not, I won't bother :).
Msg 207, Level 16, State 1, Procedure sp_BlitzCache, Line 4814 [Batch Start Line 10926]
Invalid column name 'pages_kb'.

**What is the expected behavior?**
Execute Install-Core-Blitz-No-Query-Store.sql, and it runs without error

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2008 R2, Windows 2012 R2.  This worked on the previous month's version.

**Comment by BrentOzar** [comment]
OK, do you want to check in fixes to get it to work on SQL Server 2008 then?

**Comment by Brianc-DBA** [comment]
Sure, I could give it a shot.

**Comment by BrentOzar** [comment]
I'm betting #2373 had something to do with it - can you download the latest version of sp_Blitz and see if that works? https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_Blitz.sql

**Comment by Brianc-DBA** [comment]
Yes - #2373 was related.  I was looking into the unreadable characters while investigating this.  The new version of sp_Blitz has resolved this issue on 2008 R2.  The bug in sp_BlitzCache is resolved as well by #2373 .
