### ISSUE TITLE
sp_BlitzCache errors on sys.dm_os_memory_clerks call

### ISSUE THREAD

**Issue by WestSeattleCoug** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2372]
Version 7.9

**What is the current behavior?**
Errors on the following line of code:
	SELECT @buffer_pool_memory_gb = SUM(pages_kb)/ 1024. / 1024.  
		FROM sys.dm_os_memory_clerks 
		WHERE type = 'MEMORYCLERK_SQLBUFFERPOOL';

The column "pages_kb" is only from SQL2014 on, and I'm running on SQL 2008R2.

Procedure calls
To reproduce, just try to load the procedure

Solution:

IF @common_version >= 11
    SET @user_perm_sql += N'
	SELECT @buffer_pool_memory_gb = SUM(pages_kb)/ 1024. / 1024.  
		FROM sys.dm_os_memory_clerks 
		WHERE type = ''MEMORYCLERK_SQLBUFFERPOOL'';'
ELSE
    SET @user_perm_sql += N'
	SELECT @buffer_pool_memory_gb = SUM(single_pages_kb + multi_pages_kb)/ 1024. / 1024.  
		FROM sys.dm_os_memory_clerks 
		WHERE type = ''MEMORYCLERK_SQLBUFFERPOOL'';'

EXEC sys.sp_executesql @user_perm_sql, 
                       N'@user_perm_gb DECIMAL(10,2) OUTPUT', 
					   @user_perm_gb = @user_perm_gb_out OUTPUT;

**Comment by BrentOzar** [comment]
Great catch! Fixed in the dev branch, and will be in the June release. Thanks!
