### ISSUE TITLE
sp_Blitz - non-readable char in script

### ISSUE THREAD

**Issue by jeffchulg** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2373]
**Version of the script**
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.
20200506

**What is the current behavior?**
the script has a non-readable char at line 5866 between "FROM" and "master.sys.master_files"

**If the current behavior is a bug, please provide the steps to reproduce.**
/

**What is the expected behavior?**

No non-readable char. When generating a version, maybe a treatment of special chars should be applied. Example in PowerShell:

```
$NewLineValue = $NewLineValue -replace$([Char] 9),"    "
$NewLineValue = $NewLineValue -replace"[^ -x7e]"," "
```

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Win10 + SQL Server 2019 Express
Win Server 2016 and SQL Server 2016

**Comment by BrentOzar** [comment]
When you say a non-readable character, can you elaborate about the problem it's causing for you? What's this stopping you from being able to do, or what alert is it throwing?

**Comment by BrentOzar** [comment]
Here's the line in Github, and it looks okay from here:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_Blitz.sql#L5866

I use a Mac though, so I'm guessing maybe you're on Windows and there's a problem with a tool or something that you're using? I'm definitely not minimizing it, I'm just trying to find out what's the problem we're trying to solve.

**Comment by jeffchulg** [comment]
Hi Brent,

It's in the installation step of the script: I read the file with Powershell and, when executing, it converted the char to '?' so the procedure won't install/update because the text is:

> FROM?master.sys.master_files

While I've juste added in the treatment of the file a pre-processing that strip any non-readable char, I wanted to point it out so that you can take the same kind of treatment.

And, yes, I'm on Windows.

**Comment by jeffchulg** [comment]
Ha, yes, I forgot... the non-readable char is "FF (FORM FEED)"
I downloaded the version from 
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/archive/master.zip

**Comment by BrentOzar** [comment]
OK, gotcha. So I'm going to give you a little tough love there: if you're doing something with the scripts with PowerShell, and you're already giving me the instructions on how to fix it with PowerShell, well...why aren't you doing that, then? Why don't you add that code as part of your handling?

**Comment by BrentOzar** [comment]
Gotcha, I see that you're doing that - okay, cool. I'll go ahead and close this then. Thanks though!

**Comment by BrentOzar** [comment]
@jeffchulg I apologize for the tone I took with that. That was unnecessary and over the top. You made a great suggestion, and I should have just run with that. I've gone ahead and pulled the character. I'm sorry for the bug, and for the way I approached it. 

![facepalm](https://user-images.githubusercontent.com/245462/81565691-9da83480-934e-11ea-94b3-deffc756fa49.gif)

**Comment by jeffchulg** [comment]
@BrentOzar no worry... I'm happy ;)
