### ISSUE TITLE
Sp_BlitzFirst / Sp_BlitzCache intermittent failures

### ISSUE THREAD

**Issue by Brianc-DBA** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2376]
**Version of the script**
@Version = '7.95', @VersionDate = '20200506';

**What is the current behavior?**
We have a job running BlitzFirst every 15 minutes to capture data for the PowerBI Dashboard.  Ever since the newest version has been implemented, there are intermittent failures of the job on different versions of SQL.  The error seems to be traceable to an error in sp_BlitzCache since the former references the latter and the errors referring to @buffer_pool_memory_gb are the same...but I will put in both scripts' errors just in case.

1. Scheduled SQL Agent job  + errors below:
EXEC sp_BlitzFirst 
  @OutputDatabaseName = 'DBA', 
  @OutputSchemaName = 'dbo', 
  @OutputTableName = 'BlitzFirst',
  @OutputTableNameFileStats = 'BlitzFirst_FileStats',
  @OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
  @OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
  @OutputTableNameBlitzCache = 'BlitzCache',
  @OutputTableNameBlitzWho = 'BlitzWho';

Executed as user: (name redacted). ...age 50000)  Now starting diagnostic analysis [SQLSTATE 01000] (Message 50000)  Checking for Read intent databases to exclude [SQLSTATE 01000] (Message 50000)  Capturing first pass of wait stats, perfmon counters, file stats [SQLSTATE 01000] (Message 50000)  Logging sp_BlitzWho to table [SQLSTATE 01000] (Message 50000)  Beginning investigatory queries [SQLSTATE 01000] (Message 50000)  Finished running investigatory queries [SQLSTATE 01000] (Message 50000)  Waiting to match @Seconds parameter [SQLSTATE 01000] (Message 50000)  Capturing second pass of wait stats, perfmon counters, file stats [SQLSTATE 01000] (Message 50000)  Analyzing changes between first and second passes of DMVs [SQLSTATE 01000] (Message 50000)  Analysis finished, outputting results [SQLSTATE 01000] (Message 50000)  Determining SQL Server version. [SQLSTATE 01000] (Message 50000)  Calling sp_BlitzCache [SQLSTATE 01000] (Message 50000)  Checking @MinutesBack validity. [SQLSTATE 01000] (Message 50000)  Setting @MinutesBack to a negative number [SQLSTATE 01000] (Message 50000)  Creating temp tables for results and warnings. [SQLSTATE 01000] (Message 50000)  Checking database validity [SQLSTATE 01000] (Message 50000)  Checking sort order [SQLSTATE 01000] (Message 50000)  Skip Analysis set to 1, hiding Summary [SQLSTATE 01000] (Message 50000)  Cleaning up old warnings for your SPID [SQLSTATE 01000] (Message 50000)  Cleaning up old plans for your SPID [SQLSTATE 01000] (Message 50000)  Checking all sort orders, please be patient [SQLSTATE 01000] (Message 50000)  Beginning all sort loop [SQLSTATE 01000] (Message 50000)  Beginning for ALL [SQLSTATE 01000] (Message 50000)  Must declare the scalar variable "@buffer_pool_memory_gb". [SQLSTATE 42000] (Error 137)  Checking @MinutesBack validity. [SQLSTATE 01000] (Error 50000)  Creating temp tables for results and warnings. [SQLSTATE 01000] (Error 50000)  Checking database validity [SQLSTATE 01000] (Error 50000)  Checking sort order [SQLSTATE 01000] (Error 50000)  Skip Analysis set to 1, hiding Summary [SQLSTATE 01000] (Error 50000)  Cleaning up old warnings for your SPID [SQLSTATE 01000] (Error 50000)  Cleaning up old plans for your SPID [SQLSTATE 01000] (Error 50000)  Creating temp tables for internal processing [SQLSTATE 01000] (Error 50000)  Checking for Read intent databases to exclude [SQLSTATE 01000] (Error 50000)  Checking plan cache age [SQLSTATE 01000] (Error 50000)  Setting up variables [SQLSTATE 01000] (Error 50000)  Determining SQL Server version. [SQLSTATE 01000] (Error 50000)  Creating dynamic SQL based on SQL Server version. [SQLSTATE 01000] (Error 50000)  Ignoring readable secondaries databases by default [SQLSTATE 01000] (Error 50000)  Ignoring system databases by default [SQLSTATE 01000] (Error 50000)  Setting minutes back filter [SQLSTATE 01000] (Error 50000)  Applying chosen sort order [SQLSTATE 01000] (Error 50000)  Getting spill information for newer versions of SQL [SQLSTATE 01000] (Error 50000)  Adding additional info columns for newer versions of SQL [SQLSTATE 01000] (Error 50000)  Getting memory grant information for newer versions of SQL [SQLSTATE 01000] (Error 50000)  Getting spill information for newer versions of SQL [SQLSTATE 01000] (Error 50000)  Adding SQL to collect trigger stats. [SQLSTATE 01000] (Error 50000)  Collecting execution plan information. [SQLSTATE 01000] (Error 50000)  Skipping analysis, going to results [SQLSTATE 01000] (Error 50000)  Displaying analysis of plan cache. [SQLSTATE 01000] (Error 50000)  Returning ExpertMode = 0 [SQLSTATE 01000] (Error 50000)  Must declare the scalar variable "@buffer_pool_memory_gb". [SQLSTATE 42000] (Error 137)  Must declare the scalar variable "@buffer_pool_memory_gb". [SQLSTATE 42000] (Error 137)  Writing results to table. [SQLSTATE 01000] (Error 50000)  Checking @MinutesBack validity. [SQLSTATE 01000] (Error 50000)  Creating temp tables for results and warnings. [SQLSTATE 01000] (...  The step failed.

2. Exec sp_BlitzCache + errors below:

Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking for Read intent databases to exclude
Checking plan cache age
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring readable secondaries databases by default
Ignoring system databases by default
Applying chosen sort order
Getting spill information for newer versions of SQL
Adding additional info columns for newer versions of SQL
Getting memory grant information for newer versions of SQL
Getting spill information for newer versions of SQL
Adding SQL to collect trigger stats.
Collecting execution plan information.
Attempting to aggregate stored proc info from separate statements
Computing CPU, duration, read, and write metrics
Update CPU percentage for stored procedures
Gather percentage information from grouped results
Begin XML nodes processing
Gathering high level plan information
Warning: Null value is eliminated by an aggregate or other SET operation.
Performing query level checks
Performing compile timeout checks
Performing compile memory limit exceeded checks
Gathering trivial plans
Gathering statement costs
Updating statement costs
Gathering stored procedure costs
Checking for plan warnings
Checking for implicit conversion
Performing TVF join check
Checking for table variables
Checking for expensive key lookups
Checking for expensive remote queries
Checking for expensive sorts
Cursor plans found, investigating
Checking for Optimistic cursors
Checking if cursor is Forward Only
Checking if cursor is Fast Forward
Checking for Dynamic cursors
Checking for filters that reference scalar UDFs
Checking for wonky Index Spools
Checking for wonky Table Spools
Checking for selects that cause non-spill and index spool writes
Checking for forced serialization
Checking for downlevel cardinality estimators being used on SQL Server 2014.
Gathering additional plan level information
Warning: Null value is eliminated by an aggregate or other SET operation.
Attempting to get stored procedure name for individual statements
Attempting to get function name for individual statements
Trace flag checks
Checking for MSTVFs
Checking for non-sargable predicates
Getting information about implicit conversions and stored proc parameters
Getting variable info
Getting conversion info
Parsing conversion info
Updating variables for inserted procs
Inserting variables for other procs
Updating procs
Updating SET options
Updating conversion XML
Updating cached parameter XML for stored procs
Updating cached parameter XML for statements
Filling in implicit conversion and cached plan parameter info
Inserting to #missing_index_xml
Inserting to #missing_index_schema
Inserting to #missing_index_usage
Inserting to #missing_index_detail
Inserting to missing indexes to #missing_index_pretty
Inserting to #index_spool_ugly
Inserting to spools to #missing_index_pretty
Updating missing index information
Filling in missing index blanks
Setting configuration values
Checking for query level SQL Server issues.
Checking for forced parameterization and cursors.
Populating Warnings column
Populating Warnings column for stored procedures
Checking for plans with >128 levels of nesting
Checking for plans with no warnings
Displaying analysis of plan cache.
Returning ExpertMode = 0
Msg 137, Level 15, State 1, Line 84
Must declare the scalar variable "@buffer_pool_memory_gb".
Msg 137, Level 15, State 1, Line 84
Must declare the scalar variable "@buffer_pool_memory_gb".
Building query plan summary data.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Scheduled SQL Agent job as above 
2. Exec sp_BlitzCache

**What is the expected behavior?**
1. Scheduled sp_BlitzFirst jobs run consistently without error.
2. Manual sp_BlitzCache jobs run without error.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2016, 2014, 2008R2; Windows 2012 R2

**Comment by BrentOzar** [comment]
Hi! Can you get on the latest dev branch of sp_BlitzCache: 

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzCache.sql

**Comment by Brianc-DBA** [comment]
Hi Brent, I updated sp_BlitzCache with that version, but still received the same error on execution:

...
Returning ExpertMode = 0
Msg 137, Level 15, State 1, Line 84
Must declare the scalar variable "@buffer_pool_memory_gb".
Msg 137, Level 15, State 1, Line 84
Must declare the scalar variable "@buffer_pool_memory_gb".
Building query plan summary data.

**Comment by Brianc-DBA** [comment]
I'm not certain if we can call this fully great news, but I have an update.  There were no sp_Blitzfirst job failures in the last 24 hours, and sp_BlitzCache now runs manually without error.

So it looks like whatever the issue was (locking? other resource contention?) resolved itself.  Like I said, it was intermittent - in 3 out of the 32 non-production servers I implemented the latest FRK version on, there would be maybe 5-10 failures a day in the every-15-minute-schedule sp_BlitzCache job runs.  All in clumps, but not generally when backups and the like were running.  So I don't know if the behavior can be explained at all?

**Comment by BrentOzar** [comment]
OK, great - I'll close this, but if you can reproduce it, try the latest dev version first, and we can go from there. Thanks!
