### ISSUE TITLE
Strange characters in 2 lines in sp_blitz.sql

### ISSUE THREAD

**Issue by parlevjo2** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2378]
Version of the script: '7.95', Date: 20200506

Line 5866 Checkid 234
							FROM**Â** master.sys.master_files f
							WHERE**Â** (f.name**Â** =**Â** N'master')

Gives error 
Msg 102, Level 15, State 1, Procedure sp_Blitz, Line 5863 [Batch Start Line 3]
Incorrect syntax near 'FROMÂ'.
when executing
EXEC [master].[dbo].[sp_Blitz]

**Comment by BrentOzar** [comment]
Great, thanks, fixed.

**Comment by parlevjo2** [comment]
Hi Brentozar

You are not going to change http://public.brentozar.com/FirstResponderKit.zip ?

**Comment by BrentOzar** [comment]
Not until the monthly release. I only change that once per month.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws
