### ISSUE TITLE
Consultant Toolkit: BlitzWho Memory Grant Hint missing

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2382]
**Version of the script**
2020-05-06

**What is the current behavior?**
No memory cap is present on the BlitzWho query

```
/* If the server has > 50GB of memory, add a max grant hint to avoid getting a giant grant */
IF (@ProductVersionMajor = 11 AND @ProductVersionMinor >= 6020)
	OR (@ProductVersionMajor = 12 AND @ProductVersionMinor >= 5000 )
	OR (@ProductVersionMajor >= 13 )
	AND 50000000 < (SELECT cntr_value 			
						FROM sys.dm_os_performance_counters 
						WHERE object_name LIKE '%:Memory Manager%'
						AND counter_name LIKE 'Target Server Memory (KB)%')
	BEGIN
		SET @StringToExecute = @StringToExecute + N' OPTION (MAX_GRANT_PERCENT = 1, RECOMPILE) ';
	END
ELSE
	BEGIN
		SET @StringToExecute = @StringToExecute + N' OPTION (RECOMPILE) ';
	END

/* Be good: */
SET @StringToExecute = @StringToExecute + N' ; ';
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Open script, reveal missing hint. 

Alternately, run the exe and see BlitzWho in BlitzCache's memory tab 😬

**What is the expected behavior?**
Memory should be capped on BlitzWho in the CTK as it is in the FRK

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Only SQL Server 2012+, where the hint is present.

Please to thank me for the model bug report.

**Comment by BrentOzar** [comment]
Oh wow, I totally forgot we even had sp_BlitzWho in there. It hadn't been updated in 2 years. Fixed, will be in the June release. Thanks for the supermodel bug report!
