### ISSUE TITLE
sp_Blitz - report on "invalid" logins

### ISSUE THREAD

**Issue by jeffchulg** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2387]
**Is your feature request related to a problem? Please describe.**

When a Windows login is disabled in Active Directory and this login is defined in SQL Server, there should be an advice fired by sp_Blitz to drop this login.

**Describe the solution you'd like**

A simple row Security - Invalid Logins and a detail with the list of the invalid logins

**Describe alternatives you've considered**

```
DECLARE @ExecRet INT;

IF(OBJECT_ID('tempdb..#Logins2Drop') IS NOT NULL)
BEGIN
    EXEC sp_executesql N'DROP TABLE #Logins2Drop;';
END;

CREATE TABLE #Logins2Drop (
    LoginSID    varbinary(85),
    LoginName   VARCHAR(256)
)
EXEC @ExecRet = sp_validatelogins 
;

-- check @ExecRet = 0

SELECT * FROM #Logins2Drop;
```

**Are you ready to build the code for the feature?**
As much as we'd love to build everything that everyone wants for free, we need your help. Open source is built with your help and code. Are you ready to commit time to this project? Have you got existing code you can help contribute to solve the problem?

See code below.
I can submit a pull request, but a CheckId should be assigned to this test before...

**Comment by BrentOzar** [comment]
Sure, sounds good! You can assign a CheckId by editing the file in Documentation.

**Comment by BrentOzar** [comment]
Awesome, thanks sir! Merged into dev, and it'll be in the June release this week along with credit for you in the release notes. Thanks!
