### ISSUE TITLE
Sp_BlitzFirst / Sp_BlitzCache intermittent failures

### ISSUE THREAD

**Issue by Brianc-DBA** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2389]
**Version of the script**
@Version = '7.95', @VersionDate = '20200506' (latest dev release)

**What is the current behavior?**
See #2376 for reference.  We were still getting intermittent failures, so I've been updating with every new version to see if that would fix it.  So far it hasn't; weird that it doesn't fail all the time though.  I'm running it just like the comments at the end of sp_BlitzFirst states - I think there are new requirements to execute the script and load into a table.

We have a job running BlitzFirst every 15 minutes to capture data for the PowerBI Dashboard. Ever since the newest version has been implemented, there are intermittent failures of the job on different versions of SQL.  I can run BlitzFirst or BlitzCache manually with no special parameters.  If I try to load it into the table as per the job it complains. The manual run error seems to state "Invalid column name 'LastCompletionTime'"

Scheduled SQL Agent job + errors below:
EXEC sp_BlitzFirst
@OutputDatabaseName = 'DBA',
@OutputSchemaName = 'dbo',
@OutputTableName = 'BlitzFirst',
@OutputTableNameFileStats = 'BlitzFirst_FileStats',
@OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
@OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
@OutputTableNameBlitzCache = 'BlitzCache',
@OutputTableNameBlitzWho = 'BlitzWho';

-- manual run error:
Setting up configuration variables
Now starting diagnostic analysis
Checking for Read intent databases to exclude
Capturing first pass of wait stats, perfmon counters, file stats
Logging sp_BlitzWho to table
Beginning investigatory queries
Finished running investigatory queries
Waiting to match @Seconds parameter
Capturing second pass of wait stats, perfmon counters, file stats
Analyzing changes between first and second passes of DMVs
Analysis finished, outputting results
Determining SQL Server version.
Calling sp_BlitzCache
Checking @MinutesBack validity.
Setting @MinutesBack to a negative number
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Checking all sort orders, please be patient
Beginning all sort loop
Beginning for ALL
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking for Read intent databases to exclude
Checking plan cache age
Checking for single use plans and plans with many queries
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring readable secondaries databases by default
Ignoring system databases by default
Setting minutes back filter
Applying chosen sort order
Getting spill information for newer versions of SQL
Adding additional info columns for newer versions of SQL
Getting memory grant information for newer versions of SQL
Getting spill information for newer versions of SQL
Adding SQL to collect trigger stats.
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Writing results to table.
Msg 207, Level 16, State 1, Line 1
Invalid column name 'LastCompletionTime'.
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking for Read intent databases to exclude
Checking plan cache age
Checking for single use plans and plans with many queries
Processing SQL Handles To Ignore
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring readable secondaries databases by default
Ignoring system databases by default
Including only chosen SQL Handles
Setting minutes back filter
Applying chosen sort order
Getting spill information for newer versions of SQL
Adding additional info columns for newer versions of SQL
Getting memory grant information for newer versions of SQL
Getting spill information for newer versions of SQL
Adding SQL to collect trigger stats.
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Writing results to table.
Msg 207, Level 16, State 1, Line 1
Invalid column name 'LastCompletionTime'.
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking for Read intent databases to exclude
Checking plan cache age
Checking for single use plans and plans with many queries
Processing SQL Handles To Ignore
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring readable secondaries databases by default
Ignoring system databases by default
Including only chosen SQL Handles
Setting minutes back filter
Applying chosen sort order
Getting spill information for newer versions of SQL
Adding additional info columns for newer versions of SQL
Getting memory grant information for newer versions of SQL
Getting spill information for newer versions of SQL
Adding SQL to collect trigger stats.
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Writing results to table.
Msg 207, Level 16, State 1, Line 1
Invalid column name 'LastCompletionTime'.
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking for Read intent databases to exclude
Checking plan cache age
Checking for single use plans and plans with many queries
Processing SQL Handles To Ignore
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring readable secondaries databases by default
Ignoring system databases by default
Including only chosen SQL Handles
Setting minutes back filter
Applying chosen sort order
Getting spill information for newer versions of SQL
Adding additional info columns for newer versions of SQL
Getting memory grant information for newer versions of SQL
Getting spill information for newer versions of SQL
Adding SQL to collect trigger stats.
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Writing results to table.
Msg 207, Level 16, State 1, Line 1
Invalid column name 'LastCompletionTime'.
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking for Read intent databases to exclude
Checking plan cache age
Checking for single use plans and plans with many queries
Processing SQL Handles To Ignore
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring readable secondaries databases by default
Ignoring system databases by default
Including only chosen SQL Handles
Setting minutes back filter
Applying chosen sort order
Getting spill information for newer versions of SQL
Adding additional info columns for newer versions of SQL
Getting memory grant information for newer versions of SQL
Getting spill information for newer versions of SQL
Adding SQL to collect trigger stats.
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Writing results to table.
Msg 207, Level 16, State 1, Line 1
Invalid column name 'LastCompletionTime'.
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking for Read intent databases to exclude
Checking plan cache age
Checking for single use plans and plans with many queries
Processing SQL Handles To Ignore
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring readable secondaries databases by default
Ignoring system databases by default
Including only chosen SQL Handles
Setting minutes back filter
Applying chosen sort order
Getting spill information for newer versions of SQL
Adding additional info columns for newer versions of SQL
Getting memory grant information for newer versions of SQL
Getting spill information for newer versions of SQL
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Writing results to table.
Msg 207, Level 16, State 1, Line 1
Invalid column name 'LastCompletionTime'.
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking for Read intent databases to exclude
Checking plan cache age
Checking for single use plans and plans with many queries
Processing SQL Handles To Ignore
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring readable secondaries databases by default
Ignoring system databases by default
Including only chosen SQL Handles
Setting minutes back filter
Applying chosen sort order
Getting spill information for newer versions of SQL
Adding additional info columns for newer versions of SQL
Getting memory grant information for newer versions of SQL
Getting spill information for newer versions of SQL
Adding SQL to collect trigger stats.
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Writing results to table.
Msg 207, Level 16, State 1, Line 1
Invalid column name 'LastCompletionTime'.
Writing results to table.
sp_BlitzCache Finished

-- scheduled run error:
Executed as user: [name removed] ...essage 50000)  Now starting diagnostic analysis [SQLSTATE 01000] (Message 50000)  Checking for Read intent databases to exclude [SQLSTATE 01000] (Message 50000)  Capturing first pass of wait stats, perfmon counters, file stats [SQLSTATE 01000] (Message 50000)  Logging sp_BlitzWho to table [SQLSTATE 01000] (Message 50000)  Beginning investigatory queries [SQLSTATE 01000] (Message 50000)  Finished running investigatory queries [SQLSTATE 01000] (Message 50000)  Capturing second pass of wait stats, perfmon counters, file stats [SQLSTATE 01000] (Message 50000)  Analyzing changes between first and second passes of DMVs [SQLSTATE 01000] (Message 50000)  Analysis finished, outputting results [SQLSTATE 01000] (Message 50000)  Determining SQL Server version. [SQLSTATE 01000] (Message 50000)  Calling sp_BlitzCache [SQLSTATE 01000] (Message 50000)  Checking @MinutesBack validity. [SQLSTATE 01000] (Message 50000)  Setting @MinutesBack to a negative number [SQLSTATE 01000] (Message 50000)  Creating temp tables for results and warnings. [SQLSTATE 01000] (Message 50000)  Checking database validity [SQLSTATE 01000] (Message 50000)  Checking sort order [SQLSTATE 01000] (Message 50000)  Skip Analysis set to 1, hiding Summary [SQLSTATE 01000] (Message 50000)  Cleaning up old warnings for your SPID [SQLSTATE 01000] (Message 50000)  Cleaning up old plans for your SPID [SQLSTATE 01000] (Message 50000)  Checking all sort orders, please be patient [SQLSTATE 01000] (Message 50000)  Beginning all sort loop [SQLSTATE 01000] (Message 50000)  Beginning for ALL [SQLSTATE 01000] (Message 50000)  Invalid column name 'LastCompletionTime'. [SQLSTATE 42S22] (Error 207)  Checking @MinutesBack validity. [SQLSTATE 01000] (Error 50000)  Creating temp tables for results and warnings. [SQLSTATE 01000] (Error 50000)  Checking database validity [SQLSTATE 01000] (Error 50000)  Checking sort order [SQLSTATE 01000] (Error 50000)  Skip Analysis set to 1, hiding Summary [SQLSTATE 01000] (Error 50000)  Cleaning up old warnings for your SPID [SQLSTATE 01000] (Error 50000)  Cleaning up old plans for your SPID [SQLSTATE 01000] (Error 50000)  Creating temp tables for internal processing [SQLSTATE 01000] (Error 50000)  Checking for Read intent databases to exclude [SQLSTATE 01000] (Error 50000)  Checking plan cache age [SQLSTATE 01000] (Error 50000)  Checking for single use plans and plans with many queries [SQLSTATE 01000] (Error 50000)  Setting up variables [SQLSTATE 01000] (Error 50000)  Determining SQL Server version. [SQLSTATE 01000] (Error 50000)  Creating dynamic SQL based on SQL Server version. [SQLSTATE 01000] (Error 50000)  Ignoring readable secondaries databases by default [SQLSTATE 01000] (Error 50000)  Ignoring system databases by default [SQLSTATE 01000] (Error 50000)  Setting minutes back filter [SQLSTATE 01000] (Error 50000)  Applying chosen sort order [SQLSTATE 01000] (Error 50000)  Getting spill information for newer versions of SQL [SQLSTATE 01000] (Error 50000)  Adding additional info columns for newer versions of SQL [SQLSTATE 01000] (Error 50000)  Getting memory grant information for newer versions of SQL [SQLSTATE 01000] (Error 50000)  Getting spill information for newer versions of SQL [SQLSTATE 01000] (Error 50000)  Adding SQL to collect trigger stats. [SQLSTATE 01000] (Error 50000)  Collecting execution plan information. [SQLSTATE 01000] (Error 50000)  Skipping analysis, going to results [SQLSTATE 01000] (Error 50000)  Displaying analysis of plan cache. [SQLSTATE 01000] (Error 50000)  Returning ExpertMode = 0 [SQLSTATE 01000] (Error 50000)  Writing results to table. [SQLSTATE 01000] (Error 50000)  Checking @MinutesBack validity. [SQLSTATE 01000] (Message 50000)  Creating temp tables for results and warnings. [SQLSTATE 01000] (Message 50000)  Checking database validity [SQLSTATE 01000] (Message 50000)  Checking sort order [SQLSTATE 01000] (Message 50000)  Skip Analysis set to 1, hiding Summary [SQ...  The step failed.

**If the current behavior is a bug, please provide the steps to reproduce.**
As above

**What is the expected behavior?**
Runs without error

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Tested on SQL 2019, but the intermittent failures happen from SQL 2008R2 - 2019

**Comment by rrankins** [comment]
I can answer this one regarding the LastCompletionTime missing column. the latest dev version now adds LastcompletionTime as an output and also for fixing an issue where sp_blitzcache was not recording queries that started before the last capture ran but finished after because the start time did not happen within the last @minutesBack, even if it completed within that timeframe. Checking LastCompletionTime fixed that. To fix the issue with the missing column, you just need to add LastCompletionTime to the BlitzCache table. 
ALTER TABLE BlitzCache add LastCompletionTime Datetime NULL

**Comment by Brianc-DBA** [comment]
Thanks, @rrankins.  I think that was a partial fix.  It is no longer failing on every server after I made the alter table change you stated.

Still getting occasional failures on some servers, as it was before the two changes you referenced.  It errors with: 'Must declare the scalar variable "@buffer_pool_memory_gb"' like in my previous bug #2376:

Executed as user: [removed]. Setting up configuration variables [SQLSTATE 01000] (Message 50000)  Now starting diagnostic analysis [SQLSTATE 01000] (Message 50000)  Capturing first pass of wait stats, perfmon counters, file stats [SQLSTATE 01000] (Message 50000)  Logging sp_BlitzWho to table [SQLSTATE 01000] (Message 50000)  Warning: The join order has been enforced because a local join hint is used. [SQLSTATE 01000] (Message 8625)  Beginning investigatory queries [SQLSTATE 01000] (Message 50000)  Warning: The join order has been enforced because a local join hint is used. [SQLSTATE 01000] (Message 8625)  Warning: The join order has been enforced because a local join hint is used. [SQLSTATE 01000] (Message 8625)  Finished running investigatory queries [SQLSTATE 01000] (Message 50000)  Waiting to match @Seconds parameter [SQLSTATE 01000] (Message 50000)  Capturing second pass of wait stats, perfmon counters, file stats [SQLSTATE 01000] (Message 50000)  Analyzing changes between first and second passes of DMVs [SQLSTATE 01000] (Message 50000)  Analysis finished, outputting results [SQLSTATE 01000] (Message 50000)  Determining SQL Server version. [SQLSTATE 01000] (Message 50000)  Calling sp_BlitzCache [SQLSTATE 01000] (Message 50000)  Checking @MinutesBack validity. [SQLSTATE 01000] (Message 50000)  Setting @MinutesBack to a negative number [SQLSTATE 01000] (Message 50000)  Creating temp tables for results and warnings. [SQLSTATE 01000] (Message 50000)  Checking database validity [SQLSTATE 01000] (Message 50000)  Checking sort order [SQLSTATE 01000] (Message 50000)  Skip Analysis set to 1, hiding Summary [SQLSTATE 01000] (Message 50000)  Cleaning up old warnings for your SPID [SQLSTATE 01000] (Message 50000)  Cleaning up old plans for your SPID [SQLSTATE 01000] (Message 50000)  Checking all sort orders, please be patient [SQLSTATE 01000] (Message 50000)  Beginning all sort loop [SQLSTATE 01000] (Message 50000)  Beginning for ALL [SQLSTATE 01000] (Message 50000)  Must declare the scalar variable "@buffer_pool_memory_gb". [SQLSTATE 42000] (Error 137)  Must declare the scalar variable "@buffer_pool_memory_gb". [SQLSTATE 42000] (Error 137)  Checking @MinutesBack validity. [SQLSTATE 01000] (Error 50000)  Creating temp tables for results and warnings. [SQLSTATE 01000] (Error 50000)  Checking database validity [SQLSTATE 01000] (Error 50000)  Checking sort order [SQLSTATE 01000] (Error 50000)  Skip Analysis set to 1, hiding Summary [SQLSTATE 01000] (Error 50000)  Cleaning up old warnings for your SPID [SQLSTATE 01000] (Error 50000)  Cleaning up old plans for your SPID [SQLSTATE 01000] (Error 50000)  Creating temp tables for internal processing [SQLSTATE 01000] (Error 50000)  Checking plan cache age [SQLSTATE 01000] (Error 50000)  Checking for single use plans and plans with many queries [SQLSTATE 01000] (Error 50000)  Setting up variables [SQLSTATE 01000] (Error 50000)  Determining SQL Server version. [SQLSTATE 01000] (Error 50000)  Creating dynamic SQL based on SQL Server version. [SQLSTATE 01000] (Error 50000)  Ignoring system databases by default [SQLSTATE 01000] (Error 50000)  Setting minutes back filter [SQLSTATE 01000] (Error 50000)  Applying chosen sort order [SQLSTATE 01000] (Error 50000)  Substituting NULLs for spill columns in older versions of SQL [SQLSTATE 01000] (Error 50000)  Adding additional info columns for newer versions of SQL [SQLSTATE 01000] (Error 50000)  Substituting NULLs for memory grant columns in older versions of SQL [SQLSTATE 01000] (Error 50000)  Substituting NULLs for spill columns in older versions of SQL [SQLSTATE 01000] (Error 50000)  Collecting execution plan information. [SQLSTATE 01000] (Error 50000)  Skipping analysis, going to results [SQLSTATE 01000] (Error 50000)  Displaying analysis of plan cache. [SQLSTATE 01000] (Error 50000)  Returning ExpertMode = 0 [SQLSTATE 01000] (Error 50000).  The step failed.

**Comment by BrentOzar** [comment]
@Brianc-DBA yep, this error:

`Must declare the scalar variable "@buffer_pool_memory_gb".`

Was fixed in this pull request: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/2384

You'll need to apply that. Just FYI, you probably don't want to be using the dev branch builds unless you're ready to jump in and start troubleshooting them yourself - I don't test the dev branch builds until we're ready for our monthly release process. They haven't even been executed on 2008, case-sensitive servers, etc.

**Comment by Brianc-DBA** [comment]
Was the code from #2384 included in the latest dev release file?  That was the script I used.  
The issues started with the regular release after downloading the zip file, and as per the closing comments in #2376 I started using the dev branch versions in an attempt to fix my issues.  I haven't moved this into any of my prod systems yet since I don't want to be troubleshooting there.  I might just roll back to the April release instead of the May or post-May dev versions.

**Comment by BrentOzar** [comment]
There's no dev release - we only do releases from master. 

Yeah, you're best rolling back to a production release that you're comfortable with - I totally appreciate that you want to help, but if you're not comfortable with GitHub and dev branches, you're best not using this code in production. I'm very limited as to how much training I can do on this kind of thing - I'm kinda maxed out there. Thanks for understanding!

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws
