### ISSUE TITLE
sp_DatabaseRestore cant restore split diff and split log backups

### ISSUE THREAD

**Issue by ggoncz** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2394]
**Version of the script**
7.95

**What is the current behavior?**
I have split diff backups (4 files) and the script tries to restore the last one only from the set.
I tested it only with split diff backups but I have split log backups too. I've checked the code and I think only the full restore can manage the split backups.

**If the current behavior is a bug, please provide the steps to reproduce.**
Use diff backups with multiple files

**What is the expected behavior?**
Restore the split diff and split log backups as same as the full restore,,

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2019

**Comment by BrentOzar** [comment]
Hi. Yes, that's been reported before:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/2220

I don’t use that proc myself anymore, so if there’s a feature you’d like to see added (like handling multiple differential files), you would need to code it yourself, or reach out to other folks in the community to see if they’d be willing to code it for you (possibly for hire.) To learn more about that, read the contributing guide for This project, linked to from the home page of the project. Does this sound like something you’d be interested in tackling?

**Comment by BrentOzar** [comment]
I haven't heard back from you, so I'll go ahead and close this. If you change your mind and want to tackle it, just come back here and leave a comment. Thanks!
