### ISSUE TITLE
SQL 2008, sp_Blitz error

### ISSUE THREAD

**Issue by slpefanis** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2395]
**Version of the script**
7.95

**What is the current behavior?**
Error when running script 
"Msg 102, Level 15, State 1, Procedure sp_Blitz, Line 5863 [Batch Start Line 3]
Incorrect syntax near ' '."

**If the current behavior is a bug, please provide the steps to reproduce.**
Just execute the script against the master database

**What is the expected behavior?**
Procedure created

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Version 10.50.6220.0

**Comment by BrentOzar** [comment]
Howdy. This was fixed in an earlier issue - grab the latest dev build from here:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_Blitz.sql

And if that doesn't fix it, report back. No reply necessary if that fixes it. Thanks!
