### ISSUE TITLE
String or binary data would be truncated in table 'DBAtools.dbo.BlitzFirst', column 'Details'

### ISSUE THREAD

**Issue by KellyHanna** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2412]
Install the new version of the script  today
sp_BlitzFirst 2020-06-02 00:00:00.0000000 +00:00

Then created an agent job to output  the  results to  tables 
When I  ran the script it failed  with the following  error 
String or binary data would be truncated in table 'DBAtools.dbo.BlitzFirst', column 'Details'

I change the  column definition to nvarchar (max).
Then I reran the script and it worked .
 Need to up the script that creates the table to make the column larger

**Comment by BrentOzar** [comment]
Hi - yep, fixed here: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/2409
