### ISSUE TITLE
sp_BlitzWho - error while running with storage to table not existing at execution

### ISSUE THREAD

**Issue by jeffchulg** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2421]
**Version of the script**
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.

@Version = '7.96', @VersionDate = '20200602'

**What is the current behavior?**

Fails at execution, looks like the value assigned to @StringToExecute is truncated at second occurrence of "varbinary".

**If the current behavior is a bug, please provide the steps to reproduce.**

EXEC sp_BlitzWho @OutputDatabaseName = @CurrentDbName, @OutputSchemaName = 'FirstResponderKit', @OutputTableName = 'BlitzWhoExecutionHistory', @Debug = 1;

**What is the expected behavior?**

No error.

Simply cut the statement into two parts and it will work.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

SQL Server 2019

**Comment by BrentOzar** [comment]
It's working fine here - I just took the latest dev branch and ran it. Can you give me the exact error you're getting?

**Comment by BrentOzar** [comment]
You may also want to check the code you've got that's setting @CurrentDbName - try running it with a real database name string and see if that works.

**Comment by BrentOzar** [comment]
Oh also, make sure the schema already exists - we don't create schemas.

**Comment by jeffchulg** [comment]
Everything exists... except the destination table

Complete Code:
```
DECLARE @CurrentDbName SYSNAME;
SET @CurrentDbName = DB_NAME();

EXEC sp_BlitzWho 
            @OutputDatabaseName = @CurrentDbName, 
            @OutputSchemaName = 'FirstResponderKit', 
            @OutputTableName = 'TestBlitzWhoNoTableExists', 
            @debug = 1
;
```

Result:

`USE [DBA]; IF EXISTS(SELECT * FROM [SAIDBA].INFORMATION_SCHEMA.SCHEMATA WHERE QUOTENAME(SCHEMA_NAME) = '[FirstResponderKit]') AND NOT EXISTS (SELECT * FROM [SAIDBA].INFORMATION_SCHEMA.TABLES WHERE QUOTENAME(TABLE_SCHEMA) = '[FirstResponderKit]' AND QUOTENAME(TABLE_NAME) = '[TestBlitzWhoNoTableExists]') CREATE TABLE [FirstResponderKit].[TestBlitzWhoNoTableExists](
    ID INT IDENTITY(1,1) NOT NULL,
    ServerName NVARCHAR(128) NOT NULL,
    CheckDate DATETIMEOFFSET NOT NULL,
    [elapsed_time] [varchar](41) NULL,
    [session_id] [smallint] NOT NULL,
    [database_name] [nvarchar](128) NULL,
    [query_text] [nvarchar](max) NULL,
    [query_plan] [xml] NULL,
    [live_query_plan] [xml] NULL,
    [query_cost] [float] NULL,
    [status] [nvarchar](30) NOT NULL,
    [wait_info] [nvarchar](max) NULL,
    [top_session_waits] [nvarchar](max) NULL,
    [blocking_session_id] [smallint] NULL,
    [open_transaction_count] [int] NULL,
    [is_implicit_transaction] [int] NOT NULL,
    [nt_domain] [nvarchar](128) NULL,
    [host_name] [nvarchar](128) NULL,
    [login_name] [nvarchar](128) NOT NULL,
    [nt_user_name] [nvarchar](128) NULL,
    [program_name] [nvarchar](128) NULL,
    [fix_parameter_sniffing] [nvarchar](150) NULL,
    [client_interface_name] [nvarchar](32) NULL,
    [login_time] [datetime] NOT NULL,
    [start_time] [datetime] NULL,
    [request_time] [datetime] NULL,
    [request_cpu_time] [int] NULL,
    [request_logical_reads] [bigint] NULL,
    [request_writes] [bigint] NULL,
    [request_physical_reads] [bigint] NULL,
    [session_cpu] [int] NOT NULL,
    [session_logical_reads] [bigint] NOT NULL,
    [session_physical_reads] [bigint] NOT NULL,
    [session_writes] [bigint] NOT NULL,
    [tempdb_allocations_mb] [decimal](38, 2) NULL,
    [memory_usage] [int] NOT NULL,
    [estimated_completion_time] [bigint] NULL,
    [percent_complete] [real] NULL,
    [deadlock_priority] [int] NULL,
    [transaction_isolation_level] [varchar](33) NOT NULL,
    [degree_of_parallelism] [smallint] NULL,
    [last_dop] [bigint] NULL,
    [min_dop] [bigint] NULL,
    [max_dop] [bigint] NULL,
    [last_grant_kb] [bigint] NULL,
    [min_grant_kb] [bigint] NULL,
    [max_grant_kb] [bigint] NULL,
    [last_used_grant_kb] [bigint] NULL,
    [min_used_grant_kb] [bigint] NULL,
    [max_used_grant_kb] [bigint] NULL,
    [last_ideal_grant_kb] [bigint] NULL,
    [min_ideal_grant_kb] [bigint] NULL,
    [max_ideal_grant_kb] [bigint] NULL,
    [last_reserved_threads] [bigint] NULL,
    [min_reserved_threads] [bigint] NULL,
    [max_reserved_threads] [bigint] NULL,
    [last_used_threads] [bigint] NULL,
    [min_used_threads] [bigint] NULL,
    [max_used_threads] [bigint] NULL,
    [grant_time] [varchar](20) NULL,
    [requested_memory_kb] [bigint] NULL,
    [grant_memory_kb] [bigint] NULL,
    [is_request_granted] [varchar](39) NOT NULL,
    [required_memory_kb] [bigint] NULL,
    [query_memory_grant_used_memory_kb] [bigint] NULL,
    [ideal_memory_kb] [bigint] NULL,
    [is_small] [bit] NULL,
    [timeout_sec] [int] NULL,
    [resource_semaphore_id] [smallint] NULL,
    [wait_order] [varchar](20) NULL,
    [wait_time_ms] [varchar](20) NULL,
    [next_candidate_for_memory_grant] [varchar](3) NOT NULL,
    [target_memory_kb] [bigint] NULL,
    [max_target_memory_kb] [varchar](30) NULL,
    [total_memory_kb] [bigint] NULL,
    [available_memory_kb] [bigint] NULL,
    [granted_memory_kb] [bigint] NULL,
    [query_resource_semaphore_used_memory_kb] [bigint] NULL,
    [grantee_count] [int] NULL,
    [waiter_count] [int] NULL,
    [timeout_error_count] [bigint] NULL,
    [forced_grant_count] [varchar](30) NULL,
    [workload_group_name] [sysname] NULL,
    [resource_pool_name] [sysname] NULL,
    [context_info] [varchar](128) NULL,
    [query_hash] [binary](8) NULL,
    [query_plan_hash] [binary](8) NULL,
    [sql_handle] [varbinary](64) NULL,
    [plan_handle] [varbin
 
Msg 105, Niveau 15, État 1, Ligne 90
Unclosed quotation mark after the character string 'varbin'.
Msg 173, Niveau 15, État 13, Ligne 90
The definition for column 'plan_handle' must include a data type.
Msg 4902, Niveau 16, État 1, Ligne 3
Cannot find the object "SAIDBA.FirstResponderKit.TestBlitzWhoNoTableExists" because it does not exist or you do not have permissions.`

**Comment by BrentOzar** [comment]
Ahhh, yeah, between the sysname and the long schema name, that'd do it. I split the string concatenation up into two phases and now it works. Sorry about that!

**Comment by jeffchulg** [comment]
Also get the problem, not in the SP, but outside, when assigning a long concatenation of strings ...

`DECLARE @StringToExecute NVARCHAR(MAX);
SET @StringToExecute = N'USE '
	  + 'blablblablblablblablblablblablblabl'
	  + N'; IF EXISTS(SELECT * FROM '
	  + 'blablblablblablblablblablblablblabl'
	  + N'.INFORMATION_SCHEMA.SCHEMATA WHERE QUOTENAME(SCHEMA_NAME) = '''
	  + 'blablblablblablblablblablblablblabl'
	  + N''') AND NOT EXISTS (SELECT * FROM '
	  + 'blablblablblablblablblablblablblabl'
	  + N'.INFORMATION_SCHEMA.TABLES WHERE QUOTENAME(TABLE_SCHEMA) = '''
	  + 'blablblablblablblablblablblablblabl' + N''' AND QUOTENAME(TABLE_NAME) = '''
	  + 'blablblablblablblablblablblablblabl' + N''') CREATE TABLE '
	  + 'blablblablblablblablblablblablblabl' + N'.'
	  + 'blablblablblablblablblablblablblabl'
	  + N'(
	ID INT IDENTITY(1,1) NOT NULL,
	ServerName NVARCHAR(128) NOT NULL,
	CheckDate DATETIMEOFFSET NOT NULL,
	[elapsed_time] [varchar](41) NULL,
	[session_id] [smallint] NOT NULL,
	[database_name] [nvarchar](128) NULL,
	[query_text] [nvarchar](max) NULL,
	[query_plan] [xml] NULL,
	[live_query_plan] [xml] NULL,
	[query_cost] [float] NULL,
	[status] [nvarchar](30) NOT NULL,
	[wait_info] [nvarchar](max) NULL,
	[top_session_waits] [nvarchar](max) NULL,
	[blocking_session_id] [smallint] NULL,
	[open_transaction_count] [int] NULL,
	[is_implicit_transaction] [int] NOT NULL,
	[nt_domain] [nvarchar](128) NULL,
	[host_name] [nvarchar](128) NULL,
	[login_name] [nvarchar](128) NOT NULL,
	[nt_user_name] [nvarchar](128) NULL,
	[program_name] [nvarchar](128) NULL,
	[fix_parameter_sniffing] [nvarchar](150) NULL,
	[client_interface_name] [nvarchar](32) NULL,
	[login_time] [datetime] NOT NULL,
	[start_time] [datetime] NULL,
	[request_time] [datetime] NULL,
	[request_cpu_time] [int] NULL,
	[request_logical_reads] [bigint] NULL,
	[request_writes] [bigint] NULL,
	[request_physical_reads] [bigint] NULL,
	[session_cpu] [int] NOT NULL,
	[session_logical_reads] [bigint] NOT NULL,
	[session_physical_reads] [bigint] NOT NULL,
	[session_writes] [bigint] NOT NULL,
	[tempdb_allocations_mb] [decimal](38, 2) NULL,
	[memory_usage] [int] NOT NULL,
	[estimated_completion_time] [bigint] NULL,
	[percent_complete] [real] NULL,
	[deadlock_priority] [int] NULL,
	[transaction_isolation_level] [varchar](33) NOT NULL,
	[degree_of_parallelism] [smallint] NULL,
	[last_dop] [bigint] NULL,
	[min_dop] [bigint] NULL,
	[max_dop] [bigint] NULL,
	[last_grant_kb] [bigint] NULL,
	[min_grant_kb] [bigint] NULL,
	[max_grant_kb] [bigint] NULL,
	[last_used_grant_kb] [bigint] NULL,
	[min_used_grant_kb] [bigint] NULL,
	[max_used_grant_kb] [bigint] NULL,
	[last_ideal_grant_kb] [bigint] NULL,
	[min_ideal_grant_kb] [bigint] NULL,
	[max_ideal_grant_kb] [bigint] NULL,
	[last_reserved_threads] [bigint] NULL,
	[min_reserved_threads] [bigint] NULL,
	[max_reserved_threads] [bigint] NULL,
	[last_used_threads] [bigint] NULL,
	[min_used_threads] [bigint] NULL,
	[max_used_threads] [bigint] NULL,
	[grant_time] [varchar](20) NULL,
	[requested_memory_kb] [bigint] NULL,
	[grant_memory_kb] [bigint] NULL,
	[is_request_granted] [varchar](39) NOT NULL,
	[required_memory_kb] [bigint] NULL,
	[query_memory_grant_used_memory_kb] [bigint] NULL,
	[ideal_memory_kb] [bigint] NULL,
	[is_small] [bit] NULL,
	[timeout_sec] [int] NULL,
	[resource_semaphore_id] [smallint] NULL,
	[wait_order] [varchar](20) NULL,
	[wait_time_ms] [varchar](20) NULL,
	[next_candidate_for_memory_grant] [varchar](3) NOT NULL,
	[target_memory_kb] [bigint] NULL,
	[max_target_memory_kb] [varchar](30) NULL,
	[total_memory_kb] [bigint] NULL,
	[available_memory_kb] [bigint] NULL,
	[granted_memory_kb] [bigint] NULL,
	[query_resource_semaphore_used_memory_kb] [bigint] NULL,
	[grantee_count] [int] NULL,
	[waiter_count] [int] NULL,
	[timeout_error_count] [bigint] NULL,
	[forced_grant_count] [varchar](30) NULL,
	[workload_group_name] [sysname] NULL,
	[resource_pool_name] [sysname] NULL,
	[context_info] [varchar](128) NULL,
	[query_hash] [binary](8) NULL,
	[query_plan_hash] [binary](8) NULL,
	[sql_handle] [varbinary] (64) NULL,
	[plan_handle] [varbinary] (64) NULL,
	[statement_start_offset] INT NULL,
	[statement_end_offset] INT NULL,
	JoinKey AS ServerName + CAST(CheckDate AS NVARCHAR(50)),
	PRIMARY KEY CLUSTERED (ID ASC));';

PRINT @StringToExecute;`

The right part of the concatenation is limited to 4000 chars
