### ISSUE TITLE
sp_BlitzFirst - OutputType NONE with ExpertMode = 1 generates output tables/ResultsSets

### ISSUE THREAD

**Issue by jeffchulg** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2423]
**Version of the script**
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.

latest (20200602)

**What is the current behavior?**
When @OutputType = 'NONE' and @ExpertMode = 1, there are still SELECT queries that are fired during execution (due to conditions testing the ExpertMode = 0.

The point is that when I run a SQL Server Agent Job with ExpertMode = 1 to store reports to tables and that I log job activity to a log file, then each run takes at least 40Mo... Run it 4 times per hour, 24hours a day and it takes more or less 3Gb of disk space, for nothing...

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

No SELECT query run that leads to a dataset.

The point is that, when @ExpertMode = 1, there are checks that are performed in addition to normal checks
/* Server Info - SQL Compilations/sec - CheckID 25 */
/* Server Info - SQL Re-Compilations/sec - CheckID 26 */
Query  wait stats (etc)

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

any

**Comment by BrentOzar** [comment]
Sure, you're welcome to submit a pull request for that. I've assigned the issue to you. If you decide not to work on it, no worries - just let me know and I can close the issue.

**Comment by BrentOzar** [comment]
Good work! Thanks for the pull request. It's merged into dev, and it'll be in the July release. Thanks!
