### ISSUE TITLE
sp_BlitzCache Arithmetic Overflow

### ISSUE THREAD

**Issue by smcnaughton** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2425]
Seeing this error on several servers as of latest Master update (6/5/2020)

Error occurring multiple times in output

Msg 8115, Level 16, State 8, Procedure sp_BlitzCache, Line 1340 [Batch Start Line 0]
Arithmetic overflow error converting numeric to data type numeric.
The statement has been terminated.

**Comment by BrentOzar** [comment]
Howdy! I just checked line 1340, and it hasn't changed in 3 years. What I bet is happening is that this error is coming from the dynamic SQL, not from sp_BlitzCache itself. Can you try using the @Debug = 1 parameter, and then going to the Messages tab of SSMS, copying the dynamic SQL into an editor, finding line 1340, and then pasting that general region in here (like the 30 lines before & after) to help me track that down? Thanks!

**Comment by smcnaughton** [comment]
Didn't get anything that long in the message output using debug=1, I've included the entire outpt below. Even formatting the sql statement output in msg, wasn't longer than 500ish lines.

Checking @MinutesBack validity.
Setting @MinutesBack to a negative number
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Checking all sort orders, please be patient
Beginning all sort loop
Beginning for ALL

					DECLARE @ISH NVARCHAR(MAX) = N''

					INSERT #bou_allsort (	DatabaseName, Cost, QueryText, QueryType, Warnings, QueryPlan, missing_indexes, implicit_conversion_info, cached_execution_parameters, ExecutionCount, ExecutionsPerMinute, ExecutionWeight, 
											TotalCPU, AverageCPU, CPUWeight, TotalDuration, AverageDuration, DurationWeight, TotalReads, AverageReads, 
											ReadWeight, TotalWrites, AverageWrites, WriteWeight, AverageReturnedRows, MinGrantKB, MaxGrantKB, MinUsedGrantKB, 
											MaxUsedGrantKB, AvgMaxMemoryGrant, MinSpills, MaxSpills, TotalSpills, AvgSpills, PlanCreationTime, LastExecutionTime, LastCompletionTime, PlanHandle, SqlHandle, SetOptions, RemovePlanHandleFromCache ) 					 
					 
					 EXEC sp_BlitzCache @ExpertMode = 0, @HideSummary = 1, @Top = @i_Top, @SortOrder = 'cpu', 
                     @DatabaseName = @i_DatabaseName, @SkipAnalysis = @i_SkipAnalysis, @OutputDatabaseName = @i_OutputDatabaseName, @OutputSchemaName = @i_OutputSchemaName, @OutputTableName = @i_OutputTableName, @CheckDateOverride = @i_CheckDateOverride, @MinutesBack = @i_MinutesBack WITH RECOMPILE;
					 
					 UPDATE #bou_allsort SET Pattern = 'cpu' WHERE Pattern IS NULL OPTION(RECOMPILE);

					 SELECT TOP 1 @ISH = STUFF((SELECT DISTINCT N',' + CONVERT(NVARCHAR(MAX),b2.SqlHandle, 1) FROM #bou_allsort AS b2 FOR XML PATH(N''), TYPE).value(N'.[1]', N'NVARCHAR(MAX)'), 1, 1, N'') OPTION(RECOMPILE);

					INSERT #bou_allsort (	DatabaseName, Cost, QueryText, QueryType, Warnings, QueryPlan, missing_indexes, implicit_conversion_info, cached_execution_parameters, ExecutionCount, ExecutionsPerMinute, ExecutionWeight, 
											TotalCPU, AverageCPU, CPUWeight, TotalDuration, AverageDuration, DurationWeight, TotalReads, AverageReads, 
											ReadWeight, TotalWrites, AverageWrites, WriteWeight, AverageReturnedRows, MinGrantKB, MaxGrantKB, MinUsedGrantKB, 
											MaxUsedGrantKB, AvgMaxMemoryGrant, MinSpills, MaxSpills, TotalSpills, AvgSpills, PlanCreationTime, LastExecutionTime, LastCompletionTime, PlanHandle, SqlHandle, SetOptions, RemovePlanHandleFromCache ) 					 
					 
					 EXEC sp_BlitzCache @ExpertMode = 0, @HideSummary = 1, @Top = @i_Top, @SortOrder = 'reads', @IgnoreSqlHandles = @ISH, 
                     @DatabaseName = @i_DatabaseName, @SkipAnalysis = @i_SkipAnalysis, @OutputDatabaseName = @i_OutputDatabaseName, @OutputSchemaName = @i_OutputSchemaName, @OutputTableName = @i_OutputTableName, @CheckDateOverride = @i_CheckDateOverride, @MinutesBack = @i_MinutesBack WITH RECOMPILE;
					 
					 UPDATE #bou_allsort SET Pattern = 'reads' WHERE Pattern IS NULL OPTION(RECOMPILE);

					 SELECT TOP 1 @ISH = STUFF((SELECT DISTINCT N',' + CONVERT(NVARCHAR(MAX),b2.SqlHandle, 1) FROM #bou_allsort AS b2 FOR XML PATH(N''), TYPE).value(N'.[1]', N'NVARCHAR(MAX)'), 1, 1, N'') OPTION(RECOMPILE);

					INSERT #bou_allsort (	DatabaseName, Cost, QueryText, QueryType, Warnings, QueryPlan, missing_indexes, implicit_conversion_info, cached_execution_parameters, ExecutionCount, ExecutionsPerMinute, ExecutionWeight, 
											TotalCPU, AverageCPU, CPUWeight, TotalDuration, AverageDuration, DurationWeight, TotalReads, AverageReads, 
											ReadWeight, TotalWrites, AverageWrites, WriteWeight, AverageReturnedRows, MinGrantKB, MaxGrantKB, MinUsedGrantKB, 
											MaxUsedGrantKB, AvgMaxMemoryGrant, MinSpills, MaxSpills, TotalSpills, AvgSpills, PlanCreationTime, LastExecutionTime, LastCompletionTime, PlanHandle, SqlHandle, SetOptions, RemovePlanHandleFromCache ) 					 
					 
					 EXEC sp_BlitzCache @ExpertMode = 0, @HideSummary = 1, @Top = @i_Top, @SortOrder = 'writes', @IgnoreSqlHandles = @ISH, 
                     @DatabaseName = @i_DatabaseName, @SkipAnalysis = @i_SkipAnalysis, @OutputDatabaseName = @i_OutputDatabaseName, @OutputSchemaName = @i_OutputSchemaName, @OutputTableName = @i_OutputTableName, @CheckDateOverride = @i_CheckDateOverride, @MinutesBack = @i_MinutesBack WITH RECOMPILE;
			
		 
					 UPDATE #bou_allsort SET Pattern = 'writes' WHERE Pattern IS NULL OPTION(RECOMPILE);

					 SELECT TOP 1 @ISH = STUFF((SELECT DISTINCT N',' + CONVERT(NVARCHAR(MAX),b2.SqlHandle, 1) FROM #bou_allsort AS b2 FOR XML PATH(N''), TYPE).value(N'.[1]', N'NVARCHAR(MAX)'), 1, 1, N'') OPTION(RECOMPILE);

					INSERT #bou_allsort (	DatabaseName, Cost, QueryText, QueryType, Warnings, QueryPlan, missing_indexes, implicit_conversion_info, cached_execution_parameters, ExecutionCount, ExecutionsPerMinute, ExecutionWeight, 
											TotalCPU, AverageCPU, CPUWeight, TotalDuration, AverageDuration, DurationWeight, TotalReads, AverageReads, 
											ReadWeight, TotalWrites, AverageWrites, WriteWeight, AverageReturnedRows, MinGrantKB, MaxGrantKB, MinUsedGrantKB, 
											MaxUsedGrantKB, AvgMaxMemoryGrant, MinSpills, MaxSpills, TotalSpills, AvgSpills, PlanCreationTime, LastExecutionTime, LastCompletionTime, PlanHandle, SqlHandle, SetOptions, RemovePlanHandleFromCache ) 					 
					 
					 EXEC sp_BlitzCache @ExpertMode = 0, @HideSummary = 1, @Top = @i_Top, @SortOrder = 'duration', @IgnoreSqlHandles = @ISH, 
                     @DatabaseName = @i_DatabaseName, @SkipAnalysis = @i_SkipAnalysis, @OutputDatabaseName = @i_OutputDatabaseName, @OutputSchemaName = @i_OutputSchemaName, @OutputTableName = @i_OutputTableName, @CheckDateOverride = @i_CheckDateOverride, @MinutesBack = @i_MinutesBack WITH RECOMPILE;
					 
					 UPDATE #bou_allsort SET Pattern = 'duration' WHERE Pattern IS NULL OPTION(RECOMPILE);

					 SELECT TOP 1 @ISH = STUFF((SELECT DISTINCT N',' + CONVERT(NVARCHAR(MAX),b2.SqlHandle, 1) FROM #bou_allsort AS b2 FOR XML PATH(N''), TYPE).value(N'.[1]', N'NVARCHAR(MAX)'), 1, 1, N'') OPTION(RECOMPILE);

					INSERT #bou_allsort (	DatabaseName, Cost, QueryText, QueryType, Warnings, QueryPlan, missing_indexes, implicit_conversion_info, cached_execution_parameters, ExecutionCount, ExecutionsPerMinute, ExecutionWeight, 
											TotalCPU, AverageCPU, CPUWeight, TotalDuration, AverageDuration, DurationWeight, TotalReads, AverageReads, 
											ReadWeight, TotalWrites, AverageWrites, WriteWeight, AverageReturnedRows, MinGrantKB, MaxGrantKB, MinUsedGrantKB, 
											MaxUsedGrantKB, AvgMaxMemoryGrant, MinSpills, MaxSpills, TotalSpills, AvgSpills, PlanCreationTime, LastExecutionTime, LastCompletionTime, PlanHandle, SqlHandle, SetOptions, RemovePlanHandleFromCache ) 					 
					 
					 EXEC sp_BlitzCache @ExpertMode = 0, @HideSummary = 1, @Top = @i_Top, @SortOrder = 'executions', @IgnoreSqlHandles = @ISH, 
                     @DatabaseName = @i_DatabaseName, @SkipAnalysis = @i_SkipAnalysis, @OutputDatabaseName = @i_OutputDatabaseName, @OutputSchemaName = @i_OutputSchemaName, @OutputTableName = @i_OutputTableName, @CheckDateOverride = @i_CheckDateOverride, @MinutesBack = @i_MinutesBack WITH RECOMPILE;
					 
					 UPDATE #bou_allsort SET Pattern = 'executions' WHERE Pattern IS NULL OPTION(RECOMPILE);
					 
					  SELECT TOP 1 @ISH = STUFF((SELECT DISTINCT N',' + CONVERT(NVARCHAR(MAX),b2.SqlHandle, 1) FROM #bou_allsort AS b2 FOR XML PATH(N''), TYPE).value(N'.[1]', N'NVARCHAR(MAX)'), 1, 1, N'') OPTION(RECOMPILE);
					
					INSERT #bou_allsort (	DatabaseName, Cost, QueryText, QueryType, Warnings, QueryPlan, missing_indexes, implicit_conversion_info, cached_execution_parameters, ExecutionCount, ExecutionsPerMinute, ExecutionWeight, 
											TotalCPU, AverageCPU, CPUWeight, TotalDuration, AverageDuration, DurationWeight, TotalReads, AverageReads, 
											ReadWeight, TotalWrites, AverageWrites, WriteWeight, AverageReturnedRows, MinGrantKB, MaxGrantKB, MinUsedGrantKB, 
											MaxUsedGrantKB, AvgMaxMemoryGrant, MinSpills, MaxSpills, TotalSpills, AvgSpills, PlanCreationTime, LastExecutionTime, LastCompletionTime, PlanHandle, SqlHandle, SetOptions, RemovePlanHandleFromCache ) 					 
										  
										  EXEC sp_BlitzCache @ExpertMode = 0, @HideSummary = 1, @Top = @i_Top, @SortOrder = 'memory 
grant', @IgnoreSqlHandles = @ISH, 
                     @DatabaseName = @i_DatabaseName, @SkipAnalysis = @i_SkipAnalysis, @OutputDatabaseName = @i_OutputDatabaseName, @OutputSchemaName = @i_OutputSchemaName, @OutputTableName = @i_OutputTableName, @CheckDateOverride = @i_CheckDateOverride, @MinutesBack = @i_MinutesBack WITH RECOMPILE;
					 					  
										  UPDATE #bou_allsort SET Pattern = 'memory grant' WHERE Pattern IS NULL OPTION(RECOMPILE); SELECT TOP 1 @ISH = STUFF((SELECT DISTINCT N',' + CONVERT(NVARCHAR(MAX),b2.SqlHandle, 1) FROM #bou_allsort AS b2 FOR XML PATH(N''), TYPE).value(N'.[1]', N'NVARCHAR(MAX)'), 1, 1, N'') OPTION(RECOMPILE);
					
					INSERT #bou_allsort (	DatabaseName, Cost, QueryText, QueryType, Warnings, QueryPlan, missing_indexes, implicit_conversion_info, cached_execution_parameters, ExecutionCount, ExecutionsPerMinute, ExecutionWeight, 
											TotalCPU, AverageCPU, CPUWeight, TotalDuration, AverageDuration, DurationWeight, TotalReads, AverageReads, 
											ReadWeight, TotalWrites, AverageWrites, WriteWeight, AverageReturnedRows, MinGrantKB, MaxGrantKB, MinUsedGrantKB, 
											MaxUsedGrantKB, AvgMaxMemoryGrant, MinSpills, MaxSpills, TotalSpills, AvgSpills, PlanCreationTime, LastExecutionTime, LastCompletionTime, PlanHandle, SqlHandle, SetOptions, RemovePlanHandleFromCache ) 					 
										  
										  EXEC sp_BlitzCache @ExpertMode = 0, @HideSummary = 1, @Top = @i_Top, @SortOrder = 'spills', @IgnoreSqlHandles = @ISH, 
                     @DatabaseName = @i_DatabaseName, @SkipAnalysis = @i_SkipAnalysis, @OutputDatabaseName = @i_OutputDatabaseName, @OutputSchemaName = @i_OutputSchemaName, @OutputTableName = @i_OutputTableName, @CheckDateOverride = @i_CheckDateOverride, @MinutesBack = @i_MinutesBack WITH RECOMPILE;
					 					  
										  UPDATE #bou_allsort SET Pattern = 'spills' WHERE Pattern IS NULL OPTION(RECOMPILE); SELECT DatabaseName, Cost, QueryText, QueryType, Warnings, QueryPlan, missing_indexes, implicit_conversion_info, cached_execution_parameters,ExecutionCount, ExecutionsPerMinute, ExecutionWeight, 
										  TotalCPU, AverageCPU, CPUWeight, TotalDuration, AverageDuration, DurationWeight, TotalReads, AverageReads, 
										  ReadWeight, TotalWrites, AverageWrites, WriteWeight, AverageReturnedRows, MinGrantKB, MaxGrantKB, MinUsedGrantKB, 
										  MaxUsedGrantKB, AvgMaxMemoryGrant, MinSpills, MaxSpills, TotalSpills, AvgSpills, PlanCreationTime, LastExecutionTime, LastCompletionTime, PlanHandle, SqlHandle, SetOptions, RemovePlanHandleFromCache, Pattern 
										  FROM #bou_allsort 
										  ORDER BY Id 
										  OPTION(RECOMPILE);  
 
 
 
 
 
 
 
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking for Read intent databases to exclude
Checking plan cache age
Checking for single use plans and plans with many queries
Msg 8115, Level 16, State 8, Procedure sp_BlitzCache, Line 1340 [Batch Start Line 0]
Arithmetic overflow error converting numeric to data type numeric.
The statement has been terminated.
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring readable secondaries databases by default
Ignoring system databases by default
Setting minutes back filter
Applying chosen sort order
Getting spill information for newer versions of SQL
Adding additional info columns for newer versions of SQL
Getting memory grant information for newer versions of SQL
Getting spill information for newer versions of SQL
Adding SQL to collect trigger stats.
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Writing results to table.
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking for Read intent databases to exclude
Checking plan cache age
Checking for single use plans and plans with many queries
Msg 8115, Level 16, State 8, Procedure sp_BlitzCache, Line 1340 [Batch Start Line 0]
Arithmetic overflow error converting numeric to data type numeric.
The statement has been terminated.
Processing SQL Handles To Ignore
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring readable secondaries databases by default
Ignoring system databases by default
Including only chosen SQL Handles
Setting minutes back filter
Applying chosen sort order
Getting spill information for newer versions of SQL
Adding additional info columns for newer versions of SQL
Getting memory grant information for newer versions of SQL
Getting spill information for newer versions of SQL
Adding SQL to collect trigger stats.
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Writing results to table.
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking for Read intent databases to exclude
Checking plan cache age
Checking for single use plans and plans with many queries
Msg 8115, Level 16, State 8, Procedure sp_BlitzCache, Line 1340 [Batch Start Line 0]
Arithmetic overflow error converting numeric to data type numeric.
The statement has been terminated.
Processing SQL Handles To Ignore
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring readable secondaries databases by default
Ignoring system databases by default
Including only chosen SQL Handles
Setting minutes back filter
Applying chosen sort order
Getting spill information for newer versions of SQL
Adding additional info columns for newer versions of SQL
Getting memory grant information for newer versions of SQL
Getting spill information for newer versions of SQL
Adding SQL to collect trigger stats.
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Writing results to table.
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking for Read intent databases to exclude
Checking plan cache age
Checking for single use plans and plans with many queries
Msg 8115, Level 16, State 8, Procedure sp_BlitzCache, Line 1340 [Batch Start Line 0]
Arithmetic overflow error converting numeric to data type numeric.
The statement has been terminated.
Processing SQL Handles To Ignore
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring readable secondaries databases by default
Ignoring system databases by default
Including only chosen SQL Handles
Setting minutes back filter
Applying chosen sort order
Getting spill information for newer versions of SQL
Adding additional info columns for newer versions of SQL
Getting memory grant information for newer versions of SQL
Getting spill information for newer versions of SQL
Adding SQL to collect trigger stats.
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Writing results to table.
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking for Read intent databases to exclude
Checking plan cache age
Checking for single use plans and plans with many queries
Msg 8115, Level 16, State 8, Procedure sp_BlitzCache, Line 1340 [Batch Start Line 0]
Arithmetic overflow error converting numeric to data type numeric.
The statement has been terminated.
Processing SQL Handles To Ignore
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring readable secondaries databases by default
Ignoring system databases by default
Including only chosen SQL Handles
Setting minutes back filter
Applying chosen sort order
Getting spill information for newer versions of SQL
Adding additional info columns for newer versions of SQL
Getting memory grant information for newer versions of SQL
Getting spill information for newer versions of SQL
Adding SQL to collect trigger stats.
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Writing results to table.
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking for Read intent databases to exclude
Checking plan cache age
Checking for single use plans and plans with many queries
Msg 8115, Level 16, State 8, Procedure sp_BlitzCache, Line 1340 [Batch Start Line 0]
Arithmetic overflow error converting numeric to data type numeric.
The statement has been terminated.
Processing SQL Handles To Ignore
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring readable secondaries databases by default
Ignoring system databases by default
Including only chosen SQL Handles
Setting minutes back filter
Applying chosen sort order
Getting spill information for newer versions of SQL
Adding additional info columns for newer versions of SQL
Getting memory grant information for newer versions of SQL
Getting spill information for newer versions of SQL
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Writing results to table.
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking for Read intent databases to exclude
Checking plan cache age
Checking for single use plans and plans with many queries
Msg 8115, Level 16, State 8, Procedure sp_BlitzCache, Line 1340 [Batch Start Line 0]
Arithmetic overflow error converting numeric to data type numeric.
The statement has been terminated.
Processing SQL Handles To Ignore
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring readable secondaries databases by default
Ignoring system databases by default
Including only chosen SQL Handles
Setting minutes back filter
Applying chosen sort order
Getting spill information for newer versions of SQL
Adding additional info columns for newer versions of SQL
Getting memory grant information for newer versions of SQL
Getting spill information for newer versions of SQL
Adding SQL to collect trigger stats.
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Writing results to table.
Writing results to table.
USE [DBA_Internal]; IF EXISTS(SELECT * FROM [DBA_Internal].INFORMATION_SCHEMA.SCHEMATA WHERE QUOTENAME(SCHEMA_NAME) = '[dbo]') AND NOT EXISTS (SELECT * FROM [DBA_Internal].INFORMATION_SCHEMA.TABLES WHERE QUOTENAME(TABLE_SCHEMA) = '[dbo]' AND QUOTENAME(TABLE_NAME) = '[BlitzFirst_Cache]') CREATE TABLE [dbo].[BlitzFirst_Cache](ID bigint NOT NULL IDENTITY(1,1),
          ServerName NVARCHAR(258),
		  CheckDate DATETIMEOFFSET,
          Version NVARCHAR(258),
          QueryType NVARCHAR(258),
          Warnings varchar(max),
          DatabaseName sysname,
          SerialDesiredMemory float,
          SerialRequiredMemory float,
          AverageCPU bigint,
          TotalCPU bigint,
          PercentCPUByType money,
          CPUWeight money,
          AverageDuration bigint,
          TotalDuration bigint,
          DurationWeight money,
          PercentDurationByType money,
          AverageReads bigint,
          TotalReads bigint,
          ReadWeight money,
          PercentReadsByType money,
          AverageWrites bigint,
          TotalWrites bigint,
          WriteWeight money,
          PercentWritesByType money,
          ExecutionCount bigint,
          ExecutionWeight money,
          PercentExecutionsByType money,
          ExecutionsPerMinute money,
          PlanCreationTime datetime,
		  PlanCreationTimeHours AS DATEDIFF(HOUR, PlanCreationTime, SYSDATETIME()),
          LastExecutionTime datetime,
		  LastCompletionTime datetime, 
		  PlanHandle varbinary(64),
		  [Remove Plan Handle From Cache] AS 
			CASE WHEN [PlanHandle] IS NOT NULL 
			THEN 'DBCC FREEPROCCACHE (' + CONVERT(VARCHAR(128), [PlanHandle], 1) + ');'
			ELSE 'N/A' END,
		  SqlHandle varbinary(64),
			[Remove SQL Handle From Cache] AS 
			CASE WHEN [SqlHandle] IS NOT NULL 
			THEN 'DBCC FREEPROCCACHE (' + CONVERT(VARCHAR(128), [SqlHandle], 1) + ');'
			ELSE 'N/A' END,
		  [SQL Handle More Info] AS 
			CASE WHEN [SqlHandle] IS NOT NULL 
			THEN 'EXEC sp_BlitzCache @OnlySqlHandles = ''' + CONVERT(VARCHAR(128), [SqlHandle], 1) + '''; '
			ELSE 'N/A' END,
		  QueryHash binary(8),
		  [Query Hash More Info] AS 
			CASE WHEN [QueryHash] IS NOT NULL 
			THEN 'EXEC sp_BlitzCache @OnlyQueryHashes = ''' + CONVERT(VARCHAR(32), [QueryHash], 1) + '''; '
			ELSE 'N/A' END,
          QueryPlanHash binary(8),
          StatementStartOffset int,
          StatementEndOffset int,
          MinReturnedRows bigint,
          MaxReturnedRows bigint,
          AverageReturnedRows money,
          TotalReturnedRows bigint,
          QueryText nvarchar(max),
          QueryPlan xml,
          NumberOfPlans int,
          NumberOfDistinctPlans int,
		  MinGrantKB BIGINT,
		  MaxGrantKB BIGINT,
		  MinUsedGrantKB BIGINT, 
		  MaxUsedGrantKB BIGINT,
		  PercentMemoryGrantUsed MONEY,
		  AvgMaxMemoryGrant MONEY,
		  MinSpills BIGINT,
		  MaxSpills BIGINT,
		  TotalSpills BIGINT,
		  AvgSpills MONEY,
		  QueryPlanCost FLOAT,
          JoinKey AS ServerName + Cast(CheckDate AS NVARCHAR(50)),
          CONSTRAINT [PK_BlitzFirst_Cache] PRIMARY KEY CLUSTERED(ID ASC))

**Comment by rabryst** [comment]
@BrentOzar it looks like it's the bit after `Checking for single use plans and plans with many queries`, where you have the `DECIMAL(3,2)` cast in a few places. That might need to be slightly larger, say `(4,2)` or possibly even `(5,2)`. The joke is I can't test that theory right now because I don't have any duplicate plans.

**Comment by BrentOzar** [comment]
Ooo, nice! Yeah, I have a dynamic SQL generator I can use to test that out. I'll get on that this weekend.

**Comment by BrentOzar** [comment]
Ooo, not so much: that DECIMAL(3,2) is where we're calculating percentages. It's tough to be over 999%, obviously, heh:

```
SELECT m.duplicate_plan_handles, 
       CONVERT(DECIMAL(3,2), m.duplicate_plan_handles / (1. * NULLIF(t.total_plans, 0))) * 100. AS percent_duplicate,

```

During a live stream, I tried putting tens of thousands of duplicate plans in the cache, and we still couldn't get it to do the overflow even with 35K plans in the cache.

**Comment by BrentOzar** [comment]
Woohoo! Possibly fixed it during a live stream thanks to Santi Swarup Choudhury catching my bad math in Twitch. Note that Emanuele in Twitch thinks we may still need to expand it to more decimal places, but I'll let someone else give that a shot because I couldn't reproduce this.
