### ISSUE TITLE
Exception to tables in the master database

### ISSUE THREAD

**Issue by parlevjo2** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2426]
Hi

I would like to add an exception to tables in the master database. That is table '$ndo$srvproperty'. 
The $ndo$srvproperty is used to store your NAV (Navision) license file. You will not find it in master if you have selected "Per Database License" in the NAV "Per Database License" configuration.

`AND name NOT IN ('CommandLog','$ndo$srvproperty','SqlServerVersions');`

Rgds Johan Parlevliet

**Comment by BrentOzar** [comment]
Sure, sounds good! Go for it - that pull request would be welcomed. Makes sense.
