### ISSUE TITLE
sp_BlitzFirst error when running ExpertMode on Azure SQL DB

### ISSUE THREAD

**Issue by imyourdba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2428]
EXEC sp_BlitzFirst @ExpertMode =1

This gets an error when running against an Azure SQL DB.  I don't believe this happened in past versions.  
Version:  sp_BlitzFirst 2020-05-06 00:00:00.0000000 +00:00

Setting up configuration variables
Msg 40515, Level 15, State 1, Line 19
Reference to database and/or server name in 'msdb.dbo.sysjobs' is not supported in this version of SQL Server.

**Comment by BrentOzar** [comment]
Check the readme on the home page of this repo - none of the scripts have ever been supported on Azure SQL DB.

**Comment by imyourdba** [comment]
And yet it has worked until recently.  Unfortunate that we're half way through 2020 and still no "support" for Azure SQL DB after all these years.

**Comment by SparkyMarkyNZ** [comment]
@imyourdba

Is that you volunteering?

**Comment by BrentOzar** [comment]
@imyourdba yes, I agree that it's unfortunate that we're halfway through 2020 and you still think it's my job to build software for you for free, and that you can't be bothered to contribute to open source projects that help you do your job. Real bummer there. Maybe 2021 will be the year you turn it around.

Then again, maybe not. Cheers.

**Comment by imyourdba** [comment]
I apologize, my point wasn't to attack you personally, just frustrated that we can't use the scripts now.  There are those of us that work for companies that make decisions above our pay grade to move to Azure SQL DB.  We get accustomed to using these great tools on-prem and then once we get to Azure, we can't use them anymore (or as you said, they aren't supported for breaking changes...or at least what we see as breaking as users).  

I work 70-80 hours a week (not for I'm Your DBA unfortunately, lol) to help the my full time job keep up with customer demand.  So if I can ever get any free time I'm happy to look at the project, but assumed that at some point there would be a tipping point of Azure SQL DB adoption that would facilitate a push for adapting the tools. We'll see...maybe 2021 will bring some extra free time (and sleep).

**Comment by BrentOzar** [comment]
@imyourdba I see. So you make money 70-80 hours per week, and you don't give anything back to the community. You just use free scripts from volunteers, then stop in and bark orders about how their scripts need to do more to make money for you.

You might want to step away for a while and think about how you approach volunteers who give you the scripts you rely on to make money for all those hours.

Have a good weekend. I'll be spending time with the folks I love rather than doing the work you're requesting of me. I hope you can find it in your heart to forgive me.

By the way, you're welcome.

**Comment by SparkyMarkyNZ** [comment]
Nicely put.

 

Have a good weekend – ALL of you. 😊

 

Regards,

 

Mark

**Comment by imyourdba** [comment]
Well first of all I said we use them at my full time job, which is just a normal salaried position like everyone else, so my hours are not "paid consulting" like you are alluding.  Second, we pay for your Consultant Toolkit, Constant Care, a Training Subscription and we sign up and pay for pre-con's and training in live sessions with you.  So let's not make it sound like I'm a freeloader that doesn't believe in giving you money for the work you do...that's simply not the case.
