### ISSUE TITLE
Minor issue with SqlServerVersions

### ISSUE THREAD

**Issue by tpbrownec** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2429]
1. You don't mention in your release notes when this has been updated.  Can you let us know?
2. More difficult: SqlServerVersions is not installed as part of Install-All-Scripts.sql.  Can that be added?

**Comment by BrentOzar** [comment]
1. When there are new versions.
2. Sure! You can contribute the code to do that. The build scripts are here:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/Documentation/Development/Merge%20Blitz.ps1

And the contributing guide is here:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

Thanks!

**Comment by tpbrownec** [comment]
Brent:

I'm working on it and almost done, but I ran into this when trying to
publish my branch update.  It appears branch did not get created in Github
itself, only on the desktop.
Sorry, I'm a newbie at using Github for someone else's code....
[image: image.png]

Curtis Browne
Phone: 949.422.3517
curtbrowne@computer.org

**Comment by BrentOzar** [comment]
Thanks for the pull request! Merged into the dev branch, and it'll be in the July release notes along with credit to you. Have a good week!
