### ISSUE TITLE
sp_BlitzFirst - add sys.dm_os_waiting_tasks to wait stats

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#243]
sys.dm_os_wait_stats doesn't include currently waiting tasks because they haven't finished. If we have a long-running query blocking others, there could be hundreds of seconds of lock waits in a 5-second sample, but that won't show up in sp_AskBrent right now because we only look at sys.dm_os_wait_stats - which doesn't update until a query finishes.

The easiest way to do this is to:

- Create a temp table for sys.dm_os_waiting_tasks
- Populate it with two passes like we do with sys.dm_os_wait_stats
- Add the delta to the second-pass results for sys.dm_os_wait_stats. So for example, if there's been 30 seconds of LCK_YOU_UP waits in sys.dm_os_waiting_tasks, I need to find the LCK_YOU_UP wait record for pass #2 of sys.dm_os_wait_stats, and then add the waits there.

That way I don't have to change the results logic. Now, it *will* make cumulative tracking incorrect if you're looking at the delta views written to disk - they'll be artificially higher since they'll include the double-counted waits (from sys.dm_os_waiting_tasks while the user queries run, plus again from sys.dm_os_wait_stats when they finish) so I may need to write the wait stats to disk BEFORE I add them together.

**Comment by BrentOzar** [comment]
If @SinceStartup = 1, don't put , just include all data that's in sys.dm_os_waiting_tasks. Don't bother doing a temp table or a diff. 

If @SinceStartup = 0 or @Seconds <> 0 (same thing), then just subtract @Seconds from sys.dm_os_waiting_tasks.wait_duration_ms. If the result > 0, then add it to the wait stats sample #2.

**Comment by BlitzErik** [comment]
This is included in what is running. Do you still want a separate breakout?

**Comment by BrentOzar** [comment]
Not a separate breakout, but just added to the wait stats totals. If, during the 5-second sample, there's 10 queries that are all waiting on LCK*, then right now in the waits stats section, it looks like there's no waits. sys.dm_os_wait_stats doesn't increment until the wait finishes.

**Comment by BlitzErik** [comment]
Cool! I love this idea, but I sort of hate the idea of double-counting wait stats. After playing with it a little, I think doing something like this might be interesting. This way, we're only getting waiting tasks that are longer than the window we're examining, and we can warn for a) long running transactions and b) their wait types. This DMV is very snap-shotty, so doing a delta on it might be misleading without some filtering.

```
DECLARE @Seconds INT = 30
SELECT  
	owt.session_id,
	owt.wait_type,
        SUM(owt.wait_duration_ms) AS [duration_ms]
FROM    sys.dm_os_waiting_tasks owt
WHERE owt.session_id > 50
AND owt.wait_duration_ms >= @Seconds * 1000
GROUP BY owt.session_id, owt.wait_type
```

![image](https://cloud.githubusercontent.com/assets/11590415/16895133/bf5685de-4b39-11e6-9091-799eb39d5e54.png)

**Comment by BrentOzar** [comment]
Exactly! Then, when adding the number to the totals:

If @Seconds = 0, that means we're checking waits since startup. We'd add the whole wait amount to the totals.

If @Seconds <> 0, then we're only checking waits for a range of time. We would subtract @Seconds from the duration_ms, then add the remainder to the totals.

Say your task has been waiting for a lock for 35 seconds, and @Seconds = 5. We'd only want to add 5 seconds to the lock waits.

**Comment by BlitzErik** [comment]
#387

**Comment by BrentOzar** [comment]
Getting closer! Looks like there's a join bug or something.

Start two windows with this:
BEGIN TRAN
UPDATE dbo.Users SET DisplayName = 'Brent Ozar' WHERE Id = 26837

The first one will succeed, the second one gets blocked. sp_BlitzFirst @ExpertMode = 1 correctly reports 5 seconds of waits.

Now copy/paste that into another window, run it (so you have two blocked queries), and you get 19 seconds of lock waits - should be 10. (2 sessions x 5 seconds each.)

Copy/paste it into yet another window, run it, and you get 80 seconds - should be 15.

**Comment by BlitzErik** [comment]
This was also super obvious/easy. Need to also partition the window function over session_id to subtract @Seconds * 1000 from each instance of the wait rather than the wait as a whole. Excellent catch, boss man.

**Comment by BlitzErik** [comment]
Pasting this here as well for reference:

![image](https://cloud.githubusercontent.com/assets/11590415/16972764/1db2443c-4dfc-11e6-9640-cac4bfd3d171.png)

**Comment by BrentOzar** [comment]
This was fixed in https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/387 - closing.
