### ISSUE TITLE
'Example Calls' section of sp_BlitzQueryStore page missing --  on line for 'Set a duration minimum' comment

### ISSUE THREAD

**Issue by syeats** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2432]
**Version of the script**
its the web page, not the script.
https://www.brentozar.com/first-aid/sp_blitzquerystore/

**What is the current behavior?**
Set a duration minimum

**If the current behavior is a bug, please provide the steps to reproduce.**
self evident looking at page, or copying the text to a query window.

**What is the expected behavior?**
-- Set a duration minimum

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
n/a

**Comment by BrentOzar** [comment]
Sorry about that, fixed!
