### ISSUE TITLE
sp_BlitzWho fix for Azure SQL DB

### ISSUE THREAD

**Issue by imyourdba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2435]
Code in sp_BlitzWho (Version 7.95 - 20200506) that hits 'msdb.dbo.sysjobs' causes it to error when run against an Azure SQL DB.  I have a fix below for this and wanted to socialize it for inclusion since it causes an error in sp_BlitzFirst when using @ExpertMode = 1 against an Azure SQL DB (I know, it's not supported, that's why I'm suggesting the fix).  It may not be the most elegant, but it will work.

**I would add a Platform check to the variables list like such:**
`,@Platform NVARCHAR(8) /* Azure or NonAzure are acceptable */ = (SELECT CASE WHEN @@VERSION LIKE '%Azure%' THEN N'Azure' ELSE N'NonAzure' END AS [Platform])`

**Then at lines 347 & 546, I would change the code from this:**
`			       s.nt_user_name ,
			       program_name = COALESCE((
SELECT REPLACE(program_name,Substring(program_name,30,34),''"''+j.name+''"'') 
FROM msdb.dbo.sysjobs j WHERE Substring(program_name,32,32) = CONVERT(char(32),CAST(j.job_id AS binary(16)),2)
),s.program_name) 
						    '`

**To this:**
`			       s.nt_user_name ,'
		IF @Platform = 'NonAzure'
		BEGIN
		SET @StringToExecute +=
				   N'program_name = COALESCE((
					SELECT REPLACE(program_name,Substring(program_name,30,34),''"''+j.name+''"'') 
					FROM msdb.dbo.sysjobs j WHERE Substring(program_name,32,32) = CONVERT(char(32),CAST(j.job_id AS binary(16)),2)
					),s.program_name)'
		END
		ELSE
		BEGIN
		SET @StringToExecute += N's.program_name'
		END`

[sp_BlitzWho_Azure.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/4777054/sp_BlitzWho_Azure.txt)

**Comment by BrentOzar** [comment]
OK, cool - here's how to contribute code:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

Thanks!

**Comment by BrentOzar** [comment]
Good work! Thanks for contributing. I've merged your pull request. It's in the dev branch now, and it'll be in the July release along with credit for you in the release notes. Welcome to the club!
