### ISSUE TITLE
sp_BlitzLock fails on case sensitive instances

### ISSUE THREAD

**Issue by pnauta** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2440]
**Version of the script**
2.93

**What is the current behavior?**
Script fails with a missing column Database_Name on CS (case sensitive) instances, while for CI (case insensitive) instances no problem is detected

**If the current behavior is a bug, please provide the steps to reproduce.**
Run the script on a CI collation instance

**What is the expected behavior?**
Script runs fine on CS collations.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All, when CS collation is used.

Line 219 Database_Name is used.  All other references to the table use database_name.
line 219 << 							Database_Name NVARCHAR(256),
>> 							database_name NVARCHAR(256),

**Comment by BrentOzar** [comment]
Sorry about that! Fixed in the dev branch, and will be in the July release. Thanks for the bug report!
