### ISSUE TITLE
sp_BlitzLock may benefit from @OutputXMLasNVARCHAR parameter which is available in sp_Blitz

### ISSUE THREAD

**Issue by pnauta** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2442]
**Is your feature request related to a problem? Please describe.**
When including the results in a HTML table, XML messes up the rendering sometimes.  

**Describe the solution you'd like**
Sending XML columns query, object name and deadlock graph as nvarchar would really help

**Describe alternatives you've considered**
Rendering the columns as nvarchar myself using XQuery methods

**Are you ready to build the code for the feature?**
In this case, while the code may already exist, I would rather leave it to the original author who is the master of coding anyway :-)

**Comment by BrentOzar** [comment]
I understand that you'd rather leave it to the authors, but we're kinda busy too. If this is something you'd like, you're welcome to put it in, but otherwise we'd mark this one as closed.

Would you like to contribute the code? If not, I totally understand.

**Comment by BrentOzar** [comment]
I haven't heard back from you, so I'll go ahead and close this. If you change your mind and you want to work on it, hop into Slack as described in the contributing guide and folks can help you get started. Thanks!
