### ISSUE TITLE
sp_ineachdb - Incorrect description text

### ISSUE THREAD

**Issue by LowlyDBA** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2445]
**Version of the script**
`SELECT @Version = '2.96', @VersionDate = '20200602';`

**What is the current behavior?**

Has incorrect text from license c&p: "This script will restore a database from a given file path."

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Should have something like "This script will execute a command against multiple databases."

**Comment by BrentOzar** [comment]
Hahaha, good catch! Thanks! Merged into the dev branch, and will be in the July release along with credit to you in the release notes.
