### ISSUE TITLE
sp_BlitzIndex - Create TSQL column has DROP INDEX script for Disabled index

### ISSUE THREAD

**Issue by defcon84** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2447]
**Version of the script**
sp_BlitzIndex(TM) v7.96 - June 06, 2020: Database [master] as of 2020-06-30 09:43

**What is the current behavior?**
Create TSQL column has DROP INDEX script for a Disabled index. So it now has 2 disabled scripts next to each other.
![Capture](https://user-images.githubusercontent.com/1416066/86098709-c9c27500-bab6-11ea-9a22-df939196a38b.PNG)

**If the current behavior is a bug, please provide the steps to reproduce.**
- create index
- disable index
- run blitzindex for that table

**What is the expected behavior?**
i would like a Create index script

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Tested on SQL Server 14.0.1000.169
Did not work in May release either.

**Comment by BrentOzar** [comment]
Hi. It's always been that way - can you elaborate a little more on why you would want to create a disabled index? You shouldn't need to do that - if you need to enable it again, just rebuild it.

I'm just hesitant to change the behavior of this since it's been the same for so long - if you've got a solid use case, I'm open to it though.

**Comment by defcon84** [comment]
That way I'm able to drop and create the query if I'd like to by copying the 2 statements next to each other, like I sometimes do with the enabled indexes, eg. if I want to test or change something.

And also just to be consistent with enabled indexes:
![image](https://user-images.githubusercontent.com/1416066/86464870-bd495100-bd30-11ea-8379-d0a25245657b.png)
What is the use of having the drop index twice, only difference being one is missing the database name.

It feels wrong to to have a drop in the create column, I'd rather have the create of even the rebuild statement.

**Comment by BrentOzar** [comment]
OK, gotcha. If it's important to you, then sure, you could do the code and submit a pull request. Here's the contributing guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

I'm working on the July release this morning - if you want to get it in today, I can sneak it into the July release. Not a rush though. If you don't want to code it, let me know and I can close the issue. Thanks!

**Comment by BrentOzar** [comment]
Looks good, thanks! I merged it into the dev branch just now. It'll be in the July release along with a credit to you in the release notes. Thanks!

**Comment by defcon84** [comment]
Thanks! My mind is at ease again.
