### ISSUE TITLE
Update README to cover install scripts

### ISSUE THREAD

**Issue by BurtCrowne** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2458]
There is no mention of the 
Install-All-Scripts, Install-Core-Blitz-No-Query-Store, Install-Core-Blitz-With-Query-Store SPs

* What are the use cases for using each of these?
* Should a user install using one of these or install each SP separately?

* Why is sp_BlitzInMemoryOLTP specifically not installed by any of these.  According to the code in Merge Blitz.ps1, it is deliberate.

Can we have the README cover these topics?  I'd write something, but I don't know the answers.

**Comment by BrentOzar** [comment]
Great idea! I've added that in the dev branch. Thanks!
