### ISSUE TITLE
__MACOSX folder included in FirstResponderKit.zip file.

### ISSUE THREAD

**Issue by kevinmartin-es** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2462]
**Is your feature request related to a problem? Please describe.**
No problem. It was just confusing the first time I saw the __MACOSX folder in the FirstResponderKit.zip file. Mac users do not see the hidden folder by Windows users see it.

![screenshot](https://user-images.githubusercontent.com/46450902/86928476-33b3cd80-c0fa-11ea-9951-42e26f55354a.png)

**Describe the solution you'd like**
It looks like there is a solution in stack that will exclude the folder.

["Can be fixed after the fact by zip -d filename.zip __MACOSX/\*" --Chris Johnson](https://stackoverflow.com/a/13665552)

**Comment by BrentOzar** [comment]
Yeah, that's just the fact that I sometimes do the releases on a Mac. I totally hear you, but this wouldn't be something I'd build into my routine - just only so far I can go for this kind of thing. At some point, I'd love to have a fully automated release process, but we're not there yet. Thanks though.
