### ISSUE TITLE
sp_BlitzFirst - Wait stats not returned when @ExpertMode = 1

### ISSUE THREAD

**Issue by RichBenner** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2463]
**Version of the script**
Current released version.

**What is the current behavior?**
When called with @ExpertMode = 1 we do not get wait stats returned any more. This behaviour was altered during the following pull request;

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/commit/625979e76fc6f5d2392b5a22d72fe15e9bd7ebee#diff-552d8a2836417d18a75bac2ab9f8fa82

The modification of line 3964 to remove "@ExpertMode = 0 AND " means we're now hitting that block when @ExpertMode = 1 whereas we want to be hitting the if block after this.

**If the current behavior is a bug, please provide the steps to reproduce.**
Run the current BlitzFirst with @ExpertMode = 1 and you will not get wait stats returned.

This version (just before that pull request) works fine;

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/db25ecbac09466678f06c072ce7bf8bb47af0111/sp_BlitzFirst.sql

**What is the expected behavior?**

Well, it'd be nice if we could see the wait stats returned please.

**Comment by BrentOzar** [comment]
Thanks for the detective work, sir! Merged into the dev branch. I'll do a round of testing when I'm back home tomorrow and then do a release just to get this one out into public hands.
