### ISSUE TITLE
sp_AllNightLog_Setup fails silently if @BackupPath not set

### ISSUE THREAD

**Issue by BurtCrowne** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2474]
**Version of the script**
@Version = '3.96', @VersionDate = '20200712'

**What is the current behavior?**
Output of @help=1 has this snippet in it:
"@BackupPath NVARCHAR(MAX), defaults to = ''D:\Backup''. You 99.99999% will need to change this path to something else. This tells Ola''s job where to put backups." 
The code actually just sets and leaves it at NULL if not specified.
msdbCentral created with no tables, but 22 jobs  are created as expected
Message in output is "@tbl_sql is NULL for some reason".. not helpful to the user
**If the current behavior is a bug, please provide the steps to reproduce.**
Reproduce by omitting @BackupPath value when invoking SP
**What is the expected behavior?**
Check if @BackupPath is NULL, issue Raiserror and exit
**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
No idea if this ever worked correctly

**Comment by BurtCrowne** [comment]
I'll submit a fix shortly

**Comment by BrentOzar** [comment]
OK, great, thanks!

**Comment by BrentOzar** [comment]
Merged into dev, and it'll be in the August release along with credit to you in the release notes. Thanks!
