### ISSUE TITLE
CheckID 178 (snapshot-looking backups have occurred in the last two weeks, indicating that IO may be freezing up.)

### ISSUE THREAD

**Issue by seniuka** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2478]
Hi, 

Currently we have split our backup files into 4 files using Ola Hallengren's scripts and we can backup a 50GB database in under 60 seconds, with compression of course. Could we update the rule to 30 seconds? or 100GB uncompressed? or 50GB compressed? 

Thanks
Adam

**Comment by BrentOzar** [comment]
That isn't snapshot backups. Read the more-info URL carefully.

**Comment by seniuka** [comment]
I get you, I will have to talk to the VM guys to make sure they are not doing LUN snaps at that time. Also if I am backing up to a remote file share that potentially would look similar to LUN snap if there was heavy writes to that remote share.

Thanks for looking at this so quickly.

**Comment by BrentOzar** [comment]
No, backing up to a remote file share has nothing to do with it.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws
