### ISSUE TITLE
sp_blitzcache 'many single-use plans' section showing 172% are single-use plans?

### ISSUE THREAD

**Issue by SimonYeatsEM** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2480]
**Version of the script**
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.

Current version: 7.97 released on Jul 12 2020 12:00AM.

**What is the current behavior?**
gives > 100% (172%) for plan usage ratio, and also the 'Plan Cache Stability' section doesnt total the report percentages to 100% ->

You have 2541 plans in your cache, and 172.00% are single use plans, meaning SQL Server thinks it's seeing a lot of "new" queries and creating plans for them. Forced Parameterization and/or Optimize For Ad Hoc Workloads may fix the issue.To find troublemakers, use: EXEC sp_BlitzCache @SortOrder = 'query hash'; 

Note: further down the list (priority 254), it seems to get this calc closer (none greater than 100) although the percentages reported don't sum to 100% ? ie 17% + 15% + 13%;

Priority	FindingsGroup	Finding	URL	Details
254	Plan Cache Information	Plan Cache Stability	https://www.brentozar.com/archive/2018/07/tsql2sday-how-much-plan-cache-history-do-you-have/	You have 2541 total plans in your cache, with 17.00% plans created in the past 24 hours, 15.00% created in the past 4 hours, and 13.00% created in the past 1 hour. When these percentages are high, it may be a sign of memory pressure or plan cache instability.

**If the current behavior is a bug, please provide the steps to reproduce.**

Run sp_blitzcache on the sql server (2016 Ent SP1)

**What is the expected behavior?**
To get a plan usage ratio below 100% for 'Many single-use plans' section, and the percentage sums totalling 100% for the 'Plan Cache Stability' section.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Microsoft SQL Server 2016 (SP1) (KB3182545) - 13.0.4001.0 (X64)   Oct 28 2016 18:17:30   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor) 

Not sure, presume so.

**Comment by BrentOzar** [comment]
Thanks for the bug report! I've noticed that too, and I'll dig into it this week.

**Comment by BrentOzar** [comment]
Fixed by changing the source DMV from where we pull total number of query plans. I'm not 100% confident this will work, but will try it a few times during next week's training classes and make sure it produces the right results. Thanks for the report, will be in August's release along with crediting you in the release notes.

**Comment by rebambus** [comment]
I'm on version 7.98 released on Aug  8 2020 12:00AM.

And I'm still getting a similar problem for "Many Duplicate Plans"
`You have 13151 plans in your cache, and 103.00% are duplicates with more than 5 entries, meaning similar queries are generating the same plan repeatedly. Forced Parameterization may fix the issue. To find troublemakers, use: EXEC sp_BlitzCache @SortOrder = 'query hash'; `

**Comment by BrentOzar** [comment]
@rebambus for different problems, can you open a new issue? Thanks.

**Comment by rebambus** [comment]
Yep!

**Comment by SimonYeatsEM** [comment]
hi guys, yes, i think the '"Many Duplicate Plans" section may have the same DMV issue that Brent found with the 'many single-use plans'  section - as Brent suggests, probably best to open a new issue for it, thx Simon.
