### ISSUE TITLE
Error Installing the FRK using DBATools command

### ISSUE THREAD

**Issue by RangaSQL** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2485]
**Version of the script**
Version: From the Zip File downloaded on 7-17-20 (sorry, couldn't even install due to an error, so unsure of version)

**What is the current behavior?**
Error Trying to install using the DBATools command:
Install-DbaFirstResponderKit $instance.name -Database master -FORCE
Error:
WARNING: [15:59:16][Install-DbaFirstResponderKit] Couldn't download the First Responder Kit. Download and install manually from https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/archive/master.zip. | The remote server returned an error: (404) Not Found.

**If the current behavior is a bug, please provide the steps to reproduce.**
Install-DbaFirstResponderKit $instance.name -Database master -FORCE

Tried to download a local copy and used the command below:
Install-DbaFirstResponderKit $instance.name -Database master -LocalFile "E:\SQL-Server-First-Responder-Kit-main.zip"
the above command gave tons of output, just weird! Last out is like below:

VERBOSE: Changed database context to 'master'.
SqlInstance  : SQLInstanceName
InstanceName :SQLInstanceName
ComputerName : SQLInstanceName
Name         : sp_Blitz_SQL_Server_2005
Status       : Installed
Database     : master

**What is the expected behavior?**
Should install, fine.
Install-DbaWhoIsActive - works fine

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2016, SP2
Os: windows 2016

**Comment by BrentOzar** [comment]
Hi! For support with DBAtools, head to https://dbatools.io. They have a Github repo and they track issues as well. There's already an issue for this, too:

https://github.com/sqlcollaborative/dbatools/issues/6641
