### ISSUE TITLE
sp_BlitzCache - Unqualified join(s) detected by DataMigrationAssistant

### ISSUE THREAD

**Issue by gabster12** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2486]
**Version of the script**
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.

Answer: SELECT @Version = '7.96', @VersionDate = '20200602';

**What is the current behavior?**
Answer: run Data Migration Assistant to upgrade my sql server instance from 2016 version to 2017, and when checking the results, this was reported:
![image](https://user-images.githubusercontent.com/57949518/87933799-8f853b80-ca96-11ea-87f7-fc98144abe4c.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2016 Enterperise Edition on Windows Server 2016 Standard

**Comment by BrentOzar** [comment]
OK, if you want to track that down, you're welcome to, but this wouldn't be something we'd be interested in tracking down. In my experience, the Data Migration Assistant throws all kinds of false alarms, and sp_BlitzCache has thousands of lines of code, so this wouldn't be something I'd be able to do quickly for free.

If you'd like to do it, here's the contributing guide on how to get started:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/main/CONTRIBUTING.md

I'll close this issue for now, but if you decide you want to work on it, go ahead - when you find the tweaks necessary to get the DMA not to complain, you can use the steps in the contributing guide to turn in the fix. Thanks for the bug report, though.
