### ISSUE TITLE
sp_BlitzWho throws an error when HA readable replica exists

### ISSUE THREAD

**Issue by AdrianB1** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2491]
**Version of the script**
7.97 20200712

**What is the current behavior?**
Executed manually several times, everything is fine, but when ran as a SQL job it failed every time "The target database (xxx) is in an availability group and is currently accessible for connections when the application intent is set to read only. For more information about application intent, see SQL Server Books Online.". 

Removing @OutputTableNameBlitzWho = 'BlitzWho' fixed the job. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Run:
sp_blitzfirst @OutputDatabaseName = 'DBATools',
@OutputSchemaName = 'dbo',
@OutputTableName = 'BlitzFirst',
@OutputTableNameFileStats = 'BlitzFirst_FileStats',
@OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
@OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
@OutputTableNameBlitzCache = 'BlitzCache',
@OutputTableNameBlitzWho = 'BlitzWho'
it will fail sometimes in a HA configuration with read only replicas.

Commenting out @OutputTableNameBlitzWho = 'BlitzWho', it will run fine. I think it fails only when there are open connections to one of the read only replicas, if there is none then it runs fine.

**What is the expected behavior?**
No errors.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2016 CU10 13.0.5492.2 on Windows 2016

**Comment by BrentOzar** [comment]
Thanks for the bug report. That's likely because sys.dm_exec_query_plan appears to have problems querying it when a replica requires read-only intent.

Would you like to adapt the code from #2072 and make it work in sp_BlitzWho? This isn't something that I'd personally tackle - I don't use sp_BlitzWho on readable replicas - but you're welcome to contribute it. If so, check out the contributing guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/main/CONTRIBUTING.md

If you don't want to contribute the code, just let me know and I'll add this to the readme as a known issue.

**Comment by AdrianB1** [comment]
I will spend some time on it early next week and report the progress.

**Comment by BrentOzar** [comment]
It's been a month now - did you still want to work on this, or should I close it? Thanks!

**Comment by AdrianB1** [comment]
I just got back after being away for 2 weeks, I have problems trying to reliably reproduce the problem. I can try to implement the fix blindly, not sure I can confirm it is working in all cases. Is this fine with you?

**Comment by BrentOzar** [comment]
Sure, but just let 'er bake on your side for a couple of weeks doing testing first to make sure you don't continue to have the problem. Thanks!

**Comment by AdrianB1** [comment]
I cannot publish the branch that I have created for the change, I get a message in Git desktop that I don't have write access. I am attaching the file here.
[sp_BlitzWho.sql.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/5153064/sp_BlitzWho.sql.txt)

The fix works when the sp is called manually, when running as a SQL job it still throws an error that seems to be from BlitzFirst or one of the stored procedures called there. I will investigate that separately.

**Comment by AdrianB1** [comment]
This change is also needed: moved the creation of ReadableDBs temp table after calling BlitzWho, otherwise it will throw an error the object does not exist.
Running for the past 8 hours every 15 minutes without any problems.
[sp_BlitzFirst.sql.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/5154796/sp_BlitzFirst.sql.txt)

**Comment by BrentOzar** [comment]
I did a quick code review on the merge - can you read through those comments and respond? Thanks - this URL will show you the changed files in the pull request:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/2567/files

**Comment by BrentOzar** [comment]
THAT IS GENIUS. Totally makes sense, and I appreciate your explanation. Good catch. Merged into the dev branch, and it'll be in the November release with credit to you in the release notes.
