### ISSUE TITLE
sp_Blitz: Implement @SkipChecksServer 

### ISSUE THREAD

**Issue by PierreLetter** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2496]
After you reminding me to read documentation, and going into the code, found out @OutputServerName was working on sp_Blitz. So wanted to use @SkipChecksServer.
Figured it was only a question of putting the parameter in the code with a condition to check if its null or not. Removed the comment stating that it wasn't working at the same time.

To use @OutputServerName or @SkipChecksServer, one simply needs to create a link server to the central repository server (and have proper RPC settings on that linked server). Also, Central server needs to have its storage DB created with the @OutputServerName set (due to the XML bug).

Did the code already and tested it on SQL Server 2019 Enterprise and Standard, CU5.

**Comment by PierreLetter** [comment]
=> https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/2493
Sorry, I am still new at using github and can't seem to find how to link issue to pull request, having done the PR after creating the issue. Please excuse that.

**Comment by BrentOzar** [comment]
Thanks for the code! Works great, merged into dev, will credit you in the August release.
