### ISSUE TITLE
Uninstall doesn't remove new SqlServerVersions table

### ISSUE THREAD

**Issue by rebambus** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2502]
**Version of the script**
@Version = '7.97', @VersionDate = '20200712';

**What is the current behavior?**
Uninstall.sql hasn't been modified in 5 months, so of course it doesn't delete the new SqlServerVersions table.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Run Install-Core-Blitz-No-Query-Store.sql.
2. Run Uninstall.sql
3. See the new table that gets left behind.

**What is the expected behavior?**
Delete that table.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All.

**Comment by BrentOzar** [comment]
OK, cool. If this is important to you, you're welcome to submit a pull request to do this. Here's the contributing guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/main/CONTRIBUTING.md

If you don't want to do it, no problem, I'll close this in a few days. Thanks!

**Comment by rebambus** [comment]
This is basically my first time using Github, so... let me know if I'm doing things wrong. Thanks!

**Comment by BrentOzar** [comment]
Looks good! Thanks for the pull request. Merging this into the dev branch, and it'll be in the August release along with credit to you in the release notes.
