### ISSUE TITLE
sp_Blitz - tempdb missing from checkId 24

### ISSUE THREAD

**Issue by NotTheDBAYoureLookingFor** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2506]
**Version of the script**
7.97

**What is the current behavior?**
Current DBs to check that are located on C drive are IN ( 'master', 'model', 'msdb' ), it also ins't included in the user database Check, so it's completely missing from C drive checks

**If the current behavior is a bug, please provide the steps to reproduce.**
Look at SQL for Check ID 24 & 26

**What is the expected behavior?**
If tempdb is located on the C drive it is flagged in Check 24

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All versions

Happy to do the change in a pull request. It is literally just adding ,'tempdb' to the IN clause

**Comment by BrentOzar** [comment]
Yes, that's as designed - you missed check 25.

* Check 24 looks for the system databases, master, model, and msdb.
* Check 25 looks for tempdb.
* Check 26 looks for user databases.
