### ISSUE TITLE
sp_ineachdb treats distribution databases as user DBs.

### ISSUE THREAD

**Issue by amtwo** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2507]
**Version of the script**
2.97

**What is the current behavior?**
sp_ineachdb treats distribution databases as user DBs. 

**If the current behavior is a bug, please provide the steps to reproduce.**
On a server with a distribution database (or several) this query should include distribution databases in the results, but does not:
```sql
EXEC dbo.sp_ineachdb @command = 'SELECT db_name();', @system_only = 1;
```
On a server with a distribution database (or several) this query should **not** include distribution databases in the results, but does:
```sql
EXEC dbo.sp_ineachdb @command = 'SELECT db_name();', @user_only = 1;
```

**What is the expected behavior?**
SSMS groups distribution dbs under "system" and this procedure should do the same.

`sys.databases.is_distributor` should be used to check for distributors, in addition to the ID-based check for database_id 1,2,3,4

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Verified problem/fix on 2008R2 SP3 and newer

**Comment by BrentOzar** [comment]
Looks good! Merging into the dev branch, will be in the August release along with credit to you in the release notes.
