### ISSUE TITLE
sp_BlitzIndex throws error when tables/indexes are dropped while it runs

### ISSUE THREAD

**Issue by Jorriss** [BrentOzarULTD/SQL-Server-First-Responder-Kit#251]
_Moved from Critical Care Collector repo [Issue 18](https://github.com/BrentOzarULTD/CriticalCareCollector/issues/19) submitted by Angie_

It failed during the collector so I re-ran it in mode=0 and it said the SP existed already. I dropped the SP and recreated with provided script in release 5 zip. Mode=0 succeeded that time. Modes 1 and 2 still failed, even after trying to drop and re-create SP again.

Attaching the error messages for both modes 1 and 2, and the initial log file when it failed to run with collector.

[BI_mode1_error.txt](https://github.com/BrentOzarULTD/PublicTools/files/261395/BI_mode1_error.txt)
[BI_mode2_error.txt](https://github.com/BrentOzarULTD/PublicTools/files/261396/BI_mode2_error.txt)
[CriticalCareCollector.zip](https://github.com/BrentOzarULTD/PublicTools/files/261399/CriticalCareCollector.zip)

**Comment by BrentOzar** [comment]
Going to close this - we're not likely to ever implement it.
