### ISSUE TITLE
sp_BlitzIndex - Failure populating temp tables.

### ISSUE THREAD

**Issue by Zhunya** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2512]
**Version of the script**

Fetched **dev** branch directly from GitHub 2020-08-06 

**What is the current behavior?**

Run `[dbo].[sp_BlitzIndex] @DatabaseName = '<DatabaseName>', @Mode = 2, @Debug = 1`

Get an error - `Failure populating temp tables.`
[Pastebin output](https://pastebin.com/9htMDUtJ)

**If the current behavior is a bug, please provide the steps to reproduce.**

This bug present in latest dev branch, not latest release (https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/releases/tag/20200712)

**What is the expected behavior?**

Get information from `[dbo].[sp_BlitzIndex]`

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Tested on two structurally identical DBs but with different data.

- Microsoft SQL Server 2016 (SP2-CU12) (KB4536648) - 13.0.5698.0 (X64)   Feb 15 2020 01:47:30   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) 
- Microsoft SQL Server 2016 (SP2-CU12) (KB4536648) - 13.0.5698.0 (X64)   Feb 15 2020 01:47:30   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by BrentOzar** [comment]
Perfect, thanks for the bug report!

**Comment by BrentOzar** [comment]
I mitigated this by making the #MissingIndexes processing table have NVARCHAR(MAX) lengths instead of NVARCHAR(4000) for the data types, but there's a chance it'll still occur depending on what we do with those. Can you give the new dev version a shot and let me know if it works for you now? Thanks!

**Comment by Zhunya** [comment]
Error got fixed, thank you, sir.

**Comment by BrentOzar** [comment]
Awesome, thanks for testing it.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws
