### ISSUE TITLE
sp_Blitz: sp_validate logins fails in Amazon RDS

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2526]
**Version of the script**
`@Version = '7.97', @VersionDate = '20200712';`

**What is the current behavior?**
sp_validatelogins (#2387) check fails on Amazon RDS instances.

**If the current behavior is a bug, please provide the steps to reproduce.**
I noticed in a Consultant Toolkit run on an RDS instance that the Health tab didn't populate. While on with the client, I ran Blitz with `@CheckServerInfo = 1` and it failed on that check, with a permissions error:

> Msg 15247, Level 16, State 1, Procedure sp_validatelogins, Line 6 [Batch Start Line 0]
> User does not have permission to perform this action.

**What is the expected behavior?**
Skip this check for Amazon RDS instances. The user is db_owner, which I think it as elevated as it gets for RDS.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All that I know of, though it may only be the result of a lower

**Comment by BrentOzar** [comment]
Doh! Yeah, that was a new check that was added in a community pull request this month. Sorry about that! Fixed in the dev branch.
