### ISSUE TITLE
sp_Blitz needs server name field captured

### ISSUE THREAD

**Issue by Schutzhund3** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2527]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I am testing using dbatools process indicated on https://garrybargsley.com/2020/07/14/sp_blitz-for-all-servers/ and a central management server.  The first thing I noticed is that the server name isn't captured in the results when running against multiple servers.

**Describe alternatives you've considered**
Writing my own procedures in PowerShell.

**Are you ready to build the code for the feature?**
I cannot commit at this time, but will reach out to you if possible.

**Comment by BrentOzar** [comment]
OK, when you're ready to work on the code, leave a message here and we can reopen the issue.

When you're ready, here's the contributing guide:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/main/CONTRIBUTING.md
