### ISSUE TITLE
"Many Duplicate Plans" check returning >100% duplicates

### ISSUE THREAD

**Issue by rebambus** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2532]
**Version of the script**
7.98 released on Aug  8 2020 12:00AM.

**What is the current behavior?**
"Many Duplicate Plans" check returns:
`You have 13151 plans in your cache, and 103.00% are duplicates with more than 5 entries, meaning similar queries are generating the same plan repeatedly. Forced Parameterization may fix the issue. To find troublemakers, use: EXEC sp_BlitzCache @SortOrder = 'query hash'; `

**If the current behavior is a bug, please provide the steps to reproduce.**
`EXEC sp_BlitzCache;`

Digging into the code, these two values don't make sense together:

Total plan count returns 13076 total_plans:
`SELECT COUNT_BIG(*) AS total_plans
FROM   sys.dm_exec_cached_plans AS deqs
WHERE  deqs.cacheobjtype = N'Compiled Plan';`

Duplicate plan handles count returns 13462 duplicate_plan_handles
`SELECT SUM(x.duplicate_plan_handles) AS duplicate_plan_handles
FROM   (   SELECT   COUNT_BIG(DISTINCT qs.plan_handle) AS duplicate_plan_handles
           FROM     sys.dm_exec_query_stats AS qs
                    CROSS APPLY sys.dm_exec_plan_attributes(qs.plan_handle) AS pa
           WHERE    pa.attribute = N'dbid'
           GROUP BY qs.query_hash,
                    pa.value
           HAVING   COUNT_BIG(DISTINCT qs.plan_handle) > 5) AS x;`

**What is the expected behavior?**
Shouldn't be more than 100%, right!?

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
I conflated this with #2480, because I noticed that problem too, but I think that one is fixed.

**Comment by BrentOzar** [comment]
OK, fixed. It's not a great fix - I just said if it's over 100%, report as 100% - but if anybody reading this wants to do the "real" fix, they can take the code from #2480 and do the same approach with this check as well.
