### ISSUE TITLE
sp_BlitzIndex - add separate heap warning for small/unused

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#254]
Right now we only have one warning on heaps, but we need three different priorities:
- Large heaps (over 250MB) that are queried - high priority, need to fix
- Small heaps (under 250MB) that are queried - medium priority, need to fix
- Heaps that aren't queried - low priority, probably need to rename and then drop later

**Comment by BlitzErik** [comment]
#550

**Comment by BlitzErik** [comment]
Merged, closing.
