### ISSUE TITLE
Output timestamp in the first info row when the script was started

### ISSUE THREAD

**Issue by miksh7** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2546]
**Is your feature request related to a problem? Please describe.**
When troubleshooting and sql server conditions are been changing it's important to know when the script was started to correlate later to other metrics. It's very important in BlitzFirst but could be useful in other scripts.

**Describe the solution you'd like**
Output timestamp in the first info row when the script was started

**Describe alternatives you've considered**
write timestamp manually

**Are you ready to build the code for the feature?**
As much as we'd love to build everything that everyone wants for free, we need your help. Open source is built with your help and code. Are you ready to commit time to this project? Have you got existing code you can help contribute to solve the problem?

**Comment by BrentOzar** [comment]
This is what the CheckDate column is for in the output table. If you're troubleshooting over time later, I highly recommend logging to table.
