### ISSUE TITLE
sp_BlitzFirst - CheckID 44 gets blocked when an index operation is in progress

### ISSUE THREAD

**Issue by Adedba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2548]
**Version of the script**
SELECT @Version = '7.97', @VersionDate = '20200712';

**What is the current behavior?**
If an index operation is in progress the statistics updated check gets blocked, if you are logging sp_blitzfirst output to a table then this can leave gaps due to long running collections.

**If the current behavior is a bug, please provide the steps to reproduce.**

**Query window 1:**

Use [StackOverflow2010];

```
/* rebuild a reasonable size index a few times just so we do not miss it during its operation */

	ALTER INDEX [PK_Votes__Id] ON [dbo].[Votes] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON);
	ALTER INDEX [PK_Votes__Id] ON [dbo].[Votes] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON);
	ALTER INDEX [PK_Votes__Id] ON [dbo].[Votes] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON);
	ALTER INDEX [PK_Votes__Id] ON [dbo].[Votes] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON);

```

**Query window 2:**

```
/* Execute sp_BlitzFirst */
EXEC sp_BlitzFirst ;

```

**Query Window 3:** 

```
/* Check for blocking when sp_Blitzfirst reaches CheckID 44 */

EXEC sp_BlitzWho;
```

**What is the expected behavior?**
Ideally for the check to be skipped if there are Index operations in progress and change the output text to reflect that the statistics information could not be obtained as there were Index operations in progress, it would appear that statistics updates do not have the same behavior with locking the dmvs.

We can use With (NOWAIT) against sys.objects and sys.stats for checkid 44 and gracefully handle the error if present using try/catch.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Checked on SQL 2012 and 2016

Ready to work on this.

**Comment by BrentOzar** [comment]
I started working on it because I was in there, and then I got stumped as to how to add a nolock or nowait hint on a cross apply, hahaha: https://dba.stackexchange.com/q/274484/426

Worst case, I have a bad fix - doing SET LOCK_TIMEOUT 1000 at the top of the query. That fixes it in the sense that sp_BlitzFirst finishes, but it also throws an error, and I'd rather not do that if I can avoid it.

**Comment by Adedba** [comment]
Yeah I was doing some testing locally and came across the same issue with the cross apply, I was thinking what we could do is:

If you enter the code block for CheckID 44 (you have less than 20 user databases) then set lock timeout = 0

Inside the foreachdb we wrap the code in a try catch and if we get an error 1222 we can handle this and any other error gracefully per database and insert into the temp table with the relevant message

Back outside again after the foreach we set timeout back to -1 

Bit mucky but I think it will get the job done.

**Comment by BrentOzar** [comment]
Yeah, agreed.

**Comment by BrentOzar** [comment]
Update: answer found at DBA.se, and you can't use isolation level hints on table valued functions: https://dba.stackexchange.com/questions/71174/use-nolock-hint-when-calling-table-valued-function (sigh)

So I checked in the fix I had so far, which at least minimizes the blocking and throws an error. You can keep working on it with a try/catch if you want. I'm fine either way - I don't mind shipping this to at least get past the hurdle.

**Comment by Adedba** [comment]
Ok kool, just committed what I had in case you wanted to give it a trial and see you feel most comfortable with :)

Sample output of the how to stop it xml clickable with repro:
![image](https://user-images.githubusercontent.com/33764798/91458265-34a4e800-e87d-11ea-886a-53383b6764e3.png)

**Comment by BrentOzar** [comment]
Very nice! Can you do a pull request for that and I'll get it into this month's release? I tried doing one and it said it couldn't be automatically merged. (sigh, Github)

**Comment by Adedba** [comment]
Sure no problem! yeah looks like I made the commit after yours then didn't refresh my branch from Dev.

**Comment by BrentOzar** [comment]
Thanks for the pull request! Merged into the dev branch, will be in the September release with credit to you in the release notes.
