### ISSUE TITLE
BlitzIndex will suggest an index name that is too long for SQL to handle

### ISSUE THREAD

**Issue by gdoddsy** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2552]
**Version of the script**
Yet to be released September edition

**What is the current behavior?**
From bug #2533:
BlitzIndex will suggest an index name that is too long for SQL to handle. You get an error:

The identifier that starts with 'Reputation_ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ15_CreationDa' is too long. Maximum length is 128.

**What is the expected behavior?**
I don't know. Happy to close this issue as it's just too hard to come up with what it should do instead? We could truncate it easily enough to 128 characters, but that might just cause it's own problems?

I'm not complaining about the current behavior, it's just something I noted when fixing #2533. If nobody wants this fixed then let's just close it and leave it up to the user to rename their index to something sane.

I'm happy to fix this if you have a suggested fix.

**Comment by BrentOzar** [comment]
Capped index lengths at 128 characters. Good call.
