### ISSUE TITLE
sp_blitzindex - show sys.tables lock_escalation_desc

### ISSUE THREAD

**Issue by SAinCA55** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2553]
When sp_blitzindex reports Lock Escalation Attempts, that's useful information.  If we decide, having assessed the impact and resource needs, to DISABLE Lock Escalation, _in place of_ the reports of attempts/actual escalations, perhaps show "(Lock Escalation DISABLE)"

**Comment by BrentOzar** [comment]
Sure, did you want to code that?

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by SAinCA55** [comment]
Knew that would be the response!

I am SO limited on Git that I took the latest proc from a freshly downloaded First Responder Kit zip file and edited it, keeping the style as close to what it was as I could.  Original file used, and file modified are attached, if that's any use.....  I bumped the version# and date, just in case, in the modified file.

Synopsis:

  *   Line 415 - Added column:
              lock_escalation_desc nvarchar(60) NULL, to #IndexSanitySize
  *   Lines 453 - 456 - Removed the "." then added the new conditional string code:
                    total_index_lock_promotion_attempt_count = 0 THEN N'0 lock waits'
                    + CASE WHEN lock_escalation_desc = N'DISABLE' THEN N'; Lock escalation DISABLE.'
                      ELSE N'.'
                      END
  *
Line 492 - Removed, as it looks ugly when followed by the "DISABLE" string:
+ N'.'
  *
Lines 495 - 498 - Appended to the existing <END>, and added:
                    <END>  +
                    CASE WHEN lock_escalation_desc = N'DISABLE' THEN
                        N'; Lock escalation DISABLE.'
                    ELSE N'.'
                    END
  *
Line 2174 - Inserted new column into the list:
INSERT    #IndexSanitySize ( [index_sanity_id], [database_id], [schema_name], [lock_escalation_desc], partition_count, total_rows, total_reserved_MB,
  *
Line 2183 - Appended the additional column, before any aggregated columns:
        SELECT  index_sanity_id, ipp.database_id, ipp.schema_name, le.lock_escalation_desc,
  *
Lines 2222 - 2226 - New OUTER APPLY and augmented the GROUP BY:
        OUTER APPLY (SELECT st.lock_escalation_desc
                     FROM sys.tables st
                     WHERE st.object_id= ipp.object_id
                         AND ipp.index_id < 2 ) le
        GROUP BY index_sanity_id, ipp.database_id, ipp.schema_name, le.lock_escalation_desc


Hope this is adequate!  If I'm totally off, then apologies in advance - it looks good on my end 😊 (he said, cheerfully).

Regards,

Stephen L. Anslow
________________________________

**Comment by SAinCA55** [comment]
In case the files didn't make it with the email above...
[sp_blitzindex_LockEscalation.zip](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/5144456/sp_blitzindex_LockEscalation.zip)

**Comment by BrentOzar** [comment]
Ooof. Sorry, bad news here: you're working from an outdated version of sp_BlitzIndex. There are more changes in the development branch that you haven't incorporated. I started trying to work through them, but there are so many that I gotta cut bait here.

If you want to contribute to the project, you're totally welcome to do it with Github - but I do need you to do it with Github, or else it's not fair to me and the other project volunteers. By working with Github, you'll be able to develop your code simultaneously with other people who are also contributing - without requiring manual labor on their part.

Here's how to get started: https://sqldbawithabeard.com/2019/11/29/how-to-fork-a-github-repository-and-contribute-to-an-open-source-project/

If you don't want to do it in Github, I do totally understand - it's more work for you, but less work for the project overall - let me know either way. Thanks!

**Comment by SAinCA55** [comment]
Went to that link.  Fork is as-illustrated.  CLONE is not.  NO " Clone or Download" button...  Tutorials are great - when they don't keep up with accurate illustrations, not so much for those taking first steps in Git.


Thankfully, GitHub DESKTOP is clear enough to parallel the instructions, although I may have prematurely "Published" my branch!

Testing, using the sp_blitzindex EXECs under the Documentation folder is underway on about 25 databases - running all scripts, with just the one DB that has a partitioned table.

Fingers crossed.

Do ping if I'm off the beaten track!

Regards,

Stephen
[cid:a8bb4cc0-4364-44c5-9381-fbf02100851a]
________________________________

**Comment by SAinCA55** [comment]
Well, as best I know to use Git in-house, where the workflow is Clone, Pull, Change, Commit, Pull, Push, (using Tortoise-Git) I pushed the changes in my Fork/Branch up to GitHub.  When I show the original https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit page, I see this:

[cid:3d6065d3-e17e-468f-97ee-7a32876b78e8]

My commit comment:

When the Clustered rowstore or Heap has Lock Escalation set to DISABLE, the "Lock Waits" column when NOT executed using @mode = 2, contains additional text, e.g., "0 lock waits; Lock escalation DISABLE.".  Mode-2 was not included because it would likely be a breaking change for those capturing the results to a table.

I ran the code on SQL 2014 Standard and SQL 2017 Enterprise, as these are the lowest and highest versions to which I have access.  sp_blitzindex was added to both master and one of our user databases to ensure that anyone using a user DB context or master context will get the same results.

As mentioned, I ran the _TestBed.sql sp_blitzindex EXECs for all 4 modes - no issues.  Table-specific EXECs also tested on Clustered and Heap, with and without DISABLE set.

I sincerely hope this is now in a good state in GitHub for anyone to hammer on!

Where I've gone wrong will be a learning experience, should that be the end-case.

Sincerely

Stephen

________________________________

**Comment by BrentOzar** [comment]
There's no attachment, unfortunately.

You're really close: go to your repo:

https://github.com/SAinCA55/SQL-Server-First-Responder-Kit/tree/LockEscalationDISABLE

And at the top of the screen, you'll see a "Pull request" icon:

<img width="918" alt="Screen Shot 2020-09-02 at 3 46 30 AM" src="https://user-images.githubusercontent.com/245462/91972014-ec4b5700-ecce-11ea-9294-a2872a6280ed.png">

Click there, and follow the instructions. Thanks!

**Comment by SAinCA55** [comment]
MAN I'm glad you're patient!  Pull request created.  No conflicts.  Can auto-merge.

Do I simply hit that "Close pull request" button arrowed in the snapshot?  (Obviously CLUELESS re this part of Git - we don't fork, and each Branch is its own local repo, so my Git is a ton different from what now confronts me...)

[cid:6a1888af-c8f6-4e0b-a490-3a9c7fddab13]
________________________________

**Comment by BrentOzar** [comment]
Looks great! Thanks for the pull request. Merged into the dev branch, will be in the September release along with credit to you in the release notes.

I also really like how you did this, adding the column to the temp table and not modifying the output tables. Good job!
