### ISSUE TITLE
sp_BlitzCache new error on readable replica

### ISSUE THREAD

**Issue by AdrianB1** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2556]
**Version of the script**
ver 7.98/20200808

**What is the current behavior?**
Executing manually on a secondary readable in debug mode an error appears.
[...]
Collecting execution plan information.
Msg 978, Level 14, State 1, Line 5
The target database ('userdatabasename') is in an availability group and is currently accessible for connections when the application intent is set to read only. For more information about application intent, see SQL Server Books Online.

**If the current behavior is a bug, please provide the steps to reproduce.**
USE [DBATools]
GO
DECLARE	@return_value int,
		@Version varchar(30),
		@VersionDate datetime
EXEC	@return_value = [dbo].[sp_BlitzCache]
		@Debug = 1,
		@Version = @Version OUTPUT,
		@VersionDate = @VersionDate OUTPUT
SELECT	@Version as N'@Version',
		@VersionDate as N'@VersionDate'
SELECT	'Return Value' = @return_value
GO

**What is the expected behavior?**
No errors.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Windows 2016, SQL 2016 SP2 CU10 (13.0.5492.2) Enterprise

I found this by accident trying to fix sp_BlitzWho on readable replica; I got an error there and I tried to see how it is working here. If @Adedba is not interested to fix this, I will try to find time for it late this month (September 2020).

**Comment by BrentOzar** [comment]
Ok, let's not volunteer someone else to do coding, okay? If you want to fix it, you're totally welcome to - but please don't page other people by name and assign them bugs, hahaha. This project is composed of volunteers. Thanks, and I look forward to your pull request.

**Comment by AdrianB1** [comment]
He did the original work on #2072, I thought he is interested to know there are still problems; I would be. Sorry if this was inappropriate.

**Comment by BrentOzar** [comment]
Did you want to do the work on this one? If not I'm going to close it - I don't have AGs where I would specify read-only intent where I can test this kind of thing. Thanks!

**Comment by BrentOzar** [comment]
I haven't heard back from you, so I'll go ahead and close this. If you change your mind and want to work on it, leave a note here and I can reopen it. Thanks!
