### ISSUE TITLE
sp_Blitz - Improve drive space reporting

### ISSUE THREAD

**Issue by PierreLetter** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2557]
**Is your feature request related to a problem? Please describe.**
Right now, drive space only reports total free space. I feel it lacks total drive space, drive name and usage ratio. Adding the volume name can also help people like myself who have multiples drives on different servers.

**Describe the solution you'd like**
Using sys.dm_os_volume_stats, will add the extra information on all drives that have SQL Server files on them. For those who don't, will just keep the current information provided by xp_fixeddrives.

**Describe alternatives you've considered**
Considered using powershell but some people might not be fond of it and this will suit my needs without changing too much the existing mechanism.

**Are you ready to build the code for the feature?**
Yes, will implement this for the octobre release.

**Comment by BrentOzar** [comment]
OK, just make sure it works (or skips, without throwing error messages) on SQL Server 2008 & newer. Thanks!

**Comment by BrentOzar** [comment]
Ooo - thanks for the pull request, but this uses an undocumented, unsupported extended stored procedure. I'm kinda not okay with introducing that into sp_Blitz. If you want to take another shot at it using only documented, supported tools, go for it, but otherwise we need to hold off.

**Comment by PierreLetter** [comment]
Hi. Totally fine with that decision but... are you sure?
I found both in the documentation:
https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-volume-stats-transact-sql?view=sql-server-ver15
https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-master-files-transact-sql?view=sql-server-ver15
However xp_fixeddrives which is currently in sp_blitz seems undocumented.

**Comment by BrentOzar** [comment]
Right, we're just not adding any new undocumented/unsupported commands.

**Comment by BrentOzar** [comment]
Updating - I had the wrong answer there, sorry! I should have pointed you to "sys.dm_os_volume_stats" which is new in 2008R2 SP1. If you want to use that, that's fine, but it needs to be inside dynamic SQL to checks to see if that DMV is available first, then gracefully skips, without losing any existing functionality on 2008.

**Comment by BrentOzar** [comment]
Worked on this during the live stream, and the first bug I noticed was that the free size & total size were shown as the same. I'll go ahead and merge this pull request anyway, and work on it in my own branch. Thanks for the pull request, will be in the September release with credit to you in the release notes.
