### ISSUE TITLE
Install-Core-Blitz-No-Query-Store errors in the list of SP and CU

### ISSUE THREAD

**Issue by SQLJAN** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2560]
**Version of the script**
Install-Core-Blitz-No-Query-Store
@Version = '7.98', @VersionDate = '20200808'

**What is the current behavior?**
I found some errors in the list of SP and CU
More then one CU have the same minerVersionNumber
13, 5426, 'SP2 CU10'
13, 5426, 'SP2 CU9'
13, 5426, 'SP2 CU8'

13, 5492, 'SP2 CU11'
13, 5492, 'SP2 CU10'

Duplicate entries
14, 3238, 'RTM CU17'

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

**Comment by BrentOzar** [comment]
Great, thanks for the heads up! Fixed in the dev branch, and will be in the September release.
