### ISSUE TITLE
sp_Blitz only shows SQL Memory Dumps if there are 5 or more instances in sys.dm_server_memory_dumps

### ISSUE THREAD

**Issue by gbargsley** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2564]
**Version of the script**
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.
@Version = '7.98', @VersionDate = '20200808';

**What is the current behavior?**
Only shows checkID 171 for SQL memory dump check if 5 dumps or more exist in the sys.dm_server_memory_dumps table.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I would expect this to return as a result with 1 or more dumps.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
OS - Windows 10
SQL - 2017 (14.0.1000.169)

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, merged into dev branch, will be in the September release with credit to you in the release notes.
