### ISSUE TITLE
sp_Blitz Report advanced drive size even with >100 files

### ISSUE THREAD

**Issue by PierreLetter** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2569]
Related to #2557 
The 100 files limitation could be reached quickly with data warehousing, especially with partitions in archive filegroups over multiple databases.

As Adedba pointed out on stream, the cross apply is a risk so I swapped out
`sys.master_files`
for
```
SELECT TOP 1 WITH TIES 
database_id
,file_id
,SUBSTRING(physical_name,1,1) AS Drive
FROM sys.master_files
ORDER BY ROW_NUMBER() OVER(PARTITION BY SUBSTRING(physical_name,1,1) ORDER BY database_id)
```

This will only return one file per drive, which shouldn't go over 26.

**Comment by BrentOzar** [comment]
That doesn't work in SQL Server 2008, does it? Just did a quick Google to check: https://stackoverflow.com/questions/27503275/over-partition-by-giving-error-in-sql-server-2008

**Comment by PierreLetter** [comment]
Let me try it again tonight on my home SQL Server 2008 VM.
I had a doubt with the "WITH TIES" in 2008. Can't remember if I tested the whole thing or just the first part of the query.

**Comment by PierreLetter** [comment]
Forget the previous comment, the code won't run on 2008 as its in the
`IF EXISTS (SELECT * FROM sys.all_objects WHERE name = 'dm_os_volume_stats')`
That's why I didn't get an error.

Need to test on 2008 R2 though then. Only tested on 2008, 2016 and 2019.

**Comment by PierreLetter** [comment]
![image](https://user-images.githubusercontent.com/50179739/92801849-45de1080-f3b6-11ea-8de8-6688c86b63c8.png)

👍

**Comment by BrentOzar** [comment]
Looks good! Thanks, merged into the dev branch, will be in the September release with credit to you in the release notes.
