### ISSUE TITLE
database failed to process. XML parsing: line 1, character 4000, unexpected end of input

### ISSUE THREAD

**Issue by naruto3650** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2572]
**Version of the script**
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.
Starting run. sp_BlitzIndex(TM) v7.98 - August 08, 2020
Create temp tables.
Adding UQ index on #IndexSanity (database_id, object_id, index_id)
Number of databases to examine: 2
Checking partition counts to exclude databases with over 100 partitions
Starting loop through databases

**What is the current behavior?**
It gives error 
**If the current behavior is a bug, please provide the steps to reproduce.**
it gives error database failed to process. XML parsing: line 1, character 4000, unexpected end of input but the previous version don't have this error
**What is the expected behavior?**
show the blitzindex result
**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Microsoft SQL Server 2016 (SP2-CU11-GDR) (KB4535706) - 13.0.5622.0 (X64)   Dec 15 2019 08:03:11   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2012 R2 Datacenter 6.3 <X64> (Build 9600: ) (Hypervisor) 

yes it is running from the feb 2020 version of blitzindex but when i update to august 2020 it is not working.
![sp_blitzindex error](https://user-images.githubusercontent.com/37581077/92677761-177d1880-f357-11ea-93d4-6d79b6d062e3.JPG)

**Comment by BrentOzar** [comment]
Can you try the current dev branch? This was reported a while back and was fixed: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzIndex.sql

**Comment by paul-logicmelon** [comment]
@BrentOzar I also experienced this error, so tried the dev branch, and I am happy to report that it is working again. Thanks for the update.

Microsoft SQL Server 2017 (RTM-CU21) (KB4557397) - 14.0.3335.7 (X64)   Jun 12 2020 20:39:00   Copyright (C) 2017 Microsoft Corporation  Web Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)

**Comment by naruto3650** [comment]
> Can you try the current dev branch? This was reported a while back and was fixed: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzIndex.sql

Hi @BrentOzar I have tried the dev branch you provided and it work now without errors.
Yey!!!
