### ISSUE TITLE
[Enhancement] SqlServerVersions Extended Properties

### ISSUE THREAD

**Issue by LowlyDBA** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2574]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add extended properties to the table and columns so that it is more self-documenting. I'm probably in the minority for using extended properties, but am trying to use them more in conjunction with my auto-generated documentation utility [sp_doc](https://github.com/LowlyDBA/ExpressSQL/blob/master/docs/sp_doc.md). No downsides to having the EP added as far as I can tell. 

**Are you ready to build the code for the feature?**
Yup, happy to make the PR.

**Comment by BrentOzar** [comment]
Sure, sounds good. Just make sure it can be run repeatedly without errors, works on case-sensitive servers, on 2008+, etc. Looking forward to the PR - thanks!

**Comment by BrentOzar** [comment]
Looks good, thanks for the pull request. Merged into the dev branch, and will be in the September release with credit to you in the release notes.
