### ISSUE TITLE
sp_BlitzIndex: include columnstore dictionary sizes in index size

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2585]
**Is your feature request related to a problem? Please describe.**
When comparing the rowstore & columnstore versions of a table, the columnstore version looks smaller than it is because it doesn't include the dictionaries, which can be kinda large on text-type tables.

**Describe the solution you'd like**
In the "Size" text column in the table-level and database-level outputs, include the dictionary size on disk separately. 

Here's how Mode 2 output now looks. I dragged the size column over to the left - normally it's way off to the right.
<img width="699" alt="Screen Shot 2020-09-15 at 7 58 53 AM" src="https://user-images.githubusercontent.com/245462/93227580-5fba8300-f729-11ea-9b0c-06787f34566f.png">

It's now in the dev branch, and if you find problems with it, leave a note here. Please include:
* Your SQL Server version number
* Screenshots
* If you get an error, run it again with @Debug = 1, go into the Messages tab, copy/paste the entire output of the Messages tab, and include it here in your note or attach it as a file

Known bugs as of Tuesday, Sept 15:
* In-memory OLTP indexes don't show sizes - because SQL Server doesn't report them in the usual DMVs. Unless someone else codes this, I won't be fixing this for the October release. (Nothing against in-memory OLTP, I just don't use it.)

**Comment by BrentOzar** [comment]
Merged into dev branch, putting on social media to get some initial testing before the October release.

**Comment by Xyaran** [comment]
Hi,

I'm trying this version of sp_blitzIndex to get information about my columnstore index (clustered and partitioned).

I ran the following command: 

- sp_blitzIndex @TableName = 'T_FACT_STEP_RUN'
- sp_blitzIndex @TableName = 'T_FACT_STEP_RUN', @SkipPartitions=0

I don't see any information about my columnstore index.

**SQL Version:** Microsoft SQL Server 2017 (RTM-CU21) (KB4557397) - 14.0.3335.7 (X64) 	Jun 12 2020 20:39:00 	Copyright (C) 2017 Microsoft Corporation	Enterprise Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: )

![sp_blitzIndex 2584](https://user-images.githubusercontent.com/1643121/93239375-af607500-f750-11ea-9b6b-77de02df295b.png)

**Comment by BrentOzar** [comment]
Yeah, due to the number of partitions, check the Messages tab of the output. Most likely you didn't pass in the parameters required to run a large number of partitions.

**Comment by Xyaran** [comment]
Sorry, I thought I did pull the latest version of sp_blitz Dev Branch, looks like I didn't get the right version.
I grabbed it from the raw link you posted and I can now see CS index info on non partitioned tables.

On partitioned tables, I get the following error:

@TableName specified, giving detail only on that table.
Visualizing columnstore index contents.
Failure analyzing temp tables.
Msg 50000, Level 15, State 1, Procedure sp_blitzIndex, Line 5417
The number of elements in the select list exceeds the maximum allowed number of 4096 elements.

I tried with @bringThePain=1 and @skipPartitions=0 and I always get this error.

**Comment by BrentOzar** [comment]
@Xyaran interesting! How many columns does your table have? Any way you can send me the messages as described above: If you get an error, run it again with @debug = 1, go into the Messages tab, copy/paste the entire output of the Messages tab, and include it here in your note or attach it as a file

**Comment by Xyaran** [comment]
My table has 13 columns, might be the unlucky number ;)

I attached the result of the execution with @debug=1.

[sp_blitzIndex 2586 debug.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/5227010/sp_blitzIndex.2586.debug.txt)

**Comment by BrentOzar** [comment]
Gotcha - I think that's an earlier version of the proc. Can you get the one that's in there right now? Thanks!

**Comment by Xyaran** [comment]
When I look at the Dev Branch, I see this:
![image](https://user-images.githubusercontent.com/1643121/93262896-f7908f00-f772-11ea-86e6-94fbc28159d0.png)

This is the version I have and I still get the same error.
The last change I see is this one:
![image](https://user-images.githubusercontent.com/1643121/93263122-4fc79100-f773-11ea-850f-c7716bd815a9.png)

Note that @VersionDate = '20200913'
Please let me know if this is not the correct file to get.

**Comment by BrentOzar** [comment]
Ah, okay, sorry about that mixup! I wasn't paying quite enough attention to what you were running - the table-level details is a different feature, issue #2584. Give the current dev branch a shot now. Thanks!
