### ISSUE TITLE
sp_BlitzFirst: When running on "ExpertMode=1", should not sp_BlitzWho inside sp_BlitzFirst run as "ExpertMode=1" too.

### ISSUE THREAD

**Issue by CarlosBenito** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2594]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you ready to build the code for the feature?**
As much as we'd love to build everything that everyone wants for free, we need your help. Open source is built with your help and code. Are you ready to commit time to this project? Have you got existing code you can help contribute to solve the problem?

**Comment by BrentOzar** [comment]
Thanks for the feature request. However, you need to actually *fill out the form* above. I'm going to close this, and you can open it again, next time filling out the form with the full text, including your ability to code the feature you'd like to add. Thanks!
