### ISSUE TITLE
sp_BlitzQueryStore doesn't change database context on Azure Managed Instance

### ISSUE THREAD

**Issue by coltengoll** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2597]
**Version of the script**
3.99

**What is the current behavior?**
The QueryStore data is queried for the database the stored procedure lives in, regardless if the @DatabaseName parameter is suplied.

The messages written out even specify the database name that procedure lives in.

**If the current behavior is a bug, please provide the steps to reproduce.**
Create two databases on an Azure managed instance.  Install the stored procedure on database1.  Execute stored procedure with @DatabaseName = 'database2'.

**What is the expected behavior?**
The results would be for the database specified within the parameter, regardless of where the procedure lives.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server version it does not work on is Microsoft SQL Azure (RTM) - 12.0.2000.8   Sep 11 2020 22:32:15   Copyright (C) 2019 Microsoft Corporation .

I verified the exact same procedure works on an on-premise 2016 SP2-CU4 server.

**Comment by BrentOzar** [comment]
Hi. Check the read me in the root of this repo for what's supported - sadly, we don't fully support Azure SQL DB, Managed Instances, etc. If you'd like to make the script changes necessary to get it to work, you're absolutely welcome to, but this wouldn't be something that other folks will pick up and run with.

If you decide you want to pick this up and run with it, just leave a note here and I can assign the issue to you and reopen it. Thanks!
