### ISSUE TITLE
sp_DatabaseRestore tries to change the database owner before the database is recovered

### ISSUE THREAD

**Issue by gdoddsy** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2598]
**Version of the script**
7.99

**What is the current behavior?**
When you run sp_DatabaseRestore with @RunRecovery = 0, and @DatabaseOwner = 'some owner' then you get the error Database '%database%' cannot be opened. It is in the middle of a restore.

**If the current behavior is a bug, please provide the steps to reproduce.**
EXEC sp_DatabaseRestore @Database = N'Samples'									
			,@MoveDataDrive = N'f:\samples\'
			,@MoveLogDrive = N'f:\samples\'
			,@BackupPathFull = N'c:\temp\copy to F drive\Backup\Full\Samples'								
			,@RunRecovery = 0										
			,@MoveFiles = 1
			,@DatabaseOwner = 'sa'

**What is the expected behavior?**
No error will happen, the database owner will not  be updated. Maybe add a message to make that clear in the output

**Comment by BrentOzar** [comment]
Looks good! Thanks for the pull request. Merged into the dev branch, and will be in the October release with credit to you in the release notes.
