### ISSUE TITLE
sp_DatabaseRestore fails to apply @StopAt parameter for full backups

### ISSUE THREAD

**Issue by sergdess** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2600]
**Version of the script**
7.99

**What is the current behavior?**
Whatever value you put into `@StopAt` you always use the last full backup as a base. However, the code implies filtering full backup list up to `@StopAt` point in time and it should be possible to restore the full backup which is previous to the last full backup.

**If the current behavior is a bug, please provide the steps to reproduce.**
There is no mention of `@StopAt` influence on the full backup list so I assume this is a bug. Consider the following full backups:
```sql
/*
my_server_mydb_FULL_20200830_000000.bak
my_server_mydb_FULL_20200906_000000.bak
my_server_mydb_FULL_20200913_000000.bak
my_server_mydb_FULL_20200918_000000.bak
*/
EXEC dbo.sp_DatabaseRestore 
	@Database = 'mydb'
	,@BackupPathFull = '\\my_storage\my_server\mydb\FULL\'
	,@RunRecovery = 1
	,@StopAt = '20200911000000'
	,@Debug = 1
	,@Execute = 'N'
```
It doesn't matter what you state in `@StopAt` you will always get a restore script based on the latest full backup (my_server_mydb_FULL_20200918_000000.bak)

**What is the expected behavior?**
To restore the latest full backup which happens before or including `@StopAt` point in time (my_server_mydb_FULL_20200906_000000.bak as in our example)

**Proposed solution**
Truncate backup file list as we do it later in the script for logs. To add the following code:
```sql
	IF @StopAt IS NOT NULL
	BEGIN
		DELETE
		FROM @FileList
		WHERE BackupFile LIKE N'%.bak'
			AND
			BackupFile LIKE N'%' + @Database + N'%'
			AND
			(REPLACE( RIGHT( REPLACE( BackupFile, RIGHT( BackupFile, PATINDEX( '%_[0-9][0-9]%', REVERSE( BackupFile ) ) ), '' ), 16 ), '_', '' ) > @StopAt);
	END
```
just before 
```sql
...
    -- Find latest full backup 
    SELECT @LastFullBackup = MAX(BackupFile)
    FROM @FileList
    WHERE BackupFile LIKE N'%.bak'
        AND
        BackupFile LIKE N'%' + @Database + N'%'
	    AND
	    (@StopAt IS NULL OR REPLACE( RIGHT( REPLACE( @LastFullBackup, RIGHT( @LastFullBackup, PATINDEX( '%_[0-9][0-9]%', REVERSE( @LastFullBackup ) ) ), '' ), 16 ), '_', '' ) <= @StopAt);
```

The root cause is an issue with `@LastFullBackup` variable which is always NULL by this time, so we can fix it with:
```sql
(@StopAt IS NULL OR REPLACE( RIGHT( REPLACE( BackupFile, RIGHT(*BackupFile, PATINDEX( '%_[0-9][0-9]%', REVERSE( BackupFile ) ) ), '' ), 16 ), '_', '' ) <= @StopAt);
```
and the same thing several times later in the code but I guess truncation is the simplest solution.

**Comment by BrentOzar** [comment]
Sure, if you want to make those changes, that sounds like a good pull request. I haven't actually used this proc myself. Thanks!

**Comment by BrentOzar** [comment]
@sergdess did you want to take a shot at this, or should I close it? I'll close it if I don't hear back from you in a couple of days. Thanks!

**Comment by sergdess** [comment]
Sorry for the delay, yes, I'll take it!

**Comment by BrentOzar** [comment]
Thanks for the pull request. Looks good, merged into the dev branch, and it'll be in the November release with credit to you in the release notes.
