### ISSUE TITLE
sp_blitz will create nvarchar(max) column instead of XML column in local DB when @OutputXMLasNVARCHAR = 1 is used

### ISSUE THREAD

**Issue by david-prestridge** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2601]
sp_blitz is currently creating an XML column for QueryPlan when writing to a local table.  This forces you to have one table in your database for the local machine and a different table in the database for all remote machines when writing sp_blitz results to the database.

This request is for the @OutputXMLasNVARCHAR =1 parameter to modify the format of the local database to use NVARCHAR(MAX ) on the QueryPlan column so one table can be used for all result sets.

I have already tested code that will allow this functionality and will be willing to code these changes and create a pull request for them.

**Comment by BrentOzar** [comment]
OK, great! Looking forward to the pull request. Thanks!

**Comment by david-prestridge** [comment]
Pull request is done.

**Comment by BrentOzar** [comment]
Looks good! Thanks for the pull request. Merging into the dev branch, and it'll be in the October release with credit to you in the release notes. Thanks!
