### ISSUE TITLE
sp_BlitzWho: add an option to sort by session ID

### ISSUE THREAD

**Issue by DPetrusma** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2603]
**Problem**
A few times I've found myself investigating some issue, and through some other notifications we've set up or other DMV, I've found a problem SPID. I would like to then see who is running it and what the query is before I just kill it. Currently, the output of sp_BlitzWho is sorted by time, and it can make finding a specific session among hundreds a little tedious.

**Proposed Solution**
I can't find any previous or existing issues about the sort order for this procedure, so I assume it's not that big of a deal to most people. I'd like a new parameter (like @SortOrder) that defaults to 'elapsed_time' but also accepts 'session_id' to sort by those two columns.

**Alternatives**
At the moment I export the list of IDs and time to Excel, sort by session id, find the time, and use that to find the offending session. Within SQL, I'm not sure of any other alternatives.

**Are you ready to build the code for the feature?**
I am willing to contribute effort to this. Maybe I'm oversimplifying, but it looks like it wouldn't be too complicated to add some logic to the order by at the very end to handle a few different options with a CASE WHEN
```sql
SET @StringToExecute += 	
		N' ORDER BY 2 DESC
		';
```

**Comment by BrentOzar** [comment]
Thanks for the pull request, and nice work! I'm merging this into the dev branch, and it'll be in the October release with credit to you in the release notes.
