### ISSUE TITLE
sp_DatabaseRestore restores an older backup instead of the latest backup if the older file's name sorts later than the most recent backup file's name (a-z)

### ISSUE THREAD

**Issue by parrotdba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2604]
**Version of the script**
7.99

**What is the current behavior?**
If there's a backup file in the directory with a name that **sorts** later than Ola's naming scheme, but is an **earlier** backup than other backup files in the directory created using Ola's scripts, sp_DatabaseRestore restores the earlier file instead of the latest file.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Backup a database into the same directory that Ola's scripts backs up that database to, but name the backup file Z.BAK. 
2. Run Ola's backup scripts to backup the database again. 
3. Run sp_DatabaseRestore. 
4. sp_DatabaseRestore restores Z.BAK instead of the more recent backup from Ola's script.

**What is the expected behavior?**
sp_DatabaseRestore should restore the most recent backup, not the older Z.BAK backup.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Only just started working with sp_DatabaseRestore. So far SQL Server 2019 CU6, Windows 10. But I don't imagine the versions making a difference for this behavior.

**NOTE:** I realize this might not seem high priority, but there could be one off backups in a directory for various reasons (such as in test environments), that would potentially not be named with Ola's naming scheme. In the interest of automating restores and not having to babysit restores to check that the database was really restored from the last backup file and not from a one-off that someone made earlier, it seems like instead of sorting backups by name desc, that the backup date could be used, or the LSN sequence since those are in the headers?

**Comment by BrentOzar** [comment]
Sure, are you going to code this?

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by BrentOzar** [comment]
@parrotdba to be clear - if you want a change in the behavior in the script, this would be something that you'd need to code. Unfortunately, open source doesn't mean free consulting - you have to help out with the change you want to see.

If you decide you want to move forward with coding this, leave a comment here and I can reopen the issue and assign it to you. Then, check out the contributing guide in the root of the repo for details on how to get started with contributing code in Github.

Sorry about that!

**Comment by parrotdba** [comment]
@BrentOzar I didn't ask for free consulting 😀 Just reporting the bug to find out more info. Maybe the behavior was by design or something.

The issue can stay closed for now. I'm not sure yet if I'm going to fix the script (not done looking through the code yet, and there's file location assumptions I would want to fix as well) or if I'll just work around the issues.

Thanks!
