### ISSUE TITLE
sp_BlitzLock first result window empty

### ISSUE THREAD

**Issue by Garak1984** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2607]
**Version of the script**
@VersionDate = '20190101'

**What is the current behavior?**
First result window empty, second has diff results.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
WIN 2012 SQL 2014 
![image](https://user-images.githubusercontent.com/68588023/94950182-79f2b000-04e2-11eb-91e1-37b1943a3aea.png)

**Comment by BrentOzar** [comment]
Ah, goodness - see that "Jan 1 2019" in the screenshot? That's a very old version. Go ahead and update to the current version, and let us know if it happens again.

**Comment by Garak1984** [comment]
After update. it works properly.

**Comment by BrentOzar** [comment]
Ok, great, thanks!
