### ISSUE TITLE
Allow CheckID -1 to be skipped in SkipChecksTable

### ISSUE THREAD

**Issue by bojanderson** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2608]
**Is your feature request related to a problem? Please describe.**
I use the SkipChecks parameters to avoid certain checks but one CheckID want to avoid universally is the -1 CheckID. However if I put ServerName NULL, DatabaseName NULL, CheckID -1 then I still get those records.

**Describe the solution you'd like**
I would like to go into the code where those -1 CheckID rows are added, make sure they're in one block together and wrap it in a IF statement that looks for CheckID -1 in the SkipChecks table submitted through parameters

**Describe alternatives you've considered**
I'd be game for any other alternative, like another parameter, but mine seems the easiest and simplest

**Are you ready to build the code for the feature?**
Yes, I'm confident I can make this change quickly. If I got the go ahead that this was a valid thing to do then within a week I'd make sure I had some free time and make the quick change to the code and do some basic testing of it.

Below is a screenshot showing an example of the type of thing I want to improve/fix.
![CheckID-1Example](https://user-images.githubusercontent.com/26066615/94980712-40c63a00-04fa-11eb-88ab-65abf0bc172c.png)

**Comment by bojanderson** [comment]
I also will admit I've never contributed to an Open Source project before, so I was trying to find something small I could do just to cut my teeth on it

**Comment by BrentOzar** [comment]
Thanks for the offer, but let's focus on things that are actually causing you a problem. I totally appreciate your offer to help, but remember that the folks on the other side of the screen have to test and document your work, and they're volunteers with limited time too.

Check out the list of existing open issues, or keep your eyes peeled for incoming issues that you might be able to tackle, or find issues that are really causing you a problem during your work with the First Responder Kit.

Thanks for understanding - but again, thanks for the offer!

**Comment by bojanderson** [comment]
Maybe in the future when a real issue with Skip Checks on sp_Blitz needs done, maybe throw this enhancement in there because I would actually like to be able to skip Check ID -1.

But I can understand if the juice isn't worth the squeeze now.
