### ISSUE TITLE
BlitzFirst is missing CHECKDB running

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2609]
**Version of the script**
`SELECT @Version = '7.99', @VersionDate = '20200913';`

**What is the current behavior?**
these cross apply doodads eliminate the row for checkdb. changing them to outer apply fixes it.
```
    CROSS APPLY sys.dm_exec_query_plan(r.plan_handle) pl
    CROSS APPLY sys.dm_exec_sql_text(r.sql_handle) AS t
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Window one:
`DBCC CHECKDB(StackOverflow2013) WITH NO_INFOMSGS, ALL_ERRORMSGS, EXTENDED_LOGICAL_CHECKS, DATA_PURITY, MAXDOP = 8;`

Window two:
`EXEC sp_BlitzFirst @Seconds = 10, @ExpertMode = 1;`

**What is the expected behavior?**
CheckID 2 should fire for CHECKDB running

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Found on 2019 👻

**Comment by erikdarlingdata** [comment]
Will have PR later today!

**Comment by BrentOzar** [comment]
Nice catch! Merged into the dev branch, will be in the October release with credit to you in the release notes.
