### ISSUE TITLE
sp_BlitzIndex - show modification counter in #1900 stats query

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2612]
**Is your feature request related to a problem? Please describe.**
In the `dm_db_stats_properties` view, there's a modification counter column that might be useful to show here, though as I'm writing this I'm half-remembering some weird caveat with it. That gets hit in the query for #1900 that shows the histogram.

**Describe the solution you'd like**
Add the `modification_counter` column to the query.

**Describe alternatives you've considered**
Not knowing how many modifications the lead column in the stats object as had since it was last updated. 

**Are you ready to build the code for the feature?**
Yes, it's just adding a column to the select list.

**Comment by BrentOzar** [comment]
Thanks sir! Merged into dev, will be in the October release with an AmEx platinum credit to you in the release notes.
