### ISSUE TITLE
sp_BlitzIndex: Several Bugs With Missing Database Prefixes in DMV Queries

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2616]
**Version of the script**
`SELECT @Version = '7.99', @VersionDate = '20200913';`

**What is the current behavior?**
I was working on issue #2612 when I noticed that "new" queries to get histogram info, and column store dictionary info are all missing the database name prefix in system views. The proc will work if you run it in the context of the database you're looking in, but if you run from master, or a DBA utility database, the queries don't resolve to anything based on object id.

![image](https://user-images.githubusercontent.com/2136037/95372559-b68b2680-08a9-11eb-83ff-240bd344c4b8.png)

Those are just the ones I noticed. I'll go through the rest and spot check them when I fix these.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
USE master;

EXEC dbo.sp_BlitzIndex @DatabaseName = N'StackOverflow2013', 
                       @SchemaName = N'dbo', 
                       @TableName = N'Posts'; 
                      
USE StackOverflow2013;

EXEC dbo.sp_BlitzIndex @DatabaseName = N'StackOverflow2013', 
                       @SchemaName = N'dbo', 
                       @TableName = N'Posts';    
```

**What is the expected behavior?**
The above two executions should return the same output.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All of them.

**Comment by erikdarlingdata** [comment]
Also noticed here. I'm going to add in the change to make the PR as complete as possible. If they're not necessary in this query

![image](https://user-images.githubusercontent.com/2136037/95373939-b2600880-08ab-11eb-8813-024baadf34db.png)

**Comment by BrentOzar** [comment]
Your timing is impeccable: I just hit this with a client running sp_BlitzIndex from a DBA database, and I just realized the columnstore visualization stuff wasn't working because of the cross-database queries. Nice work. Merged into the dev branch, will be in the Oct release with credit to you in the release notes.
