### ISSUE TITLE
sp_BlitzIndex - reword error message when no warnings are found in mode 4

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#262]
In mode 4, if no problems are found, it says to run it in mode 4. Oops. Should only show up in super-healthy (or super-idle) environments.

https://cloud.githubusercontent.com/assets/15877772/15377943/408bbb96-1d14-11e6-91f8-d353a3eacccd.png

**Comment by BlitzErik** [comment]
#430
