### ISSUE TITLE
sp_BlitzCache: Missing recompile hint on #ReadableDBs query

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2629]
**Version of the script**
Newestest!

**What is the current behavior?**
There's no recompile hint, and the query shows up in output in demos with a clear cache. I know this can happen regardless, but standards is standards. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Code review!

**What is the expected behavior?**
Recompile hint!

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All

I will fix this, unless someone out there wants an easy first contribution.

**Comment by BrentOzar** [comment]
Looks like it's in there: 

`    EXEC('INSERT INTO #ReadableDBs (database_id) SELECT DBs.database_id FROM sys.databases DBs INNER JOIN sys.availability_replicas Replicas ON DBs.replica_id = Replicas.replica_id WHERE replica_server_name NOT IN (SELECT DISTINCT primary_replica FROM sys.dm_hadr_availability_group_states States) AND Replicas.secondary_role_allow_connections_desc = ''READ_ONLY'' AND replica_server_name = @@SERVERNAME OPTION (RECOMPILE);');`

**Comment by erikdarlingdata** [comment]
Oh weird, I wonder what happened over here. I had to add it in locally. Sorry about that.
