### ISSUE TITLE
sp_BlitzIndex mode 0 and mode 4 producing the same results.

### ISSUE THREAD

**Issue by Jorriss** [BrentOzarULTD/SQL-Server-First-Responder-Kit#264]
When running sp_BlitzIndex in the Collector and while testing it locally, mode 0 and mode 4 generated the same results. There is a also a question as to when mode 4 does compared to mode 0.

![2016-05-24 14_38_51-sqlquery2 sql - a-wing stackoverflow_201509 a-wing_richie 52 _ - microsoft sq](https://cloud.githubusercontent.com/assets/737277/15515760/b469ebca-21bd-11e6-8864-0566a070d6a6.png)
![2016-05-24 14_39_44-sqlquery1 sql - a-wing stackoverflow_201509 a-wing_richie 54 _ - microsoft sq](https://cloud.githubusercontent.com/assets/737277/15515761/b46cbf58-21bd-11e6-8291-839f0dd2a5a1.png)

**Comment by BlitzErik** [comment]
This doesn't seem to be an issue any more. Can we close?

**Comment by BrentOzar** [comment]
Yeah, closing.
