### ISSUE TITLE
sp_BlitzWho: Wrong ordering when a query running for 10+ days 

### ISSUE THREAD

**Issue by ahmetrende** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2652]
Hi,

If a query is running for 10+ days, sp_BlitzWho cannot order correctly. 
Day section (in elapsed_time) should be double char even query is running under ten days.
When I edit the code, it works. You can see the attached images.

as is:
![wrong](https://user-images.githubusercontent.com/22793885/97714260-fcff2a00-1ad1-11eb-9642-128c911eb595.png)

should be:
![correct](https://user-images.githubusercontent.com/22793885/97714257-fbcdfd00-1ad1-11eb-8052-e2b438e0f686.png)

**Comment by BrentOzar** [comment]
Hi, and thanks for the report.

When you opened the issue, there was a lot of text in there to fill out - that's called the issue template. Going forward, when you fill out the issue, can you leave that in and answer the questions? That helps us triage what's going on.

Now, about this one - sure, we'd love to take that code as a pull request! Read the contributing guide on how to get started contributing code: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/main/CONTRIBUTING.md

I totally understand that Github can be kinda intimidating when it comes to pull requests, so if you hit a wall and get frustrated, put in the specific code that you want changed in here. Don't copy/paste the entire script - just let us know what specifically you want changed.

Thanks!

**Comment by ahmetrende** [comment]
> Hi, and thanks for the report.
> 
> When you opened the issue, there was a lot of text in there to fill out - that's called the issue template. Going forward, when you fill out the issue, can you leave that in and answer the questions? That helps us triage what's going on.
> 
> Now, about this one - sure, we'd love to take that code as a pull request! Read the contributing guide on how to get started contributing code: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/main/CONTRIBUTING.md
> 
> I totally understand that Github can be kinda intimidating when it comes to pull requests, so if you hit a wall and get frustrated, put in the specific code that you want changed in here. Don't copy/paste the entire script - just let us know what specifically you want changed.
> 
> Thanks!

You can check my pull request. Thank you!
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/2659

**Comment by BrentOzar** [comment]
Great, thanks, fixed. It's merged into the dev branch, and will be in the November release with credit to you in the comments.

Side note - the next time you do a pull request, just edit the file and make the code changes you want. Github automatically shows the differences in what you did. Your pull request deleted all of sp_BlitzWho's content and replaced it with just your notes, so I couldn't actually accept that pull request - but the changes were straightforward enough that I could copy 'em in. I'm only mentioning this in case you contribute larger changes or try to contribute to another project. Thanks though!
