### ISSUE TITLE
sp_BlitzCache: Parameterized queries in different databases are flagged as multiple plans

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2653]
**Version of the script**
`@Version = '7.999', @VersionDate = '20201011'`

**What is the current behavior?**
If you have a database per tenant model where the same queries run, they're flagged as multiples even when they're parameterized.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
DBCC FREEPROCCACHE;
GO 

DECLARE @r INT = 1;
DECLARE @sql NVARCHAR(MAX) = N'SELECT COUNT(*) AS records FROM dbo.Users AS u WHERE u.Reputation = @r;'

EXEC StackOverflow2013.sys.sp_executesql @sql, N'@r INT', @r;
EXEC StackOverflow.sys.sp_executesql @sql, N'@r INT', @r;

EXEC sp_BlitzCache @OnlySqlHandles = '0x02000000E569613767CC36A863977FFE3AFBB63C09CD37060000000000000000000000000000000000000000'
```
![image](https://user-images.githubusercontent.com/2136037/97725038-125d5f80-1aa4-11eb-96d6-4c982292e7b2.png)

**What is the expected behavior?**
I addressed this in the query that looks at this to sort by query hash (#2102), and I think I can do the same here, by also grouping by database name:

![image](https://user-images.githubusercontent.com/2136037/97725618-c3fc9080-1aa4-11eb-95a7-f900eb7a1d92.png)

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SO MANY!

**Comment by BrentOzar** [comment]
OOO! Yeah, good catch. If you run out of time and can't fix it, holler and I can dig in there too. Thanks!

**Comment by erikdarlingdata** [comment]
Nope, getting it done today!

**Comment by BrentOzar** [comment]
Looks good! Perfect timing too, doing the release today. Will be in the Nov release with credit to you in the release notes. Thanks sir.
