### ISSUE TITLE
sp_BlitzFirst - Msg 2628 Sev16 state 1 at insertion in history table due to details column size limitation

### ISSUE THREAD

**Issue by jeffchulg** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2660]
**Version of the script**
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.

Current version

**What is the current behavior?**

The table created by `sp_BlitzFirst `has column `[Details]` limited to `NVARCHAR(4000)`:

```
IF @OutputType = 'SCHEMA'
BEGIN
    SELECT FieldList = '[Priority] TINYINT, [FindingsGroup] VARCHAR(50), [Finding] VARCHAR(200), [URL] VARCHAR(200), **[Details] NVARCHAR(4000)**
```

While in the temporary table `#BlitzFirstResults`, this column is created `NVARCHAR(MAX)`.

Hence, everytime the Details column is larger than 4000 nchars, the SP will fail with following error message:

> Msg 2628, Sev 16, State 1, Line 1 : String or binary data would be truncated in table 'DBA.FirstResponderKit.BlitzFirstExecutionHistory', column 'Details'. Truncated value: 'xxx'

**If the current behavior is a bug, please provide the steps to reproduce.**

See above.

**What is the expected behavior?**

No error, either because of controlled truncation OR by raising to `NVARCHAR(MAX) `the definition of `[Details]` column.
In addition, a check would be necessary to alter existing destination table (if any) so that if the definition of `[Details]` column is `NVARCHAR(4000)`, then it would try to fire `ALTER TABLE XXX ALTER COLUMN [Details] NVARCHAR(MAX)`. It would not be disruptive but could add a check result telling that destination table cannot be upgraded.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
I tested on SQL Server 2019 on Windows Server 2019.
However, by design, it should be reproductible in any environment.

**Comment by BrentOzar** [comment]
Good catch! I changed it to trim the details to 4000 characters. 

Changing column definitions is a little tricky for sp_BlitzFirst since folks often centralize the data into a single table, merging it via stuff like linked servers or SSIS, and enlarging the existing column would break their processes.
