### ISSUE TITLE
Get @AdeDBA set up in the write role to prep for sp_BlitzAnalysis

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2661]
@AdeDBA will be working on a stored proc to analyze the contents of several sp_Blitz% tables. I want to get him into a role where he can manage his own pull requests for it.

After a quick reading of https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization, here's what I may need to do:

* Make the main branch a protected branch (so only people in the maintainer role have access to push to it)
* Create a new group for contributors
* Assign the "write" role to that group
* Put Adrian and Erik Darling into that group
* Document what I did so I can do it again later
* Update the Contributing Guide so people know what's happening when Adrian & Erik merge their own stuff

**Comment by erikdarlingdata** [comment]
BACK IN THE GANG! 😃

**Comment by Adedba** [comment]
Just popping this here as I wasn't too sure whether to open an new issue or not. 

Here is what I have so far , should have a first revision soon which no doubt will have scope for improvements but just wanted to share a visual of how it is progressing: 

Example Procedure call: 
`EXEC sp_BlitzAnalysis 
@FromDate = '20201111 13:30',
@ToDate = NULL, /* Get an hour of data */
@OutputSchemaName = N'dbo',
@OutputDatabaseName = N'DBA',
@OutputTableNameBlitzFirst = N'BlitzFirst', 
@OutputTableNameFileStats = N'BlitzFirst_FileStats',
@OutputTableNamePerfmonStats  = N'BlitzFirst_PerfmonStats',
@OutputTableNameWaitStats = N'BlitzFirst_WaitStats',
@OutputTableNameBlitzCache = N'BlitzCache',
@OutputTableNameBlitzWho = N'BlitzWho',
@MaxBlitzFirstPriority = 249,
@BlitzCacheSortorder = 'cpu',
@WaitStatsTop = 3, /* Controls the top for wait stats only */
@Debug = 0;`


Sample output: 
![image](https://user-images.githubusercontent.com/33764798/99529032-14298d00-2997-11eb-9ae5-4c1993b7874c.png)
![image](https://user-images.githubusercontent.com/33764798/99529044-1ab80480-2997-11eb-8934-ad502b045132.png)

**Comment by BrentOzar** [comment]
I sent out invites to @Adedba and @erikdarlingdata - y'all should be able to write in this repo now, and you should be able to merge your pull requests into the dev branch. Holler if you run into problems on it. (I apologize for this taking so long! I was under the impression this was gonna be harder than it was.)
