### ISSUE TITLE
sp_Blitz Check ID 169 reports incorrect Service Account

### ISSUE THREAD

**Issue by ToddChitt** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2664]
Version: 3.99, dated 20201011

Running sp_Blitz from SSMS (18.7.1), sp_Blitz installed in master.  SQL 2017 Standard

**What is the current behavior?**
Under Finding Group = "Informational"; Finding = "SQL Server is running an NT Service account"; Details = "I'm running as NT Service\MSSQLLaunchpad. I wish I had an Active Directory service account instead."

**If the current behavior is a bug, please provide the steps to reproduce.**
Here's the thing: That service on this server is STOPPED, and SQL Server (MSSQLSERVER) is running under a Domain Service account.

**What is the expected behavior?**
Expect that it would reference the correct service (SQL Server), not SQL Server Launchpad.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
I don't know about previous versions as I only started using this tool.

**Comment by BrentOzar** [comment]
Oh no, sorry to hear that! Can you run this diagnostic query and paste a screenshot of the results:

`SELECT servicename, status_desc, service_account, filename FROM sys.dm_server_services;`

That'll help us troubleshoot the issue. Thanks!

**Comment by ToddChitt** [comment]
![2020-11-09_8-45-45](https://user-images.githubusercontent.com/7051072/98548947-2ce3c580-2268-11eb-9a91-9182e4c90b19.png)

see attached. Leading path of the file name truncated.
Thanks!
Also including appropriate line result from sp_Blitz run on the same server.

![2020-11-09_8-50-56](https://user-images.githubusercontent.com/7051072/98549424-c4e1af00-2268-11eb-9909-3db8d906081c.png)

**Comment by BrentOzar** [comment]
OK, great, fixed. It's in the dev branch now if you want to test it: 

https://raw.githubusercontent.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/dev/sp_Blitz.sql

It'll be in the November public release with credit to you in the release notes. Thanks!
