### ISSUE TITLE
sp_BlitzIndex: write post for single-threaded scalar UDFs

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2671]
**Is your feature request related to a problem? Please describe.**
Is your feature request related to a problem? Please describe.
In #2662, I'm writing up the documentation for the sp_BlitzIndex checks by priority, and I found that the warning for serial forcers (computed columns that hit scalar functions) doesn't have a URL.

**Describe the solution you'd like**
Write a blog post with rundowns of each warning, and link it to https://www.brentozar.com/go/serialudf.

**Describe alternatives you've considered**
Tried looking for an existing page with good rundowns of each issue, but they're kinda scattered around the web.

**Are you ready to build the code for the feature?**
Yes.

**Comment by erikdarlingdata** [comment]
Serial forcers also covers UDFs in check constraints. I know I wrote a couple posts over on BOU about them, which you might be able to farm some content from for the unified page if you need it.

https://www.brentozar.com/archive/2016/04/another-hidden-parallelism-killer-scalar-udfs-check-constraints/
https://www.brentozar.com/archive/2016/01/another-reason-why-scalar-functions-in-computed-columns-is-a-bad-idea/

**Comment by BrentOzar** [comment]
Done, will go live this week.
