### ISSUE TITLE
sp_BlitzLock - TimeZone convertion

### ISSUE THREAD

**Issue by merlinbruno** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2674]
**Version of the script**
SELECT @Version = '2.999', @VersionDate = '20201011';

**What is the current behavior?**
At **"Parse process and input buffer XML"** there is a conversion of TimeZone that won't match with the join criteria in **"Check 6"** `AND dp.event_date = dow.event_date`

**If the current behavior is a bug, please provide the steps to reproduce.**
Run the sp_BlitzLock looking to the summary provided by  **"Check 6 breaks down the types of locks (object, page, key, etc.)"** 
Because the different TimeZone returned by the first step, won't be matched.

I don't know if this current treatment on timezone in the first select is necessary. Is possible that the results of the first query (based on #deadlock_process) be hosted in a different server than the second query? (based on  #deadlock_owner_waiter)

**What is the expected behavior?**
A non-empty summary for "Check 6" according to the results detailed by previous checks.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2016 Standard on Windows Server 2016 Datacenter

**Comment by BrentOzar** [comment]
Hi! Thanks for the issue, and welcome to Github.

It sounds like you've got a handle on the changes you'd like to see. Here's the contributing guide on how to get involved: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/main/CONTRIBUTING.md

In there, we link to Rob Sewell's excellent getting-started-with-Github primer: https://sqldbawithabeard.com/2019/11/29/how-to-fork-a-github-repository-and-contribute-to-an-open-source-project/

Or, if you'd like someone else to make the changes, can you close this issue, and reopen it with separate issues for each thing that you'd like to see changed? If you do that, when you fill out the issue again, please don't delete the template contents: instead, fill it out with the details. Thanks!

**Comment by erikdarlingdata** [comment]
I'm not sure which path you've chosen to try to fix this, but I looked the code over, and it seems like there's only one other place in all the XML shredding that we grab a `@timestamp` value out of XML. If we apply the same logic to that timestamp as the previous one, it should make everything line up:

```
		/*Grab the full resource list*/
        SET @d = CONVERT(VARCHAR(40), GETDATE(), 109);
        RAISERROR('Grab the full resource list %s', 0, 1, @d) WITH NOWAIT;
        
        SELECT 
            CONVERT(DATETIME2(7), 
            SWITCHOFFSET(CONVERT(datetimeoffset, x.event_date ), 
            DATENAME(TzOffset, SYSDATETIMEOFFSET()))) AS event_date,
            x.victim_id, 
            x.resource_xml
        INTO        #deadlock_resource
        FROM 
        (
        SELECT      dd.deadlock_xml.value('(event/@timestamp)[1]', 'DATETIME2') AS event_date,
					dd.deadlock_xml.value('(//deadlock/victim-list/victimProcess/@id)[1]', 'NVARCHAR(256)') AS victim_id,
					ISNULL(ca.dp.query('.'), '') AS resource_xml
        FROM        #deadlock_data AS dd
        CROSS APPLY dd.deadlock_xml.nodes('//deadlock/resource-list') AS ca(dp)
        ) AS x
		OPTION ( RECOMPILE );

```

**Comment by merlinbruno** [comment]
Initially, I thought to strip any conversion and make it only in the end (for presentation). 
But checking the code you propose I think that is better since it is a minor change with the same result.

Can you proceed with the changes or do I?

**Comment by erikdarlingdata** [comment]
Totally up to you! I'm fine either way.

**Comment by BrentOzar** [comment]
Thanks for the pull request! Merged into the dev branch and will be in the December release with credit to you in the release notes.
