### ISSUE TITLE
sp_BlitzLock - Check 2 summary filter includes non-index locks related results

### ISSUE THREAD

**Issue by merlinbruno** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2676]
**Version of the script**
SELECT @Version = '2.999', @VersionDate = '20201011';

**What is the current behavior?**
At **"Check 2 continuation, number of locks per index"** the filter uses only `AND dow.lock_type NOT IN (N'HEAP', N'RID')` criteria, including some rows where indexes names have NULL value for some cases where indexes are not applicable for that lock type (OBJECTS and PAGES by example). 

At first glance I think a good idea to add `AND dow.index_name is not null` to the filter clause, but I don't be sure if the index name should be expected for the other lock types.

**If the current behavior is a bug, please provide the steps to reproduce.**
Run the sp_BlitzLock looking to the summary provided by  **"Check 2** when the results including lock types that have no index related (OBJECTS and PAGES by example). 

**What is the expected behavior?**
The summary provided by "Check 2" listing only the results that have lock types related to indexes.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2016 Standard on Windows Server 2016 Datacenter

**Comment by BrentOzar** [comment]
Sure, if you want to go for adding that filter, here's the contributing guide on how to get started:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/main/CONTRIBUTING.md

I'm going to assign you to the issue just to make it clear for other readers that you're working on the issue. (If I didn't understand that correctly, let me know.) Thanks!

**Comment by BrentOzar** [comment]
Nice catch! Merged into the dev branch, will be in the December release with credit to you in the release notes.
