### ISSUE TITLE
sp_DatabaseRestore When Restoring FULL + DIFF, differential is being disregarded

### ISSUE THREAD

**Issue by AdemirP** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2681]
**Version of the script**
SELECT @Version = '7.999', @VersionDate = '20201011'

**What is the current behavior?**
When I try to restore  FULL + DIFF backup, it's disregarding the DIFF file. 
Only FULL is being restored and none error is being raised. 
It looks like both have been restored.

**If the current behavior is a bug, please provide the steps to reproduce.**
Create 01 FULL + 01 DIFF Backup on Microsoft SQL Server 2017 (RTM-CU18) (KB4527377) Standard and use procedure to restore them at once on Microsoft SQL Server 2019 (RTM-CU7) (KB4570012)  - Standard 

**What is the expected behavior?**
Restore FULL + DIFF

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Microsoft SQL Server 2019 (RTM-CU7) (KB4570012)  - Standard 
Windows Server 2016 Standard
![RESTORE01](https://user-images.githubusercontent.com/31742461/99328034-fe627d80-2859-11eb-9164-8ff66a547aa9.png)

**Comment by BrentOzar** [comment]
Worked fine here:
<img width="1275" alt="Screen Shot 2020-11-27 at 3 09 53 AM" src="https://user-images.githubusercontent.com/245462/100443191-11492f00-305e-11eb-9706-232e454e5ce8.png">


You may have had an invalid diff path.

**Comment by AdemirP** [comment]
Hi Brent, thanks for replying! 
For me, it shows as restore completed as well, but, I’m not able to find any update done between Full and Diff backup. 
Could you, please:
- Take a Full backup
- Update something
- Take a Diff backup 
Restore both and check if update was reflected?
Thank you!

**Comment by BrentOzar** [comment]
Yes, I did. In that screenshot, it's the second restore command that shows a different number of pages restored.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws
