### ISSUE TITLE
sp_BlitzLock: Reports 0 parallel deadlocks in summary correctly

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2682]
**Version of the script**
```SELECT @Version = '2.9999', @VersionDate = '20201114';```

**What is the current behavior?**
When I wrote this check, I forgot to add a ```HAVING``` to the summary view so that if there are 0 parallel deadlocks, the line won't be inserted.

**If the current behavior is a bug, please provide the steps to reproduce.**
Run the proc on a server that hasn't had any deadlocks

**What is the expected behavior?**
Skippit

```
	/*Check 13 is total parallel deadlocks*/
        SET @d = CONVERT(VARCHAR(40), GETDATE(), 109);
        RAISERROR('Check 13 %s', 0, 1, @d) WITH NOWAIT;
	INSERT #deadlock_findings WITH (TABLOCKX) 
        ( check_id, database_name, object_name, finding_group, finding ) 	
	SELECT 13 AS check_id, 
	N'-' AS database_name, 
	'-' AS object_name,
	'Total parallel deadlocks' AS finding_group,
	'There have been ' 
	+ CONVERT(NVARCHAR(20), COUNT_BIG(DISTINCT drp.event_date)) 
	+ ' parallel deadlocks.'
        FROM   #deadlock_resource_parallel AS drp
	WHERE 1 = 1
        HAVING COUNT_BIG(DISTINCT drp.event_date) > 0
	OPTION ( RECOMPILE );
```

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
MINE 😭

**Comment by BrentOzar** [comment]
Looks good! Thanks for the pull request, will be in the December release with credit to you in the release notes. Also, SurlyDev says hi.
