### ISSUE TITLE
sp_BlitzIndex: columnstore visualizer doesn't include all columns on nonclustered columnstore

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2684]
**Version of the script**
SELECT @Version = '7.9999', @VersionDate = '20201114';

**What is the current behavior?**
Create a nonclustered columnstore index on multiple columns, and not all of them may show in the visualization result set.

```
CREATE NONCLUSTERED COLUMNSTORE INDEX NCCI
  ON dbo.Users(Location, DisplayName, CreationDate, Id);
GO
sp_BlitzIndex @TableName = 'Users'

```

**What is the expected behavior?**
We should see all columns in the visualization, including Location, which isn't present here:

<img width="1034" alt="Screen Shot 2020-11-17 at 10 37 08 AM" src="https://user-images.githubusercontent.com/245462/99432519-1b7e6700-28c1-11eb-98fb-e27da7017d64.png">

Also, AboutMe shows here, which isn't correct. I'm probably joining to the first columns in the table rather than using the ordinal. (Shout out to Will Stillwell, and definitely not Eric L, who had nothing to do with this at all.)

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2019.

**Comment by alihacks** [comment]
This almost seems like a MSSQL bug as column_id seems to be always 1,2,3... and does not reference the column_id from table:
```
CREATE NONCLUSTERED COLUMNSTORE INDEX NCCI
  ON dbo.Users(Reputation,UpVotes,Views);
GO

SELECT column_id, name FROM sys.columns
WHERE object_id = OBJECT_ID('Users')

select DISTINCT c.name, c.column_id, c.name
FROM sys.partitions p
INNER JOIN sys.columns c ON p.object_id = c.object_id
INNER JOIN sys.types t ON c.system_type_id = t.system_type_id AND c.user_type_id = t.user_type_id
INNER JOIN  sys.column_store_segments seg on p.partition_id = seg.partition_id and seg.column_id = c.column_id
WHERE c.object_id = OBJECT_ID('Users')
ORDER BY column_id

select DISTINCT seg.column_id
FROM sys.partitions p
INNER JOIN  sys.column_store_segments seg on p.partition_id = seg.partition_id 
WHERE p.object_id = OBJECT_ID('Users')
ORDER BY column_id
```

![ncci](https://user-images.githubusercontent.com/11317507/99435188-cac93700-28dd-11eb-823f-512286e49943.png)

**Comment by alihacks** [comment]
I've added code to #2683 that should address this

**Comment by BrentOzar** [comment]
Perfect! Excellent job, thank you.
