### ISSUE TITLE
sp_AllNightLog Install message when dbo.DatabaseBackup is in custom database for DBAAdminobjects

### ISSUE THREAD

**Issue by lostsole** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2685]
**Version of the script**
3.999
**What is the current behavior?**
I get this message:
The module 'sp_AllNightLog' depends on the missing object 'master.dbo.DatabaseBackup'. The module will still be created; however, it cannot run successfully until the object exists

**If the current behavior is a bug, please provide the steps to reproduce.**
Install Ola SQL Server Maintenance Solution in different database than master.
https://ola.hallengren.com/frequently-asked-questions.html

"Do the objects need to be created in the master database?
The objects can be created in any database: master, msdb, or a utility database for database administrative scripts. You just need to change this line of code in MaintenanceSolution.sql:

USE [master]

to point to the database in which the objects will be created. The jobs will automatically be configured to run against this database."

**What is the expected behavior?**
Should look in the database that is being installed first, then give the error.  Checks start at line 167 and are hardcoded to Master
SELECT COUNT(*) FROM master.sys.procedures WHERE name IN('CommandExecute', 'DatabaseBackup')
**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
NA

**Comment by BrentOzar** [comment]
OK, if you want to change that code, you're welcome to. Here's the contributing guide:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/main/CONTRIBUTING.md

This isn't a high priority for me personally - I always use the master database - but if it's important to you, we'd welcome the pull request. If you don't code it within the next week, I'll go ahead and close the pull request. Thanks!

**Comment by BrentOzar** [comment]
I haven't heard back from you, so I'll go ahead and close this. If you change your mind and want to work on it, leave a note here and I can reopen it. Thanks!
