### ISSUE TITLE
sp_BlitzLock: Better identification of Batch Mode parallel deadlocks

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2686]
**Is your feature request related to a problem? Please describe.**
We flag regular deadlocks and parallel deadlocks correctly, but the XML for parallel deadlocks when they occur in queries that contain batch mode operators is different. 

![image](https://user-images.githubusercontent.com/2136037/99882172-847d1c00-2bec-11eb-8827-d476984c2777.png)

**Describe the solution you'd like**
I don't want to put a ton of sweat into this, because there's not a lot of value in the details of the batch mode deadlock XML, just a long list of  sync points:

![image](https://user-images.githubusercontent.com/2136037/99882465-aecfd900-2bee-11eb-8a4e-137ae62c8548.png)

I really just want them to get put into the right category.

**Describe alternatives you've considered**
Day drinking

**Are you ready to build the code for the feature?**
WOULD YOU BELIEVE ME IF I TOLD YOU I ALREADY HAD IT DONE?

**Comment by BrentOzar** [comment]
Thanks for the pull request. I'm going to take you at your word because this is all witchcraft, and you know how our readers feel about sorcery.

**Comment by erikdarlingdata** [comment]
SOMEDAY YOU'LL THANK ME! 

oh wait.
