### ISSUE TITLE
sp_blitzLock results in excessive memory grant

### ISSUE THREAD

**Issue by alihacks** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2691]
**Version of the script**
2.9999,  20201114

**What is the current behavior?**
When running sp_blitzLock, SQL Server grants 22GB of memory due to a left join to an empty temp table with 100,000,000 rows

**If the current behavior is a bug, please provide the steps to reproduce.**
`EXEC EXEC sp_blitzLock`
And observe memory grant either using execution plan or `SELECT * FROM sys.dm_exec_query_memory_grants where session_id=SPID_HERE`

![image](https://user-images.githubusercontent.com/11317507/99918972-79a7b180-2ce8-11eb-9786-76d1112450b3.png)

**What is the expected behavior?**
The memory grant should ideally be less - it seems that the join to temp table with stats was introduced in #1866 by @BlitzErik - I wonder if this has different behavior on my system than originally intended by this optimization.

I've done a quick test of the specific statement causing the memory grant as follows:

Existing Join:
```
DECLARE @EventSessionPath VARCHAR(256) = 'system_health*.xel'
DECLARE @Top INT = 2147483647, @StartDate DATETIME = '19000101', @EndDate DATETIME = '99991231'

DROP TABLE IF EXISTS #t
DROP TABLE IF EXISTS #deadlock_data

CREATE TABLE #t (id INT NOT NULL);
UPDATE STATISTICS #t WITH ROWCOUNT = 100000000, PAGECOUNT = 100000000;

WITH xml
AS ( SELECT CONVERT(XML, event_data) AS deadlock_xml
        FROM   sys.fn_xe_file_target_read_file(@EventSessionPath, NULL, NULL, NULL) )
SELECT TOP ( @Top ) ISNULL(xml.deadlock_xml, '') AS deadlock_xml
INTO   #deadlock_data
FROM   xml
LEFT JOIN #t AS t
ON 1 = 1
WHERE  xml.deadlock_xml.value('(/event/@name)[1]', 'VARCHAR(256)') = 'xml_deadlock_report'
AND    CONVERT(datetime, SWITCHOFFSET(CONVERT(datetimeoffset, xml.deadlock_xml.value('(/event/@timestamp)[1]', 'datetime') ), DATENAME(TzOffset, SYSDATETIMEOFFSET())))  > @StartDate
AND    CONVERT(datetime, SWITCHOFFSET(CONVERT(datetimeoffset, xml.deadlock_xml.value('(/event/@timestamp)[1]', 'datetime') ), DATENAME(TzOffset, SYSDATETIMEOFFSET())))  < @EndDate
ORDER BY xml.deadlock_xml.value('(/event/@timestamp)[1]', 'datetime') DESC
OPTION ( RECOMPILE );
```
Memory Grant:
![image](https://user-images.githubusercontent.com/11317507/99919089-3732a480-2ce9-11eb-876d-ae6bb7b2f25f.png)

Without the #t trick introduced in #1866:
```
DECLARE @EventSessionPath VARCHAR(256) = 'system_health*.xel'
DECLARE @Top INT = 2147483647, @StartDate DATETIME = '19000101', @EndDate DATETIME = '99991231'
DROP TABLE IF EXISTS #t;
DROP TABLE IF EXISTS #deadlock_data;

WITH xml
AS ( SELECT CONVERT(XML, event_data) AS deadlock_xml
        FROM   sys.fn_xe_file_target_read_file(@EventSessionPath, NULL, NULL, NULL) )
SELECT TOP ( @Top ) ISNULL(xml.deadlock_xml, '') AS deadlock_xml
INTO   #deadlock_data
FROM   xml
WHERE  xml.deadlock_xml.value('(/event/@name)[1]', 'VARCHAR(256)') = 'xml_deadlock_report'
AND    CONVERT(datetime, SWITCHOFFSET(CONVERT(datetimeoffset, xml.deadlock_xml.value('(/event/@timestamp)[1]', 'datetime') ), DATENAME(TzOffset, SYSDATETIMEOFFSET())))  > @StartDate
AND    CONVERT(datetime, SWITCHOFFSET(CONVERT(datetimeoffset, xml.deadlock_xml.value('(/event/@timestamp)[1]', 'datetime') ), DATENAME(TzOffset, SYSDATETIMEOFFSET())))  < @EndDate
ORDER BY xml.deadlock_xml.value('(/event/@timestamp)[1]', 'datetime') DESC
OPTION ( RECOMPILE );
```
![image](https://user-images.githubusercontent.com/11317507/99919113-5e897180-2ce9-11eb-9838-1bc97473a902.png)

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Microsoft SQL Server 2019 (RTM-CU8) (KB4577194) - 15.0.4073.23 (X64)   Sep 23 2020 16:03:08   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: )

**Comment by erikdarlingdata** [comment]
Can you let me know if this still results in the large grant?

```
DECLARE @EventSessionPath VARCHAR(256) = 'system_health*.xel'
DECLARE @Top INT = 2147483647, @StartDate DATETIME = '19000101', @EndDate DATETIME = '99991231'

DROP TABLE IF EXISTS #t
DROP TABLE IF EXISTS #deadlock_data

CREATE TABLE #t (id INT NOT NULL);
UPDATE STATISTICS #t WITH ROWCOUNT = 100000000, PAGECOUNT = 100000000;

WITH xml
AS ( SELECT CONVERT(XML, event_data) AS deadlock_xml
     FROM   sys.fn_xe_file_target_read_file(@EventSessionPath, NULL, NULL, NULL) )
SELECT xml.deadlock_xml AS deadlock_xml
INTO   #deadlock_data
FROM   xml
LEFT JOIN #t AS t
ON 1 = 1
CROSS APPLY xml.deadlock_xml.nodes('/event/@name') AS x(c)
WHERE  1 = 1 
AND    x.c.exist('/event/@name[ .= "xml_deadlock_report"]') = 1
AND    CONVERT(datetime, SWITCHOFFSET(CONVERT(datetimeoffset, xml.deadlock_xml.value('(/event/@timestamp)[1]', 'datetime') ), DATENAME(TzOffset, SYSDATETIMEOFFSET())))  > @StartDate
AND    CONVERT(datetime, SWITCHOFFSET(CONVERT(datetimeoffset, xml.deadlock_xml.value('(/event/@timestamp)[1]', 'datetime') ), DATENAME(TzOffset, SYSDATETIMEOFFSET())))  < @EndDate
ORDER BY xml.deadlock_xml.value('(/event/@timestamp)[1]', 'datetime') DESC
OPTION (RECOMPILE);

```

**Comment by alihacks** [comment]
Erik - thanks for your reponse. I did test the code you provided and the memory grant I'm getting is now 168kb

**Comment by erikdarlingdata** [comment]
Great -- did you want to make the pull request?

**Comment by alihacks** [comment]
@erikdarlingdata - I did add your code change to the SP hoping to line up a pull request in https://github.com/alihacks/SQL-Server-First-Responder-Kit/commit/5e4e928b94f04fc19ad37ec3b72a2da6ca652534 - while doing that I realized the code in the comment above was missing the `TOP ( @Top )` piece, and interestingly, adding that back brings back the huge memory grant:
```
DECLARE @EventSessionPath VARCHAR(256) = 'system_health*.xel'
DECLARE @Top INT = 2147483647, @StartDate DATETIME = '19000101', @EndDate DATETIME = '99991231'

DROP TABLE IF EXISTS #t
DROP TABLE IF EXISTS #deadlock_data

CREATE TABLE #t (id INT NOT NULL);
UPDATE STATISTICS #t WITH ROWCOUNT = 100000000, PAGECOUNT = 100000000;

WITH xml
AS ( SELECT CONVERT(XML, event_data) AS deadlock_xml
     FROM   sys.fn_xe_file_target_read_file(@EventSessionPath, NULL, NULL, NULL) )
SELECT TOP ( @Top ) xml.deadlock_xml AS deadlock_xml
INTO   #deadlock_data
FROM   xml
LEFT JOIN #t AS t
ON 1 = 1
CROSS APPLY xml.deadlock_xml.nodes('/event/@name') AS x(c)
WHERE  1 = 1 
AND    x.c.exist('/event/@name[ .= "xml_deadlock_report"]') = 1
AND    CONVERT(datetime, SWITCHOFFSET(CONVERT(datetimeoffset, xml.deadlock_xml.value('(/event/@timestamp)[1]', 'datetime') ), DATENAME(TzOffset, SYSDATETIMEOFFSET())))  > @StartDate
AND    CONVERT(datetime, SWITCHOFFSET(CONVERT(datetimeoffset, xml.deadlock_xml.value('(/event/@timestamp)[1]', 'datetime') ), DATENAME(TzOffset, SYSDATETIMEOFFSET())))  < @EndDate
ORDER BY xml.deadlock_xml.value('(/event/@timestamp)[1]', 'datetime') DESC
OPTION (RECOMPILE);
```

![image](https://user-images.githubusercontent.com/11317507/100157832-3d578b00-2e79-11eb-8f6f-02238e53a111.png)

**Comment by erikdarlingdata** [comment]
Yep, I took it out for that reason.

**Comment by alihacks** [comment]
Wouldn't this PR basically ignore the @Top parameter then? Is there a story behind the left join to the temp table with artificial statistics? In my case, removing that seems like the simplest change but I'm not sure if that's a good idea given it was put in place to improve performance.

**Comment by erikdarlingdata** [comment]
Yep, but I don't think anyone actually uses that parameter, and it would be transparent to them if it got moved to the end where the deadlocks get displayed instead. Getting that initial data pull has always been the most painful part of the procedure, and those changes improve performance there a bit as well. At least in my testing, it goes from 16-19 seconds down to 7-8 seconds. Let me know if that doesn't hold up for you, though.

The story behind the temp table is that in many cases that query won't go parallel without it, which slows the data grab down by minutes in my experience. I considered other methods to get it to go parallel at the time, like using trace flag 8649, but decided against it in case people were running it without sa level privileges.

**Comment by alihacks** [comment]
Thanks for explaining @erikdarlingdata - I really appreciate it. I did some testing and yes I do indeed see a good bit of difference when using a large set of xel files (5:37 vs 8:53 w/o temp table) which was not noticeable when using smaller files (xe session that only contained deadlocks). I was able to observe the change in parallelism in the plans as well.

What would you think if I kept your code w/o the TOP since it seems to provide the best performance, but also code to preserve behavior of TOP? This will not impact performance in cases where TOP is not used: https://github.com/alihacks/SQL-Server-First-Responder-Kit/commit/1609ec3485a2c56fdaed22ddf9d18eea2169aac9

**Comment by erikdarlingdata** [comment]
Sure, go for it!

**Comment by alihacks** [comment]
Thank, created #2692 but it doesn't look like I have permissions to link it to this issue.

**Comment by BrentOzar** [comment]
I have no idea what this does, but it doesn't set off any alarm bells, so merging. Thanks for the pull request. Merged into the dev branch, will be in the December release with credit to you in the release notes.
