### ISSUE TITLE
sp_BlitzIndex IgnoreDatabases parameter was not taken into account when counting # of databases for generating more than 50 databases error

### ISSUE THREAD

**Issue by skrishnan31** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2693]
**Version of the script**
7.99  20200913

**What is the current behavior?**
Currently IgnoreDatabases is being ignored in checking the number of databases to generate error when count > 50

**If the current behavior is a bug, please provide the steps to reproduce.**
If we have more than 50 databases in an instance and need to ignore some databases against which we don't want to run blitz because of valid reasons like they are just snapshots.  Now when the database count is determined it doesn't account for IgnoreDatabases parameter and always throws the error saying you have more than 50 databases in the instance.

**What is the expected behavior?**
In the error check where we are counting databases to throw the error saying more than 50 databases we should ignore the databases passed in through IgnoreDatabases parameter.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All versions

**Comment by BrentOzar** [comment]
Great catch! Thanks for the pull request. Merging into the dev branch, will be in the December release with credit to you in the release notes.
