### ISSUE TITLE
sp_BlitzIndex reports reversed schema and table names in temporal tables details

### ISSUE THREAD

**Issue by MarkHions** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2694]
**Version of the script**
@Version = '7.9999', @VersionDate = '20201114';

**What is the current behavior?**
The output of the details text says
The table [schema_name].[table_name] is a temporal table, with rows versioned in **[history_table_name].[history_schema_name]** on History columns [start_column_name] and [end_column_name].

**If the current behavior is a bug, please provide the steps to reproduce.**
seen on sp_BlitzIndex @Mode = 4

**What is the expected behavior?**
Text should report [history_schema_name].[history_table_name] instead of the reverse.

This bug is likely caused by an accidental reversal of column names during the INSERT #TemporalTables statement,
currently on lines 1993-1994

**Comment by BrentOzar** [comment]
@MikeyBronowski thanks for the pull request! Merged into the dev branch, will be in the December release with credit to you in the release notes.
