### ISSUE TITLE
Columnstore data visualization doesn't work for non-dbo tables

### ISSUE THREAD

**Issue by AigleeK** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2701]
**Version of the script**
@Version = '7.9999', @VersionDate = '20201114';

**What is the current behavior?**
Visualization of columnstore index content doesn't work for tables that are not in the default schema

**If the current behavior is a bug, please provide the steps to reproduce.**
Create columnstore table not in dbo, run sp_BlitzIndex for the table

**What is the expected behavior?**
Last section should show all the rowgroups with their information

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Windows, tested in Azure SQL.

The issue is in line 2697 when trying to get the list of columns, it is just checking for the table name and not the schema so the list of columns comes up empty. By assigning to @TableName the concatenation of schema and table just before the columnList call then it should work. In my case I also had to remove the "p.partition_id = seg.partition_id" condition from the if exists, but I am not sure why that part is not working. 

So, concatenating the schema and table name and removing that part of the condition made it work for Azure SQL for non-dbo tables.

**Comment by BrentOzar** [comment]
Can you get the current version from the dev branch and test it? This was already reported & fixed in another issue. Thanks!

**Comment by AigleeK** [comment]
Oh, sorry about that. I checked the issue didn't exist but didn't check for closed issues. Will test.
