### ISSUE TITLE
exec sp_blitzindex @Mode = 3

### ISSUE THREAD

**Issue by vesajuvonenx** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2709]
**Version of the script**
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.
SELECT @Version = '7.9999', @VersionDate = '20201114';

**What is the current behavior?**
Results have every row the same plan in column Sample Query Plan.
The plan is the one that is in the first row

**If the current behavior is a bug, please provide the steps to reproduce.**
exec sp_blitzindex @Mode = 3

**What is the expected behavior?**
Every row has correct plan.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

**Comment by BrentOzar** [comment]
Hi! Read this: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/2185
