### ISSUE TITLE
Can't use @SkipBackupsAlreadyInMsdb if restoring the same log file to different databases

### ISSUE THREAD

**Issue by gdoddsy** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2710]
**Version of the script**
@Version = '7.9999', @VersionDate = '20201114';

**What is the current behavior?**
Ignores all log files waiting to be restored if you restore the database back to the same server

**If the current behavior is a bug, please provide the steps to reproduce.**
Do a full restore of the database to a new database on the same server, and then try and apply log files using `@SkipBackupsAlreadyInMsdb`

**What is the expected behavior?**
The log files should be restored

**Comment by gdoddsy** [comment]
Also fixing [CommandExecute] to call using the parameter @DatabaseContext so that it works with the latest version of Ola's scripts

**Comment by BrentOzar** [comment]
Thanks for the pull request, sir! Merged into the dev branch, will be in the December release with credit to you in the release notes. (And a link to the video, heh. I haven't watched it yet, but wanna check it out next week.)
