### ISSUE TITLE
sp_BlitzFirst repeatably clears almost everything out of query plan cache

### ISSUE THREAD

**Issue by JamesBirch** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2712]
sp_BlitzFirst v7.9999 repeatably clears almost everything out of query plan cache (a few left, thousands cleared out)

I'm sure it's something about our server, but why would this be happening?

**Comment by BrentOzar** [comment]
That doesn't happen to me - can you be more specific with steps that you're seeing or evidence? It'll be helpful to include screenshots, the size of the server, SQL Server build, etc.

**Comment by JamesBirch** [comment]
This is very specific to our scenario with over a million entries in sysobjects. Will try to narrow it down myself.
