### ISSUE TITLE
sp_BlitzLock  @Help = 1 

### ISSUE THREAD

**Issue by ToddChitt** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2717]
**Version of the script**
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Looking at the code you have hosted here, I think you need a RETRUN; statement around line 118, otherwise it just goes right on. Sure, the help stuff is displayed under Messages result set tab, but maybe you want to keep it consistent with the behavior of sp_Blitz @Help = 1 where the Help info is shown right in the Results tab.

Yeah, I know, I'm picking fly poop out of pepper here, but it's inconsistent.

Also, if I'm running any of these with @Help = 1, it sort of means that is ALL I want, not caring about actual results just yet.

**Comment by BrentOzar** [comment]
Sure, if that's important to you, you can open up a pull request to change it as described here in the contributing guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/main/CONTRIBUTING.md

We'd welcome that pull request. If you don't want to make that code change & contribute it, just let me know and I can close the issue, or if I haven't heard back from you within a week, I'll close it. Thanks!

**Comment by ToddChitt** [comment]
I'm not a big fan of Git, preferring to stay within the 'evil empire' of Dev Ops :) but I understand its power and broad adoption. It may take me a bit but I will give it a shot. Seeing how my request is not critical code to the operation of the various procedures, can you give me more than a week? Two weeks puts us at Christmas, and then everybody takes the next week off. Call it January 4th deadline?
I'm going to use this as an opportunity to FORCE myself to learn Git. It's about time.
Thanks for pushing me in that direction. :)

**Comment by BrentOzar** [comment]
Sure, you bet, sounds good. Thanks!

**Comment by ToddChitt** [comment]
Hey, quick question about the file structure:
It appears that the Install All Scripts is simply a concatenation/compilation of all the individual scripts.  Is there some build process that compiles all the individual scripts into the INSTALL ALL SCRIPTS?

Or do I make my proposed edits to BOTH the individual file(s) AND the INSTALL ALL?
Thanks

**Comment by BrentOzar** [comment]
That's the trick! Thanks for the pull request, and good idea. Merged into the dev branch, and will be in the January release with credit to you in the release notes.
