### ISSUE TITLE
sp_BlitzFirst @ExpertMode - make the PerfMon section more appealing and easier to read

### ISSUE THREAD

**Issue by MarkHions** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2722]
### Suggestion Justification
Of the 59 PerfMon counters output, 46 are some value per second.  However, the "ValuePerSecond" column is the last one output, far away from the "counter_name" and "instance_name" columns that give it meaning.  Less important yet wide columns such as "FirstSampleTime" and "LastSampleValue" intervene, and make the horizontal eye scan more difficult.

### Suggestion A
Pull the ValuePerSecond column to the left, placing it with the meaningful columns.  Keep the ValueDelta column with it, because it has meaning for the 13 non-value-per-second counters.  Push less important but wide columns to the right, where they can still be accessed by the interested reader [if there is one].

### Related Suggestion B
Eliminate many or all of the excessive decimal places in the ValuePerSecond column.  They are often a long string of zeroes without meaning.

**Comment by BrentOzar** [comment]
Hi, Mark. Thanks for the issue.

When you filled the issue out, there were a series of questions to answer. I know it sounds goofy, but that stuff is pretty important - for example, your willingness to code the feature. (Open source doesn't mean free development consulting.)

I'm going to go ahead and close this, but you're welcome to reopen it with the feature request template, and fill the questions out in there.

Thanks for understanding!

**Comment by MarkHions** [comment]
Understood.  I didn't see it as either a "Bug Report" or [New]"Feature Request" so I opened a blank issue.
Look for a better issue soon.
