### ISSUE TITLE
sp_BlitzIndex: commented ALTER TABLE command in "Drop_TSql" only has a single leading hyphen (or is that intentional)

### ISSUE THREAD

**Issue by jeffreymergler** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2724]
related to [sp_BlitzIndex], @Version = '7.9999', @VersionDate = '20201114';

I'm seeing output such as this in the Drop_TSql column:

`-ALTER TABLE [dbo].[TABLE] DROP CONSTRAINT [CONTRAINT_NAME];`
^ note the single hyphen. Unless that's intentional I think a bugfix can be added as below. It only happens when the table is a heap (yeah, yeah, ask me how I know...). I'm happy to fix it.

```
CASE 
	WHEN i.is_primary_key = 1 AND i.index_definition <> ''[HEAP]''
		THEN N''-ALTER TABLE '' + QUOTENAME(i.[database_name]) + N''.'' + QUOTENAME(i.[schema_name]) + N''.'' + 
```

to

```
CASE 
	WHEN i.is_primary_key = 1 AND i.index_definition <> ''[HEAP]''
		THEN N''--ALTER TABLE '' + QUOTENAME(i.[database_name]) + N''.'' + QUOTENAME(i.[schema_name]) + N''.'' + 
```

**Comment by BrentOzar** [comment]
That works great! Thanks for the pull request. Merged into the dev branch, will be in the January release with credit to you in the release notes.
