### ISSUE TITLE
sp_BlitzFirst @ExpertMode - make the PerfMon section more appealing and easier to read

### ISSUE THREAD

**Issue by MarkHions** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2727]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm reading the output of this section of sp_BlitzFirst.  I find the most important numeric column is ValuePerSecond, but it's way over on the right of the output, far away from the counter_name and instance_name columns that give it meaning.  Less important columns such as FirstSampleTime and LastSampleValue intervene, and make the horizontal eye scan more difficult.

46 of the 59 PerfMon counters use the ValuePerSecond metric.

Related to the readability problem is the excessive number of decimal places in the ValuePerSecond column.  While there might have been 13 HoBT lock requests per second, seeing 13.000000000000 is distracting, and the extra decimal bring nothing to the party.

**Describe the solution you'd like**
Pull the ValuePerSecond column to the left, placing it with the meaningful columns. Keep the ValueDelta column with it, because it has meaning for the 13 non-value-per-second counters. Push less important but wide columns to the right, where they can still be accessed by the interested reader [if there is one].

Reduce the number of decimal places in ValuePerSecond to a less-distracting but as-reasonable value, such as zero or one.

**Describe alternatives you've considered**
Any attempt to import into Excel and then hide columns is cumbersome at best.
It's also clumsy to change my downloaded source code so that I exclude the interstitial columns each month.

**Are you ready to build the code for the feature?**
**Yes.**

**Comment by BrentOzar** [comment]
OK, let's not change the output order of something when it's been in place for several years. I hear you that it's more convenient for you, but I'm just hesitant to change it when it's been out for so long.

You can reduce the the number of decimal places to one, though - just don't change the data type of the column if it would break the existing output-to-table functionality. Thanks!

**Comment by BrentOzar** [comment]
I should also add - if the column order is really important to you, the easy way to change that is to fork sp_BlitzFirst and maintain your own repo with a different column order. That way you can sync the upstream changes each month as we release new versions, and as long as the only thing you've changed in your repo is the column order on the output, you should be able to sync that with the main repo here with no issues. (That's a common technique in the open source world.)

**Comment by MarkHions** [comment]
The column order is important to me, but is it important **enough** to fork?  I'm leaning towards **Yes**, because it would also give me the chance to practice playing with repos.

Thanks for the chance to learn.

**Comment by BrentOzar** [comment]
OK, cool. Go for it, and good luck!
