### ISSUE TITLE
sp_BlitzFirst: conflict between collations

### ISSUE THREAD

**Issue by DBAdminDB** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2731]
**Version of the script**
latest 
@Version = '7.99999', @VersionDate = '20201211';

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/58941976/103414398-6e1c9580-4b86-11eb-9f27-df966a7b23bd.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
not so sure, but as you can see in the image, after the following step: "Beginning investigatory queries"
**What is the expected behavior?**

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2012 SP4, windows server 2016
I know that the issue is between msdb and master collation because msdb was restored after a disaster:
master	SQL_Latin1_General_CP1_CI_AS
msdb	SQL_Latin1_General_CP1255_CI_AS

Best regards,

**Comment by BrentOzar** [comment]
Different collections between system databases isn't really a supported configuration. That's something you would want to fix.

If you do want to change the code of these procs to work in a situation like that, you're welcome to - read the contributing guide in the root of the repo to learn how.

Instead though, I'd focus on fixing the server.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws
