### ISSUE TITLE
Clarify check 46 wording, fix typo in sp_BlitzFirst

### ISSUE THREAD

**Issue by alihacks** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2732]
**Version of the script**
`@Version = '7.99999', @VersionDate = '20201211'`

**What is the current behavior?**
This check reports "Query with memory a grant exceeding", percentage is not clear (reported by mrtcs on Slack)

**If the current behavior is a bug, please provide the steps to reproduce.**
Execute sp_blitzFirst on a server that reports check 46

**What is the expected behavior?**
Change wording to: "Query with a memory grant exceeding"
In details, explain what the % is over (max workspace)

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
N/A

**Comment by BrentOzar** [comment]
Nice catch! Thanks for the pull request. Merged into the dev branch, and will be in the January release with credit to you in the release notes.
