### ISSUE TITLE
sp_BlitzIndex breaks when columns indexes include characters requiring XML encoding (e.g. ampersand)

### ISSUE THREAD

**Issue by snckirkmarken** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2734]
**Version of the script**
sp_BlitzIndex(TM) v7.99999 - December 11, 2020

**What is the current behavior?**
Breaks with error message

**If the current behavior is a bug, please provide the steps to reproduce.**
Run sp_BlitzIndex on a database where one of the tables in `sys.dm_db_missing_index_details` has an entry in with an ampersand in the name in `included_columns`.

**What is the expected behavior?**
sp_BlitzIndex results.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server Enterprise Edition 2016, Windows Server 2012. Yes this did work in previous versions. First noticed the issue in August this year, but may have been broken beforehand.

**Comment by BrentOzar** [comment]
Oh interesting. You actually have a column name with an ampersand in it?

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by snckirkmarken** [comment]
Yeah... legacy databases FTW! Pull request coming in a moment courtesy of help from @alihacks...

**Comment by snckirkmarken** [comment]
Not familiar enough with GitHub to know whether I can link PRs to Issues myself, so linking in a comment here: #2735

**Comment by BrentOzar** [comment]
Nice work! And my condolences for having to deal with a database structure like that, hahaha. Merging into the dev branch, will be in the January release with credit to you in the release notes.
