### ISSUE TITLE
What about multiple AG on a 3 node setup?

### ISSUE THREAD

**Issue by ekelmans** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2736]
Will this centralized backup storage info approach work if you have a 3 node server HA/DR setup with multiple AG's (1 per logical grouping of apps), where the AG's are balanced over the 2 HA nodes?

**Comment by BrentOzar** [comment]
What centralized backup are you talking about? Sorry, not sure what script you’re referring to.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by ekelmans** [comment]
Ah... of course

Sorry about that Bent, I thought it was posting this to a specific sp_BlitzBackups repo, hence the sparseness of my question.

I was talking about the msdb_fake fake DB of which you commented to Ron MacNeil that it should be a part of the AG so it's available on each AG node.  

I was wondering what would happen if there is more than 1 AG, does that mean I have to segment the backups per AG or can several AG's share a single msdb_fake?

**Comment by BrentOzar** [comment]
Gotcha. This is pretty far beyond what the community can design for you quickly for free. For multi-node, multi-AG setups, you're best off hiring a consultant to achieve the monitoring solution that works best for your own needs. Hope that's fair.

**Comment by ekelmans** [comment]
Yup.  Totally fair.  I just wanted to check what the sizing boundaries were for this script.Thanks for the quick responsetheo.Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Brent Ozar <notifications@github.com> Datum: 03-01-2021  00:41  (GMT+01:00) Aan: BrentOzarULTD/SQL-Server-First-Responder-Kit <SQL-Server-First-Responder-Kit@noreply.github.com> Cc: Theo Ekelmans <theo@ekelmans.com>, Author <author@noreply.github.com> Onderwerp: Re: [BrentOzarULTD/SQL-Server-First-Responder-Kit] What about multiple AG on a 3 node setup? (#2736) 
Gotcha. This is pretty far beyond what the community can design for you quickly for free. For multi-node, multi-AG setups, you're best off hiring a consultant to achieve the monitoring solution that works best for your own needs. Hope that's fair.
