### ISSUE TITLE
sp_ineachdb - Case sensitivity error -  CTE called "F"

### ISSUE THREAD

**Issue by jeffchulg** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2737]
**Version of the script**
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.
20201211

**What is the current behavior?**

Error in case sensitive environment

**If the current behavior is a bug, please provide the steps to reproduce.**

try to install the procedure in a case sensitive database/instance

**What is the expected behavior?**

no error on procedure installation 

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
only tried on 2016

Resolution:

F
AS (SELECT C.SrcList
         , IIF(C.Quoted = 0
                ,SUBSTRING(C.**N**ame, PATINDEX(@NoSpaces, **N**ame), DATALENGTH (**N**ame)/2 - PATINDEX(@NoSpaces, **N**ame) - PATINDEX(@NoSpaces, REVERSE(**N**ame))+2)
             , C.Name) 
 AS name

**Comment by sm8680** [comment]
Hi Jeff,

  This also breaks on SQL Server 2008 and 2008R2 due to the IIF statement being introduced in SQL Server 2012.  Now I know alot of us including myself would only like to have the latest 3 versions of SQL Server in production.  However for large organizations that's not always the case and unfortunately in those cases we have versions of SQL Server that aren't supported.

Thanks
Steven

**Comment by BrentOzar** [comment]
@sm8680 let's keep issues focused on just one thing - if you run into a separate problem, go ahead and start a separate issue. Thanks!

**Comment by BrentOzar** [comment]
@jeffchulg sorry about that! I don't actually have any case sensitive instances around, so I took a quick stab at a fix using your text, but it's literally just a guess. If it still doesn't work, can you submit a pull request with the changes you want? Thanks!

**Comment by sm8680** [comment]
I did a pull request for Jeff.
