### ISSUE TITLE
sp_BlitzFirst - statistics update insert fails, possibly related to special characters in database schema

### ISSUE THREAD

**Issue by jeffchulg** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2738]
**Version of the script**
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.
20201211 

**What is the current behavior?**

On SQL Server 2016+, I get following errors:
```

Running Check #044
Msg 120, Level 15, State 1, Line 34
The select list for the INSERT statement contains fewer items than the insert list. The number of SELECT values must match the number of INSERT columns.
Msg 120, Level 15, State 1, Line 34
The select list for the INSERT statement contains fewer items than the insert list. The number of SELECT values must match the number of INSERT columns.
Msg 120, Level 15, State 1, Line 34
The select list for the INSERT statement contains fewer items than the insert list. The number of SELECT values must match the number of INSERT columns.
Msg 120, Level 15, State 1, Line 34
The select list for the INSERT statement contains fewer items than the insert list. The number of SELECT values must match the number of INSERT columns.
Msg 120, Level 15, State 1, Line 34
The select list for the INSERT statement contains fewer items than the insert list. The number of SELECT values must match the number of INSERT columns.
Msg 120, Level 15, State 1, Line 34
The select list for the INSERT statement contains fewer items than the insert list. The number of SELECT values must match the number of INSERT columns.
Msg 120, Level 15, State 1, Line 34
The select list for the INSERT statement contains fewer items than the insert list. The number of SELECT values must match the number of INSERT columns.
Msg 120, Level 15, State 1, Line 34
The select list for the INSERT statement contains fewer items than the insert list. The number of SELECT values must match the number of INSERT columns.
Msg 120, Level 15, State 1, Line 34
The select list for the INSERT statement contains fewer items than the insert list. The number of SELECT values must match the number of INSERT columns.
Msg 120, Level 15, State 1, Line 34
The select list for the INSERT statement contains fewer items than the insert list. The number of SELECT values must match the number of INSERT columns.
Msg 120, Level 15, State 1, Line 34
The select list for the INSERT statement contains fewer items than the insert list. The number of SELECT values must match the number of INSERT columns.
Msg 120, Level 15, State 1, Line 34
The select list for the INSERT statement contains fewer items than the insert list. The number of SELECT values must match the number of INSERT columns.
Msg 120, Level 15, State 1, Line 34
The select list for the INSERT statement contains fewer items than the insert list. The number of SELECT values must match the number of INSERT columns.
```
After adding some debug commands (when @Debug = 1 then print which check is running) and check for changes made with previous version, I found out that check # 44 was in doubt.

I commented the dynamic sql section and it worked without error.

**If the current behavior is a bug, please provide the steps to reproduce.**

Run on a SQL Server 2016+ version.

The in-doubt section is:
```

EXEC sp_MSforeachdb N'USE [?];
            SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SET LOCK_TIMEOUT 1000;
            BEGIN TRY
                INSERT INTO #UpdatedStats(HowToStopIt, RowsForSorting)
                SELECT HowToStopIt = 
                            QUOTENAME(DB_NAME()) + N''.'' +
                            QUOTENAME(SCHEMA_NAME(obj.schema_id)) + N''.'' +
                            QUOTENAME(obj.name) +
                            N'' statistic '' + QUOTENAME(stat.name) + 
                            N'' was updated on '' + CONVERT(NVARCHAR(50), sp.last_updated, 121) + N'','' + 
                            N'' had '' + CAST(sp.rows AS NVARCHAR(50)) + N'' rows, with '' +
                            CAST(sp.rows_sampled AS NVARCHAR(50)) + N'' rows sampled,'' +  
                            N'' producing '' + CAST(sp.steps AS NVARCHAR(50)) + N'' steps in the histogram.'',
                    sp.rows
                FROM sys.objects AS obj WITH (NOLOCK)
                INNER JOIN sys.stats AS stat WITH (NOLOCK) ON stat.object_id = obj.object_id  
                CROSS APPLY sys.dm_db_stats_properties(stat.object_id, stat.stats_id) AS sp  
                WHERE sp.last_updated > DATEADD(MI, -15, GETDATE())
                AND obj.is_ms_shipped = 0
                AND ''[?]'' <> ''[tempdb]'';
            END TRY
            BEGIN CATCH
                IF (ERROR_NUMBER() = 1222)
                BEGIN 
                    INSERT INTO #UpdatedStats(HowToStopIt, RowsForSorting)
                    SELECT HowToStopIt = 
                                QUOTENAME(DB_NAME()) +
                                N'' No information could be retrieved as the lock timeout was exceeded,''+
                                N''  this is likely due to an Index operation in Progress'',
                        -1
                END
                ELSE
                BEGIN
                    INSERT INTO #UpdatedStats(HowToStopIt, RowsForSorting)
                    SELECT HowToStopIt = 
                                QUOTENAME(DB_NAME()) +
                                N'' No information could be retrieved as a result of error: ''+
                                CAST(ERROR_NUMBER() AS NVARCHAR(10)) +
                                N'' with message: ''+
                                CAST(ERROR_MESSAGE() AS NVARCHAR(128)),
                        -1
                END
            END CATCH';
```
may be either a quoting error ??

**What is the expected behavior?**

No error message displayed.
Successful check 44 execution.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Checked and worked on SQL Server 2014
Checked and worked with error on SQL Server 2016 and 2019.

**Comment by Adedba** [comment]
I executed sp_BlitzFirst and cannot seem to replicate this using SQL 2016 (13.0.5698.0) . I took the code from the check and popped it into a test script to test the Try block, and both of the code blocks within the catch block and could not get it to error as you have.

Below is the code I used for isolated testing, if you were to run the same code I would expect you to receive the error if the issue is indeed with this check.

This code will execute the check 3 times, once for the code in the Try block and once for each block in the catch so that all three inserts are executed and populate the Results temp table, you should see results for all 3 outcomes e.g.

[Databsename] statistic [_WA_Sys_00000007_46E78A0C] was updated on 2021-01-07 01:18:01.7066667, had 50 rows, with 50 rows sampled, producing 1 steps in the histogram.

[Databsename] No information could be retrieved as the lock timeout was exceeded,  this is likely due to an Index operation in Progress

[Databsename] No information could be retrieved as a result of error: 50000 with message: Forcing an error

Here is the code I extracted and adapted to test all three scenarios: 

`
		IF OBJECT_ID('tempdb..#UpdatedStats') IS NOT NULL
        DROP TABLE #UpdatedStats;	
		CREATE TABLE #UpdatedStats (HowToStopIt NVARCHAR(4000), RowsForSorting BIGINT);
		
		IF OBJECT_ID('tempdb..#BlitzFirstResults') IS NOT NULL
        DROP TABLE #BlitzFirstResults;

		CREATE TABLE #BlitzFirstResults
        (
          ID INT IDENTITY(1, 1) PRIMARY KEY CLUSTERED,
          CheckID INT NOT NULL,
          Priority TINYINT NOT NULL,
          FindingsGroup VARCHAR(50) NOT NULL,
          Finding VARCHAR(200) NOT NULL,
          URL VARCHAR(200) NULL,
          Details NVARCHAR(MAX) NULL,
          HowToStopIt NVARCHAR(MAX) NULL,
          QueryPlan [XML] NULL,
          QueryText NVARCHAR(MAX) NULL,
          StartTime DATETIMEOFFSET NULL,
          LoginName NVARCHAR(128) NULL,
          NTUserName NVARCHAR(128) NULL,
          OriginalLoginName NVARCHAR(128) NULL,
          ProgramName NVARCHAR(128) NULL,
          HostName NVARCHAR(128) NULL,
          DatabaseID INT NULL,
          DatabaseName NVARCHAR(128) NULL,
          OpenTransactionCount INT NULL,
          QueryStatsNowID INT NULL,
          QueryStatsFirstID INT NULL,
          PlanHandle VARBINARY(64) NULL,
          DetailsInt INT NULL,
          QueryHash BINARY(8)
        );

		TRUNCATE TABLE #UpdatedStats;

		/* execute the insert inside the Try */
		IF (1=1)
		BEGIN
		EXEC sp_MSforeachdb N'USE [?];
			SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SET LOCK_TIMEOUT 1000;
			BEGIN TRY
				INSERT INTO #UpdatedStats(HowToStopIt, RowsForSorting)
				SELECT HowToStopIt = 
							QUOTENAME(DB_NAME()) + N''.'' +
							QUOTENAME(SCHEMA_NAME(obj.schema_id)) + N''.'' +
							QUOTENAME(obj.name) +
							N'' statistic '' + QUOTENAME(stat.name) + 
							N'' was updated on '' + CONVERT(NVARCHAR(50), sp.last_updated, 121) + N'','' + 
							N'' had '' + CAST(sp.rows AS NVARCHAR(50)) + N'' rows, with '' +
							CAST(sp.rows_sampled AS NVARCHAR(50)) + N'' rows sampled,'' +  
							N'' producing '' + CAST(sp.steps AS NVARCHAR(50)) + N'' steps in the histogram.'',
					sp.rows
				FROM sys.objects AS obj WITH (NOLOCK)
				INNER JOIN sys.stats AS stat WITH (NOLOCK) ON stat.object_id = obj.object_id  
				CROSS APPLY sys.dm_db_stats_properties(stat.object_id, stat.stats_id) AS sp  
				WHERE sp.last_updated > DATEADD(MI, -15, GETDATE())
				AND obj.is_ms_shipped = 0
				AND ''[?]'' <> ''[tempdb]'';
			END TRY
			BEGIN CATCH
				IF (ERROR_NUMBER() = 1222)
				BEGIN 
					INSERT INTO #UpdatedStats(HowToStopIt, RowsForSorting)
					SELECT HowToStopIt = 
								QUOTENAME(DB_NAME()) +
							    N'' No information could be retrieved as the lock timeout was exceeded,''+
								N''  this is likely due to an Index operation in Progress'',
						-1
				END
				ELSE
				BEGIN
					INSERT INTO #UpdatedStats(HowToStopIt, RowsForSorting)
					SELECT HowToStopIt = 
								QUOTENAME(DB_NAME()) +
							    N'' No information could be retrieved as a result of error: ''+
								CAST(ERROR_NUMBER() AS NVARCHAR(10)) +
								N'' with message: ''+
								CAST(ERROR_MESSAGE() AS NVARCHAR(128)),
						-1
				END
			END CATCH';
		END

		/* Force an error (RAISERROR(''Forcing an error'',11,0);) and force the error 1222 block in the catch by replacing IF (ERROR_NUMBER() = 1222) with IF (1222 = 1222)*/
		IF (1=1)
		BEGIN
		EXEC sp_MSforeachdb N'USE [?];
			SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SET LOCK_TIMEOUT 1000;
			BEGIN TRY
				RAISERROR(''Forcing an error'',11,0);
				INSERT INTO #UpdatedStats(HowToStopIt, RowsForSorting)
				SELECT HowToStopIt = 
							QUOTENAME(DB_NAME()) + N''.'' +
							QUOTENAME(SCHEMA_NAME(obj.schema_id)) + N''.'' +
							QUOTENAME(obj.name) +
							N'' statistic '' + QUOTENAME(stat.name) + 
							N'' was updated on '' + CONVERT(NVARCHAR(50), sp.last_updated, 121) + N'','' + 
							N'' had '' + CAST(sp.rows AS NVARCHAR(50)) + N'' rows, with '' +
							CAST(sp.rows_sampled AS NVARCHAR(50)) + N'' rows sampled,'' +  
							N'' producing '' + CAST(sp.steps AS NVARCHAR(50)) + N'' steps in the histogram.'',
					sp.rows
				FROM sys.objects AS obj WITH (NOLOCK)
				INNER JOIN sys.stats AS stat WITH (NOLOCK) ON stat.object_id = obj.object_id  
				CROSS APPLY sys.dm_db_stats_properties(stat.object_id, stat.stats_id) AS sp  
				WHERE sp.last_updated > DATEADD(MI, -15, GETDATE())
				AND obj.is_ms_shipped = 0
				AND ''[?]'' <> ''[tempdb]'';
			END TRY
			BEGIN CATCH
				IF (1222 = 1222)
				BEGIN 
					INSERT INTO #UpdatedStats(HowToStopIt, RowsForSorting)
					SELECT HowToStopIt = 
								QUOTENAME(DB_NAME()) +
							    N'' No information could be retrieved as the lock timeout was exceeded,''+
								N''  this is likely due to an Index operation in Progress'',
						-1
				END
				ELSE
				BEGIN
					INSERT INTO #UpdatedStats(HowToStopIt, RowsForSorting)
					SELECT HowToStopIt = 
								QUOTENAME(DB_NAME()) +
							    N'' No information could be retrieved as a result of error: ''+
								CAST(ERROR_NUMBER() AS NVARCHAR(10)) +
								N'' with message: ''+
								CAST(ERROR_MESSAGE() AS NVARCHAR(128)),
						-1
				END
			END CATCH';
		END;

		/* Force an error (RAISERROR(''Forcing an error'',11,0);) and force execution of the else block in the catch replacing IF (ERROR_NUMBER() = 1222) with IF (1 = 1222)*/
		IF (1=1)
		BEGIN
		EXEC sp_MSforeachdb N'USE [?];
			SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SET LOCK_TIMEOUT 1000;
			BEGIN TRY
				RAISERROR(''Forcing an error'',11,0);
				INSERT INTO #UpdatedStats(HowToStopIt, RowsForSorting)
				SELECT HowToStopIt = 
							QUOTENAME(DB_NAME()) + N''.'' +
							QUOTENAME(SCHEMA_NAME(obj.schema_id)) + N''.'' +
							QUOTENAME(obj.name) +
							N'' statistic '' + QUOTENAME(stat.name) + 
							N'' was updated on '' + CONVERT(NVARCHAR(50), sp.last_updated, 121) + N'','' + 
							N'' had '' + CAST(sp.rows AS NVARCHAR(50)) + N'' rows, with '' +
							CAST(sp.rows_sampled AS NVARCHAR(50)) + N'' rows sampled,'' +  
							N'' producing '' + CAST(sp.steps AS NVARCHAR(50)) + N'' steps in the histogram.'',
					sp.rows
				FROM sys.objects AS obj WITH (NOLOCK)
				INNER JOIN sys.stats AS stat WITH (NOLOCK) ON stat.object_id = obj.object_id  
				CROSS APPLY sys.dm_db_stats_properties(stat.object_id, stat.stats_id) AS sp  
				WHERE sp.last_updated > DATEADD(MI, -15, GETDATE())
				AND obj.is_ms_shipped = 0
				AND ''[?]'' <> ''[tempdb]'';
			END TRY
			BEGIN CATCH
				IF (1 = 1222)
				BEGIN 
					INSERT INTO #UpdatedStats(HowToStopIt, RowsForSorting)
					SELECT HowToStopIt = 
								QUOTENAME(DB_NAME()) +
							    N'' No information could be retrieved as the lock timeout was exceeded,''+
								N''  this is likely due to an Index operation in Progress'',
						-1
				END
				ELSE
				BEGIN
					INSERT INTO #UpdatedStats(HowToStopIt, RowsForSorting)
					SELECT HowToStopIt = 
								QUOTENAME(DB_NAME()) +
							    N'' No information could be retrieved as a result of error: ''+
								CAST(ERROR_NUMBER() AS NVARCHAR(10)) +
								N'' with message: ''+
								CAST(ERROR_MESSAGE() AS NVARCHAR(128)),
						-1
				END
			END CATCH';
		END;
		
		/* We mark timeout exceeded with a -1 so only show these IF there is statistics info that succeeded */
		IF EXISTS (SELECT * FROM #UpdatedStats WHERE RowsForSorting > -1)
			INSERT INTO #BlitzFirstResults (CheckID, Priority, FindingsGroup, Finding, URL, Details, HowToStopIt)
			SELECT 44 AS CheckId,
					50 AS Priority,
					'Query Problems' AS FindingGroup,
					'Statistics Updated Recently' AS Finding,
					'http://www.BrentOzar.com/go/stats' AS URL,
					'In the last 15 minutes, statistics were updated. To see which ones, click the HowToStopIt column.' + Char(10)+Char(13) + Char(10)+Char(13)
						+ 'This effectively clears the plan cache for queries that involve these tables,' + Char(10)+Char(13)
						+ 'which thereby causes parameter sniffing: those queries are now getting brand new' + Char(10)+Char(13)
						+ 'query plans based on whatever parameters happen to call them next.' + Char(10)+Char(13) + Char(10)+Char(13)
						+ 'Be on the lookout for sudden parameter sniffing issues after this time range.',
					HowToStopIt = (SELECT (SELECT HowToStopIt + NCHAR(10))
						FROM #UpdatedStats
						ORDER BY RowsForSorting DESC
						FOR XML PATH(''));


						SELECT * FROM #UpdatedStats;

`

Are you able to provide the Exact command you are using to execute sp_BlitzFirst which produces the error?

**Comment by jeffchulg** [comment]
Unfortunately, I don't invent it...
![image](https://user-images.githubusercontent.com/1788348/103859185-e40a8a80-50b9-11eb-913b-cd5bac7297f6.png)

My test SQL Server version is: 

Microsoft SQL Server 2016 (SP1-CU7-GDR) (KB4057119) - 13.0.4466.4 (X64) 

However, the code you provided did not raise the error....

**Comment by BrentOzar** [comment]
@jeffchulg yeah, my guess - and this is just a guess - is that you've got a special character somewhere in a database, schema, or statistic name. I don't have an easy way to track that down here, but if you make progress, let us know and we can dig into it.

**Comment by jeffchulg** [comment]
Well, it's ok now... the issue was during the (automated) unzipping process.. The file was converted from UTF8 to UTF8 with BOM... 

I don't know why the error appears just at that particular check ...

**Comment by BrentOzar** [comment]
Oh wow, that's awesome! That's funny, I was just helping someone troubleshoot a failed download the other day. "Helper" utilities can be a little too ambitious sometimes, heh.

**Comment by jeffchulg** [comment]
Hi Brent, 
I was a little bit too confident on my discovery... 
Would it be possible to make following change ? (Replacing direct call to a string creation then execution)

```
SET @StringToExecute =  'USE [?];' + @LineFeed +
                                    'SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SET LOCK_TIMEOUT 1000;' + @LineFeed +
                                    'BEGIN TRY' + @LineFeed +
                                    '    INSERT INTO #UpdatedStats(HowToStopIt, RowsForSorting)' + @LineFeed +
                                    '    SELECT HowToStopIt = ' + @LineFeed +
                                    '                QUOTENAME(DB_NAME()) + N''.'' +' + @LineFeed +
                                    '                QUOTENAME(SCHEMA_NAME(obj.schema_id)) + N''.'' +' + @LineFeed +
                                    '                QUOTENAME(obj.name) +' + @LineFeed +
                                    '                N'' statistic '' + QUOTENAME(stat.name) + ' + @LineFeed +
                                    '                N'' was updated on '' + CONVERT(NVARCHAR(50), sp.last_updated, 121) + N'','' + ' + @LineFeed +
                                    '                N'' had '' + CAST(sp.rows AS NVARCHAR(50)) + N'' rows, with '' +' + @LineFeed +
                                    '                CAST(sp.rows_sampled AS NVARCHAR(50)) + N'' rows sampled,'' +  ' + @LineFeed +
                                    '                N'' producing '' + CAST(sp.steps AS NVARCHAR(50)) + N'' steps in the histogram.'',' + @LineFeed +
                                    '        sp.rows' + @LineFeed +
                                    '    FROM sys.objects AS obj WITH (NOLOCK)' + @LineFeed +
                                    '    INNER JOIN sys.stats AS stat WITH (NOLOCK) ON stat.object_id = obj.object_id  ' + @LineFeed +
                                    '    CROSS APPLY sys.dm_db_stats_properties(stat.object_id, stat.stats_id) AS sp  ' + @LineFeed +
                                    '    WHERE sp.last_updated > DATEADD(MI, -15, GETDATE())' + @LineFeed +
                                    '    AND obj.is_ms_shipped = 0' + @LineFeed +
                                    '    AND ''[?]'' <> ''[tempdb]'';' + @LineFeed +
                                    'END TRY' + @LineFeed +
                                    'BEGIN CATCH' + @LineFeed +
                                    '    IF (ERROR_NUMBER() = 1222)' + @LineFeed +
                                    '    BEGIN ' + @LineFeed +
                                    '        INSERT INTO #UpdatedStats(HowToStopIt, RowsForSorting)' + @LineFeed +
                                    '        SELECT HowToStopIt = ' + @LineFeed +
                                    '                    QUOTENAME(DB_NAME()) +' + @LineFeed +
                                    '                    N'' No information could be retrieved as the lock timeout was exceeded,''+' + @LineFeed +
                                    '                    N''  this is likely due to an Index operation in Progress'',' + @LineFeed +
                                    '            -1' + @LineFeed +
                                    '    END' + @LineFeed +
                                    '    ELSE' + @LineFeed +
                                    '    BEGIN' + @LineFeed +
                                    '        INSERT INTO #UpdatedStats(HowToStopIt, RowsForSorting)' + @LineFeed +
                                    '        SELECT HowToStopIt = ' + @LineFeed +
                                    '                    QUOTENAME(DB_NAME()) +' + @LineFeed +
                                    '                    N'' No information could be retrieved as a result of error: ''+' + @LineFeed +
                                    '                    CAST(ERROR_NUMBER() AS NVARCHAR(10)) +' + @LineFeed +
                                    '                    N'' with message: ''+' + @LineFeed +
                                    '                    CAST(ERROR_MESSAGE() AS NVARCHAR(128)),' + @LineFeed +
                                    '            -1' + @LineFeed +
                                    '    END' + @LineFeed +
                                    'END CATCH'                          
                                    ;
            EXEC sp_MSforeachdb @StringToExecute;
```

This way, I don't get any error...

**Comment by BrentOzar** [comment]
Can you do a pull request please? Thanks!

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by BrentOzar** [comment]
Thanks for the pull request! Merged into the dev branch, will be in the March release with credit to you.
