### ISSUE TITLE
sp_BlitzLock throws error when running

### ISSUE THREAD

**Issue by gortok** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2749]
**Version of the script**
Version: 7.99999
Date: 20201211

**What is the current behavior?**

When running sp_blitzLock with the following parameters; I get an error in the messages saying
```
Msg 2714, Level 16, State 8, Line 5
There is already an object named 'DeadLockFindings' in the database.
Msg 2714, Level 16, State 8, Line 5
There is already an object named 'DeadLockTbl' in the database.
Grab the inital set of XML to parse at Jane 2021 3:35:08:343pm
<snip>...</snip>
Results 1 Jan 12 2021 3:35:08:487PM
Msg 208, LEvel 16, State 1, Procedure sp_BlitzLock, Line 1261 [Batch Start Line 4]
Invalid object name 'DeadLockTbl'.

Completion time: 2021-01-12T15:35:08.5049956-5:00
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I ran sp_blitzLock with:
```
exec sp_blitzLock @OutputTableName='spBlitzLockTable', @OutputSchemaName='dbo', @OutputDatabaseName='MyDb'
```

**What is the expected behavior?**

Expected behavior is that there are no errors.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

I've never run sp_blitzLock before so I don't know the answer; this was run on SQL Server 2016:

```
Microsoft SQL Server 2016 (SP2-GDR) (KB4505220) - 13.0.5101.9 (X64)
```

**Comment by BrentOzar** [comment]
Howdy sir. My guess - and this is just a guess - is that you've got a bad install of sp_BlitzLock, like maybe there was an error during copy/pasting it into SSMS. Can you re-download and re-install it?

**Comment by gortok** [comment]
@BrentOzar Looking again, the scripts were installed into the "Master" database but run against "MyDB".  I think that is what caused the problem. When I dropped them from Master and recreated them in "MyDB" they seemed to work without error.
