### ISSUE TITLE
sp_Blitz isn't formatting the Poison waits correctly

### ISSUE THREAD

**Issue by TaraKizer** [BrentOzarULTD/SQL-Server-First-Responder-Kit#275]
sp_Blitz says there's 000:03:57.8400000 of these waits for a client. 20_waitstats_all says there are 660 total hours of it. sp_Blitz should reflect the same amount, probably just a formatting issue.

**Comment by BlitzErik** [comment]
Yep, fixed earlier this week. Tara tested with client.
