### ISSUE TITLE
sp_Blitz - Offline databases show up in auto-shrink and page verification checks

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2750]
**Version of the script**
Latest in main

**What is the current behavior?**
Offline databases appear in checks when they probably should get ignored

**If the current behavior is a bug, please provide the steps to reproduce.**
Set a database offline with these settings and Blitz will list it

**What is the expected behavior?**
Ignore offline databases

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All!

**Comment by BrentOzar** [comment]
Looks good! Thanks for the pull request, merging into the dev branch, will be in the January release with credit to you in the release notes.
