### ISSUE TITLE
Install-All-Scripts fails missing object dbo.SqlServerVersions'

### ISSUE THREAD

**Issue by TLSystemsLLC** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2753]
**Version of the script**
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.
Version Date:  20201211

**What is the current behavior?**
On a new SQL server installation the script fails with missing object SqlServerVersions:

The module 'sp_AllNightLog' depends on the missing object 'master.dbo.sp_DatabaseRestore'. The module will still be created; however, it cannot run successfully until the object exists.
The module 'sp_AllNightLog' depends on the missing object 'master.dbo.sp_DatabaseRestore'. The module will still be created; however, it cannot run successfully until the object exists.
The module 'sp_BlitzFirst' depends on the missing object 'sp_BlitzWho'. The module will still be created; however, it cannot run successfully until the object exists.
Msg 208, Level 16, State 1, Line 41603
Invalid object name 'dbo.SqlServerVersions'.

**If the current behavior is a bug, please provide the steps to reproduce.**
Run Uninstall.sql, then run Install-All-Scripts.sql

**What is the expected behavior?**
Run without error.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Microsoft SQL Server 2019 (RTM-CU8-GDR) (KB4583459) - 15.0.4083.2

**Comment by BrentOzar** [comment]
Ooo! Good catch. The root cause is a missing GO before this:

IF (OBJECT_ID('dbo.SqlServerVersions') IS NULL)

**Comment by BrentOzar** [comment]
Hilariously, the root cause on this was that in last month's release, one of the checkins removed the GO from the end of sp_ineachdb. When the scripts were all assembled into one, that's where it failed.

The dev branch now has the GO in the end of sp_ineachdb, and when January's installation scripts are created, the updated Install-All-Scripts.sql will work.
