### ISSUE TITLE
@OutputTableRetentionDays is not applied for BlitzWho when saving BlitzFirst results to table

### ISSUE THREAD

**Issue by EmanueleMeazzo** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2758]
**Version of the script**
20210117

**What is the current behavior?**
When using BlitzFirst to store its data in a Database, the @OutputTableRetentionDays  parameter is supposed to define the retention days for the data saved by this procedure call:

EXEC sp_BlitzFirst
  @OutputDatabaseName = 'DBAtools'
, @OutputSchemaName = 'dbo'
, @OutputTableName = 'BlitzFirst'
, @OutputTableNameFileStats = 'BlitzFirst_FileStats'
, @OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats'
, @OutputTableNameWaitStats = 'BlitzFirst_WaitStats'
, @OutputTableNameBlitzCache = 'BlitzCache'
, @OutputTableNameBlitzWho = 'BlitzWho'
, @OutputTableRetentionDays = 30

However, the parameter @OutputTableRetentionDays isn't passed down to BlitzWho (that makes its table writing independently), and hence the default 3 days retention policy for BlitzWho is applied on the @OutputTableNameBlitzWho  table

**If the current behavior is a bug, please provide the steps to reproduce.**
Execute the query above for more than 3 days straight, and on the 4th you'll lose the data from the 1st day, only for the @OutputTableNameBlitzWho table

**What is the expected behavior?**
The retention days for the **all** data saved in this procedure should be coherent with the parameter provided

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All of them

**How do you want to fix it?**
At line 1390 change from:
`EXEC sp_BlitzWho @OutputDatabaseName = @UnquotedOutputDatabaseName, @OutputSchemaName = @UnquotedOutputSchemaName, @OutputTableName = @OutputTableNameBlitzWho, @CheckDateOverride = @StartSampleTime;`

To:
`EXEC sp_BlitzWho @OutputDatabaseName = @UnquotedOutputDatabaseName, @OutputSchemaName = @UnquotedOutputSchemaName, @OutputTableName = @OutputTableNameBlitzWho, @CheckDateOverride = @StartSampleTime, @OutputTableRetentionDays = @OutputTableRetentionDays;`

**Comment by BrentOzar** [comment]
Thanks for the pull request! Good catch. Merging into the dev branch, and will be in the February release with credit to you in the release notes.
