### ISSUE TITLE
sp_Blitz: adding new checks for sp_configure "Best Practices"

### ISSUE THREAD

**Issue by ToddChitt** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2764]
There are a few sp_Blitz checks that look at server defaults, things like Max Server Memory (1031), Database Mail XP's (1072), and Backup Compression (1073) to name a few. where the DEFAULT setting is NOT the BEST PRACTICE setting. 

If and when we CHANGE these settings from their respective DEFAULT values, we get sp_Blitz result row stating such. But it is actually beneficial to make these configuration changes. 

Let's take a single example: Backup Compression (Check ID #1073). 
* The DEFAULT setting is OFF. 
* The BEST PRACTICE is ON 

Assuming we are NOT using a BlitzChecksToSkip table, then you will always get a message about this setting. There is no way to NOT get a result line. 
For the former, Check ID #116 will tell you that "Backup Compression Default Off" 
For the latter, Check ID #1073 will tell you "Non Default server configuration"
(I may not have all the details right as this one may depend on actual backups taken? not sure)

Seems the best way to deal with these types of checks, where the DEFAULT <> BEST PRACTICE is by placing the Findings higher or lower on the Priority scale:

If the setting is at the DEFAULT value, place it under the appropriate Group. 
But if the setting is at the BEST PRACTICE value, place it in the 250/Server Info group, or a new Group at Priority 250: Best Practices. 

For this one in particular, I would set the Findings as  250 / Best Practices / Backup Compression is ON"
Kind of lets the user know they have done a good job adhering to best practices.

Yes, I know I can always extend my BlitxChecksToSkip table to skip over this one item, and I have done so. Just seems there are a few that are in this category.

Not sure how I would attack this. Probably have to take it on a case by case basis for each Check ID that deals with Defaults.

It's fairly easy to make a determination on these server defaults where it is either ON or OFF, 1 or 0. It gets a little more complicated when there is a value along a continuum, like Cost Threshold for Parallelism or Max DOP, and even harder still for MAX Server Memory where the 'best practice' is dependent on the installed memory.

This is my starting list of items from sys.configurations that I would change:
Agent XP's has DEFAULT of 0, BP = 1
Database Mail XP's has default = 0, BP = 1
Backup Compression has default = 0, BP = 1

If you can expand my short list above based on your knowledge, maybe give suggestions or guidance on how you might deal with CTFP or MaxDOP or Max Server Memory, I will give it a shot. Oh, and I'm bound and determined to figure out GitHub if it kills me :). It's ubiquitous enough that it's almost a required skill for developers these days.

Thanks again.

**Comment by BrentOzar** [comment]
Yes, we're already doing that for backup compression (check 116) and Cost Threshold and MAXDOP (check 188). Do a search in sp_Blitz for those numbers to see how those checks work.

If you want to add others, check to make sure we're not already checking them, then add to this issue:
* The setting you want to check
* The setting you want
* How you want to make sure they actually need the setting (for example, with backup compression, we're checking to see if they've had uncompressed backups - they don't need the setting if they're already handling it in their backup jobs.)

**Comment by ToddChitt** [comment]
I think you're not understanding my suggestion here. I love your analogy of the pilot and the dog. It's a great story to illustrate the fact that you shouldn't mess with SQL defaults unless you know what you're doing. And when you DO, sp_Blitz is going to report that fact under a Findings Group of "Non-Default Server Config".

BUT, there are certain (fringe) cases where a "Non-Default Server Config" is actually desirable, as is the case for the Dedicated Admin Connection. Check ID #100 informs the reader that the DAC is NOT enabled. Fine. But then after you enable it, Check ID #1049 reports "Non-Default Server Config" 

Those "Non-Default Server Config" findings make the German Shepherd in the cockpit start growling at me because my hand is on a knob or switch! The un-trained may think, "Oh, my, I better put this back!"

We need to train the dog that in certain cases, the pilot SHOULD flip that switch!

My suggestion is that for these fringe cases where it is actually ADVISABLE or BEST PRACTICE to change the out-of-the-box settings, that the Findings reflect this. 

The suggestion, then, is that CheckID 1049 (DAC enabled) should have the following findings:
Priority: 250
Findings Group: Best Practices
Finding:   Dedicated Admin Connection is ENABLED
URL:         https://BrentOzar.com/go/dac

I would lump CheckID 1071 (Agent XPs) in this category as well.

Hope that explains it a little better. I'm going to make the changes, test them locally, and submit them. You are always free to say, "Nah, I don't like it."

**Comment by BrentOzar** [comment]
Todd - I hear you, but you're not hearing me. We already ***have*** those for Cost Threshold, MAXDOP, and backup compression. Please read those first and follow those designs if you'd like to add additional checks.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by BrentOzar** [comment]
Just a quick note in case other folks run across this issue - before you code anything on this issue, write up what you want to do in an issue first, and then we'll go from there.

Part of the goal of sp_Blitz is to only return a line in the results when an action needs to be taken. Let's not return additional output that says "things are good" - just only warn 'em if they need to take an action, or if there's an extra line item in sp_Blitz that you want to suppress because no action needs to be taken, that would be a good issue to add too. Thanks!
