### ISSUE TITLE
Add support for Output* in sp_BlitzIndex for mode 0, 1, 3, 4 

### ISSUE THREAD

**Issue by torerikh** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2774]
**Is your feature request related to a problem? Please describe.**
Currently only mode=2 is supported by the Output* parameters

**Describe the solution you'd like**
Suggestion is to add support for the remaning modes (0,1,3,4)

**Describe alternatives you've considered**
N/A

**Are you ready to build the code for the feature?**
Yes, I'm prepared to provide this improvement, but would appreciate some assistance in testing on the various versions of SQL.

**Comment by BrentOzar** [comment]
Sure, sounds like a good pull request we'd love to get. The easiest way to make sure that complex code like this will work is to test it in a case-sensitive database with 2008 compatibility level.

**Comment by torerikh** [comment]
@BrentOzar Is it intentional that the code is splinkled with dsql and output duplication when it comes to output* and proc results. I was wondering of the possibility to store results to temp tables instead so it's possible to use as source for both output* and proc results. Any toughts?

**Comment by BrentOzar** [comment]
I don't have the time to dig into it myself, my apologies - I would just try to make the least changes possible to get the result that you want, keeping in mind that other volunteer community members will have to review and test your code. The least burden you can put on them, the better. Hope that helps!

**Comment by BrentOzar** [comment]
@torerikh I'm going to go ahead and close this issue, but if you decide you want to tackle it, just leave a note here and I can reopen the issue. We just tend not to leave open feature requests here if we're not actively working on them. Thanks!

**Comment by torerikh** [comment]
@BrentOzar I finally got to look into this. I now have a first implementation ready, just need to test it a bit before publishing a PR

**Comment by torerikh** [comment]
I also found a call to sp_blitzcache inside mode=3. Not sure if I should add a separate set of output variables for it, or just output an information that in order to catch that information the user has to make a separate call to sp_blitzcache

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good. Merging into the dev branch, will be in the December release with credit to you in the release notes.

Here's how I tested it:

```
sp_BlitzIndex @DatabaseName = 'StackOverflow',
	@OutputDatabaseName = 'DBAtools',
	@OutputSchemaName = 'dbo',
	@OutputTableName = 'BlitzIndex_Mode0',
	@Mode = 0;
GO 2 
/* Twice make sure it also works when the table already exists */
SELECT * FROM DBAtools.dbo.BlitzIndex_Mode0;
GO


EXEC sp_BlitzIndex @DatabaseName = 'StackOverflow',
	@OutputDatabaseName = 'DBAtools',
	@OutputSchemaName = 'dbo',
	@OutputTableName = 'BlitzIndex_Mode1',
	@Mode = 1;
GO 2 
/* Twice make sure it also works when the table already exists */
SELECT * FROM DBAtools.dbo.BlitzIndex_Mode1;
GO

EXEC sp_BlitzIndex @DatabaseName = 'StackOverflow',
	@OutputDatabaseName = 'DBAtools',
	@OutputSchemaName = 'dbo',
	@OutputTableName = 'BlitzIndex_Mode2',
	@Mode = 2;
GO 2 
/* Twice make sure it also works when the table already exists */
SELECT * FROM DBAtools.dbo.BlitzIndex_Mode2;
GO


EXEC sp_BlitzIndex @DatabaseName = 'StackOverflow',
	@OutputDatabaseName = 'DBAtools',
	@OutputSchemaName = 'dbo',
	@OutputTableName = 'BlitzIndex_Mode3',
	@Mode = 3;
GO 2
/* Twice make sure it also works when the table already exists */
SELECT * FROM DBAtools.dbo.BlitzIndex_Mode3;
GO



EXEC sp_BlitzIndex @DatabaseName = 'StackOverflow',
	@OutputDatabaseName = 'DBAtools',
	@OutputSchemaName = 'dbo',
	@OutputTableName = 'BlitzIndex_Mode4',
	@Mode = 4;
GO 2
/* Twice make sure it also works when the table already exists */
SELECT * FROM DBAtools.dbo.BlitzIndex_Mode4;
GO

```
