### ISSUE TITLE
sp_AllNightLog ignores both the @rpo and @rto parameters

### ISSUE THREAD

**Issue by alinselicean** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2775]
Implemented sp_AllNightLog to a customer and discovered that no matter what RPO and RTO was set, the backups were taken at 5 minutes intervals and restores were happening with the same frequency. The required interval was 30 minutes (1800s). The first 2 screenshots are showing the actual settings in place. If needed, I can provide screenshots of the backup and restore frequencies from the CommandLog table.

The last 2 screenshots are showing the lines where we made the changes that helped getting the backup and restores to happen at the set intervals. We replaced the hardcoded value of -5 with the @rpo and @rto variables, respectively.

I hope the details below are enough to help identify the issue. I am not very good with Github, but if I can help in any other way at fixing this, let me know.

Thanks,
Alin Selicean

![image](https://user-images.githubusercontent.com/20295322/105696149-99876b80-5f0b-11eb-8c6e-6277c401ea7c.png)
![image](https://user-images.githubusercontent.com/20295322/105696182-a4420080-5f0b-11eb-8970-1c094f21a697.png)
![image](https://user-images.githubusercontent.com/20295322/105696241-b459e000-5f0b-11eb-9d49-800b01d6e1b2.png)
![image](https://user-images.githubusercontent.com/20295322/105696282-c3d92900-5f0b-11eb-9d26-14bfb34ee847.png)

**Comment by BrentOzar** [comment]
@alinselicean one thing to be careful of - the rpo and rto variables are in seconds, not minutes. In my fix, I also switched the dateadd to use DATEADD(SECOND, (@rpo * -1), GETDATE()) rather than minute.

**Comment by alinselicean** [comment]
Thanks, @BrentOzar. Yes, we figured that one out and fixed that too in our local copy, but screenshots were made before that. Waiting the release.
