### ISSUE TITLE
sp_Blitz: check 68 (CHECKDB) running even when @CheckUserDatabaseObjects = 0

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2779]
**Version of the script**
SELECT @Version = '8.0', @VersionDate = '20210117';

**What is the current behavior?**
If you set @CheckUserDatabaseObjects = 0, check 68 (CHECKDB) still runs, even though it's an sp_MSforeachdb. This is slow for folks who have a lot of databases. Probably need to check for all usage of sp_MSforeachdb outside of the @CheckUserDatabaseObjects = 0 loop.

**Comment by BrentOzar** [comment]
I did a quick check, and this appears to be the only sp_MSforeachdb check that was running when CheckUserDatabaseObjects is set to 0. Fixed.

**Comment by capnsue** [comment]
this rules!
