### ISSUE TITLE
Please add an "Is Clustered" and "Is Unique" field to sp_BlitzIndex

### ISSUE THREAD

**Issue by S-Coutant** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2782]
Please add an "Is Clustered" and "Is Unique" field to sp_BlitzIndex.

**Comment by BrentOzar** [comment]
Check out the CX, PK, UNIQUE, etc info in the Definition columns of sp_BlitzIndex.
![Screen Shot 2021-02-08 at 2 44 53 PM](https://user-images.githubusercontent.com/245462/107235121-425dbc80-6a1c-11eb-8291-9c1d5225c23b.png)
