### ISSUE TITLE
URL typo for CheckID 222 output

### ISSUE THREAD

**Issue by michaelgowan** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2786]
**Version of the script**
  Version 8.0
  VersionDate 20210117

**What is the current behavior?**
  The URL in the output for CheckID 222 has a typo.  The t is missing in BrentOzar.com
  Line 8828 currently has https://www.BrenOzar.com/go/azurevm

**If the current behavior is a bug, please provide the steps to reproduce.**
  Run sp_Blitz against a SQL Server that qualifies for CheckID 222.
  Honestly, this is the first time I've seen this finding and still not sure why my SQL Server qualified.  It's not an Azure VM.

**What is the expected behavior?**
  That the URL produced would be valid.
  It should be https://www.BrentOzar.com/go/azurevm

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
  SQL 2019 on Win 10 Pro
  I'm not sure if this worked before.  This is my first time seeing this finding for CheckID 222.

**Comment by BrentOzar** [comment]
Good catch! Fixed, will be in the Feb release with credit to you in the release notes.

**Comment by michaelgowan** [comment]
LOL No credit! I want my first credit to be for code contribution not grammar police!
