### ISSUE TITLE
sp_Blitz* - Treat "DBATools" like a system database

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2787]
**Is your feature request related to a problem? Please describe.**
In a few scripts, we filter out system databases. This can help avoid seeing/processing irrelevant information.

**Describe the solution you'd like**
Starting with "DBATools", I'd like to go through scripts and add common admin database names (DBAdmin would be another candidate) to the screen out list. 

**Describe alternatives you've considered**
A caboose but backwards and made of jelly.

**Are you ready to build the code for the feature?**
Yes, this will be a FUN WEEKEND ACTIVITY.

For the children.

**Comment by BrentOzar** [comment]
Love it.

**Comment by BrentOzar** [comment]
@Iomckee - Woohoo! Looks good, thanks for making those changes. Merging into the dev branch, will be in the March release with credit to you in the release notes. Nice catch on the documentation, too.

Other readers - this was only implemented on sp_BlitzCache, just FYI.

**Comment by jeffchulg** [comment]
Hi, would it be possible to add a custom comma-separated list as an input to these procedures, in case one database is not listed in the changes above? This could be used as an exclusion list at the same time...

**Comment by erikdarlingdata** [comment]
@jeffchulg there's an `@IgnoreDatabases` parameter to `sp_BlitzIndex` if you want to use that as a template for other procs.

**Comment by jeffchulg** [comment]
> 
> 
> @jeffchulg there's an `@IgnoreDatabases` parameter to `sp_BlitzIndex` if you want to use that as a template for other procs.

Sounds great! :)

**Comment by BrentOzar** [comment]
Thanks for the pull request! Merging into the dev branch, will be in the March release with a shout-out to you in the release notes.
