### ISSUE TITLE
sp_BlitzInMemoryOLTP version should be 8.01

### ISSUE THREAD

**Issue by mdekarske** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2797]
**Version of the script**
V1.8, that's what wrong.

**Comment by BrentOzar** [comment]
That's actually correct. sp_BlitzInMemoryOLTP is hosted in KTaranov's Github repo, not ours. If you want to edit that one, head over there - we pull the changes and just update the release date to match the rest of our scripts. That script hasn't changed in years. Thanks!
