### ISSUE TITLE
sp_BlitzAnalysis Parameters need to be updated in Documentation

### ISSUE THREAD

**Issue by devendra2108** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2798]
**Version of the script**
 @Version = '8.01', @VersionDate = '20210222'

**What is the current behavior?**
Below examples are incorrect

EXEC sp_BlitzAnalysis 
	@FromDate = NULL,
	@ToDate = NULL,	
	@OutputDatabaseName = 'DBAtools',
	@OutputSchemaName = 'dbo',
	@OutputTableNameFileStats = N'BlitzFirst_FileStats',		
	@OutputTableNamePerfmonStats  = N'BlitzFirst_PerfmonStats',		
	@OutputTableNameWaitStats = N'BlitzFirst_WaitStats',		 
	@OutputTableNameBlitzCache = N'BlitzCache',		 
	@OutputTableNameBlitzWho = N'BlitzWho';
Exclude specific tables e.g lets exclude PerfmonStats by setting to NULL, no lookup will occur against the table and a skipped message will appear in the resultset

EXEC sp_BlitzAnalysis 
	@FromDate = NULL,
	@ToDate = NULL,	
	@OutputDatabaseName = 'DBAtools',
	@OutputSchemaName = 'Blitz',
	@OutputTableNameFileStats = N'BlitzFirst_FileStats',		
	@OutputTableNamePerfmonStats  = NULL,		
	@OutputTableNameWaitStats = N'BlitzFirst_WaitStats',		 
	@OutputTableNameBlitzCache = N'BlitzCache',		 
	@OutputTableNameBlitzWho = N'BlitzWho';

**If the current behavior is a bug, please provide the steps to reproduce.**
If you take either of above examples and run you will get an error message

Msg 8145, Level 16, State 1, Procedure sp_BlitzAnalysis, Line 0 [Batch Start Line 0]
@FromDate is not a parameter for procedure sp_BlitzAnalysis.

**What is the expected behavior?**

The above examples should be updated to:

Below examples are incorrect

EXEC sp_BlitzAnalysis 
        @StartDate = NULL, 
	@EndDate = NULL,
	@OutputDatabaseName = 'DBAtools',
	@OutputSchemaName = 'dbo',
	@OutputTableNameFileStats = N'BlitzFirst_FileStats',		
	@OutputTableNamePerfmonStats  = N'BlitzFirst_PerfmonStats',		
	@OutputTableNameWaitStats = N'BlitzFirst_WaitStats',		 
	@OutputTableNameBlitzCache = N'BlitzCache',		 
	@OutputTableNameBlitzWho = N'BlitzWho';
Exclude specific tables e.g lets exclude PerfmonStats by setting to NULL, no lookup will occur against the table and a skipped message will appear in the resultset

EXEC sp_BlitzAnalysis 
        @StartDate = NULL, 
	@EndDate = NULL,
	@OutputDatabaseName = 'DBAtools',
	@OutputSchemaName = 'Blitz',
	@OutputTableNameFileStats = N'BlitzFirst_FileStats',		
	@OutputTableNamePerfmonStats  = NULL,		
	@OutputTableNameWaitStats = N'BlitzFirst_WaitStats',		 
	@OutputTableNameBlitzCache = N'BlitzCache',		 
	@OutputTableNameBlitzWho = N'BlitzWho';

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
This is issue with incorrect parameters so should effect all versions

**Comment by devendra2108** [comment]
Below needs to be updated as well:


SELECT 
    [ServerName]
	,[CheckDate]
	,[counter_name]
    ,[object_name]
    ,[instance_name]
    ,[cntr_value]
FROM [dbo].[BlitzFirst_PerfmonStats_Actuals]
WHERE CheckDate BETWEEN @FromDate AND @ToDate
ORDER BY 
	[CheckDate] ASC,
	[counter_name] ASC

TO

SELECT 
    [ServerName]
	,[CheckDate]
	,[counter_name]
    ,[object_name]
    ,[instance_name]
    ,[cntr_value]
FROM [dbo].[BlitzFirst_PerfmonStats_Actuals]
WHERE CheckDate BETWEEN @StartDate AND @EndDate
ORDER BY 
	[CheckDate] ASC,
	[counter_name] ASC

**Comment by Adedba** [comment]
Thanks, well spotted! did you want to create a pull request for this or would you like me to make the change?

**Comment by devendra2108** [comment]
Thanks, Just tried one :)

**Comment by BrentOzar** [comment]
Looks good, thanks for the pull request. Merged into dev, will be in the March release.
