### ISSUE TITLE
sp_blitzlock Invalid length parameter passed to the LEFT or SUBSTRING function.

### ISSUE THREAD

**Issue by RogerSAllen** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2800]
**Version of the script**

SELECT @Version = '8.01', @VersionDate = '20210222';

**If the current behavior is a bug, please provide the steps to reproduce.**

Metadata deadlock occurred with client app name of 'SQLAgent - Initial Boot Probe' causing this line to fail as client app name does not contain a step resulting in error 'Invalid length parameter passed to the LEFT or SUBSTRING function.'

        INTO #agent_job
        FROM (
            SELECT dp.event_date,
                   dp.victim_id,
                   dp.id,
                   dp.database_id,
                   dp.client_app,
                   SUBSTRING(dp.client_app, 
                             CHARINDEX('0x', dp.client_app) + LEN('0x'), 
                             32
                             ) AS job_id,
				   		    	   SUBSTRING(dp.client_app, 
                             CHARINDEX(': Step ', dp.client_app) + LEN(': Step '), 
                             CHARINDEX(')', dp.client_app, CHARINDEX(': Step ', dp.client_app)) 
                                 - (CHARINDEX(': Step ', dp.client_app) 
                                     + LEN(': Step '))
                             ) AS step_id
            FROM #deadlock_process AS dp
            WHERE dp.client_app LIKE 'SQLAgent - %' 
        ) AS x
		OPTION ( RECOMPILE );

[metadatadeadlock.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/6031478/metadatadeadlock.txt)

**What is the expected behavior?**
To ignore this client app name? change code to this?

        INTO #agent_job
        FROM (
            SELECT dp.event_date,
                   dp.victim_id,
                   dp.id,
                   dp.database_id,
                   dp.client_app,
                   SUBSTRING(dp.client_app, 
                             CHARINDEX('0x', dp.client_app) + LEN('0x'), 
                             32
                             ) AS job_id,
				   		    	   SUBSTRING(dp.client_app, 
                             CHARINDEX(': Step ', dp.client_app) + LEN(': Step '), 
                             CHARINDEX(')', dp.client_app, CHARINDEX(': Step ', dp.client_app)) 
                                 - (CHARINDEX(': Step ', dp.client_app) 
                                     + LEN(': Step '))
                             ) AS step_id
            FROM #deadlock_process AS dp
            WHERE dp.client_app LIKE 'SQLAgent - %' AND dp.client_app != 'SQLAgent - Initial Boot Probe'
        ) AS x
		OPTION ( RECOMPILE );

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2016 SP2 CU 13

**Comment by BrentOzar** [comment]
Thanks! When you're ready, you can contribute the code in a pull request. Here's how:
https://sqldbawithabeard.com/2019/11/29/how-to-fork-a-github-repository-and-contribute-to-an-open-source-project/

And that's covered in our contributing guide here:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/main/CONTRIBUTING.md

I know it can be kinda intimidating at first, but I'd want to encourage you to jump in and give it a shot. Once you get started with Github, it's addictive, and I'd rather teach you how to fish. Thanks!
