### ISSUE TITLE
BlitzFirst HowToStopIt message confusing

### ISSUE THREAD

**Issue by AdrianB1** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2809]
**Version of the script**
8.01 / 20210022

**What is the current behavior?**
When running sp_BlitzFirst if there is a priority 50 problem "Statistics Updated Recently" the message in the HowToStopIt box is confusing: it starts with a warning: "WARNING: Running this command may result in data loss or an outage.
This tool is meant as a shortcut to help generate scripts for DBAs." but then it provides no command, just a list of statistics that were updated, something like this:
 "[dbname].[schema.[tablename] statistic [statname] was updated on 2021-03-04 17:47:41.7700000, had 77974 rows, with 17055 rows sampled, producing 199 steps in the histogram."

**If the current behavior is a bug, please provide the steps to reproduce.**
Run sp_BlitzFirst on a server with recent statistics updated

**What is the expected behavior?**
Not sure what the intent was, either to provide some command (what is that?) or to provide the list of updates; if the second, the warning text can be removed.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
It does not seem to be related to SQL server version. I found it on a SQL 2012 SP4 Standard Edition. I checked the info saved in tables (with sp_BlitzFirst output set to tables) and there is just the list of statistics, no text warning there.

**Comment by BrentOzar** [comment]
Hi. The warning text is a prefix that's at the beginning of all the HowToStopIt column. If you'd like to put in additional text to make that more clear, you're welcome to - you can reopen this issue with your pull request. Thanks!
