### ISSUE TITLE
Confusing Results!

### ISSUE THREAD

**Issue by MehdiGhvi** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2812]
Why is the event_date column data so very different from the last_tran_started column data?
Does the event_date column indicate the time of the deadlock?

**Comment by BrentOzar** [comment]
Hi, Mehdi. A transaction can start, and then not encounter a deadlock for a long period of time.

**Comment by MehdiGhvi** [comment]
Hi Brent!
Which column shows the exact time of the deadlock?
Because the deadlock time in XEvents is also very different from Event_Date.

**Comment by BrentOzar** [comment]
Rather than us going back & forth here, your best bet is to pop open the source code to understand where the different columns are sourced from.
