### ISSUE TITLE
sp_BlitzCache - error at first run, when storing results to table

### ISSUE THREAD

**Issue by jeffchulg** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2816]
**Version of the script**
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.
Latest - SELECT @Version = '8.01', @VersionDate = '20210222';
 
**What is the current behavior?**
At first execution on a new instance, I get following error:

> 
> Writing results to table.
> USE [DbaTools]; IF EXISTS(SELECT * FROM [DbaTools].INFORMATION_SCHEMA.SCHEMATA WHERE QUOTENAME(SCHEMA_NAME) = '[dbo]') AND NOT EXISTS (SELECT * FROM [DbaTools].INFORMATION_SCHEMA.TABLES WHERE QUOTENAME(TABLE_SCHEMA) = '[dbo]' AND QUOTENAME(TABLE_NAME) = '[BlitzCacheExecutionHistory]') CREATE TABLE [dbo].[BlitzCacheExecutionHistory](ID bigint NOT NULL IDENTITY(1,1),
>                     ServerName NVARCHAR(258),
>                     CheckDate DATETIMEOFFSET,
>                     Version NVARCHAR(258),
>                     QueryType NVARCHAR(258),
>                     Warnings varchar(max),
>                     DatabaseName sysname,
>                     SerialDesiredMemory float,
>                     SerialRequiredMemory float,
>                     AverageCPU bigint,
>                     TotalCPU bigint,
>                     PercentCPUByType money,
>                     CPUWeight money,
>                     AverageDuration bigint,
>                     TotalDuration bigint,
>                     DurationWeight money,
>                     PercentDurationByType money,
>                     AverageReads bigint,
>                     TotalReads bigint,
>                     ReadWeight money,
>                     PercentReadsByType money,
>                     AverageWrites bigint,
>                     TotalWrites bigint,
>                     WriteWeight money,
>                     PercentWritesByType money,
>                     ExecutionCount bigint,
>                     ExecutionWeight money,
>                     PercentExecutionsByType money,
>                     ExecutionsPerMinute money,
>                     PlanCreationTime datetime,
>                     PlanCreationTimeHours AS DATEDIFF(HOUR,CONVERT(DATETIMEOFFSET(7),[PlanCreationTime]),[CheckDate]),
>                     LastExecutionTime datetime,
>                     LastCompletionTime datetime, 
>                     PlanHandle varbinary(64),
>                     [Remove Plan Handle From Cache] AS 
>                         CASE WHEN [PlanHandle] IS NOT NULL 
>                         THEN 'DBCC FREEPROCCACHE (' + CONVERT(VARCHAR(128), [PlanHandle], 1) + ');'
>                         ELSE 'N/A' END,
>                     SqlHandle varbinary(64),
>                         [Remove SQL Handle From Cache] AS 
>                         CASE WHEN [SqlHandle] IS NOT NULL 
>                         THEN 'DBCC FREEPROCCACHE (' + CONVERT(VARCHAR(128), [SqlHandle], 1) + ');'
>                         ELSE 'N/A' END,
>                     [SQL Handle More Info] AS 
>                         CASE WHEN [SqlHandle] IS NOT NULL 
>                         THEN 'EXEC [dbo].sp_BlitzCache @OnlySqlHandles = ''' + CONVERT(VARCHAR(128), [SqlHandle], 1) + '''; '
>                         ELSE 'N/A' END,
>                     QueryHash binary(8),
>                     [Query Hash More Info] AS 
>                         CASE WHEN [QueryHash] IS NOT NULL 
>                         THEN 'EXEC [dbo].sp_BlitzCache @OnlyQueryHashes = ''' + CONVERT(VARCHAR(32), [QueryHash], 1) + '''; '
>                         ELSE 'N/A' END,
>                     QueryPlanHash binary(8),
>                     StatementStartOffset int,
>                     StatementEndOffset int,
>                     PlanGenerationNum bigint,
>                     MinReturnedRows bigint,
>                     MaxReturnedRows bigint,
>                     AverageReturnedRows money,
>                     TotalReturnedRows bigint,
>                     QueryText nvarchar(max),
>                     QueryPlan xml,
>                     NumberOfPlans int,
>                     NumberOfDistinctPlans int,
>                     MinGrantKB BIGINT,
>                     MaxGrantKB BIGINT,
>                     MinUsedGrantKB BIGINT, 
>                     MaxUsedGrantKB BIGINT,
>                     PercentMemoryGrantUsed MONEY,
>                     AvgMaxMemoryGrant MONEY,
>                     MinSpills BIGINT,
>        
>  IF EXISTS(SELECT * FROM [DbaTools].INFORMATION_SCHEMA.SCHEMATA WHERE QUOTENAME(SCHEMA_NAME) = '[dbo]') AND EXISTS (SELECT * FROM [DbaTools].INFORMATION_SCHEMA.TABLES WHERE QUOTENAME(TABLE_SCHEMA) = '[dbo]' AND QUOTENAME(TABLE_NAME) = '[BlitzCacheExecutionHistory]') AND EXISTS (SELECT * FROM [DbaTools].sys.computed_columns WHERE [name] = N'PlanCreationTimeHours' AND QUOTENAME(OBJECT_NAME(object_id)) = N'[BlitzCacheExecutionHistory]' AND [definition] = N'(datediff(hour,[PlanCreationTime],sysdatetime()))')
> BEGIN 
>     RAISERROR('We noticed that you are running an old computed column definition for PlanCreationTimeHours, fixing that now',0,0) WITH NOWAIT;
>     ALTER TABLE [DbaTools].[dbo].[BlitzCacheExecutionHistory] DROP COLUMN [PlanCreationTimeHours];
>     ALTER TABLE [DbaTools].[dbo].[BlitzCacheExecutionHistory] ADD [PlanCreationTimeHours] AS DATEDIFF(HOUR,CONVERT(DATETIMEOFFSET(7),[PlanCreationTime]),[CheckDate]);
> END 
>  
>  
>  
>  
>  
>  
>  
>  
> Msg 156, Level 15, State 1, Line 73
> Incorrect syntax near the keyword 'IF'.
> Msg 4902, Level 16, State 1, Line 4
> Cannot find the object "DbaTools.dbo.BlitzCacheExecutionHistory" because it does not exist or you do not have permissions.
> Msg 4902, Level 16, State 1, Line 4
> Cannot find the object "DbaTools.dbo.BlitzCacheExecutionHistory" because it does not exist or you do not have permissions.

**If the current behavior is a bug, please provide the steps to reproduce.**

On a newly installed instance: 

EXEC dbo.sp_BlitzCache
                            @HideSummary = 1,
                            @ExpertMode                     = 1, -- also collect queries stats 
                            @OutputDatabaseName             = 'DbaTools',
                            @OutputSchemaName               = 'dbo', 
                            @OutputTableName                = 'BlitzCacheExecutionHistory', 
                            @Debug = 1

**What is the expected behavior?**

No error, table should be created.

The issue is the same as experienced multiple times in the past: string truncation. If you split the @StringToExecute statement for table columns definition, there won't be any issue.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2019, but other versions should be affected.

**Comment by erikdarlingdata** [comment]
I've run this a few times trying to repro, and it doesn't seem to. 

The one thing I notice is different is that your create table statement cuts off at MinSpills, but mine doesn't. 

![image](https://user-images.githubusercontent.com/2136037/111687378-966c7580-8800-11eb-9e1a-5977bc00730c.png)

Does yours really cut off there or did you truncate the output?

It could be that the missing Unicode N prefixes here are causing [weird conversions](https://www.brentozar.com/archive/2018/07/tsql2sday/). 

![image](https://user-images.githubusercontent.com/2136037/111687884-33c7a980-8801-11eb-8a5e-347be7ef6b3f.png)

**Comment by jeffchulg** [comment]
Hi @erikdarlingdata , the fact is that I use a name of database longer than DBATools. Try using an extra long name 

@BrentOzar and I already experienced this kind of issue for other procedures and, everytime, it was the size limit for a string assignment which was reached (Before my split, in the `CREATE TABLE` statement I pasted, we already have 2464 chars assigned)

Nevertheless, the implicit conversion (from VARCHAR to  NVARCHAR) could be removed at the same time.

**Comment by Adedba** [comment]
I was having a nose at this the other day but couldn't replicate. Since you mentioned about the length of database name though I started testing in a different way. I grabbed the dynamic SQL code and ran it in SSMS directly and found that playing around with the lengths of the parameters does yield different results: 

This works ok: 
```
   DECLARE @StringToExecute NVARCHAR(MAX) = N'' ;
    DECLARE @OutputServerName NVARCHAR(258) = NULL ,
    @OutputDatabaseName NVARCHAR(258) = CAST(REPLICATE('A',258) AS VARCHAR(258)),
    @OutputSchemaName NVARCHAR(258) = 'dbo' ,
    @OutputTableName NVARCHAR(258) = CAST(REPLICATE('A',91) AS VARCHAR(258));
```
    
    Last few Chars: 
    PRIMARY KEY CLUSTERED(ID ASC));
    
 As soon as I increase one of the lengths , lets do OutputTableName increasing from 91 to 92 I get a missing semicolon: 
   Last few Chars:
   PRIMARY KEY CLUSTERED(ID ASC))

Tested replacing my CAST(REPLICATE with just REPLICATE so that the returned data type is NVARCHAR and still yielded the same results.

So anything beyond this point starts to truncate the text more and more. 

For example replacing the 92 chars with 150 we get: 

`					CONSTRAINT [PK_AAAAAAAA`

I have found two ways around it: 
`SET @StringToExecute = @StringToExecute + 'USE '`

OR 

`SET @StringToExecute += CAST(N'' AS NVARCHAR(MAX)) + 'USE '`

Whilst we are at it, it might be worth adding N Prefixes to the other concatenations just for tidiness.

I did try changing them all to N prefixes as Erik mentioned but seems the issue was still present.

Out of curiosity what lengths were you passing into the Output variables?

**Comment by jeffchulg** [comment]
@Adedba  I don't really remember...

But another fact, to me, could be the use of script file CLRF... I personally prefer use `'+@LineFeed+'` instead... 
I experience many times weird behaviors when it comes to string concatenation without this way of programming... (sometimes, it's just due to a special char which should not be there, but actually is... and it can lead to headaches !)

**Comment by BrentOzar** [comment]
Very nice catch! Thanks for the pull request, merging into the dev branch, will be in the April release with credit to y'all in the release notes.
