### ISSUE TITLE
sp_Blitz: Checks 38 and 39 are crazy slow sometimes; need check logic

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2818]
**Is your feature request related to a problem? Please describe.**
sp_BlitzIndex makes some decisions about if it will run without `@BringThePain` specified.  Checks 38 and 39 look for Heaps across all databases (obeying rules on if user databases are checked), but on large databases with a lot of objects/partitions/the world is on fire these are crazy slow. I've had to quote them out/`@SkipChecks` on a few occasions now to get results back in a reasonable amount of time.

**Describe the solution you'd like**
On the one hand, we could add additional check logic in here like it exists in `sp_BlitzIndex` to skip things if they're out of hand.
On the other hand, I question the value of these checks in `sp_Blitz`

**Describe alternatives you've considered**
Falling in love in an elevator

**Are you ready to build the code for the feature?**
Yes, after the best path forward is decided.

**Comment by BrentOzar** [comment]
Yeah, agreed, there's no value in these checks now that sp_BlitzIndex handles it so well. I removed those checks. Good call.
