### ISSUE TITLE
sp_BlitzFirst: add @ExportToExcel parameter like sp_BlitzCache has

### ISSUE THREAD

**Issue by tmvtmv** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2823]
**Version of the script**
sp_BlitzIndex(TM) v8.01 - February 22, 2021

**What is the current behavior?**
The Window with the Findings and Priority doesn't show nicely as columns when copy/pasted to Excel.
![Screenshot 2021-03-14 at 12 15 59](https://user-images.githubusercontent.com/28952111/111121998-b20c1d80-856d-11eb-977e-3ddb4d83dd76.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
* Run sp_BlitzFirst
* Copy with headers Window 2 (with headers Priority - Finding - URL -etc)

**What is the expected behavior?**
* Show up in columns as the other windows do.

Thanks!

**Comment by BrentOzar** [comment]
Correct, Excel doesn't handle copy/pasting of XML columns.

If you'd like to get a copy/paste friendly version, that would be a new feature. Here's the Contributing Guide on how to get started proposing new features and coding them:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/main/CONTRIBUTING.md

In sp_BlitzCache, the way the contributor built it was to add an @ExportToExcel input parameter, defaulted to 0. When set to 1, it returns two sets of results: one set without the XML columns, and a second result set with the XML columns. That way you can choose which ones you'd like to copy/paste.

I'm going to close this issue, but if you want to tackle this by coding it yourself and doing a pull request, that'd be great! Just leave a note here and I'll assign it to you and reopen it.

**Comment by tmvtmv** [comment]
Challenge accepted! :-)

**Comment by BrentOzar** [comment]
Hahaha, ok, cool! If you have any questions, holler.

**Comment by BrentOzar** [comment]
In case others are reading this, here was my note from the code review: Wait - so if all you need to do is set @OutputXMLasNVARCHAR = 1, then why do we need a new parameter and changes to the proc? Why can't you just run it with @OutputXMLasNVARCHAR = 1 and get what you need? (Just trying to minimize change and risk.)

**Comment by tmvtmv** [comment]
Well ... there's that other catch: Excel only allows 32KB characters per column; I've came across output for the "HowToStopIt"-column up to 64KB which makes Excel divide the output over multiple rows = messy.

**Comment by tmvtmv** [comment]
When to come to think of it ... I could have truncated the output to 32KB instead as well to preserve as much info as possible.
First, let's decide if you feel this "feature" is useful and then I could do some additional polishing ;-)

**Comment by BrentOzar** [comment]
Gotcha, yeah, in that case, it sounds like the only thing we need to do is change the @OutputXMLasNVARCHAR = 1 to trim columns to their necessary length, and then let's stop there.

**Comment by tmvtmv** [comment]
OK, want me to do that?

**Comment by BrentOzar** [comment]
Sure, sounds good! Thanks!

**Comment by tmvtmv** [comment]
Sorry, it this gets annoying - do you want me to add a warning when text is truncated or can we do without?

**Comment by BrentOzar** [comment]
I would skip it.

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, merging into the dev branch, will be in the April release with credit to you in the release notes.
