### ISSUE TITLE
sp_Blitzlock throws error when using ExportToExcel=1

### ISSUE THREAD

**Issue by PierrevdMoosdijk** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2824]
If you execute sp_Blitzlock with parameter ExportToExcel=1 you receive an error message : 

Msg 9455, Level 16, State 1, Procedure sp_BlitzLock, Line 1504 [Batch Start Line 0]
XML parsing: line 1, character 624, illegal qualified name character

I'm using sp_blitzlock version 8.01 release date 20210222

exec dbo.sp_BlitzLock @ExportToExcel=1

MessageLog:
Grab the initial set of XML to parse at Mar 18 2021 10:29:32:500AM
Parse process and input buffer XML Mar 18 2021 10:29:39:060AM
Parse execution stack XML Mar 18 2021 10:29:39:823AM
Grab the full resource list Mar 18 2021 10:29:39:870AM
Parse object locks Mar 18 2021 10:29:39:950AM
Parse page locks Mar 18 2021 10:29:39:980AM
Parse key locks Mar 18 2021 10:29:40:010AM
Parse RID locks Mar 18 2021 10:29:40:090AM
Parse row group locks Mar 18 2021 10:29:40:120AM
Parse parallel deadlocks Mar 18 2021 10:29:40:153AM
Get rid of parallel noise Mar 18 2021 10:29:40:183AM
Get rid of nonsense Mar 18 2021 10:29:40:200AM
Update some nonsense part 1 Mar 18 2021 10:29:40:200AM
Update some nonsense part 2 Mar 18 2021 10:29:40:230AM
Get Agent Job and Step names Mar 18 2021 10:29:40:247AM
Check 1 Mar 18 2021 10:29:41:747AM
Check 2 objects Mar 18 2021 10:29:41:760AM
Check 2 indexes Mar 18 2021 10:29:41:777AM
Check 2 heaps Mar 18 2021 10:29:41:793AM
Check 3 Mar 18 2021 10:29:41:793AM
Check 4 Mar 18 2021 10:29:41:793AM
Check 5 Mar 18 2021 10:29:41:810AM
Check 6 Mar 18 2021 10:29:41:823AM
Check 7 part 1 Mar 18 2021 10:29:41:997AM
Check 7 part 2 Mar 18 2021 10:29:42:230AM
Check 8 Mar 18 2021 10:29:42:247AM
Check 9 Mar 18 2021 10:29:42:260AM
Check 10 Mar 18 2021 10:29:42:293AM
Check 11 Mar 18 2021 10:29:42:323AM
Check 12 Mar 18 2021 10:29:42:340AM
Check 13 Mar 18 2021 10:29:42:340AM
Results 1 Mar 18 2021 10:29:42:340AM
Msg 9455, Level 16, State 1, Procedure sp_BlitzLock, Line 1504 [Batch Start Line 0]
XML parsing: line 1, character 624, illegal qualified name character

Completion time: 2021-03-18T10:29:42.4511700+01:00

**Comment by erikdarlingdata** [comment]
@PierrevdMoosdijk  Do you get this error when you don't try to export? I'm trying to reproduce and I'm not getting the same error.

**Comment by PierrevdMoosdijk** [comment]
Hi Erik,

Without the @ExportToExcel=1 parameter, everything works fine. Also tested with @ExportToExcel=0 throws no error.

It's a SQL2016 Standard Edition with SP2 and latest CU16

This is the exact statement : exec dbo.sp_BlitzLock @ExportToExcel=1

**Comment by erikdarlingdata** [comment]
Okay, so I have a feeling about what's happening. If you run this query:

```
    DECLARE 
        @e bit = 1;

    SELECT
        CASE @e 
            WHEN 0
            THEN CONVERT(xml, '!')
            ELSE '!'
        END AS c
     OPTION(RECOMPILE);
```
The `!` comes back as XML no matter what. That works fine for the parts of the result set where we just return a NULL on the return, but it doesn't work when we return a string. It gets cast as XML. 

There's likely something in this replace that doesn't agree with something that's in one of your queries, but I'm not sure what just yet.

`SUBSTRING(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(LTRIM(RTRIM(d.inputbuf)),' ','<>'),'><',''),NCHAR(10), ' '),NCHAR(13), ' '),'<>',' '), 1, 32000)
`

Can you run this without exporting and eyeball the `query` column for any oddball characters?

Thanks!

**Comment by erikdarlingdata** [comment]
Ah, yeah, here you go. All it would take is an inequality predicate.

```
    DECLARE 
        @e bit = 1;

    SELECT
        CASE @e 
            WHEN 0
            THEN CONVERT(xml, '!')
            ELSE SUBSTRING
                 (
                     REPLACE(
                         REPLACE(
                             REPLACE(
                                 REPLACE(
                                     REPLACE(
                                         LTRIM(
                                             RTRIM('<!')
                                              ), ' ','<>'
                                            ), '><',''
                                        ), NCHAR(10), ' '
                                    ), NCHAR(13), ' '
                                ), '<>', ' '
                            ), 1, 32000
                )
        END AS c
     OPTION(RECOMPILE);
```

**Comment by erikdarlingdata** [comment]
When you have a chance, can you test the code [in the branch here](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/2825)?
