### ISSUE TITLE
Standardize tabs vs spaces 

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2828]
**Is your feature request related to a problem? Please describe.**
When I go to work on code I get annoyed by tabs

**Describe the solution you'd like**
Select all, press replace
![image](https://user-images.githubusercontent.com/2136037/111868490-84015180-8950-11eb-9255-eb15f23d24d1.png)

**Describe alternatives you've considered**
Continuing to be annoyed

**Are you ready to build the code for the feature?**
I was born ready.

**Comment by BrentOzar** [comment]
I'd actually rather go the other way and switch to tabs for accessibility:
https://www.reddit.com/r/javascript/comments/c8drjo/nobody_talks_about_the_real_reason_to_use_tabs/

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by erikdarlingdata** [comment]
Sure, as long as it's standard! I can reverse the find and replace.

**Comment by erikdarlingdata** [comment]
Gonna close this one out. Long term I think it would be a hassle to enforce. I looked into some ways to do it with GitHub, but it's not anything I'd be confident with maintaining.
