### ISSUE TITLE
sp_Blitz:  check 92 fails with an arithmetic overflow when disk is almost full

### ISSUE THREAD

**Issue by ScottL1969** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2837]
**Version of the script**
	SELECT @Version = '8.01', @VersionDate = '20210222';

**What is the current behavior?*
Msg 8115, Level 16, State 8, Line 1
Arithmetic overflow error converting numeric to data type numeric.    When a drive calculates to 100.00 pct full.   It actually has like 8 MB.

**If the current behavior is a bug, please provide the steps to reproduce.**
Fill up a drive

**What is the expected behavior?**  
Script runs with no error.

@Debug = 1
--
Running CheckId [92].
Msg 8115, Level 16, State 8, Line 1
Arithmetic overflow error converting numeric to data type numeric.
The statement has been terminated.
Running CheckId [103].

Fix:    ,(CONVERT(DECIMAL(4,2),(total_bytes/1.0 - available_bytes)/total_bytes * 100))  AS used_percent   
Should be  ,(CONVERT(DECIMAL(5,2),(total_bytes/1.0 - available_bytes)/total_bytes * 100))  AS used_percent   

Calc that failed  (100.00)   convert only allowed 99.99.
volume_mount_point	logical_volume_name	total_MB	available_MB	used_percent
M	 (New Volume)	153596	136511	11.12
E	 (New Volume)	1791996	305534	82.95
T	 (New Volume)	102396	83046	18.90
F	 (SAPs)	409596	8	100.00

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2017

**Comment by BrentOzar** [comment]
Great, thanks for the bug report. I've fixed it in the dev branch, and it'll be in the April release with credit to you in the release notes.
