### ISSUE TITLE
Standardize parameter format across procs

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#284]
Use @PascalCase for params on everything, like @ExpertMode = 1.

Yes, this will be a breaking change for folks, and we'll need to test this with our own utilities too, but it's the right thing to do going forward before we make the big public push.

(Updated - originally called that @CamelCase)

**Comment by aschwabe10** [comment]
I'm gonna be a bit pendantic and point out that this is camelCase and this is PascalCase.

**Comment by BrentOzar** [comment]
DAMMIT THERE'S A BUG AND I HAVEN'T EVEN STARTED CODING YET

**Comment by AndySchwabe** [comment]
Is there an overall desired type of formatting? Is it documented? I.e. Right align vs left align, tabs vs spaces, tab size, etc...

**Comment by BrentOzar** [comment]
No, in the past, we had a few different authors on these, each of which had their own formatting standards. I'll create a documentation ticket for that. We'll probably use the default formatting in https://format-sql.com/ just to give users something they can easily do without a paid tool.

**Comment by BrentOzar** [comment]
Stuff we'll have to do:

* Find/replace in the stored procs.
* Update the documentation.
* Change the querymanifest.json in the collector to use the right params. (Starting a separate ticket for that one.)

**Comment by BrentOzar** [comment]
@Version output parameter for sp_AskBrent and sp_Blitz has been an int, but that's no longer useful since we're switching to semantic versioning. Removing that, and just leaving the @VersionDate parameter.

**Comment by BrentOzar** [comment]
sp_AskBrent @SkipChecksQueries changed to @CheckProcedureCache (to match sp_Blitz). Is still defaulted to off until we can put better logic in there to explain to users which queries suck.

**Comment by BrentOzar** [comment]
sp_BlitzCache @results parameter replaced with @ExpertMode.

@results had choices for narrow, simple (default), or expert. Narrow is now gone.

**Comment by BrentOzar** [comment]
I'm sure there's going to be bugs with this - for example, in sp_BlitzCache I found that the old parameter @whole_cache wasn't even hooked up to anything - but marking this as complete since the parameter names have been changed, at least.
