### ISSUE TITLE
sp_BlitzIndex: Add create and modify dates to the sort order options

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2845]
**Is your feature request related to a problem? Please describe.**
If you add new indexes, you might want to check in on their usage metrics to make sure they're helpful.

**Describe the solution you'd like**
Add modify and create date to potential sort orders

**Describe alternatives you've considered**
Scrolling through everything

**Are you ready to build the code for the feature?**
Yes, I have a copy of it ready

...Even though `create_date` is for the table and not the index and only `modify_date` would be really useful

😔

**Comment by BrentOzar** [comment]
How neat is that! Nifty, nice work. Merging into the dev branch, will be in the April release.
