### ISSUE TITLE
Questionable text in sp_BlitzLock help

### ISSUE THREAD

**Issue by AdrianB1** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2849]
**Version of the script**
All since March 2018

**What is the current behavior?**
The known limitation list in the help includes "your mom" as an entry. Not looking professional.

**If the current behavior is a bug, please provide the steps to reproduce.**
Run sp_BlitzLock with @Help = 1.

**What is the expected behavior?**
Probably remove the text?

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All supported versions.

**Comment by BrentOzar** [comment]
@AdrianB1 did you want to move forward with a pull request, or should I close this?

**Comment by BrentOzar** [comment]
Thanks for the pull request! Merged into the dev branch, will be in the April release with credit to you in the release notes.

**Comment by AdrianB1** [comment]
Please don't mention it, it is a trivial change not worth telling about.
