### ISSUE TITLE
Rename sp_AskBrent to sp_Blitz(Something)

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#285]
I'd rather rename it to something that isn't Brent-specific.

Its largest goal is to capture performance metrics on the server as of right now, so ideas:

* sp_BlitzPerformance
* sp_BlitzMetrics
* sp_BlitzIAmFreshOutOfIdeasAt11AM

**Comment by BlitzErik** [comment]
sp_WhoIsBlitzing

**Comment by BrentOzar** [comment]
sp_WhoIsBlitzed

**Comment by AndySchwabe** [comment]
sp_BlitzBaseline?

**Comment by mvelic** [comment]
sp_BlitzSnap (aka snapshot)

**Comment by rdameron** [comment]
sp_BlitzWTFisGoingOnNow

**Comment by rdameron** [comment]
sp_BlitzWTF, sp_BlitzWTFisHappening?

**Comment by rdameron** [comment]
sp_Blitz8Ball

**Comment by rdameron** [comment]
sp_BlitzAskMeIKnow

**Comment by BrentOzar** [comment]
Done, renamed as sp_BlitzFirst. Blog post will go out Tuesday.
