### ISSUE TITLE
sp_BlitzIndex: add parameter to only show Columnstore Index Visualisation data.

### ISSUE THREAD

**Issue by Djheath2000** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2851]
**Is your feature request related to a problem? Please describe.**
I've been using sp_BlitzIndex to assess columnstore indexes, specifically the columnstore visualisation section to see how updates/deletes etc. are affecting the index.  It can be a pain in SSMS to resize the results window to just show the row_group/segments section I want.  After watching Brent's Fundamentals of Columnstore Indexes class, Brent also mentioned he would like a switch to just show this information, so I thought it is worth adding it in!

**Describe the solution you'd like**
Add a new parameter "ShowColumnstoreOnly" (data type bit, default value = 0) to sp_BlitzIndex procedure.
This parameter will only get checked in the "STEP 3: DIAGNOSE THE PATIENT" section when the table_name is not null.  If the parameter is set to 1, then only the "Visualizing columnstore index contents." section is executed.  

**Describe alternatives you've considered**
None.

**Are you ready to build the code for the feature?**
Yes!  Just need to remind myself on the process to submit code changes in Github!! Is this something worth adding?

**Comment by Djheath2000** [comment]
I've made changes to the sp_BlitzIndex procedure. I think I've submitted the pull request properly, so please check and let me know if you would like any changes.
Thanks.,

**Comment by BrentOzar** [comment]
Looks good! Thanks for the pull request. Merging into the dev branch, will be in the April release with credit to you in the release notes.
