### ISSUE TITLE
sp_Blitz recommendation of an Active Directory account

### ISSUE THREAD

**Issue by AdrianB1** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2854]
**Version of the script**
sp_Blitz Mar 22 2021 12:00AM

**What is the current behavior?**
When running on a virtual account, sp_Blitz displays this message: "I'm running as NT Service\MSSQLSERVER. I wish I had an Active Directory service account instead."

**If the current behavior is a bug, please provide the steps to reproduce.**
Execute sp_Blitz on a SQL server running on a virtual account

**What is the expected behavior?**
Microsoft recommends to use a virtual account for stand-alone servers (not clustered) here: https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-windows-service-accounts-and-permissions?view=sql-server-ver15. Should the sp_Blitz message be changed to match Microsoft's recommendation? If not, the https://www.brentozar.com/go/setup page should include an explanation for the difference in opinions.

Btw, the setup checklist cannot be downloaded, https://www.brentozar.com/go/setup link goes to https://www.brentozar.com/first-aid/ where there is no option to get the checklist.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2019 on Windows 2019, probably all versions

**Comment by BrentOzar** [comment]
Howdy! The setup checklist is inside the First Responder Kit.

Sorry about the misleading language in sp_Blitz - I've removed that to make it clear that we're not doing security advice in this tool.

Thanks!
