### ISSUE TITLE
Add partition ranges to columnstore visualization

### ISSUE THREAD

**Issue by NickPapatonis** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2860]
**Is your feature request related to a problem? Please describe.**
It's not a problem, just a nice to have.  I think Brent mentioned it would be nice to see this information in the sp_BlitzIndex columnstore visualization.

**Describe the solution you'd like**
Add a new, optional column that will display each partition's range values when a columnstore table contains more than one partition.  I'm thinking it should go to the right of the PIVOT columns so it's not in the way when not needed.  Here are a few examples showing a datetime2 and int parameter type.

partition_number | row_group_id | total_rows | partition_range
------------------- | --------------- | ----------- | -----------------
1 | 0 | 61506 | < 2021-01-01T00:00:00
2 | 0 | 1048576 | >= 2021-01-01T00:00:00 < 2021-02-01T00:00:00
2 | 1 | 150701 | >= 2021-01-01T00:00:00 < 2021-02-01T00:00:00
3 | 0 | 1048576 | >= 2021-02-01T00:00:00 < 2021-03-01T00:00:00
3 | 1 | 1048576 | >= 2021-02-01T00:00:00 < 2021-03-01T00:00:00
3 | 2 | 388945 | >= 2021-02-01T00:00:00 < 2021-03-01T00:00:00

partition_number | row_group_id | total_rows | partition_range
------------------- | --------------- | ----------- | -----------------
1 | 0 | 61506 | < 100000
2 | 0 | 1048576 | >= 100000 < 200000
2 | 1 | 150701 | >= 100000 < 200000
3 | 0 | 1048576 | >= 200000 < 300000
3 | 1 | 1048576 | >= 200000 < 300000
3 | 2 | 388945 | >= 200000 < 300000

**Describe alternatives you've considered**
No alternatives identified yet.

**Are you ready to build the code for the feature?**
Yes.  I've done a little experimenting to get an idea what this will involve.  I have something working, but I could definitely use a review to make sure my approach is correct (or to make sure there isn't a better one).  Along with the implementation questions, there are some around the actual functionality that may require a few iterations.  Also, I've enumerated a number of the obvious test cases, but if anyone wants to suggest some, I will be sure to cover those too.

**Comment by BrentOzar** [comment]
Howdy! Ah, the thing I wanted wasn't about the partitioning - it's about the contents of the columnstore indexes themselves. In the visualization section, for columns that use the data dictionary (like in StackOverflow.Users, the DisplayName column), I'd love to see the lowest and highest values in the dictionary. However, I think this is great too! Good idea.

**Comment by NickPapatonis** [comment]
Sorry for the confusion, I must have misunderstood.  I'll go ahead with this since it could have some value.  Maybe after this one, I'll see if I can assist with what you really wanted:)  I have a few requirements questions below.  Thanks for the help!

- Do you care what the default is for the parameter that will control whether the range values column is shown? I'm thinking it should default to 0 since this wasn't your intended change (i.e., don't show the column unless user explicitly requests it).
- I saw your guidance on formatting dates/times in ISO-8601, so I'm CONVERT'ing those to NVARCHAR with format 126.  Do we have formatting requirements for other types (e.g., numeric types), or is acceptable to just CAST everything else to an NVARCHAR?
- Should the range values repeat for each row group within a partition or appear only on row group 0?
  - Repeating on every row is a little busy.  But if the range only appears on the first row of a partition, the user may have to scroll at times to find it.

#### Repeating for each row group within a partition
partition_number | row_group_id | total_rows | partition_range
------------------- | --------------- | ----------- | -----------------
1 | 0 | 61506 | < 2021-01-01T00:00:00
2 | 0 | 1048576 | >= 2021-01-01T00:00:00 < 2021-02-01T00:00:00
2 | 1 | 150701 | >= 2021-01-01T00:00:00 < 2021-02-01T00:00:00
3 | 0 | 1048576 | >= 2021-02-01T00:00:00 < 2021-03-01T00:00:00
3 | 1 | 1048576 | >= 2021-02-01T00:00:00 < 2021-03-01T00:00:00
3 | 2 | 388945 | >= 2021-02-01T00:00:00 < 2021-03-01T00:00:00

#### Once per partition on the first row group row
partition_number | row_group_id | total_rows | partition_range
------------------- | --------------- | ----------- | -----------------
1 | 0 | 61506 | < 2021-01-01T00:00:00
2 | 0 | 1048576 | >= 2021-01-01T00:00:00 < 2021-02-01T00:00:00
2 | 1 | 150701 | 
3 | 0 | 1048576 | >= 2021-02-01T00:00:00 < 2021-03-01T00:00:00
3 | 1 | 1048576 | 
3 | 2 | 388945 |

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, merging into the dev branch, will be in the next release with credit to you in the release notes.
