### ISSUE TITLE
sp_Blitz - add a check for incompatible version with TLS 1.2 version

### ISSUE THREAD

**Issue by jeffchulg** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2867]
**Is your feature request related to a problem? Please describe.**

We all know that SSL v2 and v3 ( https://www.tenable.com/plugins/nessus/20007 ) so as TLS 1.0 ( https://www.tenable.com/plugins/nessus/104743) are vulnerable protocols that should be avoided.
But, before being able to avoid their use, one should check that its installation will still be able to accept incoming connection using still secured protocols as TLS 1.2.

There is a [documentation ](https://support.microsoft.com/en-us/topic/kb3135244-tls-1-2-support-for-microsoft-sql-server-e4472ef8-90a9-13c1-e4d8-44aad198cdbe)page on Microsoft's website that describes from which SQL Server version this protocol is supported.

There could be a check for Operating System hosting SQL Server as well.

Other resources :

- https://serverfault.com/questions/639706/change-ssl-protocol-in-mssql-2012
- https://www.jorgebernhardt.com/disable-ssl-and-tls-on-winserv/
- https://dba.stackexchange.com/questions/107820/sql-server-compatibility-with-new-tls-standards

**Describe the solution you'd like**

As there is already an insecured version check in sp_Blitz, we could go ahead and add a check to tell "not ready for secure transfer protocols"

**Describe alternatives you've considered**

none

**Are you ready to build the code for the feature?**

I don't have code for that at the moment.

**Comment by BrentOzar** [comment]
Howdy sir. I'm steering clear of doing new security advice in sp_Blitz. There's definitely an opportunity in the market for someone to build a security advisory tool, but I'd rather not have that as part of the First Responder Kit - the liability there is on the high side. You might try building something like this into DBAtools.
