### ISSUE TITLE
v20210421 of sp_BlitzFirst failing against SQL 2008 R2 Servers

### ISSUE THREAD

**Issue by mike-halford** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2875]
First Responder 20210421 spBlitzFirst  failing since upgrading only on SQL 2008 R2 servers

EXEC dbo.sp_BlitzFirst 
  @OutputDatabaseName = 'DBATools', 
  @OutputSchemaName = 'dbo', 
  @OutputTableName = 'BlitzFirst',
  @OutputTableNameFileStats = 'BlitzFirst_FileStats',
  @OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
  @OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
  @OutputTableNameBlitzCache = 'BlitzCache',
  @OutputTableNameBlitzWho = 'BlitzWho';

Results in the following error.
Setting up configuration variables
Now starting diagnostic analysis
Determining SQL Server version.
Capturing first pass of wait stats, perfmon counters, file stats
Logging sp_BlitzWho to table
**Msg 120, Level 15, State 1, Line 33
The select list for the INSERT statement contains fewer items than the insert list. The number of SELECT values must match the number of INSERT columns.**
Beginning investigatory queries
Warning: The join order has been enforced because a local join hint is used.
Warning: The join order has been enforced because a local join hint is used.
Warning: The join order has been enforced because a local join hint is used.
Finished running investigatory queries
Waiting to match @Seconds parameter
Capturing second pass of wait stats, perfmon counters, file stats
Analyzing changes between first and second passes of DMVs
Analysis finished, outputting results
Calling sp_BlitzCache
Checking @MinutesBack validity.
Setting @MinutesBack to a negative number
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Checking all sort orders, please be patient
Beginning all sort loop
Beginning for ALL
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking plan cache age
Checking for single use plans and plans with many queries
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring system databases by default
Setting minutes back filter
Applying chosen sort order
Substituting NULLs for spill columns in older versions of SQL
Adding additional info columns for newer versions of SQL
Substituting NULLs for memory grant columns in older versions of SQL
Substituting NULLs for spill columns in older versions of SQL
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Writing results to table.
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking plan cache age
Checking for single use plans and plans with many queries
Processing SQL Handles To Ignore
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring system databases by default
Including only chosen SQL Handles
Setting minutes back filter
Applying chosen sort order
Substituting NULLs for spill columns in older versions of SQL
Adding additional info columns for newer versions of SQL
Substituting NULLs for memory grant columns in older versions of SQL
Substituting NULLs for spill columns in older versions of SQL
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Writing results to table.
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking plan cache age
Checking for single use plans and plans with many queries
Processing SQL Handles To Ignore
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring system databases by default
Including only chosen SQL Handles
Setting minutes back filter
Applying chosen sort order
Substituting NULLs for spill columns in older versions of SQL
Adding additional info columns for newer versions of SQL
Substituting NULLs for memory grant columns in older versions of SQL
Substituting NULLs for spill columns in older versions of SQL
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Writing results to table.
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking plan cache age
Checking for single use plans and plans with many queries
Processing SQL Handles To Ignore
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring system databases by default
Including only chosen SQL Handles
Setting minutes back filter
Applying chosen sort order
Substituting NULLs for spill columns in older versions of SQL
Adding additional info columns for newer versions of SQL
Substituting NULLs for memory grant columns in older versions of SQL
Substituting NULLs for spill columns in older versions of SQL
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Writing results to table.
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking plan cache age
Checking for single use plans and plans with many queries
Processing SQL Handles To Ignore
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring system databases by default
Including only chosen SQL Handles
Setting minutes back filter
Applying chosen sort order
Substituting NULLs for spill columns in older versions of SQL
Adding additional info columns for newer versions of SQL
Substituting NULLs for memory grant columns in older versions of SQL
Substituting NULLs for spill columns in older versions of SQL
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Writing results to table.
Writing results to table.
sp_BlitzCache Finished

**Comment by BrentOzar** [comment]
OK, I don't have any 2008R2 boxes handy - it's out of support by Microsoft and not technically supported here either - can you drill down and get us a little more details? Thanks!

**Comment by mike-halford** [comment]
Can confirm after very quick look the issue is with sp_BlitzWho. Works fine for 2014, 2016, 2017 and 2019 but fails with SQL 2008R2.

Runs fine unless you try and log results to table.

EXECUTION
EXEC	@return_value = [dbo].[sp_BlitzWho]
		@OutputDatabaseName = N'DBATools',
		@OutputSchemaName = N'dbo',
		@OutputTableName = N'BlitzWho',
		@Version = @Version OUTPUT,
		@VersionDate = @VersionDate OUTPUT

RESULTS
Msg 120, Level 15, State 1, Line 33
The select list for the INSERT statement contains fewer items than the insert list. The number of SELECT values must match the number of INSERT columns.

(1 row(s) affected)

(1 row(s) affected)

**Comment by wqweto** [comment]
In `sp_BlitzWho` on SQL2008R2 the `[cached_parameter_info]` column is not returned but is still present in the column list on the output table INSERT statement.

Works here after a simple fix like this: https://github.com/wqweto/SQL-Server-First-Responder-Kit/commit/c0016bb65648df8b366ed4613fec7e4bde05c8cb

**Comment by mike-halford** [comment]
Thanks to @wqweto for guidance. The following change to sp_BlitzWho fixes the issue.
`+ CASE WHEN @ProductVersionMajor >= 11 THEN N',[cached_parameter_info]' ELSE N'' END `

**Comment by BrentOzar** [comment]
Woohoo! Might be the first time I've fetched code from someone else's repo and integrated it into the FRK without them doing the pull request, neato. Thanks, @wqweto - merged into the dev branch, will be in the May release with credit to you in the release notes.
