### ISSUE TITLE
Query Cutoff for Deadlock Script

### ISSUE THREAD

**Issue by cblaze22** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2877]
**Version of the script**
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.

SELECT @Version = '8.02', @VersionDate = '20210322';

**What is the current behavior?**

Query gets cut off

**If the current behavior is a bug, please provide the steps to reproduce.**

Not a bug but probably by design, but cant diagnose where the query is coming from because of it.

**What is the expected behavior?**

Below is what I see, but need full script.

 (@p__linq__0 int,@p__linq__1 int)SELECT      [UnionAll2].[Id] AS [C1],      [UnionAll2].[Id1] AS [C2],      [UnionAll2].[Id2] AS [C3],      [UnionAll2].[Email] AS [C4],      [UnionAll2].[PhoneNumber] AS [C5],      [UnionAll2].[Carrier] AS [C6],      [UnionAll2].[Source] AS [C7],      [UnionAll2].[Active] AS [C8],      [UnionAll2].[DisableEmail] AS [C9],      [UnionAll2].[DisablePhone] AS [C10],      [UnionAll2].[VerifiedEmail] AS [C11],      [UnionAll2].[VerifiedPhone] AS [C12],      [UnionAll2].[DateCreated] AS [C13],      [UnionAll2].[DateModified] AS [C14],      [UnionAll2].[UserType] AS [C15],      [UnionAll2].[C1] AS [C16],      [UnionAll2].[Id3] AS [C17],      [UnionAll2].[Id4] AS [C18],      [UnionAll2].[DivisionTeamId] AS [C19],      [UnionAll2].[SubscriptionId] AS [C20],      [UnionAll2].[UserType1] AS [C21],      [UnionAll2].[Id5] AS [C22],      [UnionAll2].[Id6] AS [C23],      [UnionAll2].[Status] AS [C24],      [UnionAll2].[NCAACertificationStatus] AS [C25],      [UnionA

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

SQL Server 2016

**Comment by BrentOzar** [comment]
To see the max amount possible of the deadlock, open up the deadlock graph. I usually use SentryOne Plan Explorer for that since it's easier than using SSMS. That's all of the query that SQL Server captures.
