### ISSUE TITLE
sp_BlitzIndex: missing indexes Sample Query Plan is for the wrong query

### ISSUE THREAD

**Issue by gdoddsy** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2883]
**Version of the script**
8.03 (20210420)

**What is the current behavior?**
When running `EXEC sp_BlitzIndex @TableName='MyTable'` I get missing indexes reported with the new Sample Query Plan column, however the plan loaded in there doesn't reference 'MyTable' at all. 

The Sample Query Plan shown does have 1 missing index request, but it's for a different table.

**If the current behavior is a bug, please provide the steps to reproduce.**
I haven't been able to repro this in an environment where I can share screenshots from. Hopefully the above makes sense.

**What is the expected behavior?**
The Sample Query Plan loaded in the column would have the missing index request.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2019 CU9. I notice that there's some comments around SQL 2019 in the commit history, maybe it's just not supported yet?

**Comment by gdoddsy** [comment]
Had a bit more of a look, it seems that I'm always getting the top 1 query that has missing index queries. I've added a pull request that fixed it for me, but it's not tested properly.

**Comment by erikdarlingdata** [comment]
That's funny -- I originally had the same correlation when I thought I had fixed it, but removing it didn't change results at all for me.  I figured the one inside the cross apply was enough.

**Comment by gdoddsy** [comment]
@erikdarlingdata - could you have had something different in the cross apply?

When I had a quick look I thought it needed something in the select that joined it back to the outer query for sql to know which record it was grabbing a plan for.

**Comment by erikdarlingdata** [comment]
No, I think what happened was I had a query that generated multiple missing index requests, e.g.

```
SELECT
    COUNT_BIG(*)
FROM dbo.Users AS u
JOIN dbo.Posts AS p
   ON p.OwnerUserId = u.Id
JOIN dbo.Comments AS c
    ON c.PostId = p.Id
WHERE u.Reputation = 1
AND   p.PostTypeId = 3
AND   c.Score = 0;
```

![image](https://user-images.githubusercontent.com/2136037/117212090-e068e500-adc7-11eb-9d17-d1efd03c2dee.png)

That generates three entries here all with different group handles:

```
SELECT
    ddmigsq.*,
    lsh.text
FROM sys.dm_db_missing_index_group_stats_query AS ddmigsq
CROSS APPLY sys.dm_exec_sql_text(ddmigsq.last_sql_handle) AS lsh;
```

![image](https://user-images.githubusercontent.com/2136037/117212461-6127e100-adc8-11eb-9bfc-82d35281e65c.png)

I don't recall exactly what happened at the time I tested it, though it might be worth testing this scenario with your change as well.

**Comment by erikdarlingdata** [comment]
You may also want to test running two queries in the same batch and seeing which one shows up. Doing some tests with simplified queries locally is giving some surprising results. 

```
SELECT 
    COUNT_BIG(*)
FROM dbo.Posts AS p
WHERE p.OwnerUserId = 22656
AND   p.Score < 0;

SELECT
    COUNT_BIG(*)
FROM dbo.Users AS u
JOIN dbo.Posts AS p
   ON p.OwnerUserId = u.Id
JOIN dbo.Comments AS c
    ON c.PostId = p.Id
WHERE u.Reputation = 1
AND   p.PostTypeId = 3
AND   c.Score = 0;
```

**Comment by gdoddsy** [comment]
Multiple missing index requests? But SSMS only shows me one in the green text!

I hadn't considered multiple missing indexes for a query. I also don't understand enough about the structure and relationships in the sys views that this all comes from.

Unfortunately I'm not going to have time in the next few weeks to get my head around it all and test out my change properly (I did note in the pull request and here that it's not tested). I love the feature you built, and at the moment the change is working for me when I ran it, so that'll do me for now.

**Comment by BrentOzar** [comment]
I left this in the open pull requests. I'll do testing on it this week or next, or other folks are welcome to jump in too if they've got time. Thanks for collaborating on this one, y'all!

**Comment by BrentOzar** [comment]
I've confirmed that this one is working for me much better than the old one was. I think there are probably still some edge cases where it's not going to work, but in the interest of keeping the thing moving forward in each version, I'll roll with this as-is.

Here's the testing I was doing just in case anybody's curious:

```
/* One-time setup */
USE StackOverflow2010;
GO
DropIndexes;
CREATE INDEX Age ON dbo.Users(Age); /* To avoid trivial plans */
GO
CREATE OR ALTER PROC dbo.Users_DisplayName AS
	SELECT Id FROM dbo.Users WHERE DisplayName = N'Brent Ozar' AND 1 = (SELECT 1);
GO
CREATE OR ALTER PROC dbo.Users_Location AS
	SELECT Id FROM dbo.Users WHERE Location = N'San Diego, CA, USA' AND 1 = (SELECT 1);
GO
CREATE OR ALTER PROC dbo.Users_TwoIndexes AS
	SELECT Id FROM dbo.Users WHERE DisplayName = N'Brent Ozar' AND 1 = (SELECT 1);
	SELECT Id FROM dbo.Users WHERE Location = N'San Diego, CA, USA' AND 1 = (SELECT 1);
GO
CREATE OR ALTER PROC dbo.OneQuery_MultipleMissingIndexes AS
	SELECT
		COUNT_BIG(*)
	FROM dbo.Users AS u
	JOIN dbo.Posts AS p
	   ON p.OwnerUserId = u.Id
	JOIN dbo.Comments AS c
		ON c.PostId = p.Id
	WHERE u.Reputation = 1
	AND   p.PostTypeId = 3
	AND   c.Score = 0;
GO
CREATE OR ALTER PROC dbo.TwoQueries_MultipleMissingIndexes AS
	SELECT 
		COUNT_BIG(*)
	FROM dbo.Posts AS p
	WHERE p.OwnerUserId = 22656
	AND   p.Score < 0;

	SELECT
		COUNT_BIG(*)
	FROM dbo.Users AS u
	JOIN dbo.Posts AS p
	   ON p.OwnerUserId = u.Id
	JOIN dbo.Comments AS c
		ON c.PostId = p.Id
	WHERE u.Reputation = 1
	AND   p.PostTypeId = 3
	AND   c.Score = 0;
GO


/* Testing */
DBCC FREEPROCCACHE;
GO
EXEC Users_DisplayName;
GO 10
EXEC Users_Location;
GO 10
EXEC Users_TwoIndexes;
GO 10
EXEC OneQuery_MultipleMissingIndexes;
GO 3
EXEC TwoQueries_MultipleMissingIndexes;
GO 3

sp_BlitzIndex @Mode = 3
```
