### ISSUE TITLE
Enhancements to sp_Blitz for Amazon RDS

### ISSUE THREAD

**Issue by rrankins** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2889]
Add enhancements to sp_Blitz for when it's run on Amazon RDS, primarily to allow reading of the errorlog using rdsadmin.dbo.rds_read_error_log when it is running on an RDS server instead of xp_readerrorlog, which user's do not have permission to run on RDS.
Also add query against sys.dm_server_services to check whether instant_file_initialization is enabled if it can’t find it in the errorlog, possibly due to cycling of the errorlog which causes the startup messages to no longer be in the current errorlog 
Add comments to the RDS inserts to #SkipChecks to explain what checks are being skipped on RDS and why

**Comment by BrentOzar** [comment]
Hahaha, thanks for creating the issue too! Look at you go. You're on fire!

**Comment by rrankins** [comment]
Thanks, I was hoping I did everything correctly.
Still getting up to speed with Github and the whole concept of pull requests, forks, etc.
