### ISSUE TITLE
sp_BlitzCache DATEADD Arithmetic overflow error converting expression to data type int.

### ISSUE THREAD

**Issue by RonMacNeil** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2890]
**Version of the script**
@Version = '8.03', @VersionDate = '20210420'

**What is the current behavior?**
If the query plan's last_elapsed_time (coming from sys.dm_exec_query_stats, stored as microseconds as BIGINT) is greater than an INT after first having been converted to milliseconds, then the DATEADD evaluations will fail with "Arithmetic overflow error converting expression to data type int.".

**If the current behavior is a bug, please provide the steps to reproduce.**
Tough one to reproduce.

**What is the expected behavior?**
Evaluate the DATEADD without error.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All versions are affected.

**Suggested Fix**
I can fix this by changing the affected DATEADDs to use a last_elapsed_time that is instead converted to SECONDS instead of MILLISECONDS:
Currently:
    DATEADD(MILLISECOND, (x.last_elapsed_time / 1000.), x.last_execution_time)
To something like:
    DATEADD(SECOND, (x.last_elapsed_time / 1000000.), x.last_execution_time)

**Comment by BrentOzar** [comment]
HAHAHA, woooow. That would be a fun issue to troubleshoot. Thanks for the pull request, merging into the dev branch, will be in the May release with credit to you in the release notes.
