### ISSUE TITLE
Uninstall.sql: Drops table dbo.SqlServerVersions: Only in current database / Regardless of @printOnly / Not part of PRINT

### ISSUE THREAD

**Issue by andreasjordan** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2893]
**Version of the script**
Current dev-branch at GitHub

**What is the current behavior?**
The table dbo.SqlServerVersions is only dropped in current database
The table dbo.SqlServerVersions is dropped regardless of @printOnly
The drop statement is not included in the PRINT output

**If the current behavior is a bug, please provide the steps to reproduce.**
Just have a look at the code:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/0e76863536bcd42c8f7f2292711099c43f80cae7/Uninstall.sql#L76-L77

**What is the expected behavior?**
In the first case (only current database) I am not sure, because it may be risky to delete all tables dbo.SqlServerVersions in all databases.
In the second case (regardless of @printOnly) I would expect that @printOnly does not delete any objects, so does not drop the table.
In the third case (PRINT output) I would expect the DROP TABLE to be included in the PRINT. This is how I found the bug: I have missed the statement and so I had a look at the code.

If you want me to code that and open a pull request, just give me a hint.

**Comment by BrentOzar** [comment]
Thanks for the pull request. Merging into the dev branch, will be in the May release with credit to you in the release notes.
