### ISSUE TITLE
sp_Blitz: Add new check for Jobs with a schedule type of: "Start automatically when SQL Server Agent starts"

### ISSUE THREAD

**Issue by MikeScalise** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2902]
**Is your feature request related to a problem? Please describe.**
There's an existing check for Stored Procedures that run at startup (Check #7) because it's a good idea to know what's happening and if third-party software is doing anything you wouldn't approve of. Jobs could also contain similar T-SQL and run when the SQL Server Agent starts, so I thought it would be good to include a check for these.

**Describe the solution you'd like**
A check for jobs scheduled to run at SQL Server Agent startup.

Here's the code to create a job that would meet the criteria:

```
IF EXISTS (SELECT job_id FROM msdb.dbo.sysjobs_view WHERE name = N'AgentJobRunAtStartup')
EXEC msdb.dbo.sp_delete_job @job_name=N'AgentJobRunAtStartup', @delete_unused_schedule=1
GO

DECLARE @jobId BINARY(16);

EXEC msdb.dbo.sp_add_job @job_name=N'AgentJobRunAtStartup', 
                         @enabled=1,
			 @job_id = @jobId OUTPUT;

EXEC msdb.dbo.sp_add_jobstep @job_id=@jobId,
                             @step_name=N'StepOne', 
			     @step_id=1,
			     @subsystem=N'TSQL', 
			     @command=N'SELECT 1
/* or some malicious code
    or code that changes my server configuration settings without my knowing it */', 
			     @database_name=N'master';

EXEC msdb.dbo.sp_add_jobserver @job_id = @jobId,
                                                       @server_name = N'(local)';

EXEC msdb.dbo.sp_add_jobschedule @job_id=@jobId,
                                 @name=N'AutoStartSchedule',
                                 @enabled=1,
				 @freq_type=64;
```

**Describe alternatives you've considered**
Check the schedules for each enabled job to see if they have a schedule type of: Start automatically when SQL Server Agent starts.

**Are you ready to build the code for the feature?**
Yes, I have a copy of it ready.

**Comment by erikdarlingdata** [comment]
This already has a check, at [CheckId 57](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_Blitz.sql#L3120). 

Is that not getting you what you're after?

**Comment by MikeScalise** [comment]
Yes, that's exactly what I was after. My apologies. I had searched the closed issues for a reference to that but didn't find anything. I must've not used the right search terms. Next time, I'll also look in sp_Blitz_Checks_by_Priority.md to make sure there isn't already a check.

**Comment by erikdarlingdata** [comment]
No worries at all! Large chunks of this were written pre-GitHub, so there may not be a corresponding issue to everything. I'm going to close this one out.
