### ISSUE TITLE
sp_Blitz: Add new check for Agent Jobs missing steps

### ISSUE THREAD

**Issue by MikeScalise** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2904]
**Is your feature request related to a problem? Please describe.**
In my mind, the three main components of an Agent Job are its Step(s), Schedule(s), and Notification(s). sp_Blitz already has a check for Agent Jobs Without Failure Emails (Check #94), but not for missing steps or schedules. It would be beneficial to know if there are enabled jobs that are missing either one of these.

**Describe the solution you'd like**
A check for jobs that are enabled but missing steps.

Here's the code to create a job that would meet the criteria:

```
IF EXISTS (SELECT job_id FROM msdb.dbo.sysjobs_view WHERE name = N'AgentJobWithoutSteps')
EXEC msdb.dbo.sp_delete_job @job_name=N'AgentJobWithoutSteps', @delete_unused_schedule=1
GO

DECLARE @jobId BINARY(16);

EXEC msdb.dbo.sp_add_job @job_name=N'AgentJobWithoutSteps', 
                         @enabled=1,
					     @job_id = @jobId OUTPUT;

EXEC msdb.dbo.sp_add_jobserver @job_id = @jobId,
                               @server_name = N'(local)';
```

**Describe alternatives you've considered**
Check each enabled job to see if they are have at least one step defined.

**Are you ready to build the code for the feature?**
Yes, I have a copy of it ready.

**Comment by BrentOzar** [comment]
Interesting. I'm going to be honest though: if someone has an Agent job without any steps, I don't think it's something that I'd want to raise an alarm about. I'm not really concerned about it in the grand scheme of things.

Can you share a scenario where you ran into this and it caused a problem?

**Comment by MikeScalise** [comment]
I can't share a scenario where I actually ran into this and it caused a problem. This is something that clearly SQL Server allows but didn't feel "right" to me because a job without steps is worthless. However, you make a good point--it's not really something worthy of raising an alarm about (relative to other issues). Thanks for your feedback and feel free to close!

**Comment by BrentOzar** [comment]
OK, cool!
