### ISSUE TITLE
sp_Blitz: The check for Agent Jobs Without Failure Emails (Check #94) ignores a specific schedule type.

### ISSUE THREAD

**Issue by MikeScalise** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2905]
**Version of the script**
Latest

**What is the current behavior?**
In the check for Agent Jobs Without Failure Emails, sp_Blitz looks at msdb.[dbo].[sysjobs], but it also inner joins to msdb.[dbo].[sysjobschedules] (WHERE  next_run_date > 0). In using that criteria, it's excluding jobs with a schedule type of: Start automatically when SQL Server Agent starts, because that schedule type has a next_run_date of 0. The query would need to join msdb.[dbo].[sysschedules] and look for a freq_type of 64 to determine this specific schedule (though I don't think that should be the resolution--see below).

**If the current behavior is a bug, please provide the steps to reproduce.**
Here's an example of a job with a schedule type of Start automatically when SQL Server Agent starts and that's missing notifications, yet doesn't get picked up by sp_Blitz in check #94.

```
IF EXISTS (SELECT job_id FROM msdb.dbo.sysjobs_view WHERE name = N'AgentJobRunAtStartup')
EXEC msdb.dbo.sp_delete_job @job_name=N'AgentJobRunAtStartup', @delete_unused_schedule=1
GO

DECLARE @jobId BINARY(16);

EXEC msdb.dbo.sp_add_job @job_name=N'AgentJobRunAtStartup', 
                                             @enabled=1,
					     @job_id = @jobId OUTPUT;

EXEC msdb.dbo.sp_add_jobstep @job_id=@jobId,
                                                    @step_name=N'StepOne', 
						    @step_id=1,
						    @subsystem=N'TSQL', 
						    @command=N'SELECT 1
/* or some malicious code
    or code that changes my server configuration settings without my knowing it */', 
						    @database_name=N'master';

EXEC msdb.dbo.sp_add_jobserver @job_id = @jobId,
                                                       @server_name = N'(local)';

EXEC msdb.dbo.sp_add_jobschedule @job_id=@jobId,
                                                           @name=N'AutoStartSchedule',
                                                           @enabled=1,
							    @freq_type=64;
```

**What is the expected behavior?**
In this particular case, I would expect a row in the result set for the "AgentRunAtStartup" because it has a schedule and is missing notifications.

However, what I actually think should happen to resolve this is to remove the join to [msdb].[dbo].[sysjobschedules] altogether. I'm not sure why a job needs to have a schedule for its failure email status to be evaluated. Getting rid of the join resolves this bug since there wouldn't be a tie to schedules at all. Additionally, the finding and detail messages of this check make no indication that a job must have a schedule to be evaluated--so getting rid of the join makes the action more aligned with its descriptions.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2019 Developer
Windows 10
No, I don't believe so.

**Comment by BrentOzar** [comment]
Sure, makes sense! This is a good candidate for a pull request. Thanks!

**Comment by BrentOzar** [comment]
Thanks for the pull request! Merging into the dev branch, will be in the next release with credit to you in the release notes.
