### ISSUE TITLE
Hanging process of Data Collection sp_BlitzFirst

### ISSUE THREAD

**Issue by larkinis** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2907]
**Version of the script**
Version - 8.03 / VersionDate-2021-04-20 00:00:00.000

The periodic job sp_BlitzFirst caused the process to hang with the QRY_PROFILE_LIST_MUTEX wait type. 
Аt the same time, the sp_BlitzFirst process was blocked by a session (on screen 172) waiting for QRY_PROFILE_LIST_MUTEX. The blocking process did not respond to kill, but exited only after the forced termination of sp_BlitzFirst.

![sp_BlitzFirst](https://user-images.githubusercontent.com/84312745/118464532-a671da00-b709-11eb-9c4c-97b16d80b4c9.png)

**Comment by BrentOzar** [comment]
OK, I added a 1-second lock timeout in the dev branch. Can you see if that avoids the issue? Thanks!

**Comment by larkinis** [comment]
Thank you very much Brent! Added this code to production system. I think this should be help. We will observe.
