### ISSUE TITLE
Add SET STATISTICS XML OFF to the top of the procs

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2911]
**Is your feature request related to a problem? Please describe.**
When I run the procs and I accidentally have actual plans turned on, they take forever.

**Describe the solution you'd like**
Thanks to Daniel Hutmacher, I learned that you can set statistics xml off at the top of a proc, and that'll turn off the actual plans.

**Are you ready to build the code for the feature?**
Yep!

**Comment by erikdarlingdata** [comment]
i love this

**Comment by rebambus** [comment]
Yessss!
