### ISSUE TITLE
Server\Instance Name in output

### ISSUE THREAD

**Issue by parlevjo2** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2915]
Hi Brent,

I copy always the output of sp_blitz to excel, but then I cannot see the server\instance name anymore.
Could you please change 'SQL Server First Responder Kit' in this piece of code 

`
VALUES  ( -1 ,
		  0 ,
		  'sp_Blitz ' + CAST(CONVERT(DATETIME, @VersionDate, 102) AS VARCHAR(100)),
		  'SQL Server First Responder Kit' ,
		  'http://FirstResponderKit.org/' ,
		  'To get help or add your own contributions, join us at http://FirstResponderKit.org.'
		);
`

to 'SQL Server First Responder Kit' + ', Instance: ' + @@SERVERNAME

`
VALUES  ( -1 ,
		  0 ,
		  'sp_Blitz ' + CAST(CONVERT(DATETIME, @VersionDate, 102) AS VARCHAR(100)),
		  'SQL Server First Responder Kit' + ', Instance: ' + @@SERVERNAME,
		  'http://FirstResponderKit.org/' ,
		  'To get help or add your own contributions, join us at http://FirstResponderKit.org.'
		);
`

As it is only a change in one line, could you do that yourself. Sorry for me is always a struggle to propose a piece of code by means of github.

Output In Column Finding would than eq be: SQL Server First Responder Kit, Instance: XXX-SQL-01
I have already tested that on many instances.

Of course If you find a better place to put the server\instance name that's Ok with me.

Thanks in Advance.

**Comment by BrentOzar** [comment]
Did you try running it with @CheckServerInfo =1? I believe it’s already in the output there, but not certain.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by BrentOzar** [comment]
Yeah, just checked and it's in the priority 250 Server Info section:
<img width="570" alt="Screen Shot 2021-05-26 at 5 02 58 PM" src="https://user-images.githubusercontent.com/245462/119701798-49320300-be44-11eb-9e17-07cb8ee09db1.png">

Closing the issue.
