### ISSUE TITLE
Error creating sp_Blitz procedure: invalid column name instant_file_initialization_enabled

### ISSUE THREAD

**Issue by ghotz** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2921]
**Version of the script**

Version 8.04

**What is the current behavior?**

```
Msg 207, Level 16, State 1, Procedure sp_Blitz, Line 8196 [Batch Start Line 3]
Invalid column name 'instant_file_initialization_enabled'.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

run `sp_Blitz.sql` on an instance version not having `instant_file_initialization_enabled` in DMV `sys.dm_server_services`

**What is the expected behavior?**

Procedure should compile and execute check 193 as dynamic SQL if column exists.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Previous version, 8.03, worked correctly.
As a workaround, I think it's safe to simply remove lines from 8174 to 8203 (included).

**Comment by BrentOzar** [comment]
Gotcha, sorry about this. This was due to @rrankins's check-in here:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/2888

It looks like he referenced the instant_file_initialization_enabled column, which isn't available in all builds of 2008, 2012, or 2016. We'll need to rewrite his check as dynamic SQL, similar to the existing check 192 for Instant File Initialization Not Enabled.

**Comment by ghotz** [comment]
> We'll need to rewrite his check as dynamic SQL, similar to the existing check 192 for Instant File Initialization Not Enabled.

I was in a hurry and just did a quick diff between the two versions, but I'm pretty sure just removing lines 8174 to 8203 would be enough i.e. both the new AWS check, and the old dynamic check when columns is there, would work.

**Comment by BrentOzar** [comment]
I don't believe that's the case, no. But you're welcome to submit a pull request if you can test your fixes on both RDS and non-RDS servers. Otherwise, let's hold off for someone who can do that. Thanks for understanding!

**Comment by jeffreymergler** [comment]
> Previous version, 8.03, worked correctly.
> As a workaround, I think it's safe to simply remove lines from 8174 to 8203 (included).

As a silly workaround, I just commented out the instant_file_initialization_enabled reference and return 0:

											where exists (select 0 FROM sys.dm_server_services
											               WHERE /*instant_file_initialization_enabled = 'Y'
											               AND*/ filename LIKE '%sqlservr.exe%')
											OPTION (RECOMPILE);

**Comment by BrentOzar** [comment]
I've turned the check into dynamic SQL. Give the current dev branch copy a shot and let me know if that doesn't solve the issue. Thanks!

**Comment by jmstull** [comment]
Just tried Install-Core-Blitz-No-Query-Store.sql  and got the above error as well,"Msg 207, Level 16, State 1, Procedure sp_Blitz, Line 8196 [Batch Start Line 3] Invalid column name 'instant_file_initialization_enabled'."
We are running "Microsoft SQL Server 2014 (SP1-GDR) (KB4019091) - 12.0.4237.0 (X64)   Jul  5 2017 22:03:42   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows NT 6.3 <X64> (Build 14393: ) " and I did not see that listed above and wanted to add it to the list.

**Comment by BrentOzar** [comment]
That was fixed in last month's release. If you're having that issue on the current version, open a new issue. Cheers.
