### ISSUE TITLE
sp_BlitzFirst - "Sleeping Query with Open Transactions" is not checked correctly

### ISSUE THREAD

**Issue by EitanBlumin** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2922]
**Version of the script**
8.04, 20210530

**What is the current behavior?**
CheckID 8 (Sleeping Query with Open Transactions) is not performed correctly.
Since the relevant query relies on `sys.dm_exec_requests`, it doesn't actually mean that it finds **sleeping** sessions.

**If the current behavior is a bug, please provide the steps to reproduce.**

```sql
BEGIN TRAN
/* some kind of DML statement here */
```

Once the command above completes, its transaction remains opened and so it retains any locks that it got.
However, since this command completed, it would not show up in sp_BlitzFirst as it doesn't have any corresponding data in `sys.dm_exec_requests`.

**What is the expected behavior?**
Since a session could hold open transactions without actively running any request, they should be alerted on as part of CheckID 8.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All SQL and OS versions are affected.

**Relevant Line in Source Code**

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dbb121efbf8fef9b14d967a76547e967fffd1b09/sp_BlitzFirst.sql#L1653-L1683

**Suggested Fix**

```sql
		INSERT INTO #BlitzFirstResults (CheckID, Priority, FindingsGroup, Finding, URL, Details, HowToStopIt, StartTime, LoginName, NTUserName, ProgramName, HostName, DatabaseID, DatabaseName, QueryText, OpenTransactionCount)
		SELECT 8 AS CheckID,
		    50 AS Priority,
		    'Query Problems' AS FindingGroup,
		    'Sleeping Query with Open Transactions' AS Finding,
		    'https://www.brentozar.com/askbrent/sleeping-query-with-open-transactions/' AS URL,
		    'Database: ' + DB_NAME(db.resource_database_id) + @LineFeed + 'Host: ' + s.[host_name] + @LineFeed + 'Program: ' + s.[program_name] + @LineFeed + 'Asleep with open transactions and locks since ' + CAST(s.last_request_end_time AS NVARCHAR(100)) + '. ' AS Details,
		    'KILL ' + CAST(s.session_id AS NVARCHAR(100)) + ';' AS HowToStopIt,
		    s.last_request_start_time AS StartTime,
		    s.login_name AS LoginName,
		    s.nt_user_name AS NTUserName,
		    s.[program_name] AS ProgramName,
		    s.[host_name] AS HostName,
		    db.[resource_database_id] AS DatabaseID,
		    DB_NAME(db.resource_database_id) AS DatabaseName,
		    (SELECT TOP 1 [text] FROM sys.dm_exec_sql_text(c.most_recent_sql_handle)) AS QueryText,
		    s.open_transaction_count AS OpenTransactionCount
		FROM sys.dm_exec_sessions s
		INNER JOIN sys.dm_exec_connections c ON s.session_id = c.session_id
		INNER JOIN (
		SELECT DISTINCT request_session_id, resource_database_id
		FROM    sys.dm_tran_locks
		WHERE resource_type = N'DATABASE'
		AND     request_mode = N'S'
		AND     request_status = N'GRANT'
		AND     request_owner_type = N'SHARED_TRANSACTION_WORKSPACE') AS db ON s.session_id = db.request_session_id
		WHERE s.status = 'sleeping'
		AND s.open_transaction_count > 0
		AND s.last_request_end_time < DATEADD(ss, -10, SYSDATETIME())
		AND EXISTS(SELECT * FROM sys.dm_tran_locks WHERE request_session_id = s.session_id
		AND NOT (resource_type = N'DATABASE' AND request_mode = N'S' AND request_status = N'GRANT' AND request_owner_type = N'SHARED_TRANSACTION_WORKSPACE'));
```

**Comment by BrentOzar** [comment]
Thanks for the suggestion! Would you like to submit a pull request?

**Comment by EitanBlumin** [comment]
Sure. Will do.

**Comment by EitanBlumin** [comment]
oops, sorry for the mess 😅 
Hope I got this PR thing right this time.

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, fixes the bug. Merging into the dev branch, will be in the July release with credit to you in the release notes.
