### ISSUE TITLE
Invalid column name 'instant_file_initialization_enabled' when running Install-Core-Blitz-No-Query-Store on SQL2014

### ISSUE THREAD

**Issue by osudude** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2926]
**Version of the script**
SELECT @Version = '8.04', @VersionDate = '20210530';

**What is the current behavior?**
Upgrading from previous release, pulled current release from github and ran Install-Core-Blitz-No-Query-Store in SSMS and recive the following error:

Msg 207, Level 16, State 1, Procedure sp_Blitz, Line 8196 [Batch Start Line 3]
Invalid column name 'instant_file_initialization_enabled'

**What is the expected behavior?**
Run without error

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Microsoft SQL Server 2014 (SP2-CU10-GDR) (KB4052725) - 12.0.5571.0 (X64)   Jan 10 2018 15:52:08   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: )

**Comment by BrentOzar** [comment]
Hi. Whenever you file an issue, make sure to check to see if it's already been opened, and like in this case, fixed. ;-) It was #2921. Sorry about that!
