### ISSUE TITLE
sp_Blitz 20210530 fails with SQL 2008 R2

### ISSUE THREAD

**Issue by mike-halford** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2929]
updating sp_Blitz on SQL 2008 R2 servers fails with the following

Msg 207, Level 16, State 1, Procedure sp_Blitz, Line 8196 [Batch Start Line 3]
Invalid column name 'instant_file_initialization_enabled'.

Tested and works on fine SQL 2014,2016,2017 and 2019

**Comment by BrentOzar** [comment]
Hi. Whenever you file an issue, make sure to check to see if it's already been opened, and like in this case, fixed. ;-) It was #2921. Sorry about that!
