### ISSUE TITLE
sp_Blitz output table order different than onscreen table order

### ISSUE THREAD

**Issue by parlevjo2** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2937]
Not really an bug, but some cosmetic

**Version of the script**
@Version = '8.04', @VersionDate = '20210530'

The order of the records in the output table is not consistent with the order of the records in SQL Server Management Studio on the screen.
There are total of 5 lines where the ORDER BY should be changed from
```
      1 x	         CheckID FROM ##BlitzResults ORDER BY Priority , FindingsGroup, Finding, Details;
      4 x	QueryPlanFiltered FROM #BlitzResults ORDER BY Priority , FindingsGroup , Finding , Details';
```
to
` ... ORDER BY Priority , FindingsGroup , Finding , DatabaseName , Details`

**Comment by BrentOzar** [comment]
OK, if that's important to you, you're welcome to submit a pull request with the change as described here:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/main/CONTRIBUTING.md

If not, let me know or I'll close this issue in a few days. Thanks!

**Comment by parlevjo2** [comment]
Ok. I wil do a Pull Reqeust. It will take me some time beacuse that github program drives me crazy every time

**Comment by parlevjo2** [comment]
I have created a Pull Request #2940 "Update sp_Blitz.sql change order in output table same as onscreen"

**Comment by BrentOzar** [comment]
Merged, thanks!
