### ISSUE TITLE
sp_Blitz: Warn when databases have <> 60 for Target Recovery Interval

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2938]
**Is your feature request related to a problem? Please describe.**
On servers where there are a lot of flushcache messages in the error log, changing the [target recovery internal from 0 to 60](https://sqlperformance.com/2020/05/system-configuration/0-to-60-switching-to-indirect-checkpoints) (the default in databases created on 2016+) can really help alleviate stress on the server in several ways.

**Describe the solution you'd like**
Right now, having a non-zero value gets called out as a non-default setting. I think that should be taken out, and we should warn when people use 0 instead. Over the last couple years, I've had people bump that setting and have a lot of oddball problems disappear. 

**Describe alternatives you've considered**
Cataloging fetishes

**Are you ready to build the code for the feature?**
Yes, but this may need some tweaking for cloud places where the setting may not be available for change. I have not done research in this area.

**Comment by erikdarlingdata** [comment]
Just a couple notes on this while I have a moment:
 * The `target_recovery_time_in_seconds` column is 2012+
 * Exclude system databases
 * Make sure databases read read/write

```
SELECT
    d.name,
    d.target_recovery_time_in_seconds
FROM sys.databases AS d
WHERE d.database_id > 4
AND   d.is_read_only = 0;
```

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, merging into the dev branch, will be in the next release with credit to you in the release notes.
