### ISSUE TITLE
code referencing instant_file_initialization_enabled column should be placed in @StringToExecute

### ISSUE THREAD

**Issue by mehurley99** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2943]
Version of the script ... 
SELECT @Version = '8.04', @VersionDate = '20210530';

**What is the current behavior?**
Ran Install-Core-Blitz-No-Query-Store on SQL Server < 2016 but I get invalid column error:
**Msg 207, Level 16, State 1, Procedure sp_Blitz, Line 8199
Invalid column name 'instant_file_initialization_enabled'.**

**If the current behavior is a bug, please provide the steps to reproduce.**
Run Install-Core-Blitz-No-Query-Store on SQL Server < 2016.

**What is the expected behavior?**
Successful completion of the script w/ no errors 

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server < 2016.  Yes it used to work previously as we have an earlier version of sp_Blitz installed on the server.

NOTE: I will submit a fix.

**Comment by BrentOzar** [comment]
Hi. Whenever you file an issue, make sure to check to see if it's already been opened, and like in this case, fixed. ;-) It was #2921. Sorry about that!

**Comment by mehurley99** [comment]
I'm sorry.  I thought I did check your latest change prior to writing my issue.  Where can I get a version of Install-Core-Blitz-No-Query-Store with the fix?  Thank you!

**Comment by BrentOzar** [comment]
That will be done with the next monthly release.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws
