### ISSUE TITLE
sp_Blitz - Reliability warning for wrong version (CheckId 182)

### ISSUE THREAD

**Issue by FlatlandR** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2946]
**Version of the script**
SELECT @Version = '8.04', @VersionDate = '20210530';

**What is the current behavior?**
I installed SQL Server **2019** (RTM-GDR) (KB4583458) - 15.0.2080.9. Before applying the CU I ran sp_Blitz. 
It gave the warning: Prio 20, Reliability, SQL **2016** RTM has a bug involving dumps that happen every time Query Store cleanup jobs run. This is fixed in CU1 and later: https://sqlserverupdates.com/sql-server-2016-updates/

**What is the expected behavior?**
sp_Blitz should return no warning, since I am on SQL Server 2019.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Every version from SQL Server 2016 and newer. 

**To fix it**
In line 6084 there is a line of code which causes this behaviour: 
IF @ProductVersionMajor >= 13 AND @ProductVersionMinor < 2149 --CU1 has the fix in it

To fix: change the >= into =.
Result: After the change, sp_Blitz did not show the message anymore.

**Comment by BrentOzar** [comment]
Great catch, thanks! Fixed in the dev branch, will be in the next monthly release.
