### ISSUE TITLE
sp_BlitzIndex: DatabaseId from sys.databases not accurate for SQL Azure

### ISSUE THREAD

**Issue by hyrmd** [BrentOzarULTD/SQL-Server-First-Responder-Kit#295]
I would LOVE to use sp_BlitzIndex on our SQL Azure. However, I find that I do not get the missing index information from sp_BlitzIndex because the database id in the sys.databases tables doesn't match that in the sys.dm_db_missing_index. So I never get results back. I guess the database_id in sys.databases is not reliable on Azure SQL Database. =/ 

I think if sp_BlitzIndex used  db_id() function to get the database id instead of the query against sys.databases, it would work for Azure SQL DB too?

**Comment by BrentOzar** [comment]
Yeah, this (and the rest of the scripts) don't really work well in Azure SQL DB. I'm going to leave this ticket open for volunteer coders, though.

**Comment by BrentOzar** [comment]
Did a quick round of testing, and it seems to be working fine now. Dunno if MS fixed the sys.databases issue, maybe? Screenshot attached. If anybody still has this issue and wants to reopen it, include screenshots & repro examples. Thanks!

![1](https://cloud.githubusercontent.com/assets/245462/23581477/3ba46632-00da-11e7-8c0f-f10bf87d7878.png)
