### ISSUE TITLE
sp_BlitzIndex - Unique constraints are scripted as index create/drops

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2950]
**Version of the script**
Latest and greatest

**What is the current behavior?**
Unique constraints get scripted as index create/drop statements. Drops will fail if you're quickly trying to declutter indexes.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
CREATE TABLE dbo.whatever(id int NOT NULL);
CREATE UNIQUE INDEX i ON dbo.whatever(id);
ALTER TABLE dbo.whatever ADD CONSTRAINT u UNIQUE (id);

EXEC sp_BlitzIndex 
    @TableName = 'whatever';
```

![image](https://user-images.githubusercontent.com/2136037/125819424-a516d50f-fb68-4bb9-940a-83f9809dccbd.png)

**What is the expected behavior?**
These should be scripted as alter table statements, like we do with primary keys.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Well...

**Comment by erikdarlingdata** [comment]
Just a quick note: I need to change the `#IndexSanity` table to get `is_unique_constraint` from `sys.indexes`, and then change the insert into `#IndexCreateTsql`, along with the `@TableName` specific output.

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, merging into dev, will be in the September release with credit to you in the release notes.
