### ISSUE TITLE
sp_DatabaseRestore's 'trailing slash adder' doesn't work for root drives when moving data files

### ISSUE THREAD

**Issue by LowlyDBA** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2952]
**Version of the script**
SELECT @Version = '8.04', @VersionDate = '20210530';

**What is the current behavior?**

Passing a root drive as a `@MoveDataDrive` (or any other @MovexxDrive param) without a trailing slash does not trigger the 'trailing slash adder' functionality since there is no slash to identify if a back or forward slash should be used:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/60352a57bd4b82512a2b0c9302d10c009acc30ab/sp_DatabaseRestore.sql#L388-L397

**If the current behavior is a bug, please provide the steps to reproduce.**

Passing a naked drive, i.e. `F:` as the `@MoveDataDrive` or similar parameter.

**What is the expected behavior?**

The slash adder should automatically assume a backslash needs to be added if no slashes are present in the supplied drive.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

SQL 2019 - OS irrelevant. I introduced this bug with https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/2067

**Comment by LowlyDBA** [comment]
Happy to make this into a PR - I think the best approach is to reorder the two statements and remove the `CHARINDEX` search from the 2nd statement:

```tsql

IF (SELECT RIGHT(@MoveDataDrive, 1)) <> '/' AND CHARINDEX('/', @MoveDataDrive) > 0 --Has to end in a '/' 
 BEGIN 
 	IF @Execute = 'Y' OR @Debug = 1 RAISERROR('Fixing @MoveDataDrive to add a "/"', 0, 1) WITH NOWAIT; 
 	SET @MoveDataDrive += N'/'; 
 END; 
ELSE IF (SELECT RIGHT(@MoveDataDrive, 1)) <> '\'  --Has to end in a '\' 
 BEGIN 
 	IF @Execute = 'Y' OR @Debug = 1 RAISERROR('Fixing @MoveDataDrive to add a "\"', 0, 1) WITH NOWAIT; 
 	SET @MoveDataDrive += N'\'; 
 END; 
```

**Comment by BrentOzar** [comment]
Thanks for the pull request! Just did a quick visual exam and looks good. (I don't have a testbed setup for sp_DatabaseRestore at the moment.) Merging into the dev branch. Will be in the next release with credit to you in the release notes.
