### ISSUE TITLE
sp_BlitzIndex - does not show stats when running against tables in DBs outside session's scope

### ISSUE THREAD

**Issue by MisterZeus** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2954]
**Version of the script**
@Version = '8.04', @VersionDate = '20210530'

**What is the current behavior?**
When running a table-specific sp_BlitzIndex, for a table in a database outside your session's currently-connected database, you get no stats.
I think this is because the query that grabs the table's stats uses some system DMVs like the below which are locked to the session's database and cannot peek into other databases' DMVs, even if you run them as EXEC OtherDB.sys.dm_db_stats_properties (... , ...)

[sys-dm-db-stats-properties-transact-sql](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-db-stats-properties-transact-sql)

**If the current behavior is a bug, please provide the steps to reproduce.**
- Install sp_Blitz into any db.
- EXEC dbo.sp_BlitzIndex @DatabaseName='NotTheDbYourSessionIsConnectedTo', @SchemaName='OtherDbsSchema', @TableName='OtherDbsTable';
- the table stats comes back with an empty set, even though we have defined the correct target @DatabaseName above

**What is the expected behavior?**
- table's stats should show up for table specific runs of sp_BlitzIndex no matter which database the sproc is installed in or what DB scope the session is running in

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
- tested in SQL 2016, I think this has always been a bug.

**Comment by BrentOzar** [comment]
Correct, it's always been that way. If that change is important to you, we'd welcome a pull request with the fixes necessary to change the behavior. Read the contributing guide on how to get started:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/main/CONTRIBUTING.md

If you don't want to contribute the code, just let us know and we can close the pull request. (This isn't something I have the time to do, unfortunately.)

**Comment by BrentOzar** [comment]
Looks good! Thanks for the pull request. Merging into the dev branch, will be in the next release with credit to you in the release notes.
