### ISSUE TITLE
Attempting installation in SQL Server 2012 fails with error: "Procedure sp_Blitz, Line 8196 [Batch Start Line 3] Invalid column name 'instant_file_initialization_enabled'."

### ISSUE THREAD

**Issue by rferreiradba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2956]
**Attempting installation in SQL Server 2012 fails with error: "Procedure sp_Blitz, Line 8196 [Batch Start Line 3] Invalid column name 'instant_file_initialization_enabled'."**

Attempted version installation:
@Version = '8.04', @VersionDate = '20210530', which I downloaded straight from https://www.brentozar.com/first-aid/, so, as far as I know, that's the latest version there is..?

**When running Install-Core-Blitz-No-Query-Store.sql I get the error "Procedure sp_Blitz, Line 8196 [Batch Start Line 3] Invalid column name 'instant_file_initialization_enabled'."**

Expected behavior is that the script would complete successfully, creating all stored procedures and any other dependent objects.

I have (had) Version '7.96', Date = '20200606' already installed in the server and it used to work fine. But this new version I just downloaded will not install, and displays the error message already mentioned.

SQL Server version -> Microsoft SQL Server 2012 (SP1) - 11.0.3156.0 (X64)   May  4 2015 18:48:09   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.2 <X64> (Build 9200: ) (Hypervisor) 

OS Version -> Windows Server 2012 R2 Standard

I MUCH appreciate your work and all you do. THANK you so much if you can take a look at the issue. Either way, thanks a million for all the scripts, articles, opinions, etc...

Best,

Raphael

**Comment by BrentOzar** [comment]
Thanks, glad you like our work! That one's already been fixed here:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/2921

And it'll be in next month's release. Cheers!

**Comment by rferreiradba** [comment]
Thank you much, R.
