### ISSUE TITLE
Create an open source SQL Server setup checklist

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2957]
**Is your feature request related to a problem? Please describe.**
We ship a SQL Server setup checklist PDF in the First Responder Kit, but it's woefully out of date. I started to update it, and I was reminded of the perils of working in Microsoft Word, so I figured screw it, I'll create one in Markdown. Then I thought as long as I'm doing it, why not just open source it here?

**Describe the solution you'd like**
I'm going to need a few parts:

* Create a separate Github repo (to make it easier to fork or compile the book on its own)
* Set up a file for each chapter
* Convert the existing checklist into Markdown
* Add a chapter about how to contribute improvements, making it clear that links to blog posts and resources are welcome, make it clear what's in scope (Linux, Windows, cloud VMs), what's out of scope (Azure SQL DB, Kubernetes, services other than the engine itself, third party apps)
* Add a chapter for credits to authors so they can link to their work
* Write a blog post announcing the checklist in progress

The checklist will be in the August release of the First Responder Kit. I don't want to include it in the pending July update because the first version will just be my own stuff - I'd rather the community contribute a round of improvements and corrections before it's updated.

**Comment by nick-fotopoulos** [comment]
I've fixed all of the issue with the previous PR. New PR is #3035

**Comment by MichelZ** [comment]
Is there a repo yet for this?
Also, what is the goal? To include a generated PDF in the first responder kit? Or have it online as HTML rendering? Both? Or include as HTML in the First responder kit?

**Comment by BrentOzar** [comment]
Thanks for working on this, but I'm going to go ahead and close this for now. Just comes down to my own schedule - I don't have the bandwidth to work on this, and other folks are welcome to start a new repo with this kind of thing.
