### ISSUE TITLE
sp_BlitzIndex - document support of XML, columnstore, spatial, Hekaton indexes, temporal tables

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#296]
I don't know if these are supported, and we don't have to ADD support, but we just need to mention in the documentation:
- If they'll show up in sp_BlitzIndex results or not
- If they do show up, are the definitions, usage numbers, and sizes correct
- Will SQL Server recommend these indexes in the missing indexes section (I know the answer's no on that one, we just need to document it)

**Comment by BlitzErik** [comment]
Where do you want this documented, exactly?

**Comment by BrentOzar** [comment]
In the sp_BlitzIndex page and in readme.md would be cool, just something we can point people to.

**Comment by BlitzErik** [comment]
Notes to self:
 - Use a VM because I don't want any Hekaton code paths opened up on an instance I normally use
 - Compare output of BlitzIndex to output of sp_BlitzInMemory 
 - Make sure I check different kinds of in memory indexes
 - Check clustered and nonclustered columnstore
 - Figure out how to even create and index spatial data (there might be examples in AW?) 
 - There are a bunch of different kinds of XML indexes: primary, selective, and then if they're defined by node, path, etc. It should be easy to grab data to futz with this on from the plan cache.

**Comment by BrentOzar** [comment]
What we learned so far:

* Temporal tables - fully supported.
* Columnstore indexes have 2 bugs:
    * In sp_BlitzIndex @TableName = 'Votes', the columns are all shown as includes, not as keys
    * In the "Size" column, the data is shown as 150,668,527 rows; 1.2GB; 1.2GB LOB - I don't think I wanna call that LOB data

**Comment by BrentOzar** [comment]
ALTER DATABASE CURRENT ADD FILEGROUP Stack_Hekaton
    CONTAINS MEMORY_OPTIMIZED_DATA;

ALTER DATABASE CURRENT ADD FILE (
    name='Stack_Hekaton', filename='M:\MSSQL\DATA\Stack_Hekaton')
    TO FILEGROUP Stack_Hekaton;

ALTER DATABASE CURRENT
    SET MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT = ON;
GO  
CREATE TABLE dbo.Users_Durable (Id INT PRIMARY KEY NONCLUSTERED, 
	DisplayName NVARCHAR(40), Location NVARCHAR(100), Reputation INT,
	LastAccessDate DATETIME) WITH (MEMORY_OPTIMIZED = ON);
GO
INSERT INTO dbo.Users_Durable(Id, Displayname, Location, Reputation, LastAccessDate)
SELECT Id, Displayname, Location, Reputation, LastAccessDate
FROM dbo.Users;
GO
SELECT * FROM dbo.Users_Durable WHERE DisplayName = 'Brent Ozar'
GO 10

sp_BlitzIndex @TableName = 'Users_Durable';

/* Things that are wrong for both durable and non-durable tables:

* Shows as a heap, but I don't know that we really wanna call it that. We need a separate name, like [In-Memory OLTP]
* The "heap" shows nothing in the Size column
* The nonclustered PK's Size column shows correct # of rows, 0.0MB as size (wrong)
* Missing index recommendations show up as CREATE INDEX, but that doesn't actually work in In-Memory OLTP. You have to use a different syntax.

ALTER TABLE [dbo].[Users_NonDurable]
ADD INDEX [<Name of Missing Index, sysname,>]
NONCLUSTERED ([DisplayName])
*/

**Comment by BrentOzar** [comment]
XML indexes:

/* Create a table and load some query plans into it */
CREATE TABLE dbo.PlansCached (ID INT IDENTITY(1,1) PRIMARY KEY CLUSTERED,
	QueryPlan XML);
INSERT INTO dbo.PlansCached(QueryPlan)
	SELECT SampleQueryPlan
	FROM dbo.CachedPlans;
GO

CREATE PRIMARY XML INDEX PXML_QueryPlan  
    ON dbo.PlansCached (QueryPlan);  
GO 
CREATE XML INDEX Secondary_IXML_QueryPlan
    ON dbo.PlansCached (QueryPlan)
    USING XML INDEX PXML_QueryPlan FOR PATH ;  
GO


sp_BlitzIndex @TableName = 'PlansCached';
/* Bugs or things to be aware of:

* Index definition says "XML" - that's good - doesn't say columns, that's not quite as good
* Size column is empty - definitely wanna show size there
*/
