### ISSUE TITLE
DATABASEPROPERTYEX(@RestoreDatabaseName,'STATUS') returning null when specifying @RestoreDatabaseName and @ExistingDBAction = 1

### ISSUE THREAD

**Issue by jesusnac** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2960]
**Version of the script**
@Version = '8.04', @VersionDate = '20210530';

**What is the current behavior?**
Script skips SINGLE_USER modification failing restore if there is any connected user. Actually the process keeps running even it cannot restore the first backup.

**If the current behavior is a bug, please provide the steps to reproduce.**
Restoring a backup under a different name that matches to an existing database that we want to overwrite.

EXEC DBUTILS.dbo.sp_DatabaseRestore 
@Database = N'Database_Orig',
@RestoreDatabaseName = N'Database_to_orverwrite',
@BackupPathFull = N'F:\Backup\MSSQL14.INSTANCE\SERVER$INSTANC\Database_Orig\FULL\', 
@ExistingDBAction = 1,
@MoveFiles = 1,
@ForceSimpleRecovery = 1,
@RunCheckDB = 1,
@DatabaseOwner = N'sa',
@RunRecovery = 1,
@ContinueLogs = 0,
@Execute = 'Y',
@DEBUG = 1

**Debugging shows that the ALTER DATABASE... SET SINGLE_USER / OFFLINE WITH ROLLBACK IMMEDIATE command never gets executed because DATABASEPROPERTYEX(@RestoreDatabaseName,'STATUS') returns NULL... checking @RestoreDatabaseName variable seems to be quoted**.

**What is the expected behavior?**
Kill the open connections and restore

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
It failed on a SQL Server 2017 on a Windows 2019.

**Resolution**
I think you just need to replace the `DATABASEPROPERTYEX(@RestoreDatabaseName,'STATUS') != 'RESTORING'` bit by `DATABASEPROPERTYEX(@UnquotedRestoreDatabaseName,'STATUS') != 'RESTORING'`

**Comment by BrentOzar** [comment]
Thanks for the report. It sounds like you've got the ability to reproduce this quickly - can you put in a pull request with the changes that fix it? Thanks!

**Comment by BrentOzar** [comment]
Thanks for the pull request! I don't have a testbed for sp_DatabaseRestore at the moment, but just merging into dev, will be in the September release with credit to you in the release notes.
