### ISSUE TITLE
sp_BlitzFirst - Check Id #1 fails on SQL Server 2008R2 due to unavailable column (database_id) in sys.dm_exec_sessions

### ISSUE THREAD

**Issue by danielsuarezdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2961]
Version: 8.05 (20210725)

**Description:**
CheckID 1 fails in SQL Server 10.50.6560.0 in Line 1538 since column database_id is not available for such a build in sys.dm_exec_sessions

![image](https://user-images.githubusercontent.com/51271933/127263597-10bcfd6b-bf8b-41e7-96ca-9004d82465e0.png)

**Steps to reproduce:**
Run sp_BlitzFirst.sql in a SQL Server instance with version 10.50.6560.0

Result
![image](https://user-images.githubusercontent.com/51271933/127263467-db96503c-69b1-4cb9-9909-4a53d674ca70.png)

**Workaround:**
Comment the block for Check 1

**Expected behavior**
I was not able to find a way to fix the issue, but it seems to me that if database_id is required and not available in SQL2008 R2, this check should be only valid for SQL Server 2012+

**Comment by erikdarlingdata** [comment]
It looks like this was introduced in #2941 in the last merge. I'm unsure about continued support for 2008 or 2008R2, but it looks like you could change the view reference to `dm_exec_requests`, if you want to test and submit a pull request.

```
SELECT TOP (1)
    v = 
	   @@VERSION,
	der.database_id,
	der.open_transaction_count
FROM sys.dm_exec_requests AS der;
```

![image](https://user-images.githubusercontent.com/2136037/127342199-3c3ef9d5-5c89-4751-80e9-21ca0943feca.png)

**Comment by Adedba** [comment]
That's my bad! I need to get hold of a dev or express edition of SQL 2008R2 for testing really.

**Comment by BrentOzar** [comment]
Erik - thanks for the pull request! Looks good, merging into the dev branch, will be in the next release with credit to you in the release notes.
