### ISSUE TITLE
sp_BlitzFirst - Check Id #8 fails on SQL Server 2008R2 due to unavailable column (open_transaction_count) in sys.dm_exec_sessions

### ISSUE THREAD

**Issue by danielsuarezdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2962]
Version: 8.05 (20210725)

Description:
CheckID 8 fails in SQL Server 10.50.6560.0 in Lines 1765 and 1776 since column **open_transaction_count** is not available for such a build in sys.dm_exec_sessions

Steps to reproduce:
Run sp_BlitzFirst.sql in a SQL Server instance with version 10.50.6560.0

Result
![image](https://user-images.githubusercontent.com/51271933/127263882-13d823d8-7040-4835-9571-761552dc43d9.png)

Workaround:
Comment the block for Check 8

Expected behaviour
I was not able to find a way to fix the issue, but it seems to me that if open_transaction_count is required and not available in SQL2008 R2, this check should be only valid for SQL Server 2012+

**Comment by erikdarlingdata** [comment]
See [this comment](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/2961#issuecomment-888366401) for follow up.

**Comment by erikdarlingdata** [comment]
@EitanBlumin -- it looks like this came from your pull request. Can you comment on if hitting `sys.dm_exec_requests` instead gets you the correct results, since it has the `open_transaction_count` column?

**Comment by EitanBlumin** [comment]
Hi @erikdarlingdata , as I mentioned in my PR, hitting `sys.dm_exec_requests` would not get the correct results as it would mean the session is not actually sleeping.

I guess something else would need to be used for SQL 2008 R2. Do you happen to recall if, let's say, `sys.dm_tran_session_transactions` exists in SQL 2008 R2?

**Comment by erikdarlingdata** [comment]
@EitanBlumin ooh sorry, I missed that. I just checked my 2008 instance, and that DMV is in there. It looks like you could also hit `sys.sysprocesses`, which is what WhoIsActive and a number of Tiger Toolkit/pssdiag scripts use.

**Comment by EitanBlumin** [comment]
@erikdarlingdata , yeah you're right. I see the `open_tran` column in `sys.sysprocesses` so I guess that could be used to replace `sys.dm_exec_sessions`.

**Comment by erikdarlingdata** [comment]
@EitanBlumin sweet as. Did you wanna work on the issue or leave it open to the community? Thanks!

**Comment by EitanBlumin** [comment]
@erikdarlingdata I'm open to either option. The fix shouldn't be too difficult to implement.
I will probably have time for it sometime during the week.
But if someone does this before me, I wouldn't mind.

**Comment by erikdarlingdata** [comment]
@EitanBlumin cool, I'll leave it be for now. Have a great weekend!

**Comment by EitanBlumin** [comment]
@erikdarlingdata done. Created PR #2978
