### ISSUE TITLE
sp_BlitzIndex - Add optimize_for_sequential_key to analysis

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2963]
**Is your feature request related to a problem? Please describe.**
Check `sys.indexes` for `optimize_for_sequential_key` and include it in findings

**Describe the solution you'd like**
It would be good to know if indexes have this enabled.

**Describe alternatives you've considered**
Starting an advice podcast

**Are you ready to build the code for the feature?**
yesindeedydoody

**Comment by BrentOzar** [comment]
Thanks for the pull request! Love this - I kept thinking about it whenever I read a blog post about this feature, heh. Looks good, merging into dev, will be in the September release with credit to you in the release notes.
