### ISSUE TITLE
Trace flag 8048 warned on server >= SQL 2016

### ISSUE THREAD

**Issue by brettshearer** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2966]
Will probably get around to sending a pull request, but 8048 is suggested for high CMEMTHREAD waits on a version of SQL where it no longer has any effect.

**Comment by erikdarlingdata** [comment]
It does, though, and I end up having to enable it still: https://www.erikdarlingdata.com/sql-server/trace-flag-8048-may-still-be-necessary-after-sql-server-2016/
