### ISSUE TITLE
sp_BlitzIndex - null error when populating #IndexSanitySize

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#297]
From this DBA.se question:
http://dba.stackexchange.com/questions/141303/sp-blitzindex-cannot-insert-the-value-null-into-column-index-sanity-id/141306?noredirect=1#comment267651_141306

The #IndexPartitionSanity table allows nulls on index_sanity_id:

        CREATE TABLE #IndexPartitionSanity
            (
              [index_partition_sanity_id] INT IDENTITY PRIMARY KEY ,
              [index_sanity_id] INT NULL ,

But when we later use this table to populate #IndexSanitySize, that table's index_sanity_id is not nullable:

        CREATE TABLE #IndexSanitySize
            (
              [index_sanity_size_id] INT IDENTITY NOT NULL ,
              [index_sanity_id] INT NOT NULL ,

The insert is done FROM #IndexPartitionSanity, which means sometimes the index_sanity_id could be null. Since the insert groups on index_sanity_id, we should probably just add a filter for it.

Instead of:
                WHERE ipp.database_id = @DatabaseID

Switch to:
                WHERE ipp.database_id = @DatabaseID AND ipp.index_sanity_id IS NOT NULL

Alternate solution: make #IndexSanitySize.index_sanity_id nullable.

**Comment by BlitzErik** [comment]
Adding the where clause made BlitzIndex go from running in 29 seconds to taking 42 seconds. Changing the column to NULLable has no overhead. Going to go with making the column NULLable for now, but will revisit if it causes errors out in the wild. If no objections, I'll close this one for now.

**Comment by BrentOzar** [comment]
Works for me.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by BlitzErik** [comment]
Closing for now.
