### ISSUE TITLE
sp_BlitzWho - Add dm_exec_requests.wait_resource to report and output table.

### ISSUE THREAD

**Issue by davidhooey** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2970]
**Is your feature request related to a problem? Please describe.**

I often use sp_BlitzWho to track blocking situations it would be nice to be able to see the type of resource being blocked such as `KEY: 5:72057594044350464 (557abd962af2)`. It would indicate if row level, page level, or object level lock is in place.

**Describe the solution you'd like**

Add this column to the output table and report.

**Are you ready to build the code for the feature?**

I can work on this, however I do not have all versions of SQL Server to test.

**Comment by BrentOzar** [comment]
This would definitely be something you would need to code if it’s important to you. Do you want to tackle it, or should I close the issue?

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by davidhooey** [comment]
I will give it a go. 😊 From: Brent Ozar ***@***.***>Date: Wednesday, August 4, 2021 at 11:45 AMTo: BrentOzarULTD/SQL-Server-First-Responder-Kit ***@***.***>Cc: davidhooey ***@***.***>, Author ***@***.***>Subject: Re: [BrentOzarULTD/SQL-Server-First-Responder-Kit] sp_BlitzWho - Add dm_exec_requests.wait_resource to report and output table. (#2970)This would definitely be something you would need to code if it’s important to you. Do you want to tackle it, or should I close the issue?---Tiny glass keyboardTypos flowing like riversAs winter snow thaws> On Aug 4, 2021, at 3:22 PM, davidhooey ***@***.***> wrote:> > ﻿> Is your feature request related to a problem? Please describe.> > I often use sp_BlitzWho to track blocking situations it would be nice to be able to see the type of resource being blocked such as KEY: 5:72057594044350464 (557abd962af2). It would indicate if row level, page level, or object level lock is in place.> > Describe the solution you'd like> > Add this column to the output table and report.> > Are you ready to build the code for the feature?> > I can work on this, however I do not have all versions of SQL Server to test.> > —> You are receiving this because you are subscribed to this thread.> Reply to this email directly, view it on GitHub, or unsubscribe.> Triage notifications on the go with GitHub Mobile for iOS or Android.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, merging into dev, will be in the September release with credit to you in the release notes.

**Comment by davidhooey** [comment]
Awesome. Thanks!
