### ISSUE TITLE
sp_BlitzFirst - USE statement causes failure in Azure SQLDB, et al

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2971]
**Version of the script**
In CheckId 29, there's an unnecessary `USE` statement in the dynamic SQL, because the DMV in use is already prefixed with `tempdb`:

```
FROM tempdb.sys.dm_db_index_operational_stats(DB_ID(''tempdb''), NULL, NULL, NULL) os
    LEFT OUTER JOIN #TempdbOperationalStats os_prior ON os.object_id = os_prior.object_id
```

**What is the current behavior?**
`USE` statement causes an error.

**If the current behavior is a bug, please provide the steps to reproduce.**
Run proc in Cloud Nonsense™

**What is the expected behavior?**
Remove the `USE` statement at the beginning

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Azureness

**Comment by BrentOzar** [comment]
Looks good! Thanks for the pull request. Merged into the dev branch, and will be in the next release along with credit to the Grand Trunk.
