### ISSUE TITLE
Error in InstallAllScripts for sp_BLitzLock on SQL Server 2008R2

### ISSUE THREAD

**Issue by Shashahan** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2974]
**Version of the script**
 @Version = '8.05', @VersionDate = '20210725

**What is the current behavior?**
Following error is thrown when running the script:
Msg 102, Level 15, State 1, Procedure sp_BlitzLock, Line 317
Incorrect syntax near 'THROW'.

The procedure is created but has no parameters. Scripting out the sp_BlitzLock procedure reveals the following code:
```
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_BlitzLock] AS RETURN 0;
GO
```
**If the current behavior is a bug, please provide the steps to reproduce.**
Run the script to install all procedures

**What is the expected behavior?**
Script is running with no errors

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2008R2 version 10.50.4321.0 (X64) on Window Server 2008R2
SQL Server 2008R2 version 10.50.6560.0 (X64) on Windows Server 2012R2

Tested with script versions
@Version = '8.05', @VersionDate = '20210725'
@Version = '8.04', @VersionDate = '20210530'
@Version = '8.01', @VersionDate = '20210222'

all show the same behaviour.

Kind Regards,
Olaf

**Comment by BrentOzar** [comment]
Make sure to check the readme for the scripts. sp_BlitzLock isn't supported on SQL Server 2008R2.
