### ISSUE TITLE
Add "SET TRUSTWORTHY ON" option on SP_DATABASERESTORE

### ISSUE THREAD

**Issue by jesusnac** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2981]
**Is your feature request related to a problem? Please describe.**
Not really a problem but an improvement. In order to use sp_DatabaseRestore on database deployment automation it would be quite useful adding the option of enabling the TRUSTWORHY property on the database after restoring with recovery.

**Describe the solution you'd like**
Basically add a new BIT parameter named @SetTrustworthyON to the SP and then the following bit after the @DatabaseOwner option implementation (about line 1460 on current source)

    IF @SetTrustworthyON = 1
	    BEGIN
		    IF @RunRecovery = 1
		    BEGIN
			    IF IS_SRVROLEMEMBER('sysadmin') = 1
			    BEGIN
				    SET @sql = N'ALTER DATABASE ' + @RestoreDatabaseName + N' SET TRUSTWORTHY ON;';

					    IF @Debug = 1 OR @Execute = 'N'
					    BEGIN
						    IF @sql IS NULL PRINT '@sql is NULL for SET TRUSTWORTHY ON';
						    PRINT @sql;
					    END;

				    IF @Debug IN (0, 1) AND @Execute = 'Y'
					    EXECUTE @sql = [dbo].[CommandExecute] @DatabaseContext=N'master', @Command = @sql, @CommandType = 'ALTER DATABASE', @Mode = 1, @DatabaseName = @UnquotedRestoreDatabaseName, @LogToTable = 'Y', @Execute = 'Y';
			    END
			    ELSE
			    BEGIN
				    PRINT 'Current user''s login is NOT a member of the sysadmin role. Database TRUSTWORHY bit has not been enabled.';
			    END
		    END
		    ELSE
		    BEGIN
			    PRINT @RestoreDatabaseName + ' is still in Recovery, so we are unable to enable the TRUSTWORHY bit.';
		    END
	    END;

**Are you ready to build the code for the feature?**
Yes, it is as simple as mentioned before.

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, merging into dev, will be in the September release with credit to you in the release notes.
