### ISSUE TITLE
sp_Blitz: Add Trace flag 1204 To Known Trace Flags With Reason

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2985]
**Is your feature request related to a problem? Please describe.**
When you run Blitz on a server with 1204 and 1222 enabled, only 1222 is identified as being involved with getting deadlock information.

**Describe the solution you'd like**
Add 1204 to the list of trace flags with known behavior

**Describe alternatives you've considered**
Adding [all known trace flags](https://github.com/ktaranov/sqlserver-kit/blob/master/SQL%20Server%20Trace%20Flag.md)

**Are you ready to build the code for the feature?**
Yep, it's a one line change.

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, wow, can't believe we didn't have that in there before. Merging into dev, will be in the September release with credit to you in the release notes.
