### ISSUE TITLE
sp_BlitzWho does not cleanup output table

### ISSUE THREAD

**Issue by albertogastaldo70** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2988]
**Version of the script**
v. 8.05 dated 20210725

**What is the current behavior?**
The output table is never  cleaned-up 

**If the current behavior is a bug, please provide the steps to reproduce.**

Using the Sp with the following parameters:
EXEC MaintenanceDB.dbo.sp_BlitzWho 
  @OutputDatabaseName = 'MaintenanceDB', 
  @OutputSchemaName = 'dbo',
  @OutputTableName = 'BlitzWho_Results',
  @OutputTableRetentionDays = 3,
  @ExpertMode = 1

The internal query that creates the DELETE statement use
IF EXISTS(
SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE QUOTENAME(SCHEMA_NAME) = @OutputSchemaName
)
QUOTENAME(SCHEMA_NAME) returns [dbo] while @OutputSchemaName is just dbo and the two do not match,
As a result, no action is taken and the table is never cleaned up.

**What is the expected behavior?**
Cleanup should occur after the time specified in @OutputTableRetentionDays  

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Running on SQL 2017 EE CU24
Never tried on previous versions.

**Comment by BrentOzar** [comment]
OK, if that's important to you, we'd welcome a pull request with the changes necessary to get that implemented. To get started, here's the contributing guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/main/CONTRIBUTING.md

If you don't submit a pull request in the next month or so, we'll go ahead and close this issue. Thanks!

**Comment by andreasjordan** [comment]
Hi @albertogastaldo70 - line 131 says `@OutputSchemaName = QUOTENAME(@OutputSchemaName)` so the input is quoted before used. And the DELETE works on my maschine. If it does not on your maschine, this might have other reasons. Do you need help?

**Comment by albertogastaldo70** [comment]
Hi @andreasjordan yes, you're right. I double-checked and realize that cleanup is happening.
Don't know why initially it did not work, it seemed a problem related to that server.

**Comment by andreasjordan** [comment]
Great to hear that. As you have opened the issue, you could probably also close it.
