### ISSUE TITLE
sp_DatabaseRestore fails when extra text files present in backup directory

### ISSUE THREAD

**Issue by drothgerySSNI** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2989]
**Version of the script**
8.05 / 2021-07-05

**What is the current behavior?**

1. Use Ola's dbo.DabaseBackup script to create a multi-file backup into a folder.
2. Add a text file to that folder
3. Run sp_DatabaseRestore pointing to the folder (not individual files)
4. Error Message
System.Data.SqlClient.SqlException (0x80131904): The volume on device '\\MyBackupShare\MyServerName\MyDbName\FULL\File Name.txt' is empty. RESTORE FILELIST is terminating abnormally. The volume on device '\\MyBackupShare\MyServerName\MyDbName\FULL\File Name.txt' is empty. RESTORE HEADERONLY is terminating abnormally. Backupfile "File Name.txt" does not match @Database parameter 

**What is the expected behavior?**

Non-.bak files in the backup directory are ignored

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Error occurring on SQL Server 2019 Standard / Windows Server 2019 Standard; other versions not tested.
Unknown if this worked on previous versions.

**Comment by BrentOzar** [comment]
OK, if that's important to you, we'd welcome a pull request with the changes necessary to get that implemented. To get started, here's the contributing guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/main/CONTRIBUTING.md

If you don't submit a pull request in the next month or so, we'll go ahead and close this issue. Thanks!
