### ISSUE TITLE
sp_BlitzIndex: modification on Sep, 6 breaks the execution

### ISSUE THREAD

**Issue by FlatlandR** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2991]
**Version of the script**
SELECT @Version = '8.05', @VersionDate = '20210725';

**What is the current behavior?**
Running the modified verson of sp_BlitzIndex generates an error:
Msg 50000, Level 16, State 7, Procedure sp_Blitzindex, Line 2203 [Batch Start Line 0]
[X] database failed to process. Column name or number of supplied values does not match table definition.

Needed the latest version for a minor bug issue. 

**Fix**
Table #IndexSanity has an extra column [optimize_for_sequential_key]. That column is part of the dynamic SQL starting at line 1299:

```
CASE
	WHEN @OptimizeForSequentialKey = 1
	THEN N', si.optimize_for_sequential_key'
	ELSE N', CONVERT(BIT, NULL) AS optimize_for_sequential_key'
END
```

The insert into #IndexSanity at line 1377 does not specify this column:

```
INSERT    #IndexSanity ( ...,  filter_definition, user_seeks, user_scans, ... )
EXEC sp_executesql @dsql, @params = N'@i_DatabaseName NVARCHAR(128)', @i_DatabaseName = @DatabaseName;

```
To fix it add column name [optimize_for_sequential_key] in the insert between columns filter_definition and user_seeks.

**Comment by erikdarlingdata** [comment]
That's *really* weird. I had tested this and got a correct result for a couple tables where this is enabled. I must have ctrl+z backtracked too far at some point.

Thanks!
