### ISSUE TITLE
sp_BlitzIndex: Check 94 (Check Constraints That Reference Functions) can give an incorrect result

### ISSUE THREAD

**Issue by FlatlandR** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2992]
**Version of the script**
SELECT @Version = '8.05', @VersionDate = '20210725', @Check_id = 94;

**What is the current behavior?**
When a check constraint contains a fully qualified column name (i.e. with table name in front of it) that check constraint is reported as a Serial Forcer: Check Constraint with Scalar UDF

**If the current behavior is a bug, please provide the steps to reproduce.**

Add 2 check constraints to table Comments in the StackOverflow database:
```
ALTER TABLE Comments ADD CONSTRAINT ckc_Score CHECK (Score != -100000 ); 
ALTER TABLE Comments ADD CONSTRAINT ckc_Score2 CHECK (Comments.Score != -100000 ); 
```

And run sp_BlitzIndex. Result:
The check constraint [ckc_Score2] on [dbo].[Comments] is based on ([Comments].[Score]<>(-100000)). That indicates it may reference a scalar function, or a CLR function with data access, which can cause all queries and maintenance to run serially.

**Why**
The code for determining whether the check constraints (the Dynamic SQL for the insert #CheckConstraints) contains:
`
CASE WHEN cc.definition LIKE ''%|].|[%'' ESCAPE ''|'' THEN 1 ELSE 0 END AS is_function`

**Alternative**
An alternative solution is to use a CTE to find if check constraint uses a function:
```
WITH ConstraintsWithFunction AS
    (   SELECT
            o.[name] AS used_function,
            SCHEMA_NAME(referenced_objext.[schema_id]) AS [used_schema],
            referenced_objext.[object_id],
            referenced_objext.[name] AS [referenced_object]
        FROM sys.objects o
            JOIN sys.sql_expression_dependencies AS dep ON o.[object_id] = dep.referenced_id
            JOIN sys.objects AS referenced_objext ON dep.referencing_id = referenced_objext.[object_id]
        WHERE o.[type] in ('FN', 'TF', 'IF') /* finding the functions */
            AND referenced_objext.[type_desc] = 'CHECK_CONSTRAINT' /* ... in the check constraints */
    )
SELECT /* combining with code from sp_BlitzIndex */
    t.[name] AS table_name,
    s.[name] AS [schema_name],
    --> cc.[object_id] AS constraint_object_id,
       cc.[name] AS constraint_name,
    cc.[definition],
    CASE WHEN cc.[definition] LIKE '%|].|[%' ESCAPE '|' THEN 1 ELSE 0 END AS is_function_blitzindex, /* current */
    CASE WHEN cwf.[object_id] IS NULL THEN 0 ELSE 1 END AS is_function_cte /* proposed */
FROM sys.check_constraints AS cc
    JOIN sys.tables AS t ON t.[object_id] = cc.parent_object_id
    JOIN sys.schemas AS s ON s.[schema_id] = t.[schema_id]
    LEFT JOIN ConstraintsWithFunction AS cwf ON cwf.[object_id] = cc.[object_id] AND cwf.used_schema = s.[name]
ORDER BY is_function DESC
OPTION (RECOMPILE);
```

Implemented in the Dynamic SQL gives:

```
 SET @dsql=N'
WITH ConstraintsWithFunction AS
(   SELECT
		o.[name] AS used_function,
		SCHEMA_NAME(referenced_objext.[schema_id]) AS [used_schema],
		referenced_objext.[object_id],
		referenced_objext.[name] AS [referenced_object]
	FROM sys.objects o
		JOIN sys.sql_expression_dependencies AS dep ON o.[object_id] = dep.referenced_id
		JOIN sys.objects AS referenced_objext ON dep.referencing_id = referenced_objext.[object_id]
	WHERE o.[type] in (''FN'', ''TF'', ''IF'') /* finding the functions */
		AND referenced_objext.[type_desc] = ''CHECK_CONSTRAINT'' /* ... in the check constraints */
)             
SELECT DB_ID(@i_DatabaseName) AS [database_id], 
	   @i_DatabaseName AS database_name,
	   t.name AS table_name,
	   s.name AS schema_name,
	   cc.name AS constraint_name,
	   cc.is_disabled,
	   cc.definition,
	   cc.uses_database_collation,
	   cc.is_not_trusted,
	   /* CASE WHEN cc.definition LIKE ''%|].|[%'' ESCAPE ''|'' THEN 1 ELSE 0 END AS is_function, */
	   CASE WHEN cwf.[object_id] IS NULL THEN 0 ELSE 1 END AS is_function,
	   ''ALTER TABLE '' + QUOTENAME(s.name) + ''.'' + QUOTENAME(t.name) + 
	   '' ADD CONSTRAINT '' + QUOTENAME(cc.name) + '' CHECK '' + cc.definition  + '';'' COLLATE DATABASE_DEFAULT AS [column_definition]
FROM    ' + QUOTENAME(@DatabaseName) + N'.sys.check_constraints AS cc
JOIN    ' + QUOTENAME(@DatabaseName) + N'.sys.tables AS t
ON      t.object_id = cc.parent_object_id
JOIN    ' + QUOTENAME(@DatabaseName) + N'.sys.schemas AS s
ON      s.schema_id = t.schema_id
LEFT JOIN ConstraintsWithFunction AS cwf ON cwf.[object_id] = cc.[object_id] AND cwf.used_schema = s.[name]
OPTION (RECOMPILE);';
```

**Test**
To check if the code works we need an oversimplified function:
```
CREATE FUNCTION dbo.ReturnOne ( @d DATETIME2(7))
RETURNS BIT
WITH RETURNS NULL ON NULL INPUT
AS
    BEGIN
        RETURN 1;
    END;
GO
```

And to apply it to a smallish table:
`ALTER TABLE dbo.Users ADD CONSTRAINT ckc_IsDate CHECK ( dbo.ReturnOne(CreationDate) = 1 );`

Running sp_BlitzIndex now shows the expected result, the check constraint with the function.

**Cleaning up**
```
ALTER TABLE Users DROP CONSTRAINT ckc_IsDate; 
DROP FUNCTION ReturnOne;
ALTER TABLE Comments DROP CONSTRAINT ckc_Score; 
ALTER TABLE Comments DROP CONSTRAINT ckc_Score2; 
```

**Drawback!**
I have never used a CLR function with data access, so I do not know how to test that. It may be that my proposed solution messes this part up. If I recall correctly, even ErikDarling had problems with CLR functions... so mere mortals should not use it unless forced. So there another check is needed.

**Comment by erikdarlingdata** [comment]
Hi -- yeah, I'm aware of the false positives here -- that's why the details are worded as *That indicates it may reference a scalar function*. A bit lazy, for sure, but I hit very few false positives in general so I never put more time into it.

Anyway, I like your solution,  just don't forget to add the database name prefix to your CTE, or else it won't work cross-database. 

This has me thinking about a way to get the same thing for the check on Computed Columns based on Scalar UDFs. It'd make sense to make both more correct. 

As for CLR UDFs, I don't think I've ever looked into identifying if they touch data or just process inputs. I looked around in the various assembly views but didn't see anything obvious. I don't have a problem with them in general, though. They can be quite useful, and are often far better at string manipulation than T-SQL.

![image](https://user-images.githubusercontent.com/2136037/132993145-d9139466-e6ad-42ce-afc2-570159cf6cae.png)

Anyway, I didn't see in the issue if this is code you're going to contribute or not. If you are, I'll assign the issue to you.

Thanks!

**Comment by BrentOzar** [comment]
@FlatlandR just to make it clear what the next step is - you can open a pull request with your changes, including Erik's recommendations, and then we can get that into the dev branch for future release. Thanks!

**Comment by BrentOzar** [comment]
I haven't heard back from you, so I'll go ahead and close this. If you decide you want to tackle it, just drop a note in here and we can reopen it for you when you're ready to work on it. Have a good weekend!
