### ISSUE TITLE
Add the Email Recipient Feature from sp_Blitz to sp_BlitzCache and sp_BlitzIndex

### ISSUE THREAD

**Issue by bojanderson** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2994]
**Is your feature request related to a problem? Please describe.**
The sp_BlitzCache and sp_BlitzIndex stored procedures allow you to output results into an Output Table just like sp_Blitz does. However they do not allow you to email the results to recipients. My team has discussed running sp_BlitzCache and sp_BlitzIndex regularly and dumping them in an output table but also emailing the results to ourselves like we do with sp_Blitz. However neither stored procedure has the EmailRecipients and EmailProfile like sp_Blitz does.

I have reviewed closed issues and to the best of my abilty I couldn't find an example of anybody ever asking for this before.

**Describe the solution you'd like**
I would like to add the functionality from sp_Blitz that uses the EmailRecipients and EmailProfile parameters and add those parameters to sp_BlitzCache and sp_BlitzIndex. And then similar to sp_Blitz right before we log the results to an Output table if those parameters are populated run the sp_send_dbmail and send the results out if they are specified.

**Describe alternatives you've considered**
I have considered creating a SQL Job to query the results from the Output Tables from both SPs and then email those results, and that's a totally viable option if this Feature Request is denied. However since I'm already using the Email feature in sp_Blitz I figured it only made sense to be consistent and try and use each SP the same way if possible.

**Are you ready to build the code for the feature?**
I am ready to build this feature, I cannot start on it this week, but I could start on it during the week of September 20th and I believe I would have it completed within 30 days of starting it (or sooner if need be).

**Comment by BrentOzar** [comment]
Sure, makes sense. Just be careful about which columns you email since the query plans and queries can end up pretty large.

**Comment by BrentOzar** [comment]
It's been another month, so I'll go ahead and close this for now. If you want to return to working on it, let me know and I can reopen it. Thanks!
