### ISSUE TITLE
sp_BlitzFirst - Table for @OutputTableNameBlitzCache not filled if @OutputType = 'NONE' 

### ISSUE THREAD

**Issue by andreasjordan** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2998]
**Version of the script**

Current dev-branch downloaded and installed with `Install-DbaFirstResponderKit -SqlInstance sql01\prod -Branch dev -OnlyScript Install-Core-Blitz-No-Query-Store.sql -Force`
Source code says: `SELECT @Version = '8.06', @VersionDate = '20210914';`

**What is the current behavior?**
**If the current behavior is a bug, please provide the steps to reproduce.**

I use this command:
```
master.dbo.sp_BlitzFirst 
  @OutputType = 'NONE'
, @OutputDatabaseName = 'BlitzMonitoring'
, @OutputSchemaName = 'dbo'
, @OutputTableName = 'BlitzFirst'
, @OutputTableNameFileStats = 'BlitzFirst_FileStats'
, @OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats'
, @OutputTableNameWaitStats = 'BlitzFirst_WaitStats'
, @OutputTableNameBlitzCache = 'BlitzCache'
, @OutputTableNameBlitzWho = 'BlitzWho'
```
I use `@OutputType = 'NONE'` because I don't need any output and just want the tables to be filled. But the table BlitzCache is not filled.

This command fills the table, but also outputs two resultsets, one with the output of sp_BlitzCache and one with the "classic" output from sp_BlitzFirst (sp_BlitzFirst 2021-09-14 00:00:00.0000000 +00:00, Server Info, Thanks!):

```
master.dbo.sp_BlitzFirst 
  @OutputDatabaseName = 'BlitzMonitoring'
, @OutputSchemaName = 'dbo'
, @OutputTableName = 'BlitzFirst'
, @OutputTableNameFileStats = 'BlitzFirst_FileStats'
, @OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats'
, @OutputTableNameWaitStats = 'BlitzFirst_WaitStats'
, @OutputTableNameBlitzCache = 'BlitzCache'
, @OutputTableNameBlitzWho = 'BlitzWho'
```

**What is the expected behavior?**
I would expect that the table for @OutputTableNameBlitzCache gets filled like all other tables do, even when using @OutputType = 'NONE'

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
This SQL Server 2017 on Windows Server 2016 Core and I don't know if this worked in previous versions of the procedure.

**Comment by andreasjordan** [comment]
Will start looking at the code now to find the bug and then I will provide a pull request to fix it.

If this is no bug but expected behaviour, please let me know.

**Comment by andreasjordan** [comment]
This code looks like sp_BlitzCache should write to the table and sp_BlitzFirst does everything right:
```
                IF(@OutputType = 'NONE')
				BEGIN 
                    EXEC sp_BlitzCache
                        @OutputDatabaseName = @UnquotedOutputDatabaseName,
                        @OutputSchemaName = @UnquotedOutputSchemaName,
                        @OutputTableName = @OutputTableNameBlitzCache,
                        @CheckDateOverride = @StartSampleTime,
                        @SortOrder = 'all',
                        @SkipAnalysis = @BlitzCacheSkipAnalysis,
                        @MinutesBack = @BlitzCacheMinutesBack,
                        @Debug = @Debug,
					    @OutputType = @OutputType
				    ;
				END;
				ELSE
				BEGIN
				
				    EXEC sp_BlitzCache
                        @OutputDatabaseName = @UnquotedOutputDatabaseName,
                        @OutputSchemaName = @UnquotedOutputSchemaName,
                        @OutputTableName = @OutputTableNameBlitzCache,
                        @CheckDateOverride = @StartSampleTime,
                        @SortOrder = 'all',
                        @SkipAnalysis = @BlitzCacheSkipAnalysis,
                        @MinutesBack = @BlitzCacheMinutesBack,
                        @Debug = @Debug
				    ;
				END;
```
Sorry for the indention - the source code mixes blanks and tabs. Time for reformatting?

**Comment by andreasjordan** [comment]
Changing `NONE` to `SomethingElse` in this line helps:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/e21adb82cd8c4d8b00bcfb27867b7ca3edf730d4/sp_BlitzCache.sql#L6916

Then the table is filled. But there is also an output. So maybe we have add an else block and change the parameters there. I'll try...

**Comment by andreasjordan** [comment]
I now think the key is the `@SortOrder = 'all'`. 

This works as expected, filling the table (with the default `@SortOrder VARCHAR(50) = 'CPU'`) and not showing a resultset:
```
EXEC sp_BlitzCache
    @OutputDatabaseName = 'BlitzMonitoring',
    @OutputSchemaName = 'dbo',
    @OutputTableName = 'BlitzCache',
    @OutputType = 'NONE'
```

But this does not show anything:
```
EXEC sp_BlitzCache
    @OutputDatabaseName = 'BlitzMonitoring',
    @OutputSchemaName = 'dbo',
    @OutputTableName = 'BlitzCache',
    @OutputType = 'NONE',
    @SortOrder = 'ALL'
```

The reason is, that the output to the table is grabbed from ##BlitzCacheProcs, but the table is not used with sort order ALL. Instead, the table #bou_allsort is used to gather the results recursivly and to return them to the user.

**Comment by andreasjordan** [comment]
On the other hand: `@SortOrder = 'all'` executes sp_BlitzCache with different `@SortOrder = 'xyz` and includes all parameters to fill the output table. So the individual calls should all fill the output table...

**Comment by andreasjordan** [comment]
Ok, the bug was introduced here: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/2817

**Comment by andreasjordan** [comment]
Some more infos about this. `@AllSortSql` contains the varous `INSERT #bou_allsort (...) EXEC sp_BlitzCache ...` to get the results for different @SortOrder, but at the end also the `SELECT ... FROM #bou_allsort` that outputs the results to the user. This last step should be suppressed with `@OutputType = 'NONE'`, while the rest has to be executed to let the individual `EXEC sp_BlitzCache` write to the output table.

So the ` IF(@OutputType <> 'NONE')` should not suppress `EXEC sys.sp_executesql @stmt = @AllSortSql, ...` but only suppress lines 6718 to 6724 and lines 6894 to 6900.

Will try to open a pull request for that.

**Comment by BrentOzar** [comment]
Looks good! Thanks for the pull request. Merging into the dev branch, will be in the next release with credit to you in the release notes. You don't have to worry about the AllSort one if you don't need it for your own use cases, but we'd welcome a pull request for that too - either way is good. Thanks!
