### ISSUE TITLE
sp_BlitzIndex: Check 100 includes nondeterministic columns

### ISSUE THREAD

**Issue by tonyfountain** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3001]
**Version of the script**
Version: 8.06
Version Date: 20210914

**What is the current behavior?**
Includes nondeterministic columns with recommendations to persist the computed column.

**If the current behavior is a bug, please provide the steps to reproduce.**
I wouldn't say so much a bug as an oversight ;)

**What is the expected behavior?**
Nondeterministic columns cannot be persisted.  The query should be modified to include:
`WHERE COLUMNPROPERTY(t.object_id, c.name, ''IsDeterministic'') = 1`

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All versions that support computed columns.

**Comment by erikdarlingdata** [comment]
@tonyfountain thanks for bringing this up! Were you planning on contributing a pull request to correct the query?

**Comment by tonyfountain** [comment]
@erikdarlingdata I can definitely do the pull request.  Give me a day or two, swamped with work, family stuff, and a partial home remodel ;)

**Comment by erikdarlingdata** [comment]
@tonyfountain no rush at all. I've assigned the issue to you. Please leave a note if you don't think you'll be able to get to it for any reason.

**Comment by BrentOzar** [comment]
I haven't heard back from you, so I'll go ahead and close this. If you decide you want to tackle it, just drop a note in here and we can reopen it for you when you're ready to work on it. Have a good weekend!
