### ISSUE TITLE
sp_BlitzCache sorted for duration results in "String or binary data would be truncated" error

### ISSUE THREAD

**Issue by osudude** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3002]
**Version of the script**
SELECT @Version = '8.06', @VersionDate = '20210914';
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**
run the following
`exec sp_BlitzCache @SortOrder = 'duration', @Top = 30`

Here is the output / error:

> Getting information about implicit conversions and stored proc parameters
> Getting variable info
> Getting conversion info
> Parsing conversion info
> Msg 8152, Level 16, State 13, Procedure sp_BlitzCache, Line 3712 [Batch Start Line 18]
> String or binary data would be truncated.
> The statement has been terminated.
> Updating variables for inserted procs

**What is the expected behavior?**
Run without error

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Microsoft SQL Server 2014 (SP2-CU10-GDR) (KB4052725) - 12.0.5571.0 (X64)   Jan 10 2018 15:52:08   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: )

**Comment by erikdarlingdata** [comment]
Thanks for the report! But there's no way anyone can figure out what happened based on the details you've provided, here.

Can you run the proc again with `@Debug = 1`, and post the data that ends up in the `#conversion_info` table?

Thanks!

**Comment by osudude** [comment]
Well this is embarrassing. It's now working and I can't get it to fail.    (˵ ͡° ͜ʖ ͡°˵)

**Comment by BrentOzar** [comment]
Hahaha, we love fixes like that, closing.
