### ISSUE TITLE
non-aligned indexes

### ISSUE THREAD

**Issue by MehdiGhvi** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3005]
Hi Brent!
I ran Sp_blitz on a server and it showed that,
Having non-aligned indexes on partitioned tables may cause inefficient query plans and CPU pressure.
The biggest problem with aligned non-clustered index is that it changes the execution plans of the
queries. unfortunately, it reduces query performance.  
Please look at the following example:

Create Database Test
GO

Use Test
GO

CREATE TABLE dbo.DATA
(
  ID INT NOT NULL,
  DATECREATED DATETIME NOT NULL
  CONSTRAINT DEF_DATA_DATECREATED DEFAULT GETUTCDATE(),
  DATEMODIFIED DATETIME NOT NULL
  CONSTRAINT DEF_DATA_DATEMODIFIED DEFAULT GETUTCDATE(),
  PLACEHOLDER CHAR(500) NULL
);

DECLARE @STARTDATE DATETIME = '2016-01-01';
;WITH N1(C) AS (SELECT 0 UNION ALL SELECT 0) -- 2 ROWS
,N2(C) AS (SELECT 0 FROM N1 AS T1 CROSS JOIN N1 AS T2) -- 4 ROWS
,N3(C) AS (SELECT 0 FROM N2 AS T1 CROSS JOIN N2 AS T2) -- 16 ROWS
,N4(C) AS (SELECT 0 FROM N3 AS T1 CROSS JOIN N3 AS T2) -- 256 ROWS
,N5(C) AS (SELECT 0 FROM N4 AS T1 CROSS JOIN N4 AS T2) -- 65,536 ROWS
,N6(C) AS (SELECT 0 FROM N5 AS T1 CROSS JOIN N2 AS T2 CROSS JOIN N1 AS T3) -- 524,288 
,IDS(ID) AS (SELECT ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) FROM N6)
INSERT INTO dbo.DATA WITH (TABLOCK)(ID, DATECREATED, DATEMODIFIED)
SELECT ID, DATEADD(SECOND,35 * ID,@STARTDATE),
CASE
WHEN ID % 10 = 0
THEN DATEADD(SECOND, 24 * 60 * 60 * (ID % 31) + 11200 + ID % 59 + 35 * ID,
@STARTDATE)
ELSE DATEADD(SECOND,35 * ID,@STARTDATE)
END
FROM IDS;
GO

CREATE PARTITION FUNCTION PFDATA(DATETIME)
AS RANGE RIGHT FOR VALUES
('2016-02-01', '2016-03-01','2016-04-01','2016-05-01','2016-06-01','2016-07-01','2016-08-01');

CREATE PARTITION SCHEME PSDATA AS PARTITION PFDATA ALL TO ([Primary]);

CREATE UNIQUE CLUSTERED INDEX IDXDATAID
ON DBO.DATA(DATECREATED, ID)
WITH (DATA_COMPRESSION = PAGE)
ON PSDATA(DATECREATED);

CREATE NONCLUSTERED INDEX IDXDATADATEMODIFIED
ON DBO.DATA(DATEMODIFIED)
WITH (DATA_COMPRESSION = PAGE)
ON [Primary]
GO

CREATE PROCEDURE USP_TEST
(@TOP TINYINT, @LASTDATEMODIFIED DATETIME)
AS
SELECT TOP (@TOP) ID, DATECREATED, DATEMODIFIED, PLACEHOLDER
FROM dbo.DATA
WHERE DATEMODIFIED > @LASTDATEMODIFIED
ORDER BY DATEMODIFIED
GO

EXEC USP_TEST 100, '2016-08-25 00:00:00.000' 

![1](https://user-images.githubusercontent.com/80213299/135858202-9008fa08-048f-40a6-80c6-148f1e4c1ba2.png)

-- logical reads 218

CREATE NONCLUSTERED INDEX IDXDATADATEMODIFIED
ON DBO.DATA(DATEMODIFIED)
WITH (DATA_COMPRESSION = PAGE, DROP_EXISTING = ON)
ON PSDATA(DATECREATED);
GO

EXEC USP_TEST 100, '2016-08-25 00:00:00.000'

![2](https://user-images.githubusercontent.com/80213299/135858173-e2ba9274-9c7a-423c-9e12-a81089ae18d6.png)

-- logical reads 1113

Thanks!

**Comment by BrentOzar** [comment]
Hello. When you open an issue here in Github, there is a text template with specific questions that help us understand the problem you're having with the scripts. It's really helpful because I get hundreds of emails a day, and I need to be able to move quickly.

When you created this issue, you deleted all of that, and you wrote something else. I don't really understand what issue you're asking me to solve.

Can you try again, creating the issue but leaving the question text in place, so I and the other volunteers here can understand what problem you need us to solve? Thanks!

**Comment by MehdiGhvi** [comment]
Having non-aligned indexes on partitioned tables may cause inefficient
query plans and CPU pressure.
While I sent you a great example on github that shows aligned non-clustered
indexes change the execution plans of the queries and reduce query
performance.
What are potential issues in data partitioning?
I don't expect you to answer my question.
I will send you my question on pollgab.
I don't want to try again on github.
Regards!

**Comment by BrentOzar** [comment]
OK, gotcha. Yeah, I can't really do free training here on Github, and I'm going to be honest: that question is a little too big for PollGab as well. Your best bet there would be to attend my Mastering Index Tuning class, where we cover partitioning (among lots of other stuff.) See you in class!

**Comment by MehdiGhvi** [comment]
Good to know, I use non-aligned nonclustered indexes on the partitioned
table with five billion rows without any performance issues. So I can not
understand why sp_blitz tell me,
Having non-aligned indexes on partitioned tables may cause inefficient
query plans and CPU pressure.

Please see the following book if you interested:
Pro SQL Server Internals
Publishers Apress; 2nd ed. edition (December 1, 2016)
It is written on page 369 onwards.
Good luck.
