### ISSUE TITLE
sp_BlitzIndex: Unique Constraint Creation Scripting Doesn't Include Column Names

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3006]
**Version of the script**
Latest -- this is my blunder in #2950 

**What is the current behavior?**
It scripts out the drops correctly, but the creation scripts you get back from `@Mode = 4` don't bring column names back with them like they do for primary keys.

**If the current behavior is a bug, please provide the steps to reproduce.**
Run like modes 0 or 4 against a database with unique constraints.

**What is the expected behavior?**
Script the full definition

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
No versions are idiot proof 🤦‍♂️

**Comment by BrentOzar** [comment]
Looks good! Thanks for the pull request. Merging into the dev branch, will be in the next release with credit to you in the release notes.
