### ISSUE TITLE
sp_AllNightLog procs should automatically be created in the database where Ola Hallengren's scripts are located

### ISSUE THREAD

**Issue by nick-fotopoulos** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3009]
SSFRK = SQL Server First Responders Kit
OHDMS = Ola Hallengren's Database Maintenance Solution

**Is your feature request related to a problem? Please describe.**
Problems:
1. sp_DatabaseRestore - is created in the same database context that the scripts are run in, but all sanity test and calls to the stored proc are hard coded to master.dbo.sp_DatabaseRestore. If you install the scripts in database XYZ, the proc will be created as XYZ.dbo.sp_DatabaseRestore, but the code will still look for the proc in master.
2. CommandExecute - Calls to this proc will always look in the current database context, but the sanity checks are hard coded to look in master.dbo.CommandExecute. OHDMS script test can find the script in master, but the calls could still fail if SSFRK was installed somewhere other than master. If OHDMS and SSFRK are installed in the same database (but not master) the OHDMS script test will indicate a failure to locate the proc, but the calls to that proc will work as expected. Installing OHDMS and SSFRK into master mask these bugs because dbo.CommandExecute and master.dbo.CommandExecute refer to the same proc.
3. DatabaseBackup - [not really a bug but it's inconsistent with the two above procs] this proc is consistently referenced with explicit calls to master.dbo.DatabaseBackup and matching sanity checks. This isn't a bug, but it forces you to install OHDMS scripts in a specific location.
4. Cannot sequester OHDMS and SSFRK to a maintenance database.

**Describe the solution you'd like**
SSFRK will create AllNightLog support procs and search for OHDMS procs in the same database context that all SSFRK procs are in, and fall back to master if they are not found there. This will allow scripts to be in the same database as SSFRK, but also still support scripts installed in master.

**Describe alternatives you've considered**
Make database and schema for SSFRK and OHDMS configurable so they can be organized in any way that make sense for the environment. For example install both to DBAMaintenance database, install SSFRK to FR schema and OHDMS to OH schema. This is a more complicated solution. I'll open a separate Feature Request for this after the simpler solution is complete.

**Are you ready to build the code for the feature?**
Yes. I've already forked the repo and started working on the changes.
A similar feature request (#2685) was opened last year, but closed as no one worked on it.

**Comment by wycislo** [comment]
Thank you for taking this on. AWS does not let you update master so OHMDS will not install to master. I created a database called DBATools and installed to this database. I also installed first responder in this database. Configured first responder to put monitored results into this database as well.

**Comment by nick-fotopoulos** [comment]
Okay, lets try that one more time. #3034

**Comment by BrentOzar** [comment]
Thanks for the pull request. Looks good - I haven't tested it myself because I don't use sp_AllNightLog these days, but conceptually the changes make sense. Merging into the dev branch, will be in the next release with credit to you in the release notes.
