### ISSUE TITLE
sp_Blitz Check #2 offline databases

### ISSUE THREAD

**Issue by dnc-msimons** [BrentOzarULTD/SQL-Server-First-Responder-Kit#301]
Check #1 has "AND d.state NOT IN(1, 6, 10)  /* Not currently offline or restoring, like log shipping databases */"

Check #2 only has "AND d.state <> 1 /* Not currently restoring, like log shipping databases */"

It's easy enough to ignore this result, but it seems that, for consistency sake at the very least, since both checks are looking for whether or not backups have run in the past week, they should probably both ignore offline databases.

**Comment by BlitzErik** [comment]
#394
