### ISSUE TITLE
sp_BlitzCache - Placeholder Issue For 2022 Plan XML Stuff

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3030]
**Is your feature request related to a problem? Please describe.**
Starting with [SQL Server 2022](https://techcommunity.microsoft.com/t5/microsoft-mechanics-blog/what-s-new-in-sql-server-2022/ba-p/2922227), there are going to be multiple plans for parameter sensitive queries. sp_BlitzCache should detect and differentiate between them.

**Describe the solution you'd like**
Wait for the [new showplan schema to be published](http://schemas.microsoft.com/sqlserver/2004/07/showplan/), and add in the necessary checks for things. It wouldn't surprise me if 2022 plans need a whole different set of parsing.

**Describe alternatives you've considered**
Pursuing dreams that do not involve XQuery.

**Are you ready to build the code for the feature?**
You know me.

**Comment by BrentOzar** [comment]
I don't have any inside knowledge here, but I got nervous with the demos that I saw so far because they implied that the plans will be pulled from Query Store. I have a nervous feeling that the plan cache will still only show one plan, and that the only way to see the history of the different plans will be to pull it from Query Store.

I really hope my hunch is wrong.

**Comment by erikdarlingdata** [comment]
That would be really unfortunate.

**Comment by erikdarlingdata** [comment]
It looks like there's going to be a QueryVariantId element in plan XML. Whether or not it's _always_ set at the outset, and then incremented for additional plans, I'm not sure. We might be able to either just grab that element, or we might need to identify a query with multiple variants and then count the different variants? I didn't catch anything else in Pedro's talk WRT additional identifiers, but I was a bit distracted.

**Comment by BrentOzar** [comment]
I followed up via Twitter and asked him if multiple variants would share the same sql_handle. I’m assuming they would, but just wanted to double check. It just made me a little nervous when I saw them hard coding options into the query text in the plan.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by BrentOzar** [comment]
Turns out that the same query will have different sql_handles now:

https://twitter.com/SQLPedro/status/1458843460954251265

> @BrentO All different among variants. plan_handle bc they are different plans. sql_handle bc query text is decorated with variant identifiers outside the query text offsets; also different IDs in Query Store.

**Comment by erikdarlingdata** [comment]
girls_laughing.jpg

/*
I typed this on a phone.
Thanks for understanding.
*/
________________________________

**Comment by BrentOzar** [comment]
Going to close this for now, and we can revisit it whenever the public CTPs start.
