### ISSUE TITLE
Remove Recovery Interval Not Optimal on HADR instances

### ISSUE THREAD

**Issue by Kurama2121** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3031]
**Is your feature request related to a problem? Please describe.**
Running sp blitz on an instance of sql 2019 with HADR enabled shows the recovery interval not optimal, but the provided script to fix it doesnt seem to work on HADR instances. 

**Describe the solution you'd like**
Remove the fix if HADR isnt support\doesnt need this fix. 

**Are you ready to build the code for the feature?**
It should already exist, AND NOT EXISTS 
    (
      SELECT 1 FROM sys.dm_hadr_availability_replica_states AS s
        INNER JOIN sys.availability_databases_cluster AS c
             ON s.group_id  = c.group_id 
          WHERE c.database_name = d.name
            AND (s.role_desc <> 'PRIMARY' OR s.is_local = 0)

**Comment by BrentOzar** [comment]
Did you try changing this on the primary? (I'm guessing you might be running it on a read-only replica, but you have to make the change on the primary.)

**Comment by Kurama2121** [comment]
Yea I did, 

From the primary - 

<img width="638" alt="image" src="https://user-images.githubusercontent.com/39833426/140794429-4207f883-653e-4af0-a87c-7e45c2b5ab23.png">

<img width="651" alt="image" src="https://user-images.githubusercontent.com/39833426/140794562-e62fafe8-1b44-48a8-a7a7-bab5d90c103d.png">

**Comment by erikdarlingdata** [comment]
@Kurama2121 I think it should stay in specifically because it doesn't carry over, and it would be useful for folks to know when it's not set correctly there so they can fix it. I'm open to being wrong, but unless you have a really good reason this will likely get closed out. Let me know what you think, though.

**Comment by erikdarlingdata** [comment]
@Kurama2121 sorry, deleted previous comment. I had a couple people test out setting this on an AG primary, and it carried over immediately to the secondary. I think you've got something else going on, here. You're right that it's not settable on the secondary, but if it's set correctly on the primary it should be on the secondary as well.

**Comment by AaronBertrand** [comment]
@Kurama2121 if you want to _fix_ the issue on the primary, you need to uncomment the EXEC.

**Comment by Kurama2121** [comment]
@AaronBertrand I did do that previously just not in the screenshot for Brent. Shouldnt the database count show something other than 0 considering I do have databases with the interval at 0 after all. I know its not a script you guys wrote so ill have to do some more digging.

**Comment by AaronBertrand** [comment]
@Kurama2121 Well, what is the role in replica_states for one of the databases that you think should be returned but is not? FWIW I verified that this code works as expected on a primary and secondary where databases have the wrong setting. When run on a secondary, it shouldn't produce any alter database commands, because you can't alter the database there. Perhaps the code should include different output, like "there are problems but you need to fix them on primary" but that's a different issue.

<img width="1989" alt="Screen Shot 2021-11-11 at 11 30 23 AM" src="https://user-images.githubusercontent.com/5168570/141334045-aa2e4752-c381-43af-a8e2-facfc2089988.png">

**Comment by Kurama2121** [comment]
I guess im not understanding. Running the base code, it shows 0 for a database count, but when I select * there are multiple databases that have a target recovery time at 0 seconds rather than 60 so shouldnt that add to the database count and produce an alter command? The role is listed as primary.

<img width="796" alt="image" src="https://user-images.githubusercontent.com/39833426/141380233-393e053f-26c3-4f8c-b354-5256e0845321.png">

**Comment by AaronBertrand** [comment]
I'm having a play with the logic and think it might make sense to break out the "is this in an AG and is it primary" check separate from "is this not in an AG at all" ... can you tell me how this script works for you on your primary and secondary:

```
DECLARE @sql nvarchar(max) = N'';

;WITH d AS 
(
  SELECT name FROM sys.databases AS d 
    WHERE target_recovery_time_in_seconds = 0
      AND database_id > 4 
      AND [state] = 0
      AND is_read_only = 0
)
SELECT @sql += N'
  ALTER DATABASE ' + QUOTENAME(name) 
  + N' SET TARGET_RECOVERY_TIME = 60 SECONDS;' 
  FROM 
  (
    SELECT name FROM d
      WHERE EXISTS -- it's in an AG that is primary on this node
      (
        SELECT 1 FROM sys.dm_hadr_availability_replica_states AS s
          INNER JOIN sys.availability_databases_cluster AS c
             ON s.group_id  = c.group_id 
          WHERE c.database_name = d.name
          AND (s.role_desc = N'PRIMARY' AND s.is_local = 1) 
      )
    UNION ALL
    SELECT name FROM d
      WHERE NOT EXISTS -- it's not in an AG at all
      (
        SELECT 1 FROM sys.availability_databases_cluster AS c
          WHERE c.database_name = d.name
      )
  ) AS x
 ORDER BY name;

SELECT DatabaseCount = @@ROWCOUNT, Version = @@VERSION, cmd = @sql;
```

**Comment by AaronBertrand** [comment]
And after working through it a bit more, I really didn't like the multiple references to the cluster catalog view, and I actually like this a lot better:

```
DECLARE @sql nvarchar(max) = N'';

SELECT @sql += CHAR(13) + CHAR(10) + CASE
  WHEN ag.role = N'PRIMARY' OR ag.role IS NULL THEN
  N'ALTER DATABASE ' + QUOTENAME(d.name) 
  + N' SET TARGET_RECOVERY_TIME = 60 SECONDS;' ELSE 
  N'PRINT N''-- fix ' + QUOTENAME(d.name) + N' on Primary.'';' END
FROM sys.databases AS d 
OUTER APPLY
(
  SELECT role = s.role_desc
    FROM sys.dm_hadr_availability_replica_states AS s
    INNER JOIN sys.availability_databases_cluster AS c
       ON s.group_id  = c.group_id AND s.is_local = 1
       AND d.name = c.database_name
) AS ag
WHERE d.target_recovery_time_in_seconds <> 60
  AND d.database_id > 4 
  AND d.[state] = 0 
  AND d.is_in_standby = 0 
  AND d.is_read_only = 0;

SELECT DatabaseCount = @@ROWCOUNT, cmd = @sql;

-- EXEC sys.sp_executesql @sql;
```

**Comment by Kurama2121** [comment]
Primary - 
<img width="274" alt="image" src="https://user-images.githubusercontent.com/39833426/141816165-27e720af-f3ef-48bc-8e88-a49f7f7968be.png">

Secondary - 
<img width="265" alt="image" src="https://user-images.githubusercontent.com/39833426/141827400-c007cb73-af96-4ec4-acd3-d3870894c39e.png">

Looking much better, thank you @AaronBertrand ! Sorry Brent for tagging under FRK

**Comment by erikdarlingdata** [comment]
@Kurama2121 This seems to be all set, so I'm going to close it out over here.

**Comment by TaylorM-DBA** [comment]
@AaronBertrand Hey Aaron, thanks for crediting me in your article. I couldnt find any other way to contact you so sorry for spamming the question here, but any way you could use my Name (in profile) or new account name? I created this account forever ago before I thought I'd ever be doing anything like this ;)

Thanks again.
