### ISSUE TITLE
Very minor documentation issue

### ISSUE THREAD

**Issue by Tarjei-stavanger** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3036]
**Version of the script**

This is in the README.md file.

It is in the "sp_DatabaseRestore: Easier Multi-File Restores" section.

'\FILESERVER\BACKUPS\SQL2016PROD1A\LogShipMe\FULL' is not a correct UNC path. It should be '\\\\FILESERVER\BACKUPS\SQL2016PROD1A\LogShipMe\FULL'

**What is the current behavior?**

Current documentation.

**If the current behavior is a bug, please provide the steps to reproduce.**

Current documentation.

**What is the expected behavior?**

Current documentation.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Current documentation.

**Comment by nick-fotopoulos** [comment]
Both paths look the same. Should the second one have an extra \ in front of it?

**Comment by Tarjei-stavanger** [comment]
The double backslash disappeard. Returned now.
