### ISSUE TITLE
Workgroup edition link no-longer points to useful information

### ISSUE THREAD

**Issue by TeeDavey** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3037]
similar to issue #799, but the link to BOL that Brent put in 4 years ago now points to the _Editions and supported features_ page for 2016 (with links back to 2014), for which there was no Workgroup Edition, so it doesn't lead to any useful information.

The (retired) 2008R2 page - which does contain information on Workgroup Edition - can be found at https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/cc645993(v=sql.105)

Would it be better if https://BrentOzar.com/go/workgroup pointed at this address now?

**Comment by BrentOzar** [comment]
Thanks for the heads up! Fixed.
