### ISSUE TITLE
Build out related Grafana Dashboard to pull info from centralized, scheduled run of  'spBlitzOutput' table and or more

### ISSUE THREAD

**Issue by tBalwithatouchofMalace** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3040]
**Is your feature request related to a problem? Please describe.**

Limited visibility into the wonderful details of what this toolset can provide.  It would be nice to schedule many of these tools to run to centrally store their results, and let a monitoring and alert system do what it does well (in this case, my suggestion is Grafana)

A pre created and published (grafana.com) dashboard with appropriate statistics and info from the 'spBlitzOutput' table, or any other centralized table which would be useful.

**Describe the solution you'd like**

1 or more Grafana Dashboards showing daily totals of result issues, tracking of issues that were resolved, and so on with Alert levels for certain issue types to be able to run so that Grafana will alert you when, for example, several Issues with Severity 1 pop up within a time period.

**Describe alternatives you've considered**

I have not really considered others as Grafana is widely used, and free, and seems to be quite excellent.

**Are you ready to build the code for the feature?**
As much as we'd love to build everything that everyone wants for free, we need your help. Open source is built with your help and code. Are you ready to commit time to this project? Have you got existing code you can help contribute to solve the problem?

I am not even moderately capable of coding on the SQL side, but if someone starts it with a standardization of results tables, I could certainly contribute with additions to any Dashboards within Grafana.

**Comment by BrentOzar** [comment]
This would be beyond the scope of the work we'd consider doing on the SQL side, unfortunately. For building a monitoring solution, you're best off checking with tools like Opserver.

**Comment by tBalwithatouchofMalace** [comment]
Thanks for reviewing my idea.
