### ISSUE TITLE
sp_BlitzIndex - Script index created for missing FK indexes

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3041]
**Is your feature request related to a problem? Please describe.**
When I wrote the check for unindexed foreign keys, I neglected to add in `CREATE INDEX` statements for them.

**Describe the solution you'd like**
I'd like to add `CREATE INDEX` statements for missing foreign keys.

**Describe alternatives you've considered**
Inheriting billions of dollars.

**Are you ready to build the code for the feature?**
Yes, unless someone is willing to give me billions of dollars.

**Comment by BrentOzar** [comment]
Do you still want to do this? If not, let's close it.

**Comment by erikdarlingdata** [comment]
You can can it for now, I think the warning is enough.

/*
I typed this on a phone.
Thanks for understanding.
*/
________________________________

**Comment by BrentOzar** [comment]
OK, cool!
