### ISSUE TITLE
sp_BlitzIndex - ColumnNamesWithDataTypes CTE is hella slow

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3042]
**Is your feature request related to a problem? Please describe.**
Here's an instance where this query runs for >2 minutes. I've seen it do worse, but this is good enough to work with.

[bibad.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/7565278/bibad.txt)

Just change .txt to .sqlplan to view it. There's a lot going on in that query that a Professional Query Tuner™ would probably tinker with. It might work to stick some of this stuff into `#temp` tables and then select out at the end when we do the insert. It sort of looks like the wacky parts happen when the query plan DMVs get hit, but I haven't pored over it yet. Kinda busy on other stuff at the moment.

**Describe the solution you'd like**
Tune this sucker.

**Describe alternatives you've considered**
Letting the masses suffer.

**Are you ready to build the code for the feature?**
Yes, but it I'm happy to let anyone else get a crack at it, too. Leaving it unassigned for now.

**Comment by BrentOzar** [comment]
Been several months, so I'm going to close this for now, but if you want to work on it, you can reopen it.
