### ISSUE TITLE
sp_BlitzIndex: Visualizing columnstore index contents is slow

### ISSUE THREAD

**Issue by rsocol** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3043]
**Is your feature request related to a problem? Please describe.**
Visualizing columnstore index contents is slow when there are many columns in the table but few are used in the columnstore.

For example, I have a table with 35 columns (and about 18 million rows) and a non-clustered columnstore index using only one column. For this table, sp_BlitzIndex with @ShowColumnstoreOnly=1 takes about 14 seconds.

I have another table with 114 columns (and 217 million rows) and a non-clustered columnstore index using only one column. For this table, sp_BlitzIndex with @ShowColumnstoreOnly=1 takes about 9 minutes.

**Describe the solution you'd like**
In the section "Visualize columnstore index contents" of sp_blitzIndex there is a PIVOT FOR column_name IN ( ' + @ColumnList + N').
It seems to me that filtering on the c.name column before applying the PIVOT would improve performance significantly.

In my case, the modified query takes about 4 seconds for the first table and about 30 seconds for the second table.

**Describe alternatives you've considered**
I have taken a quick'n'dirty approach with REPLACE to change the @ColumnList with square brackets to apostrophes. I don't know if that's acceptable in your oppinion, another alternative would be to build a @ColumnList2 by using QUOTENAME(c.name,'''').

**Are you ready to build the code for the feature?**
Yes

**Comment by BrentOzar** [comment]
Thanks for the pull request, but unfortunately your solution breaks when columns have brackets in the name. Here's a test script to use:

```
DROP TABLE IF EXISTS dbo.TestColumnstore;
GO
CREATE TABLE dbo.TestColumnstore
	([ [ ] INT,
	 [ ] INT,
	 [ [COL]]] INT,
	 [Normal1] INT,
	 [Normal2] INT);
GO
CREATE CLUSTERED COLUMNSTORE INDEX CCI ON dbo.TestColumnstore;
INSERT INTO dbo.TestColumnstore
	SELECT TOP 1000000 1,1,1,1,1
	FROM sys.all_columns ac1
	CROSS JOIN sys.all_columns ac2;
GO
sp_BlitzIndex @TableName = 'TestColumnstore', @ShowColumnstoreOnly = 1;
```

Your pull request fails with:

```
Failure analyzing temp tables.
Msg 50000, Level 15, State 1, Procedure sp_BlitzIndex, Line 5715 [Batch Start Line 15]
Incorrect syntax near ', '.
```

**Comment by BrentOzar** [comment]
Thanks for the pull request. Looks good. Merging into the dev branch, will be in the next release with credit to you in the release notes.
