### ISSUE TITLE
MoveFiles needs to be specifiable.

### ISSUE THREAD

**Issue by dalehhirt** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3046]
**Is your feature request related to a problem? Please describe.**
When restoring files, they are automatically moved to the default data/log directories.  I need the ability to set whether that is true.

**Describe the solution you'd like**
A configuration item that allows to define by all or by database whether or not to move files.

**Describe alternatives you've considered**
currently, the code is buried deep, so I don't want to update it without giving back.

**Are you ready to build the code for the feature?**
I've already built it.

**Comment by dalehhirt** [comment]
[PR 3047](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/3047)

**Comment by BrentOzar** [comment]
Thanks for the pull request. Looks good - I haven't tested it since I don't have a testbed for sp_AllNightLog, but conceptually it makes sense. Merging into the dev branch, will be in the next release with credit to you in the release notes.
