### ISSUE TITLE
sp_blitzlock reporting UNKNOWN for login, application and host

### ISSUE THREAD

**Issue by AceOfHobbes** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3048]
When running sp_blitzlock I am seeing the following entry
This database has had 588 instances of deadlocks involving the login UNKNOWN from the application UNKNOWN on host UNKNOWN
This is from the Sept 14 build running against SQL 2014

**Comment by BrentOzar** [comment]
Yes, that's normal and by design - if we don't get that data out of the default Extended Events health session, we can't show it to you.
