### ISSUE TITLE
Error 8631 is reported when the sp_Blitz stored procedure is executed

### ISSUE THREAD

**Issue by zangqianglei** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3057]
**Version of the script**
- Script Version: SELECT @Version = '8.08', @VersionDate = '20220108';
- DB Version: Microsoft SQL Server Enterprise: Core-based Licensing  11.0.3000.0
- OS: Microsoft Windows NT 6.2 (9200)
![image](https://user-images.githubusercontent.com/19665208/148905159-ac19ebd3-5479-40d3-95d5-bcc028873399.png)

**ERROR MESSAGE**
Error 8631 is reported when the sp_Blitz stored procedure is executed
![image](https://user-images.githubusercontent.com/19665208/148905007-69b5f1b8-4d5b-42e4-8ea6-7f22853cb1e7.png)

**Comment by erikdarlingdata** [comment]
Thanks for reporting this! Can you paste the exact command that you're running when this error happens?

Also, want to confirm that the error message you get is regarding reaching the internal stack limit?
![image](https://user-images.githubusercontent.com/2136037/150412852-99a15920-6f2b-488b-b619-46e095878b9e.png)

To help us troubleshoot things, can you use the `@Debug = 1` argument and tell us which CheckId in the Messages tab is printed before the error is thrown?

Thanks!

**Comment by BrentOzar** [comment]
We haven't heard back, so closing the issue.
