### ISSUE TITLE
spBlitz 20220108 fails on SQL2008 R2

### ISSUE THREAD

**Issue by mike-halford** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3058]
**Version of the script**
**8.08 20220108**

**What is the current behavior?**
**fails to run.**

**If the current behavior is a bug, please provide the steps to reproduce.**
fails to install

**What is the expected behavior?**
installs correctly

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2008 R2

I understand that SQL 2008 R2 is unsupported but this is the first version to fail. Not sure whether a change can be made to fix or not.

![Screenshot 2022-01-11 155745](https://user-images.githubusercontent.com/32711714/148976898-53af2f94-cd3e-4972-bf74-c27076281d22.png)

**Comment by BrentOzar** [comment]
Check the Deprecated folder for versions of the scripts that work with deprecated versions of SQL Server. We no longer maintain support for 2008/2008R2.
