### ISSUE TITLE
sp_Blitz causes SQL server to crash when table sys.plan_guides holds a hint with double quoted index name

### ISSUE THREAD

**Issue by CodingForFunToo** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3059]
Version 8.07, dated 20211106

Running with parameters   @CheckUserDatabaseObjects, @CheckServerInfo  and  @BringThePain set to 1, sp_blitz outputs the folllowing errors and writes a Dump report in the log file (Access violation):
`.Net SqlClient Data Provider: Msg 102, Level 15, State 1, Line 1
Incorrect syntax near 'IX_SaleTransactions_VendingSiteNo'.
.Net SqlClient Data Provider: Msg 596, Level 21, State 1, Line 0
Cannot continue the execution because the session is in the kill state.
.Net SqlClient Data Provider: Msg 0, Level 20, State 0, Line 0
A severe error occurred on the current command.  The results, if any, should be discarded.
`
This is caused by a table hint in the system table `sys.plan_guides` where column `hint` looks like this (beware of the double quotes around the index name):
`option (table hint (saletransa0_, index("IX_SaleTransactions_VendingSiteNo")))`

This error is prevented when the batch, starting at about line 6464, invoked by `sp_MSforeachdb,` holds the clause `set quoted_identifier on;`, like this:
`								EXEC dbo.sp_MSforeachdb 'USE [?];
			SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
			SET QUOTED_IDENTIFIER ON;
            INSERT INTO #BlitzResults
			(CheckID,
			DatabaseName,
			Priority,
			FindingsGroup,
			Finding,
			URL,
			Details)
		  SELECT DISTINCT 164,
		  N''?'',
		  100,
		  ''Reliability'',
		  ''Plan Guides Failing'',
		  ''https://www.brentozar.com/go/misguided'',
		  (''The ['' + DB_NAME() + ''] database has plan guides that are no longer valid, so the queries involved may be failing silently.'')
		  FROM [?].sys.plan_guides g CROSS APPLY fn_validate_plan_guide(g.plan_guide_id) OPTION (RECOMPILE)';
`

Running on SQL Server version SQL Server 2012 (SP4-GDR)

**Comment by BrentOzar** [comment]
Thanks for the pull request! Merged, will be in the next release with credit to you in the release notes.
