### ISSUE TITLE
sp_DatabaseRestore: @StopAt not respected for non-split diff backups

### ISSUE THREAD

**Issue by rob-hague** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3061]
**Version of the script**
8.08 / 20220108

**What is the current behavior?**
When specifying @RestoreDiff = 1 and @StopAt, @LastDiffBackup is found correctly but then overridden shortly after. This is ok for split backups (fixed by #2899) but for non-split this causes the latest diff backup to be restored even if it is after the value of @StopAt

**If the current behavior is a bug, please provide the steps to reproduce.**
As above

**What is the expected behavior?**
The latest diff backup on or before @StopAt should be restored, or the latest if @StopAt not specified

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2019 (probably all). Has not worked at least since #2180

**Comment by BrentOzar** [comment]
Thanks for the pull request! Merging into the dev branch, will be in the next release with credit to you in the release notes. I don't have a testbed for sp_DatabaseRestore, but conceptually the changes make sense.
