### ISSUE TITLE
sp_Blitz - Arithmetic overflow error converting expression to data type int - Check 158

### ISSUE THREAD

**Issue by DavidAPoole** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3063]
**Version of the script**
'8.08', '20220108'

**What is the current behavior?**
Arithmetic overflow error converting expression to data type int error generated on check 158 for database size > 2TB.

**If the current behavior is a bug, please provide the steps to reproduce.**
Reproduce error with a database size of 272539264 from sys.database_files, e.g:
```
DECLARE @size INT = 272539264;
SELECT CAST((@size * 8 / 1000000) AS NVARCHAR(10));
GO
```

You can fix the overflow error with cast as bigint, e.g:
```
DECLARE @size INT = 272539264;
SELECT CAST((CAST(@size AS BIGINT) * 8 / 1000000) AS NVARCHAR(10));
GO
```

In summary, to resolve the issue change line 6463 of the current sp_Blitz version from this:

`''The ['' + DB_NAME() + ''] database file '' + f.physical_name + '' is using 1MB filegrowth settings, but it has grown to '' + CAST((f.size * 8 / 1000000) AS NVARCHAR(10)) + '' GB. Time to up the growth amount.''`

to this:

`''The ['' + DB_NAME() + ''] database file '' + f.physical_name + '' is using 1MB filegrowth settings, but it has grown to '' + CAST((CAST(f.size AS BIGINT) * 8 / 1000000) AS NVARCHAR(10)) + '' GB. Time to up the growth amount.''`

**What is the expected behavior?**
sp_Blitz should complete check 158 no matter what size the database or its growth.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Microsoft SQL Server 2017 (RTM-CU25) (KB5003830) - 14.0.3401.7 (X64)   Jun 25 2021 14:02:48   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)

**Comment by BrentOzar** [comment]
Thanks for the pull request! Merging into the dev branch, will be in the next release with credit to you in the release notes. I don't have a testbed for a database of that size, heh, but conceptually the changes make sense.
