### ISSUE TITLE
[Dupe of #1985] sp_BlitzCache: use the OS's default decimal separators (commas vs periods) in output

### ISSUE THREAD

**Issue by Tarjei-stavanger** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3069]
**Version of the script**

sp_BlitzCache from November 06, 2021

**What is the current behavior?**

When the database is set up to have comma as the decimal point, exporting using data from "**exec sp_blitzcache @expertmode=1, @DatabaseName=DBName, @ExportToExcel = 1;**" gives interesting results for some fields. See the "**Total CPU (ms)**" column in the attached screenshots.

It does not help to change the decimal point in Excel/Operating System because most of the data in the report uses the database decimal point.

**If the current behavior is a bug, please provide the steps to reproduce.**

Run script and export to Excel when Excel has comma as the decimal point.

**What is the expected behavior?**

The expected behaviour is that the decimal point of the database is used.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Windows Server 2016 Standard (10.0)  14.0.3370.1

![image](https://user-images.githubusercontent.com/82510602/152500115-1336f093-5126-48be-ab51-dabb90471d91.png)
![image](https://user-images.githubusercontent.com/82510602/152500298-6b9950ad-156c-4ba7-b82e-c19356a79628.png)

**Comment by BrentOzar** [comment]
Yes, we had an open feature request for that for over a year:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/1985

Would you like to make the coding changes necessary? It isn't something I'm pursuing at this time, but if you've got the time to dig into it, we'd welcome the code contribution.

**Comment by BrentOzar** [comment]
I haven't heard back from you in a couple of months, so closing the issue. If you change your mind and you want to work on it, we can reopen the issue for you. Thanks!
