### ISSUE TITLE
sp_BlitzIndex doesn't find indexes on msdb.dbo.backupset table

### ISSUE THREAD

**Issue by gdoddsy** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3072]
I haven't looked into why yet, but when I run sp_BlitzIndex I don't get any details about the indexes on the table. Is this by design because it's in MSDB? If not, I'll find a way to stop filtering it out.

**Comment by BrentOzar** [comment]
Yeah, we ignore system objects.
