### ISSUE TITLE
Collation error on uninstall

### ISSUE THREAD

**Issue by Fiander** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3077]
**Version of the script**
8.07

**What is the current behavior?**
When uninstalling, i get an collation error

**If the current behavior is a bug, please provide the steps to reproduce.**
install in a database,
uninstall from that database

**What is the expected behavior?**
no collation error

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
all

**Comment by BrentOzar** [comment]
Thanks for the pull request. Looks good, merging into the dev branch, will be in the next release with credit to you in the release notes.
