### ISSUE TITLE
sp_BlitzFirst - check for KB 3162589's high PAGELATCH times

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#308]
If the server is on 2014 SP1 (12.0.4100 through 12.0.4458), and it has high PAGELATCH_\* waits, warn the user to install SP1 CU7 (12.0.4459): https://support.microsoft.com/en-us/kb/3162589

I don't know what "high" is based on the KB, but I'd say if they're getting half of clock time (2.5 seconds in a 5 second sample, or half of uptime) then trigger the alert.

**Comment by BlitzErik** [comment]
This is a year old now, closing it down.
