### ISSUE TITLE
sp_BlitzIndex - flushed the plancache

### ISSUE THREAD

**Issue by paulneering** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3085]
We recently updated the responder kit to version 8.08 and found something strange. By installing this version our server maxed out it’s memory. We found that this version of sp_BlitzIndex probably used so much memory that it caused our plancache to almost flush entirely. 

We mailed Brent about this and he told us there is a never version 8.09. We tested that version and it has the same problems.
We reinstalled 8.01 and everything is fine!

**Case**
While running sp_BlitzIndex (version 8.09) the plancache is being dumped. 
Before:   48.382 plans in cache taking 6.8GB of memory 
After:        1872 plans in cache taking 185mb of memory

**Specifications**
Windows Server 2019 Datacenter (10.0) (VMWare)
12-cores 128GB mem 
1TB over 5 disks (SAN storage) (Io latency and speed are good!)
Microsoft SQL Server Web (64-bit) (15.0.4102.2) (2019 CU9)
Temp-db spread over 8 files
Max server Memory : 107 GB (~85%)
Optimize for ad-hoc Workloads  = True
Cost Threshold For Parallelism = 50
MAXDOP = 8
Running a single database ~80GB
Application footprint:  Hour registration/planning application (500 concurrent users)
Database Load: ~200 Batches per second on a normal day,  ~400 on busy day
Plancache: Cycles 35.000-40.000 within 2 weeks. Having the biggest number of plans in last 3 hours.
FirstResponderKit (8.09) install on master

**Memory**

Before (running sp_blitzIndex)
![image](https://user-images.githubusercontent.com/79528486/162915838-cd0d74b8-8918-4936-ba65-efbc60367c6c.png)

After (running sp_blitzIndex) (1 minute 20 seconds (takes 30 seconds in version 8.01)):
![image](https://user-images.githubusercontent.com/79528486/162915941-08ff1087-0804-48ea-9da5-e4c77d8ad4ca.png)

**Plancache**

Before
![image](https://user-images.githubusercontent.com/79528486/162916157-dbb1515f-b345-4cea-a70e-ecd90346817b.png)

After
![image](https://user-images.githubusercontent.com/79528486/162916226-5e3b9411-b8eb-4d43-a244-0f0bdda8ec88.png)

**Note**: We are aware of plan replication. Still have to do a lot of work narrowing down the numbers by parameterizing the queries. The first 3 in this top 50 are delete and insert queries.

query_hash	 	        PlansCached
0x1F619BC7917132D8	1238
0x0AFCEB77C30A6661	853
0x072E00A7C5F95616	744
0x9131886D5634F604	319
0xEC93C79FEA2A2A4D	308
0x072E00A7C5F95616	265
0x072E00A7C5F95616	206
0xC72801AC55CB21C6	203
0x786E04C0B1E371CA	192
0x60D52AA31B60F58D	178
0x41F067D1210BA537	161
0xDDA9C9AF629687D6	149
0x072E00A7C5F95616	144
0x072E00A7C5F95616	141
0x3B667C417B288A44	136
0xB1F56DAD777D360B	127
0x91849F181D4B120C	126
0x786E04C0B1E371CA	117
0x95D6390EB99AB6A6	110
0x072E00A7C5F95616	98

**Comment by BrentOzar** [comment]
I haven't been able to reproduce this. After sp_BlitzIndex runs, can you try:

sp_BlitzCache @SortOrder = 'memory grant'

It's possible that one of the sp_BlitzIndex queries has an artificially high memory grant on your system. If an sp_BlitzIndex query is in that top 10 list, can you upload the plan to pastetheplan.com, or send it to me at help@brentozar.com?

Also, can you include the output of sp_Blitz @CheckServerInfo = 1 in a spreadsheet? I'm wondering if there isn't something else going on on the system that's affecting memory grants, or if the server's under memory pressure overall.

**Comment by paulneering** [comment]
I will need clearance from our technical director for that and pick a good moment because we will be killing our plancache and possible force our production server into memory pressure.  He's having his holyday so I will get back to you on that!

I have been in sniffing in the BlitzIndex code. And a big difference that I found is in 8.01 there is no sample_query_plan (which is pretty nice feature btw) and in the 8.08-9 version this is a working feature.

This could be the place where is all goes wrong for us. I also really doesn't help having 40.000+ plans we are aware of that.

I will (if I have the clearance) comment this feature out to check if the plan cache persists. That way we know for sure if this is the reason. If not I will send you the information you requested!

**Comment by paulneering** [comment]
I got the clearance and tested it last Friday evening. I comment out the sample_query_plan feature in the 8.09 version. And there was no problem what so ever!!! 

We also tested the original but after 15 minutes the memory became dangerously low so we killed the process. The plancache memory was 24GB+ when we killed it! It usually is around 7GB. We checked the cache for huge memory grants, and we only saw queries linked to our application. 

`	
	/* Github #2780 BGO Removing SQL Server 2019's new missing index sample plan because it doesn't work yet:*/
        IF NOT EXISTS
		(
		    SELECT
			    1/0
			FROM sys.all_objects AS o
			WHERE o.name = 'dm_db_missing_index_group_stats_query'
	    )
        SELECT
		    @dsql += N' , NULL AS sample_query_plan '
		/* Github #2780 BGO Removing SQL Server 2019's new missing index sample plan because it doesn't work yet:*/
        ELSE
		BEGIN
			/*
				Test if this causes memory problems
			
			SELECT
			    @dsql += N'
			, sample_query_plan =
			  (
			      SELECT TOP (1)
				      p.query_plan
				  FROM sys.dm_db_missing_index_group_stats gs 
				  CROSS APPLY
				  (
				      SELECT TOP (1)
					      s.plan_handle
				  	  FROM sys.dm_db_missing_index_group_stats_query q 
				  	  INNER JOIN sys.dm_exec_query_stats s
					      ON q.query_plan_hash = s.query_plan_hash
				  	  WHERE gs.group_handle = q.group_handle 
				  	  ORDER BY (q.user_seeks + q.user_scans) DESC, s.total_logical_reads DESC
			      ) q2
				  CROSS APPLY sys.dm_exec_query_plan(q2.plan_handle) p
                  WHERE ig.index_group_handle = gs.group_handle
			  ) '
 		  */
		  
		  		    @dsql += N' , NULL AS sample_query_plan '

		  
		END`

So the problem is definitely in this piece of code. We checked the record count in the table dm_db_missing_index_group_stats_query and it was 353428. That is a pretty high number!

I have all the information you requested in a excel-sheet so let me know if you still need it!

**Comment by BrentOzar** [comment]
Ah, so it's a bug in SQL Server then. Read the Books Online for that DMV:
https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-db-missing-index-group-stats-query-transact-sql?view=sql-server-ver15

The notes state:

> The result set for this DMV is limited to 600 rows. Each row contains one missing index. If you have more than 600 missing indexes, you should address the existing missing indexes so you can then view the newer ones.

Can you open a support case with Microsoft on that? I totally understand if you can't, but anytime we find a bug in SQL Server, I'm always eager to try to get that fixed.

For sp_BlitzIndex, I'll work around that by doing a SELECT COUNT(*) from that DMV, and if it's got more than, say, 2,000 rows, then I'll skip running the missing index query.

**Comment by BrentOzar** [comment]
Demo query to repro:

```
/* Create a numbers table temporarily: https://stackoverflow.com/a/1407488/26837 */
DROP TABLE IF EXISTS #Numbers;

SELECT TOP 1000 IDENTITY(int,1,1) AS Number
    INTO #Numbers
    FROM sys.objects s1       --use sys.columns if you don't get enough rows returned to generate all the numbers you need
    CROSS JOIN sys.objects s2 --use sys.columns if you don't get enough rows returned to generate all the numbers you need
ALTER TABLE #Numbers ADD CONSTRAINT PK_NumbersTest PRIMARY KEY CLUSTERED (Number)

DROP TABLE IF EXISTS dbo.WideTable;
DECLARE @StringToExec NVARCHAR(MAX) = N'CREATE TABLE dbo.WideTable (
	Id INT IDENTITY(1,1) PRIMARY KEY CLUSTERED ';

SELECT @StringToExec = @StringToExec + N' , Col' + CAST(Number AS NVARCHAR(10)) + N' INT '
	FROM #Numbers;

SET @StringToExec = @StringToExec + N' );'

EXEC(@StringToExec);
GO
CREATE INDEX Id ON dbo.WideTable(Id);

/* Put ~800MB of rows into the table: */
INSERT INTO dbo.WideTable(Col1)
	SELECT TOP 100000 1
	FROM #Numbers n1
	CROSS JOIN #Numbers n2;
GO

/* Query each column to add a missing index hint to the DMVs: */
DECLARE @StringToExec NVARCHAR(MAX), @CurrentId INT = 2;
WHILE @CurrentId < 1000
	BEGIN
	SET @StringToExec = N'SELECT Col' + CAST(@CurrentId AS NVARCHAR(10))
		+ N' FROM dbo.WideTable WHERE Col' + CAST(@CurrentId AS NVARCHAR(10)) + N' = 2;'
	EXEC(@StringToExec);

	SET @StringToExec = N'SELECT Col' + CAST(@CurrentId AS NVARCHAR(10))
		+ N' FROM dbo.WideTable WHERE Col' + CAST(@CurrentId AS NVARCHAR(10)) + N' = 2 '
		+ N' AND Col' + CAST((@CurrentId-1) AS NVARCHAR(10)) + N' = 2 '
	EXEC(@StringToExec);

	SET @CurrentId = @CurrentId + 1;
	END

```

**Comment by BrentOzar** [comment]
It's been limited to 600 rows for over a decade because the parent DMVs are limited to 600 rows as well, like this: https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-db-missing-index-groups-transact-sql?view=sql-server-ver15

**Comment by BrentOzar** [comment]
Made some code changes this morning. There are a couple of different fixes in here:

* In modes 0 (the default output) and 4, the sample_query_plan is now added at the end of the result set
* We only query sys.dm_db_missing_index_group_stats_query if there are < 1000 plans in it
* We fully prefix sys.dm_db_missing_index_group_stats_query with the database name (I don't think that's going to have any effect here, but was worth a shot)

If you want to use the version in dev and see if it works for you, bypassing the sample query plans, go for it. If you still see issues with this version, let me know with a note in here. Thanks!
