### ISSUE TITLE
Collation issue on installing

### ISSUE THREAD

**Issue by Nemesis36** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3086]
_**Version of the script**_
version 8.09

_**What is the current behavior?**_
On running Install-All-Scripts I get the following message :
XX-XXXX(XXXXXX\xxxx): Msg 468, Level 16, State 9, Procedure sp_AllNightLog, Line 564 [Batch Start Line 13]
Cannot resolve the collation conflict between "Latin1_General_CI_AS" and "SQL_Latin1_General_CP1_CI_AS" in the equal to operation.

**Comment by BrentOzar** [comment]
Howdy! It sounds like you might be trying to install the scripts in a database that have a different collation than the system databases. I wouldn't do that - either install the scripts in master, or in a database that has the same collation as master and tempdb.

It may also be that you've got a really wildly unsupported configuration and your master and tempdb databases are different collations. That would be a yuuuuge problem for more than just the First Responder Kit.

**Comment by Nemesis36** [comment]
Thanks for the feedback.  I used central management server to deploy the script and indeed I had a few servers with a different default database.  This is now fixed and all installs work great.
