### ISSUE TITLE
New Report Issue : username is equal to password

### ISSUE THREAD

**Issue by Nemesis36** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3087]
**Is your feature request related to a problem? Please describe.**
It can be marked as an issue when the username is equal to the password.
I think this would be an interesting item to add to SP_Blitz.

**Describe the solution you'd like**
  SELECT   'Name = Password', NAME from sys.sql_logins  WHERE Pwdcompare( name, password_hash) = 1;

**Comment by BrentOzar** [comment]
Howdy! We're not adding any security features to sp_Blitz. If you're interested in security auditing, your best bet would be to create a new script that focuses on that. Thanks!
