### ISSUE TITLE
Check 181 Alerts on false positives

### ISSUE THREAD

**Issue by josh-simar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3090]
**Version of the script**
8.08

**What is the current behavior?**
Check 181 checks if maintenance plans have Rebuild/Reorg or Rebuild/Update in their plan but does not check if any of these steps are disabled.

**If the current behavior is a bug, please provide the steps to reproduce.**
Create maintenance plan with a Rebuild/Reorg Disable those steps. It still reports that repetitive tasks are occuring.

**What is the expected behavior?**
If the task is disabled the check should not fire that repetitive tasks are occuring.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
2016 SP1
To be clear, this is working just not reporting correctly and I don't think it ever has.

**Comment by BrentOzar** [comment]
This has actually come up in the past. Just because a step is disabled doesn't mean it's not occurring - you can start a job at any step, and you can automate that process as well. I'm a huge believer that if you don't need a harmful step, you shouldn't disable it - you should remove it.
