### ISSUE TITLE
sp_BlitzCache - Duplicate Parameter Values in 'Cached Execution Parameters' column

### ISSUE THREAD

**Issue by aroques** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3098]
**Version of the script**
SELECT @Version = '8.09', @VersionDate = '20220408';

**What is the current behavior?**
`sp_BlitzCache` will report multiple different values for a single cached execution parameter.
Here's a couple examples that I have noticed: 
```sql
<?ClickMe SET ANSI_NULLS ON 
SET ANSI_PADDING ON 
SET ANSI_WARNINGS ON 
SET ARITHABORT  OFF 
SET CONCAT_NULL_YIELDS_NULL ON 
SET NUMERIC_ROUNDABORT OFF 
SET QUOTED_IDENTIFIER ON 

EXEC [sGold].[stpArchive_Order]  @IDOrders = 9177871, @LogID = 58605, @LogID = 59644, @LogID = 60655?>
```
```sql
<?ClickMe SET ANSI_NULLS ON 
SET ANSI_PADDING ON 
SET ANSI_WARNINGS ON 
SET ARITHABORT  OFF 
SET CONCAT_NULL_YIELDS_NULL ON 
SET NUMERIC_ROUNDABORT OFF 
SET QUOTED_IDENTIFIER ON 

EXEC [Savant].[gOrdersSelect_220310]  @DataField = '1Z830R100327513363', @IDOrders = 11511154, @IDOrders = 11536868, @IDOrders = NULL?>
```

**If the current behavior is a bug, please provide the steps to reproduce.**
The following steps reproduced the issue for me:
1. Run a stored procedure that takes two parameters
2. Run the same stored procedure with a different value inputted for the second parameter
3. Check the value of `sp_BlitzCache`'s Cached Execution Parameters column

**What is the expected behavior?**
A single value for each cached parameter value.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
**Product:** Microsoft SQL Server Enterprise: Core-based Licensing (64-bit)
**OS:** Microsoft Windows NT 6.3 (14393)
**Compatibility Level:** SQL Server 2012 (110)

I believe that I've also seen this on a 2017 server.

I don't know if this worked in a previous version.

**Comment by erikdarlingdata** [comment]
This is expected behavior so you have multiple parameter values to test with. It has been reported before, but I can't find it quickly.

**Comment by aroques** [comment]
@erikdarlingdata that is strange. if a plan can only be compiled with 1 set of values, then where is sp_BlitzCache getting the other values from?

**Comment by erikdarlingdata** [comment]
There are many reasons a query can end up with multiple associated plans. You'll have to dig further into your system to figure out why there are compilation differences that result in that.

**Comment by aroques** [comment]
@erikdarlingdata 

Thanks for the reply, but I have an example query that doesn't have multiple plans yet it has duplicate parameters values so 1 query having multiple plans doesn't explain this.

If you ctrl-f  for 'DMHQ-' in the following plan's XML, then you can see that the same plan has 2 different values of @MachineName cached: 'DMHQ-PRC13' and 'DMHQ-PRC15'. It makes sense why `sp_BlitzCache` is pulling both values in the parameter list, but it doesn't make sense to me why the plan has multiple values of this parameter.

**Query Plan**:  https://www.brentozar.com/pastetheplan/?id=BJsCOVFPc

**Cached Execution Parameters**:
```sql
<?ClickMe SET ANSI_NULLS ON 
SET ANSI_PADDING ON 
SET ANSI_WARNINGS ON 
SET ARITHABORT  OFF 
SET CONCAT_NULL_YIELDS_NULL ON 
SET NUMERIC_ROUNDABORT OFF 
SET QUOTED_IDENTIFIER ON 

EXEC [dbo].[sWindowsServicesSelect_200225]  @MachineName = 'DMHQ-PRC13', @MachineName = 'DMHQ-PRC15', @ServiceTitle = NULL?>
```

**Comment by aroques** [comment]
I found out that this is caused when different queries in a stored procedure use the same parameter, but cache a plan with different values. I think there's two main ways that this can happen:
1. The parameter value changes during stored procedure execution
2. Branching: only certain parts of the stored procedure are executed under certain conditions
