### ISSUE TITLE
Errors when creating sp_Blitz on SQL 2008 R2 FCI 

### ISSUE THREAD

**Issue by Niphyr** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3099]
**Version of the script**

    SELECT @Version = '8.09', @VersionDate = '20220408';

**What is the current behavior?**
Attempting to create the sp_Blitz stored procedure produces the following error:

    Msg 207, Level 16, State 1, Procedure sp_Blitz, Line 3123
    Invalid column name 'is_current_owner'.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Attempt to create the sp_Blitz stored procedure from **sp_Blitz.sql**.

**What is the expected behavior?**

The procedure creation is successful.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

SQL Server failover cluster running version 10.50.6560 (SQL Server 2008 R2). Windows Server 2012 R2 Datacenter.

The previously running version of sp_Blitz on this server was from 2018. The issue looks to be introduced in a change to check 53 in https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/commit/08a3ffcfb6e51cb42d958fc5600ea3a58490224e. 

If I comment out the mention of `is_current_owner` in check 53 then sp_Blitz will create successfully, but upon running it, it throws another error:

    Msg 208, Level 16, State 1, Procedure sp_Blitz, Line 3050
    Invalid object name 'sys.dm_hadr_availability_replica_cluster_states'.

Which is the AAG/FCI check code also from check 53:

    IF (SELECT COUNT(DISTINCT join_state_desc) FROM sys.dm_hadr_availability_replica_cluster_states) = 2 
        BEGIN --if count is 2 both JOINED_STANDALONE and JOINED_FCI is configured
        SET @AOFCI = 1
    END

If I comment out the above 4 lines inside Check 53, it both creates sp_Blitz successfully and can be run successfully. 

For completeness, here are the objects from check 53 which are unavailable on this server:

- `is_current_owner` from `sys.dm_os_cluster_nodes
- `sys.dm_hadr_availability_replica_cluster_states`
- `sys.availability_groups`
- `sys.availability_replicas`
- `sys.dm_hadr_availability_group_states`

**Comment by BrentOzar** [comment]
Unfortunately, SQL Server 2008 and R2 are no longer supported, as shown in the readme: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/README.md 

For support on versions that Microsoft no longer supports, check the Deprecated folder. Cheers!

**Comment by Niphyr** [comment]
Thanks for the quick reply, wasn't sure if this fell under `but we try not to make changes that would break functionality here` so thought it worth mentioning regardless.
