### ISSUE TITLE
sp_BlitzLock - Add spid and wait_resource to table results.

### ISSUE THREAD

**Issue by davidhooey** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3101]
**Is your feature request related to a problem? Please describe.**
It would be helpful to see the spid and wait_resource information from the XML data in the table output. With the application we develop we log the spid for each connection to our application logs. When we troubleshoot deadlocks we look for the specific logs matching the spids involved in the deadlock. This helps us paint the picture of what the application was doing to cause the deadlock. Although the spids and wait_resource are within the deadlock XML data, it would be must faster and easier to view the data within the table output.

**Describe the solution you'd like**
Extract the spid and the wait_resource data points from the deadlock XML and include them in the table ouput.

**Describe alternatives you've considered**
None

**Are you ready to build the code for the feature?**
Yes, I will create a pull request for this issue.

**Comment by davidhooey** [comment]
PR: #3102

**Comment by BrentOzar** [comment]
Thanks for the pull request!

It works if the table doesn't exist yet, but for users who already deployed this and are logging to tables, sp_BlitzLock fails with this error:

```
Results 1 Jun  6 2022  7:12:56:293AM
Msg 207, Level 16, State 1, Procedure sp_BlitzLock, Line 1284 [Batch Start Line 0]
Invalid column name 'spid'.
Msg 207, Level 16, State 1, Procedure sp_BlitzLock, Line 1284 [Batch Start Line 0]
Invalid column name 'wait_resource'.
```

Because the table already exists, but doesn't have those two columns in it. I'm going to merge this pull request as-is, and then do a separate pull request with the changes to fix that. Thanks!

**Comment by davidhooey** [comment]
Very nice! Thanks @BrentOzar
