### ISSUE TITLE
Links in the advanced area are broken.

### ISSUE THREAD

**Issue by norlando** [BrentOzarULTD/SQL-Server-First-Responder-Kit#311]
The links under "**Advanced sp_BlitzIndex Parameters**" and "**Advanced sp_AskBrent Parameters**" seem to be broken.

**Comment by BrentOzar** [comment]
Which page is this on?

**Comment by norlando** [comment]
It's on the readme.md close to the bottom.

**Comment by BrentOzar** [comment]
Great, thanks! Fixed.
