### ISSUE TITLE
Cluster reported - Not configured

### ISSUE THREAD

**Issue by Toakan** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3112]
**Version of the script**
8.09

**What is the current behavior?**
When run against a server that has HADR enabled, but Clustered disabled, it will display that the node is clustered (Technically not as it is not configured).

![image](https://user-images.githubusercontent.com/7566941/172599180-35c56b6b-a570-499e-afde-7d68a3b248b9.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
- Enable Serverproperty "IsHadrEnabled", however do not configure. 
- Disable Serverproperty "IsClustered"
- Run SP_Blitz

**What is the expected behavior?**
The message regarding "This is a node in a cluster." should possibly read "This node is not yet configured into a Cluster", "Cluster is enabled, however not configured" or something similar.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
- SQL Server for Linux 2017

**Comment by Toakan** [comment]
Without changing too much, this appears to resolve the issue.

`DECLARE @AOFCI AS INT, @AOAG AS INT, @AOAGC AS INT, @HAType AS VARCHAR(10), @errmsg AS VARCHAR(200)

                                         SELECT @AOAG = CAST(SERVERPROPERTY('IsHadrEnabled') AS INT)
                                         SELECT @AOFCI = CAST(SERVERPROPERTY('IsClustered') AS INT)

                                         IF (SELECT COUNT(DISTINCT join_state_desc) FROM sys.dm_hadr_availability_replica_cluster_states) = 2 
											BEGIN --if count is 2 both JOINED_STANDALONE and JOINED_FCI is configured
												SET @AOFCI = 1
											END
										
										IF (SELECT COUNT(Distinct Nodename) from sys.dm_os_cluster_nodes) = 0
											BEGIN
												SET @AOAGC = 0
											END

                                         SELECT @HAType =
                                         CASE
                                                       WHEN @AOFCI = 1 AND @AOAG =1 THEN 'FCIAG'
                                                       WHEN @AOFCI = 1 AND @AOAG =0 THEN 'FCI'
													   WHEN @AOFCI = 0 AND @AOAG = 1 AND @AOAGC = 0 THEN 'AGNC'
                                                       WHEN @AOFCI = 0 AND @AOAG = 1 THEN 'AG'
                                                       ELSE 'STANDALONE'
                                         END

										 IF (@HATYPE = 'AGNC')
											BEGIN
												INSERT  INTO #BlitzResults
                                                               ( CheckID ,
                                                                      Priority ,
                                                                      FindingsGroup ,
                                                                      Finding ,
                                                                      URL ,
                                                                      Details
                                                               )

                                                   SELECT 53 AS CheckID ,
                                                   200 AS Priority ,
                                                   'Informational' AS FindingsGroup ,
                                                   'Cluster Node' AS Finding ,
                                                   'https://BrentOzar.com/go/node' AS URL ,
                                                   'This server has IsHadrEnabled enabled, however is not configured into a Cluster.' AS Details
											END`
											
											
![image](https://user-images.githubusercontent.com/7566941/172602448-2e42a321-7c9f-4a7b-ab0e-7460e238f994.png)

**Comment by BrentOzar** [comment]
Howdy, and thanks for the report! I don't actually use Linux myself, and I don't have a testbed handy. If this is important to you, can you create a pull request as described here:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md

I'll go ahead and close it for now since it doesn't have a pull request, but if you do want to add it, feel free to do a pull request and refer to this issue, and I can reopen it. Thanks!
