### ISSUE TITLE
sp_Blitz: Skip system and utility databases when checking for stored procedures with recompile

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3119]
**Is your feature request related to a problem? Please describe.**
Right now, we filter on a few stored procedure name patterns to avoid showing known mainenance/analysis procs. Assuming we even continue to care about procedures with recompile hints, we should skip the same databases that we skip other checks on:
* master, model, msdb
* dbadmin, dbatools, etc.

**Describe the solution you'd like**
Leave obvious system and utility databases alone

**Describe alternatives you've considered**
Soothsaying

**Are you ready to build the code for the feature?**
Yeah, it's a quick change to the dynamic SQL.

**Comment by BrentOzar** [comment]
Good catch. I went ahead & did it because I wanted to get a release out this week.
