### ISSUE TITLE
Minor fix to comments section of sp_blitzindex

### ISSUE THREAD

**Issue by thornersetrans** [BrentOzarULTD/SQL-Server-First-Responder-Kit#313]
Add one addition line to comments of sp_blitzindex:

CHANGE LOG :
    Mar 20, 2016 (3.0)
        Prioritized results
Line I added:
	Mode now defaults to 0, Diagnose. Mode=4 gives results that previous versions defaulted to
Rest of comments:
        Moved URL to near the end of columns
        etc.

**Comment by BrentOzar** [comment]
Let's not rearrange column output unless there's a reason - folks have built tools that rely on the output of these scripts.

**Comment by thornersetrans** [comment]
Sorry, you misunderstood.  All I am suggesting is that the line:
"Mode now defaults to 0, Diagnose. Mode=4 gives results that previous versions defaulted to"
be added to the CHANGE LOG comments of the SP so that users of previous versions not be confused when suddenly they have a lot less output because mode=0 is now the default.  Sorry for the confusion. You may have better way of stating this.

**Comment by BrentOzar** [comment]
Oh, okay, we don't really take suggestions here. If you'd like to change the code, you're welcome to fork it, make the change yourself, and then submit a pull request for your change.

**Comment by BrentOzar** [comment]
For more info about how to contribute to the project, check this out:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

Thanks!
