### ISSUE TITLE
sp_RestoreDatabase: Possibility to restore all (user or system) databases

### ISSUE THREAD

**Issue by MaiklT** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3131]
**Describe the solution you'd like**
Ola Hallengren's backup script have the possibility to pass "USER_DATABASES" or "SYSTEM_DATABASES"  (or a list of databases etc.) as the parameter value for @Databases. It would be nice to have such a possibility as well... (OK, I know, the procedure is called sp_RestoreDatabase, not sp_RestoreDatabase**s**)

**Are you ready to build the code for the feature?**
I am not sure if I have enough knowledge for this. But I'll give it a try...

**Comment by BrentOzar** [comment]
Thanks for the offer, but for the sake of simplicity, let's keep this one as-is. It's already challenging enough to maintain.

If you need to restore multiple databases, your best bet is to build a wrapper around this stored procedure.
