### ISSUE TITLE
Url for `sp_Blitz - Performance - Parallelism Rocket Surgery` Broken

### ISSUE THREAD

**Issue by imajaydwivedi** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3133]
**Version of the script**
8.10

**What is the current behavior?**
`sp_Blitz` result has url [https://www.BrentOzar.com/go/makeparallel](https://www.BrentOzar.com/go/makeparallel) for CheckId 115 `Parallelism Rocket Surgery`. This url is not taking to page [http://sqlblog.com/blogs/adam_machanic/archive/2013/07/11/next-level-parallel-plan-porcing.aspx](http://sqlblog.com/blogs/adam_machanic/archive/2013/07/11/next-level-parallel-plan-porcing.aspx) which seems to not exist anymore.

**If the current behavior is a bug, please provide the steps to reproduce.**
Copy/paste url [https://www.BrentOzar.com/go/makeparallel](https://www.BrentOzar.com/go/makeparallel). It would eventually throw "connection timeout error".

**What is the expected behavior?**
Expecting to reach a valid webpage after putting [https://www.BrentOzar.com/go/makeparallel](https://www.BrentOzar.com/go/makeparallel) on web browser.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
NA

**Comment by BrentOzar** [comment]
It's working okay here - you might try from another machine, or try resetting your browser cache.

**Comment by BrentOzar** [comment]
Also, just to be clear - it's redirecting to here: http://dataeducation.com/next-level-parallel-plan-forcing-an-alternative-to-8649/
