### ISSUE TITLE
sp_DatabaseRestore errors out on SQL Server 2022 

### ISSUE THREAD

**Issue by hold-fast-1971** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3135]
Line: 

SET @HeadersSQL = 
N'INSERT INTO #Headers WITH (TABLOCK)
  (BackupName, BackupDescription, BackupType, ExpirationDate, Compressed, Position, DeviceType, UserName, ServerName
  ,DatabaseName, DatabaseVersion, DatabaseCreationDate, BackupSize, FirstLSN, LastLSN, CheckpointLSN, DatabaseBackupLSN
  ,BackupStartDate, BackupFinishDate, SortOrder, CodePage, UnicodeLocaleId, UnicodeComparisonStyle, CompatibilityLevel
  ,SoftwareVendorId, SoftwareVersionMajor, SoftwareVersionMinor, SoftwareVersionBuild, MachineName, Flags, BindingID
  ,RecoveryForkID, Collation, FamilyGUID, HasBulkLoggedData, IsSnapshot, IsReadOnly, IsSingleUser, HasBackupChecksums
  ,IsDamaged, BeginsLogChain, HasIncompleteMetaData, IsForceOffline, IsCopyOnly, FirstRecoveryForkID, ForkPointLSN
  ,RecoveryModel, DifferentialBaseLSN, DifferentialBaseGUID, BackupTypeDescription, BackupSetGUID, CompressedBackupSize

needs the following columns added to the temp table definition and insert list (new in resultset for SQL Server 2022):
LastValidRestoreTime
TimeZone
CompressionAlgorithm

the statament that is run causing the issue is:
EXEC ('RESTORE HEADERONLY FROM DISK='...')

Error: 
Msg 213, Level 16, State 7, Line 23
Column name or number of supplied values does not match table definition.
Msg 3013, Level 16, State 1, Line 23
RESTORE HEADERONLY is terminating abnormally.

Other than that it is work fine in SQL Server 2022 CTP!

**Comment by BrentOzar** [comment]
Because SQL Server 2022 is pre-release, the contents of system queries can change leading up to release. I'm going to go ahead and close this for now, but once it releases, if you'd like to submit a pull request with the code necessary to get it to work, we'd welcome that. Thanks!
