### ISSUE TITLE
sp_BlitzLock @DatabaseName = 'OneDB' lists object_names where objects are in another database than specified

### ISSUE THREAD

**Issue by UrbSve** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3137]
**Version of the script**
Version = '8.10', VersionDate = '20220718'

**What is the current behavior?**
When running "sp_BlitzLock" without any other parameters followed by running "sp_BlitzLock @Database='someDB'" thera are rows where object_names contains both the object name from the specified database and another object name has been added and where the extra object does not reside in the database specified by @DatabaseName.

**If the current behavior is a bug, please provide the steps to reproduce.**
Run: EXEC sp_BlitzLock
Run: EXEC sp_BlitzLock @someDB

**What is the expected behavior?**
Object names from the current database only.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Windows Server 2019 and SQL Server 2019 CU16

![Object_Names](https://user-images.githubusercontent.com/96235267/189647763-bfee4c41-607a-43bc-a7d6-bd846b20dbb2.png)

**Comment by BrentOzar** [comment]
That can happen if the database name isn't populated in the deadlock graph (if the database name is null in that file, for example) or if the query context is in a different database (like cross-database queries.)

If you think you have an example where that isn't the case, can you include the exact contents of the deadlock graph, or a repro script? That way we can troubleshoot the logic in it. Thanks!
