### ISSUE TITLE
SQL "USE" statement is not supported in azure sql database...

### ISSUE THREAD

**Issue by SJOrderDIRECT** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3138]
v8.10 - 20220718

Creating the sp_BlitzFirst.sql stored procedure in an Azure environment produces the "USE statement is not supported in azure SQL database" error message.

On line 2474, 'USE [?]' is still being included in the concatenation of the @StringToExecute variable.

**Comment by BrentOzar** [comment]
Great catch! Fixed in the dev branch, will be in the next release with credit to you in the release notes.
