### ISSUE TITLE
Possible bug in sp_blitzindex?

### ISSUE THREAD

**Issue by thornersetrans** [BrentOzarULTD/SQL-Server-First-Responder-Kit#314]
When running sp_blitzindex with mode=0, I get all heap tables with forwarded fetches. With mode=4, I get a subset of those.  Looking at SP it appears that when using mode=4 heap size has to be greater than ThresholdMB to be reported, yet all are reported if mode=0.  Is this as designed?

**Comment by BrentOzar** [comment]
It isn't designed that way, no.

**Comment by BlitzErik** [comment]
#430
