### ISSUE TITLE
Control Suppressing of Output Messages in Blitz Scripts

### ISSUE THREAD

**Issue by imajaydwivedi** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3144]
**Is your feature request related to a problem? Please describe.**
I execute `sp_Blitz**` scripts from SQLNotebooks (through PowerShell). The execution of procedures return 2 types of results-

- "output_type":  "execute_result"
- "output_type":  "display_data"

Output_type `execute_result` has option to collapse, but there is not for output_type `display_data` that is quite a lot in `sp_Blitz**` scripts result.

![image](https://user-images.githubusercontent.com/18259277/193023375-471940a9-7541-4090-91bb-c56b8e61b471.png)

**Describe the solution you'd like**
A parameter in the stored procedure that lets me suppress these `display_data` output_type.

**Describe alternatives you've considered**
I tried reading *.ipynb json files using PowerShell to remove the display_data text, and resave the SQL Notebook. But seems little complex.

**Are you ready to build the code for the feature?**
Yes, I can code if required. No ready code yet.

**Comment by BrentOzar** [comment]
Sure, if that's something you'd like, a pull request for that would be welcome. Thanks!

**Comment by imajaydwivedi** [comment]
Hi @BrentOzar, I am ready with the code, kindly point me to your blog/video that can help me understand how to submit PR. 
I took pull request of dev branch, and tried to push updated code as a new branch, but get permission error -

![image](https://user-images.githubusercontent.com/18259277/193288195-9ef7315f-3e22-4675-a88a-739d12c7dd00.png)

**Comment by BrentOzar** [comment]
Howdy sir. Looks like a lot of files were changed in here that you probably didn't mean to change - click the "Files changed" tab: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/3145/files

Can you give it another shot, only changing the necessary files? I'm not sure if you maybe started with an old version, perhaps?

**Comment by BrentOzar** [comment]
There hasn't been any activity on here in a while, so closing. If you want to work on it again, feel free to leave a note here and open a new pull request with your changes. Thanks, and happy holidays!
