### ISSUE TITLE
sp_Blitz - Update Dangerous Third Party Modules

### ISSUE THREAD

**Issue by DavidWiseman** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3147]
**Is your feature request related to a problem? Please describe.**
There is already a Dangerous Third Party Modules check but this should be extended to include CrowdStrike dlls.  These were highlighted in a recent RCA with Microsoft to investigate why an AG went offline.
ScriptControl64_15316.dll
umppc15316.dll

Additionally, this link provides some extra modules to blacklist:
https://learn.microsoft.com/en-us/troubleshoot/sql/performance/performance-consistency-issues-filter-drivers-modules

**Describe the solution you'd like**
Update the Dangerous Third Party Modules check to include the modules listed in the MS docs.

**Describe alternatives you've considered**
N/A

**Are you ready to build the code for the feature?**
Yes!  I'll submit a PR for review and consideration.  Feel free to amend/reject.

**Comment by DavidWiseman** [comment]
What news?  I must have missed it.
This came out of a recent RCA with MS.  Currently working on updating [DBA Dash ](https://github.com/trimble-oss/dba-dash/issues/309) to include this check also.

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good. Merging into the dev branch, will be in the next release with credit to you in the release notes.

**Comment by BrentOzar** [comment]
This news: https://medium.com/@DCSO_CyTec/mssql-meet-maggie-898773df3b01

**Comment by DavidWiseman** [comment]
Thanks for reviewing/accepting the PR and the link.  I did see this one:
https://www.seangallardy.com/ffs-not-everything-is-a-sql-server-vulnerability/
Seems like you are already compromised by the time they manage to load the dll.  

Is it worth adding sqlmaggieAntiVirus_64.dll to the blacklist?  Or maybe just %AntiVirus% as anything labelled AntiVirus probably isn't good.  I'll create another PR if you like.  Let me know.

**Comment by BrentOzar** [comment]
Yeah, I think so - that'd be awesome!
