### ISSUE TITLE
sp_Blitz - Update Dangerous Third Party Modules for AntiVirus

### ISSUE THREAD

**Issue by DavidWiseman** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3149]
**Is your feature request related to a problem? Please describe.**
Following on from #3147, adding %ANTIVIRUS% to the list of dangerous modules. 

This article highlights some malware calling itself sqlmaggieAntiVirus_64.dll.

https://medium.com/@DCSO_CyTec/mssql-meet-maggie-898773df3b01

Anything with %ANTIVIRUS% in the name - malware or legitimate AV software is likely to be dangerous.

**Describe the solution you'd like**
Updated list

**Describe alternatives you've considered**
N/A

**Are you ready to build the code for the feature?**
Yes! PR coming soon.

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, merging into the dev branch. Will be in the next release with credit to you in the release notes.
