### ISSUE TITLE
sp_Blitz error on German server: converting varchar to datetime, value out of range

### ISSUE THREAD

**Issue by christianspecht** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3161]
**Version of the script**
`@Version = '8.11', @VersionDate = '20221013';`

**What is the current behavior?**
Executing sp_Blitz opens the result table at the end, but also returns an error message.

Original German message:

> Nachricht 242, Stufe 16, Status 3, Prozedur sp_Blitz, Zeile 1050 [Batchstartzeile 0]  
Bei der Konvertierung eines varchar-Datentyps in einen datetime-Datentyp liegt der Wert außerhalb des gültigen Bereichs.

English translation of the error message:

> When converting a varchar data type to a datetime data type, the value is out of range.

**If the current behavior is a bug, please provide the steps to reproduce.**

Nothing special, just `exec sp_Blitz`

**What is the expected behavior?**

The error message shouldn't occur.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

`select @@VERSION` result:

> Microsoft SQL Server 2016 (SP1-CU15-GDR) (KB4505221) - 13.0.4604.0 (X64) 
	Jun 15 2019 07:56:34 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: )

The OS **and** the SQL Server installation are both in German.

Until yesterday, the same server was running `@Version = '8.03', @VersionDate = '20210420'`, where the error didn't occur.

## More information, including part of the solution:

The error happens in [this line](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/commit/3a823b8fbfc57d57e5901389f0f1ca672a115385#diff-ec9e8d5bcf4f22d4401357f0a78d82ecaa6598017e9a3108225ab3768fa8108bR1094), which was added in this month's release:

	OR
	(
		Convert(datetime,ll.Value) < DATEADD(dd,-7, GETDATE())
	)

`ll.Value` is a `varchar` column, which contains a date value.  
(date of the last log backup, `select * from #DBCCs where Field = 'dbi_LastLogBackupTime'`)

Some DBs on this server have values from today (`2022-10-27 10:40:00.983`), and some DBs with simple recovery never had log backups, so the date is `1900-01-01 00:00:00.000`.

This is *(at least for me)* a known problem on German versions of SQL Server: casting/converting a string to datetime doesn't recognize the date in the format `yyyy-mm-dd`, but `yyyymmdd` works.

Examples I just executed on this server:

	select convert(datetime,'2022-10-27 10:40:00.983')  --> throws the error mentioned above
	select convert(datetime,'20221027 10:40:00.983')    --> converts successfully
	select convert(datetime,'1900-01-01 00:00:00.000')  --> converts successfully too - I'm not sure why *this* date works

I can "fix" this by just removing the `-` from the string:

	select convert(datetime, replace('2022-10-27 10:40:00.983', '-', '')) --> converts successfully

So I changed the line in sp_Blitz to this, so it works *on my server*:

	OR
	(
		Convert(datetime,replace(ll.Value, '-', '')) < DATEADD(dd,-7, GETDATE())
	)

**I'd love to contribute this fix to sp_Blitz, but I'm not sure how to write it so it works on all SQL Servers, no matter which language.**

**Comment by luporpi** [comment]
I think convert should be called using the parameter style = 21. 

https://learn.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-2016

`Convert(datetime,ll.Value,21) < DATEADD(dd,-7, GETDATE())`

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good. Merging into the dev branch, will be in the December release with credit to you in the release notes.

**Comment by ikhzter** [comment]
Thank you very much for fixing this issue!
