### ISSUE TITLE
sp_BlitzWho - shows procedure definition not the current statement in query_text if proc is executing for the first time

### ISSUE THREAD

**Issue by Adedba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3163]
**Version of the script**
SELECT @Version = '8.11', @VersionDate = '20221013';

**What is the current behavior?**
If you have a stored procedure executing for the first time (not in the plan cache) the query_text column will not show you the current statement being executed, it will show you the stored procedure definition instead.

**If the current behavior is a bug, please provide the steps to reproduce.**

Clear your cache (DBCC FREEPROCCACHE) 

create a stored procedure: 

```
USE [StackOverflow];
GO

CREATE PROCEDURE usp_GetTopVotesByYearAndMonth
AS 
BEGIN 
	
	SELECT /* Query 1 of 2 */ TOP (10) 
		DATENAME(YEAR,[CreationDate]) AS VoteYear,
		COUNT(CreationDate) AS TotalVotes
	FROM [dbo].[Votes] v
	INNER JOIN [dbo].[VoteTypes] vt ON v.[VoteTypeId] = vt.[Id]
	GROUP BY 
		DATENAME(YEAR,[CreationDate])
	ORDER BY 
		[TotalVotes] DESC;	
	
	SELECT /* Query 2 of 2 */ TOP (10) 
		DATENAME(MONTH,[CreationDate]) AS VoteMonth,
		COUNT(CreationDate) AS TotalVotes
	FROM [dbo].[Votes] v
	INNER JOIN [dbo].[VoteTypes] vt ON v.[VoteTypeId] = vt.[Id]
	GROUP BY 
		DATENAME(MONTH,[CreationDate])
	ORDER BY 
		[TotalVotes] DESC;		
END 
go
```

Query window 1: Execute stored procedure:
`EXEC usp_GetTopVotesByYearAndMonth;`

Query window 2: Execute sp_BlitzWho:
`EXEC sp_BlitzWho
`
Observer the query_text column, this will contain the stored procedure definition. 

Now execute your stored procedure again and the execute sp_BlitzWho whilst running and you will notice that this time the statement being executed will now show in the query_text column. 

**What is the expected behavior?**
For the current statement in a stored procedure to show in the query_text column

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Tested on SQL 2016

**Comment by BrentOzar** [comment]
Howdy sir! Did you want to code a change for this? If not, let me know and I'll close it - the current implementation is alright for my purposes.

**Comment by BrentOzar** [comment]
@Adedba I haven't heard back from you, so I'll go ahead and close this for now, but if you decide you want to work on it, you can leave a comment here when you're ready to do a pull request, and I can reopen it.

**Comment by Adedba** [comment]
Thanks Brent, I did a commit which was ready to go just forgot to raise a pull request but I have created one now.

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, merging into the dev branch. Will be in the next release with credit to you in the release notes.
