### ISSUE TITLE
sp_BlitzIndex: skips database when > 100 partitions

### ISSUE THREAD

**Issue by ZedZipDev** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3167]
sp_BlitzIndex(TM) v8.11 - October 13, 2022: All Databases
SQL Server 2019
I run EXEC sp_BlitzIndex @GetAllDatabases=1

and receive 

Database Skipped: dog
Over 100 partitions found - use @BringThePain = 1 to analyze

Then I run the query
SELECT so.name,p.* FROM sys.partitions p inner join sys.sysobjects so on p.object_id=so.id WHERE partition_number > 1 OPTION    ( RECOMPILE );
and see the result: 170 partitions  like this
ifts_comp_fragment_1336391830_19755845
etc 

As I understand it is not a problem for index analyze because it is FTS partitions.

**Comment by BrentOzar** [comment]
OK, so you can run @BringThePain = 1 then.
