### ISSUE TITLE
sp_BlitzIndex - when >50 databases, return error in result rather than printing it

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#317]
sp_BlitzIndex v4 correctly bails out when we have >50 databases, but that it's printing an error message rather than returning a result set. We should return a result set so folks parsing the output can see it:

Starting run. sp_BlitzIndex(R) v3.0 - March 20, 2016
Create temp tables.
You're trying to run sp_BlitzIndex on a server with 102 databases. 
Running sp_BlitzIndex on a server with 50+ databases may cause temporary insanity for the server and/or user.
If you're sure you want to do this, run again with the parameter @BringThePain = 1.

**Comment by BlitzErik** [comment]
#430
