### ISSUE TITLE
sp_BlitzCache - Add Pattern column for @SortOrder = 'all' and include when outputting to table

### ISSUE THREAD

**Issue by Adedba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3172]
**Is your feature request related to a problem? Please describe.**
Would be good if sp_Blitzcache could show which sort order was used per result row when using @Sortorder = 'all' especially for when you log this information to a table.

Currently if you query your BlitzCache output table you dont really know why a specific row is there, you could sort by various columns such as totalCPU etc however you may have a query/proc that has made it in the top 5 for a few different sort orders in which case getting the top 5 per CheckDate gets skewed.

**Describe the solution you'd like**
Have sp_BlitzCache return the Pattern column in the result set to show which sort order was used for the row
If this change is accepted I would like to revise sp_BlitzAnalysis to use this new column too.

Not sure if adding this new column for SortOrder = 'all' will break anything that relys on the current schema produced by sp_BlitzCache.

I have tested a revision with the following calls which succeed: 

```
EXEC [dbo].[sp_BlitzFirst] 
	@OutputDatabaseName = 'DBA',
	@OutputSchemaName = 'dbo',
	@OutputTableName = 'BlitzFirst',
	@OutputTableNameFileStats = 'BlitzFirst_FileStats',
	@OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
	@OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
	@OutputTableNameBlitzCache = 'BlitzCache',
	@OutputTableNameBlitzWho = 'BlitzWho';
```

```
EXEC sp_BlitzCache
	@Top=5,
	@SortOrder= 'all', 
	@OutputDatabaseName = 'DBA',
	@OutputSchemaName = 'dbo',
	@OutputTableName = 'BlitzCache_test'
```

`EXEC sp_BlitzCache @SortOrder = 'all'`

**Describe alternatives you've considered**
No other solutions I can think of.

**Are you ready to build the code for the feature?**
You bet!

**Comment by Adedba** [comment]
Made a first revision for testing.

**Comment by BrentOzar** [comment]
@Adedba I haven't heard back from you, so I'll go ahead and close this for now, but if you decide you want to work on it, you can leave a comment here when you're ready to do a pull request, and I can reopen it.

**Comment by Adedba** [comment]
Thanks Brent, I have created a pull request now.

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, merging into the dev branch. Will be in the next release with credit to you in the release notes.
