### ISSUE TITLE
sp_BlitzFirst - outer_command column in sp_BlitzWho logging

### ISSUE THREAD

**Issue by aroques** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3182]
**Is your feature request related to a problem? Please describe.**
When `sp_BlitzFirst` logs `sp_BlitzWho` to disk, I want to see what stored procedure that the queries are running under if applicable. 

**Describe the solution you'd like**
I'd like the `outer_command` column that you get when you call `EXEC sp_BlitzWho @GetOuterCommand = 1;` when `sp_BlitzFirst` logs `sp_BlitzWho` to disk:
```sql
EXEC sp_BlitzFirst 
  @OutputDatabaseName = 'BlitzDB', 
  @OutputSchemaName = 'dbo', 
  @OutputTableName = 'BlitzFirst',
  @OutputTableNameFileStats = 'BlitzFirst_FileStats',
  @OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
  @OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
  @OutputTableNameBlitzCache = 'BlitzCache',
  @OutputTableNameBlitzWho = 'BlitzWho',
  @OutputTableRetentionDays = 30;
```

**Describe alternatives you've considered**
It might need to be an additional flag so that it doesn't break existing code.
Like `@OutputBlitzWhoParameters = '@GetOuterCommand = 1'`.

**Are you ready to build the code for the feature?**
I can try!

**Comment by erikdarlingdata** [comment]
@aroques I've added you as the assignee here. If you decide you don't want to work on it for any reason, let us know. Thanks1

**Comment by BrentOzar** [comment]
@aroques I haven't heard back from you, so I'll go ahead and close this for now, but if you decide you want to work on it, you can leave a comment here when you're ready to do a pull request, and I can reopen it.
