### ISSUE TITLE
sp_AllNightLog

### ISSUE THREAD

**Issue by RubberChickenParadise** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3186]
**Is your feature request related to a problem? Please describe.**
What is the expected behavior for sp_AllNightLog for databases in with a simple recovery model?  I am setting up a DR server using log shipping for the databases that have a FULL recovery model.  However, since the SIMPLE recovery databases do not have a `LOG` folder, if they are not ignored, sp_DatabaseRestore throws an error because the constructed path `SET @restore_path_log = @restore_path_base + N'\' + @database + N'\' + N'LOG\'` does not exist.

Is sp_AllNightLog the right tool to handle the log shipping for BULK or FULL databases and nightly restores for the SIMPLE databases?  (With or without additional development?)

**Describe the solution you'd like**
When using sp_AllNightLog, if a database does not exist on the secondary server but exists on disk (on the primary server's backup directory from using Ola's scripts) restore the database with `NORECOVERY`.  If the database has a logged recovery model (FULL or BULK LOG), restore any logs.  If the database has a SIMPLE recovery model, check the most recent backup on the `@RestorePath`, and if the backup is newer than what was previously restored, perform a full restore of the database with `NORECOVERY`.

**Describe alternatives you've considered**
Option 1: A mix of sp_AllNightLog for the FULL databases and custom coding for the SIMPLE databases
Option 2: Going full custom but that is reinventing the wheel for something that is basically solved

**Are you ready to build the code for the feature?**
If the intention for sp_AllNightLog is "Keep the Secondary server up to date with the most recent backup" then yes.

**Comment by BrentOzar** [comment]
No, as you might guess from the clever name, sp_AllNightLog is focused on log shipping. If you just want to restore fulls and doffs, check out sp_DatabaseRestore.
