### ISSUE TITLE
sp_AllNightLog - Fix known issue 'overwrites existing databases without warning.'

### ISSUE THREAD

**Issue by DavidWiseman** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3187]
**Is your feature request related to a problem? Please describe.**
sp_AllNightLog will overwrite existing databases without warning as [documented here.](https://www.brentozar.com/sp_AllNightLog/).  This behaviour could potentially result in data loss if users don't read the documentation.  I believe adding some safety checks will be a good idea.

Additionally, there is a 'bug' with the ignore_database option.  This only works for newly added databases.  The OR condition should be wrapped in some additional brackets.  See highlighted comment below:

```sql
WHERE 
/*!!!! We should have a bracket here : 
( 
*/
			(		/*This section works on databases already part of the backup cycle*/
						rw.is_started = 0
		AND rw.is_completed = 1
		AND rw.last_log_restore_start_time < DATEADD(SECOND, (@rto * -1), GETDATE()) 
                                      AND (rw.error_number IS NULL OR rw.error_number > 0) /* negative numbers indicate human attention required */
			)
OR    
			(		/*This section picks up newly added databases by DiskPollster*/
								rw.is_started = 0
				AND rw.is_completed = 0
				AND rw.last_log_restore_start_time = '1900-01-01 00:00:00.000'
				AND rw.last_log_restore_finish_time = '9999-12-31 00:00:00.000'
                                      AND (rw.error_number IS NULL OR rw.error_number > 0) /* negative numbers indicate human attention required */
			)
/*!!!! And a closing one here : 
)
*/
AND rw.ignore_database = 0
```

**Describe the solution you'd like**

I believe we should exclude existing databases unless they are in a restoring or standby state.  Adding this to the de queue statement would solve the issue:

```sql
AND NOT EXISTS	(
					/* Validation check to ensure the database either doesn't exist or is in a restoring/standby state */
					SELECT 1 
					FROM sys.databases d
					WHERE d.name = rw.database_name COLLATE SQL_Latin1_General_CP1_CI_AS
					AND state<> 1 /* Restoring */
					AND NOT (state=0 AND d.is_in_standby=1) /* standby mode */
				)
```

If there is an existing DB with the same name there would need to be manual intervention to fix - I think this is appropriate.  These DBs would appear in the restore_worker table with a last_log_restore_start_time  of 1900-01-01 00:00:00.000 etc.  Users could add some monitoring for this.

**Describe alternatives you've considered**
Although the issue is documented I believe some extra safety checks are appropriate. 

**Are you ready to build the code for the feature?**
Yes!  I will follow up with a PR.

Note:
I'm not a user of sp_AllNightLog but I recommended it to a colleague that has a large number of DBs.  I've been playing about with it in a lab environment so I'm able to give them a hand with the setup.

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, merging into the dev branch, will be in the next release with credit to you in the release notes.
