### ISSUE TITLE
sp_DatabaseRestore fails on SQL Server 2022

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3190]
**Version of the script**
SELECT @Version = '8.11', @VersionDate = '20221013';

**What is the current behavior?**
If you execute it on SQL Server 2022, it fails because RESTORE HEADERONLY added 3 new undocumented columns: LastValidRestoreTime, TimeZone, and CompressionAlgorithm. Known issue in SQL Server 2022: https://github.com/MicrosoftDocs/sql-docs/issues/7879

**If the current behavior is a bug, please provide the steps to reproduce.**
Run sp_DatabaseRestore with any parameters, any database, and it'll fail.

**What is the expected behavior?**
Whenever Microsoft changes the result set of the product's stored procedures, they should - 

oh wait, you meant - never mind. That's obviously not gonna happen, ha ha ho ho. Instead, we'll just take our best guess at the data types in sp_DatabaseRestore.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Only SQL Server 2022, which is surely production ready despite the lack of documentation.

**Comment by rsocol** [comment]
The data types are now documented. They are actually smaller than your guess: nvarchar(32) instead of nvarchar(256). So you can leave it like this or update it, your choice.

**Comment by BrentOzar** [comment]
@rsocol thanks for the heads up. I went ahead and changed 'em to NVARCHAR(32) to match the documentation.
