### ISSUE TITLE
Out of Range Value

### ISSUE THREAD

**Issue by ikhzter** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3199]
Hi

I tried running the latest version of SP Blitz and i get the error message below:

Msg 242, Level 16, State 3, Procedure sp_Blitz, Line 1048 [Batch Start Line 5]
The conversion of a varchar data type to a datetime data type resulted in an out-of-range value.
The statement has been terminated.

I do not have any issues running/reverting to the previous July release.

**Comment by BrentOzar** [comment]
Howdy. When you open an issue, there's a set of questions in the issue - we do actually need that filled out.

I'll close this so you can fill it out again with the text included. *Do not delete the questions, and fill in your answers.*

Thanks for understanding!
