### ISSUE TITLE
sp_AllNightLog - Error Handling Issues

### ISSUE THREAD

**Issue by DavidWiseman** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3203]
sp_AllNightLog - Error Handling

**Is your feature request related to a problem? Please describe.**

I was helping a colleague setup sp_AllNightLog where the restores were not working. This had a simple solution - the CommandLog table was missing, but troubleshooting the issue wasn't straightforward due to the error handling in sp_AllNightLog.

If you run sp_DatabaseRestore and the CommandLog table is missing you get a nice error message:

```
Msg 50000, Level 16, State 1, Procedure dbo.CommandExecute, Line 157 [Batch Start Line 7]
The table CommandLog is missing. Download https://ola.hallengren.com/scripts/CommandLog.sql.
```

If you run `EXEC sp_AllNightLog @Restore = 1,@Debug=1`, the error is caught.  The CATCH block doesn't actually do anything.  We get `Error number IS NULL` (normal/expected) and `Updating backup_worker for database DB1 for UNsuccessful backup`. These are normal print statements and we don't get any additional information about what caused the error.  We only get the UNsuccessful backup message as there is a check outside the CATCH block to see if we have a DB in a restoring state.

```
Checking restore path
Beginning Restores
Checking variables
Begin tran to grab a database to restore
Updating restore_worker for database DB1
Restoring full backup for DB1
Path for FULL backups for DB1 is \\LAB2022\Backup\LAB2019NODE1\DB1\FULL\
Path for LOG backups for DB1 is \\LAB2022\Backup\LAB2019NODE1\DB1\LOG\
Starting first Full restore from: 
\\LAB2022\Backup\LAB2019NODE1\DB1\FULL\
Getting default data drive for @MoveDataDrive
Getting default log drive for @MoveLogDrive
Setting default data drive for @MoveFilestreamDrive
Setting default data drive for @MoveFullTextCatalogDrive
DIR /b "\\LAB2022\Backup\LAB2019NODE1\DB1\FULL\"
INSERT INTO #FileListParameters WITH (TABLOCK)
       (LogicalName, PhysicalName, Type, FileGroupName, Size, MaxSize, FileID, CreateLSN, DropLSN
       ,UniqueID, ReadOnlyLSN, ReadWriteLSN, BackupSizeInBytes, SourceBlockSize, FileGroupID, LogGroupGUID
       ,DifferentialBaseLSN, DifferentialBaseGUID, IsReadOnly, IsPresent, TDEThumbprint, SnapshotUrl)
EXEC ('RESTORE FILELISTONLY FROM DISK=''\\LAB2022\Backup\LAB2019NODE1\DB1\FULL\LAB2019NODE1_DB1_FULL_20221215_000000.bak''')
INSERT INTO #Headers WITH (TABLOCK)
  (BackupName, BackupDescription, BackupType, ExpirationDate, Compressed, Position, DeviceType, UserName, ServerName
  ,DatabaseName, DatabaseVersion, DatabaseCreationDate, BackupSize, FirstLSN, LastLSN, CheckpointLSN, DatabaseBackupLSN
  ,BackupStartDate, BackupFinishDate, SortOrder, CodePage, UnicodeLocaleId, UnicodeComparisonStyle, CompatibilityLevel
  ,SoftwareVendorId, SoftwareVersionMajor, SoftwareVersionMinor, SoftwareVersionBuild, MachineName, Flags, BindingID
  ,RecoveryForkID, Collation, FamilyGUID, HasBulkLoggedData, IsSnapshot, IsReadOnly, IsSingleUser, HasBackupChecksums
  ,IsDamaged, BeginsLogChain, HasIncompleteMetaData, IsForceOffline, IsCopyOnly, FirstRecoveryForkID, ForkPointLSN
  ,RecoveryModel, DifferentialBaseLSN, DifferentialBaseGUID, BackupTypeDescription, BackupSetGUID, CompressedBackupSize
, Containment, KeyAlgorithm, EncryptorThumbprint, EncryptorType)
EXEC ('RESTORE HEADERONLY FROM DISK=''\\LAB2022\Backup\LAB2019NODE1\DB1\FULL\LAB2019NODE1_DB1_FULL_20221215_000000.bak''')
@MoveFiles = 1, adjusting paths
 
@ExistingDBAction 0 so do nothing
@ContinueLogs set to 0
RESTORE DATABASE [DB1] FROM DISK = '\\LAB2022\Backup\LAB2019NODE1\DB1\FULL\LAB2019NODE1_DB1_FULL_20221215_000000.bak' WITH NORECOVERY, REPLACE
Error number IS NULL
Updating backup_worker for database DB1 for UNsuccessful backup
Begin tran to grab a database to restore
No databases to restore up right now, starting 3 second throttle
```

**Describe the solution you'd like**

A check could be added to see if the CommandLog table exists.  This would be a simple fix that could save someone some time that runs into the same issue. Fixing the error handling has some additional complexity but it would make it easier to troubleshoot any other issues that might occur. 

I believe this is where we are going wrong - we are capturing the error number etc within the TRY block.  This should be moved down to the catch block.

```sql
        BEGIN TRY
        ...
        ...
                            /*
                            
                            Catch any erroneous zones
                            
                            */
                            
                            SELECT @error_number = ERROR_NUMBER(), 
                                    @error_severity = ERROR_SEVERITY(), 
                                    @error_state = ERROR_STATE();

                    END; --End call to dbo.sp_DatabaseRestore

            END; --End successful check of @database (not NULL)
        
        END TRY

        BEGIN CATCH

            IF  @error_number IS NOT NULL
```

Moving the `SELECT @error_number = ...` down to the `BEGIN CATCH` block would improve things slightly.  The text is highlighted red and it's more obvious that a problem has occurred.  We can see the error number.  This tells us it's a user error message but it doesn't identify exactly what the issue is - additional troubleshooting would still be required.

```
RESTORE DATABASE [DB1] FROM DISK = '\\LAB2022\Backup\LAB2019NODE1\DB1\FULL\LAB2019NODE1_DB1_FULL_20221215_000000.bak' WITH NORECOVERY, REPLACE
Msg 50000, Level 16, State 1, Procedure sp_AllNightLog, Line 1390 [Batch Start Line 2]
Error number is 50000
Updating restore_worker for database DB1 for unsuccessful backup
```

Using THROW would give us a nice error message but would abort the execution of the batch.  We could build a nice error message instead with something like this:

```sql
SET @msg = N'Error number: ' + ISNULL(CONVERT(NVARCHAR(10), ERROR_NUMBER()),N'') 
            + N', Line: ' + ISNULL(CAST(ERROR_LINE() AS NVARCHAR(10)),N'') 
            + N', Severity: ' + ISNULL(CAST(ERROR_SEVERITY() AS NVARCHAR(10)),N'') 	
            + N', State: ' + ISNULL(CAST(ERROR_STATE() AS NVARCHAR(10)),N'')  
            + N', Procedure: ' + ISNULL(ERROR_PROCEDURE(),N'')
            + N', Message: ' + ISNULL(ERROR_MESSAGE(),N''); 
```

We now have enough detail in the error message to know exactly what the problem is without any additional troubleshooting:
```
Msg 50000, Level 16, State 1, Procedure TEST, Line 21 [Batch Start Line 0]
Error number: 50000, Line: 157, Severity: 16, State: 1, Procedure: dbo.CommandExecute, Message: The table CommandLog is missing. Download https://ola.hallengren.com/scripts/CommandLog.sql.
```

There are similar issues with the error handling for backups also.

The improvements could be taken an additional step.  Ideally the error message would be logged in the backup_worker/restore_worker tables.  We would need an additional column added to the table to record the error message.  We would also need to handle upgrades from older versions of sp_AllNightLog.

**Describe alternatives you've considered**
-

**Are you ready to build the code for the feature?**

Yes.  I don't use sp_AllNighLog myself so I don't have that much experience with it.  I'm helping someone out though and I have it setup in a lab environment to test fixes.  I'm also happy if you prefer to make the code changes yourself.  I'll wait for feedback on how you want to proceed with this issue. Thanks. 😊

**Comment by BrentOzar** [comment]
I no longer use sp_AllNightLog either, so any changes would be left up to folks who want it. You're welcome to do it if you want, though.

**Comment by DavidWiseman** [comment]
Thanks - I'll take a look.  I'm guessing you created it to solve the log shipping at scale problem for a particular client and have now moved on.  Are there any other solutions you would recommend for log shipping large numbers of databases?  sp_AllNightLog seems like a reasonable approach.

**Comment by BrentOzar** [comment]
No, I don't do production DBA work anymore, only development DBA work (performance tuning.)

**Comment by DavidWiseman** [comment]
That's where the fun is 😁

**Comment by BrentOzar** [comment]
@DavidWiseman I haven't heard back from you, so I'll go ahead and close this for now, but if you decide you want to work on it, you can leave a comment here when you're ready to do a pull request, and I can reopen it.

**Comment by DavidWiseman** [comment]
I'm still interested in working on this, but it will be early in the new year before I'll look at it.
