### ISSUE TITLE
sp_blitzlock: String or binary data would be truncated in table 'tempdb.dbo.#deadlock_owner_waiter

### ISSUE THREAD

**Issue by johnkurtdk** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3206]
When I run this command
[dbo].[sp_blitzlock] @databasename ='ssisdb'
I got this error
String or binary data would be truncated in table 'tempdb.dbo.#deadlock_owner_waiter
I think reason is that in linie 1174:
lock_type = N'OBJECT'
it create a column named 'lock_type' and is 6 long but in linie 1355 it try this
lock_type = N'ROWGROUP'  (= 8 character)
so I think the solution can be
1) linie 1174 is changed from lock_type = N'OBJECT' to  lock_type = cast(N'OBJECT' as nvarchar(10))
2) or linie 1355 is changed from lock_type = N'ROWGROUP' to lock_type = N'ROWGR.'
I prefer option 1 :-)

I use :	SELECT @Version = '8.12', @VersionDate = '20221213';

p.s I don't know anything about Git so I hope I have done it right

**Comment by BrentOzar** [comment]
OK, I made the change, but I don't think that was actually what was causing the issue. On your machine, whenever you hit a bug like this, feel free to actually change the code to prove that it fixes the issue, just to be safe. I think the change is harmless, though, so I've made it. Cheers!
