### ISSUE TITLE
Sp_BlitzFirst intermittent failures

### ISSUE THREAD

**Issue by thecleverblonde** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3211]
@Version = '8.10', @VersionDate = '20220718'

--
First, thank you for providing the tools that you have. They've been helpful for a lot of my career. 
--
As to the behavior: The procedure runs as expected in most cases and logs the appropriate information as intended. However, it seems to fail intermittently and the error/failure message gets truncated before I can find out why it's failing. across 1000 executions it might fail 5 times. While that's a small failure rate, it's still annoying the person on-call who's getting failed job alerts and I'd like very much to mitigate this if possible. 
--
I've installed the FirstResponder tools in a utility database and am running them from a SQL Agent job: 

USE [utility database]; 
GO 

EXEC utility database.dbo.sp_BlitzFirst @OutputDatabaseName = 'utility database',
                           @OutputSchemaName = 'dbo',
                           @OutputTableName = 'BlitzFirst',
                           @OutputTableNameFileStats = 'BlitzFirst_FileStats',
                           @OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
                           @OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
                           @OutputTableNameBlitzCache = 'BlitzCache',
                           @OutputTableNameBlitzWho = 'BlitzWho', 
	           @OutputTableRetentionDays = 7; 

--
Collect performance metrics for reporting purposes. 
--
All instances are on SQL Server 2019. 

Again, I am appreciative of the work you and your team do to provide tools to the community. It means a lot and I hate to bother you with this but I can't seem to figure out why it's failing and I'd like to continue to use this as a tool in production. Thank you, in advance.

**Comment by BrentOzar** [comment]
Thanks for the kind words.

When you filled out this issue, you deleted all of the text in the issue - things that ask what the exact error message is, what version you're using, etc. I do need all of that, including the exact error message, or I can't help troubleshoot the problem.

I'm going to go ahead and close this issue, but feel free to open a new one - next time, keeping in all of the text in the issue and filling out the question. However, if you don't have the exact error message, I can't troubleshoot it.

Thanks!
