### ISSUE TITLE
Sp_BlitzFirst intermittent failures

### ISSUE THREAD

**Issue by thecleverblonde** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3213]
**Version of the script**
@Version = '8.10', @VersionDate = '20220718' (grabbed the latest version from the site and tested before submitting)

**What is the current behavior?**
The procedure runs as expected in most cases and logs the appropriate information as intended. However, it seems to fail intermittently and the error/failure message gets truncated before I can find out why it's failing; I believe it is a timeout in most cases. Across 1000 executions it might fail 5 times. While that's a small failure rate, it's still annoying the person on-call who's getting failed job alerts and I'd like very much to mitigate this if possible.

If it is a timeout issue, is there any way that I can have it fail gracefully without reporting an error that then generates a ticket for the on-call teammate? Not that I want it to fail at all, but if it does I'd rather simply be missing data rather than annoying someone with a non-actionable task. 

**If the current behavior is a bug, please provide the steps to reproduce.**
I've installed the FirstResponder tools in a utility database and am running them from a SQL Agent job every 15 minutes:

USE [utility database];
GO

EXEC utility database.dbo.sp_BlitzFirst @OutputDatabaseName = 'utility database',
@OutputSchemaName = 'dbo',
@OutputTableName = 'BlitzFirst',
@OutputTableNameFileStats = 'BlitzFirst_FileStats',
@OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
@OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
@OutputTableNameBlitzCache = 'BlitzCache',
@OutputTableNameBlitzWho = 'BlitzWho',
@OutputTableRetentionDays = 7;

Error Message: 
Executed as user: AGILENCEINC\cvssqlsvc. ...50000)  Now starting diagnostic analysis [SQLSTATE 01000] (Message 50000)  Checking for Read intent databases to exclude [SQLSTATE 01000] (Message 50000)  Determining SQL Server version. [SQLSTATE 01000] (Message 50000)  Capturing first pass of wait stats, perfmon counters, file stats [SQLSTATE 01000] (Message 50000)  Lock request time out period exceeded. [SQLSTATE 42000] (Error 1222)  The statement has been terminated. [SQLSTATE 01000] (Error 3621)  Logging sp_BlitzWho to table [SQLSTATE 01000] (Message 50000)  Checking for Read intent databases to exclude [SQLSTATE 01000] (Message 50000)  Beginning investigatory queries [SQLSTATE 01000] (Message 50000)  Finished running investigatory queries [SQLSTATE 01000] (Message 50000)  Capturing second pass of wait stats, perfmon counters, file stats [SQLSTATE 01000] (Message 50000)  Analyzing changes between first and second passes of DMVs [SQLSTATE 01000] (Message 50000)  Analysis finished, outputting results [SQLSTATE 01000] (Message 50000)  Calling sp_BlitzCache [SQLSTATE 01000] (Message 50000)  Checking @MinutesBack validity. [SQLSTATE 01000] (Message 50000)  Setting @MinutesBack to a negative number [SQLSTATE 01000] (Message 50000)  Creating temp tables for results and warnings. [SQLSTATE 01000] (Message 50000)  Checking database validity [SQLSTATE 01000] (Message 50000)  Checking sort order [SQLSTATE 01000] (Message 50000)  Skip Analysis set to 1, hiding Summary [SQLSTATE 01000] (Message 50000)  Cleaning up old warnings for your SPID [SQLSTATE 01000] (Message 50000)  Cleaning up old plans for your SPID [SQLSTATE 01000] (Message 50000)  Checking all sort orders, please be patient [SQLSTATE 01000] (Message 50000)  Beginning all sort loop [SQLSTATE 01000] (Message 50000)  Beginning for ALL [SQLSTATE 01000] (Message 50000)  Checking @MinutesBack validity. [SQLSTATE 01000] (Message 50000)  Creating temp tables for results and warnings. [SQLSTATE 01000] (Message 50000)  Checking database validity [SQLSTATE 01000] (Message 50000)  Checking sort order [SQLSTATE 01000] (Message 50000)  Skip Analysis set to 1, hiding Summary [SQLSTATE 01000] (Message 50000)  Cleaning up old warnings for your SPID [SQLSTATE 01000] (Message 50000)  Cleaning up old plans for your SPID [SQLSTATE 01000] (Message 50000)  Creating temp tables for internal processing [SQLSTATE 01000] (Message 50000)  Checking for Read intent databases to exclude [SQLSTATE 01000] (Message 50000)  Checking plan cache age [SQLSTATE 01000] (Message 50000)  Checking for single use plans and plans with many queries [SQLSTATE 01000] (Message 50000)  Setting up variables [SQLSTATE 01000] (Message 50000)  Determining SQL Server version. [SQLSTATE 01000] (Message 50000)  Creating dynamic SQL based on SQL Server version. [SQLSTATE 01000] (Message 50000)  Ignoring readable secondaries databases by default [SQLSTATE 01000] (Message 50000)  Ignoring system databases by default [SQLSTATE 01000] (Message 50000)  Setting minutes back filter [SQLSTATE 01000] (Message 50000)  Applying chosen sort order [SQLSTATE 01000] (Message 50000)  Getting spill information for newer versions of SQL [SQLSTATE 01000] (Message 50000)  Adding additional info columns for newer versions of SQL [SQLSTATE 01000] (Message 50000)  Getting memory grant information for newer versions of SQL [SQLSTATE 01000] (Message 50000)  Getting spill information for newer versions of SQL [SQLSTATE 01000] (Message 50000)  Adding SQL to collect trigger stats. [SQLSTATE 01000] (Message 50000)  Collecting execution plan information. [SQLSTATE 01000] (Message 50000)  Skipping analysis, going to results [SQLSTATE 01000] (Message 50000)  Displaying analysis of plan cache. [SQLSTATE 01000] (Message 50000)  Returning ExpertMode = 0 [SQLSTATE 01000] (Message 50000)  Writing results to table. [SQLSTATE 01000] (Message 50000)  Checking @MinutesBack validity. [SQLSTATE 01000] (Message 50000)  Creating temp tables for results and w...  The step failed.

**What is the expected behavior?**
Collect performance metrics for reporting purposes without failing or timing out. 

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All instances are on SQL Server 2019.

Thank you again for taking the time. Apologies for not opening the first one correctly.

**Comment by BrentOzar** [comment]
Thanks, but this still doesn't have the error message.

When you run scripts via an Agent job, the output in Agent gets truncated. When the script has a lot of things going on, like these do, you don't get the final error message that caused the problem.

You may want to try logging the output of the job to a file, ideally a new file for each execution. Then, when the job fails, circle back with the contents of that file.

**Comment by thecleverblonde** [comment]
On it. Will follow up when I have the complete error message.

**Comment by thecleverblonde** [comment]
Logged the error message to table for this pass since each server has different drive configurations and I wasn't sure where it would fail next. The results from the most recent failure. 

Job 'Database Performance Monitor - COLLECT PERFORMANCE METRICS' : Step 1, 'EXEC BlitzFirst' : Began Executing 2023-01-10 11:15:00    Setting up configuration variables [SQLSTATE 01000]  Now starting diagnostic analysis [SQLSTATE 01000]  Checking for Read intent databases to exclude [SQLSTATE 01000]  Determining SQL Server version. [SQLSTATE 01000]  Capturing first pass of wait stats, perfmon counters, file stats [SQLSTATE 01000]  Msg 1222, Sev 16, State 56, Line 1482 : Lock request time out period exceeded. [SQLSTATE 42000]  Msg 3621, Sev 16, State 1, Line 1482 : The statement has been terminated. [SQLSTATE 01000]  Logging sp_BlitzWho to table [SQLSTATE 01000]  Checking for Read intent databases to exclude [SQLSTATE 01000]  Beginning investigatory queries [SQLSTATE 01000]  Finished running investigatory queries [SQLSTATE 01000]  Capturing second pass of wait stats, perfmon counters, file stats [SQLSTATE 01000]  Analyzing changes between first and second passes of DMVs [SQLSTATE 01000]  Analysis finished, outputting results [SQLSTATE 01000]  Calling sp_BlitzCache [SQLSTATE 01000]  Checking @MinutesBack validity. [SQLSTATE 01000]  Setting @MinutesBack to a negative number [SQLSTATE 01000]  Creating temp tables for results and warnings. [SQLSTATE 01000]  Checking database validity [SQLSTATE 01000]  Checking sort order [SQLSTATE 01000]  Skip Analysis set to 1, hiding Summary [SQLSTATE 01000]  Cleaning up old warnings for your SPID [SQLSTATE 01000]  Cleaning up old plans for your SPID [SQLSTATE 01000]  Checking all sort orders, please be patient [SQLSTATE 01000]  Beginning all sort loop [SQLSTATE 01000]  Beginning for ALL [SQLSTATE 01000]  Checking @MinutesBack validity. [SQLSTATE 01000]  Creating temp tables for results and warnings. [SQLSTATE 01000]  Checking database validity [SQLSTATE 01000]  Checking sort order [SQLSTATE 01000]  Skip Analysis set to 1, hiding Summary [SQLSTATE 01000]  Cleaning up old warnings for your SPID [SQLSTATE 01000]  Cleaning up old plans for your SPID [SQLSTATE 01000]  Creating temp tables for internal processing [SQLSTATE 01000]  Checking for Read intent databases to exclude [SQLSTATE 01000]  Checking plan cache age [SQLSTATE 01000]  Checking for single use plans and plans with many queries [SQLSTATE 01000]  Setting up variables [SQLSTATE 01000]  Determining SQL Server version. [SQLSTATE 01000]  Creating dynamic SQL based on SQL Server version. [SQLSTATE 01000]  Ignoring readable secondaries databases by default [SQLSTATE 01000]  Ignoring system databases by default [SQLSTATE 01000]  Setting minutes back filter [SQLSTATE 01000]  Applying chosen sort order [SQLSTATE 01000]  Getting spill information for newer versions of SQL [SQLSTATE 01000]  Adding additional info columns for newer versions of SQL [SQLSTATE 01000]  Getting memory grant information for newer versions of SQL [SQLSTATE 01000]  Getting spill information for newer versions of SQL [SQLSTATE 01000]  Adding SQL to collect trigger stats. [SQLSTATE 01000]  Collecting execution plan information. [SQLSTATE 01000]  Skipping analysis, going to results [SQLSTATE 01000]  Displaying analysis of plan cache. [SQLSTATE 01000]  Returning ExpertMode = 0 [SQLSTATE 01000]  Writing results to table. [SQLSTATE 01000]  Checking @MinutesBack validity. [SQLSTATE 01000]  Creating temp tables for results and warnings. [SQLSTATE 01000]  Checking database validity [SQLSTATE 01000]  Checking sort order [SQLSTATE 01000]  Skip Analysis set to 1, hiding Summary [SQLSTATE 01000]  Cleaning up old warnings for your SPID [SQLSTATE 01000]  Cleaning up old plans for your SPID [SQLSTATE 01000]  Creating temp tables for internal processing [SQLSTATE 01000]  Checking for Read intent databases to exclude [SQLSTATE 01000]  Checking plan cache age [SQLSTATE 01000]  Checking for single use plans and plans with many queries [SQLSTATE 01000]  Processing SQL Handles To Ignore [SQLSTATE 01000]  Setting up variables [SQLSTATE 01000]  Determining SQL Server version. [SQLSTATE 01000]  Creating dynamic SQL based on SQL Server version. [SQLSTATE 01000]  Ignoring readable secondaries databases by default [SQLSTATE 01000]  Ignoring system databases by default [SQLSTATE 01000]  Including only chosen SQL Handles [SQLSTATE 01000]  Setting minutes back filter [SQLSTATE 01000]  Applying chosen sort order [SQLSTATE 01000]  Getting spill information for newer versions of SQL [SQLSTATE 01000]  Adding additional info columns for newer versions of SQL [SQLSTATE 01000]  Getting memory grant information for newer versions of SQL [SQLSTATE 01000]  Getting spill information for newer versions of SQL [SQLSTATE 01000]  Adding SQL to collect trigger stats. [SQLSTATE 01000]  Collecting execution plan information. [SQLSTATE 01000]  Skipping analysis, going to results [SQLSTATE 01000]  Displaying analysis of plan cache. [SQLSTATE 01000]  Returning ExpertMode = 0 [SQLSTATE 01000]  Writing results to table. [SQLSTATE 01000]  Checking @MinutesBack validity. [SQLSTATE 01000]  Creating temp tables for results and warnings. [SQLSTATE 01000]  Checking database validity [SQLSTATE 01000]  Checking sort order [SQLSTATE 01000]  Skip Analysis set to 1, hiding Summary [SQLSTATE 01000]  Cleaning up old warnings for your SPID [SQLSTATE 01000]  Cleaning up old plans for your SPID [SQLSTATE 01000]  Creating temp tables for internal processing [SQLSTATE 01000]  Checking for Read intent databases to exclude [SQLSTATE 01000]  Checking plan cache age [SQLSTATE 01000]  Checking for single use plans and plans with many queries [SQLSTATE 01000]  Processing SQL Handles To Ignore [SQLSTATE 01000]  Setting up variables [SQLSTATE 01000]  Determining SQL Server version. [SQLSTATE 01000]  Creating dynamic SQL based on SQL Server version. [SQLSTATE 01000]  Ignoring readable secondaries databases by default [SQLSTATE 01000]  Ignoring system databases by default [SQLSTATE 01000]  Including only chosen SQL Handles [SQLSTATE 01000]  Setting minutes back filter [SQLSTATE 01000]  Applying chosen sort order [SQLSTATE 01000]  Getting spill information for newer versions of SQL [SQLSTATE 01000]  Adding additional info columns for newer versions of SQL [SQLSTATE 01000]  Getting memory grant information for newer versions of SQL [SQLSTATE 01000]  Getting spill information for newer versions of SQL [SQLSTATE 01000]  Adding SQL to collect trigger stats. [SQLSTATE 01000]  Collecting execution plan information. [SQLSTATE 01000]  Skipping analysis, going to results [SQLSTATE 01000]  Displaying analysis of plan cache. [SQLSTATE 01000]  Returning ExpertMode = 0 [SQLSTATE 01000]  Writing results to table. [SQLSTATE 01000]  Checking @MinutesBack validity. [SQLSTATE 01000]  Creating temp tables for results and warnings. [SQLSTATE 01000]  Checking database validity [SQLSTATE 01000]  Checking sort order [SQLSTATE 01000]  Skip Analysis set to 1, hiding Summary [SQLSTATE 01000]  Cleaning up old warnings for your SPID [SQLSTATE 01000]  Cleaning up old plans for your SPID [SQLSTATE 01000]  Creating temp tables for internal processing [SQLSTATE 01000]  Checking for Read intent databases to exclude [SQLSTATE 01000]  Checking plan cache age [SQLSTATE 01000]  Checking for single use plans and plans with many queries [SQLSTATE 01000]  Processing SQL Handles To Ignore [SQLSTATE 01000]  Setting up variables [SQLSTATE 01000]  Determining SQL Server version. [SQLSTATE 01000]  Creating dynamic SQL based on SQL Server version. [SQLSTATE 01000]  Ignoring readable secondaries databases by default [SQLSTATE 01000]  Ignoring system databases by default [SQLSTATE 01000]  Including only chosen SQL Handles [SQLSTATE 01000]  Setting minutes back filter [SQLSTATE 01000]  Applying chosen sort order [SQLSTATE 01000]  Getting spill information for newer versions of SQL [SQLSTATE 01000]  Adding additional info columns for newer versions of SQL [SQLSTATE 01000]  Getting memory grant information for newer versions of SQL [SQLSTATE 01000]  Getting spill information for newer versions of SQL [SQLSTATE 01000]  Adding SQL to collect trigger stats. [SQLSTATE 01000]  Collecting execution plan information. [SQLSTATE 01000]  Skipping analysis, going to results [SQLSTATE 01000]  Displaying analysis of plan cache. [SQLSTATE 01000]  Returning ExpertMode = 0 [SQLSTATE 01000]  Writing results to table. [SQLSTATE 01000]  Checking @MinutesBack validity. [SQLSTATE 01000]  Creating temp tables for results and warnings. [SQLSTATE 01000]  Checking database validity [SQLSTATE 01000]  Checking sort order [SQLSTATE 01000]  Skip Analysis set to 1, hiding Summary [SQLSTATE 01000]  Cleaning up old warnings for your SPID [SQLSTATE 01000]  Cleaning up old plans for your SPID [SQLSTATE 01000]  Creating temp tables for internal processing [SQLSTATE 01000]  Checking for Read intent databases to exclude [SQLSTATE 01000]  Checking plan cache age [SQLSTATE 01000]  Checking for single use plans and plans with many queries [SQLSTATE 01000]  Processing SQL Handles To Ignore [SQLSTATE 01000]  Setting up variables [SQLSTATE 01000]  Determining SQL Server version. [SQLSTATE 01000]  Creating dynamic SQL based on SQL Server version. [SQLSTATE 01000]  Ignoring readable secondaries databases by default [SQLSTATE 01000]  Ignoring system databases by default [SQLSTATE 01000]  Including only chosen SQL Handles [SQLSTATE 01000]  Setting minutes back filter [SQLSTATE 01000]  Applying chosen sort order [SQLSTATE 01000]  Getting spill information for newer versions of SQL [SQLSTATE 01000]  Adding additional info columns for newer versions of SQL [SQLSTATE 01000]  Getting memory grant information for newer versions of SQL [SQLSTATE 01000]  Getting spill information for newer versions of SQL [SQLSTATE 01000]  Adding SQL to collect trigger stats. [SQLSTATE 01000]  Collecting execution plan information. [SQLSTATE 01000]  Skipping analysis, going to results [SQLSTATE 01000]  Displaying analysis of plan cache. [SQLSTATE 01000]  Returning ExpertMode = 0 [SQLSTATE 01000]  Writing results to table. [SQLSTATE 01000]  Checking @MinutesBack validity. [SQLSTATE 01000]  Creating temp tables for results and warnings. [SQLSTATE 01000]  Checking database validity [SQLSTATE 01000]  Checking sort order [SQLSTATE 01000]  Skip Analysis set to 1, hiding Summary [SQLSTATE 01000]  Cleaning up old warnings for your SPID [SQLSTATE 01000]  Cleaning up old plans for your SPID [SQLSTATE 01000]  Creating temp tables for internal processing [SQLSTATE 01000]  Checking for Read intent databases to exclude [SQLSTATE 01000]  Checking plan cache age [SQLSTATE 01000]  Checking for single use plans and plans with many queries [SQLSTATE 01000]  Processing SQL Handles To Ignore [SQLSTATE 01000]  Setting up variables [SQLSTATE 01000]  Determining SQL Server version. [SQLSTATE 01000]  Creating dynamic SQL based on SQL Server version. [SQLSTATE 01000]  Ignoring readable secondaries databases by default [SQLSTATE 01000]  Ignoring system databases by default [SQLSTATE 01000]  Including only chosen SQL Handles [SQLSTATE 01000]  Setting minutes back filter [SQLSTATE 01000]  Applying chosen sort order [SQLSTATE 01000]  Getting spill information for newer versions of SQL [SQLSTATE 01000]  Adding additional info columns for newer versions of SQL [SQLSTATE 01000]  Getting memory grant information for newer versions of SQL [SQLSTATE 01000]  Getting spill information for newer versions of SQL [SQLSTATE 01000]  Collecting execution plan information. [SQLSTATE 01000]  Skipping analysis, going to results [SQLSTATE 01000]  Displaying analysis of plan cache. [SQLSTATE 01000]  Returning ExpertMode = 0 [SQLSTATE 01000]  Writing results to table. [SQLSTATE 01000]  Checking @MinutesBack validity. [SQLSTATE 01000]  Creating temp tables for results and warnings. [SQLSTATE 01000]  Checking database validity [SQLSTATE 01000]  Checking sort order [SQLSTATE 01000]  Skip Analysis set to 1, hiding Summary [SQLSTATE 01000]  Cleaning up old warnings for your SPID [SQLSTATE 01000]  Cleaning up old plans for your SPID [SQLSTATE 01000]  Creating temp tables for internal processing [SQLSTATE 01000]  Checking for Read intent databases to exclude [SQLSTATE 01000]  Checking plan cache age [SQLSTATE 01000]  Checking for single use plans and plans with many queries [SQLSTATE 01000]  Processing SQL Handles To Ignore [SQLSTATE 01000]  Setting up variables [SQLSTATE 01000]  Determining SQL Server version. [SQLSTATE 01000]  Creating dynamic SQL based on SQL Server version. [SQLSTATE 01000]  Ignoring readable secondaries databases by default [SQLSTATE 01000]  Ignoring system databases by default [SQLSTATE 01000]  Including only chosen SQL Handles [SQLSTATE 01000]  Setting minutes back filter [SQLSTATE 01000]  Applying chosen sort order [SQLSTATE 01000]  Getting spill information for newer versions of SQL [SQLSTATE 01000]  Adding additional info columns for newer versions of SQL [SQLSTATE 01000]  Getting memory grant information for newer versions of SQL [SQLSTATE 01000]  Getting spill information for newer versions of SQL [SQLSTATE 01000]  Adding SQL to collect trigger stats. [SQLSTATE 01000]  Collecting execution plan information. [SQLSTATE 01000]  Skipping analysis, going to results [SQLSTATE 01000]  Displaying analysis of plan cache. [SQLSTATE 01000]  Returning ExpertMode = 0 [SQLSTATE 01000]  Writing results to table. [SQLSTATE 01000]  DatabaseName                                                                                                                     Cost                                                  QueryText

**Comment by BrentOzar** [comment]
OK, great. The error is:

(Message 50000) Lock request time out period exceeded. [SQLSTATE 42000] (Error 1222) The statement has been terminated. 

That's a normal error - that's when someone else is blocking our code, and we abort rather than blocking other users. That's completely fine. It's up to you whether you want to troubleshoot more deeply in your environment to find out who's making system changes, index changes, etc that may be blocking monitoring scripts, but this wouldn't be something I'm going to be able to do for free here. Hope that's fair.

**Comment by thecleverblonde** [comment]
Oh yeah - for sure fair. Is there a way to suppress the failure/error until I can find the culprit?

**Comment by BrentOzar** [comment]
You can configure Agent job steps to proceed regardless of success or failure.

**Comment by thecleverblonde** [comment]
Thank you, again. Hope you have a great rest of your day :)
