### ISSUE TITLE
sp_BlitzFirst false positive CPU alert on Linux

### ISSUE THREAD

**Issue by alex-jitbit** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3219]
**Version of the script**
8.12 

**What is the current behavior?**

Running `sp_BLitzFirst' (no parameters) shows two alerts "CPU 100%" and "98% - Other Processes (not SQL Server)"

**What is the expected behavior?**

On an 8-core Ubuntu machine the actual load is 0.3% (looking at `htop` during a non-busy Sunday)

**Comment by BrentOzar** [comment]
Howdy, and thanks for the issue! Whenever you've got questions about the output from the scripts, the easiest way to get started troubleshooting it is to search for that string in the code. For example, search for "Other processes (not SQL Server)" and you find this query:

```
		INSERT INTO #BlitzFirstResults (CheckID, Priority, FindingsGroup, Finding, Details, DetailsInt, URL)
	    SELECT 28,	50,	'Server Performance', 'High CPU Utilization - Not SQL', CONVERT(NVARCHAR(100),100 - (y.SQLUsage + y.SystemIdle)) + N'% - Other Processes (not SQL Server) are using this much CPU. This may impact on the performance of your SQL Server instance', 100 - (y.SQLUsage + y.SystemIdle), 'https://www.brentozar.com/go/cpu'
            FROM (
                SELECT record,
                    record.value('(./Record/SchedulerMonitorEvent/SystemHealth/SystemIdle)[1]', 'int') AS SystemIdle
					,record.value('(./Record/SchedulerMonitorEvent/SystemHealth/ProcessUtilization)[1]', 'int') AS SQLUsage
                FROM (
                    SELECT TOP 1 CONVERT(XML, record) AS record
                    FROM sys.dm_os_ring_buffers
                    WHERE ring_buffer_type = N'RING_BUFFER_SCHEDULER_MONITOR'
                    AND record LIKE '%<SystemHealth>%'
                    ORDER BY timestamp DESC) AS rb
            ) AS y
            WHERE 100 - (y.SQLUsage + y.SystemIdle) >= 25;
```

So, let's try running that part of the query separately, without the insert statement:

```
                SELECT record,
                    record.value('(./Record/SchedulerMonitorEvent/SystemHealth/SystemIdle)[1]', 'int') AS SystemIdle
					,record.value('(./Record/SchedulerMonitorEvent/SystemHealth/ProcessUtilization)[1]', 'int') AS SQLUsage
                FROM (
                    SELECT TOP 1 CONVERT(XML, record) AS record
                    FROM sys.dm_os_ring_buffers
                    WHERE ring_buffer_type = N'RING_BUFFER_SCHEDULER_MONITOR'
                    AND record LIKE '%<SystemHealth>%'
                    ORDER BY timestamp DESC) AS rb
            ) AS y
            WHERE 100 - (y.SQLUsage + y.SystemIdle) >= 25;
```

And then that way you'll be able to find out whether your SQL Server might be reporting its CPU usage incorrectly. That'll help you track down whether it's a bug in sp_BlitzFirst, or in SQL Server itself.

Let me know what you find. Thanks!

**Comment by alex-jitbit** [comment]
Looks like `SystemIdle` is always `0` on linux. So it looks like an upstream issue.

**Comment by alex-jitbit** [comment]
@BrentOzar Further googling shows that this has been fixed in SQL Server 2019, and this is a known issue with `dm_os_ring_buffers` on SQL Server 2017 on linux. So I suggest we leave this as it is.

THanks for the fast response and for everything you're doing for the community.
