### ISSUE TITLE
sp_BlitzIndex (maybe others) - Case Sensitivity issue when specifying OutputTable* params

### ISSUE THREAD

**Issue by jeffchulg** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3222]
**Version of the script**
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.

_SELECT @Version = '8.12', @VersionDate = '20221213';_

**What is the current behavior?**

`EXEC FirstResponderKit.sp_BlitzIndex @OutputDatabaseName = 'DBATools',@OutputSchemaName = 'dbo',@OutputTableName= 'testTbl2023'`

> Starting run. sp_BlitzIndex(TM) v8.12 - December 13, 2022

> One or more output parameters specified in combination with TABLE output, changing to NONE output mode
> Create temp tables.
> Adding UQ index on #IndexSanity (database_id, object_id, index_id)
> Number of databases to examine: 1
> Checking partition counts to exclude databases with over 100 partitions
> Starting loop through databases
> 
> 
> DbaTools
> Inserting data into #IndexColumns for clustered indexes and heaps
> Inserting data into #IndexColumns for nonclustered indexes
> Inserting data into #IndexSanity
> Checking partition count
> Preferring non-2012 syntax with LEFT JOIN to sys.dm_db_index_operational_stats
> Inserting data into #IndexPartitionSanity
> Warning: Null value is eliminated by an aggregate or other SET operation.
> Inserting data into #MissingIndexes
> Inserting data into #ForeignKeys
> Inserting data into #ForeignKeys
> Gathering Computed Column Info.
> Gathering Trace Flag Information
> Gathering Temporal Table Info
> Updating #IndexSanity.key_column_names
> Updating #IndexSanity.partition_key_column_name
> Updating #IndexSanity.key_column_names_with_sort_order
> Updating #IndexSanity.key_column_names_with_sort_order_no_types (for create tsql)
> Updating #IndexSanity.include_column_names
> Updating #IndexSanity.include_column_names_no_types (for create tsql)
> Updating #IndexSanity.count_key_columns and count_include_columns
> Updating index_sanity_id on #IndexPartitionSanity
> Inserting data into #IndexSanitySize
> Warning: Null value is eliminated by an aggregate or other SET operation.
> Determining index usefulness
> Updating #IndexSanity.referenced_by_foreign_key
> Update index_secret on #IndexSanity for NC indexes.
> Update index_secret on #IndexSanity for heaps and non-unique clustered.
> Populate #IndexCreateTsql.
> Populate #PartitionCompressionInfo.
> Update #PartitionCompressionInfo.
> Update #IndexSanity for filtered indexes with columns not in the index definition.
> Failure analyzing temp tables.
> Msg 50000, Level 11, State 2, Procedure FirstResponderKit.sp_BlitzIndex, Line 6167 [Batch Start Line 0]
> **Could not find server 'myserver' in sys.server**s. Verify that the correct server name was specified. If necessary, execute the stored procedure sp_addlinkedserver to add the server to sys.servers.
> 

The collation is Case Sensitive and the server is stored in sys.servers as MYSERVER.

**If the current behavior is a bug, please provide the steps to reproduce.**

See above.

**What is the expected behavior?**

No error

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

SQL Server 2019

**Comment by BrentOzar** [comment]
Yep, that's a bummer alright - if you're using case sensitivity, then the case of what you pass in needs to match the case of how it's stored in the database.

That's not really an sp_Blitz issue - that's just how case sensitivity works. Sorry about that!

If you'd like to contribute a code change to get it to work differently, and test it on your end, you're welcome to do that, and I'll reopen the issue at that point.
