### ISSUE TITLE
sp_BlitzLock issue in Visual Studio 2022 Data Tools project

### ISSUE THREAD

**Issue by sm8680** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3224]
This is purely a Visual Studio Data Tools project issue.  I'm getting an incorrect syntax error near 9223372036854775807

To get the code to work in Visual Studio I had to comment 9223372036854775807 and replaced it with 2147483647.  In a previous sp_BlitzLock ROWCOUNT & PAGECOUNT were 100000000 which works as well.  Please let me know your thoughts on this.

            UPDATE STATISTICS
                #t
            WITH
                ROWCOUNT  = 2147483647, 
                PAGECOUNT = 2147483647;
--                ROWCOUNT  = 9223372036854775807, 
--                PAGECOUNT = 9223372036854775807;

**Comment by sm8680** [comment]
I raised the issue as suggested thanks

**Comment by sm8680** [comment]
Received the following notification from Microsoft today "Hello Steven, Thanks for the feedback ticket. We have currently updated the support of RowCount and PageCount to be similar to Azure Data Studio and SSMS. It will soon be made available to the users in upcoming preview release and I will update you when it’s done."

**Comment by sm8680** [comment]
I can confirm that Microsoft fixed the issue at hand in Version 17.6

**Comment by vytux-com** [comment]
Exporting to a bacpac file in Azure SQL with this SP also produces this error
![image](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/5370583/5c818ac9-e72f-4171-b6f4-3a959f6627f7)
