### ISSUE TITLE
Blitz first output to table doesn't work fully (Who and Cache) when installed in different schema

### ISSUE THREAD

**Issue by pmaguirepers** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3225]
**Version of the script**
@Version = '8.12', @VersionDate = '20221213'

Install all blitz scripts to a new schema (e.g. DBA).
Execute sp_blitzfirst to output "file,perfmon,wait,cache and who" to tables.  Specify schema @OutputSchemaName='dba'.
EXEC      dba.sp_BlitzFirst
                @OutputDatabaseName='XYZ',
                @OutputSchemaName='dba',
                @OutputTableName='BlitzFirst',
                @OutputTableNameFileStats='BlitzFirst_FileStats',
                @OutputTableNamePerfmonStats='BlitzFirst_PerfmonStats',
                @OutputTableNameWaitStats='BlitzFirst_WaitStats',
                @OutputTableNameBlitzCache='BlitzFirst_BlitzCache',
                @OutputTableNameBlitzWho='BlitzFirst_BlitzWho'

Errors:
Logging sp_BlitzWho to table
Msg 2812, Level 16, State 62, Procedure dba.sp_BlitzFirst, Line 1496 [Batch Start Line 0]
Could not find stored procedure 'sp_BlitzWho'.

Msg 2812, Level 16, State 62, Procedure dba.sp_BlitzFirst, Line 3625 [Batch Start Line 0]
Could not find stored procedure 'sp_BlitzCache'.
Msg 208, Level 16, State 1, Line 1
Invalid object name 'agemdmeprod101.dba.BlitzFirst_BlitzCache'.

Reviewed sp_blitzfirst and there are multiple correct references to dba.sp_BlitzWho which work when run not outputting to table.
But there couple calls where the custom schema is not used.
Line 1501 calls "EXEC sp_BlitzWho @OutputDatabaseName = @UnquotedOutputDatabaseName..."
Line 3615 calls "EXEC sp_BlitzCache"
Line 3630 calls "EXEC sp_BlitzCache"

**What is the expected behavior?**
They should call "EXEC dba.sp_BlitzWho" and "EXEC dba.sp_BlitzCache"

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2022 on Azure SQL DB

**Comment by BrentOzar** [comment]
The @OutputSchema parameter is for the schema of the output table. It's not for the schema of the stored procedure.

sp_Blitz and friends are designed to be installed in the dbo schema. If you'd like them to work in another schema automatically, you're welcome to submit a pull request to change that, but it's not the way they work today.

I'm going to close this issue, but if you want to work on the code changes, check out the contributing guide on the home page of the repo.

Thanks!

**Comment by pmaguirepers** [comment]
Thanks…  I’ve fixed in my local deployment for now.  Unfortunately, the client doesn’t want anything in DBIO.  Wants everything in named schemas.
I’ll review the contributing guide…

Regards,
Paul

Mobile (+44) 0770 332 3364
Email ***@***.******@***.***>

[Title: LinkedIn - Description: image of LinkedIn icon]<http://linkedin.com/>
