### ISSUE TITLE
@ThresholdMB parameter is not working

### ISSUE THREAD

**Issue by PaaReeS** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3226]
**Version of the script**
@Version = '8.12' @VersionDate = '20221213'

**What is the current behavior?**
When i use the @Threshold filter while using @Mode=0 shows objects with less than the threshold used.

**If the current behavior is a bug, please provide the steps to reproduce.**
sp_BlitzIndex @DatabaseName='DBName',@Mode=0,@ThresholdMB=1204
Show objects with less than 1024MB 

**What is the expected behavior?**
Filtering the objects below the threshold

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2019

**Comment by BrentOzar** [comment]
That parameter only pertains to some checks, not all. Which specific check is giving you problems, can you send a screenshot? If it's a tight, limited list, I can go through the code and add it, but if it's "all the checks", then that would be something you would need to submit a pull request for.

**Comment by PaaReeS** [comment]
I have only tried it on sp_BlitzIndex, with @Mode=0 and @Mode=2
![image](https://user-images.githubusercontent.com/124661360/219344208-78a309ab-7a37-456c-8572-82b4106b068d.png)
![image](https://user-images.githubusercontent.com/124661360/219344350-9e0ee7bd-45eb-4acb-99e6-8a9e4ff89d5d.png)

**Comment by BrentOzar** [comment]
I need you to reread what I said, and pay careful attention to it:

*That parameter only pertains to some checks, not all. Which specific check is giving you problems, can you send a screenshot? If it's a tight, limited list, I can go through the code and add it, but if it's "all the checks", then that would be something you would need to submit a pull request for.*

**Comment by erikdarlingdata** [comment]
When using `@Mode = 0`, that filter is specifically skipped in all checks. Just for example:

<img width="749" alt="image" src="https://user-images.githubusercontent.com/2136037/223798478-049eb59a-0a78-40bd-942a-32fe74e5c487.png">

But you'll see something like that across all of them. If you want that filter to be honored, use `@Mode = 4`, which is sort of like expert mode for `sp_BlitzIndex`. 

It does everything that Mode 0 does, but with additional information returned.
