### ISSUE TITLE
sp_BlitzLock - Performance improvement when using system_health event session

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3232]
**Is your feature request related to a problem? Please describe.**
In the [sys.fn_xe_file_target_read_file](https://learn.microsoft.com/en-us/sql/relational-databases/system-functions/sys-fn-xe-file-target-read-file-transact-sql?view=sql-server-ver16) function lives a column called `object_name` that can be used to filter to just the rows returned for the deadlock xml. Using this is usually much faster.

**Describe the solution you'd like**
I would like to add one weird line of code to make this thing go a lot faster. 

**Describe alternatives you've considered**
Being happy.

**Are you ready to build the code for the feature?**
It is done.

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, merging into the dev branch, will be credited to "Red Wine at 5AM" in the release notes.

**Comment by erikdarlingdata** [comment]
One additional note for future reference: There is also a `timestamp_utc` column available in SQL Server 2017+, but it is [rather buggy](https://dba.stackexchange.com/q/323147/32281). I am skipping going down the dynamic SQL route here for now.
