### ISSUE TITLE
sp_DatabaseRestore - support @FileExtensionDiff parameter

### ISSUE THREAD

**Issue by spurdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3234]
**Is your feature request related to a problem? Please describe.**
sp_DatabaseRestore will only restore DIFF backups if they use the *.bak extension. If you use the @FileExtensionDiff = 'dif' or something similar during Ola's backups, the diffs are ignored during restore.

**Describe the solution you'd like**
I would like sp_DatabaseRestore to support the same @FileExtensionDiff parameter that DatabaseBackup does, so that I do not have to tweak each new version of sp_DatabaseRestore :)

**Describe alternatives you've considered**
You could also modify the filter "WHERE BackupFile LIKE N'%.bak'" to just include ".dif" if we think that is the most common alternative to ".bak", but this seems like a poor solution.

**Are you ready to build the code for the feature?**
Yes I have a modified version of 8.13 working.

**Comment by BrentOzar** [comment]
Sure, we'd welcome a pull request for that!

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, works on my machine. Merging into the dev branch, will be in the next release with credit to you in the release notes.
