### ISSUE TITLE
sp_databaserestore - filename modification is not working if original database was renamed

### ISSUE THREAD

**Issue by wfvdijk** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3236]
**current version 8.13**

**What is the current behavior?**
If I restore a database to a new name, but the database self was renamed in the past, the processing of renaming files (parameter @MoveFiles) is not doing anything resulting in the original filenames.
This is because the script is assuming the databasefiles contain the databasename

**steps to reproduce.**
1. create database with name aaa_bbb_ccc
2. rename database to aaa_ccc_bbb
3. verify filenames; these are still "aaa_bbb_ccc.mdf" etc
4. create a backup from database aaa_ccc_bbb
5. restore this database with sp_restore with @restoredatabasename = 'bugtest' and @movefiles = 1 and @debug =1
6. notice the lack of restoring files with different names in output
7. when restoring on the original database instance, you'll get an error

**What is the expected behavior?**
correct renaming, or add logica to do a hardcoded search/replace in case this situation happens

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
tested on SQL2019 CU18 on windows, but this will also happen on previous SQL server versions

**Comment by wfvdijk** [comment]
I know there are some tricks to rename datafiles ( [https://www.mssqltips.com/sqlservertip/4419/renaming-physical-database-file-names-for-a-sql-server-database/](url) ) but this requires the database to go offline which in our case is not possible. And it's in AlwaysOn also.

**Comment by BrentOzar** [comment]
Howdy. We didn't originally code sp_DatabaseRestore for that use case, so if you want it to work in that scenario, that would be something you would need to code. We'd definitely welcome a pull request for it.

If you'd like to code it, here's our contributing guide:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/main/CONTRIBUTING.md

Is that something you'd like to code, or should I close the issue?

**Comment by wfvdijk** [comment]
I like to code this

regards,
Wilfred

**Comment by BrentOzar** [comment]
OK, great! I've assigned you to the issue. If you run into any questions around Github logistics, holler.

**Comment by wfvdijk** [comment]
got sick for quite some time, will post a pull request when I have time

Wilfred
