### ISSUE TITLE
Specify SQL schema where to create objects

### ISSUE THREAD

**Issue by 32u-nd** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3242]
Hi Brent,
thanks a lot for this wonderful script suite. I would love to see a central parameter near the script header to specify the SQL schema where to create those objects in. I use a central helper database and this would greatly simplify my work to distinguish between your wonderful scripts and other helper stuff in this database. I hope you consider this in one of your next updates. Thanks.

**Comment by BrentOzar** [comment]
You’re welcome. Okay, is this something you’re planning to code and contribute as a pull request?---Tiny glass keyboardTypos flowing like riversAs winter snow thawsOn Mar 9, 2023, at 8:07 AM, 32u-nd ***@***.***> wrote:﻿
Hi Brent,
thanks a lot for this wonderful script suite. I would love to see a central parameter near the script header to specify the SQL schema where to create those objects in. I use a central helper database and this would greatly simplify my work to distinguish between your wonderful scripts and other helper stuff in this database. I hope you consider this in one of your next updates. Thanks.

**Comment by 32u-nd** [comment]
Yeah, I can try; this will be my first pull request :).

**Comment by BrentOzar** [comment]
OK, cool! This might be a little tricky for a first pull request, but here's some background.

Don't modify any of the Install-% scripts directly, like Install-All-Scripts.sql. Those installation scripts are generated during the release process. To see what generates them, go into the Documentation/Development folder, and there's a "Merge Blitz.ps1" PowerShell script. It concatenates the various sp_Blitz% scripts, merging them into each installation script like Install-Core-Blitz-With-Query-Store.sql. Your solution might involve that PowerShell file.

You can modify the sp_Blitz% scripts, but for reverse compatibility, they need to default to the dbo schema, and no human intervention can be required when installing them. If the user just grabs any of the sp_Blitz% scripts, or the Install% scripts, they have to work by default in dbo.

**Comment by BrentOzar** [comment]
It's been a couple of weeks - when you're ready to start work on it, feel free to leave a comment here and I can reopen the issue, otherwise I'll go ahead and close it for now.
