### ISSUE TITLE
Exclude Erik Darling's sp_PressureDetector from  the "...has WITH RECOMPILE in the stored procedure code..."check. 

### ISSUE THREAD

**Issue by waltheed** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3244]
It would be great if Erik Darling's sp_PressureDetector  is excluded from the "...has WITH RECOMPILE in the stored procedure code..."check in sp_Blitz.

**Comment by BrentOzar** [comment]
Sure, that's a pull request we'd welcome. Here's how to contribute the code: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md

**Comment by BrentOzar** [comment]
Fixed by #3245. Thanks for the pull request! Looks good, merging into the dev branch, will be in the next release with credit to you in the release notes.
