### ISSUE TITLE
sp_Blitz: Reduce the time time span for old memory dump reports findings 

### ISSUE THREAD

**Issue by indexitall** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3248]
**Is your feature request related to a problem? Please describe.**
I always get scared that my server is dumping memory because it shows up on the priority list but it is from 2-3 years ago.

**Describe the solution you'd like**
I would like the reported event time reduced to like say weekly and it resets 

**Describe alternatives you've considered**
I have simply just been manually removing it from the health report scores for Sp_Blitz for the report I present daily. 

**Are you ready to build the code for the feature?**
I am not good enough Yet to build the code for this feature.

**Comment by BrentOzar** [comment]
Hmm, I just went through sp_Blitz where we're querying sys.dm_server_memory_dumps, and it's got a filter to only pull dumps from the last year:

```
 FROM
								[sys].[dm_server_memory_dumps]
							  WHERE [creation_time] >= DATEADD(year, -1, GETDATE());

```

And it's been that way for 3 years. Can you double-check that your sp_Blitz has actually been updated in the last 3 years, and if so, run this:

```
SELECT *
FROM [sys].[dm_server_memory_dumps]
WHERE [creation_time] >= DATEADD(year, -1, GETDATE())
ORDER BY creation_time;
```

**Comment by BrentOzar** [comment]
OK, great! Love those kinds of fixes.
