### ISSUE TITLE
sp_blitzlock error

### ISSUE THREAD

**Issue by llsnowinaz** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3272]
Msg 8114, Level 16, State 5, Procedure sp_BlitzLock, Line 1762 [Batch Start Line 2]
Error converting data type nvarchar to bigint.
Procedure will not run

**Comment by BrentOzar** [comment]
Howdy. You deleted all of the questions in the issue - you'll need to actually fill those out, including which version you're running. This is important because we've fixed similar issues in recent builds. Thanks!

**Comment by BrentOzar** [comment]
Further messages here won't be constructive. Please create a new issue and answer the questions this time instead of deleting them. Thanks!
