### ISSUE TITLE
SqlServerVersions.sql - links for SQL Server 2022 does not use KBID

### ISSUE THREAD

**Issue by jeffchulg** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3275]
**Version of the script**
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.
Latest version

**What is the current behavior?**

```
(16, 4025, 'CU3', 'https://learn.microsoft.com/en-us/troubleshoot/sql/releases/sqlserver-2022/cumulativeupdate3', '2023-04-13', '2028-01-11', '2033-01-11', 'SQL Server 2022', 'Cumulative Update 3'),
    (16, 4015, 'CU2', 'https://learn.microsoft.com/en-us/troubleshoot/sql/releases/sqlserver-2022/cumulativeupdate2', '2023-03-15', '2028-01-11', '2033-01-11', 'SQL Server 2022', 'Cumulative Update 2'),
    (16, 4003, 'CU1', 'https://learn.microsoft.com/en-us/troubleshoot/sql/releases/sqlserver-2022/cumulativeupdate1', '2023-02-16', '2028-01-11', '2033-01-11', 'SQL Server 2022', 'Cumulative Update 1'),
```

We use the KBId as an identifier... This is a breaking change for us.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

```
(16, 4025, 'CU3', 'https://support.microsoft.com/en-us/help/5024396', '2023-04-13', '2028-01-11', '2033-01-11', 'SQL Server 2022', 'Cumulative Update 3'),
    (16, 4015, 'CU2', 'https://support.microsoft.com/en-us/help/5023127', '2023-03-15', '2028-01-11', '2033-01-11', 'SQL Server 2022', 'Cumulative Update 2'),
    (16, 4003, 'CU1', 'https://support.microsoft.com/en-us/help/5022375', '2023-02-16', '2028-01-11', '2033-01-11', 'SQL Server 2022', 'Cumulative Update 1'),
```

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

**Comment by BrentOzar** [comment]
Sorry about that! Can you describe a little about why this is a breaking change for you? I've changed it manually in this current version, but I can't guarantee it's always going to stay that way - other people contribute code on that file, and I know I won't remember to check the specific URL. I just go to it to make sure it works. :-D

**Comment by jeffchulg** [comment]
Hi Brent,
we made a tool that compares centrally all versions of our systems against the latest ones. We made the decision to use your table and needed a key... the KBID, which is not directly in the table but is in the URL... So we extract it.

**Comment by jeffchulg** [comment]
OK for me.
