### ISSUE TITLE
sp_BlitzLock: Bad column size when adding client_option_1 and client_option_2 to already existing table

### ISSUE THREAD

**Issue by JonasEckerman** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3277]
**Version of the script**

- @Version = '8.14'
- @VersionDate = '20230420'

**What is the current behavior?**

When the output table alrweady exists but doens't have the column client_option_1 or client_option_2, the scripts crashes because it tries to add them as `nvarchar(8000)`.

Error message for client_option_1: `The size (8000) given to the parameter 'client_option_1' exceeds the maximum allowed (4000).`.

**If the current behavior is a bug, please provide the steps to reproduce.**

```SQL
USE Test_Temp;  -- Replace this with a suitable database name
GO

EXEC dbo.sp_BlitzLock
@OutputDatabaseName = 'Test_Temp', -- Replace this with a suitable database name
@OutputSchemaName = 'dbo',
@OutputTableName = 'BlitzLock_Output';
GO

ALTER TABLE BlitzLock_Output DROP COLUMN client_option_1;
ALTER TABLE BlitzLock_Output DROP COLUMN client_option_2;
GO

EXEC dbo.sp_BlitzLock
@OutputDatabaseName = 'Test_Temp', -- Replace this with a suitable database name
@OutputSchemaName = 'dbo',
@OutputTableName = 'BlitzLock_Output';
```

**What is the expected behavior?**

That sp_BlitzLock doesn't crash.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

- SQL Server 2019 on Windows
- I don't know if this bug hjas been tghere since those columsn were added or not.

**Cause of the error**

When creating a new table, this definituion is used for client_option_1 and client_option_2:

```SQL
client_option_1 varchar(2000),
client_option_2 varchar(2000),
```

When adding the existing columns, the beklow code is used. That code tries to add them as nvarchar(8000) which is not allowed.

```SQL
SET @StringToExecute =
		N'IF NOT EXISTS (SELECT 1/0 FROM ' +
		@OutputDatabaseName +
		N'.sys.all_columns AS o WHERE o.object_id = (OBJECT_ID(''' +
		@ObjectFullName +
		N''')) AND o.name = N''client_option_1'')
		/*Add wait_resource column*/
		ALTER TABLE ' +
		@ObjectFullName +
		N' ADD client_option_1 nvarchar(8000) NULL;';

IF @Debug = 1 BEGIN PRINT @StringToExecute; END;
EXEC sys.sp_executesql
	@StringToExecute;

/* If the table doesn't have the new client option column, add it. See Github #3101. */
SET @StringToExecute =
		N'IF NOT EXISTS (SELECT 1/0 FROM ' +
		@OutputDatabaseName +
		N'.sys.all_columns AS o WHERE o.object_id = (OBJECT_ID(''' +
		@ObjectFullName +
		N''')) AND o.name = N''client_option_2'')
		/*Add wait_resource column*/
		ALTER TABLE ' +
		@ObjectFullName +
		N' ADD client_option_2 nvarchar(8000) NULL;';

IF @Debug = 1 BEGIN PRINT @StringToExecute; END;
EXEC sys.sp_executesql
	@StringToExecute;
```

**Comment by JonasEckerman** [comment]
Just noticed a potential for a future bug related to this.

When selecting into #deadlock_process, a SUBSTRING(..., 3, 8000) is used, even though the columns are defined as varchar(2000) in the CREATE TABLE statement.

I didn't see this at first because it _currently_ doesn't cause any problems.

```SQL
client_option_1 =
	SUBSTRING
	(
		...,
		3,
		8000
	),
client_option_2 =
	SUBSTRING
	(
		...,
		3,
		8000
	),
```

**Comment by erikdarlingdata** [comment]
I've assigned this to you as well, since you know which changes to make.

**Comment by erikdarlingdata** [comment]
@JonasEckerman I took care of this one

**Comment by JonasEckerman** [comment]
> @JonasEckerman I took care of this one

Thank you!
