### ISSUE TITLE
sp_BlitzIndex: add ignore_dup_key column to index analysis.  

### ISSUE THREAD

**Issue by kbhaugen** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3281]
Had an index accidently modified to ignore_dup_key = true.  The index in question was a unique, non-clustered index.

Started seeing LCK_M_RS_U wait states which had never shown up before.  Issue caused transitory blocking and slow inserts (table contains  68M rows)

**Comment by BrentOzar** [comment]
Howdy! Sure, if you'd like to contribute that, here's the contributing guide:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md

This wouldn't be something I'd be able to code myself quickly, so if you're not interested in contributing the code, let me know and I can close this issue.

**Comment by BrentOzar** [comment]
I haven't heard back from you, so I'm closing this issue, but if you decide you want to work on the code, just drop a note in here when you're ready to work on it, and I can reopen it. Thanks!
