### ISSUE TITLE
Replacement for sys.dm_os_ring_buffers

### ISSUE THREAD

**Issue by AdrianB1** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3282]
Microsoft is no longer supporting sys.dm_os_ring_buffers . It will continue to work for a while, but eventually it may not. SQL Server First Responder Kit is using this DMV in a few places, so I guess it will need to replace it with something else. At this time I don't know what the replacement would be and if/when this replacement work will be needed.

I am interested to contribute to the implementation as long as there is a clear design for it.

**Comment by BrentOzar** [comment]
Books Online doesn't have a deprecation notice - do you have any official public documentation saying it's deprecated?

**Comment by AdrianB1** [comment]
They say "not supported": https://learn.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sql-server-operating-system-related-dynamic-management-views-transact-sql?view=azuresqldb-current. I tried to find this page for older SQL versions, could not find it. 

I asked at Microsoft last week, confirmed verbally it is not supported, no info of any sort about deprecation, I will have to go via more official channel for a formal answer but it will take some time to get it.

**Comment by BrentOzar** [comment]
Right, unsupported features like sp_MSforeachdb have been around for decades, and even officially deprecated things like Profiler tend to stick around for long periods.

Until Microsoft publicly says they're removing it, we're not going to put work into changing the existing, working code.
