### ISSUE TITLE
Automatically detect if running on Google Cloud SQL

### ISSUE THREAD

**Issue by EricStG** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3290]
**Is your feature request related to a problem? Please describe.**
We use the kit in GCP, on Cloud SQL instances, and we had to do some trial and error and disable some checks to get it to run.

**Describe the solution you'd like**
I could be useful to others to have some checks automatically disabled when running in GCP, since the tool already supports Azure and AWS.

**Describe alternatives you've considered**
We ran sp_blitz by disabling tests until we found a solution that works

**Are you ready to build the code for the feature?**
I can try. Biggest challenge is that I'm not 100% sure how we can detect that we're running in GCP.

This is the list of checks that we have disabled for sp_blitz:
- 2
- 29
- 30
- 31
- 57
- 59
- 61
- 68
- 69
- 73
- 79
- 96
- 98
- 123
- 164
- 180
- 181
- 219
- 2301

**Comment by BrentOzar** [comment]
Unfortunately, I don't know how we'd detect that we're running under GCP either. If you can't figure that out (and you're the one using GCP), then I'm afraid it's not doable for me.

I'm going to close this for now, but if you figure out how to detect if you're running under GCP, then leave a note here with those details and I can reopen it.
