### ISSUE TITLE
sp_Blitz - Skip checks where the login doesn’t have enough permissions 

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3292]
**Is your feature request related to a problem? Please describe.**
I’m doing some work in a high security environment where most checks run but some things like hitting sys.traces and DBCC commands fail, etc. 

**Describe the solution you'd like**
Check to see if the user is a sysadmin/has access to view traces before running some checks. 

**Describe alternatives you've considered**
Embarrassment 

**Are you ready to build the code for the feature?**
Yep, have a prototype 😮‍💨

**Comment by BrentOzar** [comment]
Thanks for the pull request! Made a couple tweaks, tested it on SQL Server 2022 as SA, and on an AWS RDS instance with the default sysadmin account, and works with the same result sets. I didn't try restricting permissions, but this is a good place to start.
