### ISSUE TITLE
Sp_BlitzCache Forced Serialization on SqlServer Express

### ISSUE THREAD

**Issue by markostojkov** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3302]
**Version of the script**
Current version: 8.15 released on Jun 13 2023 12:00AM.

**What is the current behavior?**
According to this [post ](https://dba.stackexchange.com/questions/289916/no-parallelism-in-express-edition-of-sql-server)
and my executions of queries in SqlServer that are flagged with Forced Serialization warning it says that paralel is not possible on express with error NoParallelPlansInDesktopOrExpressEdition 

**If the current behavior is a bug, please provide the steps to reproduce.**
Run Sp_BlitzCache and find a query with Forced Serialization warnin, the plan properties says NoParallelPlansInDesktopOrExpressEdition 

**What is the expected behavior?**
Forced Serialization warning does not help since the query can't go parallel due to Express limitation

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SqlServer is 2019 and I have tried version of the sp blitz script that are 6 months old and the one released june 13

**Comment by BrentOzar** [comment]
Correct, this is useful for folks who are looking at query plans on a server for the first time and wondering why performance is bad.

This is as-designed.

**Comment by markostojkov** [comment]
@BrentOzar In my humble opinion I think a note (in the blitzcache description) would have been really helpful in case when the engine is express, since as a beginner watching your courses I tried for 3 days to modify something that is limited by the engine itself, thanks

**Comment by BrentOzar** [comment]
Sure, I've put a note about Express on the documentation page for this:
https://www.brentozar.com/blitzcache/forced-serialization/

That URL shows up in the URL column for the Forced Serialization warning in the bottom result set of sp_BlitzCache.
