### ISSUE TITLE
sp_Blitz : Add information about the server property 'IsIntegratedSecurityOnly'

### ISSUE THREAD

**Issue by ghauan** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3303]
**Is your feature request related to a problem? Please describe.**
I have a job that regularly store info from sp_blitz to see what/when changes over time. I recently wanted to check if the authentication mode for a server had been changed, from windows only to sql and windows. I tried to find it in sp_blitz, but I could not. (Appollogies if it is already there)

**Describe the solution you'd like**
I know you said in one of your videos that you did not want to have to much security related stuff in sp_Blitz, but I think it could be useful to show what authentication mode is active.

**Describe alternatives you've considered**
Getting info from SELECT SERVERPROPERTY('IsIntegratedSecurityOnly') AS IsWindowsAuthentication;

**Are you ready to build the code for the feature?**
I am not able to test for all kinds of different versions, but I testet the following code on my SQL Server 2019, and it seems to work OK. Used CheckID 258 that was next in line at the moment. Code was added just below code for checkid = 233.
If this is something others also find useful, the code is as follows:

`						/* CheckID 258 - Server Info - Server Authentication */
						IF NOT EXISTS (
										  SELECT    1 FROM  #SkipChecks WHERE   DatabaseName IS NULL AND CheckID = 258
									  )
						BEGIN

							IF @Debug IN ( 1, 2 )
								RAISERROR('Running CheckId [%d].', 0, 1, 258) WITH NOWAIT;

							INSERT INTO #BlitzResults (CheckID, Priority, FindingsGroup, Finding, URL, Details)
							SELECT  258                     AS CheckID
								  , 250                     AS Priority
								  , 'Server Info'           AS FindingsGroup
								  , 'Server Authentication' AS Finding
								  , ''                      AS URL
								  , CASE
										WHEN CAST(SERVERPROPERTY('IsIntegratedSecurityOnly') AS int) = 1 THEN 'Windows Authentication mode'
										WHEN CAST(SERVERPROPERTY('IsIntegratedSecurityOnly') AS int) = 0 THEN 'SQL Server and Windows Authentication mode'
										ELSE 'N/A'
									END                     AS Details;

						END;`

**Comment by ghauan** [comment]
For our particular server/environment we have had a policy of not allowing SQL logins because of a need to log all access back to a person. I would follow up with my team why the setting had changed and it would be nice to know when the change had taken place (based on our saving of sp_blitz to a table). This is by no means a critical need, just a nice to have kind of thing... so I have no problem if the request is rejected.

**Comment by BrentOzar** [comment]
Gotcha - yeah, sp_Blitz isn't really a good fit for continuous monitoring for security issues. Going to close this one.
