### ISSUE TITLE
sp_BlitzLock - Speed up plan cache lookup of deadlock query plans

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3311]
**Is your feature request related to a problem? Please describe.**
SQL Server is picking some wack query plans when hitting the plan cache looking for SQL Handles related to deadlocked queries

![image](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/2136037/daaa8764-88ae-439e-8098-565f6affe0d6)

**Describe the solution you'd like**
Drop qualifying rows into an intermediate temp table from `sys.dm_exec_query_stats` and then get query plans only with those rows.

**Describe alternatives you've considered**
Updating the #available_plans temp table to make it look like it has a ton of rows in it so the optimizer chooses and eager index spool plan. But that doesn't port to RDS, like we discovered with the #t temp table uses to encourage a parallel plan when reading the XML data.

<img width="711" alt="image" src="https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/2136037/ab68387b-2308-4ccb-8701-687342a1ee74">

**Are you ready to build the code for the feature?**
Yes I made it already when working through the same issue with sp_HumanEventsBlockViewer.

**Comment by pydss** [comment]
unsubscribe

**Comment by BrentOzar** [comment]
@pydss to unsubscribe, click the unsubscribe link in the email.
