### ISSUE TITLE
sp_DatabasRestore is showing an incorrect debug message

### ISSUE THREAD

**Issue by gdoddsy** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3320]
**Version of the script** 8.15

**What is the current behavior?**
When debug=1 and @StopAt is not null, the message that prints reference @OnlyLogsAfter instead of @StopAt

**What is the expected behavior?**
Message should say @StopAt

**Comment by gdoddsy** [comment]
Pull request 3321 created to fix this.

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, merged into the dev branch, will be in the next release with credit to you in the release notes.
