### ISSUE TITLE
Monitoring the size of Query store

### ISSUE THREAD

**Issue by ThomasWetzel** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3324]
It would be great to monitor the size of the Query Store.

Once it get's filled you see "Query Store (Read-Only)" in your SSMS.
That means no data is longer collected.

With this code we could get the health check of query store:

USE [QueryStoreDB];
GO

SELECT actual_state_desc, desired_state_desc, current_storage_size_mb,
 max_storage_size_mb, readonly_reason
FROM sys.database_query_store_options;

Perhaps it's a good idea to display the scenario in sp_Blitz.

Bonus: Link how to increase the size of query store.

**Comment by ThomasWetzel** [comment]
Hi @BrentOzar,

I take the challenge and it would be an honor to open a pull request on this repository.

Give me some days, please. :-)

Thomas

**Comment by BrentOzar** [comment]
It's been quite a while, so I'll go ahead and close this for now, but if you'd like to work on it, leave a note here when the pull request is ready and I'll reopen it. Thanks!
