### ISSUE TITLE
sp_BlitzFirst slow when sys.dm_tran_locks contains many rows

### ISSUE THREAD

**Issue by Tisit** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3325]
**Version of the script**
Newest, 8.16

**What is the current behavior?**
If sys.dm_tran_locks contains 100k rows, sp_BlitzFirst runs for minutes.
The issue seems to be with CheckID 8. It contains self join to sys.dm_tran_locks and the execution plan always seems to choose loop join. This can become painful the more rows there are to process.

I wonder, if this join could be removed. I don't fully understand what this code is trying to achieve, but from I found lock where request_owner_type = N'SHARED_TRANSACTION_WORKSPACE' exists for every connection, so it can be simply ignored. Unfortunately there is only one reference to this in an [old post from Paul White](https://www.sqlservercentral.com/forums/topic/cause-of-a-lock-being-placed-on-the-database#post-1145320)

**If the current behavior is a bug, please provide the steps to reproduce.**
Sorry, tried to set up a reproducer, but couldn't make a standalone example

**What is the expected behavior?**
sp_Blitz returns within seconds

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2017. I used older sp_BlitzFirst versions and they inhibited same behavior

**Comment by BrentOzar** [comment]
That query is checking for sleeping queries with open transactions in a particular database, so yeah, unfortunately, we do have to check locks.
