### ISSUE TITLE
sp_BlitzIndex does not show 'DROP INDEX' column when called with table name and default database is not the one containing analyzed table

### ISSUE THREAD

**Issue by ultradumb** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3328]
**Version of the script**
SELECT @Version = '8.15', @VersionDate = '20230613';

**What is the current behavior?**
When called as dbo.sp_BlitzIndex @DatabaseName='MYDB', @SchemaName='myschema', @TableName='MYTABLE' and current database name is, say, 'master' or something else (not MYDB), then script does not display last column - DROP INDEX statement.
**If the current behavior is a bug, please provide the steps to reproduce.**
Call script on a table in any user database, but keep current database as 'master' 

**What is the expected behavior?**
Script should display column with DROP INDEX statement

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
OS: Windows 2012R2, MSSQL 2012 SP4 with latest CU applied. 

Same sp_BlitzIndex script behaves correctly when executed on SQL Server 2022 with same user database.

**Comment by erikdarlingdata** [comment]
@ultradumb are you planning on working on this issue? If so, I'll assign it to you so no one else picks it up and double-works it. It's totally cool if you're not, just want to make sure.

**Comment by BrentOzar** [comment]
@ultradumb I verified that yes, it's working as expected on SQL Server 2022:

![Screenshot 2023-09-19 at 6 58 46 AM](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/245462/afc1aafb-3c43-4cd8-92b1-377ccf711e37)

I don't have 2012 around - it's been out of support for a while. If you want to submit a pull request after you've fixed & tested it on 2012, we'd be glad to take it, but unfortunately I can't troubleshoot 2012 here.

I'm going to close this for now, but if you decide you wanna submit a pull request, go for it and I can reopen this. Thanks!
