### ISSUE TITLE
sp_BlitzLock - check if databases already have RCSI enabled in sys.databases

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3347]
**Version of the script**
All

**What is the current behavior?**
The roll-up warning section will yell about enabling RCSI for database where it's already turned on when readers and writers are blocking each other.

**If the current behavior is a bug, please provide the steps to reproduce.**
It's complicated.

**What is the expected behavior?**
I want to change the messaging in there by looking at sys.databases to see if it's already enabled, not screen it out entirely.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All

**Comment by BrentOzar** [comment]
Makes sense.

**Comment by BrentOzar** [comment]
Thanks for the pull request! Makes sense, other than the weird spaces and line return stuff. Merging into the dev branch, will be in the next release with credit to you in the release notes.
