### ISSUE TITLE
[sp_Blitz documentation] Explain @Debug values in the procedure

### ISSUE THREAD

**Issue by Montro1981** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3348]
**Version of the script**
Version: 8.16
VersionDate: 20230820

**What is the current behavior?**
There is a @Debug parameter to pass to the procedure but there is no explanation of what the different values do.

**What is the expected behavior?**
There is an explanation of what the different values for @Debug do.
0 - Silent running
1 - Output messages per step
2 - Outputs dynamic SQLs

No functional changes are needed.

**Comment by BrentOzar** [comment]
Thanks for the pull request. Looks good, merging into the dev branch, will be in the next release with credit to you in the release notes.
