### ISSUE TITLE
[sp_Blitz] DBCC dbinfo fires even if CheckID 68 or 2 is in #SkipChecks

### ISSUE THREAD

**Issue by Montro1981** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3350]
**Version of the script**
Version: 8.16
VersionDate: 20230820

**What is the current behavior?**
If the user is not part of the sysadmin group `@sa` gets set to 0:
`SET @sa = 0; /*Setting this to 0 to skip DBCC COMMANDS*/`

This later ensures that check 68 and 69 are added to #SkipChecks
```tsql
INSERT #SkipChecks (DatabaseName, CheckID, ServerName)
SELECT
    v.*
FROM (VALUES(NULL, 68, NULL)) AS v (DatabaseName, CheckID, ServerName) /*DBCC command*/
WHERE @sa = 0;

INSERT #SkipChecks (DatabaseName, CheckID, ServerName)
SELECT
    v.*
FROM (VALUES(NULL, 69, NULL)) AS v (DatabaseName, CheckID, ServerName) /*DBCC command*/
WHERE @sa = 0;
```

But the code checking if `DDBC DBInfo` can be run has a logical error in it:
```tsql
--Reformated for readablity
/*
Check 233 is not in #BlitzResults
Check 2 is not in #SkipChecks
Check 68 is in #SkipChecks
*/

IF NOT EXISTS
(
    SELECT 1
    FROM #BlitzResults 
    WHERE CheckID = 223 AND URL = 'https://aws.amazon.com/rds/sqlserver/')
    AND
    (
        NOT EXISTS
        (
            SELECT  1
            FROM    #SkipChecks
            WHERE   DatabaseName IS NULL AND CheckID = 2
        ) OR NOT EXISTS
        (
            SELECT  1
            FROM    #SkipChecks
            WHERE   DatabaseName IS NULL AND CheckID = 68
        )
)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Make a user that is not sysadmin but has VIEW SERVER STATE rights, and doesn't have read rights in some of the system databases
Execute sp_blitz:
```tsql
EXEC [dbo].[sp_Blitz] 
    @CheckUserDatabaseObjects = 1 ,
    @CheckProcedureCache = 0 ,
    @OutputType = 'TABLE' ,
    @OutputProcedureCache = 0 ,
    @CheckProcedureCacheFilter = NULL,
    @CheckServerInfo = 1 ,
    @Debug = 1
```
And you'll get these errors:
```
Extracting DBCC DBINFO data (used in checks 2 and 68).
Msg 2571, Level 14, State 1, Line 9909
User 'guest' does not have permission to run DBCC DBInfo.
Msg 2571, Level 14, State 1, Line 9909
User 'guest' does not have permission to run DBCC DBInfo.
Msg 2571, Level 14, State 1, Line 9909
User 'guest' does not have permission to run DBCC DBInfo.
Msg 2571, Level 14, State 1, Line 9909
User 'SomeUser' does not have permission to run DBCC DBInfo.
Msg 2571, Level 14, State 1, Line 9909
User 'SomeUser' does not have permission to run DBCC DBInfo.
```
**What is the expected behavior?**
The DBCC DBInfo is properly excluded if the user is not SA

**Comment by Montro1981** [comment]
Got the code staged and ready to commit, just want to test it a little more.

**Comment by Montro1981** [comment]
The current code works if both 2 and 68 are in de #SkipChecks, also the errors aren't fatal and the procedure will continue to run.

**Comment by Montro1981** [comment]
Pull request #3357 created

**Comment by BrentOzar** [comment]
Thanks for the pull request! Wow, the logic in the original one makes my head hurt. Merging into the dev branch, will be in the next release with credit to you in the release notes.
