### ISSUE TITLE
[sp_Blitz] Checks with stored procedures sp_validatelogins, xp_regread, and xp_readerrorlog fail because of permissions

### ISSUE THREAD

**Issue by Montro1981** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3356]
**Version of the script**
Version 8.16
VersionDate 2023-08-20

**What is the current behavior?**
The `fn_my_permissions` function returns that we can execute the stored procedures `sp_validatelogins` and `xp_regread` but when we try to execute them we get errors that we have no permissions.
Also permissions for stored procedure `xp_readerrorlog` are not checked.

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a user on the SQL server with VIEW SERVER STATE rights that is not sysadmin.

*sp_validatelogins*
```tsql
SELECT [entity_name], [subentity_name], [permission_name]
FROM fn_my_permissions(N'sp_validatelogins', N'OBJECT') AS fmp
WHERE fmp.permission_name = N'EXECUTE';
```

| entity_name       | subentity_name | permission_name |
|-------------------|----------------|-----------------|
| sp_validatelogins |                | EXECUTE         |

```tsql
EXEC sp_validatelogins;
/*
Msg 15247, Level 16, State 1, Procedure sp_validatelogins, Line 6 [Batch Start Line 0]
User does not have permission to perform this action.
*/
```

*xp_regread*
```tsql
SELECT [entity_name], [subentity_name], [permission_name]
FROM fn_my_permissions(N'xp_regread', N'OBJECT') AS fmp
WHERE fmp.permission_name = N'EXECUTE'
```

| entity_name | subentity_name | permission_name |
|-------------|----------------|-----------------|
| xp_regread  |                | EXECUTE         |

```tsql
EXEC xp_regread @rootkey = N'HKEY_LOCAL_MACHINE', @key = N'', @value_name = N'';
/*
Msg 22001, Level 16, State 1, Line 31
xp_regread() returned error 5, 'Access is denied.'
*/
```

*xp_readerrorlog*
```tsql
SELECT [entity_name], [subentity_name], [permission_name]
FROM fn_my_permissions(N'xp_readerrorlog', N'OBJECT') AS fmp
WHERE fmp.permission_name = N'EXECUTE';
```

| entity_name | subentity_name | permission_name |
|-------------|----------------|-----------------|
|             |                |                 |

All these errors are not fatal and the procedure will continue to run.

**What is the expected behavior?**
For `sp_validatelogins`, `xp_regread` we need to check if we can actually execute the procedures and set the `@SkipValidateLogins` and `@SkipXPRegRead` variables accordingly.
For `xp_readerrorlog` there is no variable (yet) so we need to add an skip variable to the list `,@SkipXPReadErrorLog bit = 0` and set it accordingly and disable check 193 if `@SkipXPReadErrorLog = 1`

**Comment by Montro1981** [comment]
Made three separate pull request as the issue required three different solutions.

**Comment by Montro1981** [comment]
@erikdarlingdata you're welcome.

**Comment by BrentOzar** [comment]
Thanks for the pull request. Looks good, merging into the dev branch, will be in the next release with credit to you in the release notes.
