### ISSUE TITLE
KB4583458 missing from SqlServerVersions 

### ISSUE THREAD

**Issue by shaba49** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3363]
Hi,

KB4583458- Description of the security update for SQL Server 2019 GDR: January 12, 2021

Is missing from SqlServerVersions - please add

**Comment by BrentOzar** [comment]
@shaba49 hi! We focus on CUs and current GDRs, but not every single past hotfix and GDR. If a particular build is important to you, you're welcome to add it by opening a pull request. For more information on that, check out the contributing guide here: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md

Thanks!
