### ISSUE TITLE
sp_Blitz not working

### ISSUE THREAD

**Issue by anime-shed** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3367]
**Version of the script**
SELECT @Version = '8.16', @VersionDate = '20230820';

**What is the current behavior?**
![image](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/67512697/fd15ae8e-79be-42e1-bf88-0a193a373b34)

**If the current behavior is a bug, please provide the steps to reproduce.**
Install-All-Scripts.sql, Install-Core-Blitz-With-Query-Store.sql, Install-Core-Blitz-No-Query-Store.sql, sp_Blitz
Give the following error
![image](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/67512697/664207cf-d6e3-48bf-9c45-ec2199f5e315)

**What is the expected behavior?**
Command should return details for it.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
| BuildClrVersion | ProductLevel | ProductVersion | Edition   |
|-----------------|--------------|----------------|-----------|
| NULL            | RTM          | 12.0.2000.8    | SQL Azure |

**Comment by anime-shed** [comment]
![image](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/67512697/72b4a5fe-8987-41e1-a0f7-bbfe1c15f7e9)

I just saw this right now, and I presume it might be a case for non-functioning, but I would be glad to be proved wrong.


BTW: I have tried other SP:
sp_BlitzCache
sp_BlitzFirst
sp_BlitzIndex

And these seems to work properly.

**Comment by anime-shed** [comment]
Is there any other repo that can help me with this, like having a similar functionality like sp_blitz, since I am having constant issues popping up on our database, and sheer randomness is a pain!

**Comment by Montro1981** [comment]
@anime-shed which branch of sp_blitz are you using?
Could you run it with @debug = 1 ?

**Comment by anime-shed** [comment]
@Montro1981 I was trying out the `dev` branch.
And `@dubug=1`
![image](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/67512697/b456f3da-35ec-4c9c-a4ef-1f912b8954f6)

**Comment by anime-shed** [comment]
For some reason, it does not have any parameters:
![image](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/67512697/4aeb90d6-acc9-4c4c-81f0-845092479612)
