### ISSUE TITLE
Case Sensitivity issue in sp_BlitzCache

### ISSUE THREAD

**Issue by markkeyworth** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3368]
**Version of the script**
Version: 8.16 VersionDate:20230820

**What is the current behavior?**
Error on creation:
Msg 137, Level 15, State 1, Procedure sp_BlitzCache, Line 615 [Batch Start Line 239]
Must declare the scalar variable "@minimumExecutionCount".

**If the current behavior is a bug, please provide the steps to reproduce.**
Have a database which requires case sensitivity (in my case Latin1_General_BIN) and try and execute the script

**What is the expected behavior?**
The script should allow you to create the sp_BlitzCache. Requires @minimumExecutionCount changing to  @MinimumExecutionCount

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
N/A

**Comment by markkeyworth** [comment]
Has been caused by a change in #3345. Its actually line 854 of the script which causes the issue.

**Comment by Montro1981** [comment]
There were some more case mismatches for this parameter, fixed them and opened PR #3369

**Comment by BrentOzar** [comment]
Thanks for the pull request. Looks good, merging into the dev branch, will be in the next release with credit to you in the release notes.
