### ISSUE TITLE
The module 'sp_AllNightLog' depends on the missing object

### ISSUE THREAD

**Issue by wycislo** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3372]
**Is your feature request related to a problem? Please describe.**
RDS will not let you install anything in the master database. I install first responder and Ola's scripts  in a database called DBATools. But sp_allnightlog is looking for Ola's scripts to be installed in master. 

The module 'sp_AllNightLog' depends on the missing object 'master.dbo.DatabaseBackup'. The module will still be created; however, it cannot run successfully until the object exists.

**Describe the solution you'd like**
modify sp_allnightlog to not depend on scripts existing in the master database. 

**Describe alternatives you've considered**
none

**Are you ready to build the code for the feature?**
As much as we'd love to build everything that everyone wants for free, we need your help. Open source is built with your help and code. Are you ready to commit time to this project? 
Yes
Have you got existing code you can help contribute to solve the problem?
No I am not sure how extensive this request is.

**Comment by BrentOzar** [comment]
You don't really wanna use RDS as a log shipping publisher. Amazon does their own transaction log backups, and you can't specify them to be copy-only, so your log shipping would get broken constantly.
