### ISSUE TITLE
[sp_Blitz] [Bug] Permissions checks are not working as intended

### ISSUE THREAD

**Issue by Montro1981** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3377]
**Version of the script**
8.17
20231010

**What is the current behavior?**
Mea culpa, some of the fixes I made for the permission checks are not working.
😢 

* #3360 xp_regread doesn't play nice with a TRY CATCH block, so we just have to swallow those errors, they are not breaking the run, they just annoy me in the messages tab but, oh well, that's what we get for using an undocumented stored procedure.
* #3358 the permission check for the msdb database is to broad
* Forgot the add a check for [master].[dbo].[sp_MSgetalertinfo]

**What is the expected behavior?**
Fix the code to correct the issue I introduced.
* xp_regread, it gets the `@powerScheme` alright after the first error. The cpu speed not so well. Going to ISNULL the speed to UNKW
* add additional permission check for the msdb database
* add permission checkfor [master].[dbo].[sp_MSgetalertinfo]

Will be separate Pull requests per fix.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Same errors different day, thus more fixes.

**Comment by BrentOzar** [comment]
Looks good! Thanks for the pull request. Merging into the dev branch, will be in the next release with credit to you in the release notes.

**Comment by BrentOzar** [comment]
Thanks for the modified pull request! Looks good, works on my machine, heh. Merging into dev, will be in the next release with credit to you in the release notes.

If I don't remember "Martin", remind me again the next time you see me live, heh. I'm terrible with names, and Montro1981 is so memorable, oddly!
