### ISSUE TITLE
Missing index results are different between V2 and V3/4

### ISSUE THREAD

**Issue by TaraKizer** [BrentOzarULTD/SQL-Server-First-Responder-Kit#338]
Take a look at CriticalCare_query_outputs_20160628_081300.xlsx for example.

V2 0 tab has 18 missing indexes.
V3 4 tab has 1 missing index.

The table that starts with T doesn't show up in V3 4 even though it's 715MB.
Also, the table that did show up in V3 4 (starts with R) has other missing indexes in the list in V2 0 but aren't there in V3 4.

Both tables, T and R, are above the 250MB filter.

Of note is the C table that is 0.00MB with 18,263 rows. That one came up in the execution plans and had a high cost. So even though it's small in size and registering at zero MB, it is a costly scan without the index.

**Comment by BrentOzar** [comment]
Fixed! Missing index benefit was filtering for 100k per day, but that would result in few indexes showing up for servers that had been up for months. Now no filter at all when we use @Mode = 4.
