### ISSUE TITLE
sp_BlitzLock last_execution_time error

### ISSUE THREAD

**Issue by teej21012** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3385]
**Version of the script**
Version = 8.17
VersionDate = 20231010

**What is the current behavior?**
sp_BlitzLock returns an error when there is a last_execution_time value in sys.dm_exec_query_stats that returns '1900-01-01 00:00:00.000'

```
Msg 535, Level 16, State 0, Procedure sp_BlitzLock, Line 3758 [Batch Start Line 0]
The datediff function resulted in an overflow. The number of dateparts separating two date/time instances is too large. Try to use datediff with a less precise datepart.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Check sys.dm_exec_query_stats for any queries that have a last_execution_time of '1900-01-01', do a DATEDIFF using the SECOND datepart, and compare to GETDATE()

Repo code:

```
DECLARE @creationTime DATETIME = GETDATE()
DECLARE @lastExecutionTime DATETIME = '1900-01-01 00:00:00.000'

SELECT DATEDIFF(SECOND, @creationTime, @lastExecutionTime)
```

**What is the expected behavior?**

Imagine it should either exclude those rows or treat them as NULL, unsure what the expected behavior should be for them.

**Which versions of SQL Server and which OS are affected by this issue?**

SQL Server version - Standard 2019 (15.0.4316.3)
OS version - Windows Server 2019 Standard

**Did this work in previous versions of our procedures?**
Looks like [this section of sp_BlitzLock was added](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/commit/ff8a0f4869a3f040ea3741d134b877288a9b5ad7) by @erikdarlingdata on Jun 28.

**Comment by erikdarlingdata** [comment]
@teej21012 yes, a similar issue has been reported [here](https://dba.stackexchange.com/q/332405/32281), for a different code branch. It would be easy enough to code something around it in a few different ways, but it would also be useful to understand how the DMV ends up with that data in it. If possible, can you show the code that causes an error? In particular, I’d like to understand if the queries have timed out, aborted, or are mid-execution when this happens. 

Thanks,
Erik

**Comment by teej21012** [comment]
@erikdarlingdata It looks like some of them are dynamic SQL queries (but not all dynamic SQL that happens on the server?), along with a few statements just being ran in SSMS windows.  As far as mid-execution, referencing [the MSDN for sys_dm_exec_query_stats](https://learn.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-query-stats-transact-sql?view=sql-server-ver16):

![image](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/5401085/e7314d5d-00a1-4825-bf5b-319a07246325)

The biggest thing I noticed is all the ones that have the 1900-01-01 value also have a total_dop (the total sum of degree of parallelism this plan used since it was compiled) value of 0.  Again, referencing the same page, that is supposed to be for memory-optimized tables.

Not sure what conclusion that can be drawn out of that outside of maybe the engine is trying to be do something fancy with memory tables and failing?

**Comment by BrentOzar** [comment]
Looks good! Thanks for the pull request. Merging into the dev branch, will be in the next release with credit to you in the release notes.
