### ISSUE TITLE
sp_BlitzQueryStore error on line 4302

### ISSUE THREAD

**Issue by ralfvaessen** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3387]
SQL Server 2019
error message after execution of sp_BlitzQueryStore

Msg 50000, Level 16, State 6, Procedure dbo.sp_BlitzQueryStore, Line 4302 [Batch Start Line 0]
<dbname> database failed to process. Arithmetic overflow error converting float to data type numeric.

**Comment by BrentOzar** [comment]
When you opened this issue, you deleted all of the issue template questions. I'm going to close this, but when you reopen it, make sure you answer the questions shown on the screen - don't delete them. Thanks!
