### ISSUE TITLE
BlitzCache doesn't report Stored Procedure cost

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#339]
This is a pretty simple fix. QueryHash isn't populated when we get stored procedure information. This goes back to how we filter on QueryHash, and how that information isn't available. It's NULL for stored procedures and triggers. All we need to do is update ##bou_BlitzCacheProcs. If we join it to itself on SqlHandle, we can populate that column.

```
UPDATE b
        SET 
            b.QueryHash           = b2.QueryHash,
            b.MinReturnedRows	  = b2.MinReturnedRows,
            b.MaxReturnedRows	  = b2.MaxReturnedRows,
            b.AverageReturnedRows =	b2.AverageReturnedRows,
            b.TotalReturnedRows	  = b2.TotalReturnedRows,
            b.LastReturnedRows    = b2.LastReturnedRows
FROM ##bou_BlitzCacheProcs b
JOIN ##bou_BlitzCacheProcs b2
ON b2.SqlHandle = b.SqlHandle
WHERE b.QueryHash IS NULL
```

We also need to correct a logical error in another update query. We update with a case expression on the QueryType column like '%Stored Procedure%', but that column will only ever say 'Procedure:' followed by the name of the procedure. This update can also be removed from another update further down the line.

**Comment by BlitzErik** [comment]
One comment on this is that if there's parameter sniffing, this will associate the worst case values with the stored proc. This will make for good testing in the dev branch.

**Comment by BlitzErik** [comment]
Sweet.

![image](https://cloud.githubusercontent.com/assets/11590415/16501268/8d779acc-3ed6-11e6-99d9-bce4624cb488.png)

**Comment by BrentOzar** [comment]
Ooo, love where you're going with this, and it's close. Thing is, it's getting *some* cost for the stored proc, but not the total:

`CREATE PROCEDURE [dbo].[Twofer] AS
BEGIN
SELECT * FROM dbo.Users WHERE DisplayName = 'Brent Ozar'
SELECT * FROM dbo.Users WHERE DisplayName = 'sp_BlitzErik'
END
GO
DBCC FREEPROCCACHE
GO
EXEC dbo.Twofer;
GO
sp_BlitzCache`

Each statement in that proc has an individual cost of 74.535 on my StackOverflow, but the stored proc's cost line is showing as 74.535:

<img width="638" alt="1" src="https://cloud.githubusercontent.com/assets/245462/16519406/b4534404-3f56-11e6-8d10-4dfc910f8b92.png">

I think it's this part:

`UPDATE b
        SET 
            b.QueryHash           = b2.QueryHash,
            b.MinReturnedRows	  = b2.MinReturnedRows,
            b.MaxReturnedRows	  = b2.MaxReturnedRows,
            b.AverageReturnedRows =	b2.AverageReturnedRows,
            b.TotalReturnedRows	  = b2.TotalReturnedRows,
            b.LastReturnedRows    = b2.LastReturnedRows
FROM ##bou_BlitzCacheProcs b
JOIN ##bou_BlitzCacheProcs b2
ON b2.SqlHandle = b.SqlHandle
WHERE b.QueryHash IS NULL
`

I think you wanna do a sum on b2's data. The way it is now, it's just grabbing ONE row from b2 (but you're not sure which one.) Maybe:

`UPDATE b
        SET 
            b.QueryHash           = b2.QueryHash,
            b.MinReturnedRows	  = SUM(b2.MinReturnedRows),
...`

That kind of thing.

**Comment by BlitzErik** [comment]
Yeah, you're right, I need to aggregate the update. 

The issue with the way it sums costs is in the xml processing. I'm working on it, but if you want to take a look it's where I changed '%stored procedure%' to '%procedure%'. It's not actually summing costs.

**Comment by BlitzErik** [comment]
I have the aggregation query working correctly for the first part. However, there seems to be an issue with the XML summing plan costs. 

To get it out of the way first: SqlHandle is unusable here because the internal SQL handle for each statement is different from the SQL handle in the DMVs.

I don't think it's doable the way it's being done, it will probably require extra steps because QueryHash and QueryPlanHash reliable but require grouping to get plan costs nailed down.

![image](https://cloud.githubusercontent.com/assets/11590415/16523785/2f936b50-3f73-11e6-9479-892e136bc1be.png)

**Comment by BlitzErik** [comment]
Pull request ready for dev branch

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/349

**Comment by BlitzErik** [comment]
We have a bit of a choice to make here. Would it make more sense to Use cost averages instead of exact? It will still be right/the same for 
![image](https://cloud.githubusercontent.com/assets/11590415/16534217/24f12852-3fac-11e6-8835-7a18762abf1f.png)

**Comment by BrentOzar** [comment]
Leaving this one open until we get the bugs ironed out.

If you go into Presentations/Brent/Watch Brent Tune Queries/StoredProcs.sql, there's a bunch of stored procs I use for load testing. Create those, and then run GetShell a bunch of times with SQLQueryStress. (I use like 100 executions across 10 threads.) That'll warm up your plan cache with stuff.

Then run sp_BlitzCache @SortOrder = 'duration' and you get the below screenshot. (Or at least I did, ha ha ho ho.) In the summary results at the bottom, line #3 is "Joining to table valued functions" but I don't see that in the warnings in the top set. Try running it back and forth in different sort orders, and it doesn't seem like the top and the bottom result set are always connected, and I can't get the "Joining to table valued functions" to ever appear in the top result set.

This may not be directly related to the work in this issue - I know there's been a few things checked into this one lately - so apologies if it's not directly tied. Just wanna get this fixed before I merge it into the dev branch.

![sp_blitzcache_duration](https://cloud.githubusercontent.com/assets/245462/16562779/261dfaf6-41c4-11e6-87af-0362c6e3e27c.png)

**Comment by BlitzErik** [comment]
The joining to TVFs warning is pretty unreliable. I've been trying to figure out why, but I haven't changed any of its behavior. Found this out while trying to generate the warning for something else.

 https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/329

**Comment by BrentOzar** [comment]
Oh, perfect. Everything else in it is looking great then, closing this and merging.
