### ISSUE TITLE
sp_BlitzLock not working in an AzurevSQLMI

### ISSUE THREAD

**Issue by FatimaBrunson** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3391]
I’m in the Fundamentals course this week and ran into the below error when trying to run sp_BlitzLock on an Azure SQLMI database. Can you point me to how to resolve this, so that I can view any deadlock within our production server?

![image](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/102535401/c673edf5-f186-497a-a53a-be61bebf14dc)

**Comment by BrentOzar** [comment]
@FatimaBrunson Hi, Fatima. Remember what I said during class: when you create an issue, there will be a series of questions here in the issue. You have to fill those out. Please open a new issue and this time, don't delete all the questions - actually answer 'em. Thanks!

**Comment by FatimaBrunson** [comment]
Can you point me to the series of questions because must be over looking them? I've checked in the recap pdfs and I don't see what needs to be included in the issues ticket on github.

**Comment by BrentOzar** [comment]
When you click New Issue, here are your choices:

![Screenshot 2023-11-08 at 6 13 11 AM](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/245462/c3a6783b-f4f0-4331-b712-4a3f990c2c0d)

You'll choose Bug Report. Then, the next screen looks like this:

![Screenshot 2023-11-08 at 6 13 17 AM](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/245462/e29eb9d1-0dea-4804-bdde-5f4cb8efe017)

You deleted all of that stuff. You have to actually read it and fill it in. Thanks!

**Comment by FatimaBrunson** [comment]
Thank you and I will do that now

**Comment by pydss** [comment]
Unsubscribe
