### ISSUE TITLE
Make sp_blitzindex run faster on bigger sql servers

### ISSUE THREAD

**Issue by HenrikStaunPoulsen** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3393]
**Is your feature request related to a problem? Please describe.**
It takes more than 11 hours (the limit of my patience) to run sp_blitzindex on my clients SQL Server. 

**Describe the solution you'd like**
I would like it to finish in 3 hours

**Describe alternatives you've considered**
Apply the knowledge that I've gained from Brent's lessons, on how to use #Tmp tables to extract data before running the report.

**Are you ready to build the code for the feature?**
yes.

**Comment by BrentOzar** [comment]
@HenrikStaunPoulsen I've got a little bad news there: sp_BlitzIndex does already use temp tables, but gathering data from the partitions DMV does indeed take hours when you're talking about hundreds of thousands of partitions.

You're definitely welcome to go for it, but if you don't submit a pull request in the next week or so, I'll close this for now. We can totally reopen it when you've got a more specific performance tuning idea though!

**Comment by pydss** [comment]
Unsubscribe

**Comment by pydss** [comment]
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
