### ISSUE TITLE
sp_BlitzLock does not return data on some deadlocks

### ISSUE THREAD

**Issue by bmrazik-pl** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3396]
verson - 8.17

**What is the current behavior?**
when using Erik Darling suggested extended event name "deadlock" (EXEC dbo.sp_BlitzLock @eventsesseionname = N'deadlock') or using the existing system events "system_health" (EXEC dbo.sp_BlitzLock) some deadlocks are not reported, however, when i search through the error logs i see a deadlock had been raised - the ones listed in steps below are NOT reported, nor do i see a deadlock graph for these in error logs, however, other deadlocks are reported and graphed in logs

**If the current behavior is a bug, please provide the steps to reproduce.**
see above - nothing reported via blitzlock and by calling  exec master.dbo.xp_readerrorlog 0, 1, null, null, @d (@d is last 24 hours date), null, N'asc' i get something like this:
Deadlock encountered .... Printing deadlock information
Wait-for graph
NULL
Node:1  
Port: 0x0000023D514EA550  Xid Slot: 3, Wait Slot: 1, Task: 0x00000246D3541088, (Producer), Exchange Wait Type: e_waitPipeNewRow, Merging: 1
 ResType:ExchangeId Stype:'AND' SPID:89 BatchID:0 ECID:3 TaskProxy:(0x0000022F093DEB90) Value:0xd3541088 Cost:(20/0)
   SPID: 89 ECID: 3 Statement Type: SELECT INTO Line #: 46

Node:2  
Port: 0x0000023401CF18D0  Xid Slot: 2, Wait Slot: 1, Task: 0x00000240B8F2DC28, (Producer), Exchange Wait Type: e_waitPipeNewRow, Merging: 1
 ResType:ExchangeId Stype:'AND' SPID:89 BatchID:0 ECID:7 TaskProxy:(0x0000022F093DED10) Value:0xb8f2dc28 Cost:(20/0)
   SPID: 89 ECID: 7 Statement Type: SELECT INTO Line #: 46

Node:3  
Port: 0x000002378CDFF0C0  Xid Slot: 0, Wait Slot: 2, Task: 0x00000240B8F2D468, (Consumer), Exchange Wait Type: e_waitPipeGetRow, Merging: 0
 ResType:ExchangeId Stype:'AND' SPID:89 BatchID:0 ECID:4 TaskProxy:(0x0000022F093DEBF0) Value:0xb8f2d468 Cost:(0/10000)
   SPID: 89 ECID: 4 Statement Type: SELECT INTO Line #: 46

etc...

**What is the expected behavior?**
calling blitzlock will report all deadlock events

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
i do not recall seeing the deadlocks prior to this either, this is first time i'm reporting
sql server 2016 - 13.0.6419.1 and windows 2019

**Comment by erikdarlingdata** [comment]
@bmrazik-pl these are parallel deadlocks, which have undergone several changes in when and how they're raised. See [here](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/2636) for another issue I worked on related to them.

Anyway, I can't really do much about this unless you provide the full deadlock report XML here to see where `sp_BlitzLock` might be missing something. Please make sure that you can actually see the full XML deadlock report in the Extended Event session, and not *just* in the error log. If it's not showing in any Extended Event sessions, it's not a bug, heh.

**Comment by bmrazik-pl** [comment]
@erikdarlingdata based on your comments and previous issue you worked, it appears there is no issue - there is no deadlock xml ever produced - apologize for missing the prev issue - and many thanks for all your work on this and all else - big fan :)

**Comment by erikdarlingdata** [comment]
@bmrazik-pl ooh, yeah, my pleasure. Glad you're enjoying it!

**Comment by pydss** [comment]
Unsubscribe
