### ISSUE TITLE
sp_Blitz: duplicate rows in Availability Groups output

### ISSUE THREAD

**Issue by gotqn** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3402]
**Version of the script**

8.17

**What is the current behavior?**

_Msg 2628, Level 16, State 1, Line 3429
String or binary data would be truncated in table 'tempdb.dbo.#BlitzResults_______________________________________________________________________________________________________00002FEA3294', column 'Details'. Truncated value: 'The cluster nodes are:  PRIMARY=..., PRIMARY=..., PRIMARY=..., P'._

**If the current behavior is a bug, please provide the steps to reproduce.**

![image](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/2104401/55779a0b-c563-4b8a-b3ce-3e66dec4cc74)

**What is the expected behavior?**

I am not familiar with availability groups but it seems we just need a `DISTINCT` in the sub-query like this:

```
 SELECT 53 AS CheckID ,
    200 AS Priority ,
    'Informational' AS FindingsGroup ,
    'Cluster Node Info' AS Finding ,
    'https://BrentOzar.com/go/node' AS URL,
    'The cluster nodes are: ' + STUFF((SELECT DISTINCT ', ' + CASE ar.replica_server_name WHEN dhags.primary_replica THEN 'PRIMARY'
    ELSE 'SECONDARY'
    END + '=' + UPPER(ar.replica_server_name) 
    FROM sys.availability_groups AS ag
    LEFT OUTER JOIN sys.availability_replicas AS ar ON ag.group_id = ar.group_id
    LEFT OUTER JOIN sys.dm_hadr_availability_group_states as dhags ON ag.group_id = dhags.group_id
    ORDER BY 1
    FOR XML PATH ('')
    ), 1, 1, '')
```

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

_Microsoft SQL Server 2019 (RTM-CU18) (KB5017593) - 15.0.4261.1 (X64) 
	Sep 12 2022 15:07:06 
	Copyright (C) 2019 Microsoft Corporation
	Standard Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: )_

**Comment by BrentOzar** [comment]
Thanks! Makes sense. Do you want to submit a pull request with that change? If not, no worries, I can do it since it's pretty short.

**Comment by BrentOzar** [comment]
@gotqn can you test to see if adding a distinct there fixes it? If so, I'll do the pull request. Thanks!

**Comment by gotqn** [comment]
Sorry, for the late response. Yes, I have added DISTINCT in order to run the routine without errors back then.
