### ISSUE TITLE
[sp_Blitz] [Enhancement] Different check for the 'instant_file_initialization_enabled' column in Check 192 and 193

### ISSUE THREAD

**Issue by Montro1981** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3409]
**Is your feature request related to a problem? Please describe.**
Enhancement to #3362 as Brent "Hated" my solution for checking for the 'instant_file_initialization_enabled' column in the `sys.dm_server_services` DMV: https://www.twitch.tv/videos/2004009922?t=85m15s

This makes me sad (not really).

**Describe the solution you'd like**
Make a piece of "Brent Ozar" approved code, using the `sys.all_columns`:
```tsql
IF EXISTS
(
    SELECT 1/0
    FROM sys.all_columns
    WHERE [object_id] = OBJECT_ID(N'[sys].[dm_server_services]')
    AND [name] = N'instant_file_initialization_enabled'
)
    Print 'Foo';
ELSE
    Print 'Bar';
```

**Describe alternatives you've considered**
Leaving it as-is but Brent will "hate" this solution and he might need a stronger beverage.

**Are you ready to build the code for the feature?**
Yep, a PR will be provided free of charge to please the Mighty Ozar.

**Comment by BrentOzar** [comment]
Thanks for the pull request. Looks good, merging into the dev branch, will be in the next release with credit to you in the release notes.
