### ISSUE TITLE
sp_Blitz - Add non-default database configuration check for Accelerated Database Recovery

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3411]
**Is your feature request related to a problem? Please describe.**
My problem is that sp_Blitz doesn’t tell me if Accelerated Database Recovery is enabled. 

**Describe the solution you'd like**
I would like sp_Blitz to tell me if Accelerated Database Recovery is enabled. 

**Describe alternatives you've considered**
Picking up bucket drumming

**Are you ready to build the code for the feature?**
Yes I will add it to the other checks for similar changes.

**Comment by tominyorks** [comment]
> Picking up bucket drumming

@erikdarlingdata When is that making it to YouTube?

**Comment by erikdarlingdata** [comment]
@tominyorks as soon as I can afford buckets

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, merging into the dev branch, will be in the next release with credit to you in the release notes.
