### ISSUE TITLE
sp_BlitzLock empty even though blocking occurring

### ISSUE THREAD

**Issue by fuzzy17** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3412]
**Version of the script**
version 8.11 date 20221013

**What is the current behavior?**
Empty results even though activity monitor -> processes shows blocking.

**If the current behavior is a bug, please provide the steps to reproduce.**
SQL server Agent was running CDC job and was blocked by another process.  I did not get the other process, but it could have been an application.   The CDC job was blocking another application.  

**What is the expected behavior?**
Should show blocking

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
13.0.5622

**Comment by BrentOzar** [comment]
sp_BlitzLock is about deadlocks, not blocking. For information on current blocking, check out sp_BlitzWho.
