### ISSUE TITLE
GitHub sync issue with my forked repo

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3427]
I've searched around a bit but haven't found a good answer to this.

In my fork of the FRK, I'm able to sync things from the dev branch in, but there's a note at the top of the screen:

![image](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/2136037/c2b1b0ad-9348-4a21-894c-e31855fd08ca)

When I follow that link in, it's all old commits that have been merged.

![image](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/2136037/9a4dfde4-55c0-4797-b804-f1500a16c4c9)

Even though 34 commits are listed, only one file is changed:

![image](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/2136037/f21f6760-e837-4435-902b-768e664d201b)

And it introduced a stupid bug into bp_BLitzLock:

![image](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/2136037/4e1b8f1e-48ce-4bd4-b816-5a67a6b493d0)

I don't see a way to discard these, or discard the change to the one file.

Does anyone out there know how to do either one of those things, or do I just need to delete everything and start my fork fresh?

Please @ me.

Thanks!

**Comment by DavidWiseman** [comment]
You could reset your dev branch to match the main repo (make sure dev is checked out):

`git reset --hard upstream/dev`

You will then need to force push the changes to GitHub.

`git push -f`

The workflow I use to keep me out of trouble -

Create a new branch when making any changes.  Don't change the dev/master/main branches.
Create PRs to the upstream repository.
Click the "Sync Fork" button in GitHub website to get changes made from upstream back to my fork.  I should probably use the CLI, but this works for me.

**Comment by erikdarlingdata** [comment]
@DavidWiseman I tried this, and got as far as the second command. The shell asked for a username and password, and then told me using passwords via CLI is deprecated, and wanted me to jump through a bunch of hoops to manage credentials and what not. I don't really have time to invest in all it's asking me to do, so I'm gonna try to find something else that may work.

**Comment by DavidWiseman** [comment]
@erikdarlingdata I Hope you find a fix that works for you.  For me, it pops up with a small window that gives me the option to sign in via the browser.  

![image](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/33157668/349934a3-8e2e-4dd0-afcf-04c33f07b334)

Your suggested fix to delete and re-create the fork would work if all else fails.
