### ISSUE TITLE
Run a custom SQL query when @TestRestore = 1

### ISSUE THREAD

**Issue by gdoddsy** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3429]
**Is your feature request related to a problem? Please describe.**
We have a request to do a restore of a test database from a snapshot to confirm that it's still valid (e.g. to confirm disk corruption hasn't happened). Currently I'm using `sp_databaseRestore` and passing in `@TestRestore = 1, @RunCheckDB = 1`.

Because the business is paranoid, they'd also like to run a custom script to count how many lines are in a critical table.

I feel this script could be useful after a normal restore as well, being able to say restore this database and then do....something. However, if the "something" is more than a simple statement, then debugging it via sp_DatabaseRestore is probably too much work. I'm talking myself out of this as I'm writing.

**Describe the solution you'd like**
I don't know if this is a good idea, but I'm wondering if a custom script can be passed in to run. There's probably a bunch of security issues this'll introduce, so that might be enough reason to say no.
I'd need the script to somehow return an error, but not sure if I want the error to stop the drop database script that is currently in `sp_DatabaseRestore`

**Describe alternatives you've considered**
I'll just run `sp_DatabaseRestore` without the `@TestRestore=1` parameter. Once the database is restored, I'll run the scripts required, and then run the drop database statement by itself. This is probably the better way to do, but just imagining that we're not the only company that might want to do something like this.

**Are you ready to build the code for the feature?**
I'm happy to build it, but need some direction on how to do this so it doesn't break for everyone or introduce an unacceptable risk in having scripts run. If someone has a great idea I haven't thought of, then drop it in here and I'm happy to give it a go.

Otherwise, suggest this just gets closed.

**Comment by BrentOzar** [comment]
You're gonna laugh - in my newfound interest in First Responder Kit automated testing, I'm hesitant to add in new features that would be hard to test. If we're going to test that this works, we would need to:
* Take a backup
* Run sp_DatabaseRestore to restore it
* Run the new test-restore functionality in a way that passes, and verify that it passes
* Run the new test-restore functionality in a way that it fails, and verify that it fails

If you're interested in building the automated tests as well, then yeah, we can go for it. If not, I totally understand - building automated testing for stuff like this is another level of work, and not everybody has the time to do that kind of work.

**Comment by BrentOzar** [comment]
But to be clear, I do totally understand the value of the feature, and it makes sense. I'm just hesitant to add more functionality unless we can test that it's working as designed, especially on a script like sp_DatabaseRestore that I don't ever test.

**Comment by gdoddsy** [comment]
I'm not laughing - I love the idea of automated tests!

Just thinking for my needs again, if I had a parameter-less stored proc to run instead of just accepting a script (I'd originally thought of passing in some select statements which would be a nightmare), then this would be a whole lot easier to do. This would also (help) get rid of the security issues that I had in my head - if it's a stored proc in the restored database, that **should** mean that it was code-reviewed and tested (I say should...but at least this will help shift the risk to the database before the backup happened), so there's less of a chance that things will go wrong.

If that was the case, is it as simple as wrapping a try/catch block around the proc? If it fails, it goes to the catch block, and we can display a message (e.g. `Failed to run procedure @procName after restoring`) and then continue on with the rest of the clean-up.

For testing, we'd just need to have a database with 2 stored procs in it:

- `create proc PassTest AS BEGIN select 1 END`
- `create proc FailTest AS BEGIN select 1/0 END`

Then do the backup, run `sp_databaseRestore` passing in `PassTest` and verify that the catch block is not hit, and run `sp_databaseRestore` passing in `FailTest` and verify that the catch block is hit.

I've done unit testing in c# before, but not SQL. I haven't been following along much in the last year or two about first responder kit to see what testing you've done, but has anyone got test code for sp_DatabaseRestore yet? I can't set it in github (maybe I'm just blind).

Looking at the other examples, does `-OutputAs DataSet` turn the results text into a dataset? If not, can you give me any pointers on how to test the output results, or should sp_DatabaseRestore return something else? I think I can write it, just trying to get my head around how to do it.

Last question about the testing (for now) - does it run with credentials high enough that I can create a database and add some procs to it, drop the database, restore the database with `@testrestore=1`?

**Comment by BrentOzar** [comment]
The first pass of the test setup is here: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/.github/workflows/integration-tests.yml

I wish it was as easy as editing an existing file to test sp_DatabaseRestore, but no.

**Comment by gdoddsy** [comment]
Still interested.

I've created a pull request with the proposed change in sp_databaserestore. Can you give me any feedback on your thoughts for that before proceeding with the unit testing stuff?

I was going to put it in a try/catch block, but if it fails, then I want the proc to fail. Need to decide if you want the clean-up to run if the verify stored proc fails.

**Comment by BrentOzar** [comment]
When I look at what the code does, it isn't necessarily testing the database - it's really just running a stored proc after the restore finishes. 

This functionality could be good for other stuff too, like obscuring data or changing permissions. I switched the parameter name from @VerifyRestoreWithStoredProcedure to @RunStoredProcAfterRestore.

Good work!

**Comment by BrentOzar** [comment]
I think this is done, but if there's still anything you wanna do, let me know and I'll reopen the issue. Just closing it in preparation for this month's release. Thanks sir!
