### ISSUE TITLE
Edit the contributing guide to tell Friends Of The Repo to not meddle with Installer scripts

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3432]
**Is your feature request related to a problem? Please describe.**
Though I'm sure it's not the most heavily-read guide in the world, it would be a good idea to add a note somewhere in the contributing file that edits only need to be made to the individual script files, because the Install files are auto-generated. I don't know where it should go, or the best way to say it, but I've seen it happen enough times that it's a good idea.

**Describe the solution you'd like**
Clear instructions in the contributing file to not edit Install files.

**Describe alternatives you've considered**
Continued administrative overhead and a lot of unnecessary work for contributors.

**Are you ready to build the code for the feature?**
No, I'm not sure what the best place to put the instructions is, and the "voice" of the document should remain Brent's.

**Comment by BrentOzar** [comment]
I can't believe we didn't have it in there already! Great catch, fixed.
