### ISSUE TITLE
sp_BlitzCache fails on SSMS 19.3

### ISSUE THREAD

**Issue by alexkazinets** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3434]
sp_BlitzCache  @databasename='db_name'

Returns few rows and stops with following error :

An error occurred while executing batch. Error message is: Unexpected XML declaration. The XML declaration must be the first node in the document, and no white space characters are allowed to appear before it. Line 9, position 1717.

It works fine on SSMS 18.8 and 17.9.1

**Comment by BrentOzar** [comment]
Hi, Alex. When you create a new issue, there are several questions for you to fill in. Please don't delete those - actually fill 'em in. Thanks!
