### ISSUE TITLE
sp_BlitzCache fails when running on SSMS 19.3

### ISSUE THREAD

**Issue by alexkazinets** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3435]
**Version of the script**
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.

SELECT @Version = '8.18', @VersionDate = '20231222';

**What is the current behavior?**

Procedure fails with error  only on SSMS 19.3
sp_BlitzCache @databasename='db_name'

Returns 6 rows and stops with following error :

An error occurred while executing batch. Error message is: Unexpected XML declaration. The XML declaration must be the first node in the document, and no white space characters are allowed to appear before it. Line 9, position 1717.

**If the current behavior is a bug, please provide the steps to reproduce.**

I cannot provide the  stored procedure being executed.
Row 7 when executed on lower SSMS version returns pretty large stored procedure with it's plan.

**What is the expected behavior?**

On lower SSMS version it returns 10 rows.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Microsoft SQL Server 2019 (RTM-CU24) (KB5031908) - 15.0.4345.5 (X64)   Dec  4 2023 14:44:16   Copyright (C) 2019 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 

It works fine on SSMS 18.8 and 17.9.1

**Comment by BrentOzar** [comment]
In SSMS, go into Tools, Options, Query Results, SQL Server, Results to Grid. Set the XML Data size to Unlimited. Does that fix the issue?

**Comment by alexkazinets** [comment]
Setting the XML Data size to Unlimited did not fix the issue.
I also checked older SSMS - XM data is limited to 2MB.

**Comment by BrentOzar** [comment]
OK, gotcha. Here are the next troubleshooting steps I'd try:
* Run sp_BlitzCache without the @databasename parameter
* Run sp_BlitzCache with the @SkipAnalysis = 1 parameter
* Run sp_BlitzCache with the OnlyQueryHashes parameter, and pass in just the query hash that appears to be having the problems
* Run it with Debug = 1, and paste in the last message before the issue

I wish I could dig into this more deeply for you, but obviously this isn't something happening on my end.

**Comment by alexkazinets** [comment]
Run sp_BlitzCache without the @databasename parameter
It does not fail - this SP becomes line number 15
It does fail, once I rut it with
sp_BlitzCache @top=100

 sp_BlitzCache @SkipAnalysis = 1,@databasename='db_name'

Returns the data including stored procedure, but obviously without analysis.

sp_BlitzCache   @OnlyQueryHashes = '0x05000A001CEA3B50F06CE8480F02000001000000000000000000000000000000000000000000000000000000'

Fails with different error :

Msg 2628, Level 16, State 1, Procedure sp_BlitzCache, Line 1425 [Batch Start Line 11]
String or binary data would be truncated in table 'tempdb.dbo.#only_query_hashes__________________________________________________________________________________________________000000001858', column 'query_hash'. Truncated value: ''.

I run

sp_BlitzCache @OnlySqlHandles = '0x03000A001CEA3B50BA39810027B0000001000000000000000000000000000000000000000000000000000000', @debug=1

Error:

An error occurred while executing batch. Error message is: Unexpected XML declaration. The XML declaration must be the first node in the document, and no white space characters are allowed to appear before it. Line 9, position 1717.

Last message  -

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT  TOP (@Top)  DatabaseName AS [Database],
    QueryPlanCost AS [Cost],
    QueryText AS [Query Text],
    QueryType AS [Query Type],
    Warnings AS [Warnings],
	QueryPlan AS [Query Plan],
	missing_indexes AS [Missing Indexes],
	implicit_conversion_info AS [Implicit Conversion Info],
	cached_execution_parameters AS [Cached Execution Parameters],
    CONVERT(NVARCHAR(30), CAST((ExecutionCount) AS BIGINT), 1) AS [# Executions],
    CONVERT(NVARCHAR(30), CAST((ExecutionsPerMinute) AS BIGINT), 1) AS [Executions / Minute],
    CONVERT(NVARCHAR(30), CAST((PercentExecutions) AS BIGINT), 1) AS [Execution Weight],
    CONVERT(NVARCHAR(30), CAST((TotalCPU) AS BIGINT), 1) AS [Total CPU (ms)],
    CONVERT(NVARCHAR(30), CAST((AverageCPU) AS BIGINT), 1) AS [Avg CPU (ms)],
    CONVERT(NVARCHAR(30), CAST((PercentCPU) AS BIGINT), 1) AS [CPU Weight],
    CONVERT(NVARCHAR(30), CAST((TotalDuration) AS BIGINT), 1) AS [Total Duration (ms)],
    CONVERT(NVARCHAR(30), CAST((AverageDuration) AS BIGINT), 1) AS [Avg Duration (ms)],
    CONVERT(NVARCHAR(30), CAST((PercentDuration) AS BIGINT), 1) AS [Duration Weight],
    CONVERT(NVARCHAR(30), CAST((TotalReads) AS BIGINT), 1) AS [Total Reads],
    CONVERT(NVARCHAR(30), CAST((AverageReads) AS BIGINT), 1) AS [Avg Reads],
    CONVERT(NVARCHAR(30), CAST((PercentReads) AS BIGINT), 1) AS [Read Weight],
    CONVERT(NVARCHAR(30), CAST((TotalWrites) AS BIGINT), 1) AS [Total Writes],
    CONVERT(NVARCHAR(30), CAST((AverageWrites) AS BIGINT), 1) AS [Avg Writes],
    CONVERT(NVARCHAR(30), CAST((PercentWrites) AS BIGINT), 1) AS [Write Weight],
    CONVERT(NVARCHAR(30), CAST((AverageReturnedRows) AS BIGINT), 1) AS [Average Rows],
	CONVERT(NVARCHAR(30), CAST((MinGrantKB) AS BIGINT), 1) AS [Minimum Memory Grant KB],
	CONVERT(NVARCHAR(30), CAST((MaxGrantKB) AS BIGINT), 1) AS [Maximum Memory Grant KB],
	CONVERT(NVARCHAR(30), CAST((MinUsedGrantKB) AS BIGINT), 1) AS [Minimum Used Grant KB], 
	CONVERT(NVARCHAR(30), CAST((MaxUsedGrantKB) AS BIGINT), 1) AS [Maximum Used Grant KB],
	CONVERT(NVARCHAR(30), CAST((AvgMaxMemoryGrant) AS BIGINT), 1) AS [Average Max Memory Grant],
	CONVERT(NVARCHAR(30), CAST((MinSpills) AS BIGINT), 1) AS [Min Spills],
	CONVERT(NVARCHAR(30), CAST((MaxSpills) AS BIGINT), 1) AS [Max Spills],
	CONVERT(NVARCHAR(30), CAST((TotalSpills) AS BIGINT), 1) AS [Total Spills],
	CONVERT(NVARCHAR(30), CAST((AvgSpills) AS MONEY), 1) AS [Avg Spills],
    PlanCreationTime AS [Created At],
    LastExecutionTime AS [Last Execution],
	LastCompletionTime AS [Last Completion],
	PlanHandle AS [Plan Handle], 
	SqlHandle AS [SQL Handle], 
    COALESCE(SetOptions, '') AS [SET Options],
	QueryHash AS [Query Hash],
	PlanGenerationNum,
	[Remove Plan Handle From Cache]

FROM    ##BlitzCacheProcs
WHERE   SPID = @spid 
 AND ExecutionCount >= @MinimumExecutionCount 
 ORDER BY  TotalCPU  DESC  OPTION (RECOMPILE) ;

**Comment by BrentOzar** [comment]
@alexkazinets OK, great! Like I mentioned earlier, going into this level of details is beyond what I can do for free from here, and I hope that's fair.

The good news is that you now know that you can run it with @SkipAnalysis = 1, and it runs successfully on your machine. That means there's something about that particular long stored proc that's failing during the analysis phase.

Your options are:
* Run it in SSMS 19.3 with SkipAnalysis = 1
* Run it in prior versions without SkipAnalysis = 1
* Run it in SSMS 19.3 with Debug = 1, and work through the code yourself to find out where it's failing on your particular query

I'm going to close this for now, but if there's a specific, focused question that you have on it, feel free to add another note. This just isn't something other folks will be able to debug for you remotely.
