### ISSUE TITLE
sp_Blitz v 52 (Jun 02 2016) saying SQL Server 2008 R2 SP3 unsupported

### ISSUE THREAD

**Issue by keypersltd** [BrentOzarULTD/SQL-Server-First-Responder-Kit#344]
Hi, when running v52 of sp_Blitz on client production servers it states that SQL Server 2008 R2 Sp3 is unsupported and I should apply a service pack.  There are no more SP's for this version of SQL, and when it says "unsupported" does it mean main stream support has ended or extended support. Should the text say apply the latest hotfix or CU instead.

Cheers (and thanks sp_blitz is a great tool)

Scott

**Comment by BrentOzar** [comment]
Good catch! Fixed in the dev branch. Was:
(@ProductVersionMajor = 10.5 AND @ProductVersionMinor <= 6000)

Is now:
(@ProductVersionMajor = 10.5 AND @ProductVersionMinor < 6000)

**Comment by keypersltd** [comment]
Thanks Brent!

**Comment by BrentOzar** [comment]
You bet, thanks for opening the issue.
