### ISSUE TITLE
The Documentation for sp_BlitzQueryStore Seems Confused About its Purpose.

### ISSUE THREAD

**Issue by ReeceGoding** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3440]
**Is your feature request related to a problem? Please describe.**
This cropped up as part of my pull request #3439. To my knowledge, there are five sources of official commentary for `sp_BlitzQueryStore`. Let's review what each of them say.

### [Introducing sp_BlitzQueryStore](https://www.brentozar.com/archive/2017/06/introducing-sp_blitzquerystore/)

> I set out to write a stored procedure that does for [Query Store (BOL)](https://docs.microsoft.com/en-us/sql/relational-databases/performance/monitoring-performance-by-using-the-query-store) what sp_BlitzCache does for the plan cache, but with a new approach.

> When you run sp_BlitzQueryStore, it basically:
> 
>  * Looks at your workloads over the last 7 days (that’s configurable)
>  * Finds the highest resource consuming periods of time
> * Finds the top 3 queries that used the most of that resource in that time (the top is configurable)

### [sp_BlitzQueryStore: A Gentle Introduction](https://www.brentozar.com/archive/2017/12/sp_blitzquerystore-gentle-introduction/)

>  I could have just dropped a copy of sp_BlitzCache for Query Store, but I wanted to do things a little bit more differenter’ly.
> 
>  Given the relative instability of the plan cache, the sorting by a single metric and all that totally makes sense. It’s short term.
> 
> Query store gives you a much longer history, so we have the ability to find what was going on when your server was at it’s worst by every metric.

### [@Help = 1](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzQueryStore.sql#L125C1-L126C68)

> This script displays your most resource-intensive queries from the Query Store, and points to ways you can tune these queries to make them faster.

### [The First Responder Kit Table of Contents](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit#sql-server-first-responder-kit)

> sp_BlitzQueryStore: Like BlitzCache, for Query Store

### [The Actual Documentation](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit#sp_blitzquerystore-how-has-a-query-plan-changed-over-time)

> sp_BlitzQueryStore: How Has a Query Plan Changed Over Time
> 
> Analyzes data in Query Store schema (2016+ only) in many similar ways to what sp_BlitzCache does for the plan cache.

From the above, I see three different explanations for what `sp_BlitzQueryStore` is trying to do:

1. Find which _time periods_ were the most expensive and tell you what queries were the worst in those periods.
2. Find which _queries_ are the most resource intensive, and tell you how to tune them. This seems to be the corresponding explanation to saying that it mimics `sp_BlitzCache`.
3. Track how _a query plan_ has changed over time.

**Describe the solution you'd like**
I would like answers to the following two questions, perhaps with the readme and `@Help` output updated to reflect them.

- What is `sp_BlitzQueryStore` _intended_ to do?
- What is `sp_BlitzQueryStore` _actually doing_?

Asking both of these may seem petty, but I worry that the output of the procedure is as confused as I'm claiming the documentation is. The elements inspired by `sp_BlitzCache` are trying to follow explanation 2 (e.g. the `@MinimumExecutionCount` and `@top` parameters as well as warning about problems with the query), but returning multiple rows per query (not per plan) contradicts this goal while following explanation 3.  Similarly, my ability to get 221 rows out of a call with `@top = 1` passed in suggests that explanation 1 and 3 are fighting each other. I'm clearly not getting a review of my most expensive time periods if I've only asked for one row per issue per period and you've given me 221 rows. Instead, you've probably given me a history of metrics for plans.

**Describe alternatives you've considered**
I've wondered if  `sp_BlitzQueryStore` needs a `@Mode` parameter or to be split in to multiple procedures. It's fine if it wants to do multiple jobs at once, but not if they're all outputted to the same table.

**Are you ready to build the code for the feature?**
Afraid not. This is a decision for the big shots.

**Comment by BrentOzar** [comment]
Yes, Reece, this does seem petty. ;-) Closing.
