### ISSUE TITLE
Latest version of sp_BlitzIndex fails on SQL 2014

### ISSUE THREAD

**Issue by Brianc-DBA** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3452]
**Version of the script**
20240222

**What is the current behavior?**
The following errors occur:
Msg 156, Level 15, State 1, Procedure sp_BlitzIndex, Line 1434 [Batch Start Line 13]
Incorrect syntax near the keyword 'if'.
Msg 156, Level 15, State 1, Procedure sp_BlitzIndex, Line 1452 [Batch Start Line 13]
Incorrect syntax near the keyword 'if'.

Double-clicking on the error will take you to the following lines of the code in sp_blitzIndex:
-- first error:
DROP TABLE if exists #dm_db_partition_stats_etc
-- second error:
drop TABLE if exists #dm_db_index_operational_stats

**If the current behavior is a bug, please provide the steps to reproduce.**
Either:
- Running all scripts at once by parsing or executing Install-Core-Blitz-No-Query-Store.sql (since Query Store is also 2016+), or
- Parsing or executing the new script for sp_BlitzIndex.sql

**What is the expected behavior?**
Upon success, sp_BlitzIndex or Install-Core-Blitz... should parse and execute without error.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Only fails in SQL 2014, since 'DROP TABLE IF EXISTS' was introduced in SQL Server 2016.  OS version does not factor in.

**Comment by stanom** [comment]
I have exactly the same problem by installing [Install-Core-Blitz-No-Query-Store.sql (v. 2024-02-02)](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/20240222/Install-Core-Blitz-No-Query-Store.sql) on SQL Server 2014.

### The solution could be:

##### to replace the code on the line nr. 21541:
> from:
```
           DROP TABLE if exists #dm_db_partition_stats_etc
```
> to:
```
           IF OBJECT_ID('tempdb..#dm_db_partition_stats_etc') IS NOT NULL
               DROP TABLE #dm_db_partition_stats_etc;
```

##### to replace the code on the line nr. 21559:
> from:
```
           drop TABLE if exists #dm_db_index_operational_stats
```
> to:
```
           IF OBJECT_ID('tempdb..#dm_db_index_operational_stats') IS NOT NULL
               DROP TABLE #dm_db_index_operational_stats;
```

**Comment by stanom** [comment]
fixed in https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/3453

**Comment by Brianc-DBA** [comment]
Great work!

**Comment by Raspberryfloof** [comment]
Simply making the changes in @stanom's post above does not work for me on SQL Server 2014 either.  While sp_BlitzIndex will install, running it fails with the following error:

```
Failure populating temp tables.
Last @dsql: 
                        DECLARE @d VARCHAR(19) = CONVERT(VARCHAR(19), GETDATE(), 121)
                        RAISERROR (N'start getting data into #dm_db_partition_stats_etc at (null)',0,1, @d) WITH NOWAIT;
                        SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
                        INSERT INTO #dm_db_partition_stats_etc
                        (
                            database_id, object_id, sname, index_id, partition_number, partition_id, row_count, reserved_MB, reserved_LOB_MB, reserved_row_overflow_MB, lock_escalation_desc, data_compression_desc
                        )
                        SELECT  200 AS database_id,
                                ps.object_id, 
                                s.name as sname,
                                ps.index_id, 
                                ps.partition_number, 
                                ps.partition_id,
                                ps.row_count,
                                ps.reserved_page_count * 8. / 1024. AS reserved_MB,
                                ps.lob_reserved_page_count * 8. / 1024. AS reserved_LOB_MB,
                                ps.row_overflow_reserved_page_count * 8. / 1024. AS reserved_row_overflow_MB,
                                le.lock_escalation_desc,
                            par.data_compression_desc 

            FROM    [EXAMPLE_DATABASE].sys.dm_db_partition_stats AS ps  
                    JOIN [EXAMPLE_DATABASE].sys.partitions AS par on ps.partition_id=par.partition_id
                    JOIN [EXAMPLE_DATABASE].sys.objects AS so ON ps.object_id = so.object_id
                               AND so.is_ms_shipped = 0 /*Exclude objects shipped by Microsoft*/
                               AND so.type <> 'TF' /*Exclude table valued functions*/
                    JOIN [EXAMPLE_DATABASE].sys.schemas AS s ON s.schema_id = so.schema_id
                        OUTER APPLY (SELECT st.lock_escalation_desc
                                     FROM [EXAMPLE_DATABASE].sys.tables st
                                     WHERE st.object_id ...
Msg 50000, Level 16, State 1, Procedure sp_BlitzIndex, Line 2369 [Batch Start Line 0]
EXAMPLE_DATABASE database failed to process. Invalid column name 'hobt_id'.

```

**Comment by BrentOzar** [comment]
Hi folks! I've corrected a few 2014 compatibility issues in the dev branch. You can try this version of the code to see if it works on your systems:

https://raw.githubusercontent.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/dd500ba03df3d108d29cc0c0c9d10bb374203d77/sp_BlitzIndex.sql

Those changes will be in the next First Responder Kit release.
