### ISSUE TITLE
sp_BlitzIndex can't be created in databases with old compat levels (2008/prior)

### ISSUE THREAD

**Issue by Dbawhiteley** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3456]
**Version of the script**
8.19

**What is the current behavior?**
BUG

**If the current behavior is a bug, please provide the steps to reproduce.**
Install the script on SQL 2016 - get the following error: 
Msg 156, Level 15, State 1, Procedure sp_BlitzIndex, Line 1434 [Batch Start Line 13]
Incorrect syntax near the keyword 'if'.
Msg 156, Level 15, State 1, Procedure sp_BlitzIndex, Line 1452 [Batch Start Line 13]
Incorrect syntax near the keyword 'if'.

**What is the expected behavior?**
The SP gets created.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2016 is failing and the only one that I tested. 

These statements : 
DROP TABLE if exists #dm_db_partition_stats_etc

Need to done in the version friendly way: 
IF OBJECT_ID('tempdb..#dm_db_partition_stats_etc') IS NOT NULL 
    DROP TABLE #dm_db_partition_stats_etc

**Comment by BrentOzar** [comment]
Howdy. This can happen if you're using a really old compatibility level. You can either change the code (and a pull request is fine - check the contribution guide) or install the scripts in a current compat level database.

Do you want to contribute a pull request?

**Comment by iguypouf** [comment]
This same line still fails on 2012 compatibility (110)

**Comment by BrentOzar** [comment]
@iguypouf yes, did you want to submit a pull request to change that?

**Comment by iguypouf** [comment]
I, not yet, because when this change applied I still have another error under enquiry right now.

"Msg 50000, Level 16, State 1, Procedure sp_BlitzIndex, Line 2370
database failed to process. Invalid column name 'hobt_id'.

My comment was more to help you to rename the issue title accordingly.
