### ISSUE TITLE
Stop sp_BlitzQueryStore returning the "rn" column

### ISSUE THREAD

**Issue by ReeceGoding** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3459]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I see the `rn` column in the first table of the `sp_BlitzQueryStore` output. I see no reason for it. I was hoping that reading [the code](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzQueryStore.sql#L4678) would explain it, but the only explanation that I'm seeing is that it's a product of `SELECT *`.

**Describe the solution you'd like**
Just get rid of it!

**Describe alternatives you've considered**
Praying that somebody here will enlighten me and explain why it's useful.

**Are you ready to build the code for the feature?**
Yes. It looks like a very easy job.

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, merging into the dev branch, will be in the next release with credit to you in the release notes. Sorry that it took me a while to get to this!
