### ISSUE TITLE
sp_BlitzIndex - Skip missing index details for Modes 1 and 2

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3462]
**Is your feature request related to a problem? Please describe.**
Gathering missing index details can be time consuming on some servers (another issue about that to come), but it doesn't make sense to run this part at all in modes that don't do any analysis or return those results. 

**Describe the solution you'd like**
Skip missing index details if using Mode 1 or 2.

**Describe alternatives you've considered**
Waiting. Endless... waiting.

**Are you ready to build the code for the feature?**
Sure thing skipperoo.

**Comment by BrentOzar** [comment]
I'm glad you did this because I've actually wondered in the past, "Are we gathering the data for every mode, every time?" and not gone into the code to look. Doh!

**Comment by erikdarlingdata** [comment]
@BrentOzar Yeah, looking through all the code, I was surprised at how many checks were completely unrelated. The only one I'm not entirely sure of is ForeignKeys. IndexSanity gets updated using that table, so I left it alone for now.
