### ISSUE TITLE
sp_BlitzQueryStore: There are lots of user-facing double spaces, missing spaces, typos, and twice-terminated sentences. 

### ISSUE THREAD

**Issue by ReeceGoding** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3472]
**Version of the script**
`@Version = '8.19', @VersionDate = '20240222';`

**What is the current behavior?**
The text output of `sp_BlitzQueryStore` is in need of a proofread. It has:

- Missing spaces (e.g. ["warnings,if"](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzQueryStore.sql#L310) and ["specified ([%s])is"](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzQueryStore.sql#L515))
- Double spaces (e.g. [the Wait stats DMV notice](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzQueryStore.sql#L539), [the query_store_runtime_stats columns notice](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzQueryStore.sql#L576), and [the PSP notice](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzQueryStore.sql#L599)).
- Twice-terminated sentences (e.g. [here](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzQueryStore.sql#L4921) and [here](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzQueryStore.sql#L4934), both reading "parallelism!.") 
- Typos  (e.g. ["specfic"](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzQueryStore.sql#L3721), ["cardinlity"](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzQueryStore.sql#L5248), and ["copasetic"](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzQueryStore.sql#L419)). 

This is very noticeable when paying attention to the printed outputs, the summary table, or trying to debug.

**If the current behavior is a bug, please provide the steps to reproduce.**
A few of these always appear when running the procedure on the happy path, but you don't need to run the code to see these issues. They're obvious from the source.

**What is the expected behavior?**
No double spaces, missing spaces, typos, and twice-terminated sentences. 

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
This is not version dependent.

**Are you ready to build the code for the feature?**
 I've already done it. I just need to split it out from a PR where I got carried away and changed too much.

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, merging into the dev branch, will be in the next release with credit to you in the release notes. Sorry that it took me a while to get to this!
