### ISSUE TITLE
sp_BlitzQueryStore: Replace TOP X with TOP (X)

### ISSUE THREAD

**Issue by ReeceGoding** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3476]
**Is your feature request related to a problem? Please describe.**
I recall that `SELECT TOP 1` is considered a bad habit, flagged by some tools, and is on some deprecation list somewhere. I also recall that `SELECT TOP (1)` is preferred. However, the former is seen a few times in `sp_BlitzQueryStore`.

**Describe the solution you'd like**
Replace `TOP X` with `TOP (X)`.

**Describe alternatives you've considered**
Nothing. Fixing this is effortless.

**Are you ready to build the code for the feature?**
 I've already done it. I just need to split it out from a PR where I got carried away and changed too much.

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, merging into the dev branch, will be in the next release with credit to you in the release notes. Sorry that it took me a while to get to this!
