### ISSUE TITLE
sp_BlitzQueryStore: Several of the temp tables don't have comments.

### ISSUE THREAD

**Issue by ReeceGoding** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3478]
**Is your feature request related to a problem? Please describe.**
When you read through the code for `sp_BlitzQueryStore`, it's pretty obvious that its author intended for all of the temp tables to have comments explaining what they are for. However, some of them are lacking any comments. Namely, these are:

- [#working_wait_stats](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzQueryStore.sql#L915)
- Four of the tables following _"[The next three tables hold plan XML parsed out to different degrees](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzQueryStore.sql#L958)"_. I think that "three" should have been "seven".
- [#warning_results](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzQueryStore.sql#L1048)

**Describe the solution you'd like**
Just add in some basic comments. More comprehensive explanations, if needed, can come later.

**Describe alternatives you've considered**
None have come to mind. I've consistently been of the opinion that `sp_BlitzQueryStore` doesn't do enough to explain what it does. That opinion didn't change after reading the code from top to bottom. This is a small first step towards fixing that.

**Are you ready to build the code for the feature?**
 I've already done it. I just need to split it out from a PR where I got carried away and changed too much.

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, merging into the dev branch, will be in the next release with credit to you in the release notes. Sorry that it took me a while to get to this!
