### ISSUE TITLE
sp_BlitzQueryStore: What is this comment trying to say?

### ISSUE THREAD

**Issue by ReeceGoding** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3480]
**Is your feature request related to a problem? Please describe.**
At [this point](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzQueryStore.sql#L2882C1-L2888C3) in `sp_BlitzQueryStore`'s code, we have the following:
```sql
/*
This looks for queries in the query stores that we picked up from an internal that have multiple plans in cache

This and several of the following queries all replaced XML parsing to find plan attributes. Sweet.

Thanks, Query Store
*/

RAISERROR(N'Populating object name in #working_warnings', 0, 1) WITH NOWAIT;
UPDATE w
SET    w.proc_or_function_name = ISNULL(wm.proc_or_function_name, N'Statement')
FROM   #working_warnings AS w
JOIN   #working_metrics AS wm
ON w.plan_id = wm.plan_id
   AND w.query_id = wm.query_id
OPTION (RECOMPILE);


RAISERROR(N'Checking for multiple plans', 0, 1) WITH NOWAIT;

SET @sql_select = N'SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;';
SET @sql_select += N'
UPDATE ww
SET ww.plan_multiple_plans = 1
FROM #working_warnings AS ww
JOIN 
(
SELECT wp.query_id, COUNT(qsp.plan_id) AS  plans
FROM   #working_plans AS wp
JOIN   ' + QUOTENAME(@DatabaseName) + N'.sys.query_store_plan AS qsp
ON qsp.plan_id = wp.plan_id
   AND qsp.query_id = wp.query_id
JOIN   ' + QUOTENAME(@DatabaseName) + N'.sys.query_store_query AS qsq
ON wp.query_id = qsq.query_id
JOIN   ' + QUOTENAME(@DatabaseName) + N'.sys.query_store_query_text AS qsqt
ON qsqt.query_text_id = qsq.query_text_id
JOIN   ' + QUOTENAME(@DatabaseName) + N'.sys.query_store_runtime_stats AS qsrs
ON qsrs.plan_id = wp.plan_id
WHERE    1 = 1
    AND qsq.is_internal_query = 0
	AND qsp.query_plan IS NOT NULL
	';

SET @sql_select += @sql_where;

SET @sql_select += 
N'GROUP BY wp.query_id
  HAVING COUNT(qsp.plan_id) > 1
) AS x
    ON ww.query_id = x.query_id
OPTION (RECOMPILE);
';
```

What is 

> This looks for queries in the query stores that we picked up from an internal that have multiple plans in cache

trying to say? The "_from an internal that_" part sounds like a word is missing, but I cannot think of any such word. Furthermore, what cache are we talking about? I'm pretty sure that everything in the above code is only hitting Query Store's views; Nothing is referencing the plan cache.

**Describe the solution you'd like**
Someone to suggest what this comment should read. Currently, my best idea is

>  This looks for queries that have multiple plans 

but I become suspicious when my best idea for fixing something is to destroy half of it.

**Describe alternatives you've considered**
I thought about leaving this alone, but it's the only comment in the entire procedure that totally dead-ends me. I'm convinced that I understand the rest.

The questionable comment is even making me question the code itself. Surely you're going to wrongly flag a lot of things as having multiple plans if your count is dependent on a join to `query_store_runtime_stats`? I'll look in to that later.

**Are you ready to build the code for the feature?**
It's only writing a comment. I'm quite prepared to do that, but I can't figure out what it should say.

**Comment by erikdarlingdata** [comment]
@ReeceGoding I may have not been feeling 100% myself when I wrote that comment 🥴

It should probably be something like: 

> This looks for queries in the results so far that have multiple plans in Query Store.

The rest of that comment is sort of useless, but at the time I was happy that Query Store logged certain plan attributes in columns, where they had to be parsed out of the plan XML in `sp_BlitzCache`. It made doing the checks simpler.

**Comment by ReeceGoding** [comment]
Thanks @erikdarlingdata . While we're on the topic of this code block, is there any chance that the `COUNT(qsp.plan_id)` part should be `COUNT(DISTINCT qsp.plan_id)`? I need to take a closer look at it, but my intuition won't shut up about it.

**Comment by erikdarlingdata** [comment]
@ReeceGoding maybe, but I haven't looked at this procedure in about 5 years.
