### ISSUE TITLE
sp_BlitzQueryStore: The "multiple plans" warning flags up even when you only have one plan.

### ISSUE THREAD

**Issue by ReeceGoding** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3485]
Just picking some fruit that I thought was low hanging from a discussion that came up in #3480 . Unfortunately, it is just slightly out of my reach.

**Version of the script**
8.18

**What is the current behavior?**
[The multiple plans check](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzQueryStore.sql#L2882) flags up even for queries that only have one plan. I suspect the underlying issue is that the reference to `sys.query_store_runtime_stats` makes a given plan be counted extra times if said plan occurs in multiple of Query Store's statistics collection intervals. 

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Make a new database. I've never figured out the minimum amount of code needed to do this, so just do it in your preferred way.
2. Enable Query Store. For this example, it is best to use
```sql
ALTER DATABASE [Your_New_DB]
SET QUERY_STORE = ON
(
    OPERATION_MODE = READ_WRITE,
    QUERY_CAPTURE_MODE = ALL,
    INTERVAL_LENGTH_MINUTES = 1
);
```
3. Run a query in your new database that will be captured by Query Store. I did `select * from sys.tables`.
4. Wait your `INTERVAL_LENGTH_MINUTES` (a minute, in the above case).
5. Run your query again.
6. Run `sp_BlitzQueryStore` for the database in question.
7. Find your query in the output. Given that the database is brand new, it should be there.
8. Observe that it only has one `plan_id`, but has "Multiple Plans" listed in its `warnings` column.

For what it's worth, I find this bug staring me in the face every time that I run `sp_BlitzQueryStore` on an active database. If you're as unlucky as I, then you may be able to skip the above steps by simply running the procedure on a handy QS-enabled database and carefully reading the output.

**What is the expected behavior?**
Presumably, "multiple plans" should only flag up when a given `query_id` has several corresponding `plan_ids`.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
I doubt that this is version dependent.

**Are you willing to fix this yourself?**
I'm unfortunately unsure about the requirements. I thought that it was as simple as making the `HAVING COUNT(qsp.plan_id)` [line](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzQueryStore.sql#L2929) in to a distinct count but my experiments in this area have given surprising results. That change certainly removes the false positives. However, you only seem to get a true positive for cases where a query has multiple plans within the same Query Store statistics collection interval. For example, if your collection interval is one hour, then it appears that you will never get a multiple plans warning for a query that runs once an hour but with a different plan each time; You only get the warning if you have different plans for the same query within the same hour. If this is the behaviour that we want, then I'm happy to submit the PR. Otherwise, this needs discussing.

**Comment by BrentOzar** [comment]
@ReeceGoding I have to be honest here: no one's really maintaining sp_BlitzQueryStore. @erikdarlingdata has moved on to start his own company, and he's got an excellent Query Store proc here: https://erikdarling.com/sp_quickiestore/

That's why there isn't really any discussion here. I've been debating whether to deprecate sp_BlitzQueryStore, and I think this is going to be the issue that pushes me over the edge, heh. I'm going to leave it in the FRK for the rest of the year, but announce its deprecation in the next release, and point people over towards Erik's query instead. I'll move sp_BlitzQueryStore over into the Deprecated folder in the first 2025 calendar year release.

**Comment by ReeceGoding** [comment]
@BrentOzar I must agree with the decision. Like you, I'll be honest here. The truth is that I've had my suspicions about `sp_BlitzQueryStore` for a while. My to-do list is – soon to be "was" – filled with things to investigate. Every time I looked in to something, I'd find yet more things that screamed that it was little more than a first draft and left me with low hanging fruit to grab.

I've also turned to `sp_QuickieStore` and think it needs more publicity. Investigating what `sp_BlitzQueryStore` does that `sp_QuickieStore` doesn't was on my to-do list. The only feature that I'm sure is missing is the plan analysis parts of `sp_BlitzQueryStore`. If there's a gap in the Query Store market, it's probably there. It's a shame that we can't just point `sp_BlitzCache`'s plan analysis tools to a Query Store plan somehow.

For peace of mind, here are my top five reasons for supporting your decision. 
1. `sp_BlitzQueryStore` is slow. I've seen it run for half an hour before.
2. It has lots of little things that make it obvious that it sees little maintenance. I did my best to report and patch those out (e.g. typos, double spaces, repeated prints, useless columns, etc), but they should have been spotted years ago.
3. I'm not convinced that there is any documentation on `sp_BlitzQueryStore` that accurately describes what it does. [I've ranted about this before](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/3440), but the problem became even clearer when I started looking at the code. For example, there is a major step that aggregates many things by day but none of the docs even as much as hint at daily aggregation.
4. What it returns even with sensible choices of parameters is simply overwhelming. This is true even if you set the parameters to lower the number of returned rows.
5. It quite obviously isn't getting used. Search the internet for `sp_BlitzQueryStore` and you will find shockingly little. Conversely, you can find other items in the First Responder Kit on job openings.
