### ISSUE TITLE
Missing entry in master.dbo.SqlServerVersions table

### ISSUE THREAD

**Issue by BukowskiArtur** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3506]
Looks like the latest SQL Server 2016 SP3-CU1-GDR minor version number 7029 is missing in the master.dbo.SqlServerVersions table.
Attached screenshot.

![2016-SP3-CU1-GDR](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/47842721/22e1ed62-1f28-4bc9-8796-4c8e9e5e6c6e)

**Comment by BrentOzar** [comment]
Yes, correct, I don't put every individual build like GDRs into SqlServerVersions. If it's important to you, you're welcome to do a pull request adding the versions you want. Thanks!
