### ISSUE TITLE
sp_BlitzFirst: Wait Stats Details does not display correct number of seconds that the server spent waiting

### ISSUE THREAD

**Issue by aroques** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3507]
**Version of the script**
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.

```sql
SELECT @Version = '8.19', @VersionDate = '20240222';
```

**What is the current behavior?**
This `Details` of the Wait Stats finding displays the `@Seconds` variable for how long that the server spent waiting on a particular wait (the default is 5 as shown below):
![image](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/18602501/28c88b55-6c57-47ae-baa4-e15334a075d8)

**If the current behavior is a bug, please provide the steps to reproduce.**
Run `sp_BlitzFirst` on a server busy enough that it takes longer than `@Seconds` to run.

**What is the expected behavior?**
This `Details` of the Wait Stats finding should display the number of seconds that it actually spent waiting which in the above example is 122 seconds.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
**Product:** Microsoft SQL Server Enterprise: Core-based Licensing (64-bit)
**Operating System:** Windows Server 2016 Standard (10.0)
**Version:** 14.0.3465.1

**Comment by BrentOzar** [comment]
It does. Do a search in the code for "over the last" and you'll see the relevant portions:

        'For ' + CAST(((wNow.wait_time_ms - COALESCE(wBase.wait_time_ms,0)) / 1000) AS NVARCHAR(100)) + ' seconds over the last ' + CASE @Seconds WHEN 0 THEN (CAST(DATEDIFF(dd,@StartSampleTime,@FinishSampleTime) AS NVARCHAR(10)) + ' days') ELSE (CAST(@Seconds AS NVARCHAR(10)) + ' seconds') END + ', SQL Server was waiting on this particular bottleneck.' + @LineFeed + @LineFeed AS Details,

If you believe that's incorrect, can you send a screenshot that includes these 3 things:
* The exact parameters used for sp_BlitzFirst
* The result sets
* The duration at the bottom right of sp_BlitzFirst
Thanks!

**Comment by aroques** [comment]
Exact parameters are none so they are defaulted. 
`@Seconds` defaults to 5 so the 0 seconds case does not get hit.
The result set and duration are shown in the screenshot.

**Comment by aroques** [comment]
Here's a complete screenshot if you prefer:
![image](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/18602501/fe84108b-a93b-4251-a5a9-48b8be106d94)

**Comment by BrentOzar** [comment]
HAHAHA, twelve minutes, good Lord, that's bad. OK, cool, I'll reopen this and get that in, heh.

**Comment by BrentOzar** [comment]
Fixed! Here's a screenshot showing the server under load.
![Screenshot 2024-05-01 at 6 56 12 AM](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/245462/a0e640ac-4f46-47e8-a5cf-10bbb3c34d78)
