### ISSUE TITLE
sp_BlitzIndex - @GetAllDatabases = 1, @Mode = 2 output isn't sorted

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#351]
Sort alphabetically by Database Name, Schema Name, Object Name, Index Name.

**Comment by BrentOzar** [comment]
Current example output.
![1](https://cloud.githubusercontent.com/assets/245462/16563752/6c6bbce6-41c9-11e6-9d5e-1e0eea0c064c.png)

**Comment by BlitzErik** [comment]
Fixed in Pull Request #369
