### ISSUE TITLE
Name column from sys.schemas accessed using [NAME] rather than [name]

### ISSUE THREAD

**Issue by garyhuntddn** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3515]
**Version of the script**
dev branch

**What is the current behavior?**
Query uses ```NAME``` column rather than ```name```

See the fix in #3513 - it's a simple typo that can be corrected.

**If the current behavior is a bug, please provide the steps to reproduce.**
Attempt to execute where the sys.schemas table has a case-sensitive collation

**What is the expected behavior?**
As per the dev guidelines - collation should be taken into account and work across collations

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
all versions as far as I can tell

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, merging into the dev branch, will be in the next release with credit to you in the release notes.
