### ISSUE TITLE
Can DB_NAME() ever return a different value to sys.databases.name?

### ISSUE THREAD

**Issue by garyhuntddn** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3517]
**Version of the script**
dev branch

**What is the current behavior?**
One query uses DB_NAME(), and another uses sys.databases.name and these two results are used for exclusions. It's unlikely that DB_NAME will return a different result (but why use different techniques?)

**If the current behavior is a bug, please provide the steps to reproduce.**
See #3510 for a fix

**What is the expected behavior?**
Consistent behaviour of results

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
v2022 on Win and Linux but should effect all versions

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, merging into the dev branch, will be in the next release with credit to you in the release notes.
