### ISSUE TITLE
Typos in the index script

### ISSUE THREAD

**Issue by garyhuntddn** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3519]
**Version of the script**
dev branch

**What is the current behavior?**
Spelling mistakes:
paritions vs partitions
sequental vs sequential
partioned vs partitioned

**If the current behavior is a bug, please provide the steps to reproduce.**
See the code and #3518 for the fixes

**What is the expected behavior?**
Correct spelling :-)

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
all versions

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, merging into the dev branch, will be in the next release with credit to you in the release notes.
