### ISSUE TITLE
README.md: sp_AllNightLog is still in the table of contents

### ISSUE THREAD

**Issue by ReeceGoding** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3529]
I'll skip filling out the template on this one. The title of the issue says it all.

**Comment by jrsteele23** [comment]
I was about to add this same issue. I'm not sure if the tables of contents needs to be updated or if the original content for that section accidentally got removed...

**Comment by ReeceGoding** [comment]
@jrsteele23 See https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/releases/tag/20240522

**Comment by BrentOzar** [comment]
Thanks for the pull request! I did one myself just because I also wanted to update the readme file in the deprecated folder.
