### ISSUE TITLE
brentozar.com/blitz/query-store-disabled/ Still Recommends sp_BlitzQueryStore

### ISSUE THREAD

**Issue by ReeceGoding** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3534]
Not sure where else to mention this.

**Version of the script**
N/A

**What is the current behavior?**
`sp_BlitzQueryStore` is still recommended by https://www.BrentOzar.com/go/querystore even though that procedure is deprecated. We link to this page from `sp_Blitz`.

**If the current behavior is a bug, please provide the steps to reproduce.**
N/A

**What is the expected behavior?**
It shouldn't be mentioned.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
N/A

**Comment by BrentOzar** [comment]
Good catch! Pointed it over to Erik's sp_QuickieStore.
