### ISSUE TITLE
sp_BlitzFirst - add SQL login to what's running now output

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#354]
When @ExpertMode = 1, we show what's running now at the start & end of the run. The results include NT logins, but not SQL logins.

**Comment by BlitzErik** [comment]
Taking care of this

**Comment by BlitzErik** [comment]
Fixed here: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/357
