### ISSUE TITLE
Add Point In Time restore parameter

### ISSUE THREAD

**Issue by pge92** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3544]
Hi, 
First thank you for your restore script that is very helpfull for restoring the backups made by hallengren scripts

**Is your feature request related to a problem? Please describe.**
I would like how we can restore a database from 'a past point in time' and not from the latest backup (modulo the StopAt timestamp beetween the last backup Full/Diff and NOW). 

**Describe the solution you'd like**
is there a way to launch the restore command or to add a parameter to start a Point In Time restore ? in the backup folder there are many FULL backupset but i have sometimes to restore from an older than the latest backupset

**Describe alternatives you've considered**
as a workaround i have to move the concerned FULL .bak files to a dedicated folder and write this specific path in the @BackupPathFull parameter. so that the procedure is forced to take these backup sets

**Are you ready to build the code for the feature?**
no i didn't tried yet. i have to find out how the procedure can choose the correct backupset according to the Point in time given

thank you for your help

**Comment by BrentOzar** [comment]
If you want to restore to an earlier full backup, you'll either want to do that manually, or put the full backup you want to use in a specific folder and restore from there.
