### ISSUE TITLE
sp_BlitzLock - Add max CPU and elapsed times to available plans section

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3545]
**Is your feature request related to a problem? Please describe.**
When you're looking at deadlocks, many queries may finish quickly, except when they deadlock. That might make the average time look somewhat odd. 

**Describe the solution you'd like**
Add max CPU and elapsed time to get a better sense of outlier execution metrics

**Describe alternatives you've considered**
Guessing

**Are you ready to build the code for the feature?**
It's already done

**Comment by erikdarlingdata** [comment]
@BrentOzar sorry, I goofed on this a little and forgot to branch from my local dev. Hopefully you can forgive me.

**Comment by BrentOzar** [comment]
Hahaha, that works. Github is still dark magic, hahaha.
