### ISSUE TITLE
sp_BlitzLock failed with a data conversion error

### ISSUE THREAD

**Issue by Aussie-Scum** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3547]
**Version of the script**
8.20 - dated 20240522 - downloaded today

**What is the current behavior?**

Installed sp_BlitzLock into master and executed it.  Last few lines of the output:

Update some nonsense part 2 Jun 26 2024  1:31:57:757PM
Finished at Jun 26 2024  1:31:57:757PM
Get Agent Job and Step names Jun 26 2024  1:31:57:770PM
Msg 245, Level 16, State 1, Line 2
Conversion failed when converting the nvarchar value 'SQLAgent - Job Manager' to data type int.

This SQL Server does have a LOT of SQL Server Agent jobs, don't know if that is a contributing factor here.

**If the current behavior is a bug, please provide the steps to reproduce.**

exec sp_BlitzLock

**What is the expected behavior?**

I would have expected it to finish and produce the output grid :)

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

This was run on SQL Server 2016 / MS Windows Server 2016 DataCenter Edition.  

Haven't run this before on this server but I have run sp_BlitzLock on other servers earlier this year that ran to completion.

**Comment by BrentOzar** [comment]
Can you run it with @Debug = 1, and copy/paste the contents of the messages pane from around where the error happens? Thanks!

**Comment by Aussie-Scum** [comment]
Working with a team in India who are the ones doing the keyboard driving, have messaged them, will get results for you ASAP.

**Comment by Aussie-Scum** [comment]
Full output from Debug:

@RDS = 0, updating #t with high row and page counts
@TargetSessionType is NULL, assigning for non-Azure instance
@TargetSessionType assigned as event_file for non-Azure
Grab the initial set of xml to parse at Jul  1 2024  8:30:55:323PM
Finished at Jul  1 2024  8:31:26:680PM
Initial Parse process and input buffer xml Jul  1 2024  8:31:26:680PM
Finished at Jul  1 2024  8:31:26:780PM
Final Parse process and input buffer xml Jul  1 2024  8:31:26:780PM
Finished at Jul  1 2024  8:31:27:140PM
Parse execution stack xml Jul  1 2024  8:31:27:140PM
Finished at Jul  1 2024  8:31:27:220PM
Grab the full resource list Jul  1 2024  8:31:27:220PM
Finished at Jul  1 2024  8:31:27:403PM
Parse object locks Jul  1 2024  8:31:27:410PM
Finished at Jul  1 2024  8:31:27:463PM
Parse page locks Jul  1 2024  8:31:27:463PM
Finished at Jul  1 2024  8:31:27:520PM
Parse key locks Jul  1 2024  8:31:27:520PM
Finished at Jul  1 2024  8:31:27:583PM
Parse RID locks Jul  1 2024  8:31:27:583PM
Finished at Jul  1 2024  8:31:27:620PM
Parse row group locks Jul  1 2024  8:31:27:620PM
Finished at Jul  1 2024  8:31:27:650PM
Fixing heaps in #deadlock_owner_waiter Jul  1 2024  8:31:27:650PM
Finished at Jul  1 2024  8:31:27:653PM
Parse parallel deadlocks Jul  1 2024  8:31:27:653PM
Finished at Jul  1 2024  8:31:27:723PM
Get rid of parallel noise Jul  1 2024  8:31:27:723PM
Finished at Jul  1 2024  8:31:27:730PM
Get rid of nonsense Jul  1 2024  8:31:27:730PM
Finished at Jul  1 2024  8:31:27:730PM
Update some nonsense part 1 Jul  1 2024  8:31:27:750PM
Finished at Jul  1 2024  8:31:27:770PM
Update some nonsense part 2 Jul  1 2024  8:31:27:770PM
Finished at Jul  1 2024  8:31:27:770PM
Get Agent Job and Step names Jul  1 2024  8:31:27:783PM

    UPDATE
        aj
    SET
        aj.job_name = j.name,
        aj.step_name = s.step_name
    FROM msdb.dbo.sysjobs AS j
    JOIN msdb.dbo.sysjobsteps AS s
      ON j.job_id = s.job_id
    JOIN #agent_job AS aj
      ON  aj.job_id_guid = j.job_id
      AND aj.step_id = s.step_id
    OPTION(RECOMPILE);
                 
Msg 245, Level 16, State 1, Line 2
Conversion failed when converting the nvarchar value 'SQLAgent - Job Manager' to data type int.

**Comment by BrentOzar** [comment]
Well, that's odd. Here's the relevant part of the code:

```
        ALTER TABLE
            #agent_job
        ADD
            job_name nvarchar(256),
            step_name nvarchar(256);

        IF
        (
                @Azure = 0
            AND @RDS = 0
        )
        BEGIN
            SET @StringToExecute =
                N'
    UPDATE
        aj
    SET
        aj.job_name = j.name,
        aj.step_name = s.step_name
    FROM msdb.dbo.sysjobs AS j
    JOIN msdb.dbo.sysjobsteps AS s
      ON j.job_id = s.job_id
    JOIN #agent_job AS aj
      ON  aj.job_id_guid = j.job_id
      AND aj.step_id = s.step_id
    OPTION(RECOMPILE);
                 ';

            IF @Debug = 1 BEGIN PRINT @StringToExecute; END;
            EXEC sys.sp_executesql
                @StringToExecute;
```


That rules out my hunch on what might be causing it, because we're updating columns that were clearly just set as NVARCHARs. 

I'm guessing the line causing it is actually the join from #agent_job to msdb.dbo.sysjobs:

```
    JOIN #agent_job AS aj
      ON  aj.job_id_guid = j.job_id
```

Because when we build #agent_job, we're getting the job_id_guid from here:

```
            job_id_guid =
                CONVERT
                (
                    uniqueidentifier,
                    TRY_CAST
                    (
                        N''
                        AS xml
                    ).value('xs:hexBinary(substring(sql:column("x.job_id"), 0))', 'binary(16)')

```

It's possible that there's a deadlock that has text TRY_CAST can't cast, perhaps? If you wanted to troubleshoot that more deeply, it'd require working directly on your server that's got the suspicious deadlock XML. Go into the code around line 1719 just after we do this:


```
ALTER TABLE
            #agent_job
        ADD
            job_name nvarchar(256),
            step_name nvarchar(256);
```

And then select out the contents of the #agent_job table. That way, you'll be able to see if there's anything in #agent_job.job_id_guid that isn't a guid, perhaps?

**Comment by BrentOzar** [comment]
@Aussie-Scum any word on this?

**Comment by Aussie-Scum** [comment]
I am sorry, I don't actually have access to this server, doing this as a third party resource at the moment while trying to get access to the server.   If I can't get access here soon, might have to close this out.   They've also recently migrated this database from SQL Server on a VM to what I believe is SQL Azure and I'm not sure your First Responder Kit works on Azure SQL Database ?  (I believe it did not used to anyway, unless you've enhanced it recently)

**Comment by BrentOzar** [comment]
Gotcha - I'm going to close it out then. Yes, the FRK works on Azure SQL DB. Cheers!
