### ISSUE TITLE
`sp_BlitzLock` Lock data

### ISSUE THREAD

**Issue by Imran-imtiaz48** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3548]
### Current Behavior:

Installed `sp_BlitzLock` into the master database and executed it. The output ends with the following lines:

```
Update some nonsense part 2 Jun 26 2024 1:31:57:757PM
Finished at Jun 26 2024 1:31:57:757PM
Get Agent Job and Step names Jun 26 2024 1:31:57:770PM
Msg 245, Level 16, State 1, Line 2
Conversion failed when converting the nvarchar value 'SQLAgent - Job Manager' to data type int.
```

This SQL Server instance has a large number of SQL Server Agent jobs, which might be contributing to the issue.

### Steps to Reproduce:

To reproduce this behavior, execute the following command:

```sql
exec sp_BlitzLock
```

### Expected Behavior:

The procedure should complete and produce the output grid.

### Affected Versions:

- SQL Server: 2016
- Operating System: MS Windows Server 2016 DataCenter Edition

This procedure has not been run on this server before but has completed successfully on other servers earlier this year.

**Comment by BrentOzar** [comment]
Hi! When you open an issue, there's a template with questions to fill out. Please don't delete questions - please fill them out so we can diagnose the issue. Thanks!
