### ISSUE TITLE
sp_DatabaseRestore: Document the other half of the parameters.

### ISSUE THREAD

**Issue by ReeceGoding** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3555]
**Is your feature request related to a problem? Please describe.**
By my count, `sp_DatabaseRestore` has 40 parameters and only 23 are in README.md. To figure out what they do, you either have to put complete faith in the parameter names or read the source code. You can figure out some of them from the commented examples in the  `@Help = 1`  text, but they're not all in there. My suggested feature is to document many more of the parameters in README.md than what is currently documented.

**Describe the solution you'd like**
Just stick them in README.md.

**Describe alternatives you've considered**
Updating the `@Help = 1` text with many more commented examples is a reasonable alternative, but it would be far more work.

**Are you ready to build the code for the feature?**
No. I'm not qualified. I've never used the procedure.

**Comment by BrentOzar** [comment]
@ReeceGoding - please check out the contributing guide here: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/main/CONTRIBUTING.md

If you'd like additional new things built here, you're welcome to do the work yourself, or you can commission (hire) someone else to do the work for you. Unfortunately, open source doesn't mean free work on demand from other people though. Thanks for understanding.
