### ISSUE TITLE
sp_BlitzFirst - Perfmon counter filtering

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#356]
We return something like 200 rows from the Perfmon section, does it make sense to return values where either the first counter is 0, or the delta value is 0? 

If filtering them out is a no-go, perhaps order by delta value so the frequent stuff for your sample is up top?

**Comment by BrentOzar** [comment]
Ran it with the list of counters, attached. Here's the list of ValueDelta = 0 when the server is idle - 121 of them altogether. I agree, probably wanna filter the zeroes out of the returned results, but just not out of the table inserts - it still needs to be logged so we can do trending.

SQLServer:Access Methods	Forwarded Records/sec
SQLServer:Access Methods	Page compression attempts/sec
SQLServer:Access Methods	Skipped Ghosted Records/sec
SQLServer:Access Methods	Table Lock Escalations/sec
SQLServer:Buffer Manager	Checkpoint pages/sec
SQLServer:Buffer Manager	Free list stalls/sec
SQLServer:Buffer Manager	Lazy writes/sec
SQLServer:Buffer Manager	Page writes/sec
SQLServer:Buffer Manager	Target pages
SQLServer:Cursor Manager by Type	Active cursors
SQLServer:Cursor Manager by Type	Active cursors
SQLServer:Cursor Manager by Type	Active cursors
SQLServer:Cursor Manager by Type	Active cursors
SQLServer:Databases	Log Growths
SQLServer:Databases	Log Shrinks
SQLServer:Exec Statistics	Distributed Query
SQLServer:Exec Statistics	DTC calls
SQLServer:Exec Statistics	Extended Procedures
SQLServer:Exec Statistics	OLEDB calls
SQLServer:General Statistics	Active Temp Tables
SQLServer:General Statistics	Logins/sec
SQLServer:General Statistics	Logouts/sec
SQLServer:General Statistics	Mars Deadlocks
SQLServer:General Statistics	Processes blocked
SQLServer:General Statistics	User Connections
SQLServer:Locks	Average Wait Time (ms) (many instances of these)
SQLServer:Locks	Lock Timeouts/sec (many instances of these)
SQLServer:Locks	Lock Wait Time (ms) (many instances of these)
SQLServer:Locks	Lock Waits/sec (many instances of these)
SQLServer:Locks	Number of Deadlocks/sec (many instances of these)
SQLServer:Memory Manager	Granted Workspace Memory (KB)
SQLServer:Memory Manager	Maximum Workspace Memory (KB)
SQLServer:Memory Manager	Memory Grants Pending
SQLServer:Memory Manager	Target Server Memory (KB)
SQLServer:SQL Statistics	Forced Parameterizations/sec
SQLServer:SQL Statistics	Guided plan executions/sec
SQLServer:SQL Statistics	Safe Auto-Params/sec
SQLServer:SQL Statistics	SQL Attention rate
SQLServer:Transactions	Longest Transaction Running Time

[Counters.xlsx](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/355562/Counters.xlsx)

**Comment by BlitzErik** [comment]
Fixed here: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/357
