### ISSUE TITLE
Add the SQL Server 2019+ ignorable waits to sp_Blitz's #IgnorableWaits.

### ISSUE THREAD

**Issue by ReeceGoding** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3562]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when `sp_Blitz` tells me that I need to worry about my "PWAIT_EXTENSIBILITY_CLEANUP_TASK" waits, but then links to Paul Randal's website that [tells me that I don't](https://www.sqlskills.com/help/waits/pwait_extensibility_cleanup_task/). I suspect that we've not kept `#IgnorableWaits` up to date. [I'm not the first to say this](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/2930).

**Describe the solution you'd like**
dbatools had the same problem. Before I updated it, their list was last updated in 2018. I don't know when we last updated `#IgnorableWaits` (I can see [some updates from two years ago](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/1798)?), but my plan is to copy the same updates as [what I gave them](https://github.com/dataplat/dbatools/pull/9249/files).

**Describe alternatives you've considered**
I could submit one ticket per wait and we could review each, but I think we trust Paul's judgement here.

I've also considered doing the same work for `sp_BlitzFirst`, but I'm unsure if it has the same problems. I've yet to notice it complaining about waits that it shouldn't, but I also haven't found any code that prevents it from doing that.

**Are you ready to build the code for the feature?**
Yes. It shouldn't take long.

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, merged into the dev branch, will be in the next release with credit to you in the release notes.
