### ISSUE TITLE
sp_BlitzFirst skips plan cache analysis when @ExportMode = 1

### ISSUE THREAD

**Issue by JonasEckerman** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3565]
**Version of the script:**
Version = '8.21', VersionDate = '20240701' (latest dev branch)

**What is the current behavior?**

When running sp_BlitzFirst with @ExportMode=1, the proc skips check 18 (Plan Cache Analysis) if we're not we're within 10 seconds of projected finish time, with this message in the results:  
'Due to excessive load, the plan cache analysis was skipped. To override this, use @ExpertMode = 1.'

**What is the expected behavior?**

Either that the check is not skipped when @ExportMode=1, or that the message does not say that the skip may be overridden by setting @ExportMode=1.

**Fix?:**

Since I don't know whether the behaiviour or the text is wrong, here's one patch for each.

In case the behaviour is wrong:

```
2773c2773
<     IF DATEDIFF(ss, @FinishSampleTime, SYSDATETIMEOFFSET()) > 10 AND @CheckProcedureCache = 1
---
>     IF DATEDIFF(ss, @FinishSampleTime, SYSDATETIMEOFFSET()) > 10 AND @CheckProcedureCache = 1 AND ISNULL(@ExpertMode, 0) = 0
```

In case the message is wrong:
```
2782c2782
<                 'Due to excessive load, the plan cache analysis was skipped. To override this, use @ExpertMode = 1.');
---
>                 'Due to excessive load, the plan cache analysis was skipped.');
```

If you're open to pull requests, and tell me which fix to to use, I can create one if you prefer that.

**Comment by BrentOzar** [comment]
Hi! The latter solution would be right - let's change the message. Thanks!

**Comment by BrentOzar** [comment]
@JonasEckerman did you plan on contributing the code for this? If not, let me know and I can close the issue for you.

**Comment by JonasEckerman** [comment]
@BrentOzar I'm planning on contributing, but a customer status update flipped changed me from "having a nice bit of time for stuff" to "how do I clone myself?".

**Comment by BrentOzar** [comment]
Hahaha, no worries. I'm going to close this for now, but if you decide you wanna work on it later, leave a note here and I can reopen it. Thanks!
