### ISSUE TITLE
Are there versions of the scripts without creating stored procedures?

### ISSUE THREAD

**Issue by Tony20221** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3570]
I don't have permissions to create anything in production but I am interested to know the health of the databases.
Are there versions of the scripts without creating stored procedures?
Can the scripts be modified to run as SQL for people who don't have create/alter permissions?

**Comment by BrentOzar** [comment]
@Tony20221 howdy! Your best bet there will be to check in with the folks who do have the permissions. These scripts are designed for those folks.

**Comment by Tony20221** [comment]
I will modify the SPs to straight SQL and check for myself.
