### ISSUE TITLE
Question about inclusive language update for sp_BlitzIndex

### ISSUE THREAD

**Issue by VladDBA** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3571]
Is there any more work needed on the inclusive language update for sp_BlitzIndex?
If yes, is there something I can help with? I already have a list of "sanitized" finding names that covers the most common findings as part of a helper tool I've made for PSBlitz's HTML output.

**Comment by BrentOzar** [comment]
Howdy! I actually closed that issue because I don't have the time to work on it. If you want to tackle it, can you put the list of before & after names here for discussion? After we've gotten consensus from the community, you can knock it out if you want.

**Comment by VladDBA** [comment]
Hey, Brent!
Sure, here's what I have so far:
| Priority | FindingsGroup | Finding | URL | CheckID | UpdatedFindingsGroup | UpdatedFinding |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
|10|Index Hoarder|Many NC Indexes on a Single Table|https://www.brentozar.com/go/IndexHoarder|20|Overindexing|Many NC Indexes on a Single Table|
|10|Index Hoarder|Unused NC Index with High Writes|https://www.brentozar.com/go/IndexHoarder|22|Overindexing|Unused NC Index with High Writes|
|20|Multiple Index Personalities|Duplicate Keys|https://www.brentozar.com/go/duplicateindex|1|Redundant Indexes|Duplicate Keys|
|30|Multiple Index Personalities|Borderline Duplicate Keys|https://www.brentozar.com/go/duplicateindex|2|Redundant Indexes|Approximate Duplicate Keys|
|40|Indexaphobia|High Value Missing Index|https://www.brentozar.com/go/indexaphobia|50|Index Suggestion (could also be Underindexing)|High Value Missing Index|
|70|Aggressive Indexes|Total Lock Time with Long Average Waits|https://www.brentozar.com/go/aggressiveindexes|11|Prone to Locking|Total Lock Time with Long Average Waits|
|70|Aggressive Indexes|Total Lock Time with Short Average Waits|https://www.brentozar.com/go/aggressiveindexes|12|Prone to Locking|Total Lock Time with Short Average Waits|
|80|Abnormal Psychology|Columnstore Indexes with Trace Flag 834|https://support.microsoft.com/en-us/kb/3210239|72|Abnormal Design Pattern|Columnstore Indexes with Trace Flag 834|
|80|Abnormal Psychology|Identity Column Near End of Range|https://www.brentozar.com/go/AbnormalPsychology|68|Abnormal Design Pattern|Identity Column Near End of Range|
|80|Abnormal Psychology|Filter Columns Not In Index Definition|https://www.brentozar.com/go/IndexFeatures|34|Abnormal Design Pattern|Filter Columns Not In Index Definition|
|90|Functioning Statistaholics|Low Sampling Rates|https://www.brentozar.com/go/stats|91|Statistics Warnings|Low Sampling Rates|
|90|Functioning Statistaholics|Statistics Not Updated Recently|https://www.brentozar.com/go/stats|90|Statistics Warnings|Statistics Not Updated Recently|
|90|Functioning Statistaholics|Statistics with NO RECOMPUTE|https://www.brentozar.com/go/stats|92|Statistics Warnings|Statistics with NO RECOMPUTE|
|100|Index Hoarder|NC index with High Writes:Reads|https://www.brentozar.com/go/IndexHoarder|48|Overindexing|NC index with High Writes:Reads|
|100|Self Loathing Indexes|Heap with a Nonclustered Primary Key|https://www.brentozar.com/go/SelfLoathing|47|Indexes Worth Reviewing|Heap with a Nonclustered Primary Key|
|100|Self Loathing Indexes|Heap with Forwarded Fetches|https://www.brentozar.com/go/SelfLoathing|43|Indexes Worth Reviewing|Heap with Forwarded Fetches|
|100|Self Loathing Indexes|Large Active Heap|https://www.brentozar.com/go/SelfLoathing|44|Indexes Worth Reviewing|Large Active Heap|
|100|Self Loathing Indexes|Low Fill Factor on Clustered Index|https://www.brentozar.com/go/SelfLoathing|40|Indexes Worth Reviewing|Low Fill Factor on Clustered Index|
|100|Self Loathing Indexes|Low Fill Factor on Nonclustered Index|https://www.brentozar.com/go/SelfLoathing|40|Indexes Worth Reviewing|Low Fill Factor on Nonclustered Index|
|100|Self Loathing Indexes|Medium Active Heap|https://www.brentozar.com/go/SelfLoathing|45|Indexes Worth Reviewing|Medium Active Heap|
|100|Self Loathing Indexes|Small Active Heap|https://www.brentozar.com/go/SelfLoathing|46|Indexes Worth Reviewing|Small Active Heap|
|100|Serial Forcer|Computed Column with Scalar UDF|https://www.brentozar.com/go/serialudf|99|Forced Serialization|Computed Column with Scalar UDF|
|100|Serial Forcer|Check Constraint with Scalar UDF|https://www.brentozar.com/go/computedscalar|94|Forced Serialization|Check Constraint with Scalar UDF|
|150|Abnormal Psychology|Cascading Updates or Deletes|https://www.brentozar.com/go/AbnormalPsychology|71|Abnormal Design Pattern|Cascading Updates or Deletes|
|150|Abnormal Psychology|Unindexed Foreign Keys|https://www.brentozar.com/go/AbnormalPsychology|72|Abnormal Design Pattern|Unindexed Foreign Keys|
|150|Abnormal Psychology|Columnstore Index|https://www.brentozar.com/go/AbnormalPsychology|61|Abnormal Design Pattern|Columnstore Index|
|150|Abnormal Psychology|Column Collation Does Not Match Database Collation|https://www.brentozar.com/go/AbnormalPsychology|69|Abnormal Design Pattern|Column Collation Does Not Match Database Collation|
|150|Abnormal Psychology|Compressed Index|https://www.brentozar.com/go/AbnormalPsychology|63|Abnormal Design Pattern|Compressed Index|
|150|Abnormal Psychology|In-Memory OLTP|https://www.brentozar.com/go/AbnormalPsychology|73|Abnormal Design Pattern|In-Memory OLTP|
|150|Abnormal Psychology|Non-Aligned Index on a Partitioned Table|https://www.brentozar.com/go/AbnormalPsychology|65|Abnormal Design Pattern|Non-Aligned Index on a Partitioned Table|
|150|Abnormal Psychology|Partitioned Index|https://www.brentozar.com/go/AbnormalPsychology|64|Abnormal Design Pattern|Partitioned Index|
|150|Abnormal Psychology|Spatial Index|https://www.brentozar.com/go/AbnormalPsychology|62|Abnormal Design Pattern|Spatial Index|
|150|Abnormal Psychology|XML Index|https://www.brentozar.com/go/AbnormalPsychology|60|Abnormal Design Pattern|XML Index|
|150|Index Hoarder|Borderline: Wide Indexes (7 or More Columns)|https://www.brentozar.com/go/IndexHoarder|23|Overindexing|Borderline: Wide Indexes (7 or More Columns)|
|150|Index Hoarder|More Than 5 Percent NC Indexes Are Unused|https://www.brentozar.com/go/IndexHoarder|21|Overindexing|More Than 5 Percent NC Indexes Are Unused|
|150|Index Hoarder|Non-Unique Clustered Index|https://www.brentozar.com/go/IndexHoarder|28|Overindexing|Non-Unique Clustered Index|
|150|Index Hoarder|Unused NC Index with Low Writes|https://www.brentozar.com/go/IndexHoarder|29|Overindexing|Unused NC Index with Low Writes|
|150|Index Hoarder|Wide Clustered Index (>3 columns or >16 bytes)|https://www.brentozar.com/go/IndexHoarder|24|Overindexing|Wide Clustered Index (>3 columns or >16 bytes)|
|150|Self Loathing Indexes|Disabled Index|https://www.brentozar.com/go/SelfLoathing|42|Indexes Worth Reviewing|Disabled Index|
|150|Self Loathing Indexes|Hypothetical Index|https://www.brentozar.com/go/SelfLoathing|41|Indexes Worth Reviewing|Hypothetical Index|
|200|Abnormal Psychology|Identity Column Using a Negative Seed or Increment Other Than 1|https://www.brentozar.com/go/AbnormalPsychology|74|Abnormal Design Pattern|Identity Column Using a Negative Seed or Increment Other Than 1|
|200|Abnormal Psychology|Recently Created Tables/Indexes (1 week)|https://www.brentozar.com/go/AbnormalPsychology|66|Abnormal Design Pattern|Recently Created Tables/Indexes (1 week)|
|200|Abnormal Psychology|Recently Modified Tables/Indexes (2 days)|https://www.brentozar.com/go/AbnormalPsychology|67|Abnormal Design Pattern|Recently Modified Tables/Indexes (2 days)|
|200|Abnormal Psychology|Replicated Columns|https://www.brentozar.com/go/AbnormalPsychology|70|Abnormal Design Pattern|Replicated Columns|
|200|Abnormal Psychology|Temporal Tables|https://www.brentozar.com/go/AbnormalPsychology|110|Abnormal Design Pattern|Temporal Tables|
|200|Cold Calculators|Definition Defeatists|https://www.brentozar.com/go/serialudf|100|||
|200|Functioning Statistaholics|Filter Fixation|https://www.brentozar.com/go/stats|93|Statistics Warnings|Filter Fixation|
|200|Index Hoarder|Addicted to Nulls|https://www.brentozar.com/go/IndexHoarder|25|Overindexing|High Ratio of Nulls|
|200|Index Hoarder|Addicted to Strings|https://www.brentozar.com/go/IndexHoarder|27|Overindexing|High Ratio of Strings|
|200|Index Hoarder|Wide Tables: 35+ cols or > 2000 non-LOB bytes|https://www.brentozar.com/go/IndexHoarder|26|Overindexing|Wide Tables: 35+ cols or > 2000 non-LOB bytes|
|200|Self Loathing Indexes|Heaps with Deletes|https://www.brentozar.com/go/SelfLoathing|49|Indexes Worth Reviewing|Heaps with Deletes|
|200|Workaholics|Scan-a-lots (index-usage-stats)|https://www.brentozar.com/go/Workaholics|80|High Workloads|Scan-a-lots (index-usage-stats)|
|200|Workaholics|Top Recent Accesses (index-op-stats)|https://www.brentozar.com/go/Workaholics|81|High Workloads|Top Recent Accesses (index-op-stats)|
|250|Feature-Phobic Indexes|Few Indexes Use Includes|https://www.brentozar.com/go/IndexFeatures|31|Omitted Index Features|Few Indexes Use Includes|
|250|Feature-Phobic Indexes|No Filtered Indexes or Indexed Views|https://www.brentozar.com/go/IndexFeatures|32|Omitted Index Features|No Filtered Indexes or Indexed Views|
|250|Feature-Phobic Indexes|No Indexes Use Includes|https://www.brentozar.com/go/IndexFeatures|30|Omitted Index Features|No Indexes Use Includes|
|250|Feature-Phobic Indexes|Potential Filtered Index (Based on Column Name)|https://www.brentozar.com/go/IndexFeatures|33|Omitted Index Features|Potential Filtered Index (Based on Column Name)|
|250|Medicated Indexes|Optimized For Sequential Keys||121|||

**Comment by VladDBA** [comment]
Hey Brent!
I've updated the table with the last remaining missing entry. This should cover everything, but I'd appreciate a second pair of eyes checking and any potential suggestions/corrections are also appreciated.

**Comment by BrentOzar** [comment]
@VladDBA great work! These make perfect sense. I wouldn't change any of them!

**Comment by VladDBA** [comment]
Just a quick update, @BrentOzar: 
I've started making the changes in sp_BlitzIndex, and I'll have to change the wording a bit for check_id 11, which in the above list is "Prone to locking", into "Lock-Prone " because it would better match the way the Findings Group is constructed for this check
- Original:
```sql
        RAISERROR(N'check_id 11: Total lock wait time > 5 minutes (row + page)', 0,1) WITH NOWAIT;
                INSERT    #BlitzIndexResults ( check_id, index_sanity_id, Priority, findings_group, finding, [database_name], URL, details, index_definition,
                                               secret_columns, index_usage_summary, index_size_summary )
                SELECT  11 AS check_id, 
                        i.index_sanity_id,
                        70 AS Priority,
                        N'Aggressive ' 
                            + CASE COALESCE((SELECT SUM(1) 
							                 FROM #IndexSanity iMe 
											 INNER JOIN #IndexSanity iOthers 
												ON iMe.database_id = iOthers.database_id 
												AND iMe.object_id = iOthers.object_id 
												AND iOthers.index_id > 1 
											 WHERE i.index_sanity_id = iMe.index_sanity_id
												AND iOthers.is_hypothetical = 0
												AND iOthers.is_disabled = 0
											), 0)
                                WHEN 0 THEN N'Under-Indexing'
                                WHEN 1 THEN N'Under-Indexing'
                                WHEN 2 THEN N'Under-Indexing'
                                WHEN 3 THEN N'Under-Indexing'
                                WHEN 4 THEN N'Indexes'
                                WHEN 5 THEN N'Indexes'
                                WHEN 6 THEN N'Indexes'
                                WHEN 7 THEN N'Indexes'
                                WHEN 8 THEN N'Indexes'
                                WHEN 9 THEN N'Indexes'
                                ELSE N'Over-Indexing'
                                END AS findings_group,
                        N'Total lock wait time > 5 minutes (row + page)' AS finding, 
                        [database_name] AS [Database Name],
                        N'https://www.brentozar.com/go/AggressiveIndexes' AS URL,
```

- updated version would generate findings groups such as "Lock-Prone Under-Indexing", "Lock-Prone Indexes", and "Lock-Prone Over-Indexing"
```sql
        RAISERROR(N'check_id 11: Total lock wait time > 5 minutes (row + page)', 0,1) WITH NOWAIT;
                INSERT    #BlitzIndexResults ( check_id, index_sanity_id, Priority, findings_group, finding, [database_name], URL, details, index_definition,
                                               secret_columns, index_usage_summary, index_size_summary )
                SELECT  11 AS check_id, 
                        i.index_sanity_id,
                        70 AS Priority,
                        N'Lock-Prone ' 
                            + CASE COALESCE((SELECT SUM(1) 
							                 FROM #IndexSanity iMe 
											 INNER JOIN #IndexSanity iOthers 
												ON iMe.database_id = iOthers.database_id 
												AND iMe.object_id = iOthers.object_id 
												AND iOthers.index_id > 1 
											 WHERE i.index_sanity_id = iMe.index_sanity_id
												AND iOthers.is_hypothetical = 0
												AND iOthers.is_disabled = 0
											), 0)
                                WHEN 0 THEN N'Under-Indexing'
                                WHEN 1 THEN N'Under-Indexing'
                                WHEN 2 THEN N'Under-Indexing'
                                WHEN 3 THEN N'Under-Indexing'
                                WHEN 4 THEN N'Indexes'
                                WHEN 5 THEN N'Indexes'
                                WHEN 6 THEN N'Indexes'
                                WHEN 7 THEN N'Indexes'
                                WHEN 8 THEN N'Indexes'
                                WHEN 9 THEN N'Indexes'
                                ELSE N'Over-Indexing'
                                END AS findings_group,
                        N'Total lock wait time > 5 minutes (row + page)' AS finding, 
                        [database_name] AS [Database Name],
                        N'https://www.brentozar.com/go/AggressiveIndexes' AS URL,
```

**Comment by bmercernccer** [comment]
I'd suggest Suggested Index instead of Index Suggestion, but that's just a suggestion.
