### ISSUE TITLE
sp_Blitz: Error with parameter @OutputType = 'markdown'

### ISSUE THREAD

**Issue by jukkama** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3585]
**Version of the script**
Version 8.22, version date 20241019

**What is the current behavior?**
It returns only an error
Warning: Null value is eliminated by an aggregate or other SET operation.
Msg 9421, Level 16, State 1, Procedure sp_Blitz, Line 10347 [Batch Start Line 24]
XML parsing: line 233, character 203, illegal name character

**If the current behavior is a bug, please provide the steps to reproduce.**
Run procedure with this parameter
sp_Blitz @OutputType = 'markdown'

**What is the expected behavior?**
Nicely formatted list to use with email etc as it was in earlier script version

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Problem faced with SQL Server 2019 (15.0.4360.2) in Windows Server 2019. This worked in script version 8.15, version date 20230613 on the same platform.

**Comment by BrentOzar** [comment]
@jukkama sorry about that! Can you run sp_Blitz in regular mode, and look at what the difference is in output between the old & new versions? I'm guessing there's a new check between 8.22 and 8.15 that outputs something problematic on your server, but I can't see what that is from here.

**Comment by jukkama** [comment]
Here is the output difference without any parameters

Only in new version:
Priority	FindingsGroup	Finding ...
100		Performance		Many Plans for One Query

Only in old version:
Priority	FindingsGroup	Finding
0	        Outdated sp_Blitz	sp_Blitz is Over 6 Months Old

In both but different:
Priority	        FindingsGroup				Finding
0			sp_Blitz Oct 19 2024 12:00AM	SQL Server First Responder Kit
0			sp_Blitz Jun 13 2023 12:00AM	SQL Server First Responder Kit

**Comment by BrentOzar** [comment]
Hmm, none of that has illegal XML characters, so I'm guessing the princess we're looking for is in another castle.
