### ISSUE TITLE
sp_BlitzFirst: 'Sleeping Query with Open Transactions' is not executed if there are no sys.dm_exec_requests with total_elapsed_time > 5000

### ISSUE THREAD

**Issue by spilkercompra** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3591]
Introduced in commit
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/3258/commits/043139dd6840e05fdbdf595281a3c5796737ffdf
line 1761
IF EXISTS (SELECT * FROM sys.dm_exec_requests WHERE total_elapsed_time > 5000 AND request_id > 0) ....

> This seems to be incorrect as the check for 'Sleeping Query with Open Transactions' does not use sys.dm_exec_requests.
> 
> It will not be executed if the condition is false and 'Sleeping Query with Open Transactions' will not be shown. 

 _Originally posted by @spilkercompra in [043139d](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/commit/043139dd6840e05fdbdf595281a3c5796737ffdf#r149347423)_

**Comment by BrentOzar** [comment]
Yes, that was actually on purpose - if there aren't any long-running transactions, we don't want to go querying locks, because it's extremely slow if you have thousands of open sessions.
