### ISSUE TITLE
sp_Blitz @OutputType = 'Markdown'. XML parsing: illegal name character

### ISSUE THREAD

**Issue by igaliney** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3593]
**Version of the script**
@Version = '8.22', @VersionDate = '20241019'

**What is the current behavior?**
When I run a procedure with the following parameter "exec dbo.sp_Blitz @OutputType = 'Markdown'", I expected to see the output result in Markdown format. However, I received the following error instead:

*Msg 9421, Level 16, State 1, Procedure dbo.sp_Blitz, Line 10347 [Batch Start Line 0] XML parsing: line 63, character 37, illegal name character.*

**If the current behavior is a bug, please provide the steps to reproduce.**
```sql
USE Master;  
GO  
exec dbo.sp_Blitz @OutputType = 'Markdown'
```

**What is the expected behavior?**
The output should be displayed as Markdown text without errors.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server Service: Version: 16.0.1135.2. Patch Level: RTM. Edition: Developer Edition (64-bit). Availability Groups Enabled: 0. Availability Groups Manager Status: 1
Operating System Version: Windows 11 Enterprise, version 23H2

**Possible fix**
The issue is caused by an illegal character (&) in the description of the Finding column for CheckID = 162. To resolve this issue, update the description to replace & with and, ensuring XML compatibility.
Example:
Change "Poison Wait Detected: CMEMTHREAD & NUMA" to "Poison Wait Detected: CMEMTHREAD and NUMA".

**Comment by igaliney** [comment]
@BrentOzar , my apologies for not noticing the existing issue and unintentionally duplicating it. Turns out I need a pair of glasses for GitHub! 😅 The issue I raised overlaps with the already existing request [sp_Blitz: Error with parameter @OutputType = 'markdown'](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/3585). Would you mind merging these together and review my possible solution? Thanks! 🙏

**Comment by BrentOzar** [comment]
Thanks for the pull request! Looks good, merging into the dev branch, will be in the next release with credit to you in the release notes.
