### ISSUE TITLE
sp_Blitz - Arithmetic overflow error

### ISSUE THREAD

**Issue by songomajk** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3599]
**Version of the script**
Version = '8.22', 
VersionDate = '20241019';

**What is the current behavior?**
Msg 8115, Level 16, State 7, Line 3
Arithmetic overflow error converting numeric to data type numeric.
The statement has been terminated.
Warning: Null value is eliminated by an aggregate or other SET operation.

**If the current behavior is a bug, please provide the steps to reproduce.**
Running sp_Blitz with these two parameters  ( @CheckServerInfo=1, @BringThePain=1 ) causes the error. It runs perfectly on a small instance (with <100 GB databases) but fails to do the same on a biger one (over Tbyte databases included). It spits out the results, but end up in an error message.

**What is the expected behavior?**
No error message expected.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL SERVER 2019 (STANDARD - 15.0.4261.1)

**Comment by BrentOzar** [comment]
Can you run it with @Debug = 1 and copy/paste the output into a text file and attach it here? Thanks!

**Comment by songomajk** [comment]
Thank you for the quick reply, please find the requested output attached.

Error message can starts at row # 157.

Msg 8115, Level 16, State 7, Line 6
Arithmetic overflow error converting numeric to data type numeric.
The statement has been terminated.

[sp_blitz_debug.txt](https://github.com/user-attachments/files/18147855/sp_blitz_debug.txt)

**Comment by BrentOzar** [comment]
@songomajk perfect, thanks for that! Here's the part of the code that might be at fault:

`		                                ''The ['' + DB_NAME() + ''] database file '' + f.physical_name + '' has grown to '' + CONVERT(NVARCHAR(10), CONVERT(NUMERIC(38, 2), (f.size / 128.) / 1024.)) + '' GB, and is using percent filegrowth settings. This can lead to slow performance during growths if Instant File Initialization is not enabled.''
`

Do a search in the code for that, and change the number after NVARCHAR from 10 to 20. Let's see if that fixes the problem.
