### ISSUE TITLE
sp_BlitzCache - include version number in the output

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#360]
Not sure exactly where to output this just yet - our goal is to get it into the top result set somewhere, like a last-row thank-you maybe?

**Comment by BlitzErik** [comment]
So... the last BlitzCache version announced was 2.5.0 in October of 2015. Since then it has been versionless. I'm just going to start it at 4.0, I guess.

**Comment by BlitzErik** [comment]
Outputs in last row of warnings to not interfere with collection
![image](https://cloud.githubusercontent.com/assets/11590415/20457231/a44896aa-ae54-11e6-9429-28c52642bb59.png)
