### ISSUE TITLE
BlitzFirst - Add in memory grant columns to what's running

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#362]
With [SP2 for 2014](https://support.microsoft.com/en-us/kb/3107398) out, it will be easier to call these columns when available.

@BrentOzar are there any diagnostics we want to run against these, or just display for now?

**Comment by BrentOzar** [comment]
Ooo, great question. Just thinking out loud in terms of new warnings to add in the diagnostics result set (not on the query level, although it'd be interesting to have warnings about currently running queries, but the smarter way to do that is call sp_BlitzCache for only one query hash and get the results back):

* One running query has a grant of over, say, 10% of the server's total memory
* Total memory grants outstanding is over, say, 25% of the server's memory (I'm making these up - could be 50%?)

**Comment by BlitzErik** [comment]
Is it too much to assume that someone will have BlitzCache installed?

**Comment by BrentOzar** [comment]
Well, for v1 we could just make it a known issue that if you don't have it installed, sp_BlitzFirst is gonna fail.

**Comment by BlitzErik** [comment]
I'm just going to add the columns for now. I think this is partially covered by the more_info column I added a while back that fetches the execution plan directly.

**Comment by BlitzErik** [comment]
Added #376

**Comment by BrentOzar** [comment]
Fantastic. Closing.
