### ISSUE TITLE
sp_BlitzFirst - INSERT failed because the following SET options have incorrect settings: 'QUOTED_IDENTIFIER'

### ISSUE THREAD

**Issue by chrgraefe** [BrentOzarULTD/SQL-Server-First-Responder-Kit#364]
Hello,

I'm running BlitzFirst without success. Any idea what's going wrong?

Statement:
`DECLARE	@return_value int,
		@VersionDate datetime

EXEC	@return_value = [dbo].[sp_BlitzFirst]
		@ExpertMode = 1,
		@VersionDate = @VersionDate OUTPUT

SELECT	@VersionDate as N'@VersionDate'

SELECT	'Return Value' = @return_value

GO`

Error message:
Setting up configuration variables
Now starting diagnostic analysis
Capturing first pass of wait stats, perfmon counters, file stats
Beginning investigatory queries
Msg 1934, Level 16, State 1, Procedure sp_BlitzFirst, Line 1023 [Batch Start Line 12]
INSERT failed because the following SET options have incorrect settings: 'QUOTED_IDENTIFIER'. Verify that SET options are correct for use with indexed views and/or indexes on computed columns and/or filtered indexes and/or query notifications and/or XML data type methods and/or spatial index operations.

Environment:
SSMS: 13.0.15500.91
OS: Windows 7 Professional
Server: SQL Server 2008 SP4
Server-OS: Windows Server 2012 R2

**Comment by chrgraefe** [comment]
Hi,

it seems the QUOTED_IDENTIFIER is set to OFF, but it should be ON (new behavior in SSMS)
https://msdn.microsoft.com/en-us/library/ms345117(SQL.90).aspx

**Comment by BlitzErik** [comment]
Thanks for letting us know. Since this is a localized setting, I don't think there's anything we can do about it.
