### ISSUE TITLE
sp_BlitzCache - Help text should contain default values for parameters

### ISSUE THREAD

**Issue by SelmanAY** [BrentOzarULTD/SQL-Server-First-Responder-Kit#367]
When @Help = 1 is specified the parameter list with datatype and description is perfect. 
how about adding a default value column to that table.

**Comment by BlitzErik** [comment]
Which stored procedure are you referring to?

**Comment by SelmanAY** [comment]
sp_BlitzCache, one of the default values (@ExpertMode) is printed on parameter description

**Comment by BrentOzar** [comment]
That's a great idea! Want to help? Check out our contributing guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md

That change would be relatively easy to get started with, since it just involves print commands.
