### ISSUE TITLE
sp_BlitzRS - Invaild object name 'ExecutionLogStorage'

### ISSUE THREAD

**Issue by keypersltd** [BrentOzarULTD/SQL-Server-First-Responder-Kit#368]
Hi, tried to run sp_Blitz on SQL SSRS instance and returns following error:

Msg 208, Level 16, State 1, Procedure sp_BlitzRS, Line 218
Invalid object name 'ExecutionLogStorage'.

I check the sp and could not see where this object is created - I did see an dbo.ExecutionLog tbl in ReportServer db but not 'ExecutionLogStorage'

Thanks

Scott

**Comment by BlitzErik** [comment]
From the error message, you're running sp_BlitzRS, not sp_Blitz. 

BlitzRS does query the ExecutionLogStorage table. If you don't see it, my best guess is that you don't have logging enabled.

If you don't see views for ExecutionLog, ExecutionLog2, or ExecutionLog3, or selecting * from them returns no data, that's likely the case.

You'll have to go into server properties > Logging and enable logging, and then configure it under Advanced options. 

This is not a bug in Blitz or BlitzRS.

**Comment by keypersltd** [comment]
No problem, thanks for the update Erik.

Rgds,

Scott

**Comment by douglane** [comment]
Hi Scott,

Just out of curiosity, can you tell me the version of SSRS you got this error on?

Thanks,
Doug

**Comment by keypersltd** [comment]
Hi Doug, it was from the latest Responder download 05/15 and the sp_blitzRS version is v0.92.

(ignore my typo in original post first line, sorry Erik I did mean blitzRS)

Rgds,

Scott
