### ISSUE TITLE
sp_BlitzIndex - bug in number of existing NC indexes in warnings

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#374]
In normal diagnostic mode (0 or 4), the Indexaphobia: High value missing index warnings report things like:

64 NC indexes exist (13.1GB); 48,327,153 Estimated Rows;

But that database's table doesn't necessarily have 64 missing indexes. In one I was doing today, there were 4-6 indexes on tables like this.

I haven't reproduced it successfully yet, but I think it has to do with databases starting from the same backup. For example:

1. Create a database, create a table in it, and create several indexes on that table (but don't index all of the fields, because you'll need to generate a missing index later)
2. Back up the database
3. Restore it under several different names
4. Generate a missing index DMV entry
5. Run sp_BlitzIndex @GetAllDatabases = 1.

(Evidence is in 20160713_084953 spreadsheet in client folders.)

**Comment by BlitzErik** [comment]
I think I have this fixed. There was a database join condition missing from this part of the missing index stuff. Limited proof:
One index is logged here, but each table has one NC index on it:
![image](https://cloud.githubusercontent.com/assets/11590415/16820788/e107b5ce-4920-11e6-8509-e89b3b953ee7.png)

Table 1:
![image](https://cloud.githubusercontent.com/assets/11590415/16820792/f10dbdd8-4920-11e6-84dd-a0b797fa9fad.png)

Table 2:
![image](https://cloud.githubusercontent.com/assets/11590415/16820797/fc2b2bec-4920-11e6-82eb-446986d9b1fd.png)

Checking in a fix for you to test.

**Comment by BrentOzar** [comment]
You're my gyro. I'll test it tomorrow AM.

**Comment by BlitzErik** [comment]
Here she is!

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/tree/BlitzIndex_Erik_Issue_351

**Comment by BlitzErik** [comment]
Did this fix end up in today's mergefest?

**Comment by BlitzErik** [comment]
#351
