### ISSUE TITLE
sp_BlitzRS : string or binary data will be truncated on RoleName

### ISSUE THREAD

**Issue by fghysens** [BrentOzarULTD/SQL-Server-First-Responder-Kit#378]
Hi

When running the sp_BlitzRS I received a string truncation error.
The reason was the definition of temp table #RoleTaskMask

This temptable is defined as
```
CREATE TABLE #RoleTaskMask
    (
      RoleName NVARCHAR(32) ,
      RoleFlags TINYINT ,
      TaskMaskPos TINYINT ,
      TaskMaskValue TINYINT
    )
```

this table will be filled by a query on ReportServer database in table dbo.Roles
```
SELECT
RoleName ,
RoleFlags ,
...
FROM dbo.Roles
```

the field RoleName is defined in this table as nvarchar(260)
after adapting the temp table definition the SP worked fine

it is advisable to also define the other temptables using the RoleName field to be same definition: #RoleDefault, #RoleDefaultTaskMask

Best Regards
f

**Comment by BlitzErik** [comment]
#394
