### ISSUE TITLE
sp_BlitzCache Inconsistency in name of check between warnings and findings

### ISSUE THREAD

**Issue by SelmanAY** [BrentOzarULTD/SQL-Server-First-Responder-Kit#380]
Check ID 13 is named as "Legacy Cardinality Estimator in Use" in findings (second ResultSet) [line# 2477](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzCache.sql#L2477) and "Downlevel CE" in warnings column in first resultset [line#1952](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzCache.sql#L1952)

![ssms_2016-07-15_08-07-12](https://cloud.githubusercontent.com/assets/12393411/16864254/b9bc4612-4a63-11e6-8327-c4d10f4da140.png)

note: created in reference to #377

**Comment by BrentOzar** [comment]
Great catch! In Opserver (StackOverflow's open source monitoring tool), we're doing some lookups between those result sets. For the lookups to work, the warnings/findings have to match exactly.

This fix is a great start, and I like how you did C.E. instead of CE - but can you make it match exactly? I do like the Legacy word, so how about just "Legacy C.E." on both result sets? That way it's short enough.

**Comment by BrentOzar** [comment]
I saw the commit & merge - thanks for the help, but I need you to read the contributing.md file for this repo first to understand how we work here. Someone else needs to test your work before the commit is merged into the dev branch.

Nothing personal - I really appreciate the work - but I went ahead and removed your collaborator access for now. When the code's ready, follow the instructions in contributing.md. Thanks!

**Comment by SelmanAY** [comment]
Thanks. nothing is taken personal. 
I actually appreciate every time you fixed because every time i learn something.

It's my bad not reading contributing.md for the first time. After your warning i have skipped the right titles because of time issues. i have read this time without skipping a letter of it. :hand:

**Comment by BlitzErik** [comment]
Gonna go ahead and close this since it hasn't been worked on in months.
