### ISSUE TITLE
Sp_Blitz: Prioritization of Security items

### ISSUE THREAD

**Issue by Brianc-DBA** [BrentOzarULTD/SQL-Server-First-Responder-Kit#397]
In Sp_Blitz V53.1 (or possibly any version after V49) all of the Security results get a priority of 230.  In previous versions, more critical security items would get a lower number so they would be seen at the top or the results.  

e.g. in previous versions, Users with Sysadmin access would be a priority 10, while Jobs Owned by Users would only merit a 200.  

This does not seem to be the case for other categories, like Performance.  Unless there is some other reason for this change, could the Security items be changed back to have different priority levels based on their criticality?

**Comment by BrentOzar** [comment]
Brianc - yeah, this isn't really a security tool. I'd encourage building a security tool instead - it's a really ripe market in the SQL Server community. You could even start with the bones of this one, and then build your own security-focused sp_Blitz-type-script with the priorities & references you'd recommend. We won't be doing that in sp_Blitz though.
