### ISSUE TITLE
Create Pull request template

### ISSUE THREAD

**Issue by nschonni** [BrentOzarULTD/SQL-Server-First-Responder-Kit#400]
From the [article to get people started](https://www.brentozar.com/archive/2016/07/contribute-code-sql-server-first-responder-kit-github/) there are are few things that can be done to ensure people follow your process
 -  https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

 1. [ ] Create the .github folder
 1. [ ] Create `PULL_REQUEST_TEMPLATE`
 1. [ ] Move the Contributing.md 

PS: 7 from the article won't work for everyone, since only contributors can label issues. [GitHub doesn't currently allow this :frowning:](https://github.com/isaacs/github/issues/148)

**Comment by BrentOzar** [comment]
Great idea! Love it, done.
