### ISSUE TITLE
Significant waits calculation issue due to offline processors

### ISSUE THREAD

**Issue by TaraKizer** [BrentOzarULTD/SQL-Server-First-Responder-Kit#402]
Blitz is using cpu_count from sys.dm_os_sys_info in its calculation on whether or not to show significant waits in the output. On a server with 24 processors with 8 of them offline, Blitz reported "No significant waits detected". But that isn't true as this server is under heavy CPU load. If Blitz had used the 16 online processors, it would have shown CXPACKET and SOS_SCHEDULER_YIELD in the output for this example server. 

For example server: check *20160725_114207.xlsx.

**Comment by BlitzErik** [comment]
This is easily solved by checking a different column in sys.dm_os_sys_info

```
SELECT cpu_count, scheduler_count
FROM    sys.dm_os_sys_info;
```

Affinity set to auto:
![image](https://cloud.githubusercontent.com/assets/11590415/17121511/3e13c02a-52a2-11e6-956a-4bdb12aa7e8a.png)

Change affinity:

![image](https://cloud.githubusercontent.com/assets/11590415/17121535/6406cd4a-52a2-11e6-8718-f29ca1268eb7.png)

Re-run query:

![image](https://cloud.githubusercontent.com/assets/11590415/17121538/71b92208-52a2-11e6-814e-1a618b0ac019.png)

This gives a more accurate count of available CPU resources, and in situations where CPUs are offline, will report more accurately on significant waits (check 152).

**Comment by BlitzErik** [comment]
#404
