### ISSUE TITLE
sp_BlitzFirst - "What's running right now?" section shows inflated statistics

### ISSUE THREAD

**Issue by rwhoward** [BrentOzarULTD/SQL-Server-First-Responder-Kit#406]
Under the /* What's running right now? This is the first and last result set. */ section the cpu, read and write statistics seem very inflated.  A 5ms query has not used 200000ms of CPU time.

It seems like a lot of the statistics being pulled should use dm_exec_requests (aliased as [r]) instead of the currently used, dm_exec_sessions [s].  The amount of CPU, reads, and writes that a session has done seem unimportant compared to the usage of the request.

```
[s].[cpu_time] ,
[s].[logical_reads] ,
[s].[writes] ,
[s].[reads] AS [physical_reads] 
```

This needs to be changed in 4 places and there may be other metrics I didn't notice.  Also a possibility - I'm completely missing the point of these metrics and session is the better thing to have.

**Comment by BrentOzar** [comment]
This commit was backed out in the bad-commits fix, so give it another shot.

**Comment by BlitzErik** [comment]
#503
