### ISSUE TITLE
sp_Blitz - skip maintenance plans (and agent jobs?) in rds

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#409]
Throws an error because it can't access ssis catalogs.

**Comment by BrentOzar** [comment]
If anyone wants to jump in and code this, look for this section of sp_Blitz:

			/* If the server is Amazon RDS, skip checks that it doesn't allow */
		IF LEFT(CAST(SERVERPROPERTY('ComputerNamePhysicalNetBIOS') AS VARCHAR(8000)), 8) = 'EC2AMAZ-'
		   AND LEFT(CAST(SERVERPROPERTY('MachineName') AS VARCHAR(8000)), 8) = 'EC2AMAZ-'
		   AND LEFT(CAST(SERVERPROPERTY('ServerName') AS VARCHAR(8000)), 8) = 'EC2AMAZ-'
			BEGIN
						INSERT INTO #SkipChecks (CheckID) VALUES (6);
						INSERT INTO #SkipChecks (CheckID) VALUES (29);


You can insert any number of checks into the #SkipChecks table there. Power up an Amazon RDS SQL Server instance, run sp_Blitz, and see which checks fail. You can get the ID #'s from this list:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/Documentation/sp_Blitz%20Checks%20by%20Priority.md
