### ISSUE TITLE
sp_BlitzFirst: Enhance documentation for Compilations/Sec web page

### ISSUE THREAD

**Issue by mjswart** [BrentOzarULTD/SQL-Server-First-Responder-Kit#411]
About the docs found at http://www.BrentOzar.com/askbrent/compilations/.

For a workload that makes extensive use of TVPs, each use of a TVP causes compilations to increment and it can lead to sp_BlitzFirst reporting the issue "Compilations/Sec High".

Bob Beauchemin covered this in 

[The interesting case of TVPs and plan compilation](http://www.sqlskills.com/blogs/bobb/the-interesting-case-of-tvps-and-plan-compilation/) and
[TVPs and plan compilation – the reprise](http://www.sqlskills.com/blogs/bobb/tvps-and-plan-compilation-the-reprise/)

It turns out that these compilations do occur, but in the special case of TVPs, they get treated differently in SQL Server and the overhead is described as minimal (by design apparently). 

I though maybe it deserved a note at http://www.BrentOzar.com/askbrent/compilations/.

**Comment by BrentOzar** [comment]
Interesting! I had no idea. Good catch, and added that to the page. Thanks sir!

**Comment by mjswart** [comment]
No problem, sometimes I feel that we're the only shop that makes extensive use of TVPs. :-)

Michael
