### ISSUE TITLE
sp_Blitz is reporting "Too Much Free Memory" on a seldom-used instance

### ISSUE THREAD

**Issue by TaraKizer** [BrentOzarULTD/SQL-Server-First-Responder-Kit#412]
Mark Freeman reported this issue at StackExchange: http://dba.stackexchange.com/questions/146044/sp-blitz-too-much-free-memory-on-seldom-used-ssrs-instance

His test instance is seldomly used and reporting "Too Much Free Memory".

"0GB of free memory inside SQL Server's buffer pool, which is 0GB. You would think lots of free memory would be good, but check out the URL for more information."

**Comment by BrentOzar** [comment]
Great catch. Added the below to the WHERE clause so that we're only alerting on servers with at least 4000MB of memory, because I can totally see this happening on user desktops too and it not being a big deal:

AND CAST(cTotal.cntr_value AS BIGINT) > 4000
