### ISSUE TITLE
Ignore Missing Backups for Replicated Databases

### ISSUE THREAD

**Issue by GregWhiteDBA** [BrentOzarULTD/SQL-Server-First-Responder-Kit#418]
*feature* 

**What is the current behavior?**
SP_Blitz reports that a replicated database on a subscriber isn't being backed up

**What is the expected behavior?**
Would be great to have an option to skip backup checks for replicated databases (subscribers). Due to the small size of the replicated databases I would simply re-initialise them.

**Comment by BrentOzar** [comment]
If you'd like to skip a particular check, dig into the SkipChecksTable functionality. You can create a table with the list of checks you'd like to skip, and pass that database/schema/table name into sp_Blitz, and those checks will be skipped each time they run.
