### ISSUE TITLE
sp_Blitz - CheckID 167 - SQL Agent is Offline for Express Editions of SQL * Bug

### ISSUE THREAD

**Issue by JulieOKC** [BrentOzarULTD/SQL-Server-First-Responder-Kit#420]
sp_Blitz currently lists Express editions of SQL as having "Agent is Currently Offline". All express editions will return this result. Add 

AND @@VERSION NOT LIKE '%express%' 

or adding

AND SERVERPROPERTY('Edition') NOT LIKE '%express%' 

to the where clause will eliminate this problem. Both statements work with SQL 2005 through 2014.

**Comment by BrentOzar** [comment]
Great catch! Added. I used xpress rather than express just because I wanted to make sure it'd work on case-sensitive servers. (I don't have an Express Edition here to test, let alone a case-sensitive, but I'm gambling that'll do the trick.) Thanks.
