### ISSUE TITLE
sp_BlitzCache add check for table variable use

### ISSUE THREAD

**Issue by CharBosell** [BrentOzarULTD/SQL-Server-First-Responder-Kit#422]
During a SQL Performance Tuning class today with Brent, we were discussing the horrible performance of Table variables in SQL queries.  

I would like to see the addition of functionality for the identification of queries that are using table variables in sp_BlitzCache to help in identifying these issues.

**Comment by BlitzErik** [comment]
It would be easy enough to identify table names beginning with '@' in execution plans, but physical tables can also lead with them. There's nothing explicit in an execution plan that differentiates between the two that I know of. At best we'd be guessing.

Here's some repro code.

`USE tempdb

DECLARE @crap TABLE ( col1 INT );

INSERT  @crap
        ( col1 )
SELECT TOP 10000 n.n
FROM    (	SELECT ROW_NUMBER () OVER (ORDER BY (SELECT NULL))
			FROM sys.messages 
			CROSS JOIN sys.messages AS m 
		) n ( n );

SELECT  *
FROM    @crap AS c
WHERE   c.col1 > 0;
GO 

CREATE TABLE [@crap] (col1 INT)

INSERT  [@crap]
        ( col1 )
SELECT TOP 10000 n.n
FROM    (	SELECT ROW_NUMBER () OVER (ORDER BY (SELECT NULL))
			FROM sys.messages 
			CROSS JOIN sys.messages AS m 
		) n ( n );

SELECT  *
FROM    [@crap] AS c
WHERE   c.col1 > 0;

DROP TABLE [@crap]
`

**Comment by BrentOzar** [comment]
I couldn't get this line to work:

CREATE TABLE @craptable

The only way I could get it to work was to frame it in brackets like this:

CREATE TABLE [@craptable]

Which I thought I'd be able to catch because typical table variables aren't framed in square brackets, but the diabolical engine is adding the brackets behind me even when I don't use them:

`<Object Table="[@crap]" Storage="RowStore" />`

**Comment by BlitzErik** [comment]
Yeah. I'm totally down to add it as something to look closer at in warnings, since physical tables that start with @ are pretty rare. The real benefit would be if we could also warn when estimates are skewed because of them, but of course cached plans don't give you actual vs estimated rows.

**Comment by BrentOzar** [comment]
Works! Repro:

`DBCC FREEPROCCACHE
GO
DECLARE @Dining TABLE (DinerName VARCHAR(50));
INSERT INTO @Dining VALUES ('Pope Erik');
SELECT * FROM @Dining;
GO
sp_BlitzCache
`

Produces:

![1](https://cloud.githubusercontent.com/assets/245462/19621163/7c42af24-9851-11e6-809e-28b9722f3e5a.png)
