### ISSUE TITLE
sp_Blitz - Provide date & time of last server restart and SQL restart - New feature

### ISSUE THREAD

**Issue by JulieOKC** [BrentOzarULTD/SQL-Server-First-Responder-Kit#423]
Request a *feature*

**What is the current behavior?** No information is given on how long the server nor SQL have been running.

**The code below has been tested on SQL Server 2005 - 2014, Express, Standard, & Enterprise editions. Windows 2003 - 2012 R2.

SELECT 250, 'Informational', 'Last Server Reboot' ,'','', 'This server was last rebooted: ' +
CAST(DATEADD(SECOND, (ms_ticks/1000)*(-1), GETDATE()) AS nvarchar(25)),'','','?'
FROM sys.dm_os_sys_info

SELECT 250, 'Informational', 'Last SQL Restart' ,'','', 'SQL Server was last restarted: ' +
CAST(login_time AS nvarchar(25)),'','','?'
FROM sys.dm_exec_sessions
WHERE session_id = 1

**Comment by BrentOzar** [comment]
Yeah, it's already there - for non-warning stuff like information, you have to run it with @CheckServerInfo = 1, and you get a bunch more priority 250 stuff like:

79	250	Server Info	SQL Server Last Restart	NULL		Aug 16 2016  7:50PM

**Comment by JulieOKC** [comment]
I see that last SQL restart is in there, but not server restart. We are needing this to find which servers are not patching.

**Comment by BlitzErik** [comment]
How would we determine that via tsql?

**Comment by JulieOKC** [comment]
SELECT 250, 'Informational', 'Last Server Reboot' ,'','', 'This server was last rebooted: ' +
CAST(DATEADD(SECOND, (ms_ticks/1000)*(-1), GETDATE()) AS nvarchar(25)),'','','?'
FROM sys.dm_os_sys_info

**Comment by BlitzErik** [comment]
Ah, cool. I missed the code snippet earlier in the thread. I'll look at
getting this in soon.

**Comment by JulieOKC** [comment]
Brent gave me a heads up about something Microsoft is working on. I would like to try to make this change, but it will be a few days before I can work on it.

**Comment by BlitzErik** [comment]
#428
