### ISSUE TITLE
sp_Blitz: Check that a Fail-safe operator notification option has been selected.

### ISSUE THREAD

**Issue by PhilipCavanagh** [BrentOzarULTD/SQL-Server-First-Responder-Kit#424]
Feature request.

Currently, sp_Blitz checks whether a fail-safe operator has been set for an SQL Server Instance's Agent (SQL Server Agent > Right Click > Properties > Alert System > Fail-safe operator), but does not perform a check that at least one notification method has been selected (E-mail, Pager or Net send).

Could the [Failsafe Operator Not Configured](https://www.brentozar.com/blitz/failsafe-operator-not-configured/) check be extended to include such a notification method check?

**Comment by BrentOzar** [comment]
Sure, do you want to go ahead and give it a shot? Here's the contributing guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md

**Comment by BrentOzar** [comment]
Since @PhilipCavanagh didn't add code, going to go ahead and close this.
