### ISSUE TITLE
sp_BlitzFirst @SinceStartup = 1 reports 4 hour sample immediately after restart

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#425]
Run sp_BlitzFirst @SinceStartup =1 on a server that just started up (either Windows reboot or SQL Server service restart) and it reports 4 hours of sample time in the wait stats section.

![1](https://cloud.githubusercontent.com/assets/245462/17741142/e988a2e0-644f-11e6-9194-a4d687e8a431.png)

(Not a new bug - shows up in July 2016 release too.)

**Comment by RichBenner** [comment]
Is this still an issue? I've been unable to replicate the issue on various VM's with various timezones.

**Comment by BrentOzar** [comment]
Yeah, I've replicated it a few times during demos. I'll work on that this week and get 'er fixed. I'm really curious about what's happening too. I think it has something to do with me immediately firing up a load test with SQLquerystress.

**Comment by BrentOzar** [comment]
Found it. It's this code:

ELSE IF @Seconds = 0 AND CAST(SERVERPROPERTY('edition') AS VARCHAR(100)) <> 'SQL Azure'
    SELECT @StartSampleTime = create_date , @FinishSampleTime = SYSDATETIMEOFFSET()
        FROM sys.databases
        WHERE database_id = 2;

@StartSampleTime is being set to TempDB's creation date, which isn't in UTC.

**Comment by RichBenner** [comment]
Yeah, that makes total sense. I know you said you'd fix this but I couldn't resist changing the call of created_date to calculate based upon getdate() and getutcdate() which seems to fix the issue. I've put it as seconds to allow for the time zones that are half an hour different. Something like this; DATEADD(ss,DATEDIFF(ss, GETDATE(), GETUTCDATE()),create_date)

**Comment by BrentOzar** [comment]
@RichBenner - great point. I used minutes instead of seconds just because I'm learning to be paranoid about large values and overflows with peoples' servers that have been up for years, hahaha.
