### ISSUE TITLE
Add Instant File Initialization check

### ISSUE THREAD

**Issue by TaraKizer** [BrentOzarULTD/SQL-Server-First-Responder-Kit#434]
SQL Server 2016 has an Instant File Initialization message in the Error Log, and now that same message has been backported to SQL Server 2014 SP2.

Would be helpful to have sp_Blitz check for this to avoid having to check it manually.

Pseudocode:
1. Check if 2014 SP2 or greater
2. xp_readerrorlog
3. Is IFI enabled or not? (Don't display anything if version is lower than 2014 SP2)

**Comment by TaraKizer** [comment]
Ready to be tested

**Comment by BrentOzar** [comment]
IT'S ALIVE! IT'S ALLLIIIIIIVE! Nice job, merged & closing.
