### ISSUE TITLE
more powerful duplicate index detection

### ISSUE THREAD

**Issue by chipitsine** [BrentOzarULTD/SQL-Server-First-Responder-Kit#443]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

currently only exactly duplicate indexes are considered as duplicate

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net

**What is the expected behavior?**

I used to use Percona Toolkit for MySQL, there's pt-duplicate-key-checker, it works like a charm

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

**Comment by BrentOzar** [comment]
Borderline duplicates are already caught - indexes that start with the same key. Is that what you're looking for, or can you be more specific?

**Comment by chipitsine** [comment]
I'll provide examples soon

**Comment by chipitsine** [comment]
for example
```
CREATE DATABASE i;

USE i;

CREATE TABLE t (
  i int,  j int,
  UNIQUE KEY u (i,j),
  KEY i (i,j)
);
```

pt-duplicate-key-checker:

```
# ########################################################################
# i.t                                                                     
# ########################################################################

# i is a duplicate of u
# Key definitions:
#   KEY `i` (`i`,`j`)
#   UNIQUE KEY `u` (`i`,`j`),
# Column types:
#	  `i` int(11) default null
#	  `j` int(11) default null
# To remove this duplicate index, execute:
ALTER TABLE `i`.`t` DROP INDEX `i`;

```

**Comment by BrentOzar** [comment]
Err, this is MySQL. We're talking about a SQL Server tool. If you're working with SQL Server, please give examples in SQL Server code, including sp_BlitzIndex's output that doesn't show the duplicates.

If you have two indexes on the same fields, but with different names, sp_BlitzIndex already catches those.

**Comment by chipitsine** [comment]
oh, sorry. I tried the similar indexes on ms sql, them were detected as duplicate.

I'll make more comparision between pt-duplicate-key-checker and sp_BlitzIndex

**Comment by BrentOzar** [comment]
OK, great. I'm going to go ahead and close this since they were correctly detected as duplicates. If you run into a scenario where two indexes start with the same key, and sp_BlitzIndex doesn't identify them as duplicates or borderline duplicates, then open an issue with the repro script. Thanks!
