### ISSUE TITLE
sp_BlitzFirst CheckDate is saved in UTC+0 time zone instead of the local timezone

### ISSUE THREAD

**Issue by ghauan** [BrentOzarULTD/SQL-Server-First-Responder-Kit#445]
I would like to report a bug (IMO) in sp_BlitzFirst in the saving of data to the column CheckDate in the output-table. 

CheckDate in the output table was changed from datetime to datetimeoffset. As far as I can see the CheckDate is based on the variable @StartSampleTime. This variable is set using the SYSDATETIMEOFFSET(), but somewhere along the way, this gets converted to nvarchar before inserted to the CheckDate-column. The conversion that is used (CONVERT(NVARCHAR(100), @StartSampleTime, 127)) seems to put the datetimeoffset into UTC+0 time zone.

To see the difference between the original value and the converted value: `select cast(convert(nvarchar,sysdatetimeoffset(),127) as datetimeoffset) AS ConvertedValue, SYSDATETIMEOFFSET() AS OriginalDatetimeOffset`

I would expect/want the CheckDate to be as it was set from SYSDATETIMEOFFSET(). As it is now, I need to convert this column to my local time zone using SWITHOFFSET (and this might be difficult when changing from/to daylight saving time).  (I have not used datetimeoffset very much, so it might be that what you are doing is intended and not a bug).

I have tested this on SQL SERVER 2014 SP2.
![sp_blitzfirstresultdatetimeoffset](https://cloud.githubusercontent.com/assets/20283957/18501225/3212b356-7a4f-11e6-8520-f06a573e6607.PNG)

**Comment by BrentOzar** [comment]
This was fixed in #425 by setting StartSampleTime to UTC.

**Comment by BrentOzar** [comment]
(To be clear - saving it in UTC is what we *want* to do.)
