### ISSUE TITLE
sp_BlitzFirst - add Always On Availability Groups health & latency checks

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#447]
Here's a starter set of scripts by Tara Kizer.

[AG_Health.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/477378/AG_Health.txt)
[AG_Latency.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/477377/AG_Latency.txt)

**Comment by GregWhiteDBA** [comment]
thanks, not working in 2012 as missing the is_primary_replica in the DMV's.. going to look to refactor and will post back

**Comment by BlitzErik** [comment]
How far back do we want this to be compatible with, @BrentOzar?

**Comment by BrentOzar** [comment]
I'm cool with it skipping 2012 altogether. If you're running AGs on 2012 today, you're unhealthy for sure.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by BrentOzar** [comment]
Updated AG_Health.txt to show more columns.
[AG_Health.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/1201875/AG_Health.txt)

**Comment by BlitzErik** [comment]
This is a year and a half old. Do you wanna keep it open?

**Comment by BrentOzar** [comment]
No, closing - since we don't have an active AG lab, it doesn't make sense for us to develop these.
