### ISSUE TITLE
Add Aaron Bertrand's sp_foreachdb replacement for sp_MSforeachdb into the repo

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#448]
sp_MSforeachdb isn't great - theoretically, it hits every database whether you want it to or not, including offline databases or read-only databases or system databases. Sometimes you wanna skip those.

In practice, it doesn't even hit every database, either - there are instances where it'll skip databases. That's not great either.

So Aaron Bertrand wrote this, and he's agreed to open-source it into the First Responder Kit repo, plus give credit to MSSQLtips:

https://www.mssqltips.com/sqlservertip/2201/making-a-more-reliable-and-flexible-spmsforeachdb/

**Comment by rdameron** [comment]
I'm glad to hear that. Thank you, Aaron and Brent.
I created a version of it that includes an EXCLUDE list for databases. I'll
figure out how to contribute it over the weekend.

**Comment by PerfektNerd** [comment]
Very cool. 

Should we add some basic error handling to the procedure? In Aaron's blog post he said that it was a good next step, but he also mentioned that the error handling should be done 'according to the standards and conventions in your environment.' 

I don't think that precludes building a basic structure that users can extend, though. Even just 'Script failed to run on X database with this error' would be useful.

**Comment by BrentOzar** [comment]
@PerfektNerd and @rdameron - awesome! Once we get sp_foreachdb in here, then you can start separate Github issues for those. I'm aiming to do a release in 1-2 weeks with a round of updates - if you don't have those checked in before the release, that's totally okay. We can always let it go live as-is, and improvements can be an ongoing thing. I'm excited to see this happen too!

**Comment by BrentOzar** [comment]
This was added in pull request #534. Will test this week on 2005-2016.

**Comment by BrentOzar** [comment]
This is in the repo now, closing.
