### ISSUE TITLE
Check if Failover Cluster has multiple active nodes

### ISSUE THREAD

**Issue by matthewtckr** [BrentOzarULTD/SQL-Server-First-Responder-Kit#449]
**Do you want to request a *feature* or report a *bug*?** Feature

**What is the current behavior?** sp_Blitz checks only if the current instance is part of a Failover Cluster (FCI)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net

**What is the expected behavior?** An entry is shown in sp_Blitz if it is running on an FCI cluster, but no other nodes are available for a failover if the current node stops working

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?** N/A - New Feature

**Comment by BrentOzar** [comment]
Oh interesting! That sounds like a great idea. How did you want to check for that? It could be a little tricky since you could have other nodes in the cluster config, but the failover wouldn't actually work (for example, if the other node is down, or if it can't see the shared drives.)

**Comment by matthewtckr** [comment]
Haven't done testing needed for inclusion, but I'd assume something like the following query would probably take care of this:

```
SELECT TOP 1
  999 AS CheckID ,
  50 AS Priority ,
  'Reliability' AS FindingsGroup ,
  'No Failover Cluster Nodes Available' AS Finding ,
  'http://BrentOzar.com/go/node' AS URL ,
  'There are no failover cluster nodes available if the active node fails' AS Details
FROM (
  SELECT SUM(CASE WHEN [status] = 0 AND [is_current_owner] < 1 THEN 1 ELSE 0 END) AS [available_nodes]
  FROM sys.dm_os_cluster_nodes
) a
WHERE [available_nodes] < 1
```

**Comment by matthewtckr** [comment]
To try answering your question, I think that this would just be a best-effort check, in that the data for [dm_os_cluster_nodes](https://msdn.microsoft.com/en-us/library/ms187341.aspx) appears to be based upon what's provided by the cluster quorum resource.

Cases where a hardware/network issue end up preventing the other cluster node from becoming the owner won't likely be caught, though.

**Comment by BrentOzar** [comment]
Thanks @matthewtckr! Merged, priority 20.
