### ISSUE TITLE
sp_blitzFirst - slow delta views can be made faster using a sequence

### ISSUE THREAD

**Issue by fdgit** [BrentOzarULTD/SQL-Server-First-Responder-Kit#450]
hello, 
On my system selecting from the _delta views was extremely slow an and processor intensive.
I got a big improvement by changing sp_blitzFirst to include a bigint batchID (sequences) in 
the @OutputTableNameWaitStats and @OutputTableNamePerfmonStats tables
, and changing the delta views to select on batchID = batchID+1 for the prior, middle etc, rather than
checkdate > prior.checkdate

This change would make it fast enough to allow graphing hourly waits nearly real time, and with minimal resource impact (beyond collection)

**Comment by BrentOzar** [comment]
@fdgit - have you tried indexing rather than altering the table?

**Comment by fdgit** [comment]
I understand.  I tried a variety of indexes, but once I had a few rows, I couldn't keep the performance up.  Adding the batch id was night and day.  The only place the batch id is used is in the where clause of the delta views, and I didn't remove the dates, so it wasn't a breaker for me.  Thanks for the great work btw.
anyway,  here's the script.
[sp_blitzFirst_with_batchID.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/477770/sp_blitzFirst_with_batchID.txt)
