### ISSUE TITLE
sp_Blitz: Check 152 inconsistency

### ISSUE THREAD

**Issue by rpellicaan** [BrentOzarULTD/SQL-Server-First-Responder-Kit#453]
This query has two sets of wait types, which should (to my understanding) be equal. The issue is that the first set has PREEMPTIVE_SP_SERVER_DIAGNOSTICS', PREEMPTIVE_HADR_LEASE_MECHANISM', 'SLEEP_SYSTEMTASK', 'QDS_SHUTDOWN_QUEUE', 'XE_LIVE_TARGET_TVF', while the second set doesn't contain those types. Furthermore, the second set contains 'QDS_ASYNC_QUEUE', while that one is not in the first set.

I think the two sets should be in sync.

**Comment by BrentOzar** [comment]
OK, go ahead and make that change in code. (I don't want you to feel like you have to wait on me for stuff like that.)

Here's how to make a pull request with your code:
https://www.brentozar.com/archive/2015/07/pull-request-101-for-dbas-using-github/
