### ISSUE TITLE
sp_Blitz: Check 182 - doesn't check for CU1, where issue is reported to be solved.

### ISSUE THREAD

**Issue by rpellicaan** [BrentOzarULTD/SQL-Server-First-Responder-Kit#454]
Bug

https://support.microsoft.com/en-us/kb/3178297 states this issue is solved in CU1 (build 2149). This rule doesn't check for the buildnumber, so will give a false positive on CU1 installation of !(Enterprise or Developer).

(Sorry, can't provide prove of this issue at the moment, just based on theory)

**Comment by BrentOzar** [comment]
OK, go ahead and make that change in code. (I don't want you to feel like you have to wait on me for stuff like that.)

Here's how to make a pull request with your code:
https://www.brentozar.com/archive/2015/07/pull-request-101-for-dbas-using-github/

**Comment by BrentOzar** [comment]
(Also - if you can't prove it and it's just based on theory, you either need to have a testable environment where you can test this out, or please don't file bug requests for it without code.)

**Comment by BrentOzar** [comment]
Haven't heard back from @rpellicaan, closing.
