### ISSUE TITLE
sp_Blitz: Check 165 - Doesn't report on Standard Edition at all

### ISSUE THREAD

**Issue by rpellicaan** [BrentOzarULTD/SQL-Server-First-Responder-Kit#455]
Bug

WHERE CLAUSE contains the check : CAST(SERVERPROPERTY('edition') AS VARCHAR(100)) NOT LIKE '%Standard%'. 

This means the check is not performed at all on Standard Edition. This filter on Standard Edition was introduced in #249 , but the check on >128GB wasn't added there.

SQL2008 Standard Edition did not have a limitation. SQL2012 had a 64GB cap, SQL2014 a 128GB cap, so I think the check should include a version dependent check on memorysize.

**Comment by BrentOzar** [comment]
OK, go ahead and make that change in code. (I don't want you to feel like you have to wait on me for stuff like that.)

Here's how to make a pull request with your code:
https://www.brentozar.com/archive/2015/07/pull-request-101-for-dbas-using-github/

**Comment by BrentOzar** [comment]
Haven't heard back from @rpellicaan, closing.
