### ISSUE TITLE
BlitzIndex - Add FG information for an index

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#477]
Migrated from old repo. Originally submitted by Kendra.

"S[tinks] for partitions just because of the way I have them displaying. May not handle that in V1 of this-- could just say [multiple] or something of that sort, or only display them when looking at table detail."

**Comment by BlitzErik** [comment]
@LitKnd closed this from beyond the blog: https://www.littlekendra.com/2017/01/31/which-filegroup-is-that-partition-using-how-many-rows-does-it-have/ 

Will make a feeble attempt at adding additional joins to the partitioning section and then using the code I wrote to show compression detail to also pretty print filegroup info.

**Comment by LitKnd** [comment]
There was a lot of cursing getting the joins to be in the right order for that all to work with both LEFT and RIGHT type partition functions. So I guess it stinks for more reasons than in my original note. Phew.

**Comment by BlitzErik** [comment]
@LitKnd as usual, you're way more ambitious than I am!
