### ISSUE TITLE
sp_Blitz - look for slow data file growths in the default trace

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#478]
Inspired by issue in old repo, originally submitted by Brent.

This could check for data and log file growths that take longer than a second or two, or maybe 1 second/MB or something.

**Comment by BlitzErik** [comment]
Code migrated from old repo:

`IF NOT EXISTS ( SELECT 1
FROM #SkipChecks
WHERE DatabaseName IS NULL AND CheckID = 999 ) 
BEGIN
DECLARE @default_trace_filename NVARCHAR(1000);
DECLARE @threshold_ms int
SET @threshold_ms = 500 /* threshold is half a second */

IF EXISTS(SELECT 1 FROM sys.traces WHERE [is_default] = 1)
BEGIN
    -- Get the name of the current default trace
    SELECT @default_trace_filename = CAST([path] AS NVARCHAR(1000))
    FROM sys.traces
    WHERE [id] = 1 AND [is_default] = 1;

    SET @default_trace_filename =   REVERSE(SUBSTRING(REVERSE(@default_trace_filename),CHARINDEX('_',REVERSE(@default_trace_filename))+1,LEN(REVERSE(@default_trace_filename)))) + 
                                    REVERSE(SUBSTRING(REVERSE(@default_trace_filename),1,CHARINDEX('.',REVERSE(@default_trace_filename))));

    ;WITH q AS (
        SELECT TOP 100 PERCENT
            ftg.StartTime
            ,DB_NAME(ftg.databaseid) AS DatabaseName 
            ,ftg.Filename
            ,(ftg.IntegerData*8)/1024.0 AS GrowthMB
            ,(ftg.duration/1000.0) AS DurMS
            ,(ftg.duration/1000.0) / ((ftg.IntegerData*8)/1024.0) AS MS_per_MB
        FROM ::fn_trace_gettable(@default_trace_filename, DEFAULT) AS ftg
        WHERE (ftg.EventClass = 92  -- Date File Auto-grow
            OR ftg.EventClass = 93) -- Log File Auto-grow
            AND ((ftg.duration/1000.0) / ((ftg.IntegerData*8)/1024.0)) > @threshold_ms -- more than half a second per MB
    )
    insert into #blitzresults 
                (checkid, 
                databasename, 
                priority, 
                findingsgroup, 
                finding, 
                url, 
                details) 
    SELECT DISTINCT 999, 
        DatabaseName, 
        200, 
        'Autogrow Events', 
        'AutoGrowth events longer than 0.5s', 
        'http://BrentOzar.com/go/new_link', 
        'File ' + [filename] + ' of ' + [DatabaseName] + ' grew on ' + cast(StartTime as nvarchar) + ' with ' + CAST([GrowthMB] AS nvarchar) + 
        ' and took longer than ' + CAST(@threshold_ms as nvarchar) + 'ms / MB (' + CAST(DurMS as nvarchar) + 'ms per event)'
    FROM q
END
END`

**Comment by BlitzErik** [comment]
Code is stupid.

**Comment by BrentOzar** [comment]
I took the really cheating route. There was already a check 151 that looked for slow log file growths (>15 seconds) - I just changed that to also look at data file growths.
