### ISSUE TITLE
BlitzIndex - look for out of date stats on objects with changed data

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#480]
Migrated from old repo. Originally submitted by Brent.

`set transaction isolation level read uncommitted;

SELECT DISTINCT
currenttime=GETDATE()
,tablename=object_name(i.object_id)
, typeDesc=o.type_desc
, indexName=i.[name]
, statisticsLastUpdated = STATS_DATE(i.object_id, i.index_id)
, hoursSinceUpdate = datediff(hh,getdate(),STATS_DATE(i.object_id, i.index_id))
, si.rowmodctr
FROM sys.indexes i (nolock)
JOIN sys.objects o (nolock) on
i.object_id=o.object_id
JOIN sys.sysindexes si (nolock) on
i.object_id=http://si.id
and i.index_id=si.indid
where

o.type <> 'S' --ignore system objects
and STATS_DATE(i.object_id, i.index_id) is not null
order by si.rowmodctr desc`

Probably need 3 separate alerts: long time since update (one month?), large amount of updates (over 15K rowmodctr), or small objects (maybe only 50 rows, but they're all new since stats were done).

**Comment by BlitzErik** [comment]
#512

**Comment by BrentOzar** [comment]
(Don't close these before they get merged)

**Comment by BrentOzar** [comment]
Oh, this one is closed, hahaha
