### ISSUE TITLE
sp_BlitzCache should check for compute scalar operators that call functions

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#482]
Migrated from old repo. Originally submitted by Jeremiah.

"Generate a warning based on presence and in execution count."

**Comment by BlitzErik** [comment]
![image](https://cloud.githubusercontent.com/assets/11590415/19546183/779ebdb6-965b-11e6-870b-a94dd63f69ac.png)

**Comment by BrentOzar** [comment]
Works! Here's how to repro it:

`CREATE FUNCTION [dbo].[BC_SF] ( @uid INT )
RETURNS BIGINT
    WITH RETURNS NULL ON NULL INPUT,
         SCHEMABINDING
AS
    BEGIN
        DECLARE @BCount BIGINT;
        SELECT  @BCount = COUNT_BIG(*)
        FROM    [dbo].[Badges] AS [b]
        WHERE   [b].[UserId] = @uid
        GROUP BY [b].[UserId];
        RETURN @BCount;
    END;
GO
DBCC FREEPROCCACHE
GO
SELECT TOP 10 *, dbo.BC_SF(Id) FROM dbo.Users u WHERE DisplayName LIKE 'Brent%'
GO
sp_BlitzCache
`

And it produces:

![1](https://cloud.githubusercontent.com/assets/245462/19621144/121fb4a2-9851-11e6-9579-ba4712c28514.png)
