### ISSUE TITLE
sp_BlitzCache - Identify CLR Functions

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#497]
Migrated from old repo. Originally submitted by Kendra.

"I'm not saying that they're always evil. Just that it's good to know where the lil jerks are hiding."

**Comment by BlitzErik** [comment]
Using a CLR function from T-SQL Querying (because I can't write C# for the life of me), we get this in the XML

<UserDefinedFunction FunctionName="[CLR].[dbo].[RegExMatch]" IsClrFunction="true">

<CLRFunction Assembly="t_sql_querying_project" Class="UserDefinedFunctions" Method="RegExMatch" />

They're both under the RelOp node. 

I don't know if there's a good way to get CLR stored procs detected. 

Also, if we're adding this, it may follow that we start getting clr information:


total_clr_time, last_clr_time, min_clr_time, max_clr_time from sys.dm_exec_query_stats

CLR Compiled Func, CLR Compiled Proc from sys.dm_exec_cached_plans

**Comment by BlitzErik** [comment]
![image](https://cloud.githubusercontent.com/assets/11590415/19546182/74fe3cda-965b-11e6-9f93-757587e9bd54.png)

**Comment by BrentOzar** [comment]
I am sure as hell not testing this.
