### ISSUE TITLE
BlitzIndex is warning of identity column end of range too soon for negative starting value

### ISSUE THREAD

**Issue by TaraKizer** [BrentOzarULTD/SQL-Server-First-Responder-Kit#511]
BlitzIndex is warning about an identity column being near the end of the data type's range when it's no where near running out yet. This identity column was started at negative 2.1 billion. BlitzIndex needs to take into account when negative values are used for the starting value.
![image](https://cloud.githubusercontent.com/assets/16884153/19368219/ea246d98-9153-11e6-9cc9-4f1f9cd3145a.png)

**Comment by BlitzErik** [comment]
It looks like BlitzIndex already does this. Can you repro it locally? Not sure which conditions to code around prevent what you saw.

![image](https://cloud.githubusercontent.com/assets/11590415/19386690/a3ade69c-91e3-11e6-8c14-b14c9c252220.png)

**Comment by BlitzErik** [comment]
@TaraKizer I'm going to close this unless you have anything to add

**Comment by TaraKizer** [comment]
I tried to reproduce whatever issue I was referring to but can't figure out what the original problem was even after looking back at the client BlitzIndex output where this issue occurred. But I didn't provide enough detail in this bug report to work on it later, offline from the client. Closing as a result.
