### ISSUE TITLE
BlitzIndex should alert when an index on only an identity column has fillfactor < 100

### ISSUE THREAD

**Issue by TaraKizer** [BrentOzarULTD/SQL-Server-First-Responder-Kit#517]
Feature request: BlitzIndex should alert when an index on only an identity column has fillfactor < 100. 

Currently it warns if fill factors are less than 80, but those might be okay if they are GUIDs. But if they are identity columns, we want to know about those.

**Comment by TaraKizer** [comment]
Too scared to open up sp_BlitzIndex to figure out where this should go, but here's a query that finds the indexes that are on identity columns and are less than 100% fillfactor:

SELECT * 
FROM sys.index_columns ic
JOIN sys.indexes i ON ic.object_id = i.object_id AND ic.index_id = i.index_id
JOIN sys.columns c ON i.object_id = c.object_id
WHERE i.fill_factor NOT IN (0, 100)
  AND c.is_identity = 1
  AND NOT EXISTS (SELECT * FROM sys.index_columns ic2 WHERE ic.object_id = ic2.object_id AND ic.index_id = ic2.index_id AND index_column_id > 1);

**Comment by BlitzErik** [comment]
If it helps, we already collect this. 

It's in two tables: 
- #IndexSanity has fill_factor 
- #IndexColumns tells you if it's an identity column

You could do something like:

```
SELECT *
FROM  #IndexSanity i
JOIN    #IndexColumns ic ON
i.object_id=ic.object_id
AND ic.is_identity=1
AND i.fill_factor NOT IN (0, 100)
```
