### ISSUE TITLE
Arithmetic overflow error converting expression to data type int in sp_Blitz

### ISSUE THREAD

**Issue by pkandra** [BrentOzarULTD/SQL-Server-First-Responder-Kit#526]
Testing the 20161014 version using SQL Server 2014 and received the following error:

Msg 8115, Level 16, State 2, Procedure sp_Blitz, Line 469 [Batch Start Line 0]
Arithmetic overflow error converting expression to data type int.
Warning: Null value is eliminated by an aggregate or other SET operation.

Seems to be this line of the procedure:
        SELECT DATEDIFF(MINUTE, create_date, CURRENT_TIMESTAMP) * 60000  
            FROM    sys.databases  
            WHERE   name='tempdb';

**Comment by dtodd2016** [comment]
Hi

I suggest changing this to
SELECT DATEDIFF(MINUTE, create_date, CURRENT_TIMESTAMP) * 60000.0

Making this change allowed the procedure to run on systems that were previously given the above error.

This current version changeed what was previously on two lines 
        SELECT @MSSinceStartup = DATEDIFF(MINUTE, create_date, CURRENT_TIMESTAMP)
            FROM    sys.databases
            WHERE   name='tempdb';

		SET @MSSinceStartup = @MSSinceStartup * 60000;

which didn't have this issue.

Regards
  David Todd

**Comment by BrentOzar** [comment]
Great catch guys! I went ahead and changed it to * 60000.0. It's fixed in the dev branch if you want to download that latest version. We'll probably do a new release closer to the end of the month with a few other fixes.

**Comment by mjswart** [comment]
I was just about to raise this issue. You guys are on the ball!

**Comment by BrentOzar** [comment]
I love handling this kind of thing via Github, makes my life so much easier, heh.

**Comment by dbaab** [comment]
I am testing sp_Blitz v5.2 (April 2017) and receiving this following error message - 
Msg 8115, Level 16, State 2, Procedure sp_Blitz, Line 523 [Batch Start Line 1]
Arithmetic overflow error converting expression to data type int.

I see this was an issue in the older version..

**Comment by BrentOzar** [comment]
OK, go ahead and upgrade to the current version. Thanks!

**Comment by dbaab** [comment]
I am receiving this message while testing the current version?
	SET @Version = '5.2';
	SET @VersionDate = '20170406';

**Comment by BrentOzar** [comment]
That's not the current version.

**Comment by BrentOzar** [comment]
To get the current version, click Code at the top of the page, then click Download.

**Comment by dbaab** [comment]
Thanks, I am receiving the error only on production and can't recreate it on test servers.

**Comment by dbaab** [comment]
Getting the same error with current version too

**Comment by BrentOzar** [comment]
OK, go ahead and open a new issue with the exact error message and version information. (The line numbers will be different on the new version, for example.) Thanks!

**Comment by dbaab** [comment]
will do, Thanks!

**Comment by Gizzy04** [comment]
I had incurred the same error message and found this page. I double-checked to ensure that I had the newest version. I checked the code fix as stated above but continued to get an arithmetic overflow. 
Version 5.4
VersionDate 20270603
I actually found the largest INT one can use in milliseconds is :2146999999

Upon looking at the code deeper and checking against the tables what I found is that the error was being generated during the insert into #BlitzResults (Line 536). The DATEADD function can not handle the size in milliseconds for a server that has been online for a length of time or has not been reset. Simple change:

FROM:
> 'Someone ran DBCC SQLPERF to clear sys.dm_os_wait_stats at
> approximately: ' + CONVERT(NVARCHAR(100), DATEADD(ms, (-1 *
> @MsSinceWaitsCleared), GETDATE()), 120))

TO:

> 'Someone ran DBCC SQLPERF to clear sys.dm_os_wait_stats at
> approximately: ' + CONVERT(NVARCHAR(100), DATEADD(DD, (-1 *
> @MsSinceWaitsCleared/3600000/24), GETDATE()), 120))

Once I converted the variable from milliseconds to "days" no more overflow. You can also use HH also. The difference is only about an hour. I tested with milliseconds equaling 1 day to milliseconds equaling 7 to 8 months.
