### ISSUE TITLE
BlitzCache double warns about Expensive Remote Queries

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#532]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
It will list expensive remote queries twice, which it shouldn't

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com

**What is the expected behavior?**
It should list them once

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All

**Comment by BlitzErik** [comment]
#533

**Comment by BrentOzar** [comment]
Fixed, closing.
