### ISSUE TITLE
sp_foreachdb - make the parameters compatible with sp_MSforeachdb

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#535]
**Do you want to request a _feature_ or report a _bug_?**
Feature

**What is the current behavior?**
sp_foreachdb has different parameters than sp_MSforeachdb. Let's make it an exact drop-in replacement, even if this means silently ignoring parameters we're not doing anything with for now.

ALTER proc [sys].[sp_MSforeachdb]
    @command1 nvarchar(2000), @replacechar nchar(1) = N'?', @command2 nvarchar(2000) = null, @command3 nvarchar(2000) = null,
    @precommand nvarchar(2000) = null, @postcommand nvarchar(2000) = null

ALTER PROCEDURE dbo.sp_foreachdb
    @command NVARCHAR(MAX),
    @replace_character NCHAR(1) = N'?',
    @print_dbname BIT = 0,
    @print_command_only BIT = 0,
    @suppress_quotename BIT = 0,
    @system_only BIT = NULL,
    @user_only BIT = NULL,
    @name_pattern NVARCHAR(300) = N'%', 
    @database_list NVARCHAR(MAX) = NULL,
    @recovery_model_desc NVARCHAR(120) = NULL,
    @compatibility_level TINYINT = NULL,
    @state_desc NVARCHAR(120) = N'ONLINE',
    @is_read_only BIT = 0,
    @is_auto_close_on BIT = NULL,
    @is_auto_shrink_on BIT = NULL,
    @is_broker_enabled BIT = NULL

**Comment by paweltajs** [comment]
There should be @replacechar instead @replace_character also.

**Comment by BrentOzar** [comment]
@paweltajs - yep, that's in the initial issue report:

@command1 nvarchar(2000), @replacechar nchar(1) = N'?', @command2 nvarchar(2000) = null,
