### ISSUE TITLE
sp_foreachdb - handle database names the same way as sp_MSforeachdb

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#536]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
Run this:
EXEC dbo.sp_MSforeachdb @command1 = 'USE [?]; SELECT DB_NAME();'
and it works fine. Run this:
EXEC dbo.sp_foreachdb @command = 'USE [?]; SELECT DB_NAME();'

And you get errors:

```
Msg 105, Level 15, State 1, Line 1
Unclosed quotation mark after the character string '[AdventureWorks2014]; SELECT DB_NAME();'.
Msg 102, Level 15, State 1, Line 1
Incorrect syntax near '[AdventureWorks2014]; SELECT DB_NAME();'.
Msg 105, Level 15, State 1, Line 1
Unclosed quotation mark after the character string '[ClearTrace]; SELECT DB_NAME();'.
Msg 102, Level 15, State 1, Line 1
Incorrect syntax near '[ClearTrace]; SELECT DB_NAME();'.
```

It looks like sp_foreachdb is adding brackets. This works fine:
EXEC dbo.sp_foreachdb @command = 'USE ?; SELECT DB_NAME();'

We should probably work the same way sp_MSforeachdb does by default.

**Comment by t0mburton** [comment]
I was just caught out by this myself. I've defaulted the suppress_quotename param to true in this [commit](https://github.com/t0mburton/SQL-Server-First-Responder-Kit/commit/755ef74dead74e8dba265fe73c30d3b297a243bf).

I can submit a PR if you would like or were you looking for a different solution?
