### ISSUE TITLE
sp_BlitzCache - look up plans by object name

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#543]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
If you want to get an execution plan for a known stored proc name, then run the evaluation rules against it, it's kinda hard.

**What is the expected behavior?**
Add an object name parameter, and get the query hash & plan hash from here, and then use the existing lookup by query hash functionality:

select qp.query_plan, *
from sys.dm_exec_procedure_stats ps
CROSS APPLY sys.dm_exec_query_plan(ps.plan_handle) qp
where object_id = object_id('someobject')

**Comment by BlitzErik** [comment]
![image](https://cloud.githubusercontent.com/assets/11590415/19544197/27aa12b6-964b-11e6-8d92-6e3a85481a62.png)

**Comment by BrentOzar** [comment]
Works great. Known issue: if you if you pass in a stored proc name that isn’t in cache, we’ll help you by returning everything instead.
