### ISSUE TITLE
sp_BlitzIndex - check for scalar UDFs in computed fields

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#545]
**Do you want to request a _feature_ or report a _bug_?**
Feature

**What is the current behavior?**
If you have a computed field with a scalar UDF, all access on the table is single-threaded. (Not sure if this is true for selects when the field is persisted, but definitely is for insert/update/deletes.)

**What is the expected behavior?**
Add a new warning about scalar UDFs in computed fields.

**Comment by BlitzErik** [comment]
Yeah, it's true for selects. I got this one.

**Comment by BlitzErik** [comment]
#550

**Comment by BlitzErik** [comment]
Merged, closing.
