### ISSUE TITLE
sp_Blitz - add application detection

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#55]
When CheckUserDatabaseObjects = 1, and we're looping through databases, check for the existence of objects that indicate 3rd party apps like Dynamics, Sharepoint, session state, etc. 

Bonus points: if they're present, check for best practices for those apps (like maxdop = 1, trace flags, etc) gleaned from the app's best practices docs.

**Comment by tonyfountain** [comment]
This would be awesome.  I find myself using the overrides check to ignore certain things on a SharePoint server... for example "Auto Create Stats Disabled" and "Auto Update Stats Disabled"...

**Comment by BrentOzar** [comment]
This would be a pretty big project to tackle in sp_Blitz. We've got some ideas on how we want to solve this pain point, but we're not going to try to do it in T-SQL, so closing this issue. It'll reappear in another form years from now.
