### ISSUE TITLE
sp_BlitzCache - add warning for cursor

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#556]
Example snippet:
CursorPlan CursorName="" CursorActualType="Keyset" CursorRequestedType="Keyset" CursorConcurrency="Optimistic" ForwardOnly="false"

CursorConcurrency Optimistic means it's using RCSI, and it's not read-only.

**Comment by BrentOzar** [comment]
Here's a repro script with StackOverflow to put a plan into cache:

declare @p1 int, @p2 int
exec sp_cursoropen @p1 output,N'SELECT Id FROM StackOverflow.dbo.Users WHERE Id = 26837',1, 4, @p2 output
select @p1, @p2
GO

After the query, there are two parameters - 1 and 4 in this case (keyset, optimistic concurrency). First one is the cursor type, second one is the concurrency type. Here's the list of options:

https://msdn.microsoft.com/en-us/library/ff848737.aspx

**Comment by BlitzErik** [comment]
The reason we weren't catching these is the same reason PTP doesn't -- BlitzCache doesn't pull StmtCursor out of XML. We identify cursors like this, which for some reason doesn't pick up any cursor attributes when I query it directly, which...

![image](https://cloud.githubusercontent.com/assets/11590415/19619599/59fcfdec-9839-11e6-8043-d14ac02e55d1.png)

Okay, so there's a bug in BlitzCache. I think it's been there forever. For some reason, PlanHandle wasn't populating for everything. It's happening here:

![image](https://cloud.githubusercontent.com/assets/11590415/19619719/aaa08eba-983b-11e6-8a35-f04da3070c4b.png)

When I change it to this, it picks up on the fact that this plan uses a cursor correctly.

![image](https://cloud.githubusercontent.com/assets/11590415/19619727/c1c1c230-983b-11e6-82a7-21304f6f16d0.png)

![image](https://cloud.githubusercontent.com/assets/11590415/19619728/cf064812-983b-11e6-908b-fa8571094371.png)

This gets us somewhere, but I'll still have to get the cursor options out by adding a step to parse StmtCursor, which I can do in a couple ways.

If you want full plan information for cursors, I can add a step like this

```
WITH XMLNAMESPACES('http://schemas.microsoft.com/sqlserver/2004/07/showplan' AS p)
INSERT #statements
SELECT  QueryHash ,
        SqlHandle ,
		PlanHandle,
        q.n.query('.') AS statement
FROM    ##bou_BlitzCacheProcs p
        CROSS APPLY p.QueryPlan.nodes('//p:StmtCursor') AS q(n) 
```

If you just want a few specific pieces of information about the cursor type, I can process them separately. 

HAPPY SATURDAY!

**Comment by BlitzErik** [comment]
We're good to get cursor information now. Will add it in on the plane, probably.

![image](https://cloud.githubusercontent.com/assets/11590415/19619976/2217ef42-9841-11e6-8e8f-a9a9012775f8.png)

**Comment by BrentOzar** [comment]
Works!
