### ISSUE TITLE
sp_BlitzCache - skip unused grant query if grant = min memory grant setting

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#557]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
When I run sp_BlitzCache and queries only got the minimum memory grant, and they used less, the unused memory grant is firing. Row #3 in this result set is an example - this server has the default min memory grant setting of 1024.

![1](https://cloud.githubusercontent.com/assets/245462/19621088/f7873490-984f-11e6-980b-6c78b7808336.png)

**What is the expected behavior?**
Let's check the sp_configure setting for min memory per query, and if the query grant = that number, don't fire the unused memory grant warning.

**Comment by BlitzErik** [comment]
#573

**Comment by BrentOzar** [comment]
Thanks! Closing.
