### ISSUE TITLE
sp_Blitz - Add check for local SQL accounts using the password the same as the account name

### ISSUE THREAD

**Issue by HBollah** [BrentOzarULTD/SQL-Server-First-Responder-Kit#561]
Adding a check that will look at the local SQL account and check to see if the password has been set the same as the account name e.g.

username : sqluser
password : sqluser

**Comment by BrentOzar** [comment]
Thanks, but we're not adding additional security checks in sp_Blitz. We'd recommend a more robust tool for security audits.

**Comment by HBollah** [comment]
Oh. I was just about to add the code into a branch of the code :-(

Nevermind.

**Comment by BrentOzar** [comment]
Make sure you read the project's documentation before you write code. Go to the home page of the project, and there's instructions on how to contribute. We talk about making an issue to talk about the design first to make sure it's a good fit for sp_Blitz and friends. Thanks!
