### ISSUE TITLE
sp_Blitz - check for unused snapshot isolation level

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#562]
**Do you want to request a _feature_ or report a _bug_?**
Feature 

**What is the current behavior?**
People are enabling snapshot isolation (not RCSI) but not starting any queries with snapshot isolation. I bet we could detect that by glancing at the plan cache and see if there's a field on query stats or similar DMV that shows the isolation level, but without shredding XML.

(From Gail Shaw's tempdb talk at Summit.)

**Comment by BlitzErik** [comment]
BlitzFirst reports on isolation level of running queries. Might work well
as a headline news warning there.

**Comment by BrentOzar** [comment]
Well, hello there. I just always assumed that different isolation levels might produce different plans, but it turns out they don't. (I can see a scenario where if I was serializable, I wanna get out of the table as fast as possible, maybe making different decisions about key lookups vs table scans.) Turns out isolation levels aren't stored in the plan, and don't cause different plans to be cached. Repro:

![1](https://cloud.githubusercontent.com/assets/245462/22784679/9dda84ea-ee96-11e6-9414-11a2251d8408.png)

So if we can't detect it from past query executions, and can only get it from current sessions, then it doesn't make sense to alert people. No sense in warning folks if it just happens that nobody is using that isolation level right now. Closing.
