### ISSUE TITLE
sp_BlitzFirst - the URL column does not link to the correct part of the page

### ISSUE THREAD

**Issue by rickripe** [BrentOzarULTD/SQL-Server-First-Responder-Kit#563]
SQL 2014 Web Edition

sp_BlitzFirst gives us the issues with some hyperlinks:

https://www.brentozar.com/sql/wait-stats/#SOS_SCHEDULER_YIELD
http://www.brentozar.com/sql/wait-stats/#PAGEIOLATCH_SH
http://www.brentozar.com/sql/wait-stats/#IO_COMPLETION

all of these link to the correct BO page but not the entry in question.

**Comment by BrentOzar** [comment]
Rick - thanks for stopping by and creating your first issue!

One housekeeping tip - whenever you're filing a bug report, you'll want to keep issues separated. If you're reporting multiple bugs, create multiple tickets. I'm going to edit your issue to only focus on the first thing you reported (hyperlinks) - then, for any additional issues you'd like to create, go ahead and open *separate* issues for each one of them.

Thanks!

**Comment by BrentOzar** [comment]
Great catch, fixed! Note that for some waits, like PAGEIOLATCH_SH, we have a section for multiple different PAGEIOLATCH* waits, so we can't have a single hyperlink that takes you to the PAGEIOLATCH section. You can scroll down to it though.

**Comment by rickripe** [comment]
Thanks Brent!
