### ISSUE TITLE
sp_Blitz - Check for number of quorum votes in Always On

### ISSUE THREAD

**Issue by HBollah** [BrentOzarULTD/SQL-Server-First-Responder-Kit#564]
**Do you want to request a _feature_ or report a _bug_?**
Feature

**Feature Request**
When sp_Blitz runs, to do a count on the number_of_quorum_votes from the sys.dm_hadr_cluster_members and alert the user if this vote is 2. If one of the servers goes offline, then SQL will be going bye bye

**Comment by BrentOzar** [comment]
@HBollah - it's a little trickier than that. You could have a sum of 2 if there was 1 remaining SQL Server with a vote, plus a working file share. You'll also want to check whether the node's state is offline or online.

If you talk through the pseudocode here, it'll probably be helpful for other folks to check your work. Otherwise, I like where you're going with it - just talk through the code first here before writing it.

**Comment by HBollah** [comment]
Thanks Brent. Just from you're first paragraph you've made me re-think my initial logic on this one and can see why it's trickier (and partially my fault for not researching it properly, but we'll gloss over that one).

For the first check we would see if there is only 2 nodes being used for the quorum vote.
Do a count of total quorum votes
If it is equal to 2 
Then notify the user that they haven't got a majority vote and has the potential for SQL to go offline if a node goes offline / lost network.

The next check would be to look at the total number of quorum votes greater than 2 and from that do some other checks.
Do a count of total quorum votes
If quorum count >= 3
Then do a check that no nodes are offline
If quorum count > sum of member state (reason for sum, is that online is 1 and offline is 0)
Then notify the user that they had a quorum vote offline that will need investigation

I await your feedback :-)

**Comment by BrentOzar** [comment]
OK, I hate to say this, but I'm going to hazard a guess that you haven't done a lot of work with WSFC quorum setup. The idea is great, but you're missing a lot in the decision flow tree. Let's leave this idea here for someone else with more WSFC quorum experience to run with. Don't start coding for now. Thanks for the idea, though!

**Comment by BrentOzar** [comment]
Since we haven't gotten code contributions on this, I'm going to go ahead and close it. Sounds like a great idea, but the execution's going to be hard work.
