### ISSUE TITLE
sp_Blitz - MAXDOP & Cost Threshold for Parallelism

### ISSUE THREAD

**Issue by RichBenner** [BrentOzarULTD/SQL-Server-First-Responder-Kit#568]
Cost Threshold for Parallelism & MAXDOP settings are only reported if they are anything other than default (5 & 0). These settings are not adequate for the vast majority of systems any more. 

[Brent Ozar 5 SQL Server Settings to Change](https://www.brentozar.com/archive/2013/09/five-sql-server-settings-to-change/)

I suggest it should warn if these settings are at the default and link back to the appropriate page within brentozar.com so that people can understand these settings and correct them. I've seen a lot of servers with CPU issues that have these as default, changing them made this CPU perform much better.

I'd suggest keeping at a priority 200 setting if they are not default (implying that somebody has considered and changed this setting) and making a higher priority level if they are currently at the defaults.

**Comment by BrentOzar** [comment]
@RichBenner - it already does warn if they're anything other than the default. I'm not sure what you're recommending?

**Comment by RichBenner** [comment]
Yes, it's great that it reports if the default has been changed. My suggestion is that the defaults are so poor that in the databases that I've looked at these settings are still default which is an issue in itself. I'm not sure if you would agree but when I RDP onto a customer site and they're reporting CPU being maxed out, one of the first things I check are these settings and on 90% of cases where people don't have an onsite dedicated DBA (or an accidental DBA) then these settings haven't been touched, This is usually because they've never realised they were settings that existed let alone should be changed. I think a gentle suggestion in sp_Blitz to say that these settings are still set to default and they may look at changing them if they deem necessary may help. I know in a few instances that changing these settings has really helped.

**Comment by BrentOzar** [comment]
OH, I see what you're saying. Let me try to rephrase:

Feature request: add two separate alerts for:

 -  Cost Threshold is at the default of 5
 -  MAXDOP is at the default of 0, and the system has more than 1 socket, or more than 8 cores per socket

Does that sum it up well? If so, sure, you've got the green light to start coding.

**Comment by RichBenner** [comment]
@BrentOzar Yeah that sums it up, i'll put in a pull request and get on it. Would you prefer the alerts to be at the current 200 level or shall I change them (or doesn't it matter at this point?)

**Comment by BrentOzar** [comment]
Yeah, I'd agree, 200 makes sense. Thanks!

**Comment by RichBenner** [comment]
Is there a page like BrentOzar.com/go/Parallelism around? I was going to point it towards https://www.brentozar.com/blitz/configuring-parallelism/ but that's a bit of a mouth full.

**Comment by BrentOzar** [comment]
Yeah: http://BrentOzar.com/go/cxpacket

**Comment by BrentOzar** [comment]
Great, thanks! Tweaked the code a little, and it'll be in this month's release. Good job!
