### ISSUE TITLE
sp_BlitzCache - add warnings for locking hints

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#570]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
We see LCK_R% waits indicating serializable lock hints, like updlock/holdlock. Would be nice to throw a warning in sp_BlitzCache whenever we see lock hints in the query, like HOLDLOCK, REPEATABLEREAD, UPDLOCK.

**Comment by BlitzErik** [comment]
I'm not sure there's a way to get this from the XML, aside from the statement text. If you know of one, I'm all ears. If you want to wild card search statement text, I'm all tears.

**Comment by BlitzErik** [comment]
There are some we can add from the XML, but not the locking hints.

`<IndexScan Ordered="false" ForcedIndex="false" ForceScan="false" NoExpandHint="false" Storage="RowStore">`

**Comment by BlitzErik** [comment]
Closing
