### ISSUE TITLE
sp_BlitzIndex bug with suggested fix

### ISSUE THREAD

**Issue by DavidWimbush** [BrentOzarULTD/SQL-Server-First-Responder-Kit#574]
Your Blitz stuff rocks. Thank you. But(!) there is a problem with the new check 93 (statistics with filters).

When the filter definition is longer than 128 characters the quotename() returns null which causes the insert into #BlitzIndexResults to fail because null is not allowed in the details column. The proc execution fails.

This started failing after I updated to version 4.4. It's a new check introduced in that version.

I fixed it by changing this line:
`'The statistic ' + QUOTENAME(s.statistics_name) +  ' is filtered on ' + QUOTENAME(s.filter_definition) + '. It could be part of a filtered index, or just a filtered statistic. This is purely informational.' ,`

to:
`'The statistic ' + QUOTENAME(s.statistics_name) +  ' is filtered on [' + s.filter_definition + ']. It could be part of a filtered index, or just a filtered statistic. This is purely informational.' ,`

Hope this helps.

David Wimbush

**Comment by BlitzErik** [comment]
Great catch, thanks. Hopefully we don't have to worry about SQL injection from a filtered statistic definition, right? :)
