### ISSUE TITLE
sp_BlitzIndex Supported Versions

### ISSUE THREAD

**Issue by RichBenner** [BrentOzarULTD/SQL-Server-First-Responder-Kit#577]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
sp_BlitzIndex header text (lines 42-86) states this only works on 2008 + but the validation betweek lines 680 and 686 validate it as fine for 2005 +. 

**What is the expected behavior?**
I imagine this needs to be updated to check for the correct version number minor correction below which would correct the issue (version now <= 9 rather than 8 and text altered from 2005 to 2008).

        --Validate SQL Server Verson

        IF (SELECT LEFT(@SQLServerProductVersion,
              CHARINDEX('.',@SQLServerProductVersion,0)-1
              )) <= 9
        BEGIN
            SET @msg=N'sp_BlitzIndex is only supported on SQL Server 2008 and higher. The version of this instance is: ' + @SQLServerProductVersion;
            RAISERROR(@msg,16,1);
        END

**Comment by BrentOzar** [comment]
Makes sense! You're good to go to change the code & add a pull request. (Normally we suggest that folks have a discussion in the issue notes here but this one's a slam dunk.) Thanks!

**Comment by RichBenner** [comment]
Ok cool, done.

**Comment by BrentOzar** [comment]
Thanks sir!
