### ISSUE TITLE
sp_Blitz crashing SQL Server 2008 R2 10.50.2861

### ISSUE THREAD

**Issue by benamada** [BrentOzarULTD/SQL-Server-First-Responder-Kit#579]
I ran sp_Blitz for the first time, v20161022, and it crashed my SQL Server.  It's SQL Server 2008 R2 10.50.2861 running on Windows Server 2008 R2.  I had a brief chat with Brent and he said he recalls on older versions of SQL (e.g. 2008), querying some DMV's lead to crashes.  Fortunately SQL server is running normally after restarting it, but no one is expecting a health check procedure to crash their SQL Server.

Entries related to the crash were captured in the SQL Server error log.  I've attached the relevant entries here [sql_log_1.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/573216/sql_log_1.txt).

The README for the First Responder Kit mentions that SQL 2000 and 2005 are not supported.  I assume that means 2008 is supported?

2 suggestions I have are either:

1. sp_Blitz be updated to not run DMV's against a SQL instance that has been known to crash when querying DMVs.
2. Or sp_Blitz refuse to run on SQL instances where querying DMVs may crash.

The outcome of a SQL Server crash could obviously be a lot more catastrophic than what I experienced.

Thank you.

**Comment by BrentOzar** [comment]
We haven't seen anyone be able to repro this, so we're going to go ahead and close this. If you can repro it on a from-scratch build, that'd be interesting - but otherwise, my guess is this has something to do with something more complicated.
