### ISSUE TITLE
sp_BlitzIndex - remove FileTables from heap warning

### ISSUE THREAD

**Issue by mKarous** [BrentOzarULTD/SQL-Server-First-Responder-Kit#581]
The "_Active/Inactive Tables Without Clustered Indexes_" warning currently involves also the FileTables in the database. 
Because it is not possible to create any clustered index for the FileTable, it may worth removing this type of table form this check.

**Comment by BrentOzar** [comment]
Great, that makes sense. We don't have any FileTable/FileStream type stuff here in the lab, and the check sounds like a good idea, so you're clear to go ahead and start coding it. If you haven't coded in Github before, here's how to get started:

http://blog.davidecoppola.com/2016/11/howto-contribute-to-open-source-project-on-github/

Thanks!

**Comment by BlitzErik** [comment]
No movement, closing.
