### ISSUE TITLE
Feature - Identitfy missmatch between vCPUs in VM and SQL processors

### ISSUE THREAD

**Issue by mtengmo** [BrentOzarULTD/SQL-Server-First-Responder-Kit#590]
If you hotadd vCPUs to a VM that runs SQL Servers, these new vCPUs will not be added to SQL Server without reconfigure (enterprise).  It´s a high risk that someone forgot to reconfigure SQL Server after adding vCPUs. 
https://technet.microsoft.com/en-us/library/bb964703(v=sql.105).aspx
From host performance counters, it will be hard to identity these "skew" load on vCPUs if measuring Processor\Total. 

Is it possible to identity this with sp_blitz?

**Comment by BrentOzar** [comment]
Hmm - this area isn't really for "is this possible" type questions. Your best bet to find out if something is possible with T-SQL is to pose the question on http://dba.stackexchange.com along with as many technical details as possible.

Closing this. Thanks!
