### ISSUE TITLE
sp_Blitz - Use new dmv columns (2016 sp1) to look for LPIM

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#592]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
We check a different DMV for locked pages to determine if it's enabled

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com

**What is the expected behavior?**
On newer versions, we can use additional DMV functionality

sys.dm_os_sys_info has two new columns: sql_memory_model, sql_memory_model_desc

![image](https://cloud.githubusercontent.com/assets/11590415/20360320/457128ea-ac01-11e6-8455-1934021cf032.png)

![image](https://cloud.githubusercontent.com/assets/11590415/20360325/4912a226-ac01-11e6-8ff9-3b32a644021c.png)

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
2016 SP1 (so far)

**Comment by BrentOzar** [comment]
This was easy because I didn't have to add a new check - there was already a LPIM check and URL, just getting more detail now.
