### ISSUE TITLE
sp_Blitz - Use new column (2016 sp1) to check for IFI enabled

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#593]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
We look at the error log to determine whether it's on or not

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com

**What is the expected behavior?**
We should use the new instant_file_initialization_enabled column in sys.dm_server_services to check. 

![image](https://cloud.githubusercontent.com/assets/11590415/20360634/7c30abca-ac02-11e6-91c6-117b560b7192.png)

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
2016 SP1 (so far)

**Comment by HenrikStaunPoulsen** [comment]
It would also be great if we could monitor changes to 
`SELECT * FROM sys.database_scoped_configurations`

**Comment by BlitzErik** [comment]
Sure, open a new issue for that.
