### ISSUE TITLE
sp_BlitzFirst -- do we want to warn about maintenance tasks running for log backups?

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#595]
**Do you want to request a *feature* or report a *bug*?**
Question!

**What is the current behavior?**
In sp_BlitzFirst, we warn if maintenance tasks are running during the day. This triggers for log backups as well as FULL and DIFF. I don't think it's something to be concerned about. It seems like we also give the wrong set of data for log backups (info for full backups)

![image](https://cloud.githubusercontent.com/assets/11590415/20408895/742c149e-ace5-11e6-9b0d-64585ad40f6e.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com

**What is the expected behavior?**
Either don't trigger the warning when the backup is a log file, or present different information when it's a log backup. Looking at the code, we just grab 

`WHERE r.command LIKE 'BACKUP%';`

We could change it to `'BACKUP[_]DATABASE%'` or `'AND NOT LIKE 'BACKUP[_]LOG%'`

Presenting different info would be a little more challenging, so it might be worth it to try to short circuit the log backup info.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All

**Comment by BrentOzar** [comment]
I do think we still wanna warn about diffs and logs if they're running for a while, because it could still be performance-impacting. How about if they've been running for more than, say, 60 seconds?

**Comment by BlitzErik** [comment]
Maybe 5 minutes for Diffs and 1 minute for Logs? Diffs can get dicey! But up to you.

**Comment by BrentOzar** [comment]
I like the time thing. Changed it to only alert for requests running >5 minutes. It's theoretically possible that someone could be backing up a whole bunch of databases, and each one would run under 5 minutes, and this alert wouldn't fire. Ah, well.
