### ISSUE TITLE
sp_Blitz - add check for non-default sys.database_scoped_configurations settings

### ISSUE THREAD

**Issue by HenrikStaunPoulsen** [BrentOzarULTD/SQL-Server-First-Responder-Kit#598]
**Do you want to request a *feature* or report a *bug*?**
Feature

It would be great if we could monitor changes to 
`SELECT TOP (50) * FROM sys.database_scoped_configurations` on all databases.
Please note there may be a bug in SQL Server, see [http://dba.stackexchange.com/questions/155684/bug-in-database-scoped-configurations] about database_scoped_configurations

**What is the expected behavior?**
Maybe something like this:
```

DROP TABLE IF EXISTS #h;

CREATE TABLE #h(dbname sysname, configuration_id INT, name sysname, 
  value SQL_VARIANT,  value_for_secondary SQL_VARIANT);

DECLARE @sql nvarchar(max) = N'', @base nvarchar(max) = N'insert into #h
  (dbname, configuration_id, name, value,value_for_secondary)  SELECT TOP ($c$) 
  $db$ as dbname, * FROM $qdb$.sys.database_scoped_configurations;';

SELECT @sql += REPLACE(REPLACE(REPLACE(@base, N'$qdb$', QUOTENAME(name)), 
  N'$db$', CHAR(39) + name + CHAR(39)), N'$c$', RTRIM(COUNT(*) OVER()))
FROM sys.databases WHERE state = 0;

PRINT @sql;
EXEC sys.sp_executesql @sql;
SELECT * FROM #h 
WHERE 
(value =0 AND name NOT IN ('MAXDOP', 'LEGACY_CARDINALITY_ESTIMATION'))
OR
(value =1 AND name NOT IN ('PARAMETER_SNIFFING', 'QUERY_OPTIMIZER_HOTFIXES'))

```

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2016 onwards

**Comment by BlitzErik** [comment]
Awesome. Check out other parts of Blitz to see how we validate versions that support certain code branches.

**Comment by BrentOzar** [comment]
You'll get a laugh out of this - I coded it in about an hour, but then I spent the next hour trying to figure out why I was only getting 1 row back. I didn't bother to read the StackOverflow bug. My bad.

**Comment by HenrikStaunPoulsen** [comment]
Just one hour? I think I spent the better part of a day...
Thank you very much for adding this check.
