### ISSUE TITLE
Update #FileStats output to use different column names for PowerShell Invoke-Sqlcmd to process correctly

### ISSUE THREAD

**Issue by runamuk0** [BrentOzarULTD/SQL-Server-First-Responder-Kit#599]
**Do you want to request a *feature* or report a *bug*?**
There is a bug in the sp_BlitzFirst result sets where #FileStats is output using the same column names twice.  When I execute sp_BlitzFirst in PowerShell Invoke-Sqlcmd the PowerShell returns the error message: 
`Invoke-Sqlcmd : Duplicate column names are not permitted in SQL PowerShell. To repeat a column, use a column alias for the duplicate column in the format Column_Name AS New_Name.
At line:1 char:13
+ $datasets = Invoke-Sqlcmd -ServerInstance $ComputerName -Database $da ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SyntaxError: (:) [Invoke-Sqlcmd], SqlPowerShellSqlExecutionException
    + FullyQualifiedErrorId : DuplicateColumnNameErrorMessage,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand`

Please update the SELECT statement output to use different column names for the qsNow and qsFirst aliases to eliminate the error:

            -------------------------
            --What happened: #FileStats
            -------------------------
            SELECT [qsNow].[ID],
                   [qsNow].[Pass],
                   [qsNow].[SampleTime],
                   [qsNow].[sql_handle],
                   [qsNow].[statement_start_offset],
                   [qsNow].[statement_end_offset],
                   [qsNow].[plan_generation_num],
                   [qsNow].[plan_handle],
                   [qsNow].[execution_count],
                   [qsNow].[total_worker_time],
                   [qsNow].[total_physical_reads],
                   [qsNow].[total_logical_writes],
                   [qsNow].[total_logical_reads],
                   [qsNow].[total_clr_time],
                   [qsNow].[total_elapsed_time],
                   [qsNow].[creation_time],
                   [qsNow].[query_hash],
                   [qsNow].[query_plan_hash],
                   [qsNow].[Points], 
                   [qsFirst].[ID] AS [ID2],
                   [qsFirst].[Pass] AS [Pass2],
                   [qsFirst].[SampleTime] AS [SampleTime2],
                   [qsFirst].[sql_handle] AS [sql_handle2],
                   [qsFirst].[statement_start_offset] AS [statement_start_offset2],
                   [qsFirst].[statement_end_offset] AS [statement_end_offset2],
                   [qsFirst].[plan_generation_num] AS [plan_generation_num2],
                   [qsFirst].[plan_handle] AS [plan_handle2],
                   [qsFirst].[execution_count] AS [execution_count2],
                   [qsFirst].[total_worker_time] AS [total_worker_time2],
                   [qsFirst].[total_physical_reads] AS [total_physical_reads2],
                   [qsFirst].[total_logical_writes] AS [total_logical_writes2],
                   [qsFirst].[total_logical_reads] AS [total_logical_reads2],
                   [qsFirst].[total_clr_time] AS [total_clr_time2],
                   [qsFirst].[total_elapsed_time] AS [total_elapsed_time2],
                   [qsFirst].[creation_time] AS [creation_time2],
                   [qsFirst].[query_hash] AS [query_hash2],
                   [qsFirst].[query_plan_hash] AS [query_plan_hash2],
                   [qsFirst].[Points] AS [Points2]
            FROM #QueryStats qsNow
              INNER JOIN #QueryStats qsFirst ON qsNow.[sql_handle] = qsFirst.[sql_handle] AND qsNow.statement_start_offset = qsFirst.statement_start_offset AND qsNow.statement_end_offset = qsFirst.statement_end_offset AND qsNow.plan_generation_num = qsFirst.plan_generation_num AND qsNow.plan_handle = qsFirst.plan_handle AND qsFirst.Pass = 1
            WHERE qsNow.Pass = 2

**What is the current behavior?**
The error message: 
`Invoke-Sqlcmd : Duplicate column names are not permitted in SQL PowerShell. To repeat a column, use a column alias for the duplicate column in the format Column_Name AS New_Name.
At line:1 char:13
+ $datasets = Invoke-Sqlcmd -ServerInstance $ComputerName -Database $da ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SyntaxError: (:) [Invoke-Sqlcmd], SqlPowerShellSqlExecutionException
    + FullyQualifiedErrorId : DuplicateColumnNameErrorMessage,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com
In PowerShell 
`Import-Module -Name SQLServer
$ComputerName = 'localhost'
$database = 'Portal'
$datasets = Invoke-Sqlcmd -ServerInstance $ComputerName -Database $database -Query 'EXEC [dbo].[sp_BlitzFirst] @Seconds = 1, @ExpertMode = 1;' -QueryTimeout 600 -OutputAs DataSet -Verbose -OutputSqlErrors $true -IncludeSqlUserErrors`

**What is the expected behavior?**
No errors output from PowerShell.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

**Comment by BlitzErik** [comment]
Since this is a problem with PowerShell specifically, and none of us actually do much with PowerShell, this is something we'd probably accept if you made a pull request with the fixes. Just make sure you account for all the places that the table is used.

**Comment by BrentOzar** [comment]
@runamuk0 - since you haven't added code for this in a few weeks, I'm going to go ahead and close it. If you decide you want to tackle it, go ahead and reopen this when you're ready to start working on the code. Thanks!

**Comment by runamuk0** [comment]
Hi Brent,
I just submitted a pull request (#642) for my code fixes. Sorry for the delay.
