### ISSUE TITLE
sp_BlitzCache - should warn when processing XML

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#600]
**Do you want to request a *feature* or report a *bug*?**
Ironic feature 
**What is the current behavior?**
None 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com

**What is the expected behavior?**
We should indicate plans that use XQuery 
**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All

**Comment by BrentOzar** [comment]
HAHAHAHAHAHAHAHA, nice.

**Comment by BlitzErik** [comment]
I changed my mind about this. There are too many weird ways this can surface, like the XML Reader function, or XML indexes.
