### ISSUE TITLE
sp_blitzcache - missing 'cost' when logged to table

### ISSUE THREAD

**Issue by tim-3** [BrentOzarULTD/SQL-Server-First-Responder-Kit#609]
**1.)** Please add the feature to allow the 'cost' to be logged when outputting sp_blitzcache to a table.

**2.)** When i run the following query:

**exec sp_blitzcache @Top = 10, @sortorder='cpu'**

There is a cost column displayed in the results ... However when i log the results to a table the column is not there :

**exec sp_blitzcache @Top = 10, @sortorder='cpu', @outputdatabasename = 'DBA', @outputschemaname = 'dbo', @outputtablename = 'tblBlitzCache_20161123'**

**select * from dba.dbo.tblBlitzCache_20161123**

**3.)** When the results are logged to a table it would be great if the 'cost' could also be included.

**Comment by BlitzErik** [comment]
Sure, I can get this out in the next release.

**Comment by tim-3** [comment]
Hey Erik

When i run the following command :

exec sp_blitzcache @Top = 10, @sortorder='cpu', @outputdatabasename = 'DBA', @outputschemaname = 'dbo', @outputtablename = 'tblBlitzCache_20161212'

It errors :+1: 
------------------------------------------------------------------------------------------------------------------
.
.
.
Checking for bad scans and plan forcing
Checking for ColumnStore queries operating in Row Mode instead of Batch Mode
Checking for computed columns that reference scalar UDFs
Gathering additional plan level information
Warning: Null value is eliminated by an aggregate or other SET operation.
Attempting to get stored procedure name for individual statements
Trace flag checks
Setting configuration values
Checking for query level SQL Server issues.
Checking for forced parameterization and cursors.
Populating Warnings column
Writing results to table.
Msg 121, Level 15, State 1, Line 1
The select list for the INSERT statement contains more items than the insert list. The number of SELECT values must match the number of INSERT columns.

(0 row(s) affected)

------------------------------------------------------------------------------------------------------------------

**Comment by BlitzErik** [comment]
Oh jeez. This was working for me before. It looks like I may have ctrl + z'd back a step or something. I'm going to push a quick change to the dev branch. Can you grab a copy from there to test?

**Comment by tim-3** [comment]
Sure done ... I ran some tests and it looks to now include the costs which
is great a couple of observations :


*1. Naming*

Something i noticed that when you run this command :

       *exec sp_blitzcache @Top = 10, @sortorder='cpu'*

It costy is called '*Cost*' .... and when you run this command to log to a
table :

      *exec sp_blitzcache @Top = 10, @sortorder='cpu', @outputdatabasename
= 'DBA', @outputschemaname = 'dbo', @outputtablename =
'tblBlitzCache_20161211'*

The cost is called '*QueryPlanCost*' .... Was there a reason for giving it
two different names?


*2. Results *

I notice that when it is saved to a table it doubles up its rows .... Its
not a show stopper but thought i would mention it.
Hopefully the screen dump below will show you what i mean.


[image: Inline images 1]

Anyway nice work Erik !!!

Cheers
Tim

**Comment by BlitzErik** [comment]
The column naming was, ironically, to cut down on the margin for error.

Can you open a new issue for the double insert? That's a new one to me.

Thanks!
