### ISSUE TITLE
sp_BlitzCache legend output not sorted correctly

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#610]
Should be by Priority, FindingsGroup, Finding. Looks like it's by Priority, CheckID. Note the Priority 50 stuff in this screenshot.

<img width="304" alt="1" src="https://cloud.githubusercontent.com/assets/245462/20678811/fea80348-b54c-11e6-89d1-f43fa5ac1363.png">

**Comment by BlitzErik** [comment]
This used to sort ONLY on Priority before. I chose the alternate to make sure the plan cache information and thank you stay in order and at the bottom.

**Comment by BlitzErik** [comment]
Closing
