### ISSUE TITLE
Possibly outdated sp_blitz warning for "Target Recovery Time" on SQL2016 SP1

### ISSUE THREAD

**Issue by aclenscorp** [BrentOzarULTD/SQL-Server-First-Responder-Kit#616]
Running on a freshly installed SQL2016 SP1
Microsoft SQL Server 2016 (SP1) (KB3182545) - 13.0.4001.0 (X64) 

Created a new database and the default for "Target Recovery Time" was set to 60. I believe this is the new default setting. Whether it's a good setting or not, I do not know.

sp_blitz returned a 210 priority warning "Non-Default Database Config" for this TARGET_RECOVERY_TIME value. 

Comment on this thread indicates other users are seeing the same thing:

_"The default value is 60.  I've run a clean install of Microsoft SQL Server 2016 (RTM) - 13.0.1601.5 (X64) and confirmed that the default for model, msdb, and tempdb is sset to 60.  master is 0."_

https://msdn.microsoft.com/en-us/library/hh403416.aspx?f=255&MSPPError=-2147217396

**Comment by RichBenner** [comment]
This is interesting. I've just upgraded a 2016 RTM (developer) instance to SP1 and it has different databases at different levels, 

SELECT name, target_recovery_time_in_seconds from sys.databases

gives this output

![image](https://cloud.githubusercontent.com/assets/20068038/20962762/9715cab8-bc62-11e6-8fb8-cd561d02e8df.png)

Which were all set to zero before. I've modified the code like so

    /* New default target recovery time in 2016 SP1. Now set to 60 */
    INSERT INTO #DatabaseDefaults
    SELECT 'target_recovery_time_in_seconds', 0, 142, 210, 'Target Recovery Time Changed', 'http://BrentOzar.com/go/dbdefaults', NULL
    FROM sys.all_columns 
    WHERE name = 'target_recovery_time_in_seconds' AND object_id = OBJECT_ID('sys.databases')
    AND ((@ProductVersionMajor = 13 AND @ProductVersionMinor <= 4000) OR @ProductVersionMajor < 13);
    INSERT INTO #DatabaseDefaults
    SELECT 'target_recovery_time_in_seconds', 60, 142, 210, 'Target Recovery Time Changed', 'http://BrentOzar.com/go/dbdefaults', NULL
    FROM sys.all_columns 
    WHERE name = 'target_recovery_time_in_seconds' AND object_id = OBJECT_ID('sys.databases')
    AND ((@ProductVersionMajor = 13 AND @ProductVersionMinor > 4000) OR @ProductVersionMajor > 13);

But this obviously now throws up a level 210 error for the tables that are still set to zero (on 2016 SP1).

It seems a lot of work to code out a separate block for just this check, is this something it would make sense to allow for in the cursor DatabaseDefaultsLoop?

**Comment by BlitzErik** [comment]
Does it only do that for databases in Simple?

**Comment by RichBenner** [comment]
Doesn't look like it, I thought it may be compatibility level too but doesn't look like it;

![image](https://cloud.githubusercontent.com/assets/20068038/20969939/2f4551c6-bc83-11e6-9a27-59b846a03c2c.png)

I've looked through the whole of sys.databases (ordered by recovery time) and can't see any of the entries that would explain why some are set to 60 and some to 0, really strange.

**Comment by RichBenner** [comment]
However I've just changed Database2 from the above example to compatibility level 130 and it's still showing at a recovery time of 0, even after a server reboot. I wonder perhaps if it's got something to do with the compatibility level of the table at the point when the service pack is applied.

![image](https://cloud.githubusercontent.com/assets/20068038/20970330/f67e8b4e-bc84-11e6-9e00-0e15cc5bb6ac.png)

**Comment by aclenscorp** [comment]
We just ran sp_blitz as a best practice after we completed a migration onto SQL 2016 SP1 and I noticed this was called out so I thought I'd mention it. All of our databases were taken to compatibility level 130 after the migration, and none of the migrated db's are at 60. 

However, when I had created a new database (not named Database3, but still a scratch database), it had 60 (probably taken from model) and sp_blitz flagged it as a non-standard setting.

I assume any new databases created after 2016SP1 will be 60 unless you manually change the model setting.

**Comment by BrentOzar** [comment]
Yeah, it can be either 0 or 60 depending on a few bugs I've seen like this one:

https://connect.microsoft.com/SQLServer/feedback/details/1049478/ssdt-generates-2012-option-for-target-2008-when-target-is-a-dacpac

Hard coded 0 and 60 as acceptable values, will be in the next release. Thanks!
