### ISSUE TITLE
 Cannot resolve collation conflict

### ISSUE THREAD

**Issue by dalehhirt** [BrentOzarULTD/SQL-Server-First-Responder-Kit#621]
**Do you want to request a *feature* or report a *bug*?**
I am reporting a bug.

**What is the current behavior?**
When I run sp_BlitzIndex against an Azure database, I get the following error:

Msg 2787, Level 16, State 1, Procedure dbo.sp_BlitzIndex, Line 1620 [Batch Start Line 10]
Invalid format specification: '%.%' THEN 1 ELSE 0 END AS is_function,
   					   		   'ALTER TABLE ' + QUOTENAME(s.name) + '.' + QUOTENAME(t.name) + 
   					   		   ' ADD ' + QUOTENAME(c.name) + ' AS ' + cc.definition  + 
							   CASE WHEN is_persisted = 1 THEN ' PERSISTED' ELSE '' END + ';' AS [column_definition]
   					   FROM    [helixdata].sys.computed_columns AS cc
   					   JOIN    [helixdata].sys.columns AS c
   					   ON      cc.object_id = c.object_id
   					   		   AND cc.column_id = c.column_id
   					   JOIN    [helixdata].sys.tables AS t
   					   ON      t.object_id = cc.object_id
   					   JOIN    [helixdata].sys.schemas AS s
   					   ON      s.schema_id = t.schema_id
					   OPTION (RECOMPILE);'.
Msg 50000, Level 16, State 1, Procedure dbo.sp_BlitzIndex, Line 1624 [Batch Start Line 10]
helixdata database failed to process. Cannot resolve collation conflict between "Latin1_General_BIN" and "SQL_Latin1_General_CP1_CI_AS" in add operator occurring in SELECT statement column 11.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com

Running sp_BlitzIndex with no arguments.

**What is the expected behavior?**

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

SQL Azure (SQL Server 2016)

**Comment by BlitzErik** [comment]
This was closed in #607 

Please search for issues before filing.

Thanks!

**Comment by dalehhirt** [comment]
Thank you.  I did search, but apparently I need to get better at it.
