### ISSUE TITLE
sp_BlitzCache - warn about forced index hints

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#625]
Look for this in the plan and warn that the query author forced an index:
TableScan Ordered="false" ForcedIndex="true" ForceScan="false" NoExpandHint="false" Storage="RowStore"

Example plan:
https://www.brentozar.com/pastetheplan/?id=Hy2Clr4me

**Comment by BlitzErik** [comment]
#583

**Comment by BrentOzar** [comment]
You are a god among men.

By the way, I am typing this onscreen in class.
