### ISSUE TITLE
sp_Blitz - Product Version Checks - Bug?

### ISSUE THREAD

**Issue by RichBenner** [BrentOzarULTD/SQL-Server-First-Responder-Kit#628]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

We check if @ProductVersionMajor >= 10 and @ProductVersionMinor >= 50 in a lot of places. It looks like this should be looking for anything on 2008 R2 and newer but this isn't how the minor product version is working. 

For SQL Server 2016 SP1 (13.00.4001.00) the major version is 13.00 and the minor version is 4001.00. The only version of SQL Server with a minor version less than 50 was build 8.00.047 which was for SQL Server 2000 EAP4 (source: https://sqlserverbuilds.blogspot.co.uk/). 

Is this check working correctly (checking for SQL 2008+ boxes) or should it be checking for 2008 R2 and newer? If the former, do we even need the minor version check?

To find these lines search for 'IF @ProductVersionMajor >= 10 AND @ProductVersionMinor >= 50 ' in sp_Blitz.

**Comment by BlitzErik** [comment]
Oh, barf, those are all mine. What the heck was on my mind? Or rather, my clipboard?

Yeah, all the DMVs it's hitting are 2008 and up. Given the amount of 2008 boxes this has been run on, I'd say they're "working" but, yeah.

**Comment by RichBenner** [comment]
Worth a quick fix to remove the minor version check or leave as-is?

**Comment by BlitzErik** [comment]
I'll take care of this one. It's my goof. I can test it against our 2008 instance to make sure it doesn't break anything.

Thanks!
