### ISSUE TITLE
sp_BlitzFirst -- make stored plan cache analysis (or lack thereof) more clear

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#632]
**Do you want to request a *feature* or report a *bug*?**
Enhancement

**What is the current behavior?**
We select data from #QueryStats even if @CheckProcedureCache = 0 (which it is by default)

**What is the expected behavior?**
We should replace it with dummy text that tells people the plan cache wasn't analyzed, and how to either analyze it with sp_BlitzFirst, or with sp_BlitzCache (link to frk.org)

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All

**Comment by BrentOzar** [comment]
Ooo, yeah, that's a great point.
