### ISSUE TITLE
Standard edition vs Enterprise edition

### ISSUE THREAD

**Issue by HenrikStaunPoulsen** [BrentOzarULTD/SQL-Server-First-Responder-Kit#650]
**Do you want to request a *feature* or report a *bug*?**
this must be considered a bug now.

**What is the current behavior?**
sp_Blitz reports a warning; The [mydb] database is using Compression.  If this database is restored onto a Standard Edition server, the restore will fail.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com
run Exec sp_Blitz   :-)

**What is the expected behavior?**
No warning if SQL Server is 2016 SP1 and above

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
only SQL Server 2016 SP1 affected so far. It works in old versions.

**Comment by BlitzErik** [comment]
I think for this we'd just change the wording of the message.

**Comment by BlitzErik** [comment]
Closed in #683

**Comment by HenrikStaunPoulsen** [comment]
Hi Erik, 
Thank you very much for fixing this.
Best regards,
Henrik

**Comment by BlitzErik** [comment]
My pleasure!
