### ISSUE TITLE
Number of Instances - sp_Blitz

### ISSUE THREAD

**Issue by RichBenner** [BrentOzarULTD/SQL-Server-First-Responder-Kit#651]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**

Currently sp_Blitz doesn't check for multiple SQL Servers running on the same box, it should if possible.

**What is the expected behavior?**

It would be very useful if this came up as an error. Multiple instances on the same box is not going to be a good thing, people may not even know about it when analysing a server.

The code below will find this information, the concern would be whether this would require a certain level of permissions in order to execute;

	IF OBJECT_ID('tempdb..#Instances') IS NOT NULL
		DROP TABLE #Instances;
	CREATE TABLE #Instances(Value nvarchar(100),
	 InstanceNames nvarchar(100),
	 Data nvarchar(100))
	
	INSERT INTO #Instances
	EXECUTE xp_regread
	  @rootkey = 'HKEY_LOCAL_MACHINE',
	  @key = 'SOFTWARE\Microsoft\Microsoft SQL Server',
	  @value_name = 'InstalledInstances'
	
	SELECT
		InstanceNames 
	FROM #Instances 

**Which versions of SQL Server and which OS are affected by this issue?**

All

**Comment by RichBenner** [comment]
In fact, I've just read that this is an unsupported stored procedure. Sucks. I'm assuming not a good plan to include this in the proc?

**Comment by BrentOzar** [comment]
Yeah, I was just gonna say - there's also security gotchas with that. I'd love to pull it off (the feature), but it's tough to do with pure T-SQL at this point. Closing. Good idea though.
