### ISSUE TITLE
sp_BlitzCache -- Warn for filters referencing scalar valued functions

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#652]
I'm a broken record on this stuff, but I keep finding it. 

SVFs in Filter operators as catchable:

![image](https://cloud.githubusercontent.com/assets/11590415/21289846/2fd3a710-c475-11e6-8090-b6adecd3b2eb.png)

The path will be something like Relop/Filter/Predicate/UserDefinedFunction

Can probably use the code to find them in Compute Scalars as a base.

**Comment by BlitzErik** [comment]
This creates a table and a function and runs a query that produces a filter that references a scalar udf.

```
CREATE TABLE dbo.Numbers (Number INT)

CREATE FUNCTION [dbo].[Multiplier] (@ID INT) 
RETURNS INT
WITH SCHEMABINDING
AS
BEGIN
RETURN @ID * 2
END
GO

SELECT * 
FROM dbo.Numbers AS n
WHERE n.Number < dbo.Multiplier(n.Number)
```

The result when you run BlitzCache is:

![image](https://cloud.githubusercontent.com/assets/11590415/21290495/9c3ae9e4-c48a-11e6-8a83-8a9c8438352a.png)

**Comment by BrentOzar** [comment]
Works beautifully! Nice job.
