### ISSUE TITLE
sp_BlitzCache -- Session data will be analyzed across different users

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#653]
**Do you want to request a *feature* or report a *bug*?**
If you run sp_BlitzCache in one SSMS window, and then right after in another window, the second session will analyze the first session's global temp table data.

**What is the current behavior?**
That thing up there

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com

**What is the expected behavior?**
We have a SPID column in our global temp tables that analysis queries should be filtering on

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All

**Comment by BlitzErik** [comment]
This can cause performance issues if someone on the same server runs BlitzCache with a high @Top number. 

With 10 queries, it just about doubles execution time, because it's hitting 20 plans rather than 10 plans.

**Comment by BlitzErik** [comment]
Tested with various configurations, working as far as I can tell

```
EXEC master.dbo.sp_BlitzCache @ExpertMode = 1
EXEC master.dbo.sp_BlitzCache @ExportToExcel = 1
EXEC master.dbo.sp_BlitzCache @OutputDatabaseName = 'CLR', @OutputSchemaName = 'dbo', @OutputTableName = 'BC_12172016'
EXEC master.dbo.sp_BlitzCache @DatabaseName = 'StackOverflow', @Top = 100, @SortOrder = 'writes', @ExpertMode = 1
```

**Comment by BrentOzar** [comment]
OH MAN, this makes so much sense. This is also why the footer legend stuff shows warnings that aren't in the top result set, I bet.

**Comment by BrentOzar** [comment]
Hahaha, works great. That'll be a fun one to announce, heh.

**Comment by BlitzErik** [comment]
I don't think astrophysicists have a unit of measure that could quantify the embarrassment that it took me years of using this tool to notice a problem. And that I maybe misspelled embarrassment, and potentially misspelled now, too.
