### ISSUE TITLE
sp_BlitzIndex -- Smarter missing index algorithm

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#662]
**Do you want to request a *feature* or report a *bug*?**
Enhance!ment

**What is the current behavior?**
We just multiply uses * impact * query cost and divide by days uptime to get the estimated benefit number. Under most circumstances this is fine, but sometimes your top missing index request is some weird thing that ran once, had a cost of over 9000 query bucks, and the index would have like a 20% impact. 

This isn't helpful. We should weight benefit numbers so those with high executions and high impact percentages get prioritized. Better bang for the buck.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All

**Comment by RichBenner** [comment]
How would you want the weighting to work? The easiest way would be something like this (numbers pulled out of the air);

    (uses * 10) * (impact * 20) * (cost * 1)

But that's not really a smarter way of doing it although it would work. Would it be better to include a CASE that checks for whether a query has been run less than, say, once a day and reduce the weighting of that query accordingly? It could even be scaled depending on if it's very lightly used;

    CASE
        WHEN uses = 1 THEN 1
        WHEN uses / server uptime < 0.1 THEN 1
        WHEN uses / server uptime < 1 THEN 10
        WHEN uses / server uptime >= 1 THEN 20
    END AS Weighting

**Comment by BlitzErik** [comment]
The weighting would also have to take into account missing index impact. 

Say, anything with an impact less than 70% would get a lower score. 

Although I'm not particularly eager to nuke suggestions from orbit -- sometimes they're a notable cry for help, even if SQL isn't asking for something terrifically impactful.  

It may be easier to designate 'high value missing indexes' into separate buckets if uses or impact don't break a certain threshold.
