### ISSUE TITLE
sp_blitzIndex @DatabaseName, @SchemaName, @TableName not working

### ISSUE THREAD

**Issue by mscro** [BrentOzarULTD/SQL-Server-First-Responder-Kit#666]
Do you want to request a feature or report a bug?
Bug

exec sp_blitzIndex @DatabaseName, @SchemaName, @TableName  is not picking up the @databaseName value given

Results:
Starting run. sp_BlitzIndex(TM) v4.6 - December 10, 2016
Create temp tables.

DB
Oh, this is awkward. I can't find the table or indexed view you're looking for in that database.
Please check your parameters.
Msg 50000, Level 1, State 1

**Which versions of SQL Server and which OS are affected by this issue? 
Microsoft SQL Server 2012 (SP3) (KB3072779) - 11.0.6020.0 (X64) 
	Oct 20 2015 15:36:27 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor)

Did this work in previous versions of our procedures?**
Yes

**Comment by BlitzErik** [comment]
Can you provide any further information on this? Not sure how we could troubleshoot with this info. Basic tests of those variables work fine over here.

**Comment by BlitzErik** [comment]
No more info, closing.
