### ISSUE TITLE
Trying to get SP_blitzfirst results and getting error converting date/time from character string.

### ISSUE THREAD

**Issue by tiewoods** [BrentOzarULTD/SQL-Server-First-Responder-Kit#667]
I did download the version:
20161210
 
I have to be doing something wrong.
I will try to describe what I am doing so maybe you can point me in the right direction.
 
I run the sp_blitz stored procedures from my recent download.
I run this to capture results, and this works fine.
EXEC sp_BlitzFirst @Seconds = 60
, @OutputDatabaseName = 'Data_Warehouse_Pilot'
, @OutputSchemaName = 'dbo'
, @OutputTableName = 'BlitzFirstResults'
, @OutputTableNameFileStats = 'BlitzFirstResults_FileStats'
, @OutputTableNamePerfmonStats = 'BlitzFirstResults_PerfmonStats'
, @OutputTableNameWaitStats = 'BlitzFirstResults_WaitStats'
 
A sample of this data in the BlitzFirstResults table
 
 1   USNS035   2016-12-22 13:04:43.8011422 +00:00   -1   sp_BlitzFirst 2016-12-10 00:00:00.0000000 +00:00   From Your Community Volunteers
 
I run this Statement and I get the error:
EXEC sp_BlitzFirst 
@AsOf = '2016-12-22 13:04',
@OutputDatabaseName = 'Data_Warehouse_Pilot',
  @OutputSchemaName = 'dbo', 
  @OutputTableName = 'BlitzFirstResults'
 
I get this error:
Setting up configuration variables
Msg 241, Level 16, State 1, Line 1
Conversion failed when converting date and/or time from character string.
 
 
I do think it must be something I am doing wrong and I will go through my steps again to see if I can isolate this.

**Comment by BrentOzar** [comment]
Closing, this is a known bug:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/499

Just make sure to search existing issues before you file a new one. Thanks!

**Comment by tiewoods** [comment]
Would it be possible to update your example on this site:
https://www.brentozar.com/askbrent/?utm_source=Brent+Ozar+Unlimited%C2%AE+List&utm_campaign=0785720830-6_Month_DBA_Training_Plan_Week_19&utm_medium=email&utm_term=0_8e3e861dd9-0785720830-296546377

Your example shows @AsOf with a date instead of a null value.

I was able to get this to work following the suggestions in #499, and set @AsOf = null.

**Comment by BrentOzar** [comment]
Yep, we'll fix that when we fix #499. Thanks!
