### ISSUE TITLE
sp_blitz "Many Plans for One Query" but sp_BlitzCache @ExpertMode = 1 shows all query hashes as NULL

### ISSUE THREAD

**Issue by m60freeman** [BrentOzarULTD/SQL-Server-First-Responder-Kit#669]
I'm running @VersionDate = '20161210' and get "63 plans are present for a single query in the plan cache - meaning we probably have parameterization issues." as a result.  

The linked page (https://www.brentozar.com/blitzcache/multiple-plans/) says to "Run sp_BlitzCache @ExpertMode = 1 and look at the Query Hash column for the query with multiple plans".

When I run that, I get back 10 rows, but the Query Hash column is NULL for each row. Several have "parameter sniffing" in the Warnings column. How do I find which query is the one with 63 plans? 

If I run the query from the link page with the "AND qs.query_hash =" line commented out, I get back 1189 rows, none of which have 63 in the PlanCount column. The first 188 rows, all with a PlanCount of either 114 or 74, are for sp_blitz.  :-)

**Comment by BlitzErik** [comment]
sp_BlitzCache only gives you the top 10 by total cpu by default (use @GetHelp = 1 for more helpful help). I'm not sure if you supplied any other parameters.

One thing to try might be sp_BlitzCache @SortOrder = 'executions' or sp_BlitzCache @SortOrder = 'compiles'

If you'd like to open separate tickets for queries in sp_Blitz that aren't marked with OPTION(RECOMPILE), feel free to do so.

Thanks!
