### ISSUE TITLE
sp_Blitz -- Should recompile at proc level, and hints need to go in dynamic sql

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#670]
**Do you want to request a *feature* or report a *bug*?**
Change. BlitzIndex and BlitzCache both recompile at the proc level and in dynamic sql. Blitz should too. Now I'm thinking about BlitzFirst and I'm worried.

**What is the current behavior?**
We don't recompile stuff. We shouldn't be adding to the plan cache etc.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com

**What is the expected behavior?**
RECOMPILE GOD AREN'T YOU LISTENING?

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All

**Comment by BrentOzar** [comment]
I coded this to get it out of the way before today's sp_Blitz tour blog post goes live. It touches a ton of lines of code, and didn't want merges to be a problem later.

Tested by clearing the plan cache, running sp_Blitz with all kinds of options turned on, and then running sp_BlitzCache afterwards. The stuff in the cache was all sp_MSforeachdb, hahaha.
