### ISSUE TITLE
sp_Blitz - I've broken check 185

### ISSUE THREAD

**Issue by DaveRogersEsq** [BrentOzarULTD/SQL-Server-First-Responder-Kit#675]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behaviour?**
sp_Blitz hits an arithmetic overflow error:
Msg 8115, Level 16, State 2, Procedure sp_Blitz, Line 495
Arithmetic overflow error converting expression to data type int.

**Suggested fix:**
A dateadd function is used to build a value for insertion into the #BlitzResults table. The number argument cannot exceed the range of int. I suggest changing the dateadd function from
DATEADD(ms, (-1 * @MsSinceWaitsCleared), GETDATE())
to
DATEADD(s, (@MsSinceWaitsCleared / -1000.0), GETDATE())

**Comment by BlitzErik** [comment]
This was closed in #526 

Please update to a newer version of sp_Blitz, and search for bugs before reporting.

Thanks!
