### ISSUE TITLE
sp_BlitzWho - error in SQL Server 2008

### ISSUE THREAD

**Issue by CarlosBenito** [BrentOzarULTD/SQL-Server-First-Responder-Kit#685]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Msg 207, Level 16, State 1, Line 9
Invalid column name 'database_id'.
The 'database_id' is not a column on sys.dm_exec_sessions on SQL Server 2008. I have changed to use the 'database_id' from sys.dm_exec_requests and tested with 2008, 2012 and 2016.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com
Run on a SQL Server 2008. 

**What is the expected behavior?**
Not to error out.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2008. Yes.

**Comment by BlitzErik** [comment]
Hi there!

We have a [closed issue](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/648) for this, and a fix in the dev branch.

I appreciate the time you took to file the issue, but please search first before opening.

Thanks!
