### ISSUE TITLE
Document the First Responder Kit release process

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#690]
Document the release process so I can hand it off to Erik.

Will put it in a Markdown file in the Documentation folder. Brainstorming off the top of my head:

* Create a Milestone in YYYY-MM format
* As you put pull requests into the dev branch, tag them with the milestone
* When enough PRs are in dev, do a round of testing in 2008-2016 in the cloud lab
* If it passes, bump all the version numbers, and do a pull from dev to master
* Draft a new release (write the readme for it, including the issue #'s of the changes)
* Do the PR from dev to master
* Copy the FRK scripts into BrentOzar.com's First Responder Kit zip file, create a new version, upload it to S3
* Copy the release text into a WordPress blog post, linking to the download page
* Create a Mailchimp announcement to people who subscribed to the FRK releases, linking directly to the zip file

**Comment by BlitzErik** [comment]
Adding to this: on the desktop of each cloud instance, I have a folder called procs. That's where I'll copy all scripts to, along with a file called TestBed.sql (stays on server) with common execution parameters for each stored proc and references to databases specific to each server. They all have StackOverflow, and then some secondary junk database (for the most part)
