### ISSUE TITLE
sp_BlitzCache - Make All and All Avg sort orders compatible with Export To Excel

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#700]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Right now when we sort by all or all avg, we just select all the columns from the temp table. Bit of a naive implementation. Should branch if ExportToExcel = 1 to not select the QP column.

**What is the expected behavior?**
Work with other features, dummy.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All

**Comment by BlitzErik** [comment]
This will require a lot of work. The results of Export To Excel effectively uses the column set from Expert Mode 1. Blah.

**Comment by BrentOzar** [comment]
Or we could do it the really crappy way, like this:

`IF @ExportToExcel = 1 SET @AllSortSql += N'  UPDATE #bou_allsort SET QueryPlan = NULL OPTION (RECOMPILE);'`

Which, uh, works. Not proud of it, but it works. How to test:

/* With plans: */
sp_BlitzCache;
sp_BlitzCache @ExpertMode = 1;
sp_BlitzCache @SortOrder = 'all';
sp_BlitzCache @SortOrder = 'all', @ExpertMode = 1;
sp_BlitzCache @SortOrder = 'avg reads';

/* Sans plans: */
sp_BlitzCache @ExportToExcel = 1;
sp_BlitzCache @ExpertMode = 1, @ExportToExcel = 1;
sp_BlitzCache @SortOrder = 'all', @ExportToExcel = 1;
sp_BlitzCache @SortOrder = 'all', @ExpertMode = 1, @ExportToExcel = 1;
sp_BlitzCache @SortOrder = 'avg reads', @ExportToExcel = 1;
