### ISSUE TITLE
Table Variables: False Positive on Tables starting with '@'

### ISSUE THREAD

**Issue by elvishfiend** [BrentOzarULTD/SQL-Server-First-Responder-Kit#701]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
sp_BlitzCache throws a warning about Table Variables for all queries where the table starts with '@'
We have User Tables in our Vendor Software that start with '@', and so this represents a false positive.
Example Schema: http://sqlfiddle.com/#!6/2b7b5

**What is the expected behavior?**
sp_BlitzCache should not show a warning about Table Variables for User Tables that start with '@', but should check whether it is an existing table or not.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
We're running SQL 2012 on Windows Server 2012, but I don't see why it wouldn't also affect other versions.

**Comment by BlitzErik** [comment]
This is something that was discussed during development of the feature here: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/422

Unfortunately, you're just going to have to ignore it in your case, because your vendor made a ridiculous naming choice.

Thanks!

**Comment by elvishfiend** [comment]
Ha, no worries, I expected this would be the case.
There's a number of poor choices that the vendor has made, this is a relatively minor one as far as things go.

**Comment by BlitzErik** [comment]
Yeah, I wish there was a better to make the call. 

If you open a Connect Item, let me know and I'll blog about it in the next FRK release in February.
