### ISSUE TITLE
sp_BlitzIndex - [Create TSQL] column should also consider ignore_dup_key setting on Index

### ISSUE THREAD

**Issue by chintakchhapia** [BrentOzarULTD/SQL-Server-First-Responder-Kit#702]
Enhancement can be made to sp_BlitzIndex to add "ignore_dup_key" setting information in [Create TSQL] output column, if "ignore_dup_key" was specified for an index. This way it would become easy to copy index from production to dev/qa environments.

**Comment by chintakchhapia** [comment]
@BrentOzar 

Thanks for the follow up.
Also please bare with me as some of the below text/example is redundant but added it just to reduce further to and fro.

On database that I am currently working has some  indexes where "ignore_dup_key" option is set and when I run "sp_BlitzIndex" against those tables, [Create TSQL] does not script this option.

So now If I try to use create statement returned by procedure ([Create TSQL] field) on some other environments (where index does not exists), it can create an issue (unique key violations) in applications on those environments.

Way I have updated the procedure is by only adding this option to  [Create TSQL],  if the option is set to on for that index. So, it will not create any impact on indexes which do not have this option set. 

I may be wrong but i think not getting this option scripted might create problem if this option is set for an index, so not sure why people would not want this to be added to create script if "ignore_dup_key" option is set for an index.  

For example, if I have this table
```
drop table if exists dbo.t1; 

create table dbo.t1
(
	c1 int
	, c2 int
);

create unique clustered index ix_c_u_t1 on dbo.t1(c1,c2) with (ignore_dup_key = on);

```
now when I execute procedure for table
```
exec sp_BlitzIndex @SchemaName = 'dbo',@TableName ='t1'
```
I am getting this statement in [Create TSQL] column of first resultset
```
CREATE UNIQUE CLUSTERED INDEX [ix_c_u_t1] ON [dbo].[t1] ( [c1], [c2] ) WITH (FILLFACTOR=100, ONLINE=?, SORT_IN_TEMPDB=?);
```
where I think, procedure should return below create statement as ignore_dup_key was set to on

```
CREATE UNIQUE CLUSTERED INDEX [ix_c_u_t1] ON [dbo].[t1] ( [c1], [c2] ) WITH (FILLFACTOR=100, ONLINE=?, SORT_IN_TEMPDB=?,IGNORE_DUP_KEY = ON);
```

**Comment by BrentOzar** [comment]
Ah, okay, now I understand. (I misunderstood your initial note.) Sure, that sounds good. You can go ahead and work on it and make a pull request. Thanks!

**Comment by chintakchhapia** [comment]
@BrentOzar 

I created my local branch and committed changes to it but when I try to publish the branch using this command 
```
git push -u origin issue_702/chintak
```
I am getting this error 
"remote: Permission to BrentOzarULTD/SQL-Server-First-Responder-Kit. git denied to chintakchhapia.fatal: unable to access 'https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit.git/': The requested URL returned error: 403"

Also getting similar error from GitHub windows client. 

Can you please guide me how can I handle this error?
Thanks.

**Comment by BrentOzar** [comment]
No, you don't have the ability to push - just create a pull request:
https://www.brentozar.com/archive/2016/07/contribute-code-sql-server-first-responder-kit-github/

**Comment by chintakchhapia** [comment]
Tried to create pull request and it also failing with the permission error.

Yes, I followed the steps mentioned in 
https://www.brentozar.com/archive/2016/07/contribute-code-sql-server-first-responder-kit-github/

As per last instruction in step #6 of above post

> Then click Commit, and **click Publish** at the top right to sync your changes with the rest of the world. This doesn’t merge your code with the toxic sewer that is the dev branch just yet – you’re still on an island by yourself, but at least other people can get to your code.

Not sure I am doing something wrong here, anyways I will create new gist for procedure code and add a link below.

**Comment by chintakchhapia** [comment]
Gist link
https://gist.github.com/chintakchhapia/ae54aad3d7115b8197112b31fb46e1dd

**Comment by BlitzErik** [comment]
I looked over the code, and it's perfectly fine. I'm closing this without adding it though, because I don't want to run into a weird case where someone either turned this on by accident, or just has it on temporarily. You understand the use case, but not everyone does, and I'd hate to see it cause a problem. 

What I'd suggest is (if you're feeling ambitious) adding a bit flag to the stored proc called something like @ExpandIndexOptions, and include other index options, so if you want to detect and include or alter other index options, you can, but it won't be visible to everyone by default.
