### ISSUE TITLE
sp_blitzfirst assumes sp_blitzwho is in master DB, may not always be the case.

### ISSUE THREAD

**Issue by thornersetrans** [BrentOzarULTD/SQL-Server-First-Responder-Kit#703]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
sp_blitzfirst assumes sp_blitzwho is in master DB.  This may not always be the case.  I would reverse change that added this to "if" statement.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com
I place sp_blitz routines in a database called maintdb to keep them with other maintenance SP's like the routines from Ola to do backups, etc.

**What is the expected behavior?**
Run sp_blitzwho successfully using current database context.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
I am using SQL 2014 in this testing.

**Comment by BrentOzar** [comment]
Hi, and thanks for the issue. When you file issues, though, search to make sure they haven't already been filed:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/668

**Comment by thornersetrans** [comment]
I use GitHub very rarely, so will check in future.  Sorry.

Thomas Horner
SQL Server DBA
(O) 404-209-3012

**Comment by thornersetrans** [comment]
In retrospect, you may have misunderstood my issue, since you refer to #668.  The “bug” I am reporting is that sp_blitzfirst does look in master for sp_blitzwho (it assumes that it is there), which is not the case for me (and maybe others I presume).  In other words, the fix to 668 actually breaks sp_blitzfirst for me, since sp_blitzwho is NOT in the master DB the way I install these SP’s.

Please correct me if I misread this.  I may not be looking in the right place.

Thomas Horner
SQL Server DBA
(O) 404-209-3012

From: Tom Horner
Sent: Wednesday, February 08, 2017 11:35 AM
To: 'BrentOzarULTD/SQL-Server-First-Responder-Kit' <reply@reply.github.com>
Subject: RE: [BrentOzarULTD/SQL-Server-First-Responder-Kit] sp_blitzfirst assumes sp_blitzwho is in master DB, may not always be the case. (#703)

I use GitHub very rarely, so will check in future.  Sorry.

Thomas Horner
SQL Server DBA
(O) 404-209-3012

**Comment by BlitzErik** [comment]
Yeah, there's not a lot of middle ground on this one. 

For the majority of users, it will be in master. If they ran it from StackOverflow or another database, it would not run properly and sp_BlitzWho wouldn't fire. 

You're free to change it on your end to whatever works for you.

**Comment by ghauan** [comment]
Hi
If this is the case and it will not be fixed. Then maybe sp_BlitzWho should start with a "USE master"-statement, like you do in sp_foreachdb? Or else it is easy to miss this during an upgrade to the latest version and forget that you need to put sp_BlitzWho in master.

Just a thought.

**Comment by BrentOzar** [comment]
Nah, we don't want to force people to use a particular database if they don't want to.

**Comment by BlitzErik** [comment]
This issue will be addressed via this, well, this issue #719

**Comment by ghauan** [comment]
Aah, thanks. I guess that will do the trick.
Thanks again for your excellent work!
