### ISSUE TITLE
Create a new stored procedure to examine Hekaton/IMOLTP/whatever you wanna call it

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#708]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
We don't acknowledge the existence of Hekaton tables and indexes 

**What is the expected behavior?**
I don't know enough about Hekaton to tell you if there are problems with the indexes or anything, but we should at least get basic information about them. 

If anyone wants to chime in with conditions to look for, feel free.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Even though Hekaton went live in 2014, I think support will only be for 2016+ in BlitzIndex since we've had literally 0 requests for it. I sort of don't feel like dealing with multiple blocks of dynamic SQL for this to account for any dmv changes/differences.

**Comment by BlitzErik** [comment]
There's good information about stuff to warn about rounded up at the following links (which I really just want to close)

https://msdn.microsoft.com/en-us/library/dn133166.aspx?f=255&MSPPError=-2147217396

https://msdn.microsoft.com/en-us/library/mt670614.aspx?f=255&MSPPError=-2147217396

https://msdn.microsoft.com/en-us/library/mt706517.aspx?f=255&MSPPError=-2147217396

https://technet.microsoft.com/en-us/library/dn494956%28v=sql.120%29.aspx?f=255&MSPPError=-2147217396

https://github.com/Microsoft/tigertoolbox/blob/master/Index-Information/view_IndexInformation.sql

https://github.com/Microsoft/tigertoolbox/blob/master/BPCheck/Check_BP_Servers.sql

**Comment by BlitzErik** [comment]
I think that, like the columnstore proc that Joe is working on in #1254, we should put this outside of sp_BlitzIndex.

In-memory is more than just indexes, and requires more than just index analysis.

**Comment by BrentOzar** [comment]
Yeah, agreed. Should we close this for now? We never see people using the feature.

**Comment by ktaranov** [comment]
Hi, @BrentOzarm @BlitzErik .

We start to improve awesome In-Memory OLTP diagnostic script by Ned Otter and want to transform it in stored procedure. It it possible after some iteration to integrate it in your best of the best SQL Server repo like `sp_BlitzInMemory`.
Our roadmap here: https://github.com/ktaranov/sqlserver-kit/issues/103

**Comment by BrentOzar** [comment]
OK, cool, we'll close this then. Unfortunately, we can't include that script in our library due to its non-commercial license - if you can work with Ned to relicense it under the MIT license, we might be interested though. Thanks!
