### ISSUE TITLE
sp_BlitzCache -- Add support for Query Store analysis

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#709]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
We don't look at Query Store data at all

**What is the expected behavior?**
We should give people the ability to do this per database with a start and end time.

Basic feature outline:
- User specifies database name to analyze
- BlitzCache makes sure you're on a version that supports Query Store and that it's enabled for the database specified
- Grab top N plans sorted by whatever metric (this can likely be expanded given the amount of things Query Store tracks, but probably not handling this in v1) between an optional start and end date.
- Use same XML shredding queries to detect additional issues in query plans

Challenges:

- Query Store tracks a lot more stuff, so the choice becomes 
    1. add a crapload more columns to our current global temp table 
    2. Use a different table for QS entirely

- QS tracks some stuff that BlitzCache digs to find, like DOP, parameterization type (just at a glance, might be more), so we should perhaps skip some of the XML-invasive checks in favor of already logged data.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
2016 and up!

**Comment by BlitzErik** [comment]
Additional stuff:
Sorting can use the same basic outline as regular BlitzCache, but needs to have the columns changed to use Query Store friendly names instead. Some of the calculations may change as well because of this.

**Comment by BlitzErik** [comment]
We can no longer use `sys.dm_exec_plan_attributes` reliably to get plan attributes. For Query Store plans, we use `sys.query_context_settings`, but thankfully the query doesn't change much:

```
SELECT *,           SUBSTRING(
					CASE WHEN (CAST(qcs.set_options AS INT) & 1 = 1) THEN ', ANSI_PADDING' ELSE '' END +
                    CASE WHEN (CAST(qcs.set_options AS INT) & 8 = 8) THEN ', CONCAT_NULL_YIELDS_NULL' ELSE '' END +
                    CASE WHEN (CAST(qcs.set_options AS INT) & 16 = 16) THEN ', ANSI_WARNINGS' ELSE '' END +
                    CASE WHEN (CAST(qcs.set_options AS INT) & 32 = 32) THEN ', ANSI_NULLS' ELSE '' END +
                    CASE WHEN (CAST(qcs.set_options AS INT) & 64 = 64) THEN ', QUOTED_IDENTIFIER' ELSE '' END +
                    CASE WHEN (CAST(qcs.set_options AS INT) & 4096 = 4096) THEN ', ARITH_ABORT' ELSE '' END +
                    CASE WHEN (CAST(qcs.set_options AS INT) & 8192 = 8191) THEN ', NUMERIC_ROUNDABORT' ELSE '' END 
					, 2, 200000)
FROM StackOverflow.sys.query_context_settings qcs
```

**Comment by BlitzErik** [comment]
Fun:

Query Store DMVs don't track total time. They track min, max, avg, and std dev for certain metrics. I could attempt to go back to places we already get info from, but it may not persist there as long as QS keeps stuff.

**Comment by peschkaj** [comment]
If QueryStore tracks execution counts, you can multiple executions by average to get an approximate total time since an average is just `sum / count`. 😺

**Comment by BlitzErik** [comment]
I could also just force the sorting to averages and not document it. 

For fun :dagger: :dagger: :dagger:

**Comment by BlitzErik** [comment]
This'll get done in a new stored proc
