### ISSUE TITLE
sp_BlitzFirst: display sleeping SPID if it is a blocking SPID

### ISSUE THREAD

**Issue by pnwguy** [BrentOzarULTD/SQL-Server-First-Responder-Kit#714]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Output of sp_BlitzFirst does not display sleeping SPIDs.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com

**What is the expected behavior?**
Have option to display sleeping SPIDs, especially if it is the top most blocker.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Not sure

Please see Stack Exchange article with more detail: http://dba.stackexchange.com/questions/163782/sp-blitzfirst-blocking-session-id-not-displayed-in-list-of-session-ids/163835?noredirect=1#comment315893_163835.

**Comment by BlitzErik** [comment]
It looks like this got addressed!
