### ISSUE TITLE
Add @VersionDate to 3 sp_Blitzers

### ISSUE THREAD

**Issue by sm8680** [BrentOzarULTD/SQL-Server-First-Responder-Kit#717]
This is a request

When time permits 
Can you super geniuses add in the future a VersionDate to sp_BlitzWho, sp_BlitzRS and sp_BlitzTrace?  To match the other sp_Blitzers

For extra credit you could also add @Version to the sprocs that don't have it.

Thanks
Steven

**Comment by BlitzErik** [comment]
BlitzRS isn't going to be getting any more development work. Whichever version you have is likely the latest. I'll have version dates and numbers in the rest for the next release.
