### ISSUE TITLE
sp_BlitzCache - add warning for spatial index in query plan

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#727]
Not that there's anything wrong with that.

Just want to see at a glance that there's something that might surprise you. Here's the operator I saw:

`<Object Database="[DB_REDACTED]" Schema="[sys]" Table="[extended_index_45243216_384000]" Index="[IX_REDACTED]" TableReferenceId="-1" IndexKind="Spatial" />`

Also saw this warning in the plan:

`<GuessedSelectivity>
                    <Spatial />
                  </GuessedSelectivity>
                  <Warnings SpatialGuess="1" />`

**Comment by BlitzErik** [comment]
Well, we can certainly flag Spatial index accesses, but the warning seems to be a bug that happens on every spatial query: https://connect.microsoft.com/SQLServer/feedback/details/708622/gratuitous-incorrect-spatialguess-warning

Is the Spatial index flag useful without the warning being actionable? Up to you on this on, @BrentOzar

**Comment by BlitzErik** [comment]
Code to flag:

```
WITH XMLNAMESPACES('http://schemas.microsoft.com/sqlserver/2004/07/showplan' AS p)
SELECT qs.SqlHandle,
	   n.fn.exist('(@IndexKind[.="Spatial"])'),
	   n.fn.value('@IndexKind', 'VARCHAR(100)')
FROM   #relop qs
CROSS APPLY relop.nodes('/p:RelOp//p:Object') n(fn)
WHERE n.fn.exist('(@IndexKind[.="Spatial"])') = 1
```

![image](https://cloud.githubusercontent.com/assets/11590415/23768832/4aea21b8-04db-11e7-8f2c-c46644a30def.png)
