### ISSUE TITLE
sp_BlitzIndex -- Index Hoarder: Unused NC index priority

### ISSUE THREAD

**Issue by amtwo** [BrentOzarULTD/SQL-Server-First-Responder-Kit#728]
**Do you want to request a *feature* or report a *bug*?**
Feature Request

**What is the current behavior?**
Currently, "Index Hoarder: Unused NC index" shows as a priority 150, which sorts it down with the "not necessarily wrong, but interesting" things. 

**What is the expected behavior?**
Seems like duplicate indexes should probably be slightly higher. 

I'm not sure what the right priority is, but I think it should be a lower number so that it bubbles up higher on the list.

Per Brent (in Slack) "I’m surprised the unused is 150, come to think of it."

**Comment by BlitzErik** [comment]
Let's make a deal. We'll put unused indexes with high writes (say 10,000) in a higher priority, and unused indexes with few writes in a lower priority. How's that sound?

**Comment by amtwo** [comment]
That sounds pretty good. Ok, I'll trade in Door Number 2 for that fix!
(I hope Door Number 2 didn't have a car behind it)
