### ISSUE TITLE
sp_foreachdb, sp_BlitzTrace - drop + create procedure instead of create if not exists + alter procedure

### ISSUE THREAD

**Issue by dnc-msimons** [BrentOzarULTD/SQL-Server-First-Responder-Kit#743]
**Do you want to request a *feature* or report a *bug*?**
Bug? More inconsistent behavior with the potential for errors in the right conditions. (See http://www.codeofhonor.com/blog/a-better-way-to-update-sql-stored-procedures)

**What is the current behavior?**
sp_foreachdb & sp_blitztrace both follow the "drop procedure then create procedure" pattern for deployment of updated versions of sp. 

**What is the expected behavior?**
sp_blitz, et. al. employ a "create if not exists and then alter procedure" pattern.  

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

**Comment by BrentOzar** [comment]
Sure, agreed, would be a good tweak. Thumbs up - you're good to go ahead and make those changes.

**Comment by BrentOzar** [comment]
Here's our guide to contributing:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md

And here's how to do a pull request:
https://www.brentozar.com/archive/2015/07/pull-request-101-for-dbas-using-github/
