### ISSUE TITLE
sp_Blitz Some checks are not useful on Express Edition, for example Check 96 "SQL Server Agent alerts do not exist for errors 823, 824, and 825" because there is no SQL Server Agent in the Express Editions

### ISSUE THREAD

**Issue by Totty1973** [BrentOzarULTD/SQL-Server-First-Responder-Kit#756]
sp_Blitz Some checks are not useful on Express Edition, for example Check 96 "SQL Server Agent alerts do not exist for errors 823, 824, and 825" or Check 61 "SQL Server Agent alerts do not exist for severity levels 19 through 25." or Checks 30, 31
because there is no SQL Server Agent in the Express Editions, so why bother checking for something that cannot be fixed using the existing software?

**Comment by BrentOzar** [comment]
Neat idea! Go through the list of checks in the documentation folder and make a list of ones that shouldn't be thrown. If you can make a comma delimited list of the check IDs, I'll write the code. (I don't use Express so I have no idea what's not relevant.)

**Comment by Totty1973** [comment]
30,31,61,73,96

This is from "sp_Blitz Nov 15 2016 12:00AM", so heres full output in case you rearranged the checks
30: Not all SQL Server Agent alerts have been configured.  This is a free, easy way to get notified of corruption, job failures, or major outages even before monitoring systems pick it up.
31: No SQL Server Agent operators (emails) have been configured.  This is a free, easy way to get notified of corruption, job failures, or major outages even before monitoring systems pick it up.
61: SQL Server Agent alerts do not exist for severity levels 19 through 25.  These are some very severe SQL Server errors. Knowing that these are happening may let you recover from errors faster.
73: No failsafe operator is configured on this server.  This is a good idea just in-case there are issues with the [msdb] database that prevents alerting.
96: SQL Server Agent alerts do not exist for errors 823, 824, and 825.  These three errors can give you notification about early hardware failure. Enabling them can prevent you a lot of heartbreak.

**Comment by BrentOzar** [comment]
OK, coded. Please test it here and let me know if that works - I don't have an Express Edition handy.

https://raw.githubusercontent.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/36bcce03498a99fa95c95c7ec1af69f01542c283/sp_Blitz.sql

**Comment by Totty1973** [comment]
Tested on SQL Express 2012 sp3, looks very good.

**Comment by BrentOzar** [comment]
@Totty1973 you don't have to close this - it'll be closed when @BlitzErik merges the change into the main branch and releases it. Thanks though!
