### ISSUE TITLE
sp_blitz reports "Trace flag 8017 is enabled globally." which seems to be the default for SQL Express Editions

### ISSUE THREAD

**Issue by Totty1973** [BrentOzarULTD/SQL-Server-First-Responder-Kit#758]
sp_blitz reports "Trace flag 8017 is enabled globally." which seems to be the default for SQL Express Editions, maybe since Version 2005 https://learningintheopen.org/tag/trace-flag-8017/
Check ID 74
tested on SQL Express 2012sp3

**Comment by BrentOzar** [comment]
OK, for that one, I'll let you write the code on it. (I don't want to keep writing code if you've got an Express Edition handy.) Go ahead and read contributing.md. Thanks!

**Comment by BrentOzar** [comment]
Hmm, I'm looking in the sp_Blitz code and there's nothing in there now about 8017. Were you using an old version of sp_Blitz, maybe?

**Comment by Totty1973** [comment]
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/759

**Comment by Totty1973** [comment]
why is this still open?

**Comment by BlitzErik** [comment]
Not sure, looks like Git didn't close it automatically for some reason.
