### ISSUE TITLE
DatabaseRestore - Restores fail when using @MoveFiles=1 with long paths / multiple files

### ISSUE THREAD

**Issue by jeffrosenberg** [BrentOzarULTD/SQL-Server-First-Responder-Kit#766]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

When restoring a database that is backed up to multiple files, the restore fails if you use @MoveFiles=1 and the combined length of the new paths is over 1,000 characters. The error message will look something like this, although it will vary depending on the exact file names you use:

> Msg 105, Level 15, State 1, Line 1
> Unclosed quotation mark after the character string 'C:\Pr

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com

Backup up a database to multiple files (i.e. 8) to a directory with a relatively long path (i.e. C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\Backup). Then attempt to restore using @MoveFiles=1.

**What is the expected behavior?**

The @MoveFiles=1 option should be able to accommodate long paths and multiple files.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

All supported versions, which at present is just SQL Server 2016.

**Comment by GregWhiteDBA** [comment]
changed to DECLARE @MoveOption AS NVARCHAR(max)= '';

**Comment by jeffrosenberg** [comment]
@GregWhiteDBA I submitted a pull request for this, #767. Want to take a look?
