### ISSUE TITLE
Check 193 possible BUG: SP_BLITZ does not report IFI as enabled on 2014sp2.

### ISSUE THREAD

**Issue by Totty1973** [BrentOzarULTD/SQL-Server-First-Responder-Kit#771]
**Do you want to request a *feature* or report a *bug*?**
possible Bug / maybe feature request

**What is the current behavior?**
SP_BLITZ does not report IFI as enabled, but I think I followed the required steps. The script at https://www.johnsansom.com/sqlserver-instant-file-initialization/ does provide the right output, meaning "there is no reference to the database data file." only to the LDF. This is on my delevopment box "Microsoft SQL Server 2014 (SP2-CU4) (KB4010394) - 12.0.5540.0 (X64) ,	Jan 27 2017 03:40:25,	Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 14393: )" on Windows 10 Enterprise.

**What is the expected behavior?**
Judging by the script, on SQL2014 SP_BLITZ would report an enabled IFI, and on SQL2016 it would report a disabled IFI.

I think IFI should be enabled on nearly all servers, so SP_BLITZ should only report if IFI is disabled. I don't want to start a war.
My employer still runs many many SQL2008R2 servers, only the new ones are 2012. So, a check would be helpful

**Comment by BrentOzar** [comment]
John Sansom's script works by creating and dropping a database. Unfortunately, we can't do that - that's a bad idea to just randomly create & drop databases when people aren't expecting it. Thanks though.

sp_Blitz does indeed check for IFI - do a search in the code and you can see more details, plus learn why it can't always detect it.

Thanks though!
