### ISSUE TITLE
sp_Blitz Feature: Higher priority number for jobs with issues but that have otherwise been disabled

### ISSUE THREAD

**Issue by JohnKNess** [BrentOzarULTD/SQL-Server-First-Responder-Kit#776]
**Do you want to request a *feature* or report a *bug*?**

Feature for sp_Blitz

**What is the current behavior?**

Jobs currently detected as having big No/Nos in the job steps (e.g. "SHRINKDATABASE, SHRINKFILE, ...) are marked with priority 100.

**What is the expected behaviour / What is the requested feature?**

Disabled jobs or jobs without enabled schedules should have a higher priority number so that they don't display in the viewable portion of the result set. Why? They have already been attended to (deactivated) and should no longer be displayed as high priority (currently 100) issues. This corresponds with the guidelines:

- Actionable warnings - SQL Server folks are **usually overwhelmed** with data, and we **only want to report on things they can actually do something about**

- Things that end users **or managers will notice** - if we're going to have someone change a setting on their system, **we want it to be worth their time**

**Comment by BrentOzar** [comment]
John - the challenge I've run into personally is that I've seen folks leave the job in place, and then run it manually. If you do want to code it, we'd take the contribution, but make sure to also check job history to make sure the job hasn't run in the last, say, 30 days.

(If you don't contribute the code in a month or two, we'll close the issue for you, no worries either way.)

**Comment by JohnKNess** [comment]
@BrentOzar I think we can mutually agree on that. So to sum it up, the contributor would have to check for disabled jobs and/or job-schedules and verify that they haven't run in the past 30 days to give them an end priority of ....  

1. 150
2. 200
3. 250
4. higher (please specify)

**Comment by BrentOzar** [comment]
Yep, we just go for tinyint, so:

100 - enabled/scheduled jobs, or jobs that have run in the last 30 days
200 - disabled, unscheduled jobs that have not run in the last 30 days

**Comment by JohnKNess** [comment]
This is going to be an interesting task. :-)

**Comment by JohnKNess** [comment]
I am working on it and keeping in-sync with the upstream at https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit.git. Check ID 79 seems to be the easier of the two (180 being the other in SSIS XML)

**Comment by JohnKNess** [comment]
I have finalized the code in my fork and will be testing against various versions of SQL Server before I open a pull request.

**Comment by BlitzErik** [comment]
Closed #878
