### ISSUE TITLE
Mode=2 show heap count as 3, mode = 4 only show 2 heaps sp_BlitzIndex(TM) v5.0 - March 07, 2017 

### ISSUE THREAD

**Issue by Wcikanek** [BrentOzarULTD/SQL-Server-First-Responder-Kit#783]
report a *bug*

**What is the current behavior?**
Mode =2 shows Heap count as one more than the detail Heap rows when mode = 4

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com
Run on DB that has at least one heap.

**What is the expected behavior?** Counts should match

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?** 

Microsoft SQL Server 2014 (SP2-CU3) (KB3204388) - 12.0.5538.0 (X64) 
	Dec 15 2016 17:52:48 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)
Never used this detail before.

**Comment by BlitzErik** [comment]
Thanks! Are you planning on submitting code for this?

**Comment by Wcikanek** [comment]
Actually only a minor annoyance, so not currently worth my time.  Just wanted you to be aware of issue.

**Comment by BlitzErik** [comment]
Okay, if you decide you want to submit code, go ahead and reopen the issue.

Thanks!
