### ISSUE TITLE
Consider using lower case for data type names

### ISSUE THREAD

**Issue by sm8680** [BrentOzarULTD/SQL-Server-First-Responder-Kit#784]
Something to consider
[https://blogs.sentryone.com/aaronbertrand/backtobasics-lower-case-data-types/](url)

**Comment by BlitzErik** [comment]
If you're not planning on contributing code for this, I'm going to close it. 

That's an absurd amount of work for a nit picky coding style.

**Comment by sm8680** [comment]
That's why I stated it as something to consider.  If you want I could look to do a few of these over the weekend or you could simply state please close this and I will.  :)

**Comment by BlitzErik** [comment]
I'll close it. Thanks for the idea, though.
