### ISSUE TITLE
sp_Blitz - Update to check 75 for data warehouses and staging databases

### ISSUE THREAD

**Issue by tpetersmcit** [BrentOzarULTD/SQL-Server-First-Responder-Kit#785]
**Do you want to request a *feature* or report a *bug*?**
Feature for sp_Blitz
**What is the current behavior?**
sp_Blitz will alert on a large transaction log file even when the file is (nearly) empty.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com

**What is the expected behavior?**
In data warehouse or staging databases the transaction log file can be larger than the data file, but be empty most of the time. An large, but empty transaction log file doesn't indicate that transaction log backups are not being performed or not performed often enough. The code below populates #LogSpace from dbcc sqlperf(logspace) and then check 75 will ignore large transaction files that are 10% or less full.

CREATE TABLE #LogSpace 
  (DatabaseName NVARCHAR(128) , 
  LogSize BIGINT , 
  LogSpacePercentFull TINYINT , 
  DBStatus BIT);

INSERT INTO #logspace exec('dbcc sqlperf(logspace)');

SELECT  75 AS CheckID ,
  DB_NAME(a.database_id) ,
  50 AS Priority ,
  'Reliability' AS FindingsGroup ,
  'Transaction Log Larger than Data File' AS Finding ,
  'http://BrentOzar.com/go/biglog' AS URL ,
  'The database [' + DB_NAME(a.database_id)
    + '] has a ' + CAST((CAST(a.size AS BIGINT) * 8 / 1000000) AS NVARCHAR(20)) + ' GB transaction log file, larger than the total data file sizes. This may indicate that transaction log backups are not being performed or not performed often enough.' AS Details
FROM    sys.master_files a
JOIN #logspace as ls on DB_NAME(a.database_id) = ls.DatabaseName
WHERE   a.type = 1
AND DB_NAME(a.database_id) NOT IN (
SELECT DISTINCT
  DatabaseName
FROM    #SkipChecks )
  AND a.size > 125000 /* Size is measured in pages here, so this gets us log files over 1GB. */
  AND ls.LogSpacePercentFull > 10 /*Ignore large transaction logs that are 10% or less full*/
  AND a.size > ( SELECT   SUM(CAST(b.size AS BIGINT))
  FROM     sys.master_files b
  WHERE    a.database_id = b.database_id
AND b.type = 0
)
AND a.database_id IN (
  SELECT  database_id
  FROM    sys.databases
  WHERE   source_database_id IS NULL )

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

**Comment by BrentOzar** [comment]
That's actually the problem we're trying to catch - overly bloated log files. I have a tough time imagining a legit scenario where the log file is actually *larger* than the database, even in data warehouse staging databases. I can't imagine folks successfully doing their entire load in a single transaction.

If you want to skip this check, you're best off using the SkipChecks feature. You can skip checks for a specific server, database, etc.

**Comment by tpetersmcit** [comment]
Thanks. I have two databases where this is occurring. Both are in Simple mode and have had their logs shrunk several times. They always grow back to being larger than the data files.  I can total imagine that these dbs are not legit and I plan on telling the devs so :)
