### ISSUE TITLE
DatabaseRestore -- Make script idempotent

### ISSUE THREAD

**Issue by mrthomsmith** [BrentOzarULTD/SQL-Server-First-Responder-Kit#786]
**Do you want to request a *feature* or report a *bug*?**
Feature/Bug
**What is the current behavior?**
Running `DatabaseRestore.sql` on a database where the procedure already exists causes an error.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
Create DatabaseRestore and then re-run the script.
**What is the expected behavior?**
Re-run the script without error and keep in line with the other stored procs.
**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All versions.

**Comment by BlitzErik** [comment]
This should been closed via #787
