### ISSUE TITLE
sp_Blitz -- Backup to Same Drives when using Network storage (UNC/SMB)

### ISSUE THREAD

**Issue by matthewtckr** [BrentOzarULTD/SQL-Server-First-Responder-Kit#791]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** spBlitz reports "Backing Up to Same Drive Where Databases Reside" when using SMB shares for both data directory of databases, and backup directory, even if IP addresses specified in UNC paths are different.  It appears to only look at first 3 characters of the path (e.g. `\\1` for `\\10.x.x.x` or `\\172.x.x.x`).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com

* Install a new SQL Server instance, configure database storage on a Windows Share path

**What is the expected behavior?**

spBlitz recognizes that the SMB shares are different and does not create an alert, even if they reside on the same host.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Only tested on SQL Server 2016 SP1

**Comment by BlitzErik** [comment]
We don't have anything that fancy set up on our end, so if you want to code this go right ahead. 

Just make sure to read the [contributing guidelines](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md).

**Comment by BlitzErik** [comment]
Haven't heard back from you about this, so going to close. If you decide you want to work on it, reopen the issue.

Thanks!

**Comment by matthewtckr** [comment]
Not sure I'm ready yet to invest time in setting up some VMs. 😢 

In case future-me wants to stop procrastinating, or someone else wants to be awesome and take it over the finish line with the testing, here's where I stopped:

```
SELECT 93 AS CheckID
	,1 AS Priority
	,'Backup' AS FindingsGroup
	,'Backing Up to Same Drive Where Databases Reside' AS Finding
	,'https://BrentOzar.com/go/backup' AS URL
	,CAST(COUNT(1) AS VARCHAR(50)) + ' backups done on drive ' + CASE 
		WHEN bmf.physical_device_name LIKE '\\%'
			THEN UPPER(LEFT(bmf.physical_device_name, CHARINDEX('\', bmf.physical_device_name, 3) - 1))
		ELSE UPPER(LEFT(bmf.physical_device_name, 3))
		END + ' in the last two weeks, where database files also live. This represents a serious risk if that array fails.' Details
FROM msdb.dbo.backupmediafamily AS bmf
INNER JOIN msdb.dbo.backupset AS bs ON bmf.media_set_id = bs.media_set_id
	AND bs.backup_start_date >= (DATEADD(dd, - 14, GETDATE()))
/* Filter out databases that were recently restored: */
LEFT OUTER JOIN msdb.dbo.restorehistory rh ON bs.database_name = rh.destination_database_name
	AND rh.restore_date > DATEADD(dd, - 14, GETDATE())
WHERE rh.destination_database_name IS NULL
	AND (
		UPPER(LEFT(bmf.physical_device_name COLLATE SQL_Latin1_General_CP1_CI_AS, 3)) IN (
			SELECT DISTINCT UPPER(LEFT(mf.physical_name COLLATE SQL_Latin1_General_CP1_CI_AS, 3))
			FROM sys.master_files AS mf
			WHERE mf.physical_name NOT LIKE '\\%'
			)
		OR (
			bmf.physical_device_name LIKE '\\%'
			AND UPPER(LEFT(bmf.physical_device_name, CHARINDEX('\', bmf.physical_device_name, 3) - 1)) IN (
				SELECT DISTINCT UPPER(LEFT(mf.physical_name, CHARINDEX('\', mf.physical_name, 3) - 1))
				FROM sys.master_files AS mf
				WHERE mf.physical_name LIKE '\\%'
				)
			)
		)
GROUP BY CASE 
		WHEN bmf.physical_device_name LIKE '\\%'
			THEN UPPER(LEFT(bmf.physical_device_name, CHARINDEX('\', bmf.physical_device_name, 3) - 1))
		ELSE UPPER(LEFT(bmf.physical_device_name, 3))
		END
```
