### ISSUE TITLE
sp_Blitz -- CheckID 100 not checking for all prerequisites when using Express Edition

### ISSUE THREAD

**Issue by Totty1973** [BrentOzarULTD/SQL-Server-First-Responder-Kit#792]
**Do you want to request a *feature* or report a *bug*?**
Small Bug / Feature Request

**What is the current behavior?**
CheckID only checks sys.configurations WHERE   name = 'remote admin connections' AND value_in_use = 0 
it says in the SQL server errorlog "Dedicated administrator connection support was not started because it is disabled on this edition of SQL Server. If you want to use a dedicated administrator connection, restart SQL Server using the trace flag 7806. This is an informational message only. No user action is required."

**What is the expected behavior?**
It could check for TF7806, because this is required when running Express Edition.
https://www.mssqltips.com/sqlservertip/2538/enabling-dedicated-administrator-connection-in-sql-server-2008-express-edition/
Maybe CheckID 74 should report a missing TF7806 when running express edition

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Tested only on 2012sp3express which seems affected.

**Comment by BlitzErik** [comment]
Howdy -- It's been a month, gonna close this down. If you want to pick it back up, please reopen it.
