### ISSUE TITLE
sp_Blitz -- WebEdition IMHO wrongly flagged as "capped at low amounts of CPU and memory."

### ISSUE THREAD

**Issue by Totty1973** [BrentOzarULTD/SQL-Server-First-Responder-Kit#797]
**Do you want to request a *feature* or report a *bug*?**
2 possible feature requests

**What is the current behavior?**
possible Feature Request #1: recognize Web Edition, which can do 4 procs or 16 core and 64 GB of ram, which i personally do not find "low amount". SELECT @@VERSION says "Microsoft SQL Server 2014 (SP2) (KB3171021) - 12.0.5000.0 (X64) 	Jun 17 2016 19:14:09 Copyright (c) Microsoft Corporation Web Edition (64-bit) on Windows NT 6.3 <X64> (Build 14393: )
"
possible Feature Request #2: rephrase "unusal Edition" for express edition. I'm giving the results of SP_BLITZ to my manager, I don't want any eyebrows raised or fingers pointed.

**What is the expected behavior?**
- Web Edition is recognized
- "unusal Edition" for express edition rephrase 

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
2014sp2 web edition is confirmed to be affected

**Comment by BrentOzar** [comment]
Go ahead and break this up into two issues. Don't use a single issue to track multiple things. Thanks!

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by Totty1973** [comment]
issue #799 created

**Comment by Totty1973** [comment]
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/798/commits/25e765585a046ad53526873437abf5efd8c55406 submitted

**Comment by BrentOzar** [comment]
I closed this pull request. I gotta be honest - my desktop has 64GB of memory. It's capped *lower* than Standard Edition, which isn't good. I understand that 64GB doesn't seem low to everybody, but when it's even lower than Standard, that's low, and worthy of a heads-up.

**Comment by Totty1973** [comment]
BlitzErik assigned me after clearly stating my intent and you single-handedly decline completed work? Your team needs to improve communication.

**Comment by BrentOzar** [comment]
Sorry, I was out the last few days. I apologize for that. I wanted you to split it up into separate issues so that we could talk about 'em individually. Check out contributing.md for more info on how to contribute to the project, and what to expect. Sorry about that!
