### ISSUE TITLE
sp_Blitz  --- possible Bug The URL given from Check 97 is not working ( https://BrentOzar.com/go/workgroup )

### ISSUE THREAD

**Issue by Totty1973** [BrentOzarULTD/SQL-Server-First-Responder-Kit#799]
**Do you want to request a *feature* or report a *bug*?**
possible Bug

**What is the current behavior?**
possible Bug The URL given from Check 97 is not working ( https://BrentOzar.com/go/workgroup )

**What is the expected behavior?**
 The URL given from Check 97 is working

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
version-independent

**Comment by Totty1973** [comment]
I do not currently have Edit permissions for brentozar.com. Do you plan something like a "content area contributed by a guest author" for the people running express editions, perhaps a single page listing all the restrictions?

**Comment by BrentOzar** [comment]
We don't have a plan for that now, no, but you're welcome to write a post on your own blog and include a link to it in the script.

**Comment by Totty1973** [comment]
Thanks, but I don't have enough content to offer, besides my "issues" with express edition.

**Comment by BrentOzar** [comment]
OK, added it to point to the current features/restrictions list at: https://docs.microsoft.com/en-us/sql/sql-server/editions-and-supported-features-for-sql-server-2016
