### ISSUE TITLE
sp_BlitzCache - reporting wrong number of missing indexes

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#808]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Using the same repro script as #807, run GetBadgesDetails. The stored proc reports 4 missing indexes, but there's only 1. (Guessing it's multiplying the number of statements.)

Plan: https://www.brentozar.com/pastetheplan/?id=B1BJsQg6x

**What is the expected behavior?**
I should have fond memories of dating Winona Ryder in high school (either hers or mine, I'm not picky) and it should only show 1 missing index at the stored proc level.
[Repro.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/891242/Repro.txt)

**Comment by BlitzErik** [comment]
I do not have this issue:

![image](https://cloud.githubusercontent.com/assets/11590415/24632063/c48200f4-1890-11e7-8392-83bcb35cb72b.png)

**Comment by BlitzErik** [comment]
I see why you were getting it though.
