### ISSUE TITLE
sp_BlitzCache - build test suite of scripts that produce each warning

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#809]
**Do you want to request a *feature* or report a *bug*?**
Feature (long term)

**What is the current behavior?**
When we release new versions, this script (sp_BlitzCache) is the trickiest to test. Need to have a set of scripts that:

* Free the plan cache
* Run a specific query
* Run sp_BlitzCache
* List how many rows are expected from the result set, and what warnings should be included

**Comment by BlitzErik** [comment]
It's important to test things two ways:

Once as a statement 
Once in a stored procedure 

There have been lots of times when a check in a statement passed but a check in a stored procedure didn't. Breaking the checks out into individual updates helped, but it's not foolproof.

**Comment by BlitzErik** [comment]
Thinking this through a little while looking at the list of issues here, the remote query ones might be tough to repro unless we pre-configure the lab (just thinking through having a known remote server name and known remote database etc.)

**Comment by BlitzErik** [comment]
I'm working on this a bit for demos in the pre-con material. I have a stored procedure that triggers a specific warning for a bunch of different warnings. The (problem? thing?) is that they may also trigger other warnings, and most all will trigger the "plan created last 4 hours" warning, because demos.

**Comment by BlitzErik** [comment]
We have most of this from the precon. If there's something you want me to do with them, let's discuss.
