### ISSUE TITLE
DatabaseRestore -- Add Differential Restores

### ISSUE THREAD

**Issue by TheUsernameSelectionSucks** [BrentOzarULTD/SQL-Server-First-Responder-Kit#814]
**Do you want to request a *feature* or report a *bug*?** Feature

**What is the current behavior?** Will restore Full backups, and Log backups, but not differential

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com

**What is the expected behavior?** After restoring full backups, restore the differential backups and then the log backups.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?** All

**Comment by BlitzErik** [comment]
Were you planning on submitting code for this?

**Comment by TheUsernameSelectionSucks** [comment]
I would like to. Still trying to figure out the whole GitHub thing.

**Comment by BlitzErik** [comment]
Okay, cool, make sure to read the [contributing guidelines](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md).

There are also some helpful posts on our site [here](https://www.brentozar.com/archive/2016/07/contribute-code-sql-server-first-responder-kit-github/) and [here](https://www.brentozar.com/archive/2015/07/pull-request-101-for-dbas-using-github/).

I'll go ahead and assign the issue to you for the time being, and if you decide you don't want to work on it, just let me know and I'll stick the help wanted tag on your issue.

Thanks!

**Comment by dbassassin** [comment]
Hey @BlitzErik I added some code that handles the differential part of this, and I've tested...at least once :D

Are there branch naming conventions before I create a pull request?

**Comment by BlitzErik** [comment]
I usually do the stored procedure name and the issue that it addresses.

Which versions and editions have you tested it on?

**Comment by dbassassin** [comment]
I've only tested against 

Microsoft SQL Server 2014 (SP2) (KB3171021) - 12.0.5000.0 (X64) 
	Jun 17 2016 19:14:09 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by dbassassin** [comment]
I created a branch sp_DatabaseRestore_814, also followed the steps at https://www.brentozar.com/archive/2015/07/pull-request-101-for-dbas-using-github/ 
but I ended up getting permission issues during the pull request part :(

**Comment by TheUsernameSelectionSucks** [comment]
So, is the issue closed, or can I still submit changes? How would I see if digialohm's changes are different than what I came up with? Why does this remind me of being in college programming classes again?

**Comment by BlitzErik** [comment]
Pay careful attention to all the big green icons that say "open" -- that should tell you the status of an issue ;)

**Comment by digitalohm** [comment]
@TheUsernameSelectionSucks, I think you can pull the branch I'm working on or at least see the changes from https://github.com/digitalohm/SQL-Server-First-Responder-Kit/tree/sp_DatabaseRestore_814

**Comment by TheUsernameSelectionSucks** [comment]
Ok. I like your changes better than my changes.
