### ISSUE TITLE
sp_Blitz -- Complains about not having compression enabled but the express edition product does not have that feature.

### ISSUE THREAD

**Issue by Totty1973** [BrentOzarULTD/SQL-Server-First-Responder-Kit#818]
**Do you want to request a *feature* or report a *bug*?**
Its a Bug, because the user is told he is missing a feature, which the product simply does not have.

**What is the current behavior?**
the user is told he is missing a feature, which the product simply does not have. https://msdn.microsoft.com/de-de/library/cc645993.aspx 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com

**What is the expected behavior?**
Script checks for express edition and does not request changes to be made which will not have an effect.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
all express editions

**Comment by BrentOzar** [comment]
Hmm, I'm not sure which check you're referring to. Can you take a screenshot including the CheckID column in the far right? Thanks!

**Comment by Totty1973** [comment]
Sorry, that was messed up, I need some better script placement and probably some holiday.
