### ISSUE TITLE
sp_BlitzIndex checks 30, 31, 32 don't work as expected with @GetAllDatabases = 1

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#825]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Run sp_BlitzIndex @GetAllDatabases = 1, and checks 30-32 aren't multi-database aware. Look in this section of the code:

--Feature-Phobic Indexes: Check_id 30-39

And it uses a single set of variables for ALL databases' total index feature usage, regardless of which database they're in:

```
SELECT    @number_indexes_with_includes = SUM(CASE WHEN count_included_columns > 0 THEN 1 ELSE 0    END),
@percent_indexes_with_includes = 100.* 
SUM(CASE WHEN count_included_columns > 0 THEN 1 ELSE 0 END) / ( 1.0 * COUNT(*) )
FROM    #IndexSanity;
```

Then in the following lines for checks 30-32, it makes decisions based on those variables, just saying that you don't have filtered indexes or indexed views - but that's at the entire database server level, not on a per-database level.

**What is the expected behavior?**
Instead of using a single variable for everybody's @number_of_indexes_with_includes, we'll need to switch to a table-oriented approach (hey, set-based, everybody's doing it).

**Comment by BlitzErik** [comment]
![image](https://cloud.githubusercontent.com/assets/11590415/25590782/cef83d3c-2e7f-11e7-8fd0-aae2192388b7.png)

**Comment by BrentOzar** [comment]
Perfect! This looks great. Nice job.
