### ISSUE TITLE
sp_BlitzCache -- Index check

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#832]
This is a silly branch to test XML indexing for sp_BlitzCache

Initial thoughts: they don't have a net positive effect because creating them is costly.

However, a half-decent clustered index on the main global temp table seems to help things a big.

**Comment by BlitzErik** [comment]
Closing this -- not goin nowhere!

**Comment by BrentOzar** [comment]
Deleting this branch
