### ISSUE TITLE
SP_BLITZ Check 96 does not check for agent alerts for errors 832 and 855 and 856

### ISSUE THREAD

**Issue by Totty1973** [BrentOzarULTD/SQL-Server-First-Responder-Kit#843]
**Do you want to request a *feature* or report a *bug*?**
Request a Feature

**What is the current behavior?**
checks for agent alerts for errors 823, 824 and 825.

**What is the expected behavior?**
Should also check for 
Error 832: Constant page has changed';
Error 855: Uncorrectable hardware memory corruption detected';
Error 856: SQL Server has detected hardware memory corruption, but has recovered the page';
some people may not be using Glenn Berrys Script at https://dl.dropboxusercontent.com/u/13748067/Add%20SQL%20Server%20Agent%20Alerts.sql

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2012 enterprise edition on Windows 2012 or newer

**Comment by BrentOzar** [comment]
Interesting. On some quick research, looks like 854 makes sense too:
https://support.microsoft.com/en-us/help/2967651/inf-sql-server-may-display-memory-corruption-and-recovery-errors

Those are only severity 10, though:
https://docs.microsoft.com/en-us/sql/relational-databases/errors-events/database-engine-error-severities

Have you actually *seen* any of those errors out in the wild, or is this just a copy/paste of Glenn's scripts? I'm a little hesitant to add sev-10 stuff.

**Comment by Totty1973** [comment]
I haven't seen any of these errors out in the wild, maybe virtualization "hides" some memory errors, and I only have a few dozend sql servers.

**Comment by BrentOzar** [comment]
OK, if it's just a theoretical thing, let's take a pass on it for now. Closing.
