### ISSUE TITLE
sp_BlitzCache: Name & placement of query cost columns inconsistent.

### ISSUE THREAD

**Issue by douglane** [BrentOzarULTD/SQL-Server-First-Responder-Kit#844]
**Do you want to request a *feature* or report a *bug*?**
More bug than feature

**What is the current behavior?**
In @ExpertMode = 1, the Query Plan Cost column is buried about 2/3rds across the result set. In @ExpertMode = 0, it's the second column from left and is called "Cost".

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
Just run it with Expert Mode off and on and you'll see.

**What is the expected behavior?**
Suggest moving Query Plan Cost in Expert Mode to the second column from left, and renaming "Cost" in the non-Expert Mode to "Query Plan Cost" for consistency.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All of them.

**Comment by BlitzErik** [comment]
Howdy! Were you going to code this one?
