### ISSUE TITLE
sp_DatabaseRestore transaction logs are out order

### ISSUE THREAD

**Issue by digitalohm** [BrentOzarULTD/SQL-Server-First-Responder-Kit#849]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When restoring a large amount of transaction logs, they are not restored in order.  This is due to a missing ORDER BY clause

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

I was able to get similar results on SQL 2014 and SQL 2012 with backupsets that contained lots of transaction logs.  Both test cases are on the order of log backups every minute.

  EXEC dbo.sp_DatabaseRestore 
  @Database = 'DATABASENAME', 
  @BackupPathFull = 'C:\Users\username\Desktop\Mirror\FULL\', 
  @BackupPathDiff = 'C:\Users\username\Desktop\Mirror\DIFF\',
  @BackupPathLog = '\\SOMEOTHERPATH\SOMEPATH\MSSQL\SERVERNAME\DATABASENAME\LOG\', 
  @ContinueDiff = 1,
  @ContinueLogs = 0, 
  @RunRecovery = 0;

  EXEC dbo.sp_DatabaseRestore 
  @Database = 'DATABASENAME', 
  @BackupPathFull = 'C:\Users\username\Desktop\Mirror\FULL\', 
  @BackupPathDiff = 'C:\Users\username\Desktop\Mirror\DIFF\',
  @BackupPathLog = '\\SOMEOTHERPATH\SOMEPATH\MSSQL\SERVERNAME\DATABASENAME\LOG\', 
  @ContinueDiff = 0,
  @ContinueLogs = 1, 
  @RunRecovery = 0;

**What is the expected behavior?**

I would expect for transaction logs to be restored chronologically?

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Windows Server 2012 (latest sp) and SQL 2012 (latest sp), and SQL 2014 (latest sp).

Attached is the output from one of the test runs:

[AutomatedRestoreOutput.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/916859/AutomatedRestoreOutput.txt)

**Comment by BlitzErik** [comment]
Howdy,

Thanks for the report. Were you planning on submitting code for this?

Thanks!

**Comment by dbassassin** [comment]
Yes.  I was hoping to just make it part of the branch I submitted for the differential feature request.  It's really such a small fix that I'm not sure a new unique branch needs to be submitted, (but not a problem if that makes it easier for review).

**Comment by BlitzErik** [comment]
Yeah, no problem. Thanks!

**Comment by BlitzErik** [comment]
Closed via #814
