### ISSUE TITLE
sp_DatabaseRestore Output Commands Only

### ISSUE THREAD

**Issue by digitalohm** [BrentOzarULTD/SQL-Server-First-Responder-Kit#850]
**Do you want to request a *feature* or report a *bug*?**
Feature 

**What is the current behavior?**
Currently sp_DatabaseRestore will execute and output messages.  It would be cool if we could just output the commands and run them manually (this would be helpful for testing as well).  I would also like to add a debug mode.  

I currently have a similar mode which can be veiwed as an example at: https://github.com/dbassassin/simpletalk/blob/master/ManagingTestData/sp_automate_restore.sql

I'd like to port this feature into your script.

**Comment by BlitzErik** [comment]
Sure! That'd be great. Make sure to read the [contributing guidelines](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md) first.

**Comment by BlitzErik** [comment]
Closed via #814
