### ISSUE TITLE
sp_BlitzWho - v5.2 Date Overflow Issue with Sleeping SPIDs

### ISSUE THREAD

**Issue by wScottw** [BrentOzarULTD/SQL-Server-First-Responder-Kit#852]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When viewing sleeping spids, I get this error message “The datediff function resulted in an overflow. The number of dateparts separating two date/time instances is too large. Try to use datediff with a less precise datepart.”

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
When showing sleeping spids (sp_blitzwho @ShowSleepingSPIDs = 1) it appears that the [elapsed_time] section of the query broke the 24 days, 20 hours, 31 minutes and 23.647 seconds boundary. The offending dates in my case: 
select datediff(millisecond, ‘2017-03-15 13:38:49.920’, ‘2017-04-13 14:56:05.293’)

**What is the expected behavior?**
Error free bliss.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
2008 R2, 2012, 2014, 2016
Windows Server 2012
Previous version of sp_BlitzWho (v5.0) works.

**Comment by BlitzErik** [comment]
Can you give the version here a shot and let me know if you still get the error?

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/27c24cbe7811e65917d2ef9a5c9f979d82134ed5/sp_BlitzWho.sql

**Comment by wScottw** [comment]
@BlitzErik You do good work. Works like a champ now, thank you.

**Comment by BlitzErik** [comment]
Good to hear! Merging into dev. Thanks again for letting us know.
