### ISSUE TITLE
sp_Blitz -- XML parsing: line 4, character 33, illegal xml character

### ISSUE THREAD

**Issue by ms-chr** [BrentOzarULTD/SQL-Server-First-Responder-Kit#858]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
We have an SQL Server Agent job to execute sp_Blitz every 5 minutes and export the results to an table. On a specific SQL Server 2012(Windows 2012 R2), sometimes ends this job with following error:

[SQLSTATE 01000] (Message 50000)  Now starting diagnostic analysis 
[SQLSTATE 01000] (Message 50000)  Capturing first pass of wait stats, perfmon counters, file stats 
[SQLSTATE 01000] (Message 50000)  Beginning investigatory queries 
[SQLSTATE 01000] (Message 50000)  Finished running investigatory queries 
[SQLSTATE 01000] (Message 50000)  Waiting to match @Seconds parameter 
[SQLSTATE 01000] (Message 50000)  Capturing second pass of wait stats, perfmon counters, file stats 
[SQLSTATE 01000] (Message 50000)  Analyzing changes between first and second passes of DMVs 
[SQLSTATE 01000] (Message 50000)  Analysis finished, outputting results 
[SQLSTATE 01000] (Message 50000)  XML parsing: line 4, character 33, illegal xml character 
[SQLSTATE 42000] (Error 9420).  The step failed.

However, all data was exported to the table.

**Comment by BrentOzar** [comment]
Howdy! Sorry about that. This one's going to be tough to troubleshoot without the data, though - it could be a huge number of things. Do you have anything more specific to go on?

**Comment by ms-chr** [comment]
Hi Brent, 

sure, what you want?
I uploaded the version of sp_blitz and my sp_blitz agent job.

[sp_blitz_#858.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/942250/sp_blitz_.858.txt)
[sp_blitz_job_#858.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/942249/sp_blitz_job_.858.txt)

Regards
Michael

**Comment by BrentOzar** [comment]
Hmm - have you got another person in your team who can look at this with a fresh set of eyes?

I hate to ask this, but the first thing is that your job calls sp_BlitzFirst, not sp_Blitz. You sent me the code for sp_Blitz, and a job that calls sp_BlitzFirst. :-D You might be looking so closely that you're not seeing the big picture, heh. Also, make sure you update your code - you're running older versions of the procs.

**Comment by ms-chr** [comment]
Oops :-/, I will try it with an newer version of the sp_Blitz**First**!
Thanks!

**Comment by BrentOzar** [comment]
OK, great. Closing this. Before you re-open it, let's have another person at your shop take a look at it with fresh eyes, and bring back more details. Thanks!
