### ISSUE TITLE
Would it be useful to read the error log in sp_BlitzFirst or sp_Blitz?

### ISSUE THREAD

**Issue by RichBenner** [BrentOzarULTD/SQL-Server-First-Responder-Kit#865]
**Do you want to request a *feature* or report a *bug*?**
Possible Feature

**What is the current behavior?**
I recently had a client with stack dumps occurring which were filling the hard drive. currently i don't think the blitz scripts check to see if this may be happening. The stored proc xp_readerrorlog would allow the error log to be checked for this and other major issues. The obvious downside of this is that the error log can be massive in certain situations so it may slow down the procedure and you need admin permissions i believe (this could be checked and built in to see if the user has the admin permissions). Perhaps this could be something for expert mode only if it were in blitz first?

**What is the expected behavior?**
Throw a flag if the server is seeing stack dumps or other major issues that are appearing in the error log.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
this sp is in all supported versions of sql server i believe.

**Comment by BrentOzar** [comment]
Yep, sp_Blitz already checks for memory dumps. It's check 171:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/Documentation/sp_Blitz%20Checks%20by%20Priority.md

I agree about xp_readerrorlog - I'd love to add it, but I've seen yuuuuuge error logs that take minutes to read. Closing. Good idea though!
