### ISSUE TITLE
Please add instance information to results of e.g. sp_BlitzIndex

### ISSUE THREAD

**Issue by ALZDBA** [BrentOzarULTD/SQL-Server-First-Responder-Kit#870]
**Do you want to request a *feature* or report a *bug*?**
Please add some server related information to the result set(s), e.g. in line number -1 

SELECT SERVERPROPERTY('ServerName') AS ServerName,
       last_startup_time as InstanceLastStartupTime
FROM sys.dm_server_services WITH (NOLOCK)
where last_startup_time is not null
OPTION(RECOMPILE);

**What is the current behavior?**
-1 | sp_BlitzIndex(TM) v5.2 - April 06, 2017: Database [Insite_Coil] as of 2017-05-03 09:22
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

**What is the expected behavior?**
-1 | sp_BlitzIndex(TM) v5.2 - April 06, 2017: Instance [MyInstance] Database [Insite_Coil] as of 2017-05-03 09:22 (Last Instance startup [2017-03-31 14:36] )

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

**Comment by BrentOzar** [comment]
Nah, for server info, check out sp_Blitz.
