### ISSUE TITLE
sp_Blitz DBCC Events - CHECKDB

### ISSUE THREAD

**Issue by MosesOfJ** [BrentOzarULTD/SQL-Server-First-Responder-Kit#872]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
sp_Blitz check 199 (DBCC Events / Overall Events) does not exclude 'DBCC CHECKDB' events.

It appears there is a typo for the CHECKDB test ('DBCC CHECKCB') ;-)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

Execute a DBCC CHECKDB then run sp_Blitz.

**What is the expected behavior?**
DBCC CHECKDB events are not included in the count of unexpected DBCC events.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Issue appears in both SQL Server 2008 R2 SP3 (Windows Server 2008 R2)  and SQL Server 2016 SP1 CU2 (Windows Server 2012 R2).

**Comment by BrentOzar** [comment]
Hahaha, great catch! I checked in the fix. (Will be out in the main branch next month.) Thanks!
