### ISSUE TITLE
sp_Blitz DBCC Events - Log Cycle

### ISSUE THREAD

**Issue by MosesOfJ** [BrentOzarULTD/SQL-Server-First-Responder-Kit#874]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
sp_Blitz check 199 (DBCC Events / Overall Events) does not exclude 'DBCC DBCC ERRORLOG' events, 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
Execute sp_cycle_errorlog, then run sp_Blitz.

**What is the expected behavior?**
I would consider log cycling 'noise', so perhaps this should be filtered out.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2016 SP1 CU2 (Windows Server 2012 R2).

**Comment by BrentOzar** [comment]
Dumb question: how often are you cycling the error log?

**Comment by MosesOfJ** [comment]
Daily, with a 30 log limit

**Comment by BrentOzar** [comment]
OK, so I'm going to make an executive judgment call here and say that that's fairly unusual - I've rarely seen folks do that in the wild - and I'd rather know about it than not know. 

I totally understand if you want to skip the check, and if so, dig into the SkipChecks* parameters.

Thanks though!

**Comment by MosesOfJ** [comment]
Out of interest, do you have a best practice for cycling the log?  I have seen > 10GB files in the wild that are somewhat challenging to review if SQL Server does have 'moment', hence taking a more aggressive approach to this.  Even a monthly cycle would still, I believe, be picked up by the check.

**Comment by BrentOzar** [comment]
In our setup checklist, I wanna say we do it weekly. (Which is fine, I don't have a problem with that being caught by the check.)

**Comment by MosesOfJ** [comment]
Thanks Brent.  

I *may* request a feature to output those checks (or a summary or the those checks) that are caught to reduce the scare factor from a priority 50 check... ;-)
