### ISSUE TITLE
Divide by zero errors in sp_BlitzFirst

### ISSUE THREAD

**Issue by PhilAitch** [BrentOzarULTD/SQL-Server-First-Responder-Kit#876]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
This doesn't happen constantly but on one particular Instance it seemed to be happening every hour on the quarter hour (I'm running it every 5 mins) when a particular third-party import job was running.
Results from query:
sp_BlitzFirst
    @seconds=30 
  , @expertmode = 1
  , @OutputDatabaseName = 'DBA_Admin'
  , @OutputSchemaName = 'dbo'
  , @OutputTableName = 'AskBrentResults'
  , @OutputTableNameFileStats = 'AskBrentResults_FileStats'
  , @OutputTableNamePerfmonStats = 'AskBrentResults_PerfmonStats'
  , @OutputTableNameWaitStats = 'AskBrentResults_WaitStats'
are as follows:
Setting up configuration variables
Now starting diagnostic analysis
Capturing first pass of wait stats, perfmon counters, file stats
Beginning investigatory queries
Finished running investigatory queries
Capturing second pass of wait stats, perfmon counters, file stats
Analyzing changes between first and second passes of DMVs
Msg 8134, Level 16, State 1, Procedure sp_BlitzFirst, Line 1642 [Batch Start Line 0]
Divide by zero error encountered.
The statement has been terminated.
Analysis finished, outputting results
Msg 8134, Level 16, State 1, Procedure sp_BlitzFirst, Line 2429 [Batch Start Line 0]
Divide by zero error encountered.
Msg 8134, Level 16, State 1, Procedure sp_BlitzFirst, Line 2526 [Batch Start Line 0]
Divide by zero error encountered.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
running the query above on the particular Instance on the quarter hour.
**What is the expected behavior?**
Expected results are:
Setting up configuration variables
Now starting diagnostic analysis
Capturing first pass of wait stats, perfmon counters, file stats
Beginning investigatory queries
Finished running investigatory queries
Waiting to match @Seconds parameter
Capturing second pass of wait stats, perfmon counters, file stats
Analyzing changes between first and second passes of DMVs
Analysis finished, outputting results
**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2012 Windows 2012 R2
I don't recall it failing in previous versions of sp_BlitzFirst

**Comment by BrentOzar** [comment]
What version of sp_BlitzFirst are you on? (We've had a few of these that have been fixed over time.)

**Comment by PhilAitch** [comment]
Sorry, forgot to include details. 
Version = '5.2';
VersionDate = '20170406';

**Comment by BrentOzar** [comment]
OK, thanks. Go ahead and upgrade to the current version. I'm going to close this for now, but feel free to reopen it if it happens with the current version. Thanks!
