### ISSUE TITLE
sp_BlitzIndex Partition when there are none

### ISSUE THREAD

**Issue by MrTCS** [BrentOzarULTD/SQL-Server-First-Responder-Kit#880]
sp_BlitzIndex 5.3  
SQL 2012 SP1
Windows 2008 R2

I'm running sp_BlitzIndex against one of our larger tables.  Most of the indexes only show a row count and size in the "size" column but two are showing [# Partitions] as well.  This table is not partitioned so I'm not sure where this is coming from.  One index in particular is showing as having 19 Partitions (and 19 times the row count of the entire table).  Looking in sys.dm_db_partition_stats I only see one for that index, and all rows have partition_number of 1.  "Compression Type" just repeats "Partition 1 uses Page" 19 times.

**Comment by BrentOzar** [comment]
Can you attach a screenshot or copy paste it into Excel, and also include the output for @Mode=2? Thanks!

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by MrTCS** [comment]
![image](https://cloud.githubusercontent.com/assets/21134241/26126490/c2b5b8e4-3a53-11e7-8465-461d980b9b48.png)

Found the issue, though not the cause of the issue.  sys.dm_db_index_operational_stats is returning 19 rows for that one index. 

![image](https://cloud.githubusercontent.com/assets/21134241/26126547/020a68fa-3a54-11e7-84ad-91774428fec6.png)

Mode 2 output for that index.
![image](https://cloud.githubusercontent.com/assets/21134241/26126658/7b7b32aa-3a54-11e7-96b5-43c4b75ec64b.png)

**Comment by BrentOzar** [comment]
Gotcha. Multiple rows in that DMV for a given index would be a SQL Server bug. It's an interesting bug, never seen it before. I'd make sure you're fully patched, and if so, open up a support case with Microsoft. I bet they'd be excited to see that - it affects a lot more than sp_BlitzIndex.

Closing this though - this wouldn't be something we'd code a fix for.

**Comment by BlitzErik** [comment]
Doesn't happen to be ColumnStore, does it?
