### ISSUE TITLE
sp_BlitzCache - missing comma in long-running check

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#881]
**Do you want to request a *feature* or report a *bug*?**
El Buggo

**What is the current behavior?**
Search for this line:

CASE WHEN long_running_low_cpu = 1 THEN + 'Long Running With Low CPU' ELSE '' END
                  , 2, 200000) 

Just needs a comma in front of the check name::

CASE WHEN long_running_low_cpu = 1 THEN + ', Long Running With Low CPU' ELSE '' END
                  , 2, 200000)

**Comment by BlitzErik** [comment]
Ah, I fixed it in the first one but not the second one. No problem.
