### ISSUE TITLE
sp_BlitzBackups -- fix parameters and create table if it doesn't exist.

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#885]
**Do you want to request a *feature* or report a *bug*?**
Boog

**What is the current behavior?**
Stuff Brent said

**What is the expected behavior?**
Stuff Brent said

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All'vem

**Comment by BrentOzar** [comment]
This works, marking complete.

**Comment by BrentOzar** [comment]
Deleting this branch
