### ISSUE TITLE
sp_BlitzCache  Feature - Sort by Cost

### ISSUE THREAD

**Issue by Brianc-DBA** [BrentOzarULTD/SQL-Server-First-Responder-Kit#894]
**Do you want to request a *feature* or report a *bug*?**
Feature - if sp_BlitzCache could have a SortOrder of cost, that would display and therefore help clients deal with the highest cost queries in the cache.

**What is the current behavior?**
The SortOrder parameter can be used to sort on several types (cpu, duration, reads, executions, etc.), but not cost

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
You can use several values for @SortOrder.  For example:
exec sp_BlitzCache @SortOrder = 'cpu' will sort results by cpu.
exec sp_BlitzCache @SortOrder = 'cost' will not run as expected.  By default it will sort by cpu if you use anything other than a prescribed list of values in @SortOrder.

**What is the expected behavior?**
exec sp_BlitzCache @SortOrder = 'cpu' would continue to sort results by cpu.
exec sp_BlitzCache @SortOrder = 'cost' would sort results by cost.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
n/a, this has not been included in past versions to my knowledge

**Comment by BrentOzar** [comment]
Cost is an estimate of the query's overhead BEFORE it's executed. It's not a great way to analyze queries.

**Comment by BlitzErik** [comment]
Beyond that, cost is a plan cache attribute we get from the XML. In order to sort on it, we'd have to examine the entire plan cache first, which could be quite costly. Look through the code to see all the work that has to get done to get costs for just the top 10 plans. 

Thanks!

**Comment by Brianc-DBA** [comment]
True enough, I poked around through the code and suspected it might be complicated to do.  Thanks, guys!
