### ISSUE TITLE
sp_Blitz -- Make backup on same drive check Mount Point aware

### ISSUE THREAD

**Issue by mjpelikan** [BrentOzarULTD/SQL-Server-First-Responder-Kit#896]
Make the Finding: "Backing Up to Same Drive Where Databases Reside" aware of mount points so the script does not report false positives.

**Comment by BlitzErik** [comment]
Howdy,

We've had this issue come up a few times. 

The thing is, we don't have any drives with mount points to test code out on.

If you'd like to code it using your mount points, let me know. Otherwise, I'm going to close it out.

Thanks!

**Comment by BrentOzar** [comment]
@mjpelikan - in the past, we tried tackling this but SQL 2005 didn't have support for mount point DMVs. That's better in 2008, but it's still going to be a little painful to join that DMV to the backup DMVs to narrow down data/log/backup file locations and string parse them.

**Comment by BlitzErik** [comment]
Removing milestone until we hear back from @mjpelikan

**Comment by BlitzErik** [comment]
It's been 30 days without a response, closing.
