### ISSUE TITLE
Arithmetic overflow error converting expression to data type int sp_Blitz

### ISSUE THREAD

**Issue by dbaab** [BrentOzarULTD/SQL-Server-First-Responder-Kit#901]
Testing the current version - 5.3 and versionDate = 2017-05-01 on SQL Server 2014 receiving the following error message:

Msg 8115, Level 16, State 2, Procedure sp_Blitz, Line 516 [Batch Start Line 0]
Arithmetic overflow error converting expression to data type int.
The statement has been terminated.

This version runs without error on dev and test server running SQL Server 2014.

**Comment by BrentOzar** [comment]
Hmmm, I can't see anything that might do it, but try these queries and let me know what the output is:

SELECT create_date FROM sys.databases WHERE name='tempdb';
SELECT MAX(wait_time_ms) FROM sys.dm_os_wait_stats;

**Comment by dbaab** [comment]
error was resolved after server reboot (maintenance work) this am. Thanks much.

**Comment by BrentOzar** [comment]
OK, gotcha, closing.
