### ISSUE TITLE
sp_BlitzBackups Error

### ISSUE THREAD

**Issue by jsetliffe** [BrentOzarULTD/SQL-Server-First-Responder-Kit#906]
All, I am getting an error when running sp_BlitzBackups on my production SQL 2012 ( build 11.0.6544.0) instance.  It works fine on my QA one, same build number.  What could be the issue?  Here is the error:

Inserting to #Backups
Updating #Backups with worst RPO case
Warning: The join order has been enforced because a local join hint is used.
Updating #Backups with worst RPO case queries
Gathering RTO information
Updating #RTORecoveryPoints
Add any full backups in the StartDate range that weren't part of the above log backup chain
Fill out the most recent log for that full, but before the next full
Fill out a diff in that range
Get time & size totals for full & diff
Get time & size totals for logs
Gathering RTO worst cases
Returning data
Rules analysis starting
Warning: Null value is eliminated by an aggregate or other SET operation.
Msg 105, Level 15, State 1, Line 7
Unclosed quotation mark after the character string ' backups, and the last time a certificate was backed up is Aug 24 2015  6:14PM. AS [Warning]
							FROM   [msdb].dbo.backupset AS b
							WHERE b.encryptor_type IS NOT NULL
							GROUP BY b.database_name, b.encryptor_type;
'.
Msg 102, Level 15, State 1, Line 7
Incorrect syntax near ' backups, and the last time a certificate was backed up is Aug 24 2015  6:14PM. AS [Warning]
							FROM   [msdb].dbo.backupset '.
Rules analysis starting on temp tables
Rules analysis finished

For both instances I run sp_BlitzBackups with the master database selected.

**Comment by BlitzErik** [comment]
Howdy,

Can you run it with @Debug = 1 on, and paste in the query the full text of the query it errors out on? Looks like CheckId 9.

Thanks!

**Comment by jsetliffe** [comment]
[debug_for_Erik.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/1039115/debug_for_Erik.txt)
error file attached

**Comment by BlitzErik** [comment]
Thanks for the quick reply!

Can you try the version here? 

https://raw.githubusercontent.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/sp_BlitzBackups_906/sp_BlitzBackups.sql

**Comment by jsetliffe** [comment]
Different error this time:
Inserting to #Backups
Updating #Backups with worst RPO case
Warning: The join order has been enforced because a local join hint is used.
Updating #Backups with worst RPO case queries
Gathering RTO information
Updating #RTORecoveryPoints
Add any full backups in the StartDate range that weren't part of the above log backup chain
Fill out the most recent log for that full, but before the next full
Fill out a diff in that range
Get time & size totals for full & diff
Get time & size totals for logs
Gathering RTO worst cases
Returning data
Rules analysis starting
Warning: Null value is eliminated by an aggregate or other SET operation.
Msg 207, Level 16, State 1, Line 9
Invalid column name 'encryptor_type'.
Msg 207, Level 16, State 1, Line 10
Invalid column name 'encryptor_type'.
Msg 207, Level 16, State 1, Line 7
Invalid column name 'encryptor_type'.
Rules analysis starting on temp tables
Rules analysis finished

**Comment by BlitzErik** [comment]
Oh boy, that column doesn't exist in 2012, which would make sense based on the fact that we didn't get encrypted backups until 2014. 

I'll need to roll out a larger fix for this. In the meantime, can you just quote that bit of dynamic SQL out? It should be everything in this section:
```

	/*Checking for encrypted backups and the last backup of the encryption key.*/

	SET @StringToExecute = N'SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;' + @crlf;

	SET @StringToExecute += N'SELECT 
								9 AS CheckId,
								100 AS [Priority],
								b.database_name AS [Database Name],
								''Encrypted backups'' AS [Finding],
								''The database '' + QUOTENAME(b.database_name) + '' has had '' + CONVERT(VARCHAR(10), COUNT(*)) + '' '' + b.encryptor_type + '' backups, and the last time a certificate was backed up is '
								+ CASE WHEN LOWER(@MSDBName) <> N'msdb'
									THEN + N'...well, that information is on another server, anyway.'' AS [Warning]'
									ELSE + CONVERT(VARCHAR(30), (SELECT MAX(c.pvt_key_last_backup_date) FROM sys.certificates AS c WHERE c.name NOT LIKE '##%')) + N'.'' AS [Warning]'
									END + 
							N'
							FROM   ' + QUOTENAME(@MSDBName) + N'.dbo.backupset AS b
							WHERE b.encryptor_type IS NOT NULL
							GROUP BY b.database_name, b.encryptor_type;' + @crlf;

	IF @Debug = 1
		PRINT @StringToExecute;

		INSERT #Warnings ( CheckId, Priority, DatabaseName, Finding, Warning )
		EXEC sys.sp_executesql @StringToExecute;

```

**Comment by BlitzErik** [comment]
Some notes:

We declare variables to get version/edition, but we never do anything with them:
```
@ProductVersion NVARCHAR(128), 
@ProductVersionMajor DECIMAL(10, 2),
@ProductVersionMinor DECIMAL(10, 2), 
```
Changes I need to make:
Populate these variables
Skip the encryption check for sub-2014 versions
Alter dynamic SQL in the data mover to skip this column (and others?) based on version (major)

**Comment by jsetliffe** [comment]
How is this working on our other SQL 2012 version?

**Comment by BlitzErik** [comment]
Can you try running this on both?

```
SELECT TOP 1 @@VERSION, b.encryptor_type
FROM msdb.dbo.backupset AS b
WHERE b.encryptor_type IS NOT NULL
```

**Comment by jsetliffe** [comment]
Msg 207, Level 16, State 1, Line 3
Invalid column name 'encryptor_type'.
Msg 207, Level 16, State 1, Line 1
Invalid column name 'encryptor_type'.

That's for both instances

**Comment by BlitzErik** [comment]
The result of this query should be different on them:

```
SELECT MAX(c.pvt_key_last_backup_date)
FROM   sys.certificates AS c
WHERE  c.name NOT LIKE '##%';
```

If it's `NULL` in dev, then the string we execute will go `NULL` and not be executed. If it's not `NULL` in prod, then the script will continue on.

**Comment by jsetliffe** [comment]
NULL in dev and a timestamp in production

2015-08-24 18:14:03.033

**Comment by BlitzErik** [comment]
Yerp. That's why it passed over here. No backed up certs on our 2012 box. Sorry about that! 

I'll have a fix out shortly.

**Comment by BlitzErik** [comment]
Can you try the version here?

https://raw.githubusercontent.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/713855f4cd6f9a7306a99429b7ba7c341f7f5aa8/sp_BlitzBackups.sql

**Comment by jsetliffe** [comment]
Perfecto!  Thank you sir

**Comment by BlitzErik** [comment]
Glad it's working! Thanks for letting us know about that.
