### ISSUE TITLE
sp_blitzbackups reporting Big Diffs when they're not big

### ISSUE THREAD

**Issue by gdoddsy** [BrentOzarULTD/SQL-Server-First-Responder-Kit#911]
Just tried out sp_blitzbackups and it works great, however I'm getting a report on our main database that it has Big Diffs (On average, Differential backups for this database are >=40% of the size of the average Full backup.)

I think this is wrong. According to the first dataset, which matches the files, our full backups average [FullCompressedSizeMBAvg] is 61906.19MB. Our [DiffCompressedSizeMBAvg] is 2022.57MB which is around 3%. Uncompressed is similar (average full = 256377MB, average diff = 9356, around 3%)

**Comment by BlitzErik** [comment]
Howdy,

That sure doesn't sound very big. Any chance you could drop an Excel file of your full results so I can take a look? You can redact database names and any other identifying information.

We mark the big diffs (and similarly big logs) using a computed column:

`IsBigDiff AS CASE WHEN (AvgFullSize - AvgDiffSize) * .01 > .40 AND (AvgFullSize > 1073741824)  THEN 1 ELSE 0 END,`

We get the average sizes looking at the avg `backup_size` in `dbo.backupset` for fulls and diffs, and compare those in the computed column. We're not looking at the columns that you're judging things by at all.

That being said, I'd be happy to make adjustments here. I wrote this part in a way that looked good on my sort of limited/contrived backup data, so it could totally be improved for different situations, and it would be fairly easy to add compressed backup sizes into the mix and compare those instead.

Thanks for your help!

**Comment by gdoddsy** [comment]
Excel file attached for the top 2 data sets. In addition to the Big Diffs we're also seeing Big Logs warnings. I think these are also wrong.

A bit more info on our setup, we do weekly full backups and nightly differentials and 5 minute Log backups on all databases on this server. We're seeing the same sort of ratio (< 10%) on a lot of our databases.

We had some massive code changes a bit over a month ago which rearranged a massive amount of the database, those differentials were huge, maybe that's breaking the averages? We also had a few full backups fail which meant the differentials kept growing. Did a quick check, and some dodgy SQL:

`select AVG(backup_size) from msdb.dbo.backupset where database_guid = '6A149C11-502A-4112-ADEC-8CFA0DAA0320' and type = 'D' and backup_start_date > '24 May 2017'

select AVG(backup_size) from msdb.dbo.backupset where database_guid = '6A149C11-502A-4112-ADEC-8CFA0DAA0320' and type = 'I' and backup_start_date > '24 May 2017'

select AVG(backup_size) from msdb.dbo.backupset where database_guid = '6A149C11-502A-4112-ADEC-8CFA0DAA0320' and type = 'L' and backup_start_date > '24 May 2017'`

Results are:
Full: 268830879744.000000
Diff: 9811330389.333333
Log: 9811330389.333333

Hope that helps!

[Backup Info for Primary Database.xlsx](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/1040165/Backup.Info.for.Primary.Database.xlsx)

**Comment by BlitzErik** [comment]
Thanks.

I made some changes and tossed them in the dev branch after a few rounds of testing. Let me know if they help.

https://raw.githubusercontent.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/abedea4c575c363e388b5c269b7d287e763b0eb8/sp_BlitzBackups.sql

**Comment by SOlsonFAC** [comment]
Hi Erik.  You can't calculate percentages with subtraction: WHEN (AvgFullSize - AvgDiffSize) * .01 > .40
You need to use division:  WHEN AvgFullSize > 0 and (AvgDiffSize*100)/AvgFullSize > 40

**Comment by gdoddsy** [comment]
Hi Erick, not in the office yet, but just a quick look and I think it's going to be the same problem. I'm with SOIsonFAC, you need to DiffSize/FullSize > .40. A big Full - little diff will leave you with a big number

**Comment by gdoddsy** [comment]
I think I've got the right calculation. I'll see if I can sort out this git thing when I get to the office and add a pull request

**Comment by BlitzErik** [comment]
Well, hang on. 

I want to figure out a size threshold to start worrying about diff size mattering.  

Right now we look at fulls over 1gb, but that seems too low to worry about diff sizes. 

Also, that calculation (generally) works, but i had testing artifacts in there, it should have been (F - D) * .1 <= .40

That should (unless my math is as horrible as it's been accused of being) get you flagged at 60% and up? Which I believe is what we're after, but I'm game for that changing as well.

Sorry about that!

```
SELECT (10 - 9) * .1
UNION ALL
SELECT (10 - 8) * .1
UNION ALL
SELECT (10 - 7) * .1
UNION ALL
SELECT (10 - 6) * .1
UNION ALL
SELECT (10 - 5) * .1
UNION ALL
SELECT (10 - 4) * .1
UNION ALL
SELECT (10 - 3) * .1
UNION ALL
SELECT (10 - 2) * .1
UNION ALL
SELECT (10 - 1) * .1 
```

```
0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9
```

**Comment by SOlsonFAC** [comment]
Percentage is part/whole x 100.  Multiply the AvgDiffSize by 100 first because they are bigint and then divide by AvgFullSize to get a value from 0 to 100.  Or cast them to float first and divide:  CAST(AvgDiffSize as Float) / CAST(AvgFullSize as Float) to get a value between 0.00 and 1.00

The threshold doesn't matter as far as the math goes.  Imagine a 10TB database that produces a 25GB diff backup.  Your code takes 10,000,000,000,000 - 25,000,000,000 = 9,975,000,000,000   ... a very large number.
Versus 25GB / 10000GB = .0025 = 0.25%

**Comment by gdoddsy** [comment]
I'm on board with 60% being the number.
I learnt maths (with an s) upside down in Australia, so I may be way off, but I don't think your calculation works when you get to bigger numbers.

`SELECT (100000-90000) * .1 --= 1000...differential is 90% of full`
`SELECT (100000-60) * .1 --= 9,994...differential is 0.06% of full`

Both numbers are way bigger than 0.4, so both numbers are either going to report as being large or being small.

**Comment by SOlsonFAC** [comment]
It might be that you are thinking of remaining percentage, like I take 2 from 10 and the remainder is 8.  For the percentage,  (Full - Taken) / Full = Remaining percent.  (10 - 2) / 10 = 8/10 = .80 = 80%

**Comment by BlitzErik** [comment]
Ah hah. Back to math class with me.

I'll switch it to your way.

**Comment by BlitzErik** [comment]
Updated here: 
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzBackups.sql

**Comment by gdoddsy** [comment]
Thanks Erick - looks great on my servers now
