### ISSUE TITLE
sp_BlitzBackups -- populate RTO more info column

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#915]
**Do you want to request a *feature* or report a *bug*?**
Feabug

**What is the current behavior?**
We don't populate this column:

![image](https://cloud.githubusercontent.com/assets/11590415/26656475/3f3840a0-462d-11e7-9595-539c0dfcda78.png)

**What is the expected behavior?**
It should have a query similar to RPO worst case

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All

**Comment by BrentOzar** [comment]
Taking the milestone off - I'll definitely code this, just may not get to it until Aug/Sept.

**Comment by BrentOzar** [comment]
This proc didn't get a lot of traction, so closing.
