### ISSUE TITLE
Missing closing quote in dynamic SQL in sp_BlitzBackups

### ISSUE THREAD

**Issue by TheUsernameSelectionSucks** [BrentOzarULTD/SQL-Server-First-Responder-Kit#918]
**Do you want to request a *feature* or report a *bug*?**
Bug in sp_BlitzBackups 5.3

**What is the current behavior?**
Get an error when running the proc. It appears this is in the warning section for encryption certificates.

Screenshot attached.

![blitzbackups_error](https://cloud.githubusercontent.com/assets/26902750/26698377/59b87b9e-46db-11e7-8bba-544e652302da.JPG)

**What is the expected behavior?**
To not get an error. It appears this is in the warning section for encryption certificates.
See attached for fix.
![blitzbackups_fix](https://cloud.githubusercontent.com/assets/26902750/26698386/656ca7ee-46db-11e7-9ff8-b486aeb496be.JPG)

*Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

SQL 2016 SP1 CU3, Windows 2012 R2

**Comment by BlitzErik** [comment]
Howdy,
This already has an issue here: #906 and a fix in the dev branch. Go ahead and grab that version and let me know if you run into anything new.

Thanks!

**Comment by TheUsernameSelectionSucks** [comment]
Thanks. That seems to work.

And, sorry I miss labeled the bug. I was trying to go back to rename it properly.

**Comment by BlitzErik** [comment]
No problem at all! Enjoy the (working) script!
