### ISSUE TITLE
sp_BlitzBackups -- Include "Physical Device Name" information in pushed backup history

### ISSUE THREAD

**Issue by dansqldba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#919]
**Do you want to request a *feature* or report a *bug*?**
Feature

The backup history which is pushed to a central location does not currently include the "Physical Device Name" as shown on a local server's "Backup and Restore History" report built into SSMS.

Storing the physical location of the backup might be useful information, in my case, when writing reports which use this consolidated backup history to centralise the reporting.

**Comment by BlitzErik** [comment]
Real quick -- we collect all our data from `dbo.backupset`, is the data you're looking for in that table, or in a different one? if it's in a different table, it's a bigger change for all our queries.

**Comment by BlitzErik** [comment]
Howdy Dan!

Just checking in on this question before I start working on it.

Thanks!

**Comment by BlitzErik** [comment]
Removing milestone until we hear back from @dansqldba

**Comment by dansqldba** [comment]
Hi @BlitzErik, sorry for the delay, been enjoying some annual leave!

It's in a different table, msdb.dbo.backupmediafamily I believe, the physical_device_name column.

```sql
SELECT backupset.* ,
       backupmediafamily.physical_device_name
FROM   dbo.backupset
       LEFT JOIN backupmediafamily ON backupset.media_set_id = backupmediafamily.media_set_id;
```
I guess that does complicate things a touch! Completely understand if you don't wish to pursue this, but I'm happy to help if I can.

**Comment by BlitzErik** [comment]
Ooh, yeah, that would change a heck of a lot of code and a couple table definitions. I think we have to pass on this one for now. Thanks for the suggestion, though.
