### ISSUE TITLE
SP_BILTZCACHE

### ISSUE THREAD

**Issue by Ramaudaya** [BrentOzarULTD/SQL-Server-First-Responder-Kit#920]
in your sp_XXXXcahce - there is query called "DBCC FREEPROCCACHE " --- is that safe to run in the production, I think it shouldn't but not sure- in your script it's used & will it clears caches for all the system.

is that safe to run?

**Comment by BlitzErik** [comment]
We give that command in the event that you have a bad execution plan in cache for a specific query. You should only run it if you understand what you're doing and why you're doing it. 

It's "safe" to run in production with proper analysis or knowledge of the workload. We would not recommend running that command without the additional parameter to target a specific sql handle or plan handle. 

Again, don't run it unless you understand what you're doing and why you're doing it.

**Comment by Ramaudaya** [comment]
I will recheck again.
