### ISSUE TITLE
sp_DatabaseRestore -- add NULL fault for if @DatabaseLastLSN is NULL

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#922]
Not sure if we need this, but figured I'd log it just in case.  In the middle of the proc we have code that does this:

```
SELECT @DatabaseLastLSN = CAST(f.redo_start_lsn AS NUMERIC(25, 0))
FROM master.sys.databases d
JOIN master.sys.master_files f ON d.database_id = f.database_id
WHERE d.name = @RestoreDatabaseName AND f.file_id = 1;
```

If that variable ends up being `NULL` what happens? It gets used in a couple pieces of code like this:

```
IF (@ContinueLogs = 0 AND @LogFirstLSN <= @FullLastLSN AND @FullLastLSN <= @LogLastLSN AND @RestoreDiff = 0) OR (@ContinueLogs = 1 AND @LogFirstLSN <= @DatabaseLastLSN AND @DatabaseLastLSN < @LogLastLSN AND @RestoreDiff = 0)
SET @i = 2;

IF (@ContinueLogs = 0 AND @LogFirstLSN <= @DiffLastLSN AND @DiffLastLSN <= @LogLastLSN AND @RestoreDiff = 1) OR (@ContinueLogs = 1 AND @LogFirstLSN <= @DatabaseLastLSN AND @DatabaseLastLSN < @LogLastLSN AND @RestoreDiff = 1)
SET @i = 2;
```

Do we need to stop processing is that variable is `NULL`? 

Tagging @digitalohm in this since I believe it's code he added, but not sure. Also tagging @TaraKizer in case this came from her.

**Comment by BlitzErik** [comment]
This doesn't seem like a big deal to anyone, so closing out.

**Comment by digitalohm** [comment]
I had looked at this and it was part of the original code that I just copied over for safety.  I had a good idea what it was doing but then forgot :D  I think if the value is null it would signal that the database is no longer in a restoring state, but that could be the answer to a completely different issue I was working on o_o

**Comment by BlitzErik** [comment]
Hahaha, well, uh, glad to help?
