### ISSUE TITLE
sp_DatabaseRestore -- Debug is broken

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#923]
**Do you want to request a *feature* or report a *bug*?**
Right now, the `@Debug` parameter is declared like this:

`@Debug INT = 0`

We usually do this as a `BIT` and set it to 1 to debug. Our example code calls all point to setting it to 1 to print statements out, but in all the code, the `IF` is checking if `@Debug` = 2.

Quick example:

![image](https://cloud.githubusercontent.com/assets/11590415/26792367/2c83bb10-49e8-11e7-8d82-88231bcea8b5.png)

Tagging @digitalohm  and @TaraKizer for background

**Comment by digitalohm** [comment]
@BlitzErik  I had added it in as an int for further debug levels.  Just from my own code purposes I would set a debug level 0 for execute, 1 for print commands, and 2 for printing commands + other information useful for troubleshooting like variables etc.  Level 2 would be more for the programmers benefit.

**Comment by BlitzErik** [comment]
Cool -- I don't see any references to `@Debug = 1` to print commands though, so when would it be useful to do that in existing code? No rush on this, just a curiosity.

**Comment by digitalohm** [comment]
ok that is weird....

I thought that was added and merged when I submitted for Issue 850?
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/850

Perhaps I messed up using github and overwrote it?

**Comment by BlitzErik** [comment]
@digitalohm did you have a chance to look at this part yet?

**Comment by digitalohm** [comment]
Not yet.  Multiple jobs drug me away via demonic summoning spells.

The @debug variables were just mistakenly used.  I accidentally made used @debug = 2 for both printing commands and variables.  @debug = 1 should be for printing commands where as @debug = 2 is for dev sanity.

I can probably adjust this by the end of the day PDT.

**Comment by BlitzErik** [comment]
No rush! Won't be doing an FRK release until EOM. I only asked since you mentioned you may have code already written that fixed this. Heh.

**Comment by digitalohm** [comment]
did you want me to submit the changes to a different repo?  I can't find the email that had the link to it :/

**Comment by BlitzErik** [comment]
Yeah, do it as a separate branch if you can. That way you can use the latest version from dev. Thanks!
