### ISSUE TITLE
sp_DatabaseRestore -- Order files in dir command

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#924]
Back when I had to use xp_cmdshell a lot to run `dir` and get file lists, it helped to use `/od` to order files ascending by date or `/o-d` to order descending by date. Should we be doing that here? It seems like it might make some things easier, but want to make sure before I add it in.

Again, tagging @digitalohm  and @TaraKizer  for background.

**Comment by digitalohm** [comment]
I believe the 	  ORDER BY BackupFile;   in the code is accomplishing the same thing for when the log backups are being sorted.  I'm not sure if table variables work the same way as tables in the sense that when they are queried results are not guaranteed to be in any order unless ORDER BY is used.   If that is the case it's probably safer to keep using the sort when pulling the results

**Comment by BlitzErik** [comment]
Yeah, looking back at when I used this, I was putting the files into a table with an identity/sequence column and looping over them based on the sequence. Not sure if that helps us here yet.
