### ISSUE TITLE
sp_BlitzWho - add XML output type

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#925]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
sp_BlitzWho outputs to table.

**What is the expected behavior?**
Export to a single XML field for alerting/logging purposes. (This means we probably can't capture the entire query - maybe just the first 1k characters, and strip out things that would break XML.)

**Comment by BlitzErik** [comment]
@BrentOzar do you still want this? Not sure if it's necessary anymore.

**Comment by BrentOzar** [comment]
I think it's an interesting idea, but nah, we can hold off. Closing.
