### ISSUE TITLE
sp_Blitx

### ISSUE THREAD

**Issue by gjschipper** [BrentOzarULTD/SQL-Server-First-Responder-Kit#932]
**While running the latest sp_blitz:**

EXEC [dbo].[sp_Blitz]
    @CheckUserDatabaseObjects = 1 ,
    @CheckProcedureCache = 0 ,
    @OutputType = 'TABLE' ,
    @OutputProcedureCache = 0 ,
    @CheckProcedureCacheFilter = NULL,
    @CheckServerInfo = 1

@Version = '5.4'; @VersionDate = '20170603' 

**I get following error:**

_Msg 19050, Level 16, State 1, Procedure sp_Blitz, Line 10481
Trace file name '' is invalid.
The statement has been terminated.
Msg 19050, Level 16, State 1, Procedure sp_Blitz, Line 10696
Trace file name '' is invalid.
The statement has been terminated._

SQL Server: Microsoft SQL Server 2014 (SP2-CU4) (KB4010394) - 12.0.5540.0 (X64) 
OS: Windows 2012 R2 (Build 9600)

**Comment by BrentOzar** [comment]
Yeah, that can happen if you've deleted the default trace file output. I'd advise against doing that. ;-)

**Comment by gjschipper** [comment]
Hmmm, I don't get you. What do you mean with deleted the default trace output?

**Comment by BrentOzar** [comment]
There's a default trace file, and someone deleted it. (This is beyond something I can explain fast - your best bet here is Google.)

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws
