### ISSUE TITLE
sp_BlitzQueryStore - executing with a @StoredProcName value and NULL dates returns an error message

### ISSUE THREAD

**Issue by dcurlewis** [BrentOzarULTD/SQL-Server-First-Responder-Kit#934]
**What is the current behavior?**
Calling sp_BlitzQueryStore with a stored procedure name specified (using the `@StoredProcName` parameter) while leaving default (NULL) values for `@StartDate` and/or `@EndDate` causes no results to be returned, and a custom error is thrown instead:

> We couldn't find the Stored Procedure [<stored_proc_name>] in the Query Store views for [<database_name>] between 2017-05-31 00:00:00.0000000 and 2017-06-07 23:27:35.6943627. Try removing schema prefixes or adjusting dates. If it was executed from a different database context, try searching there instead.

**To reproduce**
*This doesn't work:*
`EXEC sp_BlitzQueryStore @DatabaseName = 'StackOverflow', @Top = 1, @StoredProcName = 'UserReportExtended'`

*While this does work (obviously provided you have data in this date range for this specific proc)*
`EXEC sp_BlitzQueryStore @DatabaseName = 'StackOverflow', @Top = 1, @StoredProcName = 'UserReportExtended', @StartDate = '20170601', @EndDate = '20170608';`

**sp_BlitzQueryStore Version:** 1.4

**Proposed Solution**
The issue seems to be that since no default values are assigned to `@StartDate` or `@EndDate` when they're NULL, then when we get to [this query](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzQueryStore.sql#L740), the values passed to `@sp_StartDate` and `@sp_EndDate` (on line 748) will still be NULL.  

A possible fix could be adding something like this just before the execute at line 746:
```
	IF @StartDate IS NULL SET @StartDate = DATEADD(DAY, -7, SYSDATETIME());
	IF @EndDate IS NULL SET @EndDate = SYSDATETIME();
```

**Comment by BlitzErik** [comment]
I see a way to fix this to keep it in line with the way the rest of the proc works. We're not using the dynamically created `WHERE` clause here, when we should be. I don't know why I did it this way. There's no need to declare a separate set of parameters or force in values we're not using. I'll take care of this in the next couple days.

```
IF @StoredProcName IS NOT NULL
	BEGIN 
	
	DECLARE @proc_params NVARCHAR(MAX) = N'@sp_StartDate DATETIME2(7), @sp_EndDate DATETIME2(7), @sp_StoredProcName NVARCHAR(128), @i_out INT OUTPUT';
	
	SET @sql = N'SELECT @i_out = COUNT(*) 
				 FROM ' + QUOTENAME(@DatabaseName) + N'.sys.query_store_query qsq 
				 WHERE object_name(qsq.object_id, DB_ID(' + QUOTENAME(@DatabaseName, '''') + N')) = @sp_StoredProcName 
				 AND qsq.last_execution_time >= @sp_StartDate
				 AND qsq.last_execution_time < @sp_EndDate';
	
	EXEC sys.sp_executesql @sql, 
						   @proc_params, 
						   @sp_StartDate = @StartDate, @sp_EndDate = @EndDate, @sp_StoredProcName = @StoredProcName, @i_out = @out OUTPUT;
```
