### ISSUE TITLE
sp_DatabaseRestore -- Rename datafiles when using @RestoreDatabaseName

### ISSUE THREAD

**Issue by akrohn** [BrentOzarULTD/SQL-Server-First-Responder-Kit#935]
Using version 5.4 from 20170603 and wanted to restore to a new database on a different server for testing purposes and used @RestoreDatabaseName for the new name. 

**What is the current behavior?**
The procedure uses the original naming for the datafile. 

**What is the expected behavior?**
If one wants a new name for the database, the datafiles should be renamed too. So you can restore the same backup many times on the same server for different test purposes.

Got a diff for the changes I made to use the new database name for the datafiles too. Currently I got no git on the system. Hope with the diff it's easy too.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Using SQL Server 2016.

Hope this helps.

Cheers,
Andreas

DIFF:

```
--- D:\Projekte\assets\SqlServer\FirsResponderKit\sp_DatabaseRestore.sql
+++ D:\Projekte\Roq\xitavis\Datenbank\Backup\sp_DatabaseRestore.sql
@@ -213,16 +213,32 @@
 
 IF @MoveFiles = 1
 BEGIN
-	WITH Files
-    AS (
-		SELECT ',MOVE '''+LogicalName+''' TO '''+
-			CASE
-				WHEN Type = 'D' THEN @MoveDataDrive
-				WHEN Type = 'L' THEN @MoveLogDrive
-			END+REVERSE(LEFT(REVERSE(PhysicalName), CHARINDEX('\', REVERSE(PhysicalName), 1)-1)) +'''' AS logicalcmds
-		FROM #FileListParameters)
-	SELECT @MoveOption = @MoveOption + logicalcmds
-	FROM Files;
+	IF @RestoreDatabaseName IS NOT NULL
+	BEGIN
+		WITH Files
+		AS (
+			SELECT ',MOVE '''+LogicalName+''' TO '''+
+				CASE
+					WHEN Type = 'D' THEN @MoveDataDrive + @RestoreDatabaseName + '.mdf'
+					WHEN Type = 'L' THEN @MoveLogDrive + @RestoreDatabaseName + '.ldf'
+				END + '''' AS logicalcmds
+			FROM #FileListParameters)
+		SELECT @MoveOption = @MoveOption + logicalcmds
+		FROM Files;
+	END
+	ELSE
+	BEGIN
+		WITH Files
+		AS (
+			SELECT ',MOVE '''+LogicalName+''' TO '''+
+				CASE
+					WHEN Type = 'D' THEN @MoveDataDrive
+					WHEN Type = 'L' THEN @MoveLogDrive
+				END+REVERSE(LEFT(REVERSE(PhysicalName), CHARINDEX('\', REVERSE(PhysicalName), 1)-1)) +'''' AS logicalcmds
+			FROM #FileListParameters)
+		SELECT @MoveOption = @MoveOption + logicalcmds
+		FROM Files;
+	END;
 END;
 IF @ContinueLogs = 0
 BEGIN



```

**Comment by BrentOzar** [comment]
Thanks for the code contribution. However, next time, check the Contributing.md guide on how to contribute first - you'll want to file an issue before you start coding, and the community can discuss the change you're proposing.

In this case, I do like the idea of what you're proposing, but I've got a few questions.

- Does the user need to know to set certain parameters for it to work? For example, can they set a new name, but forget to set @MoveFiles = 1? Should MoveFiles be turned on automatically if necessary?
- If the database's name isn't in the file name, will it still work? (For example, if the database is named Accounting, but the files are named acctng.mdf and acctng.ldf, will it still work?)
- What's the reverse/left/reverse stuff doing? (Let's document our code so others can understand what we're doing)

Thanks!

**Comment by BlitzErik** [comment]
@BrentOzar -- are we keeping this one open?

**Comment by BrentOzar** [comment]
Good question - nah, if @akrohn hasn't answered in a month, let's close it. @akrohn, if you want to give it another shot, file an issue with what you want to do, and let's discuss it as a community first. Thanks though!
