### ISSUE TITLE
sp_DatabaseRestore - Restore to Availability Group

### ISSUE THREAD

**Issue by GregWhiteDBA** [BrentOzarULTD/SQL-Server-First-Responder-Kit#939]
Feature request
currently restores database to single server, would be amazing if we could restore to an availability group name. Included adding to secondary and joining when running recovery.

**Comment by BrentOzar** [comment]
Why not use direct seeding?

**Comment by BlitzErik** [comment]
I'm assuming this is for sp_DatabaseRestore?

**Comment by BrentOzar** [comment]
Greg - is there a reason you don't want to use direct seeding? 

(I'm playing devil's advocate here - if you can speak up about that, go for it - we're not likely to code this feature, but if you can create a compelling case for it, other volunteers might step up if you don't want to.)

**Comment by BlitzErik** [comment]
Removing milestone until we hear back from @GregWhiteDBA

**Comment by BlitzErik** [comment]
Closing, no response.

**Comment by GregWhiteDBA** [comment]
@BrentOzar @BlitzErik because I'm using sql 2012.... (sad face)

now i think about it its actually usable as it is just run  the same script on all your replicas then manually add to AG.
