### ISSUE TITLE
Easier installation script

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#949]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
As we've grown to more scripts, it's gotten to be more painful to install all of them.

**What is the expected behavior?**
Create a single script that will install the rest, and we can put this in the First Responder Kit download. Would be really nice to have this built as part of an automated build process, too, I guess - I would rather not have to do the copy/paste boogie and gamble that I missed something. (We could do it manually as part of the release process, though, just worried about errors.)

**Comment by BlitzErik** [comment]
This is dumb easy with the `COPY` cmd

`copy *.sql Install-All-Scripts.sql`

**Comment by BlitzErik** [comment]
I think it might be smart to have a couple sets though. Some people will just want the 'core' scripts, others may want the full suite.

**Comment by BrentOzar** [comment]
Yeah, I like that. One set with sp_Blitz*, and one set with all?

**Comment by BlitzErik** [comment]
Yeah. 

![image](https://user-images.githubusercontent.com/11590415/27331680-80ef1a5a-558c-11e7-809f-d979c4bd0377.png)

Wonder if the PowerShell crowd has an easier solution? ;)

**Comment by BrentOzar** [comment]
Does it actually run? Wondering if all of the scripts have GO at the end.

**Comment by BlitzErik** [comment]
There are a few minor issues. GO isn't one of them. Heh.

Msg 102, Level 15, State 1, Procedure sp_BlitzBackups, Line 1515 [Batch Start Line 6650]
```
Incorrect syntax near 'GOSET'.
Msg 102, Level 15, State 1, Line 12750
Incorrect syntax near '»'.
Msg 154, Level 15, State 1, Procedure sp_BlitzQueryStore, Line 3637 [Batch Start Line 19671]
a USE database statement is not allowed in a procedure, function or trigger.
```

**Comment by BlitzErik** [comment]
The weirdest one is between BlitzCache and BlitzFirst:

![image](https://user-images.githubusercontent.com/11590415/27331910-98aa7ad0-558d-11e7-9e85-eecc8fe4fb53.png)

I have no idea where those weird chars are coming from.

**Comment by BlitzErik** [comment]
Ah, so, sp_BlitzFirst was saved using a weird encoding (maybe a Mac thing?) -- changed that and it cooks up fine.
