### ISSUE TITLE
sp_AllNightLog_Setup - make idempotent (repeatable)

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#952]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
If you run sp_AllNightLog_Setup twice, it fails. It doesn't detect the existence of some components.

**What is the expected behavior?**
It should only install components (database, tables, jobs) that don't already exist.

**Comment by BlitzErik** [comment]
This is closed in #936
