### ISSUE TITLE
sp_AllNightLog - add ability to skip databases

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#958]
**Do you want to request a *feature* or report a *bug*?**
Feature. (Low priority, doesn't have to make launch, I just keep running into this in the lab.)

**What is the current behavior?**
All backups and restores are driven by the backup_configuration and restore_configuration tables.

**What is the expected behavior?**
Give the DBA the ability to skip certain databases.

My first thought is to add a msdbCentral.dbo.backup_worker.rpo_override and msdb.dbo.restore_worker.rto_override field. If it's -1, don't do backups or restores. This way, the poll processes will still pick up the database once, but then the DBA can set their override fields to -1, and we can skip those databases in AllNightLog.

The short term answer is to put those databases in simple recovery model.

**Comment by BlitzErik** [comment]
This was definitely on my mind when i designed things. All of the worker tables have a `database_name` field that's only populated by `all` right now. Down the line, I'd like to get more configuration options in there, and update the `update` part of `setup` to change configs for individual databases.

**Comment by BrentOzar** [comment]
Thinking - if #1000 means we need to add full_restore_required and diff_restore_required fields to msdb.dbo.restore_worker, then maybe we add an ignore_database bit field, default 0.

**Comment by BrentOzar** [comment]
I added the table fields, but that was it. No logic built in yet. Just wanted to get this in for other tickets.

**Comment by BrentOzar** [comment]
We're no longer actively using this ourselves in production, so closing the issue. If the folks using it in production wanna pursue it, they can check in their changes & move forward. I wouldn't wanna make further changes on this branch knowing that there are other active versions of the code out there.
