### ISSUE TITLE
sp_AllNightLog @Restore = 1 - add minimum file name or LSN feature

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#960]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
sp_AllNightLog @Restore = 1 runs RESTORE HEADERONLY for all log files found in the logs folder. This will take some time on servers with hundreds of databases, thousands of backup files.

**What is the expected behavior?**
Not sure yet, but logging this so we have a work item for it.

**Comment by BlitzErik** [comment]
OOH, I see!
I tried to do that in the cursor section:

![image](https://user-images.githubusercontent.com/11590415/27356902-4cfdbd44-55de-11e7-88ac-572c7ee4f1f5.png)

We could just delete from the `@FileList` table any dates prior to that. 

Right now, `@OnlyLogsAfter` gets fed into `sp_DatabaseRestore` from `sp_AllNightLog` _per database_, by looking at `last_log_restore_start_time`, formatting it, and assigning it to `@only_logs_after` (along with `@database_name`, etc. 

This should be a simple change!
