### ISSUE TITLE
sp_Blitz - sys.fn_trace_gettable Failure

### ISSUE THREAD

**Issue by RichBenner** [BrentOzarULTD/SQL-Server-First-Responder-Kit#962]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If you've been messing about with your trace files then sys.fn_trace_gettable is going to fail. Because we don't have error catching then the whole of sp_Blitz fails.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
Delete one of the older trace files, to test you can use this extract of the code for testing;

DECLARE @base_tracefilename NVARCHAR(500),@curr_tracefilename NVARCHAR(500),@indx int

select @curr_tracefilename = [path] from sys.traces where is_default = 1 ;
set @curr_tracefilename = reverse(@curr_tracefilename);
select @indx = patindex('%\%', @curr_tracefilename) ;
set @curr_tracefilename = reverse(@curr_tracefilename) ;
set @base_tracefilename = left( @curr_tracefilename,len(@curr_tracefilename) - @indx) + '\log.trc' ;

BEGIN TRY
SELECT * FROM sys.fn_trace_gettable(@base_tracefilename, DEFAULT)
END TRY
BEGIN CATCH
SELECT 'Yep, its broken'
END CATCH

**What is the expected behavior?**
It would be nice if failure didn't result in the whole of sp_Blitz failing

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
I believe it's always going to have been a problem. People messing with trace files transcends SQL Server versions.

**Comment by BlitzErik** [comment]
Is there an `IF EXISTS` code block we could use here instead? What I'd ideally like to do is:

If there's a trace file analyze it
If there's no trace file, warn that someone has removed a trace file

**Comment by RichBenner** [comment]
Hi Erik 

My first instinct was a TRY CATCH block but I'll see if I can work out an IF EXISTS solution too. 

I've noticed that fn_trace_gettable is used in quite a few places, and later in the code the data is inserted into a temp table and then used in quite a few other checks. Because of this, perhaps having a parameter at the beginning to skip these if the query on fn_trace_gettable returns an error might perform better. Do you have a preference for that?

**Comment by BlitzErik** [comment]
Oh, yeah, no sense in checking repeatedly for the same thing if it fails, or risking more failures.  This wouldn't be a user-exposed skipping option though, it would have to happen in code (aside from the normal ability to configure skip checks).

Let me know if you get stuck on anything.

Thanks!

**Comment by dtodd2016** [comment]
Just to update a few things (from #978 above which is now closed), I tried v5.4 across 8 SQL 2014 instances, and got the same error results - twice for one run. As this was the daily check I do, it was skipping a few checks, and the results seemed to be okay in spite of this error.
Really not sure if the trace files have been monkeyed with on these servers - they are fairly vanilla installs of standard edition, so the default trace should be in and working. On that score I was surprised to see this as an issue for me.

**Comment by BlitzErik** [comment]
You can run this on any of those servers to check. This is what we look for.

```
SELECT [path]
FROM   sys.traces
WHERE  is_default = 1
```

**Comment by dtodd2016** [comment]
BlitzErik: That query works and returns valid paths. I don't think I'm free to share the results in this forum unless I obfuscate the server names and some of the path ...

**Comment by BlitzErik** [comment]
@dtodd2016 you don't even have to do that! The variable that we store the file name in is `@base_tracefilename`. 

If you ctrl+f for that, you should hit this block of code:
```
BEGIN
		select @curr_tracefilename = [path] from sys.traces where is_default = 1 ;
		set @curr_tracefilename = reverse(@curr_tracefilename);
		select @indx = patindex('%\%', @curr_tracefilename) ;
		set @curr_tracefilename = reverse(@curr_tracefilename) ;
		set @base_tracefilename = left( @curr_tracefilename,len(@curr_tracefilename) - @indx) + '\log.trc' ;
END
```
I bet the issue is in there. Not sure if adding some PRINTs in would help. You can if you want, though.

Can you let me know if this code produces the correct path?

```
DECLARE @path NVARCHAR(260);

SELECT @path = REVERSE(SUBSTRING(REVERSE(path), CHARINDEX('\', REVERSE(path)), 260)) + N'log.trc'
FROM   sys.traces
WHERE  is_default = 1;

PRINT @path
```

**Comment by dtodd2016** [comment]
@BlitzErik 
Yes, your code snippet produces the correct path.

And given suitable declares and output, the begin-end block also works perfectly.

**Comment by BlitzErik** [comment]
@dtodd2016 -- cool, thanks!

@RichBenner -- do you still want to code this?

**Comment by RichBenner** [comment]
I'm happy to finish this, I just wanted to see where this conversation went :)

I'll have a pull request in by tomorrow.

**Comment by BlitzErik** [comment]
Woohoo! Thanks Rich!

**Comment by RichBenner** [comment]
Sorry, got swamped at work, jumping on this one today.

**Comment by BlitzErik** [comment]
@RichBenner if this is a hassle for you (totally understand if it is), I'll jump on it this week. Thanks!

**Comment by RichBenner** [comment]
@BlitzErik yeah, sorry about the delay buddy, things got pretty crazy here. I've just put in a pull request that fixes the issue, let me know if anything needs changing.
