### ISSUE TITLE
sp_BlitzQueryStore -- Don't use TRY_CONVERT if database compat level is under 110

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#969]
Big questions:
Do we even need `TRY_CONVERT` here? 
Can we just use regular `CONVERT` instead?
What are the odds that malformed XML is in the table?
Will this be wonky in Azure?

**Comment by wrgarner** [comment]
@BlitzErik: I changed the TRY_CONVERT to CONVERT as you suggested and the error no longer occurs. I am getting results from sp_BlitzQueryStore. It'll be a while before I can review the results in detail, but I have no reason to believe there's a problem. Thanks for your help!

**Comment by BlitzErik** [comment]
Cool, so I'm going to hold off on making any changes to the proc until you have some additional info on what's going on there. Are you cool with changing that one part for new releases?

**Comment by wrgarner** [comment]
I hesitate to suggest anything about what you should do with your releases. I'm one oddball user. I can certainly make the same edit in the future if necessary.

**Comment by BlitzErik** [comment]
@wrgarner hahaha, that makes you one of two verified users, so...!

I really would love more info on what's going on there -- seems weird if that's the only thing failing. Let me know what else you run into. If anything weird comes up, open a new issue here. I'm going to close this one out to get ready for this month's release.

Thanks!
