### ISSUE TITLE
Potential issue when setting row_count, reserved_MB, reserved_LOB_MB as NOT NULL

### ISSUE THREAD

**Issue by SQLNoobie** [BrentOzarULTD/SQL-Server-First-Responder-Kit#970]
Potential bug. I am using version 5.4

**What is the current behavior?**

After installing the script and attempting to run on our DB we get a series of 4 errors which can be fixed one-by-one by adjusting the script to remove the NOT NULL requirement from the following 4 columns.

              row_count BIGINT NULL ,
              reserved_MB NUMERIC(29,2) NULL ,
              reserved_LOB_MB NUMERIC(29,2) NULL ,
              reserved_row_overflow_MB NUMERIC(29,2) NULL ,

What I am using to invoke the SP:
exec dbatools..sp_blitzindex @databasename = 'MyDB'

Example Output:
Msg 50000, Level 16, State 2, Procedure sp_BlitzIndex, Line 1427 [Batch Start Line 1]
MyDB database failed to process. Cannot insert the value NULL into column 'reserved_row_overflow_MB', table 'tempdb.dbo.#IndexPartitionSanity_______________________________________________________________________________________________00000007577D'; column does not allow nulls. INSERT fails.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Our SQL Server version is 13.0.4001.0. Latest Windows Server AMI from AWS (64bit).

**Comment by BlitzErik** [comment]
This sort of thing tends to happen when you're creating and dropping tables or indexes while the proc runs. Is that known app behavior?

**Comment by BlitzErik** [comment]
Closing, no response.

**Comment by SQLNoobie** [comment]
We don't drop tables or indexes very often with the exception of #temp tables.  I've tried running the script during low-activity/after hours and it generates the same errors.  Any ideas you can offer for me to do further research?

**Comment by BrentOzar** [comment]
No, sorry, this isn't something we can easily troubleshoot remotely. Try running it in a non-used database - go create a fresh database from scratch, run it on that database, and you'll notice that you don't get the error there. That's your first indication that it's due to adding/dropping tables/indexes during your workloads.
