### ISSUE TITLE
sp_BlitzIndex shows same create date for all indexes

### ISSUE THREAD

**Issue by gbargsley** [BrentOzarULTD/SQL-Server-First-Responder-Kit#973]
This is a bug I believe.

When I run the following code I get the same create date for all indexes even though I just added the one I am trying to check on.
`DECLARE @VersionDate DATETIME;
EXEC dbo.sp_BlitzIndex @DatabaseName = N'NLS_Rise', -- nvarchar(128)
    @SchemaName = N'dbo', -- nvarchar(128)
    @TableName = N'cif_detail', -- nvarchar(128)
    @VersionDate = @VersionDate OUTPUT -- datetime`

SQL 2014 and Windows 2012 R2

**Comment by BlitzErik** [comment]
Howdy,

I just checked on my end, and I can reproduce it. Thanks for letting us know, we'll dig into it.

**Comment by BlitzErik** [comment]
So, I did some testing. and this is not a sp_BlitzIndex bug. The create_date column seems to update to whenever you created the last index.

![image](https://user-images.githubusercontent.com/11590415/28086529-599ec924-664d-11e7-9c17-c733a8753937.png)

I'd check Connect, and maybe file an item over there.
