### ISSUE TITLE
sp_AllNightLog_Setup -- Should have a cleanup mode

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#975]
Might be annoying, but we should have a mode to get rid of everything that gets created

- Agent Jobs
- Job Schedules
- msdbCentral
- Tables in msdb
- I think that's it!

**Comment by BrentOzar** [comment]
Unassigning myself again. Every time I think, "I can knock this out in no time," it turns out to be quite a bit of time.

**Comment by BrentOzar** [comment]
I don't think you really wanna do this - closing it.
