### ISSUE TITLE
sp_BlitzCache and sp_BlitzQueryStore -- Alert Paul White if you find a Switch operator

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#976]
[JEAGL](http://sqlblog.com/blogs/paul_white/archive/2013/06/11/hello-operator-my-switch-is-bored.aspx)

**Comment by BlitzErik** [comment]
![image](https://user-images.githubusercontent.com/11590415/28248267-f3f654ae-6a0f-11e7-8d7a-d473d67b3b5e.png)

**Comment by TooMuchBlue** [comment]
The link in the first comment is broken.  It looks like it moved here: https://www.sql.kiwi/2013/06/hello-operator-my-switch-is-bored.html

(I followed links from sp_BlitzCache and brentozar.com to find this.)
