### ISSUE TITLE
sp_DatabaseRestore - Error restoring database where name starts with numeric character

### ISSUE THREAD

**Issue by TheUsernameSelectionSucks** [BrentOzarULTD/SQL-Server-First-Responder-Kit#977]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
We have one database where the the first character of the name is numeric. The restore script will cause an error and not restore.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
Create a database with a name where the first character is numeric, for example `CREATE DATABASE [2two]`.
Back-up database
Try to restore database

**What is the expected behavior?**
We have added the step  `SET @Database = QUOTENAME(@Database)`. This works fine for our needs. May also have to do this with the variable `@RestoreDatabaseName`, but we are not currently using that variable in our restores.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

SQL Server 2016

**Comment by BlitzErik** [comment]
Howdy,

Interesting catch! Can you let me know where in the proc you `SET @Database = QUOTENAME(@Database)`? Just want to make sure it's not messing anything up down the line.

Thanks!

**Comment by TheUsernameSelectionSucks** [comment]
Thanks, Erik. We have it right after `SET @VersionDate` at the beginning of the proc.

**Comment by BlitzErik** [comment]
Cool -- since you're in a position to test this, can you give it a spin using `@RestoreDatabaseName` too to see if it also needs the `QUOTENAME()` treatment? 

Thanks!

**Comment by TheUsernameSelectionSucks** [comment]
It looks like it does as well. I gave it a try on the test database and it gave me an error. I added `SET @RestoreDatabaseName = QUOTENAME(@RestoreDatabaseName)` right below the `SET @Database = QUOTENAME(@Database)` (which is below `SET @VersionDate`) and it seems to work.

**Comment by BlitzErik** [comment]
Awesome! Thanks! Do you want to add the code changes for this?

**Comment by TheUsernameSelectionSucks** [comment]
Sure. I won't be able to get to it today, but should tomorrow.


-------- Original Message --------
Subject: Re: [BrentOzarULTD/SQL-Server-First-Responder-Kit]
sp_DatabaseRestore - Error restoring database where name starts with
numeric character (#977)

**Comment by TheUsernameSelectionSucks** [comment]
When I try publishing the changes, I get an error messages saying "Sync failed to push local changes"
![capture](https://user-images.githubusercontent.com/26902750/27746790-27111a88-5d8e-11e7-8214-19c90c60df87.JPG)

**Comment by BlitzErik** [comment]
Yeah, not just anyone can push code in whenever.

Check out these posts for detailed instructions: 

https://www.brentozar.com/archive/2015/07/pull-request-101-for-dbas-using-github/

https://www.brentozar.com/archive/2016/07/contribute-code-sql-server-first-responder-kit-github/

With a client today and can't troubleshoot all the steps.

Thanks!

**Comment by TheUsernameSelectionSucks** [comment]
It seems like there's conflicting information between the two articles. If the "contribute" article, it says to commit then publish (Step 6). In the "101" article, it says to comment, the do a pull request (Step 3). I did that and got the same error when submitting the pull request.

I totally understand about being at the client. No rush on my part.

**Comment by TheUsernameSelectionSucks** [comment]
Hey Erik, any direction on this?

**Comment by BrentOzar** [comment]
Brent here - sorry, those articles are for when you're a contributor on the project. For someone else's project, check this out:

https://www.brentozar.com/archive/2017/06/ola-hallengrens-maintenance-scripts-now-github/

We can't really do personal Github support (there's just limits about how many hours per day there are, dagnabbit) but check into that post and go from there. Thanks!

**Comment by BlitzErik** [comment]
@TheUsernameSelectionSucks I'm going to call this one a day with this code:

```
IF @RestoreDatabaseName IS NULL
	BEGIN
		SET @RestoreDatabaseName = QUOTENAME(@Database);
	END
ELSE
	BEGIN
		SET @RestoreDatabaseName = QUOTENAME(@RestoreDatabaseName)
	END
```

Is this equivalent to what you did, or were there more changes that had to be made?

Thanks,
Erik

**Comment by BlitzErik** [comment]
Looking a bit further down, it looks like that will break this query:

```
		SELECT @DatabaseLastLSN = CAST(f.redo_start_lsn AS NUMERIC(25, 0))
		FROM master.sys.databases d
		JOIN master.sys.master_files f ON d.database_id = f.database_id
		WHERE d.name = @RestoreDatabaseName AND f.file_id = 1;
```

**Comment by TheUsernameSelectionSucks** [comment]
Thanks, Eric. I've been out of town and away from the computer.


-------- Original Message --------
Subject: Re: [BrentOzarULTD/SQL-Server-First-Responder-Kit]
sp_DatabaseRestore - Error restoring database where name starts with
numeric character (#977)
