### ISSUE TITLE
sp_Blitz - trace file '' isn't valid

### ISSUE THREAD

**Issue by dtodd2016** [BrentOzarULTD/SQL-Server-First-Responder-Kit#978]
I've just upgraded from v5.2 (201704506) of sp_Blitz to v5.4 (20170701).

I've then gotten:
And then I get this error:
odc2db0005\irep_test(ORORAGROUP\admin.davitod): Msg 19050, Level 16, State 1, Procedure sp_Blitz, Line 3863
Trace file name '' is invalid.
odc2db0005\irep_test(ORORAGROUP\admin.davitod):
The statement has been terminated.
odc2db0005\irep_test(ORORAGROUP\admin.davitod): Msg 19050, Level 16, State 1, Procedure sp_Blitz, Line 4078
Trace file name '' is invalid.
odc2db0005\irep_test(ORORAGROUP\admin.davitod):
The statement has been terminated.

Comparing the different versions of the code, this test appears to have been introduced in v5.3. Do these code blocks need a test for skipchecks - its noted that the first is completely outside a skipcheck check, so I can't just skip this test.

My immediate fix has been to revert to v5.2

**Comment by BlitzErik** [comment]
Howdy!

Thanks for letting us know. We already have an issue in flight for this here: #962 

Keep an eye on that one for updates!

Thanks!

**Comment by dtodd2016** [comment]
Thanks
