### ISSUE TITLE
sp_BlitzQueryStore should be removed (or conditional install) from Install_Core_Blitz.sql

### ISSUE THREAD

**Issue by beckmanjm** [BrentOzarULTD/SQL-Server-First-Responder-Kit#979]
Install_Core_Blitz from 20170701

**What is the current behavior?**
Install_Core_Blitz.sql installs sp_BlitzQueryStore even though it is only valid on SQL Server 2016 and above, which constitutes a very small portion of the users. Either a useless SP is installed or users must build a new script to exclude it.

**What is the expected behavior?**
sp_BlitzQueryStore either should not be in the "core" script or, if possible, the SP should only install on 2016+ instances.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All below 2016.

**Comment by BlitzErik** [comment]
Will add a script command to ignore BQS.
