### ISSUE TITLE
sp_AllNightLog_Setup: Does not create objects or jobs

### ISSUE THREAD

**Issue by jstanford-kcura** [BrentOzarULTD/SQL-Server-First-Responder-Kit#987]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Running the command with normal parameters does nothing.  No debug output, no database or jobs created, etc.

Simplest possible repro code:
EXEC [master].[dbo].[sp_AllNightLog_Setup] @RPOSeconds = 30,
										@RTOSeconds = 30,
										@BackupPath = @BackupPath,
										@RestorePath = @BackupPath,
										@Jobs = 10,
										@RunSetup = 1,
										@Debug = 1;

**What is the expected behavior?**
Jobs + database created.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL: 2016 SP1 Standard
OS: 2012R2

**Notes**
The issue seems to be caused around line 285.

If dm_server_services exists, the ELSE block after it will never execute.  The ELSE block is where all the work is actually done.

**Comment by BrentOzar** [comment]
Fixed! Accidentally checked directly into dev branch. (facepalm)
