### ISSUE TITLE
sp_AllNightLog_Setup - add separate setups for backup, restore, or both

### ISSUE THREAD

**Issue by jstanford-kcura** [BrentOzarULTD/SQL-Server-First-Responder-Kit#988]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
On a dedicated secondary/replica, the MSDBCentral database is created, but never used.  Recommendation is to drop it post-setup, to allow the jobs to start restoring the database.

From https://www.brentozar.com/sp_allnightlog/ :
`The msdbCentral database is created by sp_AllNightLog_Setup, but on secondaries, you’ll probably want to drop the empty msdbCentral database and restore it from the primary.`

**What is the expected behavior?**
Ideally, there would be a flag to specify that the jobs are being setup for primary or secondary.  If secondary, skip the database creation entirely.

**Comment by BrentOzar** [comment]
(Just to make a scope note - this won't be v1, but I agree that it'd be cool to have.)

**Comment by BrentOzar** [comment]
Thinking through how to code this - we probably need to split @RunSetup BIT = 0 into two different parameters: @SetupBackups BIT = 0 and @SetupRestores BIT = 0.

**Comment by jstanford-kcura** [comment]
If you do add flags for setting up backups and restores, could we extend that to also enabling the jobs of the appropriate type?

**Comment by BlitzErik** [comment]
I had it all in one to make things easier on a secondary, since it could become a primary at any time. 

It's not ideal, but splitting it adds another manual step. It might be a good idea to include this as part of a failover process (which I assume is getting coded in these, somewhere.

**Comment by jstanford-kcura** [comment]
My thought: the options to setup for backup xor restore don't change which jobs/objects are created, except for the database itself.  It'll still create restore jobs on the primary, and backup jobs on the secondary.

Failover will activate the relevant components as necessary, but on initial setup, they wouldn't get activated.

**Comment by BrentOzar** [comment]
Tweaking based on our in-person discussions - @RunSetup = 1 should still be a thing, but just add parameters for @EnableBackupJobs = 1 and @EnableRestoreJobs = 1, and don't allow them to turn both on.

**Comment by BrentOzar** [comment]
Ugh, I need help. @EnableBackupJobs and @EnableRestoreJobs won't work - if people run it with zero for either of those, they're going to assume that the jobs will be disabled. What should we do instead?

**Comment by BlitzErik** [comment]
Why not have flags for `@IsPrimary` or `@IsSecondary` and handle expectations based on that instead? 

You'd only need one, and it would change the behavior based on 1/0. There's no need for a third option.

**Comment by BrentOzar** [comment]
Because we might just set one up without any enabled jobs. (That's what I do for testing, for example.)

**Comment by BlitzErik** [comment]
Wouldn't that be covered if it's `NULL`?

**Comment by BrentOzar** [comment]
LISTEN I'M CODING NOW LEAVE ME ALONE

**Comment by BrentOzar** [comment]
Done, and added notes on the documentation page: 
https://www.brentozar.com/sp_allnightlog/
