### ISSUE TITLE
sp_BlitzBackups include sysdatabases when using @PushBackupHistoryToListener

### ISSUE THREAD

**Issue by jfoudy** [BrentOzarULTD/SQL-Server-First-Responder-Kit#990]
**Do you want to request a *feature* or report a *bug*?**
Feature Request

**What is the current behavior?**
Currently only pushes the msdb..backupset table to AG or Linked server.  This provides only what backups have been made, but say a new database is added to a server and never gets backed up, then there is no way to know it is missing from the backups.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

**What is the expected behavior?**
Would also have the push to include the master..sysdatabases table as well.  

Basically here is what I'm looking to do across our enterprise.  All of our servers in multiple locations will push information to a central location.  I would like to run a report that will check to make sure all databases on that servers have a recent full/diff backup in the past 1 day and transaction log backup in the last 20 minutes.

Currently because they push doesn't include the sysdatabases table there is no way to tell if a user added a new database and it didn't get backed up with the servers backup rules.

Currently I can run the following two queries on a server to report on this information.  If rows are returned then I know that I need to look into why I don't have a backup for a given database.  It would be nice to be able to run a similar report against a central database to report on all of our SQL instances at once.

On a new server to quickly figure out if backups are running I can run two queries:
SELECT ‘No Full backup in last 1 day’, MAX(ISNULL(DATEDIFF(dd,ISNULL(b.backup_start_date, ’01/01/1900′),GETDATE()),0)) AS ‘NumDays’
, d.name as ‘DBName’
FROM master..sysdatabases d
LEFT JOIN msdb..backupset b ON d.name = b.database_name
AND b.backup_start_date = (SELECT MAX(backup_start_date)
FROM msdb..backupset b2
WHERE b.database_name = b2.database_name AND b2.type IN (‘D’,’I’))
WHERE d.name != ‘tempdb’
–AND d.name NOT IN (SELECT db_name FROM dbautility.dbo.db_exclude)
AND DATABASEPROPERTYEX(d.name, ‘Status’) = ‘ONLINE’
GROUP BY d.name, b.type, b.backup_size
HAVING MAX(ISNULL(DATEDIFF(dd,ISNULL(b.backup_start_date, ’01/01/1900′),GETDATE()),0)) > 1
and
SELECT ‘No Transaction log backup in last 20 mins’, @@servername, MAX(ISNULL(DATEDIFF(hh,ISNULL(b.backup_start_date, ’01/01/1900′),GETDATE()),0)) AS ‘NumDays’
, d.name as ‘DBName’, (select recovery_model_desc from [master].[sys].[Databases] s WITH (NOLOCK) where name = d.name) as ‘Recovery Model’
FROM master..sysdatabases d
LEFT JOIN msdb..backupset b ON d.name = b.database_name
AND b.backup_start_date = (SELECT MAX(backup_start_date)
FROM msdb..backupset b2
WHERE b.database_name = b2.database_name AND b2.type IN (‘L’))
WHERE d.name != ‘tempdb’
–AND d.name NOT IN (SELECT db_name FROM dbautility.dbo.db_exclude)
AND DATABASEPROPERTYEX(d.name, ‘Status’) = ‘ONLINE’
GROUP BY d.name, b.type, b.backup_size
HAVING MAX(ISNULL(DATEDIFF(hh,ISNULL(b.backup_start_date, ’01/01/1900′),GETDATE()),0)) > 20

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2008 R2 and greater.

**Comment by BrentOzar** [comment]
Makes sense. Can you use sys.databases instead of sysdatabases? Just because sysdatabases is deprecated.

In terms of fields, you could push all of them, but at minimum you probably want:

- name
- database_id
- state and/or state_desc (because you may not care if offline databases are backed up)
- recovery_model and/or recovery_model_desc (since you don't wanna check for logs on simple model)

**Comment by BrentOzar** [comment]
(I love this idea by the way!)

**Comment by jfoudy** [comment]
Yes, sys.databases would be fine too. I would say you would want to push all the columns possibly?  Pushing just the minimum you listed would be good for backups, but pushing everything could potentially be helpful for even more reporting across the board.  Like say, hey do I have any databases that have AutoShrink turned on, etc.

Having the recovery model show up in the Transaction log query can alert us to say Production databases that are setup with SIMPLE recovery model and really should get set to a FULL recovery model.  If there are exceptions the centralized reporting I could setup exclusions for a given server/database so that it wouldn't be included in the report.

So for example if I were to see this row returned, then I would want to check that server out and either change the database to Full Model or if we needed to have this setup as Simple for some odd reason, then I can add some filter it out.  My guess is my central database will have a exclusion table for server/databases to exclude.
![backupreport](https://user-images.githubusercontent.com/29755239/27872068-89639fea-6175-11e7-9bee-fa8272dcf221.png)

Also, (at least to my knowledge) we do not use Bulk-Logged recovery models as of now.  So any thoughts you have on how to ensure backups are being done properly in this matter I'd leave it up to you.

**Comment by BrentOzar** [comment]
OK, just to be clear - with your wording in the issue it wasn't quite clear - if you want this to happen, YOU would be the one writing the code. (Not sure if you understood that or not.)

Yep, I agree - that spec looks fine, so you're clear to start coding. (If you didn't want to code it, and you thought we were going to do it, I totally understand - we'll just close the issue.)

**Comment by jfoudy** [comment]
As far as adding the sys.databases to the push I was hoping you guys would do this. 

I can take from there to create our central reporting database.  I'm thinking I would setup Servers table with a list of servers to monitor (example: ServerA, ServerB, ServerC/SQL2008, ServerC/SQL2014).  It could then setup queries/ssrs reports against the backupsets and databases (that are getting info pushed to from the SQL instances) to make sure we have current backups across all SQL instances in the list.

Hopefully you see where I'm going with this.

**Comment by BrentOzar** [comment]
Ah, no, we don't really take requests. (We have day jobs too, heh.) If you need it for your own work, you're welcome to contribute it. Do you want me to assign this to you & leave it open, or close it?

**Comment by jfoudy** [comment]
Ah, ok.  Yes assign to me and leave it open.

**Comment by BlitzErik** [comment]
Going to close this since we haven't heard back from you in a couple months.

If you decide to work on it again in the future, feel free to reopen.

Thanks!
