### ISSUE TITLE
sp_AllNightLog restore jobs do not fail loudly when xp_cmdshell is disabled

### ISSUE THREAD

**Issue by jstanford-kcura** [BrentOzarULTD/SQL-Server-First-Responder-Kit#992]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If xp_cmdshell is disabled, the restore and poll disk jobs fail in a way which does not automatically generate alerts.

**What is the expected behavior?**
The job should fail (generating any configured alerts), and errors should be recorded in msdb..restore_worker.

**Comment by BrentOzar** [comment]
Reopening - need to fix in sp_AllNightLog_Setup too.
