### ISSUE TITLE
sp_AllNightLog: backup and restore jobs are difficult to terminate

### ISSUE THREAD

**Issue by jstanford-kcura** [BrentOzarULTD/SQL-Server-First-Responder-Kit#997]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When disabling a job, either backup or restore, the jobs keep running in the background forever, due to the "WHILE 1=1" loop.  Killing the job requires either restarting the agent service (could we not?), or hunting down every relevant SPID (which is not trivial; how many jobs have WAITFOR in them?).

Failing to kill the jobs properly will result in interesting behavior, since the restore procedures overwrite databases.

**What is the expected behavior?**
Ideally, `WHILE 1=1` can be changed to `WHILE EXISTS(SELECT * FROM msdb.dbo.sysjobs WHERE [enabled] = 1 AND [Name] LIKE 'sp_AllNightLog_Restore_%')` (or similar for backup jobs).

**Comment by BrentOzar** [comment]
For the polling and backup jobs, I coded this so they'll run through the database list once, then check for the disabled jobs. (This makes ad-hoc testing like we're doing easier.)

For the restore jobs, they also run once, BUT if the backup jobs are enabled, then they bail immediately. (Separate issue on that one.)
