### ISSUE TITLE
sp_AllNightLog @Restore = 1 full/log paths hard-coded

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#999]
**Do you want to request a *feature* or report a *bug*?**
Yes

**What is the current behavior?**
In this section of code, we're adding /full and /log to the backup paths:

`SET @restore_path_full = @restore_path_base + N'\' + @database + N'\' + N'FULL\'`

**What is the expected behavior?**
We need to fetch msdb.dbo.restore_configuration's restore path value and check that instead. We may not have `**BACKUPTYPE**` in the dynamic folder path.

**Comment by BlitzErik** [comment]
It looks like this was done in #993, no?

**Comment by BrentOzar** [comment]
Yeah, I believe this is done now, closing.
